### ISSUE TITLE
Request adding rsa_padding support to CertificateRevocationListBuilder.sign()

### ISSUE THREAD

**Issue by amd-isaac** [pyca/cryptography#10006]
As background, support was added for signing X.509 certificates using PSS padding in #8888, by adding the `rsa_padding` kwarg to the `CertificateBuilder.sign()` method. 

When developing applications to be used by certificate authorities using PSS padding, a CA should be able to sign both a newly issued certificate (which #8888 allows us to do) and also a CRL in case the newly issued certificate needs to be revoked later. Can the `rsa_padding` kwarg also be added to the `CertificateRevocationListBuilder.sign()` method to allow a CA to generate a CRL using the same key as was used to build the certificate?

**Comment by alex** [comment]
Yes, this should be doable for our next release.
