### ISSUE TITLE
CryptographyDeprecationWarning: Blowfish has been deprecated

### ISSUE THREAD

**Issue by mss** [pyca/cryptography#10002]
In #6809 a CryptographyDeprecationWarning was introduced for Blowfish. The ticket says

> We plan to deprecate them on a long cycle such that users have a chance to speak up if they have a use case that we should consider.

So I guess this is my chance to speak up.

I will explain our use case below but first of all I think this is first of all a documentation issue: What effect does/will this deprecation have, what will we have to do? We can silence the warning now but will the algorithm removed from cryptography in the future? So we might have to vendor an own implementation or maybe pick one of the alternative implementations available on pypi (a recommendation would be welcome).

Our use case: We deploy a proprietary application via Ansible. The application has a feature which checks the corporate "no plain text passwords stored on disk" requirement. We reverse engineered the algorithm and implemented it as an Ansible filter module which now starts to throw these deprecation warnings. Everybody is aware that this solution is not really secure but it is what we have to live with. Since the solution is security theater anyway we would be fine with switching to another implementation which brings me back to the documentation issue above.

**Comment by reaperhulk** [comment]
Deprecation is intended as a warning prior to removal, so yes, the intention is to eventually remove Blowfish support entirely. We released the first version that deprecated it (37.0.0) in April 2022 so while we don't have an official date it's extremely unlikely we would drop support in 2024.

Given your use case you will probably find it easiest to use a pure Python blowfish implementation since performance and security don't sound like a significant concern. 😄

**Comment by mss** [comment]
Thanks for the quick reply! And indeed, we should be totally fine with another blowfish implementation, we just chose cryptography back in the days because that's already available.

I think the deprecation process could be improved in two ways:
* From the warning it wasn't clear if the deprecation would result in a future removal or was just a hint that continued usage of this algorithm was a pretty bad idea. I'd amend the message from `... has been deprecated` to an explicit `... has been deprecated and will be removed in a future release`
* Googling for the warning still does not bring up a definite answer on this warning so I'd add some information on the deprecation process somewhere in the documentation. Maybe the FAQ or somewhere else.

If you think that's sensible I can create some PRs in that direction.

**Comment by reaperhulk** [comment]
We document our general deprecation policy [here](https://cryptography.io/en/latest/api-stability/#deprecation) but if you have some improved language we'd be happy to review. 😄

**Comment by mss** [comment]
Unfortunately that page does not pop  up when one googles for `CryptographyDeprecationWarning` (since it isn't mentioned). I'd replace `UserWarning` on that page with `CryptographyDeprecationWarning`. I'd say that's the official API and that it is derived from `UserWarning` is just an implementation detail (which might be mentioned if it is relevant).

That and amending the message as mentioned would have had cleared this up for me when I tried to find out what is happening there.
