### ISSUE TITLE
No module named 'cryptography.hazmat.primitives.asymmetric.types'

### ISSUE THREAD

**Issue by kashifzr** [pyca/cryptography#10009]
<pre><font color="#4E9A06"><b>abc@abc-System-Product-Name</b></font>:<font color="#3465A4"><b>~</b></font>$ python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
&gt;&gt;&gt; import cryptography
&gt;&gt;&gt; import do_mpc
Traceback (most recent call last):
  File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/home/abc/.local/lib/python3.8/site-packages/do_mpc/__init__.py&quot;, line 86, in &lt;module&gt;
    import asyncua
  File &quot;/home/abc/.local/lib/python3.8/site-packages/asyncua/__init__.py&quot;, line 13, in &lt;module&gt;
    from .client import Client
  File &quot;/home/abc/.local/lib/python3.8/site-packages/asyncua/client/__init__.py&quot;, line 1, in &lt;module&gt;
    from .client import Client
  File &quot;/home/abc/.local/lib/python3.8/site-packages/asyncua/client/client.py&quot;, line 5, in &lt;module&gt;
    from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes
ModuleNotFoundError: No module named &apos;cryptography.hazmat.primitives.asymmetric.types&apos;
&gt;&gt;&gt; 
</pre>

Do its related to cryptography package as i find error with specific to Module NOT Found Error

**Comment by alex** [comment]
Please provide complete instructions for reproducing in a fresh virtualenv.

**Comment by kashifzr** [comment]
As you see when i run import cryptography in shell, it does works

Name: cryptography
Version: 2.8
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The cryptography developers
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: asyncua

i think this error is due to old version of cryptography but i solved this issue by removing package asyncua

**Comment by alex** [comment]
Yes, 2.8 is far too old. The types module did not exist until 3.4.
