### ISSUE TITLE
No module named 'cryptography' 

### ISSUE THREAD

**Issue by seasighter** [pyca/cryptography#10014]
when I run command on my ec2 server  aws configure it shows "No module named 'cryptography'" even after installing cryptography

I have these versions installed 
awscli               2.9.19
cryptography         38.0.4
pip                  21.3.1
pyOpenSSL            22.1.0

**Comment by reaperhulk** [comment]
Please provide a method to replicate this in a fresh virtual environment.

**Comment by seasighter** [comment]
Is there any other method??

**Comment by seasighter** [comment]
how can I do that please ellaborate , I am not able to understand.

**Comment by reaperhulk** [comment]
Problems like this are almost always related to the environment and not this project. Accordingly, we need a way to replicate this problem ourselves in a minimal way to establish that it isn't a problem with the Python environment you have. In Python this is typically done with virtual environments. If you don't know what those are then I'd suggest doing some research, but we can't provide basic Python assistance like that in this issue tracker.

**Comment by seasighter** [comment]
Ok ,  I will do
