### ISSUE TITLE
PyO3 modules may only be initialized once per interpreter process during fernet encode/decode

### ISSUE THREAD

**Issue by matt-findlay** [pyca/cryptography#10029]
Python 3.11.6

cryptography==41.0.7 installed using pip
cffi==1.16.0
pip 23.3.1

I am trying to use the fernet lib in a temporal worker, and keep getting the following issue due to PyO3 modules being instantiated twice. I do not have this issue on cryptography==3.4.6. It seems that  cryptography needs a guard to stop this module from somehow being instantiated twice.

stacktrace

> File "/crypto_utils.py", line 28, in _decrypt
>     return fernet.decrypt(to_decrypt).decode()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/lib/python3.11/site-packages/cryptography/fernet.py", line 91, in decrypt
>     return self._decrypt_data(data, timestamp, time_info)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/lib/python3.11/site-packages/cryptography/fernet.py", line 152, in _decrypt_data
>     self._verify_signature(data)
>   File "/lib/python3.11/site-packages/cryptography/fernet.py", line 131, in _verify_signature
>     h = HMAC(self._signing_key, hashes.SHA256())
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/lib/python3.11/site-packages/cryptography/utils.py", line 48, in _extract_buffer_length
>     from cryptography.hazmat.bindings._rust import _openssl
>   File "/lib/python3.11/site-packages/temporalio/worker/workflow_sandbox/_importer.py", line 441, in __call__
>     return self.current(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/lib/python3.11/site-packages/temporalio/worker/workflow_sandbox/_importer.py", line 234, in _import
>     mod = importlib.__import__(name, globals, locals, fromlist, level)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1283, in __import__
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 573, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 1233, in create_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> ImportError: PyO3 modules may only be initialized once per interpreter process

**Comment by alex** [comment]
Can you provide a bit more context on what you're doing, are you using sub-interpreters or anything like that?

Alternatively, are you able to reproduce with one of the cp39 wheels from: https://github.com/pyca/cryptography/actions/runs/7256710038

**Comment by alex** [comment]
I will say, I see in your stacktrace you have `workflow_sandbox`, I strongly suspect this is incorrectly attempting to import and re-initization extension modules.
