### ISSUE TITLE
Trying to install cryptography module in Cpanel using python version 3.9 and i am unable to install it 

### ISSUE THREAD

**Issue by sfydeveloper** [pyca/cryptography#10128]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by reaperhulk** [comment]
There’s no information in this report. We need error messages and the information requested in our issue template to be able to assist in any way.

**Comment by sfydeveloper** [comment]
sorry for not providing you with details. I attached error screenshots.

**Comment by reaperhulk** [comment]
There are no screenshots on this issue.

**Comment by sfydeveloper** [comment]
![Picture2](https://github.com/pyca/cryptography/assets/134905253/e88b002c-66ff-408c-8ec9-1eb3b2da09be)
![Picture1](https://github.com/pyca/cryptography/assets/134905253/bed8f8e5-cd6b-4b86-bcb7-09528eba3596)

**Comment by reaperhulk** [comment]
Your installation appears to not have permissions to access the compiler and isn’t selecting a prebuilt wheel. You can try upgrading to the latest pip to see if it will fetch a wheel, but if that doesn’t work you’ll need to figure out why your environment doesn’t have permission to access the installed compiler. That isn’t something we can help with.

**Comment by auracule007** [comment]
please i am also having the same issues here too...How can i fix it?

**Comment by sfydeveloper** [comment]
use VPS or Upgrade your hosting Plan.
