### ISSUE TITLE
CSR loaded from PEM: Failure getting subject with non-ASCII common name

### ISSUE THREAD

**Issue by tmontes** [pyca/cryptography#10133]
Dear PyCA team,

Thanks for sharing such a high-quality project with the world. :-)

I've been using it successfully across many scenarios and, earlier today, I faced an unexpected failure which, I admit, may be down to some misunderstanding of mine.

The scenario has cryptography failing to grab a CSR's subject, where the common name contains non-ASCII characters.

So, all in all, I'm not sure if:

1. The CSR has been generated correctly.
2. If a CSR subject's common name can contain non-ASCII / arbitrary UNICODE characters (what does X.509 have to say about that?)
3. If this is down to me misusing the library.
4. If this is indeed an unexpected failure that cryptography should handle.

Thanks in advance for shedding some light.

ENVIRONMENT:

* macOS 12.7.2 running on Apple Silicon.
* Python 3.11.7 from installed from www.python.org macOS package.
* Setup procedure:

```
$ python3.11 -m venv venv
$ . ./venv/bin/activate
(venv) $ pip install --upgrade pip setuptools
(venv) $ pip install cryptography
(venv) $ pip freeze
cffi==1.16.0
cryptography==41.0.7
pycparser==2.21
```

REPRODUCTION:

* CSR PEM file:

```
$ cat the.csr
-----BEGIN CERTIFICATE REQUEST-----
MIICkTCCAXkCAQAwTDEQMA4GA1UEAxMHRXggVml09jEkMCIGCSqGSIb3DQEJARMV
ZXgudml0b3Jpbm9AZ21haWwuY29tMRIwEAYDVQQKEwlHcmVhdCBPcmcwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6SX9NYje579ru7VdEorFkI6GWHC+V
nlYeCyWudtaFsCaRsi/8mM8DjvrYtFMt6xFxOOXnFbq6CTWX8bepGKCTJalfk2JA
wTfnZOEQQ4SAB2WJ5XND470ngM6aDkRdKmipBFSH8RMo7hVmwlUNbnWqnD8JSDdP
YukU6w3L7Q3EaqExdSFKUm6X8SHsZtraQmoKr0JAfwQkraEef/BLVx0UXCltXs1/
WcM8vWFTI+0EZunczcPbKtLF967sw4Dd6i2R79OrY9PbML5HTbt6ODvx1t2Cwsan
i3dRCtt9LDCw1+8n3OR6QESCqH1fDFHbZufqaUeBLdh+DGlO5qh1Z+OPAgMBAAGg
ADANBgkqhkiG9w0BAQUFAAOCAQEAICVthq22+R/kLUf9QSf9FzWOqa3ZoQ7AUNNR
eN+vyJ3wgCrZ+hHwfzBWJdVwtxvr7ouY5CgQ6TtaUDLrzeZJxDBB3IwTefpz/dnx
uwBTiyrG20yiDXxbr8/VSec7np1X9/VPF0R5K4L48UGyAB0aRuz3D3noca6Z6Q3K
ogGyNpSJ2keQZSOGF7qbkFurjvvzh/D6IimS9KNWCTGaWJcrOwyyJEkitwlqV8E1
T9mMS7MHWKlGv5SLH5CTzR1eb5t17dZJni6jySEAgOIQBaWscxqp8vAThH+HWRTI
iASDqk5yLtmnplNTy4DyA0gOtfl4AMK8Pfwzrtkg1fBlPrWdsA==
-----END CERTIFICATE REQUEST-----
```

* OpenSSL parsing:

```
$ cat csr_non_ascii_subject.sh
openssl version
openssl req -in the.csr -noout -subject
```

```
$ bash csr_non_ascii_subject.sh
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
subject=CN=Ex Vitö, emailAddress=ex.vitorino@gmail.com, O=Great Org
```

* Cryptography parsing failure:

```
$ cat csr_non_ascii_subject.py 
import pathlib

import cryptography
from cryptography import x509

print(f'{cryptography.__version__=}')

csr_pem_bytes = pathlib.Path('the.csr').read_bytes()
csr = x509.load_pem_x509_csr(csr_pem_bytes)
subject = csr.subject
```

```
(venv) $ python csr_non_ascii_subject.py 
cryptography.__version__='41.0.7'
Traceback (most recent call last):
  File "/Users/tiago.montes/Work/Consult/LCG/long-run/99-cardian/x-diag-non-ascii/csr_non_ascii_subject.py", line 10, in <module>
    subject = csr.subject
              ^^^^^^^^^^^
ValueError: error parsing asn1 value: ParseError { kind: InvalidValue }
```

ADDITIONAL INFO:

* Failure is the same on CentOS 7 with Python 3.11.7 from conda-forge.

* CentOS 7's openssl output is slightly different:

   ```
   [root@ss ~]# openssl version
   OpenSSL 1.0.2k-fips  26 Jan 2017
   [root@ss ~]# openssl req -in the.csr -noout -subject
   subject=/CN=Ex Vit\xF6/emailAddress=ex.vitorino@gmail.com/O=Great Org
   ```

   **F6** in the CN is the unicode code point for the non-ASCII character `ö`.

* Debian 11's bullseye openssl output is, again, slightly different:

   ```
   root@nuckie:~# openssl version
   OpenSSL 1.1.1w  11 Sep 2023
   root@nuckie:~# openssl req -in the.csr -noout -subject
   subject=CN = Ex Vit\C3\B6, emailAddress = ex.vitorino@gmail.com, O = Great Org
   ```

  **C3 B6** is the UTF-8 encoding for the the non-ASCII character `ö`

* I also tested decoding the CSR in a few online places:
  * https://www.sslshopper.com/csr-decoder.html worked nicely.
  * https://certlogik.com/decoder/ displays something but complains that commonName's "PrintableString contains illegal character".
  * https://www.sslchecker.com/csr/decode worked nicely.

WRAP UP:

I thank you again in advance for any pointers that help me understand what's going on: all in all I'm not sure of CN's can include non-ASCII characters.

Happy to follow up with more details and tests.

**Comment by alex** [comment]
The common name here is encoded with a PrintableString ASN.1 string type. PrintableStrings have a limited set of characters they can use (a subset of ascii), which is why this is rejected.

Utf8String type may be used to encode non-ascii values.

**Comment by tmontes** [comment]
@Alex, thanks for the quick response.

So, IIUC, the CSR I shared is encoding the common name as a PrintableString ASN.1,  but could be encoding it as a Utf8String -- that would be valid and handled by cryptography. Of course, doing that is up to the CSR generating library -- https://github.com/digitalbazaar/forge, in this case.


Do you confirm?

**Comment by reaperhulk** [comment]
That's correct -- this is invalid DER as constructed, which is why cryptography rejects it. Some other implementations may be less strict, but the library creating this has a bug and should be fixed to use UTF8String types when encoding characters outside the PrintableString range.

**Comment by tmontes** [comment]
Thanks again for the quick response. I'll continue my investigation with the CSR generating lib.

**Comment by tmontes** [comment]
POST CLOSE NOTES:

* After fixing the CSR generation (see [this](https://github.com/digitalbazaar/forge/issues/754#issuecomment-716656831)), cryptography did extract the subject correctly and, subsequently, signed a usable certificate.
* Again thanks!
