### ISSUE TITLE
Breaking change in type of a private elliptic key's "curve" from instance-of-class to class

### ISSUE THREAD

**Issue by rthalley** [pyca/cryptography#10187]
While trying to test cryptography 42 changes related to UTC times going from "naive" to "timezone aware" in aioquic, I encountered an unrelated failure from our tests.

The problem was that for a SECP256R1 private key, we had code testing `isinstance(key, ec.SECP256R1)` and this is `True` in 41.0.7 and `False` in the development mainline.  I built from 00a94b00 this morning for testing with python 3.12, and I built with "python -m build".  I then installed the wheel into my aioquic test environment.

I did not see this change listed in the list of breaking changes and figure it might have snuck in unintentionally.

Here is a comparison between 41.0.7 and main:

```
# cryptography 41.0.7

>>> from cryptography.hazmat.primitives.asymmetric import ec, ed448, ed25519, rsa
>>> key = ec.generate_private_key(ec.SECP256R1)
>>> key.curve 
<cryptography.hazmat.primitives.asymmetric.ec.SECP256R1 object at 0x102da2840>
>>> isinstance(key.curve, ec.SECP256R1)
True
>>> key.curve is ec.SECP256R1  
False


# cryptography main

>>> from cryptography.hazmat.primitives.asymmetric import ec, ed448, ed25519, rsa
>>> key = ec.generate_private_key(ec.SECP256R1)
>>> key.curve
<class 'cryptography.hazmat.primitives.asymmetric.ec.SECP256R1'>
>>> isinstance(key.curve, ec.SECP256R1)
False
>>> key.curve is ec.SECP256R1
True

**Comment by alex** [comment]
Looks like a bug to me. I wonder why our tests didn't catch this.

**Comment by alex** [comment]
Ahhh, the real bug is that `ec.generate_private_key(ec.SECP256R1)` should never have been accepted in the first place. The correct way to write it is: `ec.generate_private_key(ec.SECP256R1())`

**Comment by rthalley** [comment]
Hmm, that's my bad in making the replication case, as our code calls ec.generate_private_key() as you suggest.  Also, things still break:

```
# 41.0.7
>>> key = ec.generate_private_key(ec.SECP256R1())
>>> isinstance(key.curve, ec.SECP256R1)
True


# 42
>>> from cryptography.hazmat.primitives.asymmetric import ec, ed448, ed25519, rsa
>>> key = ec.generate_private_key(ec.SECP256R1())
>>> isinstance(key, ec.SECP256R1)
False
>>> 
```

**Comment by alex** [comment]
Ahhh, still so wrong :-)

**Comment by rthalley** [comment]
Hmm, we seem to call the generate method with the class and not an instance in one place, but things work in 41 and not in 42 so I am still unsure either of why it ever worked or why it has stopped working :),

**Comment by reaperhulk** [comment]
The issue here is that in < 42 we returned an instance of the curve for `key.curve` and in main right now we return the class. We aren't entirely clear on which we return in the docs, but we should keep returning an instance since that's what we always did.

**Comment by reaperhulk** [comment]
Sorry, to be a bit more accurate here: in all releases right now if you pass a class or an instance, `key.curve` will return an instance. In `main` right now if you pass an instance you get the instance back for `key.curve` but if you pass a class you'll get the class.

**Comment by alex** [comment]
Sorry it looks to me like if you pass an instance (as opposed to the class), to generate key it looks right to me in 42:

```
>>> from cryptography.hazmat.primitives.asymmetric import ec, ed448, ed25519, rsa
>>> key = ec.generate_private_key(ec.SECP256R1())
>>> 
>>> key.curve
<cryptography.hazmat.primitives.asymmetric.ec.SECP256R1 object at 0x104505910>
>>> isinstance(key.curve, ec.SECP256R1)
True
```

So there's just a behavioral change in if you pass the class

**Comment by rthalley** [comment]
OK, I found that we were passing the class in one place in our test suite.  If I change that to an instance, then it works on both.  I can accept this is "our bad", but it might be worth considering doing "what you always did" on the return value in case others are having similar confusion between instances and classes.

Thanks for the super fast response.

I'll leave it to you to decide if you want to change something or just close the ticket, and will fix our test to use the instance.

**Comment by reaperhulk** [comment]
I think we should fix this Alex. Maybe with a deprecation warning to note this was always incorrect, maybe with a test that just silently accepts this forever ¯\_(ツ)_/¯

**Comment by alex** [comment]
Yeah, seems good.

**Comment by alex** [comment]
Ok https://github.com/pyca/cryptography/pull/10188 should resolve this and emit a warning.

Thanks for testing us pre-release!

**Comment by rthalley** [comment]
Thanks for making Cryptography!
