### ISSUE TITLE
Extra padding added when data length matches block size

### ISSUE THREAD

**Issue by apogeecmb** [pyca/cryptography#10209]
Hello,

I noticed when using the PKCS7 padder that the padder was adding extra bytes even when the inputted data exactly matches the specified block size.  For example:

```
from cryptography.hazmat.primitives import padding

padder = padding.PKCS7(128).padder()
dataToPad = b'\x01'*16
padded = padder.update(dataToPad ) + padder.finalize()
```
The above results in padded have a value of: :`b'\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10'`
which is of length 32 with 16 bytes of padding.

I tried it with an input length of 32 bytes as well, and I ended up with 48 bytes with 16 bytes of padding.  Is this expected behavior?  I naively expected it to not add any padding if the inputted data was already exactly a multiple of 16 in this case.  

Looking through the source code, it looks like since `_buffer` is of length zero because the data length is already a multiple of the block size, when `finalize` is called and it in turn calls `_byte_padding_pad`, this line returns a full 16 bytes of padding in my case:

`pad_size = block_size // 8 - len(buffer_)`

The cryptography module was installed using pip, and I'm running the following versions:
python - 3.10
pip - 22.0.2
cryptography - 41.0.7
setuptools - 69.0.3
cffi - 1.16.0

Thanks for any help.

-Chris

**Comment by alex** [comment]
This is expected behavior. Think about it from the perspective of how an unpadder would work -- if you provided exactly 16-bytes to the unpadder, it would treat the last byte as signifying how much padding there was, and truncate real data.

**Comment by apogeecmb** [comment]
@alex Ah, I hadn't thought of it that way.  I suppose that makes sense.  In my particular application, the length of the original data is included, so that hadn't occurred to me.  Thanks.
