### ISSUE TITLE
Reconsider keeping support for the Blowfish and IDEA algorithms

### ISSUE THREAD

**Issue by misterzed88** [pyca/cryptography#10227]
The Blowfish and IDEA algorithms are still used in some legacy formats, most prominently in PGP v2.0 and [OpenPGP](https://datatracker.ietf.org/doc/html/rfc4880).

These algorithms are currently flagged as deprecated and will be removed in the future (issue #6809).

Is there a chance that you can reconsider this decision? Keeping the algorithms strengthens the case for the Cryptography library being a versatile component with a broad user base, like a Swiss army knife. Security researchers, among others, may still need these algorithms. 

Optionally, would it be better to add a new deprecation variant: one where the algorithms are flagged as not recommended, but still kept in the product? (This classification could then also be used for other legacy algorithms such as ARC4).

**Comment by reaperhulk** [comment]
https://github.com/pyca/cryptography/pull/10284

(ARC4 and TripleDES will likely get moved into this namespace shortly as well)

**Comment by misterzed88** [comment]
That is a nice solution. Thank you for doing the change!
