### ISSUE TITLE
Unconfirmed regression: `RSAPrivateKey.sign(data=)` stopped accepting `bytearray` after 42.0

### ISSUE THREAD

**Issue by woju** [pyca/cryptography#10256]
If I'm reading this correctly (I'm sorry if I got any detail wrong, I'm not an expert in Rust), after commit 0000b402dd5edffa6a86ca560464e83a66fd91f5, `RSAPrivateKey.sign` stopped accepting `bytearray` as `data=` argument.

Previously, invocation of `EVP_PKEY_sign` via cffi passed `data, len(data)`, which accepted `bytearray` just fine:
https://github.com/pyca/cryptography/commit/0000b402dd5edffa6a86ca560464e83a66fd91f5#diff-97598491194e5ffd150e82dea4ddb874833c27432477fada5ef1bc9990c4b70fL280-L282

Now, `impl RsaPrivateKey` relies on `pyo3::prelude::pymethods` to convert `data` to `&[u8]`:
https://github.com/pyca/cryptography/commit/0000b402dd5edffa6a86ca560464e83a66fd91f5#diff-2820c635120a8d3d8a7f949c2ebc0f1e868bf6ff8258a5c3620d02d94e291c3fR347-R352

And PyO3 wants `bytes` only, not `bytearray`, at least according to this table: https://pyo3.rs/v0.20.2/conversions/tables#argument-types (`bytearray` would be `Vec<u8>`).

Now I'm not sure how valid this bug is. `sign()` was always (since 34d5c39a9c1efa6c2f2c9f473890ebe44816e85a) documented to accept `bytes`, but also always accepted `bytearray` (which is "bytes-like" according to https://cryptography.io/en/latest/glossary/#term-bytes-like).

Originally reported as https://github.com/gramineproject/gramine/issues/1731 by @andre-w-fischer

**Comment by reaperhulk** [comment]
Thanks for the report. I'm a bit surprised this worked previously, but we will fix this for 42.0.2 (which we currently plan to release on Jan 30).

**Comment by woju** [comment]
Thanks for the fix!
