### ISSUE TITLE
Write some checklists?

### ISSUE THREAD

**Issue by public** [pyca/cryptography#1034]
Cryptography is now, quite large and complicated but also quite well systematized.

We should write some checklists to help review changes. It would codify the mechanical changes we expect from each PR. Things such as "Check the coverage is 100%", "Check that the tests cover the documented interface behaviour", "Check that support was added to MultiBackend" and so forth.

**Comment by public** [comment]
https://www.youtube.com/watch?v=we4G_X91e5w&list=PLXxpc3zN0SWc3CnogaFHeA6ehK8g1dKPU&index=10

**Comment by alex** [comment]
Do we have any specific checklists we'd like, or the items that should be on them? I'm inclined to close this for now.
