### ISSUE TITLE
Unable to load PEM file

### ISSUE THREAD

**Issue by v0id-main** [pyca/cryptography#10343]
ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. MalformedFraming

* cffi=1.16.0 cryptography=42.0.2 pycparse=2.21
* pip3 install cryptography

**Comment by v0id-main** [comment]
decoded_public_key = base64.b64decode(public_key.encode())
recipient_key = load_pem_public_key(data=decoded_public_key) <------------------

**Comment by alex** [comment]
Please provide more context, such as a sample public key.
