### ISSUE TITLE
Cannot install Cryptography 42 on PyPy 3.8 on Windows

### ISSUE THREAD

**Issue by parafoxia** [pyca/cryptography#10371]
I understand this is a very specific issue, but since Python 3.8 is still officially supported, I thought I'd let you know. Pinning the version to 41 (or at least <42) fixes the issue. It installs fine on MacOS and Linux.

Here's some additional context:

* Python version: PyPy 7.3.11 with Python 3.8.16
* Cryptography version: 42.0.2
* Pip version: 23.1 (I think?)

Here's the GitHub Actions job I noticed the problem in: https://github.com/parafoxia/analytix/actions/runs/7832614747/job/21386253883

If there's any further information you need, please let me know.

**Comment by alex** [comment]
While Python 3.8 is supported, PyPy 3.8 (which is what you're running here) is not (you won't see it on https://www.pypy.org/download.html), and therefore we do not publish wheels for it.


If you meet the build requirements you can probably still build for it, but we don't publish pre-built wheels for it anymore.

**Comment by parafoxia** [comment]
Oh right, I didn't know that. That's fine then, I'll close this. Thanks for the quick reply!

**Comment by alex** [comment]
I guess I'll just note: the logs aren't verbose enough for me to _prove_ this, but I imagine it works on macOS and Linux only because the Github Actions Runner comes with OpenSSL and other needed dependencies pre-installed, whereas they're not on Windows.
