### ISSUE TITLE
Compiled binary incompatible at execution time

### ISSUE THREAD

**Issue by jackwood11** [pyca/cryptography#10440]
Hello! 

I'm working on upgrading my installation of `cryptography` to `42.0.2`. Per the requested information specified in the template:
```
python=3.9
cryptography=42.0.2
pip=24.0
cffi=1.16
setuptools=58.1.0
```

This is being deployed as an AWS Lambda; Lambdas with Python 3.9 as the runtime [leverage Amazon Linux 2 as the OS](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html). [Amazon Linux 2 includes glibc 2.26 as a core package](https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#glibc-gcc-and-binutils). To ensure that I am installing the binary wheels, I'm installing using the following command:

```
pip install --platform manylinux2014_x86_64 --target=./venv/lib/python3.9/site-packages \
 --implementation cp --python-version 3.9 --only-binary=:all: cryptography==42.0.2
```

The installation seems to work just fine via the command output and checking `cryptography` directly from the Lambda's ZIP file. During execution, however, I am getting the following error: 
```
{"__type":"MyLambdaException","message":"MyOperation failed with error /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)."}
```

I may be misunderstanding the role of binary wheels, and glibc is still required for executing the binary. If the host OS does not have a compatible version of glibc does that require upgrading glibc? Or is this potentially some other issue?

Thanks in advance!

**Comment by reaperhulk** [comment]
`GLIBC_2.28` suggests that you are somehow installing our `manylinux_2_28` package rather than `2014` (which would correspond to glibc 2.17). That's very odd since the command you provided caused my local pip to fetch `cryptography-42.0.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64` though.

I just took a look at objdump on the `_rust.abi3.so` (`objdump -T _rust.abi3.so | grep -i glibc`) and I don't see any symbols that are newer than 2.17, so I suspect you may have a situation where you've somehow installed multiple copies. Is there a particular reason why you are doing a `--target` command here? Is it possible you're installing this into some other path that Python isn't using and that there is an additional (broken) copy in the actual python path?

**Comment by jackwood11** [comment]
> `GLIBC_2.28` suggests that you are somehow installing our `manylinux_2_28` package rather than `2014` (which would correspond to glibc 2.17). That's very odd since the command you provided caused my local pip to fetch `cryptography-42.0.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64` though.
> 
> I just took a look at objdump on the `_rust.abi3.so` (`objdump -T _rust.abi3.so | grep -i glibc`) and I don't see any symbols that are newer than 2.17, so I suspect you may have a situation where you've somehow installed multiple copies. Is there a particular reason why you are doing a `--target` command here? Is it possible you're installing this into some other path that Python isn't using and that there is an additional (broken) copy in the actual python path?

I did some more digging and you're absolutely right on the multiple copies. Double checking the rest of my output from the `pip install -r requirements.txt` command I run subsequently, there is the following output:

```
Collecting cryptography<43,>=0.6 (from msal==1.22.0->-r requirements.txt (line 30))
  Downloading cryptography-42.0.4-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
```

I likely either have an issue with a) using the incorrect path in `--target` or b) not adhering to some dependency resolution rule from pip. To answer your question on the usage of `--target`, I ran into the following error when running the command without the flag:
```
ERROR: Can not use any platform or abi specific options unless installing via '--target' or using '--dry-run'
```

Regardless, thank you for validating that `2_17` does not have any references to `GLIB_2.28`; that gives me the confidence that resolving this dual installation issue I created should resolve the underlying issue.
