### ISSUE TITLE
Generate private key of type RSA PSS

### ISSUE THREAD

**Issue by gregbreen** [pyca/cryptography#10460]
Hi. I'm just confirming that there's no `generate_private_key()` method that can do this, correct?

```
openssl genpkey -algorithm rsa-pss -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 -out key-pss.pem
```

**Comment by reaperhulk** [comment]
We don’t support generating PSS params on RSA private keys, correct. We support PSS broadly in our signing and verification APIs (with typical RSA keys) but not the constraints on the keys themselves.

**Comment by gregbreen** [comment]
Thanks. I would use this if it were there, but I don't really need it. Closing.
