### ISSUE TITLE
Please update PyO3 to 0.20.3 and make a new release

### ISSUE THREAD

**Issue by mgorny** [pyca/cryptography#10463]
The current PyO3 version of 0.20.2 is broken on PowerPC (https://github.com/PyO3/pyo3/pull/3882/commits/9d1b11f70459367593e4cb92919f5f98c156dda9). This is preventing PowerPC users from receiving the security fix from cryptography-42.0.4.

Could you update PyO3 and make a new release, please?

**Comment by alex** [comment]
We merged the pyo3 change into main -- and it should be trivial to cherry-pick. @reaperhulk and I can talk about a backport+release

**Comment by alex** [comment]
Ok, both of us are good with doing a backport. We're going to see if there's other stuff we want to backport, but aim to get this out today or tomorrow I think.

**Comment by mgorny** [comment]
Thanks a lot!

**Comment by alex** [comment]
Done
