### ISSUE TITLE
AWS Encryption Upstream Testing Expectations

### ISSUE THREAD

**Issue by texastony** [pyca/cryptography#10502]
Howdy Pyca,

Y'all do great work, and I am very grateful of your efforts.

### Clean out p37 tests
The [AWS Encryption SDK for Python (ESDK-Python)](https://github.com/aws/aws-encryption-sdk-python/blob/master/test/upstream-requirements-py311.txt) and
the [Dynamo DB Encryption Client for Python (DDBEC-Python)](https://github.com/aws/aws-dynamodb-encryption-python/blob/master/test/upstream-requirements-py311.txt)
are used by `pyca/cryptography`'s downstream tests.

I'd like to clear out the older Python 3.7 upstream requirement tests from these repos:
- [DDBEC](https://github.com/aws/aws-dynamodb-encryption-python/blob/master/test/upstream-requirements-py37.txt)
- [ESDK](https://github.com/aws/aws-encryption-sdk-python/blob/master/test/upstream-requirements-py37.txt)

That is not going to impact your downstream testing, correct?

I assume not, based on:
- [pyca's ESDK install script](https://github.com/pyca/cryptography/blob/main/.github/downstream.d/aws-encryption-sdk.sh)
- [pyca's DDBEC install script](https://github.com/pyca/cryptography/blob/main/.github/downstream.d/dynamodb-encryption-sdk.sh)

But I'd appreciate a confirmation. 

### Documentation question
I'd like to document the expectation for these files in our repos,
so future AWS Crypto Tools developers know what the upstream tests are for
(I was told when I joined the team ~2 years ago by folks no longer here
what these `upstream` files are for. When I one day leave, who will know?).

Can you confirm this blob is an accurate expectation, from Pyca, for these files:
> AWS Crypto Tools maintains `test/upstream-requirements-py<VERSION>.txt` in our Python products such that 
our Cryptographic Primitive Provider for Python ([pyca/cryptography](https://github.com/pyca/cryptography))
may execute downstream tests against AWS Crypto Tools Python products.
These files allow pyca to install and test the Crypto Tools products.
Additionally, Crypto Tools should maintain a test configuration that can be completed without using any AWS resources.
If Crypto Tools needs to contact pyca about this expectation,
they should cut a issue to the pyca/cryptography repo.

### Dependency Question
Finally, pyca does not care what version of cryptography is declared in these `upstream-requirements` files, 
right?

Dependabot regularly notifies us to upgrade these.
If we should not, I would need to document that as well.

**Comment by alex** [comment]
1. We do not run your tests on Python 3.7, so that's fine.
2. That looks right to me -- the purpose is ultimately so that we can run your tests against all of our PRs to ensure we're not breaking you.
3. No, we don't use the declared cryptography requirement, we over-ride it with the version we're attempting to test (that's the point :-))

**Comment by texastony** [comment]
Thank you for responding!

I suspected (3) was the case.

Like I said, we never documented what was going with these files.
I wanted to verify with y'all I knew the truth before I authored any documentation. 

Closing as successful. 
Again, thank you very much!
