### ISSUE TITLE
Cypher text

### ISSUE THREAD

**Issue by testlorenzospa** [pyca/cryptography#10529]
Hello.

I want to encrypt a simple text (not a byte string) in AES256 CBC.
Is it possible?

In a script I use these instruction

`cipher = Cipher(algorithm=AES256(cryptoKey), mode=CBC(iv))`
`encText = cipher.encryptor().update(b"Ciao")`

But if I cange the parameter to the update method in a simple text ("Ciao", without sign "b") I get an error from python

`TypeError: from_buffer() cannot return the address of a unicode object`

What can I do to encrypt a simple text?

Thanks.

**Comment by alex** [comment]
Encryption is an operation performed on bytes, you are passing a unicode string. The correct solution is for you to encode your string to bytes with an encoding such as utf8.
