### ISSUE TITLE
hmac.HMAC function

### ISSUE THREAD

**Issue by testlorenzospa** [pyca/cryptography#10528]
Hello.

Is It possible to have the result from hmac.HMAC in binary format (as in PHP with the function hash_hmac)?
If yes, how?
I am not very expert about python.

Thanks for your help.

**Comment by alex** [comment]
Have you consulted the documentation?

https://cryptography.io/en/latest/hazmat/primitives/mac/hmac/#cryptography.hazmat.primitives.hmac.HMAC.finalize

**Comment by reaperhulk** [comment]
This is an issue tracker, not a place to get support for how to use this library. That said, `finalize` returns the value in bytes.
