### ISSUE TITLE
dh.generate_parameters() loops infinitely with big key sizes

### ISSUE THREAD

**Issue by kubikaugustyn** [pyca/cryptography#10520]
I'm trying to generate the parameters for key generation (as advised in [the documentation](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dh/)):
```python
from cryptography.hazmat.primitives.asymmetric import dh

parameters = dh.generate_parameters(generator=2, key_size=4096)
```
When I run this code, my Python interpreter freezes, because the code never exits the `dh.generate_parameters` function.
I tested the generation time with different key sizes, and here are my results:
* Key size 512: ~1 second
* Key size 1024: ~10 seconds
* Key size 2048: ~100 seconds
* Bigger key sizes never finished (in under 5 minutes)

I'm using Python `3.10.12`, `cryptography==42.0.5`, `cffi==1.16.0` and `setuptools==59.6.0`. I installed `cryptography` with `pip3 install cryptography`. For machine-dependent issues I ran the code not only on my machine, but also on a cloud VM just to make sure it wasn't caused by me.

I think the time to generate the parameters should be less than 50ms, not many seconds (how would my browser be so fast with functions like these when establishing a TLS conection?)

**Comment by alex** [comment]
This is somewhat expected, generating new DH parameter is incredibly expensive.

This is why FFDH is incredibly discouraged for new protocols, and ECDH is preferred instead. For protocols that do require FFDH, the recommendation is to generate a DH parameter once and reuse it.
