### ISSUE TITLE
Add key agreement APIs

### ISSUE THREAD

**Issue by public** [pyca/cryptography#1059]
Such as DH, ECDH and RSA encryption.

I think the interface can be kept pretty simple?

```
class KeyAgreement:
    def __init__(self, private_key):
        """
        Start the key agreement process.
        For ephemeral agreement a new private_key should be used.
        """

    def agree(self, peers_key):
        """
        Return the shared secret.
        """
```

DH will require a new PrivateKey object and there's probably some other complexity I've missed too.

**Comment by mgrabovsky** [comment]
Has anyone been working on this? Ocaml's Cryptokit [uses](https://github.com/msimon/cryptokit/blob/bfa910b/src/cryptokit.mli#L703-L750) pretty much the same design as @public sketched above, so it might be sufficiently suitable.

The standard groups are defined in [RFC 3526](https://tools.ietf.org/html/rfc3526). There's one additional parameter which is not yet included in the current API – the bit length of the exponent, or private secret. The recommended values for each of the groups are also included in the RFC.

The high-level API should be the same for DH and ECDH, the parameter format will naturally be different. As for the ephemeral variants, if I understand the protocol correctly, the only difference is in the private secret generation stage. Static DH uses the same number for each run, while ephemeral DH will generate a fresh number every time. Thus, provided there's a way to supply custom private secrets, the library should be able to support both the static and ephemeral variant.

**Comment by reaperhulk** [comment]
This has been languishing a bit, although there's an implementation for review in #1882.

**Comment by simo5** [comment]
@reaperhulk should we close this now that #1882 has been merged ?

**Comment by reaperhulk** [comment]
Yeah, closing for now. If we need more we'll open a new issue.
