### ISSUE TITLE
Add TLS KDFs

### ISSUE THREAD

**Issue by public** [pyca/cryptography#1060]
TLS/SSL has weird custom KDFs. I guess we should write APIs for them?

There are 2 of them that we care about

- [ ] SSL 3.0 http://tools.ietf.org/html/rfc6101#section-6.1 <-- Oh god what?
- [ ] TLS 1.0 http://trac.tools.ietf.org/html/rfc2246#section-5 which is the same as TLS 1.1 http://trac.tools.ietf.org/html/rfc4346#section-5 and TLS 1.2 http://trac.tools.ietf.org/html/rfc5246#section-5

These should probably be private APIs internal to our TLS implementation and we don't have anywhere for them to live yet either.

**Comment by reaperhulk** [comment]
Going to close this since we don't plan to do this at this time.
