### ISSUE TITLE
Build issue with cryptography using buildozer: libc-header-start.h file not found

### ISSUE THREAD

**Issue by AliArmi** [pyca/cryptography#10607]
- Python 3.11.5
- Cryptography 41.0.7
- Buildozer 1.5.0
- NDK 25c
- rustc 1.7

Log: [https://gist.github.com/AliArmi/6f37303095fda89d535d0b5dcfec3a6d](url)

Hello,

I'm trying to build an Android app using the cryptography library (version 41.0.7) with Buildozer and Python-for-Android. During the build process, I'm encountering an issue where the Rust compiler is unable to find the libc-header-start.h file. The error message:

`cryptography-cffi@0.1.0: /usr/include/stdlib.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
cryptography-cffi@0.1.0: #include <bits/libc-header-start.h>
cryptography-cffi@0.1.0:          ^~~~~~~~~~~~~~~~~~~~~~~~~~
cryptography-cffi@0.1.0: 1 error generated.`

I understand that this file is part of the GNU C Library, which is not included in the version of the Android NDK (I'm using r25c). Im pretty sure that this NDK version is using the LLVM libc++ library instead.

I've tried reinstalling the NDK and manually installing it, but the issue persists. I believe the issue might be with the cryptography-cffi Rust crate, which seems to be expecting the libc-header-start.h file to be present. Im not sure if something is outdated or just not compatible.

Is there a way to build the cryptography library with the LLVM libc++ library, or a way to use a precompiled binary that's compatible with Android, or maybe a third solution?

Please keep in mind that I'm a complete beginner.

Thank you in advance.

**Comment by reaperhulk** [comment]
Are you cross compiling? If so, do you have
gcc-multilib installed?

**Comment by AliArmi** [comment]
Yes i am cross compiling and i actually did not have gcc-multilib installed.
I installed it and ran the whole thing again and got a new error:
`warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:408:14: note: expanded from macro '_cffi_type'

warning: cryptography-cffi@0.1.0:     assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \

warning: cryptography-cffi@0.1.0:     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /usr/include/assert.h:109:11: note: expanded from macro 'assert'

warning: cryptography-cffi@0.1.0:       if (expr)                                                         \

warning: cryptography-cffi@0.1.0:           ^~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:10464:7: warning: cast to smaller integer type 'uintptr_t' (aka 'unsigned int') from 'void *' [-Wvoid-pointer-to-int-cast]

warning: cryptography-cffi@0.1.0:       _cffi_type(551), arg0, (char **)&x0);

warning: cryptography-cffi@0.1.0:       ^~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:408:14: note: expanded from macro '_cffi_type'

warning: cryptography-cffi@0.1.0:     assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \

warning: cryptography-cffi@0.1.0:     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /usr/include/assert.h:108:20: note: expanded from macro 'assert'

warning: cryptography-cffi@0.1.0:   ((void) sizeof ((expr) ? 1 : 0), __extension__ ({                     \

warning: cryptography-cffi@0.1.0:                    ^~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:10464:7: warning: cast to smaller integer type 'uintptr_t' (aka 'unsigned int') from 'void *' [-Wvoid-pointer-to-int-cast]

warning: cryptography-cffi@0.1.0:       _cffi_type(551), arg0, (char **)&x0);

warning: cryptography-cffi@0.1.0:       ^~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:408:14: note: expanded from macro '_cffi_type'

warning: cryptography-cffi@0.1.0:     assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \

warning: cryptography-cffi@0.1.0:     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /usr/include/assert.h:109:11: note: expanded from macro 'assert'

warning: cryptography-cffi@0.1.0:       if (expr)                                                         \

warning: cryptography-cffi@0.1.0:           ^~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:10467:38: warning: cast to smaller integer type 'uintptr_t' (aka 'unsigned int') from 'void *' [-Wvoid-pointer-to-int-cast]

warning: cryptography-cffi@0.1.0:     if (_cffi_convert_array_argument(_cffi_type(551), arg0, (char **)&x0,

warning: cryptography-cffi@0.1.0:                                      ^~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:408:14: note: expanded from macro '_cffi_type'

warning: cryptography-cffi@0.1.0:     assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \

warning: cryptography-cffi@0.1.0:     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /usr/include/assert.h:108:20: note: expanded from macro 'assert'

warning: cryptography-cffi@0.1.0:   ((void) sizeof ((expr) ? 1 : 0), __extension__ ({                     \

warning: cryptography-cffi@0.1.0:                    ^~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/cryptography/arm64-v8a__ndk_target_21/cryptography/src/rust/target/release/build/cryptography-cffi-7bb9e4f01c4b74a6/out/_openssl.c:10467:38: warning: cast to smaller integer type 'uintptr_t' (aka 'unsigned int') from 'void *' [-Wvoid-pointer-to-int-cast]

warning: cryptography-cffi@0.1.0:     if (_cffi_convert_array_argument(_cffi_type(551), arg0, (char **)&x0,

warning: cryptography-cffi@0.1.0:                                      ^~~~~~~~~~~~~~~

warning: cryptography-cffi@0.1.0: /home/armi/KassesystemUdenPDF/.buildozer/android/platform/build-arm64-v8a/build/other_builds/c... (9233401 more, please see e.stdout)`

The whole terminal is filled with a infinite loop of this.
