### ISSUE TITLE
missing cryptography.hazmat.backends.openssl.rsa on 42.*

### ISSUE THREAD

**Issue by tcanabrava** [pyca/cryptography#10609]
The port of rsa to rust removed this export and broke a bunch of softwares.
is there a "quick and easy" porting guide?

**Comment by alex** [comment]
Nothing that was in that module was a public API. Can you explain what you were using for and what broke?

**Comment by ptrcnull** [comment]
hiya, came across the same issue; apparently it was being used by NXP in [spsdk][1]:
```
======================================================================
ERROR: tests.utils.crypto.test_common (unittest.loader._FailedTest.tests.utils.crypto.test_common)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.utils.crypto.test_common
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 419, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 362, in _get_module_from_name
    __import__(name)
  File "/home/buildozer/aports/community/py3-spsdk/src/spsdk-1.10.0/tests/utils/crypto/test_common.py", line 14, in <module>
    from spsdk.crypto.keys_management import (
  File "/home/buildozer/aports/community/py3-spsdk/src/spsdk-1.10.0/spsdk/crypto/__init__.py", line 51, in <module>
    from cryptography.hazmat.backends.openssl.rsa import *
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.rsa'
```


[1]: https://github.com/nxp-mcuxpresso/spsdk

**Comment by alex** [comment]
From a few seconds of review, it's not at all clear why they were importing these non-public APIs in the first instance.

In any event, they were never public, and given it's been both fixed, and there doesn't appear to be some missing capability in the public API they were compensating for, I don't believe there's any action to be taken here.
