### ISSUE TITLE
cryptography.exceptions.UnsupportedAlgorithm: Unsupported key type: b'sk-ssh-ed25519@openssh.com' - YubiKey SSH public keys

### ISSUE THREAD

**Issue by commonism** [pyca/cryptography#10604]
Hi,

using:

  * Python 3.12.2
  * cryptography 42.0.5
  * cffi         1.16.0

parsing the public key of a yubikey U2F ssh public key fails

```python
import cryptography.hazmat.primitives.serialization

cryptography.hazmat.primitives.serialization.load_ssh_public_key(b"sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIMwRvXyiJg+fzGNsKeTm7gArZwzrDtnXTZvp9GcaClTaAAAADHNzaDpZdWJpa2V5Mw==")
```

```
cryptography.exceptions.UnsupportedAlgorithm: Unsupported key type: b'sk-ssh-ed25519@openssh.com'
```

Due to the unknown key format 
https://github.com/pyca/cryptography/blob/090bdf06016737e6df713f432c8b0c9fe5f871c1/src/cryptography/hazmat/primitives/serialization/ssh.py#L575-L582

and -later on- additional/unparsed application strings at the end of the container:

when force feeding a new format …
```python
cryptography.hazmat.primitives.serialization.ssh._KEY_FORMATS[b"sk-ssh-ed25519@openssh.com"] = cryptography.hazmat.primitives.serialization.ssh._KEY_FORMATS[b"ssh-ed25519"]
```

```python
cryptography.hazmat.primitives.serialization.load_ssh_public_key(b"sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIMwRvXyiJg+fzGNsKeTm7gArZwzrDtnXTZvp9GcaClTaAAAADHNzaDpZdWJpa2V5Mw==")
```
```
ssh.py", line 1033, in _load_ssh_public_identity
    _check_empty(rest)
  File "~/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 184, in _check_empty
    raise ValueError("Corrupt data: unparsed data")
```

https://github.com/openssh/openssh-portable/blob/e27f032aa8fcbae9b2e7c451baaf4b8ac6fa3d45/PROTOCOL.u2f#L81-L86
```
The format of a sk-ssh-ed25519@openssh.com public key is:

	string		"sk-ssh-ed25519@openssh.com"
	string		public key
	string		application (user-specified, but typically "ssh:")
```

**Comment by alex** [comment]
We should add support, though one caveat is that the public key will not contain the application value. So if you need that, simply adding support to `load_ssh_public_key` may be insufficient.

**Comment by alex** [comment]
Would you be interested in contributing a PR adding support?
