### ISSUE TITLE
Question: Function `cryptography.hazmat.primitives.asymmetric.dsa` no longer accessible?

### ISSUE THREAD

**Issue by Lopolio** [pyca/cryptography#10643]
Hello,

Now first I apologize in Case the Structure of this issue is incorrect.

A Bit of an explanation what I mean by the Title.
In my case I use cryptography with the dsa Module to Communicate with a Device which tends to do things a bit special.

Using cryptography in Correlation with paramiko as is results in this specific error:

```
Traceback (most recent call last):
  File ".../env/lib/python3.10/site-packages/paramiko/transport.py", line 2186, in run
    self.kex_engine.parse_next(ptype, m)
  File ".../env/lib/python3.10/site-packages/paramiko/kex_gex.py", line 100, in parse_next
    return self._parse_kexdh_gex_reply(m)
  File ".../env/lib/python3.10/site-packages/paramiko/kex_gex.py", line 282, in _parse_kexdh_gex_reply
    self.transport._verify_key(host_key, sig)
  File ".../env/lib/python3.10/site-packages/paramiko/transport.py", line 1976, in _verify_key
    if not key.verify_ssh_sig(self.H, Message(sig)):
  File ".../env/lib/python3.10/site-packages/paramiko/dsskey.py", line 152, in verify_ssh_sig
    key = dsa.DSAPublicNumbers(
ValueError: p must be exactly 1024, 2048, 3072, or 4096 bits long
```

Now for cryptography version 41.0.7 and below this was not a big type of Issue for me, I could simply overwrite the given values and add the bit length of 768 and remove the 4096 as it was needed in that Special case.

However since Version 42.0.0 on, the migration to Rust of the dsa Module, this function is no longer accessible at all and I lost the ability to communicate with these Devices.

I am not too familiar with Rust so I am unsure if there still is a way to access it or not, or would it be possible to make it accessible again?

**Comment by reaperhulk** [comment]
You would need to modify and recompile to make this possible: https://github.com/pyca/cryptography/blob/a32da2e10f5974e9338cb191cc471a6f1b77e300/src/rust/src/backend/dsa.rs#L246

768 bit keys are extremely small and insecure so I would be opposed to supporting this officially.

**Comment by Lopolio** [comment]
I am also not really a fan of changing this in the actual Code, sadly the configuration on the Device is not changeable, this is just how it communicates.

Prior Version 42, we manually override the `dsa._check_dsa_parameters` with the help of a Context Manager Implementation that was only used when communication with the special device.

The function is however no longer Accessible, which prevents us from this, would there be a way to make it accessible again?

**Comment by Lopolio** [comment]
Thanks for the fast answers, closing Ticket
