### ISSUE TITLE
PKCS7SignatureBuilder email data

### ISSUE THREAD

**Issue by msetina** [pyca/cryptography#10664]
Thank you for the implementation of PKCS7SignatureBuilder. I am trying to form an email message, but the signed message it provides does not contain Subject, From and other header info and can not find a way to add this other then the method server uses to fill this missing info.
It is not as good as an attachment.
Is this planned or am I missing something to form email message to send?

**Comment by msetina** [comment]
Externaly this needs to be done:
header = "\r\nFrom: {0}\r\nSUBJECT: {1}\r\n\r\n".format(
        sender_email, subject
    )
signature = signature.replace(b"\r\n\r\n", header.encode(), 1)

**Comment by reaperhulk** [comment]
We do support serialization to a type called SMIME :) https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.Encoding.SMIME

**Comment by msetina** [comment]
I was talking about output of this:
https://cryptography.io/en/42.0.5/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.pkcs7.PKCS7SignatureBuilder.sign
and the result from it starts with:
```MIME-Version: 1.0\r\nContent-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="===============4830284379503980412=="```
and as I understand it alreay is SMIME. It includes a signature. If I sent it like it was, the server added some header, but I want mine and with the modification I posted, the email gets to the other end as a proper email and gmail recognizes tha email has a signature and it does not present it. In the header it compares sender with data from certificate, it allows exporting the certificate, which checks out.

**Comment by alex** [comment]
It's impossible for us to provide any guidance with the limited information you've provided.

**Comment by msetina** [comment]
I have taken your example in documenttion for PKCS7SignatureBuilder and "extended" to be able to send SMIME email message. 
When using the bytes from example the SMTP server added header from sendmail call. SO I wondered it the sign call with SMIME type could be extended to allow adding email header. My solution was to insert the header to the result like SMTP server did.
My "extended" example is:
```
   header = "\r\nFrom: {0}\r\nSUBJECT: {1}\r\n\r\n".format(
        sender_email, subject
    )
```

```
            options = [pkcs7.PKCS7Options.DetachedSignature]
            bldr = pkcs7.PKCS7SignatureBuilder().set_data(body.encode())
            bldr = bldr.add_signer(cert, PK, hashes.SHA256())
            signature = bldr.sign(serialization.Encoding.SMIME, options)
            signature = signature.replace(b"\r\n\r\n", header.encode(), 1)
```
and the signature can be used to send email:
```
smtp.sendmail(
        sender_email,
        receiver_email,
        signature,
    )
```
As I mentioned before the gmail understands the message and checks the signature as per RFC and even shows the certificate. If ```sign``` could be extended with optional parameter for case of SMIME, it could be used to send signed email messages.
