### ISSUE TITLE
Is there documentation for rust backend

### ISSUE THREAD

**Issue by sc0Vu** [pyca/cryptography#10662]
Hi there,

Thanks for this great library. I used cryptography library (rust backend) on my computer. Recently, I try to export my pem ec key (`cryptography.hazmat.bindings._rust.openssl.ec.ECPrivateKey`) to other format but couldn't find the doc about it (found https://cryptography.io/en/latest/x509/tutorial/#determining-certificate-or-certificate-signing-request-key-type and https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#key-dumping).

I do find source code of `ECPrivateKey`, and works for me:
https://github.com/pyca/cryptography/blob/6d9a52cd50bab4e956798bf5677168a131b5acb6/src/rust/src/backend/ec.rs#L218

Is this possible to include rust implementation to the documentation?

**Comment by alex** [comment]
No, there is no backend because it is not a public API. All of our public APIs are documented.
