### ISSUE TITLE
ASN1 ParseError / InvalidValue / GeneralizedTime

### ISSUE THREAD

**Issue by joonis** [pyca/cryptography#10685]
Loading the following certificate (cryptography 35.0.0+):

```python
from base64 import b64decode
from cryptography import x509
from cryptography.hazmat.backends import default_backend
    
c = b'MIICxDCCAaygAwIBAgIHR80SnRf5GzANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDEwNTRUIwJBcNMjEwMjAzMTcwNzIyWhgTOTk5OTEyMzEyMjU5NTkuMzU3WjAOMQwwCgYDVQQDEwNTRUIwggEkMA0GCSqGSIb3DQEBAQUAA4IBEQAwggEMAoIBAQCchFXYYKnBBJijXhnT2IoJEXtXIzag95yF5ZfIVmAHmGDnuSLKmcHgjDEVy1MhT6t2h36OZ2WBULy2g3bbNvN2fI6syTcvorjS9gmWAa/CmiTMdLifreowCNjC6/DYomMrgQSKB8l23eSYeieHNuWpbwbVv8Q9vqJw8SOrLDX7ADc1xAp/CoIVLiqtHgr0/rnXmghA3gFA6ZY/Kig11YAJ5NGCjXqCBEKiDcMopAziCvKMt9V27vxwOuuiTps2Mlockl4DZClfy1mKfWkgeYtqFL1xMpEDeIsgxTd3T3Zr1orV3CcTzpV/I+2Y8BdidE0/01FvAWUhhHIMk4lljCTlAgUBAAAAD6MfMB0wDgYDVR0PAQH/BAQDAgWgMAsGA1UdIwQEMAKAADANBgkqhkiG9w0BAQsFAAOCAQEACBLj9Qn8WpOUnhXKEccQ226pT8Gi9gPlT6+aPlxlW+Bijna0zNHxU0SsOkUKecBTDQdEhiF5JwQUy29ycWYNIhRwjzUpFGYJYqIjJDiY0FO7wolBW2T52t1+KeFF4mqhU4T5ONV9f66HG4L6VcIf7VtTWOfrGQXbev1muUI6Jr9lEfS9CaQ1Xb1zZX9n5PrjAphmZQa/UMkw2U+MG0pKuCkhwtmDZJjBC6pG+BrmEnL6JoZfhYsHfNbzAw0HoS3UpLsJOk1HotfpYxfFiSiGU5Rt2FtU47UtMs79DF748j/YECxMbT5DcOQHvaZIEbA9DQgnouA76uEbYW+Bp1tfQQ=='
cert = x509.load_der_x509_certificate(b64decode(c), default_backend())
```

Results in:

```python
ValueError: error parsing asn1 value: ParseError { kind: InvalidValue, location: ["Certificate::tbs_cert", "TbsCertificate::validity", "Validity::not_after", "Time::GeneralizedTime"] }
```

It does work with cryptography <=3.4.8.

**Comment by alex** [comment]
I'm on phone, but I think the issue here is that the not after timestamp
contains fractional seconds. These are prohibited by RFC5280 4.1.2.5.2,
"GeneralizedTime values MUST NOT include fractional seconds."

**Comment by alex** [comment]
Yes, you can see the fractional seconds plainly in [here](https://lapo.it/asn1js/#MIICxDCCAaygAwIBAgIHR80SnRf5GzANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDEwNTRUIwJBcNMjEwMjAzMTcwNzIyWhgTOTk5OTEyMzEyMjU5NTkuMzU3WjAOMQwwCgYDVQQDEwNTRUIwggEkMA0GCSqGSIb3DQEBAQUAA4IBEQAwggEMAoIBAQCchFXYYKnBBJijXhnT2IoJEXtXIzag95yF5ZfIVmAHmGDnuSLKmcHgjDEVy1MhT6t2h36OZ2WBULy2g3bbNvN2fI6syTcvorjS9gmWAa_CmiTMdLifreowCNjC6_DYomMrgQSKB8l23eSYeieHNuWpbwbVv8Q9vqJw8SOrLDX7ADc1xAp_CoIVLiqtHgr0_rnXmghA3gFA6ZY_Kig11YAJ5NGCjXqCBEKiDcMopAziCvKMt9V27vxwOuuiTps2Mlockl4DZClfy1mKfWkgeYtqFL1xMpEDeIsgxTd3T3Zr1orV3CcTzpV_I-2Y8BdidE0_01FvAWUhhHIMk4lljCTlAgUBAAAAD6MfMB0wDgYDVR0PAQH_BAQDAgWgMAsGA1UdIwQEMAKAADANBgkqhkiG9w0BAQsFAAOCAQEACBLj9Qn8WpOUnhXKEccQ226pT8Gi9gPlT6-aPlxlW-Bijna0zNHxU0SsOkUKecBTDQdEhiF5JwQUy29ycWYNIhRwjzUpFGYJYqIjJDiY0FO7wolBW2T52t1-KeFF4mqhU4T5ONV9f66HG4L6VcIf7VtTWOfrGQXbev1muUI6Jr9lEfS9CaQ1Xb1zZX9n5PrjAphmZQa_UMkw2U-MG0pKuCkhwtmDZJjBC6pG-BrmEnL6JoZfhYsHfNbzAw0HoS3UpLsJOk1HotfpYxfFiSiGU5Rt2FtU47UtMs79DF748j_YECxMbT5DcOQHvaZIEbA9DQgnouA76uEbYW-Bp1tfQQ).

These are not permitted by RFC 5280, the approrpriate thing to do is to report this issue to the certificate issuer.

**Comment by alex** [comment]
Well, accepting invalid certificates wouldn't be fixing cryptography.

On Tue, Apr 2, 2024 at 7:00 PM Thimo ***@***.***> wrote:
>
> Have you ever asked a bank to change or fix something? It is nearly hopeless.
>
> So there are four possibilities:
>
> Fixing it in cryptography by stripping invalid fractional seconds.
> Downgrade to cryptography 3.4.8.
> Change the crypto lib.
> Change the bank ;)
>
> The first one isn't an option?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.
