### ISSUE TITLE
.x509 cert chain signature verification fails at child node

### ISSUE THREAD

**Issue by codebucket** [pyca/cryptography#10699]
Python Version: 3.12.2
cryptography Version: 42.0.5
pip Version 24.0
cffi Version: 1.16.0
setuptools Version: 69.2.0

Created a cert chain as follows

+ Root -> Self Signed : OpenSSL verifies the signature successfully
        |
	|
	+ Intermediate -> Signed by the root private key  : OpenSSL verifies the signature successfully
	        |
		|
		+ Child -> Signed by the intermediate private key  : OpenSSL fails signature verification; error is **error 2 at 1 depth lookup: unable to get issuer certificate error verification failed.**
		
The sample code that generated the certs are  provided below in the attached file

[cert_build.txt](https://github.com/pyca/cryptography/files/14864978/cert_build.txt)

Looks like there is an issue in the cert builder module. Can you please confirm and fix?

**Comment by reaperhulk** [comment]
What openssl command are you using to attempt to verify this? `openssl verify -CAfile rootcert.der -untrusted devicecert.der childcert.der` works fine for me. Although I'll note that setting `CA:True` on the child cert is not typical practice unless you intend to have a leaf node beneath that still.

**Comment by codebucket** [comment]
> What openssl command are you using to attempt to verify this? `openssl verify -CAfile rootcert.der -untrusted devicecert.der childcert.der` works fine for me. Although I'll note that setting `CA:True` on the child cert is not typical practice unless you intend to have a leaf node beneath that still.

I was missing the _-untrusted_ keyword after adding which its working. Sorry for the confusion! I shall close this issue.
