### ISSUE TITLE
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust'

### ISSUE THREAD

**Issue by gloria-mankrado** [pyca/cryptography#10777]
Attempting to update the cryptography package on AWS Lambda for security reasons, we're facing an import error: “cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust'”, despite using the correct wheel package (cryptography-42.0.5-pp310-pypy310_pp73-manylinux_2_28_x86_64.whl). This issue arises after creating a new Lambda layer and affects our other lambda function.

. I also tried to pip install using that wheel, to make sure that I am downloading the cryptography package for the correct platform, but that was also not working! FYI, commands used - 
$ pip --python 3.10 \
      install \
    --platform manylinux_2_28_x86_64 \
    --implementation cp \
    --only-binary=:all: --upgrade \
    --target awsbundle \
    Cryptography
I also tried to specify version on this pip install, but installation is failing again.

**Comment by reaperhulk** [comment]
That is the pypy wheel, not the correct CPython wheel.

**Comment by gloria-mankrado** [comment]
could you provide me with the correct CPython wheel package?

**Comment by alex** [comment]
If you look on pypi you will see there are labels indicating the platforms
that each wheel works on.

**Comment by reaperhulk** [comment]
You can also use pip to perform the download with platform args so that you don’t make this mistake again in the future.
