### ISSUE TITLE
Remove protected from _MaxLength,_Auto and _DigestLength

### ISSUE THREAD

**Issue by msetina** [pyca/cryptography#10770]
Those classes are used in salt length and can not be used in instance check if they are hidden to final user. In API paradigm it is messy to check otherwise.

**Comment by alex** [comment]
Users are expected to use the class variables that provide instances of
these values.

**Comment by msetina** [comment]
But if keys can be viewed as interfaces, then this is needed as it is part of the interface. There are a lot of  protecetd members that are usefull. 
You did a great job to provide interafaces and would be nice to clean up the ecosystem for them.

**Comment by alex** [comment]
Why? You can test if something is max length with `is MAX_LENGTH`

**Comment by msetina** [comment]
Not something I would do, but it works.
