### ISSUE TITLE
Does cryptography support Python 3.13 currently?

### ISSUE THREAD

**Issue by notatallshaw** [pyca/cryptography#10806]
Sorry if this is already answered, I tried searching and only found the blocking issue  https://github.com/python-cffi/cffi/issues/23 which seems now resolved.

I was trying to set up pip CI for 3.13 and one of the issues I ran into is pip tests import cryptography here: https://github.com/pypa/pip/blob/main/tests/lib/certs.py#L4

And on Python 3.13 they seem to give the error:

```
ImportError: /home/damian/.pyenv/versions/pip_testing_313a6/lib/python3.13/site-packages/_cffi_backend.cpython-313-x86_64-linux-gnu.so: undefined symbol: _PyErr_WriteUnraisableMsg
thread '<unnamed>' panicked at /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    import tests.lib.certs
  File "/home/damian/opensource_contributions/pip/tests/lib/certs.py", line 4, in <module>
    from cryptography import x509
  File "/home/damian/.pyenv/versions/pip_testing_313a6/lib/python3.13/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency, verification
  File "/home/damian/.pyenv/versions/pip_testing_313a6/lib/python3.13/site-packages/cryptography/x509/certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
pyo3_runtime.PanicException: Python API call failed
```

I assume https://github.com/pyca/cryptography/issues/10676 might be related but it was unclear to me. 

Feel free to close this issue if this is made clear somewhere else

**Comment by notatallshaw** [comment]
Thanks, for pip tests at least, the [workaround](https://github.com/python-cffi/cffi/issues/23#issuecomment-1845861410) of pulling directly from github seems to be sufficent and looks like all tests using cryptography are passing on Python 3.13.

**Comment by nschloe** [comment]
FYI, python-cffi has a release now (https://github.com/python-cffi/cffi/releases/tag/v1.17.0rc1).

**Comment by alex** [comment]
Great. pip won't pick it up by default since it's a pre-release, but good
to see.
