### ISSUE TITLE
RSAPrivateNumbers.private_key no longer allows passing in the 'unsafe_skip_rsa_key_validation' flag

### ISSUE THREAD

**Issue by arshad01** [pyca/cryptography#10826]
Hello

Prior to version 42.x, cryptography allowed passing in 'unsafe_skip_rsa_key_validation' in the private_key method of RSAPrivateNumbers in cryptography.hazmat.primitives.asymmetric.rsa.py. It seems that it is no longer the case after migration to rust based implementation of backend. Is there any way to still pass the unsafe_skip_rsa_key_validation flag?

Thanks

**Comment by alex** [comment]
Why do you think it's no longer possible?

**Comment by arshad01** [comment]
I believe I made a mistake while looking at the RSAPrivateNumbers.private_key method signature. It does pass in the `unsafe_skip_rsa_key_validation` flag. So apologies for the raising this issue.

However, I have a separate issue. Since I am using jwcrypto which internally uses cryptography, I could earlier monkey patch cryptography `private_key` method to pass in a True value for this flag. Monkey patching cryptography was easier as jwcrypto uses `generate_private_key` which does not take in this flag. With cryptography using rust now, setting the flag true does not seem straight forward as I do not know rust. Any help or idea is greatly appreciated in this regard.

Thanks

**Comment by alex** [comment]
Monkey patching was never part of hte supported API. We support passing the flag as an argument. If you'd like to support setting it for all keys, or something to that effect, you should direct that feature request to jwcrypto.
