### ISSUE TITLE
TypeError: _SSHCipher() takes no arguments

### ISSUE THREAD

**Issue by rameshboje** [pyca/cryptography#10865]
import docker
[Mon Apr 22 10:44:55.659523 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/docker/__init__.py", line 1, in <module>
[Mon Apr 22 10:44:55.659531 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from .api import APIClient
[Mon Apr 22 10:44:55.659538 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/docker/api/__init__.py", line 1, in <module>
[Mon Apr 22 10:44:55.659545 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from .client import APIClient
[Mon Apr 22 10:44:55.659552 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/docker/api/client.py", line 18, in <module>
[Mon Apr 22 10:44:55.659559 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from ..transport import UnixHTTPAdapter
[Mon Apr 22 10:44:55.659566 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/docker/transport/__init__.py", line 9, in <module>
[Mon Apr 22 10:44:55.659574 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from .sshconn import SSHHTTPAdapter
[Mon Apr 22 10:44:55.659581 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/docker/transport/sshconn.py", line 1, in <module>
[Mon Apr 22 10:44:55.659588 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     import paramiko
[Mon Apr 22 10:44:55.659595 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/paramiko/__init__.py", line 22, in <module>
[Mon Apr 22 10:44:55.659602 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from paramiko.transport import (
[Mon Apr 22 10:44:55.659609 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/paramiko/transport.py", line 93, in <module>
[Mon Apr 22 10:44:55.659616 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from paramiko.dsskey import DSSKey
[Mon Apr 22 10:44:55.659623 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/paramiko/dsskey.py", line 25, in <module>
[Mon Apr 22 10:44:55.659631 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]     from cryptography.hazmat.primitives import hashes, serialization
[Mon Apr 22 10:44:55.659638 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 25, in <module>
[Mon Apr 22 10:44:55.659645 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158]   File "/opt/django-project/myvenv/lib/python3.12/site-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 101, in <module>
[Mon Apr 22 10:44:55.659653 2024] [wsgi:error] [pid 1630:tid 139725902394944] [remote 172.16.100.1:57158] TypeError: _SSHCipher() takes no arguments

**Comment by rameshboje** [comment]
![image](https://github.com/pyca/cryptography/assets/36566102/4d0baa08-a73d-4a21-af5d-926c02cd4e5f)

**Comment by rameshboje** [comment]
Hi @alex  I simply installed docker library and then installed cryptography-42.0.5 package., And then it is automatically coming the error.,  When I execute `touch wsgi.py` And hard reload It shows apache 500 error page., When I checked apache error logs it's showing the below error., 

"aes256-ctr": _SSHCipher(

TypeError: _SSHCipher() takes no arguments

**Comment by alex** [comment]
You need to provide instructions with enough specificity that we could
follow them.

This error generally indicates that your installation is somehow corrupted.

On Tue, Apr 23, 2024 at 8:04 AM rameshboje ***@***.***> wrote:
>
> Hi @alex I simply installed docker library and then installed cryptography-42.0.5 package., And then it is automatically coming the error., When I execute touch wsgi.py And hard reload It shows apache 500 error page., When I checked apache error logs it's showing the below error.,
>
> "aes256-ctr": _SSHCipher(
>
> TypeError: _SSHCipher() takes no arguments
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by alex** [comment]
See https://github.com/pyca/cryptography/issues/9988 for a past instance of this bug -- it indicated a system error of some sort.
