### ISSUE TITLE
CertificateBuilder sign does not support registered RSA keys

### ISSUE THREAD

**Issue by msetina** [pyca/cryptography#10873]
I found this in sign method of CertificateBuilder:
            if not isinstance(private_key, rsa.RSAPrivateKey):
                raise TypeError("Padding is only supported for RSA keys")
This raises an error if private key given for signing is registered with a method:
RSAPrivateKey.register(KeyClass)

**Comment by alex** [comment]
Is instance should allow anything that registers itself with the ABC. Can
you provide a minimal reproducer we can run?

**Comment by msetina** [comment]
My mistake. I had EC key in the test environment.
