### ISSUE TITLE
Import "cryptography.hazmat.bindings._rust" could not be resolved (M1 Mac)

### ISSUE THREAD

**Issue by pandeyg2106** [pyca/cryptography#10919]
I am seeing this error on my M1:
`~/cryptography/hazmat/_oid.py:7: Evaluation error   PanicException: Python API call failed`
OS: M1 Mac
python version: 3.10

paramiko version : 3.4.0
Mode of installation: pip

cryptography version: 42.0.5
Mode of installation: pip

**Comment by alex** [comment]
Please provide instructions with sufficient detail for us to reproduce.

**Comment by pandeyg2106** [comment]
In my project I have dependency with paramiko. In M1 when I import paramiko and build I see this error.
Works fine if build on any machine which is not arm based architecture.

**Comment by pandeyg2106** [comment]
Basically it's this line that fails on M1
`from cryptography.hazmat.bindings._rust import (
    ObjectIdentifier as ObjectIdentifier,`

**Comment by alex** [comment]
This is not enough information for us to reproduce. Please keep in mind
that this package is successfully installed millions of times a day. You
need to give us information on what makes your situation unique.

**Comment by pandeyg2106** [comment]
So recently someone added a dependency of `paramiko` in the project to start a ssh client to run some commands. Before this I never faced any error. It's only after adding this dependency I started seeing this, and that too only in machines running arm64 architecture.

Fails here `from cryptography.hazmat.bindings._rust import ( ObjectIdentifier as ObjectIdentifier,`

This fails on all the M1 machines, so, I assume there is something with `paramiko` that is not compatible with M1, and `cryptography` is not happy.

**Comment by alex** [comment]
Again, this package supports arm64 macos and has for years.

You need to provide information on how we can reproduce this.

**Comment by pandeyg2106** [comment]
```
import paramiko

class foo:
         def __init__(self):
               self.ip = "some_ip"
               self.username = "some_username"
               self.password = "some_password"
               self.ssh_client = paramiko.SSHClient()
               self.ssh_client.connect(self.ip, username=self.username, password=self.password)
        def method(self):
               self.ssh_client.exec_command("some_command")
```
If I do something like this on a M1 machine, I get the error I stated above. I assume paramiko calls cryptography somewhere in background.
