### ISSUE TITLE
Error loading RSA private key with password

### ISSUE THREAD

**Issue by joumaico** [pyca/cryptography#10948]
I generated an RSA private key using the following command:

```bash
openssl genrsa -passout pass:foobar -out private_key.pem 2048
```

Then, I attempted to load the private key with the cryptography library (version 42.0.6):

```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

with open("private_key.pem", "rb") as f:
    private_key = serialization.load_pem_private_key(f.read(), password=b"foobar", backend=default_backend())
```

However, I encountered the following error:

```bash
Traceback (most recent call last):
  File "/home/ubuntu/test.py", line 4, in <module>
    private_key = serialization.load_pem_private_key(f.read(), password=b"foobar", backend=default_backend())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Password was given but private key is not encrypted.
```

It seems like there might be an issue with the backend not supporting RSA private keys. Could someone provide guidance on how to resolve this issue or suggest an alternative approach? Thank you!

**Comment by alex** [comment]
Please read the error message and consult your generated private key -- when I run that OpenSSL command, the private key I get is not encrypted with any password.

**Comment by joumaico** [comment]
**Solution:** The command `openssl genrsa -passout pass:foobar -out private_key.pem 2048` didn't create an encrypted private key rather use the command `openssl genrsa -aes256 -out private_key.pem 2048` which triggers a passphrase prompt and will generate an encrypted private key.
