### ISSUE TITLE
[42.0.6]  "DLL Load Failed" On Windows 7 With Python 3.8

### ISSUE THREAD

**Issue by GaneJ** [pyca/cryptography#10944]
"DLL Load Failed" On Windows 7 With Python 3.8,
because some of DLLs try to import "bcryptprimitives" function, which doesn't exist on Windows 7.

This is bcryptprimitives.dll export on Windows 7:
![Bcryptprimitives](https://github.com/pyca/cryptography/assets/20153153/26dbcbe6-8c3e-4897-9767-08b502d189ea)

This is _rust.pyd 42.0.6 import:
![_rust pyd](https://github.com/pyca/cryptography/assets/20153153/5ef6d676-e0a3-4818-9372-d0bc347c2748)

This is _rust.pyd 42.0.5 import:
![_rust pyd_old](https://github.com/pyca/cryptography/assets/20153153/e56c1fbe-fa83-40a2-8393-c65f4f77ce52)

ProcessPrng function in bcryptprimitives, only exist in Windows 10 above.

If you want to keep 42.0.6 using bcryptprimitives on Windows,
you should remove support for Python 3.8 below.

Because Python 3.8 below still support Windows 7.

**Comment by GaneJ** [comment]
I got compiled version Cryptography on pypi.org.

**Comment by alex** [comment]
Windows 7 is unsupported by Microsoft, is there a particular reason you're using it?

**Comment by Tarnum-tst** [comment]
@alex 
Please look here: https://catalog.update.microsoft.com/Search.aspx?q=Windows-7+x64+2024-04
Windows 7 is still supported by Microsoft and will be supported until (at least) October 2024 via Windows Embedded Standard 7/Windows Server 2008 R2 channels.

**Comment by alex** [comment]
We have fixed this in 42.0.7, but we will not be supporting Windows 7 in 43.0.

As a practical matter we haven't tested against windows 7 in years (maybe ever?) and we have no ability to test against an embedded Windows distribution.

**Comment by Slautin** [comment]
@alex 
Hello,
For some reason, I need to use Python 3.8 and Windows 7. Unfortunately, 42.0.7 returns the same DLL error with bcrypt. Is there any chance to fix it? 

Thanks

**Comment by reaperhulk** [comment]
bcrypt is a separate package, you’ll need to pin to an older version.

**Comment by GaneJ** [comment]
> @alex Hello, For some reason, I need to use Python 3.8 and Windows 7. Unfortunately, 42.0.7 returns the same DLL error with bcrypt. Is there any chance to fix it?
> 
> Thanks

You need to update your Windows 7 @Slautin.

Because mine, up to date till August 2024.

Version 42.x run perfectly in Windows 7.

Not 43.x, as @alex said.

**Comment by Tarnum-tst** [comment]
@GaneJ 
Based on my own experience, I can state the following:
1. Cryptography 40.0.2 and earlier is fully compatible with Windows XP SP3 because of MSRV 1.48 (which generates XP-compatible code).
2. Version 43.0.0 (and 44.0.0dev1) are fully Windows 7 compatible as MSRV 1.63/1.65 generate Win'7-compatible code. 32-bit Rust code can even be patched to work on XP SP3 via kernel extension DLL from ReactOS.
You could compile the project yourself at any time with the appropriate compatibility if You wish.
