### ISSUE TITLE
ImportError: DLL load failed while import _rust: The specified procedure could not be found

### ISSUE THREAD

**Issue by Buskie1** [pyca/cryptography#10961]
Traceback (most recent call last):
  File "Z:\Buskie\Encryptor\main.py", line 3, in <module>
    from cryptography.hazmat.primitives import hashes
  File "C:\Users\abins\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\primitives\hashes.py", line 9, in <module>    
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

import os
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

**Comment by Buskie1** [comment]
So I had this code with me for a while it worked before but now after I reset my pc its not working.

**Comment by reaperhulk** [comment]
Please provide us instructions to reproduce in a fresh virtual environment including details of OS (what version of windows?), etc.

**Comment by alex** [comment]
It is likely you are using 42.0.6, please try upgrading to 42.0.7.
