### ISSUE TITLE
`x509.load_pem_x509_certificate` fails when `trailerField` param is present for RSASSA-PSS signatures

### ISSUE THREAD

**Issue by jimlast** [pyca/cryptography#10981]
**Basic problem statement**

I have several certificates that were signed using the RSASSA-PSS signature scheme. The certs were created using Java tool chain. When attempting to decode such a certificate using either `load_pem_x509_certificate()` or `load_der_x509_certificate()`, I get the following error:

```text
ValueError: error parsing asn1 value: ParseError { kind: EncodedDefault, location: ["Certificate::tbs_cert", 
"TbsCertificate::signature_alg", "AlgorithmIdentifier::params", "RsaPssParameters::_trailer_field"] }
```

After diving into the details, I see these certs have the "trailerField" parameter listed as part of the signature Algorithm. When I attempt to read the same certificate using openssl or other online parser, I get no errors. If I use openssl to create the same sort of key and certificate with the same signature algo and prams, the `trailerField` parameter does not appear. 

From reading RFC 8017, I see that the `trailerField` parameter is there for backward compatibility to IEEE1336, but I don't see an indication that its presence should be an error.

**Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools`` you're using**

Python: 3.12.3

| Package      | Version |
| ------------ | ------- |
| cffi         | 1.16.0  |
| cryptography | 42.0.7  |
| pip          | 24.0    |

**How you installed ``cryptography``**

Installed via pip in a Python virtual environment

**Clear steps for reproducing your bug**

Simple script that attempts to load a PEM file:

```python
import sys
from cryptography import x509

with open(sys.argv[1], "rb") as file:
    data = file.read()
cert = x509.load_pem_x509_certificate(data)
```
Dummy self-signed certificate of an RSA-4k key using RSASSA-PSS padding and SHA384 hash.

Note: This cert file was modified to hide some info, so the signature won't verify, but that doesn't have a bearing on the issue.

```text
-----BEGIN CERTIFICATE-----
MIIGYzCCBBKgAwIBAgIDAwAAMEYGCSqGSIb3DQEBCjA5oA8wDQYJYIZIAWUDBAIC
BQChHDAaBgkqhkiG9w0BAQgwDQYJYIZIAWUDBAICBQCiAwIBMKMDAgEBMHsxFDAS
BgNVBAsMC0VuZ2luZWVyaW5nMQswCQYDVQQGEwJVUzEUMBIGA1UEBwwLU2FudGEg
Q2xhcmExCzAJBgNVBAgMAkNBMR8wHQYDVQQKDBZBQUFBQUFBQUFBQUFBQUFBQUFB
QUFBMRIwEAYDVQQDDAlBQUFBQUFBQUEwHhcNMjMwNTE1MjAwMzEyWhcNNDgwNTE1
MjAwMzEyWjB7MRQwEgYDVQQLDAtFbmdpbmVlcmluZzELMAkGA1UEBhMCVVMxFDAS
BgNVBAcMC1NhbnRhIENsYXJhMQswCQYDVQQIDAJDQTEfMB0GA1UECgwWQUFBQUFB
QUFBQUFBQUFBQUFBQUFBQTESMBAGA1UEAwwJQUFBQUFBQUFBMIICIjANBgkqhkiG
9w0BAQEFAAOCAg8AMIICCgKCAgEAwaAriB7EIuVc4ZB1wD3YfDxL+9eyS7+izm0J
j3W772NINCWl8Bj3w/JD2ZjmbRxWdIq/4d9iarCKorXloJUB1jRdgxqccTx1aOoi
g4+2w1XhVVJT7K457wT5ZLNJgQaxqa9Etkwjd6+9sOhlCDE9l43kQ0R2BikVJa/u
yyVOSwEk5w5tXKOuG9jvq6QtAMJasW38wlqRDaKEGtZ9VUgGon27ZuL4sTJuC/az
z9/iQBw8kEilzOl95AiTkeY5jSEBDWbAqnZk5qlM7kISKG20kgQm14mhNKDI2p2o
ua+zuAG7i52epoRF2GfU0TYk/yf+vCNB2tnechFQuP2e8bLk95ZdqPi9/UWw4JXj
tdEA4u2JYplSSUPQVAXKt6LVqujtJcM59JKr2u0XQ75KwxcMp15gSXhBfInvPAwu
AY4dEwwGqT8oIg4esPHwEsmChhYeDIxPG9R4fx9O0q6p8Gb+HXlTiS47P9YNeOpi
dOUKzDl/S1OvyhDtSL8LJc24QATFydo/iD/KUdvFTRlD0crkAMkZLoWQ8hLDGc6B
ZJXsdd7Zf2e4UW3tI/1oh/2t23Ot3zyhTcv5gDbABu0LjVe98uRnS15SMwK//lJt
9e5BqKvgABkSoABf+B4VFtPVEX0ygrYaFaI9i5ABrxnVBmzXpRb21iI1NlNCfOGU
PIhVpWECAwEAAaN+MHwwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBRkoF9x4wwK
ZNg7deUBWZ4r7gYDRDAPBgNVHRMBAf8EBTADAQH/MDoGA1UdHwQzMDEwL6AtoCuG
KUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBMEYGCSqG
SIb3DQEBCjA5oA8wDQYJYIZIAWUDBAICBQChHDAaBgkqhkiG9w0BAQgwDQYJYIZI
AWUDBAICBQCiAwIBMKMDAgEBA4ICAQA/i6Mz4IETMK8YU/HxP7Bfej5i4aXhenJo
TuiDX0nqx5CDJm9ELhskxAkJ/oLA1O92UoLybfFk4gEpKFtyfiUYex9LogZj5ix0
sb2qfSSy9CRnOktGqfpel4e3KAhLgF5n2qZrqyq/8EPPldtSjEXn78sZMlIlUcQK
SnnNCQZVFpktDfDiEiGNuitux3ghHUrcVuxSbZcrXDbsbMF7NDdfLUUS9TijrL33
lrCXJs7m8kggGyCusiRQKHli1AEswiA4xU+8xsZrByYTopiGYtbJK8s0UCCXylyO
uKSubvdAnMDJ5GDD0+DX46LSfv7fgGNSG+LOBWdif7KoQf9cIhKJtxGxZCn/tvHm
wMzu4Jnx8N2vRnT+8DpBqhxtNvdXmrZUelSeQakx4djMKvmTR8Gd25EnC4RppCkj
bmPxY3zPd1X7raalTn34EOF9DeLsC9JfzkDuojxpHWMm30wKnDo20mlDQk/zKCDa
2Zc+YjtsTZCrTbvdgCukTKNZOUUVlWRu+sO/OwrmS2p16seHTIqHEbE1LntPv3gk
CcHGDSUAKx9c0Aol+Dj9xpb2nmGqoDeJ59Ja6REkHCdw5TduXyqqMqfD1AX0/QDN
devCMKlWBRCQ7DFlog3H1a+r/kuMUZ/Ij9yyKlSgYZMJ4VgNKDgTQdcsAL0MCEMr
zpacMwFusA==
-----END CERTIFICATE-----
```

**Comment by alex** [comment]
The RFS describes the sequence as:

```
   RSASSA-PSS-params ::= SEQUENCE {
       hashAlgorithm      [0] HashAlgorithm      DEFAULT sha1,
       maskGenAlgorithm   [1] MaskGenAlgorithm   DEFAULT mgf1SHA1,
       saltLength         [2] INTEGER            DEFAULT 20,
       trailerField       [3] TrailerField       DEFAULT trailerFieldBC
   }
```

As you can see, `trailerField` is `DEFAULT trailerFieldBC` (`trailerFieldBC` is 1).

The rules of DER _prohibit_ encoding a sequence member with its default value. That is to say: if `trailerField` were 2, it'd be fine. But serializing it with a value of 1 is prohibited, it must be encoded with the value omitted.

**Comment by jimlast** [comment]
Okay, I see. So Java library is doing the wrong thing by encoding it and Openssl is not catching it.

**Comment by alex** [comment]
Sounds like it.

ping @reaperhulk to the courtesy Java phone.

**Comment by reaperhulk** [comment]
What version Java were you using for this? There have been bugs fixed in JDK 17 and 21 (some of which have backported to 11, some of which are not available unless you upgrade to 21+) so if you can please try on JDK21 or 22 and see if you still see this issue.

**Comment by jimlast** [comment]
I'll check with my colleague and see.

**Comment by jimlast** [comment]
We found the source of the errant trailerField in our cert generation code. Thank you @reaperhulk and @alex for the help. I'm closing the issue.
