### ISSUE TITLE
BadSignature(\'Signature is not valid\')\

### ISSUE THREAD

**Issue by nilankbetaflux** [pyca/cryptography#10988]
Hello Team, I am facing one issue, i have encrypted one of the column in my model, nothing has been changed in code level, now when i am trying to get the details from the table, i am getting BadSignature(\'Signature is not valid\')\.

can any one please help me?

**Comment by alex** [comment]
You have provided no information for us to assist here. Frankly, `BadSignature` doesn't appear to even be an exception from our project.

If you'd like to file an issue, you need to include enough details for someone to understand (and ideally reproduce) your issue.

**Comment by nilankbetaflux** [comment]
[logger_name: default] [line_no 23] ERROR  [process_exception]                    ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.9/site-packages/django_cryptography/core/signing.py", line 232, in unsign\n    version, timestamp, value, sig = struct.unpack(fmt, signed_value)\n', 'struct.error: bad char in struct format\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n', '  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper\n    return bound_method(*args, **kwargs)\n', '  File "/app/core/decorators.py", line 28, in decorator\n    return view_function(request, *args, **kwargs)\n', '  File "/app/core/views.py", line 121, in get\n    return kyc_details_api.get_kyc_details(request)\n', '  File "/app/core/api/kyc_details.py", line 286, in get_kyc_details\n    if not user_kyc_objects:\n', '  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 324, in __bool__\n    self._fetch_all()\n', '  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all\n    self._result_cache = list(self._iterable_class(self))\n', '  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__\n    for row in compiler.results_iter(results):\n', '  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1299, in apply_converters\n    value = converter(value, expression, connection)\n', '  File "/usr/local/lib/python3.9/site-packages/django_cryptography/fields.py", line 174, in from_db_value\n    return self._load(force_bytes(value))\n', '  File "/usr/local/lib/python3.9/site-packages/django_cryptography/fields.py", line 116, in _load\n    return pickle.loads(self._fernet.decrypt(value, self.ttl))\n', '  File "/usr/local/lib/python3.9/site-packages/django_cryptography/utils/crypto.py", line 143, in decrypt\n    data = self._signer.unsign(data, ttl)\n', '  File "/usr/local/lib/python3.9/site-packages/django_cryptography/core/signing.py", line 234, in unsign\n    raise BadSignature(\'Signature is not valid\')\n', 'django.core.signing.BadSignature: Signature is not valid\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n', '  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner\n    return func(*args, **kwds)\n', '  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view\n    return view_func(*args, **kwargs)\n', '  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 84, in view\n    return self.dispatch(request, *args, **kwargs)\n', '  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch\n    response = self.handle_exception(exc)\n', '  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception\n    response = exception_handler(exc, context)\n', '  File "/app/core/exceptions.py", line 6, in status_code_handler\n    if response.data.get("detail",None) == "Unauthenticated, invalid access token signature!" and response.status_code==403:\n', "AttributeError: 'NoneType' object has no attribute 'data'\n"]

**Comment by alex** [comment]
A completely unformatted log message is not something actionable for us. Indeed, as far as I can tell this output does not contain a single reference to this project.

**Comment by nilankbetaflux** [comment]
ok alex thankyou
