### ISSUE TITLE
Certificate signing by the root certificate

### ISSUE THREAD

**Issue by AndryAsh** [pyca/cryptography#11027]
A root self-signed certificate for the local certificate authority has been created.
A request to issue a user certificate has been created.
Can you please tell me how to create a user certificate authenticated by the root certificate of the local CA?

**Comment by reaperhulk** [comment]
Looking at our documentation I see we don’t actually have an example of this, so we should add one.

You will need to generate a new key pair, use the public key of that in the new user cert, and sign the user certificate with the private key of the CA. Additionally, you will need to place the subjectDN of the issuer into the issuerDN of the user certificate and optionally do a few other things. While CSRs are sometimes used to provide the set of fields you want to sign, this is not a requirement.

**Comment by AndryAsh** [comment]
Thanks, it turns out that the certificate issuance request itself is not necessary?

**Comment by reaperhulk** [comment]
That's right. Think of a CSR as a bag of key/values in a convenient format. CAs use this to obtain information from you: your public key, what you claim your information is, etc. However, a competent CA does not blindly trust this information. Instead, they parse it, normalize it, validate it, and then enter it into the resulting certificate themselves. Copying from CSR->cert is a security risk. In fully trusted environments this can be convenient, but ultimately a CSR is not a fundamental requirement (although many CAs do require you to provide a CSR for their own processes).

**Comment by AndryAsh** [comment]
Thank you very much!
