### ISSUE TITLE
.private_bytes(..) with incorrect passphrase presents interactive prompt with from OpenSSL 3.0.13 (#7129 redux)

### ISSUE THREAD

**Issue by ngie-eign** [pyca/cryptography#11023]
## Software versions
- Custom FreeBSD 12.x~13.x(~ish) based OS.
- OpenSSL 3.0.13
- python 3.8.19
- cryptography 42.0.5
    - I acknowledge this isn't the latest release version (or the current py38-cryptography package available per FreeBSD ports), but newer versions don't seem to have addressed this issue (yet?) according to the [change log](https://cryptography.io/en/latest/changelog/).
    - Relevant Rust Crate software versions can be found here: https://github.com/freebsd/freebsd-ports/blob/f02bbcb4046ca0f792a091c4b29e35a4584b6545/security/py-cryptography/Makefile.crates .

## Description
Attempting to decrypt and encrypted PEM and failing, e.g., with an incorrect passphrase, will prompt the user for a passphrase, similar to what's discussed in #7129. I assume this is occurring because `PEM_def_callback` has not been properly overridden/set in the rust C extensions which handle decrypting the encrypted private key.

This interactive prompt issue makes migrating infrastructure/non-interactive script code from pyca/cryptography in place of pyca/pyOpenSSL impossible without going through and hacking either libcrypto, or resorting to some unsavory tricks redirecting stdin (which is fraught with issues in multithreaded processes, etc).

## Expected Behavior
- Entering in an incorrect passphrase should error out.

## Actual Behavior
- Entering in an incorrect passphrase results in a prompt from libcrypto being displayed, like `"Enter PEM pass phrase:"`.

**Comment by alex** [comment]
Can you provide a minimal reproducer? We should have a test case for this,
so I'm surprised if it regressed.

**Comment by ngie-eign** [comment]
Sorry for not including one :(.  I should have done that before taking off this weekend. 
If someone else doesn’t beat me to it, I’ll try and create one by sometime mid next week.

**Comment by ngie-eign** [comment]
Yeah. I'll use `--pdb` the next time I run pytest to get an exact traceback. I know the password prompt is (for sure) coming from OpenSSL 3.

**Comment by ngie-eign** [comment]
I looked at the traceback and it seems that the interactive prompt is coming from OpenSSL use in xmlsec1 or python-xmlsec.
I obviously didn't get the pyOpenSSL API conversion correct, which is what is triggering the issue in those libraries.
