### ISSUE TITLE
Add more curves

### ISSUE THREAD

**Issue by public** [pyca/cryptography#1109]
Currently we support the NIST curves and nothing else. OpenSSL supports quite a lot of other curves though. Some of the are probably useless but it would probably be good to at least get the other SECG ones wired up.

secp256k1 is probably the only non-NIST non-DJB curve with any widespread usage. It's used by Bitcoin.

**Comment by shea256** [comment]
I would love to see support for `secp256k1`. Any plans on incorporating it?

**Comment by reaperhulk** [comment]
@shea256 do you know of any other sources of test vectors besides what @public linked? Adding secp256k1 is easy, but we'd like to have a good set of reference tests.

**Comment by shea256** [comment]
Here are a couple more sources:
https://github.com/richardkiss/pycoin/blob/master/tests/ecdsa_test.py
https://github.com/vbuterin/pybitcointools/blob/master/test.py

**Comment by reaperhulk** [comment]
@shea256: secp256k1 support has been merged in #1913. It will be in the next release.

**Comment by shea256** [comment]
Awesome! Excited to see it in action.

**Comment by reaperhulk** [comment]
Closing this as we should have new issues when people request new curves.
