### ISSUE TITLE
aead subpackage in ciphers not load by default

### ISSUE THREAD

**Issue by rv0lt** [pyca/cryptography#11118]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using

1. Python: 3.9.6
2. pip: 24.0
3. cryptography: 42.0.4
4. cffi: 1.15.0
5. setuptools: 58.0.4

* How you installed ``cryptography``

Installed through pip

* Clear steps for reproducing your bug

If trying to generate a key as follow:

```
from cryptography.hazmat.primitives import ciphers
ciphers.aead.AESGCM.generate_key(bit_length=256)
```

It will raise an Attribute error:  
`AttributeError: module 'cryptography.hazmat.primitives.ciphers' has no attribute 'aead'`

However, if aead is imported directly, this does not happen:

```
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
AESGCM.generate_key(bit_length=256)
```
`b'\x95D=*\x86\xad\xc3\xe4#\xe6*Hr\xd9\r\xf9\xb2\x8d\x19\x8f,\xe9\xbf\xe8\xde\x01\xf6\xa9\xa3%\x8f\xd8'`

---
Further insepction shows that, when the package is imported as the first way, aead subpackage is not load

```
from cryptography.hazmat.primitives import ciphers
dir(ciphers)
```
`['AEADCipherContext', 'AEADDecryptionContext', 'AEADEncryptionContext', 'BlockCipherAlgorithm', 'Cipher', 'CipherAlgorithm', 'CipherContext', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'algorithms', 'annotations', 'base', 'modes']`

But, when we do this:

```
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives import ciphers
dir(ciphers)
```
`['AEADCipherContext', 'AEADDecryptionContext', 'AEADEncryptionContext', 'BlockCipherAlgorithm', 'Cipher', 'CipherAlgorithm', 'CipherContext', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'aead', 'algorithms', 'annotations', 'base', 'modes']`

I.e the aead is only imported when we have manually accessed it previously.

**Comment by alex** [comment]
This is a standard part of Python imports, sub-modules aren't not necessarily loaded immediately. You can't rely on this, if you want to ensure it's available you can do:

```
import cryptography.hazmat.primitives.ciphers.aead
from cryptography.hazmat.primitives import ciphers

ciphers.aead.AESGCM.generate_key(bit_length=256)

```
