### ISSUE TITLE
Add AEGIS ciphers

### ISSUE THREAD

**Issue by tasket** [pyca/cryptography#11129]
AEGIS is a key committing AEAD cipher [family](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-aegis-aead) based on AES, designed to expand both throughput and security bounds beyond what AES-GCM offers.  A co-author of AEGIS provides an overview of its strengths and increased implementation & adoption [here.](https://crypto.stackexchange.com/a/106125) Notably, there are now AEGIS implementations in the Linux kernel, facebook's [_Fizz_](https://github.com/facebookincubator/fizz) TLS library and _libsodium_.

AEGIS-256 appears to come in different constructions based on the amount of parallelism; these are denoted with a 'X2' or 'X4' suffix.

**Comment by alex** [comment]
At this point, all of our core cryptography operations come from OpenSSL, so unless this is present in OpenSSL (or BoringSSL or LibreSSL) we're not going to offer support for it.
