### ISSUE TITLE
UnexpectedTag Error while loading pem certificate using cryptography

### ISSUE THREAD

**Issue by garv901** [pyca/cryptography#11281]
I have generated an auto-rotated certificate in Azure Key Vault with its type set as PEM. I need to use this to build a ConfidentialClientBuilder app in Azure Synapse notebook (language python). This class needs client_credentials passed to it along with the client_id and authority_url. The client_credentials consists of private_key which needs to be in PEM format. After fetching my cert from AKV, I wrapped the cert value in "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" which is required for pem certs. When passed to the function load_pem_x509_certificate cryptography library (to extract the private key), it throws the error : 

ValueError: error parsing asn1 value: ParseError { kind: UnexpectedTag { actual: Tag { value: 2, constructed: false, class: Universal } }, location: ["RawCertificate::tbs_cert"] }

Cryptography version: 40.0.2
pip version: 22.3.1

Repro steps:
![image](https://github.com/user-attachments/assets/31a81c0a-53a1-4c43-a909-c18324a5d367)
![image](https://github.com/user-attachments/assets/f74aef92-6684-4267-9364-ef738d71a0d3)

Stack Trace:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [173], line 4
      1 from cryptography.x509 import load_pem_x509_certificate, load_der_x509_certificate
      2 from cryptography.hazmat.backends import default_backend
----> 4 cert_obj = load_pem_x509_certificate(pem_private_key_64)

File ~/cluster-env/env/lib/python3.10/site-packages/cryptography/x509/base.py:521, in load_pem_x509_certificate(data, backend)
    518 def load_pem_x509_certificate(
    519     data: bytes, backend: typing.Any = None
    520 ) -> Certificate:
--> 521     return rust_x509.load_pem_x509_certificate(data)

ValueError: error parsing asn1 value: ParseError { kind: UnexpectedTag { actual: Tag { value: 2, constructed: false, class: Universal } }, location: ["RawCertificate::tbs_cert"] }

**Comment by alex** [comment]
The fact that you're referring to this as a private key indicates some sort of confusion: This API is for loading _certificates_. If your bytes contain a private key, you should be using one of our APIs for _key loading_.

**Comment by garv901** [comment]
I am trying to pass this to the ConfidentialClientApplication class of the msal library which requires passing a private key. I was using the load pem cert function so that I could refer to the private key from the created cert object. The key is an auto rotated cert (PEM) generated in Azure Key Vault. What class should I use for this purpose ?

**Comment by reaperhulk** [comment]
A private key and a certificate are very different objects. If you need to load a PEM formatted private key you'll want to use the `load_pem_private_key` function.

**Comment by garv901** [comment]
I was able to resolve the issue, able to fetch the private key using load_key_and_certificates for the pkcs12 format. Thanks a lot for the help!

Unrelated but I am able to fetch private key, public certificate and additional certificates using this function. How could I fetch the SHA1 hex thumbprint for the same azure certificate.

**Comment by alex** [comment]
If you actually mean for a certificate, they have a `fingerprint()` method that will return a hash, which you can then hex-encode yourself.

If you mean for some other datastructure (you've been using certificate, key, and PKCS#12 bundle interchangably, which is confusing us), then the fingerprint is generally just a hash of the raw bytes.
