### ISSUE TITLE
Question: where are the `load_pem_private_key` error messages defined?

### ISSUE THREAD

**Issue by sergei-maertens** [pyca/cryptography#11291]
Not a bug report or feature, just something I've been trying to figure out but fail to do so.

When invoking `cryptography.hazmat.primitives.serialization.load_pem_private_key` on a private key with or without password, either the right or wrong one, we can get various error messages, for example:

```py
TypeError("Password was not given but private key is encrypted")
ValueError("Bad decrypt. Incorrect password?")
```

I've been trying to track down where these errors are defined/raised, but I'm unsuccesful. I'm doing this to get a better understanding of the tools I'm working with.

Places I've searched (using github's code search):

* the pyca/cryptography repository
* sfackler/rust-openssl
* openssl/openssl

The closest I've gotten was in OpenSSL itself where `EVP_R_BAD_DECRYPT ` and `PEM_R_BAD_DECRYPT ` errors are defined, and I could track down the "bad decrypt" string, but not the rest of the bits and it's driving me insane 😄 

Any pointers would be greatly appreciated, and apologies for filing an issue for this.

edit: only the "bad decrypt" is still unclear, should've searched on the other error first and then I would've found https://github.com/pyca/cryptography/blob/3c7a5e07387434ced26e377994cd1a8553997c53/src/rust/src/backend/utils.rs#L451...

**Comment by alex** [comment]
The former comes from https://github.com/pyca/cryptography/blob/main/src/rust/src/backend/utils.rs#L451

The latter isn't directly around since a20d495536742a8a21f74c868b4b95f133228771

**Comment by sergei-maertens** [comment]
oh wow, thanks for the quick reply! I'm an idiot for not searching the former error string sooner. CI ran today with `cryptography==42.0.8` and https://github.com/pyca/cryptography/commit/a20d495536742a8a21f74c868b4b95f133228771 appears to be unreleased, which explains why the github code search (against the main branch) didn't make the error pop up.

I can sleep now, thanks for the super fast reply!
