### ISSUE TITLE
Certificate chain validation always fails with "required EKU not found" error

### ISSUE THREAD

**Issue by kislyuk** [pyca/cryptography#11352]
Hello,

I am trying to validate certificate chains with the `build_client_verifier()` functionality introduced in Cryptography 43. I am finding that verification never succeeds on any certificate chains in use by my counterparty applications, always failing with a "required EKU not found" error.

Upon some digging, EKU (extended key usage) is never set by any applications in my application domain (XML signature/SAML). Key usage can be reasonably expected to be set to "Digital signature" in this case, but EKU should not be expected to be set (and I can't find an appropriate value for it).

Reading through the code (https://github.com/pyca/cryptography/blob/edc43b1d69c7606fd2c7e7e1ace1b6312d8b9565/src/rust/cryptography-x509-verification/src/policy/mod.rs#L333-L338, https://github.com/pyca/cryptography/blob/edc43b1d69c7606fd2c7e7e1ace1b6312d8b9565/src/rust/cryptography-x509-verification/src/policy/extension.rs#L334-L344) it looks to me like there are two issues:

* There is no way to control the EKU assertion behavior in the client verifier policy builder (unlike validation time, max chain depth, etc.)
* The intended behavior appears to be to permit the absence of an EKU, but the actual behavior is to forbid it.

Does this sound right? If so, what's the best way to fix this?

**Comment by alex** [comment]
cc: @woodruffw

**Comment by woodruffw** [comment]
Thanks for the ping! @kislyuk could you provide an example cert you're seeing this with? The "maybe present" logic is pretty well trodden on other extensions so I'd be surprised if it was causing issues just on EKU (and we should have testcases for EKU not present), but an example would help me better isolate this 🙂
