### ISSUE TITLE
Add support for CCM mode (Counter with CBC-MAC)

### ISSUE THREAD

**Issue by wbolster** [pyca/cryptography#1141]
Currently `cryptography` does not support CCM (counter with CBC-MAC) mode (see http://en.wikipedia.org/wiki/CCM_mode).

Adding support for this mode was briefly mentioned/discussed in (now closed) issues/pull requests, e.g.

* https://github.com/pyca/cryptography/pull/394#discussion_r8679933
* https://github.com/pyca/cryptography/pull/176#issuecomment-27059751

...but it doesn't seem to be tracked anywhere currently, hence this issue report.

**Comment by reaperhulk** [comment]
We haven't seen any significant demand for this in 2 years and the API design tradeoffs required for CCM make me extremely reluctant to add support. Closing for now.

**Comment by chrysn** [comment]
Please reconsider the "no significant demand" stance in the light of AES-CCM-64-64-128 being the mandatory-to-implement cipher in the upcoming [OSCOAP](https://mail.tools.ietf.org/html/draft-ietf-core-object-security-02) specification for object security in communication with constrained devices. The Python implementation of it currently falls back to cffi-wrangling libssl itself ([code](https://github.com/chrysn/aiocoap/blob/master/aiocoap/util/crypto.py)), but I'd very much prefer to have a cryptography library provide that instead.

**Comment by reaperhulk** [comment]
There has been some conversation in #2968 around building per-scheme AEAD interfaces. That would allow us to support CCM. Thanks for the link to a spec that is actively using CCM though, that's helpful!
