### ISSUE TITLE
MultiFernet Support for `extract_timestamp`

### ISSUE THREAD

**Issue by maxmelamed** [pyca/cryptography#11426]
I am wondering if there's a reason `MultiFernet` does not support easy timestamp extraction without accessing the underlying individual `Fernet` instances like so:
```
f1 = Fernet(Fernet.generate_key())
f2 = Fernet(Fernet.generate_key())
mf = MultiFernet([f1, f2])
e = mf.encrypt(b'foo')
# if I want to know the timestamp at which `e` was encrypted, I need to do:
mf._fernets[0].extract_timestamp(e)
# this of course may fail if `e` was encrypted using an instance other than mf._fernets[0]
# so I'll have to do the following:
for f in mf._fernets:
    try:
        ts = f.extract_timestamp(e)
    except InvalidToken:
        continue
````

Would be nice if `MultiFernet` would just provide the above as a convenience. If there is no reason not to have it, I am happy to open a PR myself to add it

**Comment by alex** [comment]
I don't think there's a particularly strong reason, no. We'd be happy to
take a PR for this.

Thanks
