### ISSUE TITLE
cryptography wheel for iOS (arm64)

### ISSUE THREAD

**Issue by Sorrow91** [pyca/cryptography#11463]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
`cryptography-43.0.0`
* How you installed ``cryptography``
`pip install cryptography`
* Clear steps for reproducing your bug
I'm trying to use `cryptography` with the Python-Framework and PythonKit for iOS in swift.

Since rust is needed it creates a binary (`_rust.abi3.so`) in bindings where I get this error:

`.simruntime/Contents/Resources/RuntimeRoot/Users/kevin/Library/Developer/CoreSimulator/Devices/5D10560B-E4C2-4367-A773-1E8EB170E278/data/Containers/Bundle/Application/CA01303A-7E6E-45A5-81FA-21834A8936AC/pythontest.app/PythonScripts/cryptography/hazmat/bindings/_rust.abi3.so' (no such file), '/Users/kevin/Library/Developer/CoreSimulator/Devices/5D10560B-E4C2-4367-A773-1E8EB170E278/data/Containers/Bundle/Application/CA01303A-7E6E-45A5-81FA-21834A8936AC/pythontest.app/PythonScripts/cryptography/hazmat/bindings/_rust.abi3.so' (mach-o file (/Users/kevin/Library/Developer/CoreSimulator/Devices/5D10560B-E4C2-4367-A773-1E8EB170E278/data/Containers/Bundle/Application/CA01303A-7E6E-45A5-81FA-21834A8936AC/pythontest.app/PythonScripts/cryptography/hazmat/bindings/_rust.abi3.so), but incompatible platform (have 'macOS', need 'iOS-sim'))
`

Is the a working `universal` or `arm64` wheel for the iOS-Platform?

Thank you

**Comment by reaperhulk** [comment]
There are no precompiled binaries for iOS (simulator or otherwise -- note that iOS-sim is a different target than device). We'd happily take a docs PR describing how to build this, but we don't have familiarity with development on that platform.

**Comment by Sorrow91** [comment]
Thank you for your reply. An updated doc how to build it for arm64 would be awesome!

**Comment by alex** [comment]
To be clear: That's something we'd accept a a PR for. We have no familiarity with developing for iOS with Python, so we can't write it.

**Comment by LWKHSOFICIAL** [comment]
Olá Pessoal dá Área Comercial de: - Technologia e Informáthica e T.I ou Seja Tanto faz tou Nem aí....
