### ISSUE TITLE
In FIPS mode, RSA OAEP padding is refused with an error message: "This combination of padding and hash algorithm is not supported by this backend"

### ISSUE THREAD

**Issue by flo-renaud** [pyca/cryptography#11512]
ipa replica installation fails in FIPS mode because the RSA OAEP padding is refused by python-cryptography.

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
Python 3.12.5
python3-cffi-1.15.1-6.fc39.x86_64
python3-cryptography-41.0.7-1.fc39.x86_64
openssl-3.1.4-3.fc39.x86_64

* How you installed ``cryptography``
From fedora 39 rpm 

* Clear steps for reproducing your bug

1. install IPA server on a FIPS-enabled machine: `dnf install -y freeipa-server-dns && ipa-server-install --domain ipa.test --realm IPA.TEST --setup-dns --auto-forwarders -a Secret123 -p Secret123 -U`
2. install IPA replica on a FIPS-enabled machine: `dnf install -y freeipa-server-dns && ipa-replica-install --domain ipa.test --realm IPA.TEST --principal admin --password Secret123 -U --server server.ipa.test`
The installation fails with:
```
...
Configuring certificate server (pki-tomcatd)
  [1/2]: configure certmonger for renewals
  [2/2]: Importing RA key
  [error] UnsupportedAlgorithm: This combination of padding and hash algorithm is not supported by this backend.
Your system may be partly configured.
Run /usr/sbin/ipa-server-install --uninstall to clean up.

This combination of padding and hash algorithm is not supported by this backend.
The ipa-replica-install command failed. See /var/log/ipareplica-install.log for more information
```

See also the discussion in https://issues.redhat.com/browse/RHEL-40210

**Comment by alex** [comment]
So this happens if the hash used with OAEP (or MGF1) is not one of: sha1, sha224, sha256, sha384, or sha512.

I don't see the code here, so I can't tell which hash is being used.

**Comment by alex** [comment]
Sorry, sha1 is only available if FIPS is disabled, with FIPS (as you have), it's rejected.

**Comment by reaperhulk** [comment]
Looking at the underlying bug it looks like maybe the expectation is that we shouldn't be blocked SHA1 for MGF1 in FIPS. Is that what the concern is? If we've made a mistake we're happy to take a patch, although the 140-3 transition may complicate what is allowed/disallowed here.

**Comment by flo-renaud** [comment]
According to this [comment](https://issues.redhat.com/browse/RHEL-40210?focusedId=25437741&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25437741) this padding shouldn't be blocked for MGF in FIPS mode.

**Comment by alex** [comment]
Hmm, do we hvae a citation to FIPS itself?

**Comment by abbra** [comment]
NIST SP 800-56B REV. 2 says in "5.1 Cryptographic Hash Functions":
> In this Recommendation, cryptographic hash functions may be used for mask generation during
> RSA-OAEP encryption/decryption, in key derivation, and/or in MAC-tag computation during key
> confirmation. An approved hash function shall be used when a hash function is required (see FIPS
> 180[10] and FIPS 202[11]).

https://csrc.nist.gov/news/2022/nist-transitioning-away-from-sha-1-for-all-apps says 
> NIST will transition away from the use of SHA-1 for applying cryptographic protection to all applications by December 31, 2030.  Note that after this termination date, it may be necessary to use SHA-1 for handling information protected prior to the termination date; the [SHA-1 specification](https://doi.org/10.6028/NIST.FIPS.180-1) will remain available for this purpose.

Right now SHA-1 use is not prevented in RSA OAEP and MGF1 cases.
