### ISSUE TITLE
Implement CBC-MAC

### ISSUE THREAD

**Issue by wbolster** [pyca/cryptography#1154]
Issue #786 was about implementing both CMAC and CBC-MAC. However, that issue was closed when support for CMAC went in.

CBC-MAC is currently not supported by `cryptography`, and having support for it could possible serve as a building block for CCM mode, as discussed in #1141.

**Comment by reaperhulk** [comment]
In the year and a half since this issue was filed we haven't seen a significant use case for CBC-MAC, so I'm closing this for now. It can be reopened if one comes up.

**Comment by wbolster** [comment]
@reaperhulk yeah agreed. i just opened this issue because i noticed #786 left a gap when it was closed.
