### ISSUE TITLE
Releasing GIL in cryptographic operations

### ISSUE THREAD

**Issue by JakubKahovec** [pyca/cryptography#11585]
I'd like to ask if GIL gets released when cryptographic operations are being performed as I can't find it in the code, i.e https://github.com/pyca/cryptography/blob/60913069bb27d788c57687840a8b1b54904e9139/src/rust/src/backend/kdf.rs#L10

**Comment by alex** [comment]
Not really. I thought we did for things like scrypt, but I don't see it, so
I guess not. I'd be open to taking PRs for these though
