### ISSUE TITLE
Feature Request: ability to use external signatures in `cryptography.x509.CertificateBuilder` and `cryptography.x509.CertificateSigningRequestBuilder`

### ISSUE THREAD

**Issue by sosthene-nitrokey** [pyca/cryptography#11616]
The builder structures for Certificates and CSRs do not expose their `tbs` data, and do not allow adding a signature computed outside of `cryptography`.

This feature request asks to add this functionality to cryptography.

In OpenSSL, this corresponds to the functions, which should be exposed as part of the builder structures for CSRs and Certificates:

- `i2d_re_X509_tbs`
- `i2d_re_X509_REQ_tbs`
- `X509_set0_signature`
- `X509_REQ_set1_signature_algo`

Our use case: We want to be able to build and sign certificates and CSRs using a PIV smartcard, and the lack of this feature means we have to use another library, despite `cryptography` already being used in other parts of our project.

**Comment by alex** [comment]
This can be done by providing a custom signer.

https://github.com/reaperhulk/vault-signing shows what a custom signer
looks like.
