### ISSUE TITLE
building cryptography 43.0.1 with setuptools-rust

### ISSUE THREAD

**Issue by Ganeshkumhar1** [pyca/cryptography#11660]
I see latest cryptography 43.0.1 is using maturin for builds. I am curious is there still a way to build cryptography 43.0.1 using old setuptools-rust?

asking this as I am build cryptography for solaris sparc 11.4 platform and , I was able to build it using setuptools-rust.
I am unable to build maturin on solaris sparc seems it is not supported on this platfrom. so checking if there is away out here.

any lead/help will be appreciated. Thanks

**Comment by alex** [comment]
No, we no longer support building with setuptools-rust. Your best bet is to file an issue with maturin.

**Comment by barracuda156** [comment]
It is very disappointing to see rust being forced upon everyone.
