### ISSUE TITLE
Trying to install cryptography on chromebook results in error.

### ISSUE THREAD

**Issue by bjorn3ssen** [pyca/cryptography#11696]
When i run the command: pip install cryptography   i get an error
![Screenshot 2024-10-04 17 46 00](https://github.com/user-attachments/assets/11248833-89ce-4511-815a-31b4ac35e7ac)

I also tried running the same command in pythonn itself but that doesn't work as well.

I dont know what to do in this situation, please help me as fast as possible.

**Comment by bjorn3ssen** [comment]
@alex how do i create a virtual environment on chromebook?

**Comment by alex** [comment]
We cannot provide basic python support here
