### ISSUE TITLE
Intel on-die CA contains NULL parameter in signature algorithm parameters (CryptographyDeprecationWarning)

### ISSUE THREAD

**Issue by shane-kearns** [pyca/cryptography#11723]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using

Python 3.12.5
cryptography==43.0.1
cffi==1.16.0
pip==23.3.2
setuptools==69.1.1

* How you installed ``cryptography``

`pip install cryptography` on windows 10

* Clear steps for reproducing your bug

The CA certificate can be obtained from https://tsci.intel.com/content/OnDieCA/certs/OnDie_CA_RootCA_Certificate.cer as an official source.

```py
from cryptography import x509
with open("OnDie_CA_RootCA_Certificate.cer", "rb") as f:
    x509.load_der_x509_certificate(f.read())
```

> sys:1: CryptographyDeprecationWarning: The parsed certificate contains a NULL parameter value in its signature algorithm parameters. This is invalid and will be rejected in a future version of cryptography. If this certificate was created via Java, please upgrade to JDK21+ or the latest JDK11/17 once a fix is issued. If this certificate was created in some other fashion please report the issue to the cryptography issue tracker. See https://github.com/pyca/cryptography/issues/8996 and https://github.com/pyca/cryptography/issues/9253 for more details.
<Certificate(subject=<Name(C=US,ST=CA,L=Santa Clara,O=Intel Corporation,OU=OnDie CA Root Cert Signing,CN=www.intel.com)>, ...)>

I don't know how the certificate was generated, but the presence of long life CA root certificates with this problem suggests that they will need to be supported for a long time as well.

Attached zip contains the Intel root and intermediate certs.
Some of the intermediate CA certs have the same problem.
The older root `EKRootPublicKey.cer` is not affected.
[Intel-CAs.zip](https://github.com/user-attachments/files/17296571/Intel-CAs.zip)

**Comment by alex** [comment]
Wunderbar. Someone should tell Intel that their certificate is bad and that they should feel bad. Is that something you'd be able to do?

As this is only a deprecation warning, I think the only action item for us here is adding a comment so we're aware about this in the future.

**Comment by shane-kearns** [comment]
I don't have any contact at Intel unfortunately. I came across this as part of a package of TPM CA certificates.
