### ISSUE TITLE
not able to build cryptography 43.0.1 on solaris

### ISSUE THREAD

**Issue by Ganeshkumhar1** [pyca/cryptography#11732]
$ python -m build --wheel --no-isolation .
* Getting build dependencies for wheel...
* Building wheel...
Running `maturin pep517 build-wheel -i /home/user/python/bin/python --compatibility off`
📦 Including license file "/home/user/cryptography/43.0.1/cryptography-43.0.1/LICENSE"
📦 Including license file "/home/user//cryptography/43.0.1/cryptography-43.0.1/LICENSE.APACHE"
📦 Including license file "/home/user//cryptography/43.0.1/cryptography-43.0.1/LICENSE.BSD"
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.7
💥 maturin failed
  Caused by: The architecture sparcv9 is not supported
Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/user/python/bin/python', '--compatibility', 'off'] returned non-zero exit status 1

ERROR Backend subprocess exited when trying to invoke build_wheel

it is failing "The architecture sparcv9 is not supported"

I was able to build earlier version on cryptography on solaris for eg cryptography 42.0.7 ( without maturin) seems 43.0.1 requires maturin to build. 
Please suggest a way out here.

**Comment by reaperhulk** [comment]
Have you opened an issue with maturin? You filed this same issue two weeks ago (https://github.com/pyca/cryptography/issues/11660) and we suggested you do that at the time.

**Comment by Ganeshkumhar1** [comment]
https://github.com/PyO3/maturin/issues/2239   got this fixed. Thanks.
