### ISSUE TITLE
Cryptography - upgrade from v3.2.1 to v43.0.1 for the freebsd v11.4 not straightforward. Need to check if we can have any solution.

### ISSUE THREAD

**Issue by ajayhb** [pyca/cryptography#11760]
**OS:** Freebsd-11.4
**Python:** v3.9
**OpenSSL:** v3.0.0
**setuptools**: v51.1.2
**cryptography current version:** 3.2.1

**Scenario:** Want to upgrade cryptography to v.43.0.1 and have it's egg file generated for freebsd. Trying to build the rust compiler for the same, as it is mandatory from v35 and above. 

**Issue:** Not able to build or download cargo ( package manager of rust, which is a link between cryptography and rust). Therefore stuck. Now, I'm trying to find an egg file of cryptography v43.0.1 online, which is compatible for freebsd-11.4. which I can directly include in the build, instead of building one.
This is the last resort that I need to make. Org doesn't want to upgrade freebsd at the moment.
Any suggestion on what are the possible solutions to get the cryptography latest package in freebsd as egg file, online or via build? (if any)

**Comment by alex** [comment]
First: egg files are not used in the Python ecosystem, and haven't been for years. Wheels are what are used.

We don't publish wheels for FreeBSD, so unfortunately you're on your own.

As far as I can tell, FreeBSD is EOL, and has been for 3 years. We don't generally provide support for EOL software.
