### ISSUE TITLE
Build failed with openssl 0.10.67

### ISSUE THREAD

**Issue by Tarnum-tst** [pyca/cryptography#11778]
i686-pc-windows-gnu ; MSRV 1.63 with 604594fc123ce0797ee45417ed315871922562fe reverted.
error[E0432]: unresolved import `std::ffi::c_char`
  --> C:\Users\User\.cargo\registry\src\github.com-1285ae84e5963aae\openssl-0.10.67\src\kdf.rs:28:24
   |
28 |         use std::ffi::{c_char, c_void};
   |                        ^^^^^^ no `c_char` in `ffi`

Solved this by replacing 'use std::ffi::{c_char, c_void};' (line 28, kdfs.rs) with 'use libc::{c_char, c_void};'

**Comment by alex** [comment]
This is a rust-openssl bug, please file an issue there
