### ISSUE TITLE
I am having unknown key value error

### ISSUE THREAD

**Issue by Aswin2203** [pyca/cryptography#11814]
I am trying to generate a x509 certificate for a dilithium key pair which is PQC algorithm approved by NIST. while which I got this error ''ValueError: Unknown key type: 1.3.6.1.4.1.2.267.12.6.5'' as I guess this library don't have a support to it. Are there any other alternatives or will this be supported in future versions or releases.

**Comment by alex** [comment]
We don't support dillithium keys, and we won't until OpenSSL has support for them.
