### ISSUE TITLE
copy.copy for private keys

### ISSUE THREAD

**Issue by joakimnordling** [pyca/cryptography#11859]
Private keys (at least RSAPrivateKey) can not be copied in cryptography 43.0.3:
```
>>> import copy
>>> from cryptography.hazmat.primitives.asymmetric import rsa
>>> private_key = rsa.generate_private_key(
...     public_exponent=65537,
...     key_size=2048,
... )
>>> copied_key = copy.copy(private_key)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jocke/.pyenv/versions/3.11.7/lib/python3.11/copy.py", line 92, in copy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'cryptography.hazmat.bindings._rust.openssl.rsa.RSAPrivateKey' object
```

There was a similar issue for public keys reported in https://github.com/pyca/cryptography/issues/9403 and it seems like the fix to that issue only made it possible to copy all the public keys, not any of the private ones.

**Comment by joakimnordling** [comment]
The actual use case I had was to make my own `RsaPrivateKey` (note the lower case `sa`) subclass of the `SecretStr` from [pydantic](https://docs.pydantic.dev/) so that I could have an environment variable with a private key in PEM format and get it parsed to this "RsaPrivateKey" subclass when loading the settings for my app. My thought was that I would in the `__init__` use the `load_pem_private_key` to parse the key to the `RSAPrivateKey` (the one from cryptography with capital `SA`) and store it as an instance variable for later use, similar to how for example the `last4` is done in the [PaymentCardNumber](https://github.com/pydantic/pydantic/blob/main/pydantic/types.py#L1863). The problem is that pydantic decides that it wants to copy the object for some reason when initing the settings (I didn't investigate deeply why it wants to do that). And the reason I want to do it in the init and save it is to avoid doing the `load_pem_private_key` multiple times, as it's somewhat slow on larger keys. I hope this was not too confusing and I can try to explain in more detail if needed. But in short it's somewhat similar to wrapping it into a dataclass.

**Comment by joakimnordling** [comment]
I agree it's weird that it does that deepcopy, but still I don't see that as a reason why cryptography shouldn't support copying the key. There's likely sooner or later some other use case for it and shouldn't be many lines of change to support it, if it's immutable. So I'd rather ask the question as why should the RSAPrivateKey not support copying?

As a temporary workaround for my particular use case I implemented a `__deepcopy__` on the pydantic model itself where I pass the same RSAPrivateKey forward to the new instance by adding an optional extra field to the `__init__`. A bit of an ugly solution, but it works. And if it was unclear, the stuff it does when initializing the class does a deepcopy on the whole class (and then recursively would have copied the key), not just the key itself.

**Comment by joakimnordling** [comment]
Sorry, I'm a bit unsure if there was some question that was intended for me to respond to or not.

I agree with you that you need to be careful to not get stuck in a corner when adding features.

But to be honest, I've not ever thought of "being possible to be copied" as being a feature really. Out of my head I can't really think of any python class instances that can't be copied. I guess there are some examples of such, but as said, can't think of any such ones quickly. I guess the closes thing I can think of is integers, which are immutable and aren't really copied in memory. If you try to make a copy of an integer, you actually get the same integer back, so in that sense they do support copying despite not really being copied in memory. From what I understand from what you wrote earlier I guess the same kind of thing would hold for most keys at least, they are immutable, so the copy action would in essence be a matter of returning the instance itself.

I'm trying to think of cases where a private key could not be copied. I guess a good reason for that could be if the key would somehow contain a state. But if they are immutable, I doubt they should be able to keep a state. Also thinking a bit about some hardware keys (not something I really know almost anything of), but there I'm guessing you'd have some reference to the communication to the device as the object and copying that could likely also be handled as just returning the same object. However if it then has some API to close the connection or such, then doing that on one of the instances would close it for the other one as well. I guess this could be dealt with by documenting the behaviour in that case (also wondering if it's immutable then). But the ways different keys etc work goes way beyond my field of expertise.

I've got a workaround that is a bit ugly, but works, I can live with that. If you can make it possible to copy the private keys (the public ones were earlier made possible to copy) that would be great. I'm not sure if it would be possible to support the copy action on just some keys or does it then need to be supported also for all future kind of keys? If not, then one option could be to possibly support it only on the currently known keys.

If I'd have infinite amount of time I could look into why pydantic wants to do the copying, but the path that is taken is far from clear and evident to me and I'd simply have to put more time into it than I can spend on it, sorry about that. My quick thought was that it's weird the RSAPrivateKey doesn't support being copied (as said, can't think of any other type out of my head that fails a copy, even the integers return the same integer), spotted the similar thing for the public keys was changed and thought this was just a mistake this was not fixed for the private keys at the same time and something that might come as a bad surprise for someone else later.

**Comment by alex** [comment]
An example of a Python object that can't be copied with `copy.copy` is a `socket`. So my concern would be that something like https://github.com/reaperhulk/vault-signing/blob/main/src/vaultsigning/key.py (i.e., a key that lives somewhere over a network) might not have an obvious implementation of `__copy__`.

Similarly, a PKCS#11 hardware-backed key might not have an obvious implementation.

That said, because all of our `PrivateKey` interfaces treat the key as immutable, `return self` may be a sufficient implementation?

The one limitation, such as it is, would be if you wanted to implement our `PrivateKey` _and_ provide other mutable state APIs on the same class. Probably that's just tough luck?

@reaperhulk do you have an opinion? I'm basically persuaded that we should provide `def __copy__(self): return self` on all these key types.

**Comment by joakimnordling** [comment]
> That said, because all of our PrivateKey interfaces treat the key as immutable, return self may be a sufficient implementation?

I think so and it'd be enough at least for my use-case and those I can think of.

> The one limitation, such as it is, would be if you wanted to implement our PrivateKey and provide other mutable state APIs on the same class. Probably that's just tough luck?

Sounds OK to me. But I don't think my vote should count. But in those cases where you'd want to do that, can't you then just override the `__copy__` in that class to do an actual copy (unless it's using some hardware/socket etc)? So the limitation would in essence then be a case where you need mutable state and aren't able to provide a custom `__copy__`, which hopefully is a pretty unlikely case.

**Comment by reaperhulk** [comment]
I don't have any remaining objections based on this thread. Alternate implementations may need to fail or do some work to clone new handles (PKCS11, etc) but that's their cross to bear.

@joakimnordling would you be interested in submitting the PR?

**Comment by joakimnordling** [comment]
I don't think my non-existing rust skills are on that level :D 

On the other hand, I guess the rust part would be merely to copy&paste the same that was made in https://github.com/pyca/cryptography/commit/212fa583b1eeb0ec4243ce84dc70b73ec2da137f into correct private key classes and then add test (on Python side).

Not sure what to say; if needed to get the change done, I could give it a try, but wouldn't at all mind if someone else would do it.

**Comment by alex** [comment]
Ok! I've marked it for the next release, so if you're up for it, wonderful -- and we're happy to help -- or we'll get to it.

**Comment by joakimnordling** [comment]
@alex thanks! There's a PR (https://github.com/pyca/cryptography/pull/12110) for that now. I hope I've not overlooked anything. There's also a small comment in the PR about the DHPrivateKey (was a bit unsure about generating a strong one or skipping on FIPS).

**Comment by alex** [comment]
Thanks!
