### ISSUE TITLE
Running issues in the Win7 environment

### ISSUE THREAD

**Issue by boysj** [pyca/cryptography#11885]
When I referenced cryptography, I found that my program cannot run on Win7.When I uninstall the package and republish it, it starts normally. Can you solve it

**Comment by alex** [comment]
No, as we documented in our changelog: https://cryptography.io/en/latest/changelog/#v42-0-7 windows 7 has been unsupported since cryptography 43.

Windows 7 has been unsupported by Microsoft for years at this point.
