### ISSUE TITLE
Error while using the library

### ISSUE THREAD

**Issue by rithulaa** [pyca/cryptography#11904]
I'm encountering an error with the cryptography library in an AWS Lambda function running on Python 3.12. Despite following standard procedures to include the library as a Lambda Layer, I consistently receive the error: "Unable to import module 'lambda_function': cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)". It appears to be a compatibility issue between the cryptography library and AWS Lambda's runtime environment. I've verified that the library and dependencies are properly packaged, yet the Lambda function fails to import due to an issue with the _rust binding. Any guidance on resolving this compatibility issue or insights into the root cause would be appreciated.
![image](https://github.com/user-attachments/assets/19362795-e57c-4339-a42a-37f036c2d6ef)

**Comment by reaperhulk** [comment]
This error almost always means you are not installing the correct version of cryptography. Cryptography contains native code and execution on lambda is dependent on using the appropriate manylinux wheel. Please give us more details about how you're installing cryptography and verify which wheel is being installed.

**Comment by LeHieu1906** [comment]
Dear reaperhulk
I am encountering  the same problem, I will list information below
Python: 3.10
Cryptography: 3.3.2
<img width="515" alt="image" src="https://github.com/user-attachments/assets/e43070bc-1df1-4545-b649-acec546cfff0">
Please let me know if you have any idea to resolve this problem. I am looking forward from u !!! thanks so much.

**Comment by rithulaa** [comment]
> This error almost always means you are not installing the correct version of cryptography. Cryptography contains native code and execution on lambda is dependent on using the appropriate manylinux wheel. Please give us more details about how you're installing cryptography and verify which wheel is being installed.

I created a folder on my local machine, then opened the terminal to install Paramiko for SFTP connectivity using the command `pip install paramiko -t .`. Afterward, I zipped the folder and uploaded it to my Lambda function. I then moved all the folder contents from the `lib` directory to the main function directory. However, when I try to run the API with `import paramiko`, I encounter the error I mentioned above. I am using Python 3.12 as the runtime for Lambda, and I downloaded the latest version of the `cryptography` module.

**Comment by reaperhulk** [comment]
Unless you are running your own machine on the correct Linux distribution that method will not work. https://cryptography.io/en/latest/faq/#i-m-getting-errors-installing-or-importing-cryptography-on-aws-lambda

**Comment by reaperhulk** [comment]
We are a volunteer project and cannot provide support for arbitrary environments like Lambda. This request would be better directed at AWS for improved documentation.

**Comment by rithulaa** [comment]
Thank you for your assistance, sir.
