### ISSUE TITLE
certificate request with empty subject name is restricted

### ISSUE THREAD

**Issue by mfmarche** [pyca/cryptography#11960]
Related to #11201 , lets encrypt no longer recommends a subject name when using long domain names: 

https://community.letsencrypt.org/t/simplifying-issuance-for-very-long-domain-names/207924

A suggested fix could be to change:

https://github.com/pyca/cryptography/blob/main/src/cryptography/x509/name.py#L65

NameOID.COMMON_NAME: (1, 64) 

to

NameOID.COMMON_NAME: (0, 64)

**Comment by alex** [comment]
Can you please explain the problem you're having in a bit more detail? This limit refers to the _length_ of a common name, not its presence.

It reflects this ASN.1 from RFC5280:

```
X520CommonName ::= CHOICE {
      teletexString     TeletexString   (SIZE (1..ub-common-name)),
      printableString   PrintableString (SIZE (1..ub-common-name)),
      universalString   UniversalString (SIZE (1..ub-common-name)),
      utf8String        UTF8String      (SIZE (1..ub-common-name)),
      bmpString         BMPString       (SIZE (1..ub-common-name)) }

```

**Comment by mfmarche** [comment]
Hi,

thanks for your response. When I tried to not set a CN, I hit the following:

https://github.com/pyca/cryptography/blob/main/src/cryptography/x509/base.py#L748

        if self._subject_name is None:
            raise ValueError("A CertificateSigningRequest must have a subject")


Also note, when I tried to comment that piece of code out, the following was hit:

>       return rust_x509.create_x509_csr(
            self, private_key, algorithm, rsa_padding
        )
E       AttributeError: 'NoneType' object has no attribute 'rdns'


Suggesting further restrictions of a missing subject name in the rust code.

**Comment by alex** [comment]
It has to have a subject, but that subject may be empty: `x509.Name([])` is a cromulent subject.
