### ISSUE TITLE
Our GCM API exposes un-authenticated plaintext

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1199]
That's like... bad. We should probably come up with an AEAD API. This also times into #1141, since arguably streaming makes no sense for authenticated stuff.

https://www.imperialviolet.org/2014/06/27/streamingencryption.html

money quote: """I will even claim that the existance of an API that can operate in a streaming fashion over large records (i.e. will encrypt and defer the authenticator and will decrypt and return unauthenticated plaintext) is a mistake."""

We'd need to design a new API, and deprecate the existing one.

**Comment by simo5** [comment]
I'm curious,
why not simply use a chunked Fernet like construction where the MAC/digest of the previous chunk is used as input with the next chunk (to chain together all the parts) ? AEAD algorithms can handle this case very well.
Chunk Size can be defined in a (signed) header at the top of the file/stream, the header is he only special chunk and it is chained into the first chunk by its digest as well.
The key may be re-derived for each chunk or not.

**Comment by reaperhulk** [comment]
I have a nebulous plan to extract the authenticated encryption construction in Tahoe-LAFS and adapt it into a recipe (CTR + a merkle tree to be able to rapidly auth arbitrary bytes and make it seekable), but I haven't had a chance to write that up.

Fernet isn't a great candidate for a chunked/streaming API since it isn't seekable due to the use of CBC.

**Comment by simo5** [comment]
Do you want seekability in order to allow access to stored files and not just have a streaming format ?

**Comment by reaperhulk** [comment]
I'm going to be comfortable closing this issue once we have an AESGCM AEAD class since we can link in the docs to have users use the one shot APIs by preference and only fall back to the nasty streaming API if absolutely necessary.

**Comment by alex** [comment]
We now have an AES-GCM AEAD, so declaring this closed. Maybe some day we can think about deprecating the streaming API.
