### ISSUE TITLE
[RFE] last_update_utc and next_update_utc properties for CertificateRevocationList 

### ISSUE THREAD

**Issue by yrro** [pyca/cryptography#12006]
`Certificate` has `not_valid_before_utc` and `not_valid_after_utc` properties which return timezone-aware datetime objects. The corresponding properties which return timezone-naive datetime objects have been deprecated.

`CertificateRevocationList` has `last_update` and `next_update` properties that return timezone-naive datetime objects. There are no properties that return timezone-aware datetime objects.

It would be nice if `CertificateRevocationList` would be enhanced with `last_update_utc` and `next_update_utc` properties.

**Comment by alex** [comment]
These exist, they were added a year ago in #9661

**Comment by yrro** [comment]
You're quite right, I must have been looking at out of date documentation. Sorry for the noise!
