### ISSUE TITLE
pkcs7.serialize_certificates don't serialize certificate in the given order

### ISSUE THREAD

**Issue by emericv** [pyca/cryptography#12005]
I use cryptography version 43.0.3 from pip install on Ubuntu 24.04 LTS (openssl 3.0.13-0ubuntu3.4)

When I call pkcs7.serialize_certificates([cert1, cert2], serialization.Encoding.PEM), the certificates are written in the wrong order.

There is a way to force a specific order?

**Comment by alex** [comment]
In PKCS#7, certificates are stored in a `SET OF` datastructure. The ASN.1 DER specification requires that `SET OF` elements must be serialized in sorted lexicographic order.

As a result, no, there's no way to control the ordering of certificates when using `pkcs7.serialize_certificates()`.

The correct solution is that consumer of PKCS#7 cert bundles shouldn't rely on order for anything.

**Comment by emericv** [comment]
@alex, thanks for your answer, I will close this request...
