### ISSUE TITLE
Installing cryptography on EC2 (Amazon 3.10 Linux)

### ISSUE THREAD

**Issue by mhils** [pyca/cryptography#1203]
Hi guys,

we apparently have some users that are using mitmproxy (and thereby cryptography) on EC2. It looks like installing cryptography on this setup causes some problems, as discussed in https://github.com/mitmproxy/mitmproxy/issues/282#issuecomment-47437228 . I have no idea why six is not upgraded although cryptography lists `six>=1.4.1` as a requirement. After all, cryptography should work with Python 2.6 as well. Is this fixable from your side somehow?

Thanks!
Max

**Comment by reaperhulk** [comment]
@dstufft is this something pip/setuptools has fixed in the past few months?

**Comment by reaperhulk** [comment]
I tested this in a new virtualenv following the steps @alex listed
```
pip install six==1.2
pip install cryptography
```
and it properly upgraded six to >=1.4.1 (1.9.0 as of this post). Closing as fixed (by either current pip or current setuptools).
