### ISSUE TITLE
Nonce greater than 96 bit for AES GCM SIV?

### ISSUE THREAD

**Issue by dance321** [pyca/cryptography#12048]
When generating a nonce, I know the current standard is to use a 96 bit nonce. However, is it possible to generate one that's higher, like 128 bit or 256 bit nonces?

When I try:

```
aesgcmiv = AESGCMSIV(key)
nonce = os.urandom(32)       # Trying to generate 256 bit nonce
aesgcmiv.encrypt(nonce, data, None)


> ValueError: Nonce must be 12 bytes long
```

I get that `ValueError` if I try to use a nonce that's randomly generated to be more than 96 bits. That got me curious on why 96 bit nonce was the maximum here. So I found some of [these answers on the security stack exchange](https://crypto.stackexchange.com/questions/41601/aes-gcm-recommended-iv-size-why-12-bytes), and it suggested that while 96 bit is pretty secure if the nonce is securely randomly generated, a longer bit nonce will have even better bounds before collision happens (ie 128 bit nonce):

> When the IV is 96-bit long, the 4 byte counter for the internal CTR cipher is always 1. When the IV has a different length, the 4 byte counter for CTR is taken from the GHASH of the IV - so it is uniformly randomized across 32 bits. That means that - when the IV is taken from an RNG, which is what everybody does - due to the birthday paradox it seems more secure (though slower) to supply a non-standard 128-bit IV than a standard 96-bit IV

> A 96 bit nonce is more secure than longer nonces only when combined with a counter (and - informally - only if you create a lot of ciphertexts under the same key). A longer nonce is not less secure in case nonces are generated randomly (which is by far the most common approach).

I don't know much about cryptography, but based on above, would if it be possible to have `AESGCMSIV()` accept a nonce larger than 96 bits for this module?

**Comment by reaperhulk** [comment]
AES-GCM and AES-GCM-SIV are similar but not identical. Our GCM implementation allows (nearly) arbitrary nonce length, but the GCM-SIV requires a 96-bit nonce due to its structure. You can see the spec in RFC 8452.

**Comment by dance321** [comment]
Thanks, didn't know that AES GCM SIV had a hard limit of 96 bit!
