### ISSUE TITLE
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

### ISSUE THREAD

**Issue by bigb-me** [pyca/cryptography#12043]
**Hi i'm getting the error:**

Traceback (most recent call last):
  File "C:\Users\--\OneDrive\Desktop\OneDrive Dump\Messenger v7.py", line 10, in <module>
    from cryptography.fernet import Fernet
  File "C:\Users\--\AppData\Roaming\Python\Python39\site-packages\cryptography\fernet.py", line 14, in <module>
    from cryptography.exceptions import InvalidSignature
  File "C:\Users\--\AppData\Roaming\Python\Python39\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.
>>> 

I have no clue how to fix this, I have tried installing cryptography in a virtual environment:
python -m venv myenv
myenv\Scripts\activate
pip install cryptography

I tried coping the - cryptography and cryptography-43.0.0.dist-info folder (from another laptop where cryptography works) onto this device, wich gives the same error on this device

I have tried going to the Rust website and installing it - I installed and verified with: rustc --version.

When compiling the code into exe (with auto-py-to-exe) it works on this devise. 

I got this error when adding encryption to my code, the error also happens on smaller pieces of code so, to keep this short I will just show a small example program wich still gives the error. It is below:

from cryptography.fernet import Fernet

key = Fernet.generate_key()
cipher = Fernet(key)
message = "Test message."
encrypted_message = cipher.encrypt(message.encode())
decrypted_message = cipher.decrypt(encrypted_message).decode()

print(f"Original message: {message}")
print(f"Encrypted message: {encrypted_message}")
print(f"Decrypted message: {decrypted_message}")

**OS:**
Windows 10

**Installed with:**
pip install cryptography  
**I also tried:**
pip install cryptography --no-binary cryptography

Help would be appreciated!

**Versions:**
Cryptography Version: 43.0.0
Python 3.9.0
pip 24.3.1
Setuptools Version: 75.6.0

**Comment by bigb-me** [comment]
> Try upgrading to a later Python version (3.9.x or otherwise). See #11325

Upgrade to a higher VS then my current 3.9.0?

**Comment by reaperhulk** [comment]
Yes.

**Comment by bigb-me** [comment]
> Yes.

Looks like the problem was with Python 3.9 (is currently working with 3.13

**Comment by reaperhulk** [comment]
Glad it worked. For future people who might find this issue: 3.9.0 and 3.9.1 specifically have a bug that causes this. Upgrading to a later 3.9.x bugfix release or a newer Python (3.10+) will resolve it.

**Comment by NB-Dragon** [comment]
> Glad it worked. For future people who might find this issue: 3.9.0 and 3.9.1 specifically have a bug that causes this. Upgrading to a later 3.9.x bugfix release or a newer Python (3.10+) will resolve it.

I am using python 3.10.0, but the problem happened again. Does the Python (3.10+) you mentioned include 3.10.0?
Cryptography Version: 43.0.0 and 44.0.0
pyOpenSSL version: 24.3.0

**Comment by reaperhulk** [comment]
Are you on windows 7?

**Comment by NB-Dragon** [comment]
> Are you on windows 7?
> 
> edit: accidentally said 7, but I meant 8.x or lower.

yes, my system is Windows 7 SP 1. I don't know if it's related to the system libraries I have already installed.

And here are the dependency libraries i installed in this system.
```Text
Microsoft Visual C++ 2015-2022 Redistributable(X64) 14.40.33810
```

**Comment by reaperhulk** [comment]
Windows 7 and 8 are unsupported by MS and as of version 43 the binaries we ship do not support less than windows 10 due to underlying compilers dropping support. You’ll need to upgrade to a supported operating system to use newer versions of this project.
