### ISSUE TITLE
typing: fix x509.name.NameAttribute.value to be either str or bytes

### ISSUE THREAD

**Issue by prauscher** [pyca/cryptography#12056]
Currently, `x509.name.NameAttribute.value` is typed as `str | bytes`, as it might be `bytes` for `X500_UNIQUE_IDENTIFIER`. To improve type checking, I'd suggest to use two subclasses of `NameAttribute` (say `StringNameAttribute` and `BytesNameAttribute`) which use correct typing for `value`. Now `@override`s can be used for `get_attributes_for_oid` to deliver `list[BytesNameAttribute]` or `list[StringNameAttribute]` respectively.

I could draft a PR if the idea is generally accepted, just let me know :)

**Comment by alex** [comment]
In practice, lots of uses like iterating a name won't have a known type.
I'm also a bit concerned about extensibility if there's other non-string
OIDs.

While I'm not positive this makes sense for this reason, I'd be interested
to try it out. Perhaps without subclassing though
