### ISSUE TITLE
Cargo.toml files included in published wheels for v44.0

### ISSUE THREAD

**Issue by anderssonjohan** [pyca/cryptography#12089]
When I was comparing the published wheels for another reason I found out that from v44.0 the cargo.toml files seems to be included in the published wheels on PyPI. 
Just close this issue if it's expected.

![Screenshot 2024-12-02 at 17 21 13](https://github.com/user-attachments/assets/b739d606-6646-4350-8437-8f6a67d3176c)

They seem to first appear in the Wheel builder artifacts for this PR: https://github.com/pyca/cryptography/pull/11836

**Comment by anderssonjohan** [comment]
cc @alex

**Comment by reaperhulk** [comment]
Is there anything else in the `rust` dir or is it just a series of Cargo.tomls? Seems like noise that won't hurt, but could just be removed.

**Comment by alex** [comment]
I suppose the real question is: What would it take to remove them?

On Mon, Dec 2, 2024 at 1:46 PM Paul Kehrer ***@***.***> wrote:
>
> Is there anything else in the rust dir or is it just a series of Cargo.tomls? Seems like noise that won't hurt, but could just be removed.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by anderssonjohan** [comment]
> Is there anything else in the `rust` dir or is it just a series of Cargo.tomls? Seems like noise that won't hurt, but could just be removed.

I guess it's just noise. The wheel RECORD file has all the Cargo.tomls, but that's it:
<img width="642" alt="Screenshot 2024-12-02 at 23 43 01" src="https://github.com/user-attachments/assets/78848034-edbb-479d-9e4b-fddbba90e8ec">

I don't know this stuff and I'm sorry that I'm unable to fix it. 😔
I'm just guessing it has to do with the changes in pyproject.toml -> maturin -> `include` of that PR.

Applying this patch works, but I'm not sure if it breaks something else:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 4266e3bd5..788fea333 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -101,8 +101,10 @@ include = [
     "src/_cffi_src/**/*.c",
     "src/_cffi_src/**/*.h",

-    "**/Cargo.toml",
-    "**/Cargo.lock",
+    "Cargo.toml",
+    "Cargo.lock",
+    "src/rust/**/Cargo.toml",
+    "src/rust/**/Cargo.lock",
     "src/rust/**/*.rs",

     "tests/**/*.py",
```

Before patch running `maturin build` in my local clone:

```
📦 Including files matching "**/Cargo.toml"
📦 Including files matching "**/Cargo.lock"
📦 Including files matching "src/rust/**/*.rs"
📦 Including files matching "tests/**/*.py"
📦 Built wheel for abi3 Python ≥ 3.7 to target/wheels/cryptography-45.0.0.dev1-cp37-abi3-macosx_11_0_arm64.whl
❯ unzip -lv target/wheels/cryptography-45.0.0.dev1-cp37-abi3-macosx_11_0_arm64.whl | grep Cargo.toml
    1320  Defl:N      508  62% 12-02-2024 23:24 6b591180  rust/Cargo.toml
     386  Defl:N      227  41% 12-02-2024 23:24 919d6d4b  rust/cryptography-cffi/Cargo.toml
     210  Defl:N      108  49% 12-02-2024 23:24 f7240369  rust/cryptography-keepalive/Cargo.toml
     455  Defl:N      262  42% 12-02-2024 23:24 9edcd69b  rust/cryptography-key-parsing/Cargo.toml
     545  Defl:N      292  46% 12-02-2024 23:24 3296e930  rust/cryptography-openssl/Cargo.toml
     248  Defl:N      181  27% 12-02-2024 23:24 2bfc6b96  rust/cryptography-x509/Cargo.toml
     426  Defl:N      198  54% 12-02-2024 23:24 a744d6fa  rust/cryptography-x509-verification/Cargo.toml
```

With the above patch:

```
📦 Including files matching "Cargo.toml"
📦 Including files matching "Cargo.lock"
📦 Including files matching "src/rust/**/Cargo.toml"
📦 Including files matching "src/rust/**/Cargo.lock"
📦 Including files matching "src/rust/**/*.rs"
📦 Including files matching "tests/**/*.py"
📦 Built wheel for abi3 Python ≥ 3.7 to target/wheels/cryptography-45.0.0.dev1-cp37-abi3-macosx_11_0_arm64.whl
❯ unzip -lv target/wheels/cryptography-45.0.0.dev1-cp37-abi3-macosx_11_0_arm64.whl | grep Cargo.toml
```

Another thing I noticed from the "Build the wheel" step is that the target dir was changed to the repository root. I don't know if [that exclude pattern](https://github.com/pyca/cryptography/blob/ea8bb1a012959801574f387ac55319226454977e/pyproject.toml#L112) actually affects the build but I guess `"src/rust/target/**/*"` now should be `target/**/*`? 🤷 

Cargo target dir pre PR 11836:
<img width="934" alt="Screenshot 2024-12-02 at 23 39 45" src="https://github.com/user-attachments/assets/b2adac2a-1f00-4713-b6ed-acbfcaac6f56">

Cargo target dir post PR 11836:
<img width="818" alt="Screenshot 2024-12-02 at 23 40 25" src="https://github.com/user-attachments/assets/187a7ba6-4351-49e2-87eb-3692185bd19b">

**Comment by alex** [comment]
I think you're right. Up for sending a PR?
