### ISSUE TITLE
Mysterious issue with cryptography v44, no repro

### ISSUE THREAD

**Issue by hauntsaninja** [pyca/cryptography#12134]
Apologies for a terrible bug report. Please close, I'm mainly opening this in case this is afflicting others.

In a complicated large Python application at work, `cryptography==44.0.0` raises ImportError's under some circumstances while `cryptography==43.0.3` does not.

This looks like so:
```
      File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/azure/storage/blob/_encryption.py", line 27, in <module>
        from cryptography.hazmat.primitives.padding import PKCS7
      File "/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cryptography/hazmat/primitives/padding.py", line 12, in <module>
        from cryptography.hazmat.bindings._rust import (
    ImportError: cannot import name 'check_pkcs7_padding' from 'cryptography.hazmat.bindings._rust' (/root/.pyenv/versions/3.11.8/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```

Now the thing that makes this a terrible bug report is that this import only raises in the context of the complicated large Python application. If you run the same `from cryptography.hazmat.primitives.padding import PKCS7` import in the same environment on its own, everything is fine.

Python 3.11.8
Ubuntu 24.04
Installed cryptography via uv (from the cp39-abi3-manylinux_2_34_x86_64 wheel)

**Comment by alex** [comment]
It's hard for me to guess how this came to be, but that error suggests that you have a `.so` from cryptography 44, but Python source from an older version of cryptography.

I'm not sure what to suggest besides: If you delete your entire Python env (I see you're not using a virtualenv, which I'd recommend) and recreate, does it still reproduce?

**Comment by hauntsaninja** [comment]
No, it doesn't reproduce standalone. But thanks for pointing out the mismatch! That pretty clearly implicates stuff that's bespoke to the application, should be easy to debug from there. Thank you!
