### ISSUE TITLE
Optional parameters "encoding" / "format" to from_private_bytes() method

### ISSUE THREAD

**Issue by PimvanderEijk** [pyca/cryptography#12131]
These classes:

- cryptography.hazmat.primitives.asymmetric.x25519.X25519PublicKey 
- cryptography.hazmat.primitives.asymmetric.x448.X448PublicKey

Have the following methods:
- public_bytes(encoding, format) allows setting the format to three variants: [PEM] , [DER], or [Raw]..
- from_public_bytes(data) does not have a format parameter,  so it only supports one format.

It could be useful to have optional "encoding" / "format" parameters for the from_public_bytes method.  For example, this would allow two parties using cryptography to use DER encoding as the interchange notation for public keys.  One would use public_bytes() to export and the other from_public_bytes to import.

**Comment by alex** [comment]
We have existing APIs for loading keys, as documented here: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/

While these are not fully symmetric with `from_public_bytes`, that method exists only to handle the special case of "bytes only" serialization that those key types support.
