### ISSUE TITLE
Jenkins Infrastructure Improvements

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1215]
At the moment there are several drawbacks to our Jenkins infrastructure:
- Builders are not built via a config management tool
- There is no shared credential repository so only one person (me) has easy access
- The Jenkins config (plugins, jobs, etc) has accreted over time and may not be optimal. We should investigate tools that can build jenkins configs (via yaml?)

This will serve as a tracking issue for now.

**Comment by alex** [comment]
@reaperhulk where are we here? To what extent is this superceded by #3075 ?

**Comment by reaperhulk** [comment]
jenkins infra improvements are my focus today :) #3075 is a subset of this really.

**Comment by alex** [comment]
All that's left is modernizing the windows/macos/freebsd builders -- the host and linux builders are all configuration managed now.
