### ISSUE TITLE
AES* generate_key argument name differs in actual class vs .pyi

### ISSUE THREAD

**Issue by jborean93** [pyca/cryptography#12169]
The definition for the [AESGCM.generate_key class method](https://github.com/pyca/cryptography/blob/b27b4d5f8f4fb527ed798bda9d599682550abde3/src/rust/src/backend/aead.rs#L645) defines the first argument as `bit_length: usize` whereas the [AESGCM.generate_key pyi definition](https://github.com/pyca/cryptography/blob/b27b4d5f8f4fb527ed798bda9d599682550abde3/src/cryptography/hazmat/bindings/_rust/openssl/aead.pyi#L8) is `key_size`. This causes issues with mypy validation if calling this method with an explicit kwarg like

```python
AESGCM.generate_key(bit_length=256)
```

There are other AES* classes that also have a `bit_length` argument in the source but the `.pyi` defines it as `key_size`. These should align and to avoid backwards compatibility problems the `.pyi` files should be changed to `bit_length`. If you are happy with this change I can send through a PR with those changes.

**Comment by alex** [comment]
Sigh, good catch.

Yes, we'd be happy to take a patch, and you're correct that `bit_length` is the right name.

**Comment by jborean93** [comment]
Have opened https://github.com/pyca/cryptography/pull/12170. I'm unsure if you want a test for one or all classes to call this method with the kwarg but just left it to the `.pyi` changes for now.
