### ISSUE TITLE
openssl backend specific keys should take an evp_pkey.

### ISSUE THREAD

**Issue by dreid** [pyca/cryptography#1231]
For RSA at least we appear to take an evp_pkey, convert it to rsa_cdata, then _RSAPrivateKey makes a new evp_pkey from that.

Seems silly.

Will be easiest to refactor after the most recent deprecations are removed.

**Comment by reaperhulk** [comment]
I'm going to reopen this now that we're using EVP_PKEY for serialization in EC (and soon DSA). see #1709
