### ISSUE TITLE
Add a test for multibackend interfaces

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#1258]
The past few releases we have problems with `MultiBackend` forgetting to implement new interfaces.

```python
from cryptography.hazmat.backends import interfaces

def test_interfaces():
    interface_dict = vars(interfaces)
    backends = {
        k: interface_dict[k] for k in interface_dict if "Backend" in k
    }.values()
    for i in backends:
        assert issubclass(MultiBackend, i)
```

This code snippet should ensure that `MultiBackend` at least claims to implement all the interfaces in `cryptography.hazmat.backends.interfaces`

However, this might be get annoying during the development process if it is added into the normal test suite because adding the `Multibackend` implementation is usually the last thing that needs to be done.

Perhaps a test similar to test can be added to the release process instead?

In the longer term, I think @dreid has some ideas to move us to zope.interfaces?

**Comment by reaperhulk** [comment]
Closing since the world has changed since Oct 2014
