### ISSUE TITLE
Use getentropy(2) and getrandom(2) syscalls when available

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1299]
These are for OpenBSD and Linux respectively; neither is in a released kernel yet.

They allow for a gross simplification over our existing randomness code in the OpenSSL engine, we should use them when available.

**Comment by elitest** [comment]
It looks like this was added in Linux 3.17, which is apparently too new for what I have installed atm.  Looking at the referenced python bug it looks like ```getrandom()``` was incorporated into [os.urandom()](https://docs.python.org/2/library/os.html#os.urandom). If that function primarily relies on /dev/urandom on older platforms, I think there is a propensity to have entropy reused, so while convenient it may not be appropriate for our purposes.  It is left a bit ambiguous as to whether ```getentropy()``` was added, according to that thread there seems to be a question as to whether it is even the proper thing to call.

How would we implement this in a way that would allow us to safely move away from OpenSSL's random engine?  Or would we still have to keep OpenSSL as a fallback?

**Comment by haypo** [comment]
os.urandom() uses getentropy() in python 2.7.10, 3.4.x, and 3.5.
os.urandom() uses getrandom() in 3.5.

If getrandom() is not available, Python falls back to reading /dev/urandom
using a file descriptor.

The main purpose of using getentropy() and getrandom() is to avoid a file
descriptor. In many cases, a file descriptor causes bugs. Like applications
running in very restricted containers (RLIMIT_NOFILE is low), or under high
system load with many threads (you may reach the limit for file descriptors
in this case).

**Comment by alex** [comment]
We now use `os.urandom`, which uses the appropriate syscalls. So this is fixed.
