### ISSUE TITLE
cx_freeze comaptibility

### ISSUE THREAD

**Issue by tychotatitscheff** [pyca/cryptography#1323]
# Issue:

cxfreeze fail including the openssl dllin the build
- Work without cx_freeze
- cx_freeze perfectly without cryptography
# Error message

cffi/ffiplateform,py ligne48 in _build
distutils.errors.DistutilsModuleError invalid command build
# Remarks

Maybe I miss some include, in setup.py but if not what can bee done to force cryptography beeing exported corectly by cx_freeze

**Comment by dbortolz** [comment]
It darn works! Thank you very much Mike

**Comment by dstufft** [comment]
So the hashes aren't changing, that's good it means that it's looking for the right file, it's just doing it in the wrong place.

Changing the ``tmpdir`` is probably doing something where it enables cffi to write out the ``.c`` file. You probably don't need that change if you rename the ``.pyd`` files first. My guess is that something that cx_freeze does is making it so ``import cryptography; cryptography.__path__`` is ``None``. See here: https://bitbucket.org/cffi/cffi/src/67435ba27473de84824708c1f222bb915ddb1e03/cffi/verifier.py?at=default#cl-136 that would cause it to act as if there wasn't an ``ext_package`` defined.
