### ISSUE TITLE
Unable to cross compile due to cffi (from pyopenssl)

### ISSUE THREAD

**Issue by Diaoul** [pyca/cryptography#1325]
More information here: https://github.com/pyca/pyopenssl/issues/157

Le me kow if we should continue the discussion here or in the pyopenssl issue.

**Comment by yegorich** [comment]
I still have problems cross-compiling cryptography in Buildroot. I've tried both 0.7.2 release and master branch, but I always get the issue with _cffi_backend.so:

>>> python-cryptography custom Building
(cd /home/user/Documents/versioned/buildroot/output/build/python-cryptography-custom//; PATH="/home/user/Documents/versioned/buildroot/output/host/bin:/home/user/Documents/versioned/buildroot/output/host/sbin:/home/user/Documents/versioned/buildroot/output/host/usr/bin:/home/user/Documents/versioned/buildroot/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" PYTHONPATH="/home/user/Documents/versioned/buildroot/output/target/usr/lib/python2.7/sysconfigdata/:/home/user/Documents/versioned/buildroot/output/target/usr/lib/python2.7/site-packages/" _python_sysroot=/home/user/Documents/versioned/buildroot/output/host/usr/arm-buildroot-linux-gnueabi/sysroot _python_prefix=/usr _python_exec_prefix=/usr  /home/user/Documents/versioned/buildroot/output/host/usr/bin/python setup.py build  )
running build
Traceback (most recent call last):
  File "setup.py", line 339, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/home/user/Documents/versioned/buildroot/output/host/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/user/Documents/versioned/buildroot/output/host/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/user/Documents/versioned/buildroot/output/host/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/home/user/Documents/versioned/buildroot/output/host/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 105, in finalize_options
    self.distribution.ext_modules = get_ext_modules()
  File "setup.py", line 76, in get_ext_modules
    from cryptography.hazmat.bindings.commoncrypto.binding import (
  File "src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 12, in <module>
    class Binding(object):
  File "src/cryptography/hazmat/bindings/commoncrypto/binding.py", line 34, in Binding
    "-framework", "Security", "-framework", "CoreFoundation"
  File "src/cryptography/hazmat/bindings/utils.py", line 97, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "src/cryptography/hazmat/bindings/utils.py", line 105, in build_ffi
    ffi = FFI()
  File "/home/user/Documents/versioned/buildroot/output/target/usr/lib/python2.7/site-packages/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: /home/user/Documents/versioned/buildroot/output/target/usr/lib/python2.7/site-packages/_cffi_backend.so: wrong ELF class: ELFCLASS32
package/pkg-generic.mk:182: recipe for target '/home/user/Documents/versioned/buildroot/output/build/python-cryptography-custom/.stamp_built' failed
make: *** [/home/user/Documents/versioned/buildroot/output/build/python-cryptography-custom/.stamp_built] Error 1

**Comment by vtmram** [comment]
Hello,

Has this been resolved yet? It still fails in Buildroot. Tried version cryptography 0.9.1 and cffi 1.1.2.

Traceback (most recent call last):
  File "./setup.py", line 307, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/home/ram/.../usr/lib/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/ram/.../usr/lib/python2.7/setuptools/dist.py", line 269, in __init__
    _Distribution.__init__(self,attrs)
  File "/home/ram/.../usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/ram/.../usr/lib/python2.7/setuptools/dist.py", line 325, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/ram/.../usr/lib/python2.7/cffi/setuptools_ext.py", line 154, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/ram/.../usr/lib/python2.7/cffi/setuptools_ext.py", line 48, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/ram/.../usr/lib/python2.7/cffi/setuptools_ext.py", line 24, in execfile
    exec(code, glob, glob)
  File "src/_cffi_src/build_openssl.py", line 96, in <module>
    extra_link_args=extra_link_args(sys.platform),
  File "./src/_cffi_src/utils.py", line 65, in build_ffi_for_binding
    extra_link_args=extra_link_args,
  File "./src/_cffi_src/utils.py", line 73, in build_ffi
    ffi = FFI()
  File "/home/ram/.../usr/lib/python2.7/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: /home/.../usr/lib/python2.7/_cffi_backend.so: wrong ELF class: ELFCLASS32

Any help would be appreciated!

**Comment by xuhcc** [comment]
I've got the same error when cross-compiling using OpenEmbedded build system: `_cffi_backend.so: wrong ELF class: ELFCLASS32`.
Tried cryptography 0.9.3 and current master.

**Comment by alexykot** [comment]
This also affects my project while trying to cross-compile `cryptography` for ARM embedded system, with the same import error:
```
ImportError: /home/vagrant/poky/build/tmp/sysroots/qemuarm/usr/lib/python2.7/site-packages/_cffi_backend.so: wrong ELF class: ELFCLASS32
```

**Comment by reaperhulk** [comment]
@alexykot what happens if you use the master branch rather than 0.9.3?

**Comment by alexykot** [comment]
Just tried that, same thing happens.
```
ImportError: /home/vagrant/poky/build/tmp/sysroots/qemuarm/usr/lib/python2.7/site-packages/_cffi_backend.so: wrong ELF class: ELFCLASS32
```
Do you need full traceback?

**Comment by reaperhulk** [comment]
No, this looks like it might be something cffi has to handle. This is outside my experience so I'm not sure how to go about debugging it though.

**Comment by alexykot** [comment]
Bummer. OK, I'll try to get to cffi about this. Thanks for swift reply.

**Comment by vtmram** [comment]
@reaperhulk @alexykot I don't think it's a cffi issue. I tried to cross compile for a 32 bit system from a 64 bit system. cffi module _cffi_backend.so compiled OK for the target (that is 32 bit). The problem is that when cryptography tries to pre-cross compile (for 32 bit) cffi modules (_Cryptography_cffi_*.so), it uses (host) 64 bit compiler flags and tries to load the 32 bit cross compiled _cffi_backend.so. This is why you get "wrong ELF class: ELFCLASS32".

There needs to be some way to configure the C compiler flags from within the cryptography package while cross compiling the cffi modules. You can see how cffi module itself is allowing that in its setup.py file. Another python package I was able to configure the target c flags is python readline. 

I got around this problem (dirty hack) by skipping the cffi modules pre-cross compilation process (_Cryptography_cffi_*.so) and copying (during the build time) those modules I compiled on the target system.

**Comment by reaperhulk** [comment]
This sounds like the sort of thing that should be possible via setuptools magic. @dstufft?

**Comment by AndreMiras** [comment]
Well I could get it working myself by following [midicase comment](https://github.com/vincentbernat/snimpy/issues/21#issuecomment-73227857) on [vincentbernat/snimpy](https://github.com/vincentbernat/snimpy).
1. build and install host cffi
2. build and install target packages that depend in cffi
3. build and install target cffi
I've created a detailed install instructions https://github.com/AndreMiras/km/wiki/CFFI-Cross-Compile.

**Comment by alexykot** [comment]
Cool, I'll try this workaround and see if it would work.

**Comment by yegorich** [comment]
@vtmram FYI: python-cryptography and python-pyopenssl were both taken into Buildroot's next branch (https://git.busybox.net/buildroot/commit/?h=next&id=fbeeb4c8cb4e44c654ca27db9ae05a83202f4104)

As @AndreMiras pointed the trick was to install both host and target versions of CFFI. See python-cryptography for details.
