### ISSUE TITLE
Write some fuzzer tests

### ISSUE THREAD

**Issue by dstufft** [pyca/cryptography#142]
Once we have decryption support we should write some tests that do some fuzzing. The basic idea is to generate random strings and just test a round trip encrypt/decrypt and make sure the output matches the input. The goal being that by fuzzing we might find something that the test vectors didn't bother. For example maybe none of the vectors have a null inside the string and we accidentally used a ``ffi.string`` where a ``ffi.buffer`` should be used.

**Comment by reaperhulk** [comment]
We should do this via python-afl at some point, but that's a different issue than writing our own so closing this one :)
