### ISSUE TITLE
Better handle multiple packages

### ISSUE THREAD

**Issue by dstufft** [pyca/cryptography#1473]
Right now the cryptography repository has two packages inside of it. It has the "primary" package of cryptography which is located at `.`, and then a "secondary" package of cryptography_vectors. In #1456a third one is added which is cryptography_scrypt.

This organization is confusing, we have packages inside of packages. I think we should either decide if we want to hold multiple packages in one repository and if we do we should reorganize the repository to not do this nesting thing.

To be exact the proposal is to change the directory structure to:

```
.
├── cryptography
│   ├── setup.py
│   └── src
│       └── cryptography
├── cryptography_scrypt
│   ├── cryptography_scrypt
│   └── setup.py
└── cryptography_vectors
    ├── cryptography_vectors
    └── setup.py
```

If we're going to hold everything in a single repository. If we're not going to hold everything in a single repository then instead of having a single repository at `.` each direct descendent (cryptography, cryptography_scrypt, cryptography_vectors) would have it's own repository.

Personally I think it sort of makes sense sense to have cryptography and cryptography_vectors in the same repository (primarily because the split really only exists because of file size), but I do not think it makes sense to include other random backends in the same repository. Overall I think putting multiple things into the same repository isn't a very good way to organize things. Pip has some newish support for layouts like this, but I don't believe anything else does.

My vote is to stick to one repository per package.

**Comment by alex** [comment]
Current trajectory is that we will not be adding new backends, and may be removing the concept.
