### ISSUE TITLE
CFFI modulename should use ABI instead of sys.version[:3] where possible

### ISSUE THREAD

**Issue by dstufft** [pyca/cryptography#1475]
Starting with Python 3.something Python has a stable ABI and a string representation of that ABI. Instead of using ``sys.version`` (which will be something like ``3.4``) we should use this ABI string (which will be something like ``cpython-32mu``). We can get this information by doing:

```python
import sysconfig

abi = sysconfig.get_config_var("SOABI") or sys.version[:3]
```

We might also want to investigate what exactly Wheel does when the ABI isn't available and copy that.

**Comment by alex** [comment]
@dstufft, @reaperhulk: Is this relevant on cffi 1.0?

**Comment by dstufft** [comment]
No, I don't believe so. Unless CFFI is doing something that would cause it not too, distutils should automatically use ABI tagged .so's when the host Python supports it.

**Comment by reaperhulk** [comment]
Closing as we move to cffi 1.0 in #1986
