### ISSUE TITLE
Consider moving interface definitions out of 'interfaces' module

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1508]
Why aren't RSAPrivateKey/RSAPublicKey just in the `rsa` module?

At a minimum, i think we should consider moving the docs.

**Comment by reaperhulk** [comment]
Anybody have an opinion on where `AsymmetricPadding`, `AsymmetricVerificationContext`, and `AsymmetricSignatureContext` should live? Those interfaces, along with `KeyDerivationFunction` and `MACContext` are all that are left once the cipher PR merges.

**Comment by alex** [comment]
Not sure what to do with `KDF` and `MACContext`, for the Asymmetric ones, as a first pass we could put them in `hazmat.primtives.asymmetric`?

**Comment by reaperhulk** [comment]
We can move kdf to `cryptography.hazmat.primitives.kdf.KeyDerivationFunction`. Still not sure what to do about `MACContext`.

**Comment by reaperhulk** [comment]
One possible solution would be to move hmac/cmac to `cryptography.hazmat.primitives.mac` and deprecate their current module path. Then we'd have a place for it, but at the cost of deprecating two more things.

**Comment by public** [comment]
I think we should move the mac stuff too.

**Comment by reaperhulk** [comment]
The only item left is `MACContext` and we're not going to move that for now (per discussion in IRC).
