### ISSUE TITLE
One Shot Sign/Verify/Encrypt/Decrypt Methods

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1529]
This replaces #1287.

Via @ronf:
"The asymmetric key classes could have sign() and verify() functions in addition to signer() and verifier(). They would take the same arguments as signer/verifier plus an additional "data" argument and would do the equivalent of signer/verifier, update, and finalize all in one call (returning the signature). In cases where you needed to sign or verify a single block of data, this would be the preferred API. In cases where you wanted to feed the data in as multiple blocks, the existing API would be used."

@alex added:
"We've got a lot of APIs that are exclusively streaming right now (symmetric encryption, hashes, HMAC/CMAC), we should think if we want to do this across the board."

**Comment by reaperhulk** [comment]
For `MAC` if we follow the lead of the `hmac` module in the stdlib we end up with a new `__init__` that looks like:

```python
    def __init__(self, key, algorithm, backend, data=None, ctx=None)
```

Then there are two ways to invoke. The old way:

```python
mac = HMAC(key, algorithm, backend)
mac.update(data)
digest = mac.finalize()
```
or the new way

```python
mac = HMAC(key, algorithm, backend, data)
digest = mac.finalize()
```
The disadvantage of this approach is that the ordering of the arguments is unintuitive due to the optional arg and it still requires two calls. If we were to add `hex_finalize` (again similar to the `hmac` stdlib module) that would perhaps be more palatable though.

**Comment by cmurphy** [comment]
Reiterating what @reaperhulk proposed, but focusing in on RSA signing/verifying, I think we need two abstract methods:

```
cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey.sign(data, padding, algorithm)
cryptography.hazmat.primitives.asymmetric.rsa.RSAPublicKey.verify(signature, data, padding, algorithm)
```

and two instance methods:

```
# wraps the signer method and the signer's update and finalize methods
cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey.sign(data, padding, algorithm)
# wraps the verifier method and the verifier's update and finalize methods
cryptography.hazmat.backends.openssl.rsa._RSAPublicKey.verify(signature, data, padding, algorithm) 
```

Does this seem like a reasonable encapsulation of work that I could start on?

**Comment by reaperhulk** [comment]
We now have sign/verify one-shot functions for EC, DSA, and RSA and RSA always had encrypt/decrypt. We have separate issues talking about AEAD one shot APIs so this is now largely complete. Go team.
