### ISSUE TITLE
Constructor for modes which generates an IV?

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1557]
Is there a good way we can do this?

Idea:

```py
mode, iv = CBC.random()
```

**Comment by reaperhulk** [comment]
Does anyone want to tackle this for our upcoming eighth release? A concrete API proposal along with some sample code demonstrating it would be useful in deciding whether or not we want to do this.

**Comment by alex** [comment]
No progress here, and I think there's a compelling argument that any solution would be incosistent with the moral values of `hazmat`.
