### ISSUE TITLE
Add support for parsing distinguished names in X.509

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1569]
We need to be able to parse subject and issuer DNs!

**Comment by reaperhulk** [comment]
If we want to do this with OpenSSL do we want to have it parse it out and dump it into a generic `Name` class? That class would need to have properties that allow access to each of the subject OIDs we're supporting + some way of giving a precise order (conceptually: [['CN', 'myCN'], ['O', 'My Org'], ['O', 'Another Org']]). The latter is not typically important when parsing but definitely matters if we ever intend to use this same object to generate certificate subject/issuer DNs.

Iterating over an `X509_NAME` in OpenSSL looks something like this:

```python
        name = self._backend._lib.X509_get_issuer_name(self._x509)
        count = self._backend._lib.X509_NAME_entry_count(name)
        for x in range(0, count):
            entry = self._backend._lib.X509_NAME_get_entry(name, x)
            obj = self._backend._lib.X509_NAME_ENTRY_get_object(entry)
            assert obj != self._backend._ffi.NULL
            data = self._backend._lib.X509_NAME_ENTRY_get_data(entry)
            assert data != self._backend._ffi.NULL
            nid = self._backend._lib.OBJ_obj2nid(obj)
            if nid == self._backend._lib.NID_undef:
                raise UnknownAttribute(
                    "Not a recognized OID"
                )
            if nid == self._backend._lib.NID_commonName:
                # do some things
```

**Comment by alex** [comment]
How about `Names` as a class with accessors that returns lists of various
OIDs, and also has an `__iter__` to let people see all of them (not sure
what form they'd be in).

**Comment by reaperhulk** [comment]
Each name item that we've talked about supporting (the set in RFC 5280) has 3 values that describe it: OID, value, and the ASN.1 type of the value (UTF8String, ia5string, printableString, etc). For parsing purposes we don't really care about the ASN.1 type since we'll be returning Python strings where we've handled whatever is needed, but for generation we would need to care.

**Comment by alex** [comment]
Do we? I don't think either pyOpenSSL or Go expose the ASN.1 type for
generation, do they? Is there a reason a person would need to care, for hte
common case, or is this about edge cases?

**Comment by reaperhulk** [comment]
This would be definitively about edge cases. For the common case we could auto-select the appropriate type based on the data passed along with what the RFC recommends. My concern would be whether that proves to be insufficiently expressive in practice, but I suppose that's really something to worry about if it happens rather than right now.

**Comment by reaperhulk** [comment]
So roughly:

```python
class Name(object):
    @property
    def common_name(self):
        return self._common_name

AttributeTypeAndValue = collections.namedtuple("AttributeTypeAndValue", ["oid", "value"])
```
Each property would be a list of `AttributeTypeAndValue` objects then and we'd also have a full list that we could `__iter__` over. We may want to have `name` in addition to `oid` so we can store friendly strings like "localityName" rather than just "2.5.4.7".

`AttributeTypeAndValue` is a lousy name but it's what the RFC calls it.

**Comment by alex** [comment]
Should that class be `Name` or `Names`? There should probably also be a way to map the OID to it's usual name on an individual `Name`, in addition to the accesso ron `Names`

**Comment by reaperhulk** [comment]
From the RFC (and earlier in this thread):
```
   Name ::= CHOICE { -- only one possibility for now --
     rdnSequence  RDNSequence }

   RDNSequence ::= SEQUENCE OF RelativeDistinguishedName

   RelativeDistinguishedName ::=
     SET SIZE (1..MAX) OF AttributeTypeAndValue

   AttributeTypeAndValue ::= SEQUENCE {
     type     AttributeType,
     value    AttributeValue }
```

So the parent object is a `Name` and it (in practice) contains a list of `AttributeTypeAndValue` objects (maybe we call them `Attribute`?)

```python
Attribute = collections.namedtuple("Attribute", ["oid", "name", "value"])
```

With that you'd have the name of the OID (as defined by RFC 5280) available in addition to the OID value itself. It does, however, mean that getting the common name of an issuer would look like this:

```python
org = cert.issuer.organization
for o in org:
    print(o.value)
```

**Comment by alex** [comment]
Ok, sorry, I get confused because "Name" is a singler, but it's really a
collection.
