### ISSUE TITLE
Feature request: Record OS patch levels during release builds

### ISSUE THREAD

**Issue by public** [pyca/cryptography#1620]
So that we can track if our builds were done on potentially insecure machines. e.g. on Windows we could log a WSUS report of the installed patches on the machine.

It would also be nice to record the patch levels of any other machines involved in the release if for example the upload is done from someones laptop rather the build box.

**Comment by hawkowl** [comment]
As per discussions on IRC, this could be done on windows by the WMI CLI as well, to get all hotfixes and everything that was installed at the point-of-time of build. Since this information is pretty big, I'm not sure it could be included with the actual built package easily.

**Comment by dstufft** [comment]
Setuptools has an entry point that lets you add extra metadata files into the metadata for the project.

**Comment by reaperhulk** [comment]
I've added `wmic qfe` to our wheel builder jobs to start this. For now that data won't be embedded in anything, but we can improve from here.

**Comment by reaperhulk** [comment]
I'm skeptical of the value of this inside the packages themselves. In practice no one will audit this data. I have, however, added `/usr/sbin/system_profiler SPInstallHistoryDataType` to our 10.10 OS X wheel builder now, so we'll have information similar to `wmic qfe` available in our jenkins logs.

I'm going to close this as complete for now. If someone feels strongly that we should include this metadata in the wheels I would be willing to review the PR :)
