### ISSUE TITLE
Building against openssl-1.0.1k configured without compression via no-comp

### ISSUE THREAD

**Issue by schlenk** [pyca/cryptography#1623]
The build fails when openssl is configured with the no-comp option, to mitigate the CRIME attack on compression in SSL/TLS.

If that happens the signatures of the three compression functions used in cryptography change signatures (see openssl/ssl.h) due to OPENSSL_NO_COMP being defined, so there are link errors later.

#ifndef OPENSSL_NO_COMP
const COMP_METHOD *SSL_get_current_compression(SSL *s);
const COMP_METHOD *SSL_get_current_expansion(SSL *s);
const char *SSL_COMP_get_name(const COMP_METHOD *comp);
STACK_OF(SSL_COMP) *SSL_COMP_get_compression_methods(void);
int SSL_COMP_add_compression_method(int id,COMP_METHOD *cm);
#else
const void *SSL_get_current_compression(SSL *s);
const void *SSL_get_current_expansion(SSL *s);
const char *SSL_COMP_get_name(const void *comp);
void *SSL_COMP_get_compression_methods(void);
int SSL_COMP_add_compression_method(int id,void *cm);
#endif

The fix is obviously to handle the signature change when the macro is defined.

**Comment by reaperhulk** [comment]
This is basically resolved in 0.9
