### ISSUE TITLE
Upgrade Windows Builders to 1.0.2?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1637]
Soliciting opinions on whether we should upgrade the Windows builders to 1.0.2 now that it's final. If we do this then our next release will ship 1.0.2 wheels.

I am in favor of this as this will allow Windows users to potentially access ALPN and other new features while sacrificing no compatibility.

**Comment by alex** [comment]
+1 from me.

**Comment by Ayrx** [comment]
Yes. :+1:

**Comment by reaperhulk** [comment]
I'm going to go ahead and upgrade them whenever the packages from slproweb appear. Nothing so far.

**Comment by reaperhulk** [comment]
The blocker here continues to be that slproweb.com is not publishing 1.0.2 packages. The other Windows binary distributions don't include static libraries (which is our default link type) so we're stuck until they either publish 1.0.2 or we decide to start building our own.

**Comment by reaperhulk** [comment]
slproweb has published 1.0.2 (thanks!) and they are now installed on our builders.
