### ISSUE TITLE
Feature request: passphrase to EC key

### ISSUE THREAD

**Issue by dmbasso** [pyca/cryptography#1646]
Currently `cryptography` does not have a function to derive Elliptic Curve keys from passphrases, such as `seccure`'s `Curve.passphrase_to_privkey`. Based on that implementation I made a hack using the OpenSSL backend directly: [reference code](https://gist.github.com/dmbasso/301a0fc233bab7845ce1).

If there is interest, and with some guidance, I might submit a proper patch.

**Comment by reaperhulk** [comment]
A passphrase to private key model is interesting, but I'm reluctant to add a feature like this without an accompanying spec that other cryptography libraries may choose to implement. (See: https://github.com/fernet/spec). Have other libraries (outside of `seccure` itself of course) implemented support for `seccure`-style passphrase->private key derivation? Minilock does something similar but uses curve25519 rather than `secp192r1`.

**Comment by dmbasso** [comment]
I don't know of any other libraries that use this technique, but a simple spec could easily be written. The pseudo code is:

```python
digest = sha256(passphrase)
ctr = counter(size=128 bits, initial_value=0)
cipher = AES(mode=CTR, counter=ctr, key=digest)
random_bytes = cipher.encrypt('\x00' * curve.size_in_bytes)  # e.g. 24 zeroes for secp192r1
exponent = (number_from_bytes(random_bytes) % (curve.order - 1)) + 1
public_point = curve.base_point * exponent
```

The `exponent` is the `private_numbers().private_value`, the `public_point` correspond to the `x` and `y` from `public_numbers()`. Note that it is curve agnostic, it is not limited to `secp192r1`.

Minilock uses `BLAKE2` and `scrypt` to get to the `random_bytes`, then to get a valid `curve25519` key it sets an resets some bits ([like this](https://github.com/dmbasso/pycurve25519/blob/master/curve25519/__init__.py#L23)).

Should I write a formal spec?

**Comment by Ayrx** [comment]
A formal spec available for review will definitely make me feel a lot more comfortable about adding this in. :)

**Comment by alex** [comment]
This would be a good idea, but until there's a public spec for this, we're not going to add our own pattern for doing this.
