### ISSUE TITLE
Is it possible to encrypt/decrypt part of data?

### ISSUE THREAD

**Issue by netheril96** [pyca/cryptography#1669]
For example, CTR mode allows random access---one can encrypt and decrypt in the middle or in the parallel when the offset is known. But I don't find any API in `cryptography` that allows me to do this. Is this possible within this package?

**Comment by alex** [comment]
No, right now there's no API for seeking into the stream, you'd have to skip ahead with `ctx.update(b"\x00" * distance)`.
