### ISSUE TITLE
Make our CI LibreSSL build with -Werror

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1685]
Right now we don't build with -Werror because there are some deprecated functions. We should figure out how to enable -Werror.

**Comment by alex** [comment]
Can you add the details on the deprecated functions to this issue?

**Comment by reaperhulk** [comment]
CRYPTO_dbg_malloc, CRYPTO_dbg_realloc, CRYPTO_dbg_free, CRYPTO_dbg_set_options, CRYPTO_dbg_get_options are deprecated. Looks like we need a deprecation disable/enable (similar to what we do on OS X) because those are in `crypto.h` itself and not something we're binding (https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/src/crypto/crypto.h#L481)

**Comment by reaperhulk** [comment]
We removed these bindings, so -Werror works now (LibreSSL 2.2.5).
