### ISSUE TITLE
Document OS X installation

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1700]
We implicitly assume our OS X users already have a compiler and the ffi headers (`xcode-select --install`). This is sometimes an unsafe assumption, especially as our project gets more popular. Let's document how to install on OS X.

**Comment by jbolda** [comment]
The specific error code snippet is below. It fails on the cffi dependency.
``````````````````````
    c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
    
    #include <ffi.h>
    
             ^
    
    1 error generated.
    
    error: command 'cc' failed with exit status 1
`````````````````````````
