### ISSUE TITLE
Lack of wrapped APIs for certificate verification

### ISSUE THREAD

**Issue by schlenk** [pyca/cryptography#1701]
The openssl backend lib object provides most pieces needed for basic certificate verification with  `X509_verify_cert()` but lacks just a few APIs to allow checking CRLs too.

* One needs a wrapped `X509_STORE_CTX*`, can be done, as all needed APIs are there.
* One needs a wrapped `X509_STORE*`, can be done (in fact is done in PyOpenSSL, would just need to be moved over to cryptography), some basic APIs are there, but the `X509_STORE_add_crl()` function is sadly missing, and the so CRL checks are not possible.

An alternative would be a wrapper for `X509_STORE_set_lookup_crls_cb` to set the lookup callback instead of directly adding a fixed list of CRLs.

In addition the whole `X509_LOOKUP` API would be great to have too. It would allow hooking up callbacks for loading certificates and CRLs to handle other trust stores than plain files/symlinks in directories.

**Comment by schlenk** [comment]
Just looked again, one could use CRLs, but one critical piece is missing (if one looks at the verify app in openssl), there is no wrapping for `STACK_OF(X509_CRL)` which is consumed by the already wrapped ` X509_STORE_CTX_set0_crls()` but there is no function that creates any of this structures. So the minimum to allow CRLs to be used in verification would be functions to create a `STACK_OF(X509_CRL)` from the already existing `X509_CRL` things.

**Comment by alex** [comment]
If I understand this ticket correctly, it's resolved by adding the bindings in #1819. If I misunderstood the scope of this, leave a comment and we can reopen.
