### ISSUE TITLE
Deprecation warning in default_backend()

### ISSUE THREAD

**Issue by isaacmediacore** [pyca/cryptography#1703]
I'm getting the following deprecation warning on cryptography version 7.2 with setuptools version > 10.1 and python 2.7.6:
```
$ python -Wd -c "from cryptography.hazmat.backends import default_backend; default_backend()"
/Users/isaac/.virtualenvs/mcore/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py:22: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
```

From the setuptools changelog it looks like this was deprecated in 10.2.  Reseting setuptools to 10.1 makes the warning go away.

**Comment by alex** [comment]
This is fixed on master (see #1615), until then you can just ignore this warning; we plan to have our next release out in a week or so.
