### ISSUE TITLE
Feature request: Key encapsulation

### ISSUE THREAD

**Issue by hprid** [pyca/cryptography#1704]
[Key encapsulation](http://example.org) is an alternative to generating a symmetric key and encrypt it with public key cryptography. RSA-KEM (specified in ISO 18033-2) is I guess the most widespread key encapsulation method, using KDF1 as Key Derivation Function.

I started some work (https://github.com/pyca/cryptography/compare/master...hprid:feature_rsakeyencapsulation), but this is just a prototype to see how it could work. If there is interest in adding it to cryptography, further discussion and work is required.

At least the following questions need to be answered:
1. Should we restrict the API to specific public key algorithms? In theory key encapsulation works with several algorithms, including RSA and Diffie-Hellmann. So far I only have seen RSA-KEM in real world applications.
2. How should the API look like? For my implementation I just added RSAPublicKey.encapsulate_key(kdf), which returns a tuple of symmetric key and encapsulation and RSAPrivateKey.unencapsulate_key(encapsulation, kdf), which returns the symmetric key. This allows the user to choose the KDF, but not the random value which is encrypted for encapsulation. I don't think allowing the user to specify a random value himself would be good, he might not be aware that his value must not be used with more than one RSA public key.
3. Test vectors are required. There are some test vectors for RSA-KEM in ISO 18033-2, but we don't have KDF1 in cryptography. If we want to take those vectors, we have to implement KDF1 first. [Final Draft](http://www.shoup.net/iso/std6.pdf) of ISO 18033-2 is available for free.

**Comment by reaperhulk** [comment]
Interesting, what protocols/applications use RSA-KEM?

BTW, OpenSSL supposedly does support PBKDF1 using `EVP_BytesToKey` with "[careful selection of parameters](http://wiki.openssl.org/index.php/Manual:Evp(3))".

**Comment by hprid** [comment]
The wording "in real world applications" I used was probably misleading. RSA-KEM was included in relatively "new" standards or is proposed to be included, but does not have software support. There is RFC 5990 which describes the usage of RSA-KEM in CMS (Cryptographic Message Syntax). CSM itself is used for example in S/MIME. For W3C XML Encryption Version 1.1 there was discussion about including RSA-KEM which resulted in a draft (XML Security Generic Hybrid Ciphers). It names it RSAES-KEM, which is basically the same.

Libraries implementing RSA-KEM are BouncyCastle (Java), forge (JavaScript) and maybe some I'm not aware of.

**Comment by Commod0re** [comment]
it's not RSA-KEM specifically, but RFC 6637, in defining how to represent elliptic keys (ECDH/ECDSA) defines using ECDH, AES-KEK, and the Concatenation KDF, as defined in NIST-SP800-56A.

PGP Desktop and GnuPG 2.1.x already implement that (and PGPy will probably have it shortly after you guys have had a chance to finish implementing ECDH :))

**Comment by reaperhulk** [comment]
No interest in implementation in the last 2 years. Closing for now -- if there's still a desire please file a new issue and link this one!
