### ISSUE TITLE
cryptography.hazmat.serialization module location

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1710]
We call it `cryptography.hazmat.primitives.serialization` but (at least so far) it really should be `cryptography.hazmat.primitives.asymmetric.serialization`. Our docs currently even link it under the asymmetric section. Should we alias/move it?

**Comment by alex** [comment]
That sounds like a cure worse than the disease (which isn't really bad at all)

**Comment by alex** [comment]
Does anyone disagree?

**Comment by reaperhulk** [comment]
One advantage of aliasing it so you can import it from asymmetric would be:

```
from cryptography.hazmat.primitives.asymmetric import rsa, serialization
```

instead of
```
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
```

We could keep both paths (which is vaguely confusing, but better than deprecating something so important), but update our docs to prefer the new import location for new users going forward.

That said, I'm not overly bothered by this -- it's merely not ideal.

**Comment by alex** [comment]
I'm not really compelled. :-/

On Mon, Mar 2, 2015 at 6:41 PM, Paul Kehrer <notifications@github.com>
wrote:

> One advantage of aliasing it so you can import it from asymmetric would be:
>
> from cryptography.hazmat.primitives.asymmetric import rsa, serialization
>
> instead of
>
> from cryptography.hazmat.primitives import serialization
> from cryptography.hazmat.primitives.asymmetric import rsa
>
> We could keep both paths (which is vaguely confusing, but better than
> deprecating something so important), but update our docs to prefer the new
> import location for new users going forward.
>
> That said, I'm not overly bothered by this -- it's merely not ideal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1710#issuecomment-76876439>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by public** [comment]
In the specific case of PKCS8 and perhaps X509 certs I could see an argument for upgrading it to a recipe.

**Comment by Ayrx** [comment]
So I agree that deprecating the current import path and moving it is more trouble than it's worth but I think the docs should be changed.

**Comment by reaperhulk** [comment]
Consensus here is apathy. Closing :smile:
