### ISSUE TITLE
cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKeyWithSerialization

### ISSUE THREAD

**Issue by fayak** [pyca/cryptography#1718]
First of all, please excuse my language, I'm not a native english speaker, and I'm a beginner with python and github, sorry if I make some mistakes.

I'm trying to generate a private key and then write it down in a file, like in the pem format, so I've read the doc about Key serialization, and the private_bytes method (https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#key-serialization) but I don't understand how to create a key with serialization. I've also seen that we have to create one using RSAPrivateKeyWithSerialization (https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKeyWithSerialization), but it also say that this feature is new in the 0.8 version, but I'm still in the 0.7.2, althought i did a pip install --upgrade cryptography. So what's the point with this method and the version of cryptography ? Is there another way to write my key in a file ?

**Comment by reaperhulk** [comment]
@fayak Our docs are slightly ahead of what we have released to PyPI. 0.7.2 is the newest right now and serialization won't be supported until 0.8. We do plan to release 0.8 later this week so you'll be able to use this feature to serialize keys in a few days.
