### ISSUE TITLE
Switch entirely to jenkins?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1729]
Right now we use both Travis and jenkins. Should we keep doing this?

Advantages of switching entirely to jenkins:
* We can submit coverage from more OSes and configurations or even combine coverage in jenkins itself.
* Faster. Much, much faster.

Disadvantages:
* Responsible for our own infrastructure (although we're already maintaining jenkins now, so...)
* Build status image served straight from jenkins (https://jenkins.cryptography.io/job/cryptography-master/badge/icon)
* Can't restart individual failed builds, only a complete job.

I'm in favor of moving because I'm tired of running into cases like today where Travis is running several hours behind. Iterating on PRs is becoming a consistently multi-day affair and it's draining for both the reviewer and the patch author.

To make this move we'll need to replicate what we're doing in Travis within jenkins. Proposed steps:

* Bring back the mavericks builders (we only run 10.7, 10.8, and 10.10 at the moment in jenkins). We only have two quad core mac minis in our build fleet so mac builds will be our bottleneck.
* Create ubuntu builders. We can mimic Travis exactly (12.04 and install 0.9.8k in another dir) or we could go 14.04 + an 0.9.8 version. I'd prefer the latter.
* Update the PR and master jobs to use these new builders.
* Turn on coveralls/codecov/whatever for the jenkins builders
* Turn off travis

**Comment by reaperhulk** [comment]
This is not on the table for 0.8 BTW, just wanted to get it out there to discuss.

**Comment by public** [comment]
I am happy^H^H^H^H^H^H volunteering to help tend to the Jenkins farm if this is something we decide to do.

**Comment by Ayrx** [comment]
Definitely +1 from me although I'm concerned how bad the OS X bottleneck will be vs Travis.

**Comment by alex** [comment]
I hate to say it, but I think a prequisit for this is bring our jenkins
under some sort of configuration management.

On Fri, Mar 6, 2015 at 8:50 PM, Terry Chia <notifications@github.com> wrote:

> Definitely +1 from me although I'm concerned how bad the OS X bottleneck
> will be vs Travis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1729#issuecomment-77666727>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
A bunch of ways we can go about that, but I believe @public has taken a look at jenkins configuration builder so I'd love to know his opinion there.

**Comment by reaperhulk** [comment]
Some discussion relevant to this issue here: https://mail.python.org/pipermail/cryptography-dev/2015-March/000394.html

**Comment by reaperhulk** [comment]
Closing this as something we're not going to do for now. Our travis configs have seen significant improvement and we may be able to share coverage with codecov now.
