### ISSUE TITLE
Support AES key wrap

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1733]
We previously chose to wait on supporting this until we had a use case. Simo pointed out in IRC that [JSON Web Encryption](https://tools.ietf.org/html/draft-ietf-jose-json-web-encryption-40) lists key wrap as one of the key wrapping methods.

This can be added to both the OpenSSL and CC backends.

**Comment by reaperhulk** [comment]
(see: https://github.com/simo5/jwcrypto as an example project that would consume this)

**Comment by reaperhulk** [comment]
This may tie to #1704 since key wrap and key encapsulation are very similar concepts.

**Comment by reaperhulk** [comment]
The RFC 3394 key wrap compatible primitive was added in 0.9.8h. Unfortunately this means it's not available in RHEL/CentOS 5 (a supported platform). To handle this we'll need to do a `aes_key_wrap_supported` method.

**Comment by simo5** [comment]
I have an implementatioon in jwcrypto code, would it be bad to use that as a fallback ?

**Comment by reaperhulk** [comment]
We generally do not include any cryptographic implementations directly in the project for a variety of reasons so it's unlikely that we'd accept that as a fallback path in our own codebase. That said, RFC 3394 is largely just an iterative call to the AES primitive and layering a small amount of logic on top of existing primitives is similar to what we did for HKDF support. By that logic maybe it would be acceptable. When the PR is submitted we'll be in a better position to have people weigh in.

**Comment by simo5** [comment]
See #1970

**Comment by Ayrx** [comment]
Can be closed after #1970 was merged. @reaperhulk
