### ISSUE TITLE
X509 Certificate Extensions

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1743]
This is a tracking issue for landing support for all extensions in [RFC 5280](http://tools.ietf.org/html/rfc5280).

Must support:
- [x] Authority Key Identifier
- [x] Subject Key Identifier
- [x] Key Usage
- [x] Subject Alternative Name
- [x] Basic Constraints
- [x] Extended Key Usage
- [x] CRL Distribution Points
- [x] Authority Information Access
- [x] Certificate Policies

**Comment by kevgliss** [comment]
+1 For this I have almost completed a port of my app off of M2Crypto onto this library. But I am still missing he ability to grab data from the subjectAltName extension.

**Comment by schlenk** [comment]
Maybe add Certificate to the issue title, as your list misses the X509 CRL extensions. But in general a pretty good thing and probably much nicer than having to use pyasn1 to parse all those by hand.

**Comment by reaperhulk** [comment]
Good call @schlenk, I've added certificate to the title to prevent confusion. CRL extensions will come later :)
