### ISSUE TITLE
Deprecate PublicKeyWithSerialization?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1748]
@alex and I talked about this in channel a few days ago, but is anyone aware of a situation where a public key will be opaque and unable to be serialized? If not, should we just make the PublicKey interfaces have the WithSerialization methods and potentially deprecate/remove the old interfaces?

**Comment by alex** [comment]
I'm going to go ahead and say this should be impossible. PublicKeys must be serializable.

**Comment by reaperhulk** [comment]
I agree -- I think the context of this question was whether we should get rid of WithSerialization and just have PublicKey imply it. I think the deprecation cycle and inconsistency makes this not worth it though. I'm fine with this being closed if you agree Alex.

**Comment by alex** [comment]
Any reason not to add the methods to the base `PublicKey` and then make
`WithSerialization` a deprecated alias for an extended period of time?

On Sat, Jul 4, 2015 at 11:05 AM, Paul Kehrer <notifications@github.com>
wrote:

> I agree -- I think the context of this question was whether we should get
> rid of WithSerialization and just have PublicKey imply it. I think the
> deprecation cycle and inconsistency makes this not worth it though. I'm
> fine with this being closed if you agree Alex.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1748#issuecomment-118518476>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
I think I'd like "WithSerialization" to stay permanently as an alias since it is consistent with the privatekey naming, but otherwise I am happy with moving the methods to the base.

**Comment by alex** [comment]
Sounds good.

On Sat, Jul 4, 2015 at 11:10 AM, Paul Kehrer <notifications@github.com>
wrote:

> I think I'd like "WithSerialization" to stay permanently as an alias since
> it is consistent with the privatekey naming, but otherwise I am happy with
> moving the methods to the base.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/1748#issuecomment-118518642>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
