### ISSUE TITLE
Improve TLS for cryptography.io and jenkins.cryptography.io

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1760]
Things we should do:

- [x] DH params on cryptography.io are too small
- [x] Disable DH on jenkins.cryptography.io (ECDHE only)
- [x] Disable TLS 1.0 and 1.1 on jenkins.cryptography.io (TLS 1.2 only)
- [x] Send HSTS on jenkins.cryptography.io
- [x] includeSubDomains for all HSTS
- [x] HSTS preload for the whole domain

**Comment by reaperhulk** [comment]
DH params on cryptography.io are now 2048-bit.

**Comment by alex** [comment]
We're submitted to the preload list.
