### ISSUE TITLE
Splitting our constant time compare implementation into a separate package.

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#1767]
Our constant time compare implementation can be useful outside of our specific cryptography library. Currently, wanting to use that one function requires pulling down the entire cryptography package which means a dependency on OpenSSL.

Do we want to entertain the possibility of pulling that specific function into a separate package that cryptography depends on?

**Comment by alex** [comment]
This is now available in the stdlib, so ours is really just for legacy purposes. I'm going to go with "no".
