### ISSUE TITLE
Support OCB

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1770]
OpenSSL 1.0.2 supports OCB mode. Test vectors available here: http://web.cs.ucdavis.edu/~rogaway/ocb/ocb-test.htm (should probably be translated into NIST format so we don't need to build another vector loader).

**Comment by reaperhulk** [comment]
Derp, it's actually only in master, not in 1.0.2. So this would be a 1.1.0 feature. Closing for now.

**Comment by azet** [comment]
I do have strong interest in this, it's due for the upcoming release.

@reaperhulk can I be of any help in implementing?

Thanks

**Comment by reaperhulk** [comment]
@azet due to major code reorg (and struct opaquing) in OpenSSL master we're going to have to spend quite a bit of time figuring out how to support that version. That will be a blocker for adding OCB support unfortunately. If you want to start investigating what is going to be required to do that it'd definitely help :)

(OCB support past that will be nearly trivial since it'll just be an EVP string and then hooking into our existing AEAD cipher handling)

**Comment by azet** [comment]
@reaperhulk that happens within your pyOpenSSL subproject I assume? I'll try to find some time, though I can't promise anything currently.

**Comment by reaperhulk** [comment]
Actually the bindings are resident in this project. Cryptography is built with a pluggable backend system and our primary backend is OpenSSL right now. Pyopenssl is actually pure Python and just consumes our bindings.

**Comment by azet** [comment]
Ah, ok - thanks for explaining. I assumed pyOpenSSL are bindings cryptography relies on. Will take a closer look at the source code.
