### ISSUE TITLE
X509 SubjectAltName

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1775]
Let's talk a bit about what a SubjectAltName class should look like. SAN is an extension encoded as an ASN.1 sequence of GeneralName objects. A GeneralName looks like this:

```
   GeneralName ::= CHOICE {
        otherName                       [0]     OtherName,
        rfc822Name                      [1]     IA5String,
        dNSName                         [2]     IA5String,
        x400Address                     [3]     ORAddress,
        directoryName                   [4]     Name,
        ediPartyName                    [5]     EDIPartyName,
        uniformResourceIdentifier       [6]     IA5String,
        iPAddress                       [7]     OCTET STRING,
        registeredID                    [8]     OBJECT IDENTIFIER }
```

In practice we could start by supporting dNSName only (which covers...almost every certificate), but ultimately we'll need to support at least dNSName, rfc822Name, directoryName, iPAddress, and uniformResourceIdentifier. 

And of course because X.509 is nothing if not infinitely flexible this is what an otherName looks like:

```
   OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }
```

Bleh. Let's not try to handle parsing of arbitrary ASN.1 structures right now.

So to support the sane subset we could just create a GeneralName object
```python
class GeneralName(object):
    def __init__(self, type, value):
        self.type = type
        self.value = value
```
(Incidentally GeneralName objects are used in other extensions like AuthorityInfoAccess, CRLDistributionPoints, and AuthorityKeyIdentifier)

We could then make
```python
class SubjectAlternativeName(object):
    def __init__(self, general_names):
        self.general_names = general_names

    def __iter__(self):
        iter(self.general_names)

    def get_names_by_type(self, type):
        return [i for i in i.type == type]
```

Of course, this is a pretty ugly API for the common case of "give me the SAN names for the certificate I just got during a TLS handshake. 

```python
cert = came_from_the_tls_connection
ext = cert.extensions.get_extension_for_oid(x509.OID_SUBJECT_ALTERNATIVE_NAME)
dns_names = ext.value.get_names_for_type(TYPE_DNSNAME)
for name in dns_names:
    print(name.value)
```

Maybe ultimately this data needs to be fed to something like `service_identity`?

**Comment by reaperhulk** [comment]
Some further evolution of this idea is now in #1783

**Comment by kevgliss** [comment]
I think that API is pretty reasonable. If you wanted to make the common case more straightforward you might consider something like:

    class SubjectAlternativeName(object):
        def __init__(self, general_names):
            self.general_names = general_names

        def __iter__(self):
            iter(self.general_names)

        def get_names_by_type(self, type=TYPE_DNSNAME):
            return [i for i in i.type == type]


The type would then only be specified as needed:

    ext = cert.extensions.get_extension_for_oid(x509.OID_SUBJECT_ALTERNATIVE_NAME)
    dns_names = ext.values.get_names()

**Comment by reaperhulk** [comment]
Yeah, the current approach in #1783 is basically that. Here's what's in that PR right now:

```python
class SubjectAlternativeName(object):
    def __init__(self, general_names):
        self._general_names = general_names

    def __iter__(self):
        return iter(self._general_names)

    def __len__(self):
        return len(self._general_names)

    def get_values_for_type(self, type):
        return [i.value for i in self if i.type is type]
```

Glad to see multiple lines of thought converging on the same solution :smile:

**Comment by reaperhulk** [comment]
(The only remaining work item to close this out is #1881)
