### ISSUE TITLE
Drop support for Python 3.2

### ISSUE THREAD

**Issue by dstufft** [pyca/cryptography#1809]
In #1783 @reaperhulk made a commit where he had to use ``six.u("")`` instead of ``u""`` because Python 3.2 does not support the ``u`` prefix on strings. We recently had a discussion about dropping Python 2.6 because it was no longer supported by Python upstream. However I think a more pertinent platform to drop would be Python 3.2.

Unlike 2.6, 3.2 is still technically supported by Python upstream (for just under another year, until February 2016) however as of the last number I looked at Python 3.2 has almost zero usage both across all of PyPI and specifically for cryptography. My numbers for this are months old at this point, however I would assume that with the release of Python 3.4 that the 3.2 numbers would get smaller and smaller and not grow. Also it appears that in at least one case (#1793) supporting Python 3.2 is forcing the use of less than optimal patterns (such as calling a function to do unicode instead of using the ``u`` prefix).

Here's the graphs I happen to have (2014):

#### All of PyPI

![stacked-py-pct](https://cloud.githubusercontent.com/assets/145979/6934848/a48b26fa-d809-11e4-9203-29ad347e140a.png)

#### Cryptography

![stacked-py-pct](https://cloud.githubusercontent.com/assets/145979/6934852/b7713f3e-d809-11e4-85b4-0ae648c5e515.png)

*Note: These graphs filter out any version that has less than some average number of downloads, so that accounts for any missing versions.*

**Comment by reaperhulk** [comment]
If we choose to use the IDNA 2008 library https://github.com/kjd/idna we're also going to have to patch it for Python 3.2 support. I've actually done this here: https://github.com/reaperhulk/idna/commit/af1d53fefbe4d2252d38b54c7e68a7b60b4c9cf1, but as you can see it's not the prettiest modification to make to the codebase.

**Comment by public** [comment]
I am colour blind but I assume that 3.2 is the line just about 2.7 in the first graph?

**Comment by dstufft** [comment]
Ah, yes sorry my graphs aren't particularly color blind friendly :(

Yes, 3.2 is that line, it's a very tiny sliver of a line that you can barely see.

**Comment by reaperhulk** [comment]
3.2 ships as the Python 3 in Ubuntu 12.04 but anybody who cares can get 3.4 from deadsnakes. I think I'm in favor of officially deprecating 3.2 support (and probably dropping it soon thereafter as we start needing the `idna` library for IDNA 2008)

**Comment by Lukasa** [comment]
3.2 is a massive pool of suck that draws the life out of everything it touches. I am :+1: on this.

**Comment by reaperhulk** [comment]
(This is done)
