### ISSUE TITLE
Fernet should provide an is_expired staticmethod/classmethod

### ISSUE THREAD

**Issue by tlynn** [pyca/cryptography#1811]
No decryption [key] is needed to check whether a token has expired. A "Fernet.is_expired(token, ttl=...)" API would e.g. allow token holders to check whether they need to refresh a token without a round trip.

It could also be useful to expose the timestamp (possibly as a datetime.datetime, but probably just as an int) e.g. so that old tokens can be pruned from a list.

**Comment by reaperhulk** [comment]
Right now you can get this with a tool like https://github.com/dolph/keyless-fernet, but it somewhat persuasive that such functionality could live in cryptography itself. Of course, without the key you can't verify that the TTL hasn't been altered, but there are scenarios where that doesn't matter.

**Comment by public** [comment]
Are there? Checking the TTL seems like something you'd often want to have good guarantees about. Imagine if you could modify the expires on an X.509 certificate.

**Comment by alex** [comment]
I think I'm -1 on this, it seems to be outside the spirit of fernet's "impossible to use wrong" construct.

**Comment by reaperhulk** [comment]
(Preface: I am not arguing to add this, just stating a use case). In a scenario where your model is "I have a token and I don't want to send it unless it's still valid" you can check your own token locally without the key and without paying a round trip penalty. This gives a significant performance benefit (you can avoid sending that request and just get a new encrypted token) with no security problem since the server (which has the key) will still do the proper checking even if you don't.

**Comment by Ayrx** [comment]
Even with the scenario @reaperhulk outlines I think I'm -1 on this. In most cases verifying the TTL without authenticating is a dangerous thing and exposing that option in our API will probably trip some people up.

If this use case ever comes up we can point people at that keyless-fernet library.

**Comment by tlynn** [comment]
Fernet tokens already fail the "impossible to use wrong test", since it's up to the verifier to provide their idea of a reasonable TTL. The current API doesn't require this, so tokens live forever if the ttl keyword argument isn't provided at verification time (as in the example usage!).  If you want "impossible to use wrong", you should make that a required argument.

Tokens include issuance timestamps rather than TTLs to allow the client-side refresh use case already described, and a variant in which either client or server may detect that tokens will soon need refreshing by checking with a lower TTL, so that tokens may be refreshed ahead of time.

These use cases could be served by exposing the token timestamp instead of an is_expired(ttl) test, though at a cost of having the user implement the easy-to-get-wrong validity window test.

**Comment by tlynn** [comment]
keyless-fernet does indeed seem to serve the purpose though.

**Comment by Ayrx** [comment]
@tlynn  TTL's are irrelevant for the prevalent use case of Fernet, which is simply authenticated symmetric encryption.

**Comment by tlynn** [comment]
Ok, I concede. Exposing untrusted data probably will bite someone eventually, or at least has enough potential to that it doesn't belong here.
