### ISSUE TITLE
Adding and enhancing PKCS7 support

### ISSUE THREAD

**Issue by mahmoud** [pyca/cryptography#1828]
Per our discussion with @reaperhulk on IRC last night, another engineer from the PayPal security contingent (Mark, @mwilliam3) and I plan on adding PKCS7 support to cryptography/PyOpenSSL. We'll be getting a pull request together with the bindings today, hopefully in time for the 0.9 release. Initially we'd only planned to add bindings for signing support, but after last night's discussion, I think we'll be going ahead and adding bindings for all of OpenSSL's PKCS7 (signing/encryption/decryption).

Once that's all good to go, we'll link to the changes we'd planned for PyOpenSSL. Then we can all deliberate on whether the changes should go to PyOpenSSL or might be a fit here in cryptography, as the following issues seem to suggest: #924, #1621, and #1820.

(FTR: here's our cryptography fork: https://github.com/paypal/cryptography)

**Comment by timdawborn** [comment]
Really happy to see PKCS7 support coming to cryptography. M2Crypto is such a blocker for app py3k support. Please keep us all updated here on the progress.

**Comment by reaperhulk** [comment]
Closing this in favor of #1621.
