### ISSUE TITLE
Replace uses of `six.u` with the `u` prefix

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#1870]
Now that we dropped 3.2, we should do this to clean up the place.

(Note to whoever does this, please only do a few files at a time, reading and reviewing shorter diffs is much easier)

**Comment by sigmavirus24** [comment]
:+1:

**Comment by eeshangarg** [comment]
Hello!

Just thought I would leave a comment that I am working on this and will be submitting a PR as soon as I can. :-)

Thanks!
Eeshan Garg
