### ISSUE TITLE
DER encoding not supported for RSA public keys (error: "Only PEM encoding is supported by this backend")

### ISSUE THREAD

**Issue by shea256** [pyca/cryptography#1875]
Hi! I've been using cryptography to generate RSA keypairs and encode them into PEMs and it's been working wonderfully.

Unfortunately now I'd like to encode them into DER format but I'm having trouble and getting the following error:

`ValueError: Only PEM encoding is supported by this backend`

I tried substituting `default_backend` for the backend found in `cryptography.hazmat.backends.openssl.backend` but this didn't work either.

Any guidance would be much appreciated. Here is my code for reference:

```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization


def generate_keypair(public_exponent, key_size):
    private_key = rsa.generate_private_key(
        public_exponent=public_exponent,
        key_size=key_size,
        backend=default_backend())
    public_key = private_key.public_key()
    return private_key, public_key


def serialize_public_key_to_der(public_key):
    public_key_der = public_key.public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo)
    return public_key_der


private_key, public_key = generate_keypair(RSA_PUBLIC_EXPONENT, RSA_KEY_SIZE)

public_key_der = serialize_public_key_to_der(public_key)
```

Thanks!

**Comment by reaperhulk** [comment]
The next release (0.9) adds support for DER encoding :) If you need it immediately you can use the master branch, but otherwise it should be out in May.

**Comment by shea256** [comment]
OK thanks! I'll install from the most recent commit on the master branch.
