### ISSUE TITLE
Add binding for SSL_set_verify

### ISSUE THREAD

**Issue by mithrandi** [pyca/cryptography#1908]
This will be needed for pyca/pyopenssl#255.

**Comment by alex** [comment]
```c
void SSL_set_verify(SSL *s, int mode,
                    int (*callback) (int ok, X509_STORE_CTX *ctx));
```

is the signature

**Comment by mithrandi** [comment]
I expect SSL_set_verify_depth should also be added at the same time, with this signature:
```
        void SSL_set_verify_depth(SSL *s, int depth);
```

**Comment by eeshangarg** [comment]
Hello!

I am working on this and I will submit a PR as soon as I can. I'll post here if I have any questions. :-)

Thanks,
Eeshan Garg
