### ISSUE TITLE
CA support functions

### ISSUE THREAD

**Issue by AndreLouisCaron** [pyca/cryptography#1911]
Hi all,

I've been playing around with this package and it seems quite promising.  I'd like to write a simple CA in Python, but it seems there are quite a few parts missing (ability to generate a CSR, create a certificate from a CSR, add exceptions then sign it, generate and sign a CRL, etc.).

I managed to sketch together some of the key operations for the OpenSSL backend.  Right now, I have this working:
- as a requester, generate a CSR with configurable subject and basic constraints (CA, pathlen);
- as a CA, open a CSR, "convert" it to a certificate and sign it;
- as a CA, generate a CRL, add serial number & revocation date pairs, then sign it.

If you guys are interested, I might be able to contribute these in a cleaned up form  Are you interested in adding support for this in your package?

Assuming you are interested, I have no idea how you envision this in the API.  The certificate and CSR classes seem to be oriented for a read-only scenario.  Maybe it would be better to have separate CSRBuilder and CertificateBuilder classes or something?  How do you envision this in the API?  Maybe you can draft some interface and I can implement that, submit a pull request and then we can talk about it some more?

Also, would it be OK if it only supports the OpenSSL backend?

**Comment by AndreLouisCaron** [comment]
BTW, I've subscribed to the mailing list.  Show we discuss that there instead?

**Comment by kevgliss** [comment]
I would be interested in having the ability to create CSRs, which library are you using to do this at the moment?

**Comment by reaperhulk** [comment]
We actually do most of our discussions on issues like this in GitHub as well as in #cryptography-dev on freenode.

We are definitely focused on building read-only classes at the moment, but they've been built with an eye towards being able to use them in the future for certificate generation. After the next release we'll be in a much better position to potentially land this type of work on master. :)

As for API, a CertificateBuilder class is something we've talked a bit about on the mailing list (https://mail.python.org/pipermail/cryptography-dev/2015-May/000442.html) and @etrauschke has also started a thread discussing CRL work (https://mail.python.org/pipermail/cryptography-dev/2015-May/000446.html).

If you'd like to start going down the path of discussing the APIs I'd suggest posting either a work in progress PR or just markdown examples of the interfaces in an issue and we can talk about them.

Thanks for being interested in helping with the project! :smile:

**Comment by AndreLouisCaron** [comment]
@kevgliss For the moment, I hacked this together using the OpenSSL CFFI bindings in this project :-)

@reaperhulk Thanks for the info, I'll read up on the existing work before I do anything else!  Right now, I really hacked this together quickly without any proper interfaces of any kind.  I'll try to draft some (hopefully clean) interfaces and post it up in a PR.  I guess you can review it and we can improve from there.

**Comment by AndreLouisCaron** [comment]
I put a up a draft implementation in PR #1914.  Maybe you can close this issue and we can keep the discussion going in that thread.
