### ISSUE TITLE
 AES CTR using openssl EVP cipher routines

### ISSUE THREAD

**Issue by konstantinosA** [pyca/cryptography#1925]
Are there any steps to follow for correct implementation of AES-ctr mode using openssl EVP cipher routines?
According to this article "http://openssl.6102.n7.nabble.com/AES-256-using-CTR-mode-td43143.html"  on a similar question someone  mentions "Just replace EVP_bf_cbc() with EVP_aes_256_ctr(), and ensure you use an appropriately sized key and IV."
According to Wikipedia "https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation" is mentioning that  "Note that the nonce in this diagram is the same thing as the initialization vector (IV) in the other diagrams. The IV/nonce and the counter can be combined together using any lossless operation (concatenation, addition, or XOR) to produce the actual unique counter block for encryption."
Searching the documentation for EVP  in  "https://www.openssl.org/docs/crypto/EVP_EncryptInit.html#" nothing is mentioned for ctr mode. 
I am confused on how to implement this. 
Are there any recommended steps on how to?
e.g. if iv, key is fixed length will the following calls returns us the correct encryption ctr encryption 
        EVP_EncryptInit_ex(&ctx, EVP_aes_256_ctr(), NULL, key, iv);
        EVP_EncryptUpdate(&ctx,out, &out_len, in, len_in);

**Comment by reaperhulk** [comment]
This heavily depends on what version of OpenSSL you're using...but we actually solved this for you in the Python layer. You can do AES CTR (using EVP in 1.0.1+) or via the lower level interfaces (0.9.8) just by using our standard primitives. If you want to see how it's done take a look in cryptography/hazmat/backends/openssl/ciphers.py

**Comment by reaperhulk** [comment]
(Also, note that while we extensively leverage OpenSSL we are really a python project so questions of this type are generally better suited for openssl specific mailing lists).
