### ISSUE TITLE
Should all x509 extensions support eq/ne?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#1930]
While implementing the Python layer of X509 extensions I kind of haphazardly implemented ``__eq__`` on some of them but not others. Should we just have them everywhere? Unchecked extensions below do not have equality operators.

- [x] Authority Key Identifier
- [x] Subject Key Identifier
- [x] Key Usage
- [x] Subject Alternative Name
- [x] Basic Constraints
- [x] Extended Key Usage
- [x] CRL Distribution Points
- [x] Authority Information Access
- [x] Certificate Policies

**Comment by alex** [comment]
Yes, I believe all should have it
