### ISSUE TITLE
Missing functions (i2o_ECPublicKey, i2d_ECPrivateKey, etc.)

### ISSUE THREAD

**Issue by posita** [pyca/cryptography#1969]
Currently, `cryptography` is missing the following functions (useful if not necessary for ECDSA):

* [`d2i_ECPrivateKey`](http://openssl.sourcearchive.com/documentation/1.0.0d-2/crypto_2ec_2ec_8h_aeaa259adce95b0937cf6bf5cd2221639.html#aeaa259adce95b0937cf6bf5cd2221639)
* [`i2d_ECPrivateKey`](http://openssl.sourcearchive.com/documentation/1.0.0d-2/crypto_2ec_2ec_8h_ae714ab3e64494618b04e190bffa88030.html#ae714ab3e64494618b04e190bffa88030)
* [`i2o_ECPublicKey`](http://openssl.sourcearchive.com/documentation/1.0.0d-2/crypto_2ec_2ec_8h_a1a93f5739c093586ef83517b52b44a0c.html)
* [`o2i_ECPublicKey`](http://openssl.sourcearchive.com/documentation/1.0.0d-2/crypto_2ec_2ec_8h_a628017a03d4a4600b9f62ccb56699239.html#a628017a03d4a4600b9f62ccb56699239)

The latter two can be worked around using calls `cryptography` *does* expose, but the first two are more difficult. petertodd/python-bitcoinlib#62 provides a use case.

**Comment by reaperhulk** [comment]
We do have `i2d_ECPrivateKey_bio` as well as `d2i_ECPrivateKey_bio`, which will do the same thing as the d2i/i2d functions you list only using BIOs.

**Comment by posita** [comment]
Hmmm...not sure I'm using them correctly, but:

```py
>>> from binascii import unhexlify
>>> foo_der = unhexlify('06052b8104000a30740201010420bfc5f3e5fb7d9273551c01277643c258d72446aeb2f8cd8ec25ab6bfd5d71c7ea00706052b8104000aa1440342000448814850d8ded494faf8fbd7672849e6384ad505271e014e2cf11fec75b00fe0459f0493c1c579f12906955513860edb5eaeaf3d913a9ab43166b3a0fd40e95a')
>>> from cryptography.hazmat.bindings.openssl.binding import Binding
>>> _binding = Binding()
>>> _ssl = _binding.lib
>>> _ffi = _binding.ffi
>>> foo_der_cbuf = _ffi.new('char[]', foo_der)
>>> bio = _ssl.BIO_new_mem_buf(foo_der_cbuf, len(foo_der))
>>> bio = _ffi.gc(bio, _ssl.BIO_free)
>>> bio
<cdata 'BIO *' 0x7fee68751850>
>>> k = _ssl.d2i_ECPrivateKey_bio(bio, _ffi.NULL)
>>> k
<cdata 'EC_KEY *' NULL>
>>> bio_method = _ssl.BIO_s_mem()
>>> bio = _ssl.BIO_new(bio_method)
>>> bio = _ffi.gc(bio, _ssl.BIO_free)
>>> bio
<cdata 'BIO *' 0x7fee68602c10>
>>> _ssl.i2d_ECPrivateKey_bio(bio, k)
0
>>> buf = _ffi.new('char**')
>>> buf_len = _ssl.BIO_get_mem_data(bio, buf)
>>> buf_len
0
```

Am I doing something wrong?

**Comment by reaperhulk** [comment]
Take a look at how we do it here: https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L721

There's quite a bit of complexity unfortunately.

For serializing back to DER (PKCS8 or traditional) here's one way to do it:

https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/ec.py#L203
which calls
https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L1151
