### ISSUE TITLE
setuptools script installs dependencies to temporary .eggs directory

### ISSUE THREAD

**Issue by novocaine** [pyca/cryptography#1995]
This is setuptools' fault, but this does make a mess of people's python install, so putting it here in case anyone cares to work around it or follow up.

My ticket against setuptools:

https://bitbucket.org/pypa/setuptools/issue/391/dependencies-listed-in-both-setup_requires

For python-crytography, this meant for me that my easy-install.pth, after installation, contained this:

(dir i ran setup.py from)\.eggs\ipaddress-1.0.7-py2.7.egg
(dir i ran setup.py from)\.eggs\idna-2.0-py2.7.egg
(dir i ran setup.py from)\.eggs\cffi-1.0.3-py2.7-win32.egg
(dir i ran setup.py from)\.eggs\enum34-1.0.4-py2.7.egg
(dir i ran setup.py from)\.eggs\pyasn1-0.1.7-py2.7.egg
(dir i ran setup.py from)\.eggs\pycparser-2.13-py2.7.egg

Whereas you would expect these to be in my site-packages dir - I ran setup.py from a temporary dir.

**Comment by alex** [comment]
This is a setuptools thing -- I don't think it's actionable as a cryptography bug, so I'm marking this as closed.
