### ISSUE TITLE
osrandom_engine should validate the fd's st_dev and st_ino

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#2007]
CPython keeps a persistent fd to /dev/urandom, too. It also keeps the fd's st_dev and st_ino around and validates both before it reads from the fd. The extra check prevents tampering with the fd.

http://bugs.python.org/issue21207

**Comment by reaperhulk** [comment]
:+1:

**Comment by reaperhulk** [comment]
This issue is no longer relevant since we've landed #2073
