### ISSUE TITLE
Remove some py26 from our test suite

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2060]
We chose to deprecate (but not remove support for) Python 2.6 in the previous release. As part of that I think we should reduce the number of build configurations for it in our test infrastructure. Currently we run tests against py26 in the following ways:

Jenkins:
* CentOS 5
* Windows 32-bit
* Windows 64-bit
* Ubuntu 14.04 (against OpenSSL 1.0.2)
* OS X 10.8

Travis:
* Ubuntu 14.04 (against 0.9.8 and 1.0.1)
* OS X 10.10 (against 0.9.8 and 1.0.2)

I'd like to remove the 0.9.8 tests from the Travis infra and the OS X 10.8 and Ubuntu 14.04 tests from the jenkins infra. That will leave sufficient coverage to be confident that py26 is still working while improving our test performance and giving us some breathing room for the addition of py35 in September.

**Comment by alex** [comment]
As long as we continue to support it, I'm not sure I agree with removing builds.

**Comment by dstufft** [comment]
I agree, either it's supported in which case we should test it like everything else, or it isn't supported and we should be honest and drop all of the builders.

**Comment by reaperhulk** [comment]
We test limited subsets of a variety of versions for various reasons, but I don't feel strongly enough about this to press for it. Closing :grinning:
