### ISSUE TITLE
[BLOCKER] Conditional names broken

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2061]
When we switched to `set_source` in #1986 we broke conditional name binding. Instead of being removed as the lib is instantiated the NULL function pointers are available and, if called, cause a segfault.

**Comment by reaperhulk** [comment]
The fix for this should also include a test that verifies that conditional names are removed. We can reliably test this by creating a conditional that will always be false.

**Comment by reaperhulk** [comment]
I've been thinking about this for a bit and haven't come up with a silver bullet. Here's a potential solution though:

Pull the `Cryptography_HAS_*` declarations into a separate section and compile that. Use the resulting lib object to check for support and append the dependent types/functions/macros to the strings for the main compilation stage. Once that's done, compile the "real" lib objects and be done.

There are some challenges for this. For instance, we'll need to figure out how to delete the dylib generated by that first compilation (Donald?). Additionally, the `Cryptography_HAS_*` values are used by PyOpenSSL in various places (and potentially other libraries) so we will need to continue to have them in the main library.

I don't particularly like this solution, but I'm not seeing a better one at the moment. /cc @alex @dstufft

**Comment by dstufft** [comment]
It's basically reinventing shit like the preprocessor and autotools, and since folks haven't figured out a better way than those solutions for that... I doubt we're probably going to either.

**Comment by reaperhulk** [comment]
If we do it this way what's the best way to delete the temporary module we build?

**Comment by dstufft** [comment]
I would just use the old API for it, since it should only exist in the build scripts and won't be mentioned in the setup.py I don't think you need to delete it, it'll get cleaned up with the rest, but I may be wrong on that.

**Comment by alex** [comment]
Alternative -- wrap `lib` with something that doesn't allow access to things in `CONDITIONAL`, at runtime.
