### ISSUE TITLE
[BLOCKER] Unpin ipaddress

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2152]
This should be considered a blocker for 1.0. #2151 pins our `ipaddress` dep, but that's just a temporary workaround while upstream is fixed.

Alternately we could look into whether switching to `py2-ipaddress` makes sense, but that does have quite a few potential negatives.

**Comment by alex** [comment]
Bug filed with PyPy: https://bitbucket.org/pypy/pypy/issues/2079/behavior-difference-from-cpython-with

**Comment by alex** [comment]
Bug filed with `ipaddress` here: https://github.com/phihag/ipaddress/issues/19

**Comment by reaperhulk** [comment]
Fixed in 1.0.10
