### ISSUE TITLE
Issues building cryptography with custom OpenSSL build on linux

### ISSUE THREAD

**Issue by cecemel** [pyca/cryptography#2157]
Hi, 

I'm trying to build cryptography with a custom OpenSSL build.
After performing with custom openssl.ld:
./config -Wl,--version-script=openssl.ld -Wl,-Bsymbolic-functions -fPIC shared
sudo make install

But after that, I am not sure on how to proceed.
I guess it should be python2.7 setup.py install with a flag, but the doc does not seem very straightforward to me. 
thx

**Comment by reaperhulk** [comment]
You'll need to set `CFLAGS` and `LDFLAGS` to point at the location you installed to while running the install command. Additionally, if you left the so version as 1.0.0 you'll probably run into problems when loading the linked library and will need to recompile with a diff so version.

**Comment by cecemel** [comment]
Hi, 

thanks for the info. It did the job! If I may, I'll put the script I used here, so people might reuse it if needed.
(feel free to delete if it bothers you)

OPENSSL_VERSION=openssl-1.0.2d
LD_FILE_CONTENT="OPENSSL_1.0.2D_CUSTOM { global: *; };"
cd /tmp
mkdir /tmp/openssl_install
mkdir /tmp/openssl_install/new_openssl
cd /tmp/openssl_install
wget https://www.openssl.org/source/$OPENSSL_VERSION.tar.gz
tar -xzvf $OPENSSL_VERSION.tar.gz
cd $OPENSSL_VERSION
echo $LD_FILE_CONTENT > /tmp/openssl_install/openssl.ld
./config --prefix=/tmp/openssl_install/new_openssl --openssldir=/tmp/openssl_install/new_openssl -Wl,--version-script=/tmp/openssl_install/openssl.ld -Wl,-Bsymbolic-functions -fPIC shared
make
echo "START CRYPTOGRAPHY"
sudo pip uninstall cryptography -y
env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/tmp/openssl_install/new_openssl/lib" CFLAGS="-I/tmp/openssl_install/new_openssl/include" pip install cryptography --force-reinstall
