### ISSUE TITLE
Switch to Open Code of Conduct?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2161]
We have some language about being under the PSF's code of conduct but it'd be nice to be more specific and have a process if someone would like to address a grievance.

Here's the proposed template: http://todogroup.org/opencodeofconduct/

I'm manifestly unqualified to review the quality of this CoC, but it seems okay on first read. I'd like to get opinions from other PyCA members (as well as members of marginalized groups who have the most to gain/lose from CoCs).

I'd also like to consider adopting this across PyCA entirely, rather than just the cryptography project so /cc @hynek since he is the current "lead" on pyOpenSSL.

**Comment by hynek** [comment]
We should invite someone who actually knows something about these things and not try to have opinions ourselves.

Seems like people aren’t too happy with it.  See https://twitter.com/stubbornella/status/623396790402854912 and ff.

**Comment by alex** [comment]
I'm going to go ahead and say no, OCoC has a number of issues.

**Comment by hynek** [comment]
How about http://contributor-covenant.org ?

**Comment by hynek** [comment]
Ping, since this is coming up:  the PSF CoC is not very good because it’s not explicit, and doesn’t list neither procedures for reporting nor consequence.  It's more like guidelines.  Twisted went for CC; shouldn’t we follow?
