### ISSUE TITLE
Alternative ANS1 Encoder/Decoder

### ISSUE THREAD

**Issue by wbond** [pyca/cryptography#2162]
I've been working on a bunch of cryptography stuff that is somewhat parallel to what the cryptography package is doing (a different philosophical approach), but in the process needed a better library than pyasn1.

With the recent work on generating CSRs and certs, I figured I'd share what I've been doing in the slight chance that it may be useful.

https://github.com/wbond/asn1crypto

It provides class-based declarative structure for parsing BER/DER and generating DER encodings, along with a PEM encoder and decoder. There are predefined classes for most of the ASN1 structures associated with PKI. The readme has an overview, with documentation about the core usage. Currently the details of the structures are referenced only via the source code since user-docs would be almost identical.

Currently I am in the process of building out a project that will utilize CMS structures, but along the way am building cert validation with OCSP, CRL, path building, etc. Because of this I am slowly adding high-level attributes and methods to the various classes to help with common tasks.

**Comment by wbond** [comment]
Recently Python 2.6 support was added. Previously only 2.7+ were supported.

**Comment by reaperhulk** [comment]
I've pulled an initial asn1crypto dep into #2435

**Comment by alex** [comment]
Going to close this issue, as there's no actual work here.
