### ISSUE TITLE
Issue compiling cryptography in master branch

### ISSUE THREAD

**Issue by DoctorMalboro** [pyca/cryptography#2164]
I'm trying to compile Cryptography in Windows XP Professional SP3 and Python 2.7 with mingw, but I keep facing the same issue: http://pastebin.com/1Rbb6t1H

**Comment by reaperhulk** [comment]
We have prebuilt wheels for use, but we only support compilation under windows using Visual Studio compilers.

**Comment by DoctorMalboro** [comment]
@reaperhulk Thanks, but as I'm trying to fix the same issue as ticket #1524, I've tried installing the latest cryptography version available and had the same issue. Is this fixed in any of the prebuilt wheels?

**Comment by reaperhulk** [comment]
@DoctorMalboro the next release may improve the situation for tools like cx_freeze, pyinstaller, etc but the current one (which includes the prebuilt wheels) does not. Sorry about that :(

To compile this yourself on Windows you'll need the VS2008 compiler + a version of OpenSSL that will link against it properly (which means you can't use the slproweb.com binary distribution any more). We actually build our own OpenSSLs (you can get the 32-bit build here https://jenkins.cryptography.io/job/openssl-win32-release/). You'll also need to verify you have the INCLUDE and LIB environment variables set properly of course.

**Comment by DoctorMalboro** [comment]
@reaperhulk Thank you for the information, I'll give it a try!

**Comment by reaperhulk** [comment]
I'm going to go ahead and close this issue since there's nothing for us to do.
