### ISSUE TITLE
create separate namespaces for OIDs used for different things

### ISSUE THREAD

**Issue by glyph** [pyca/cryptography#2165]
When reviewing the documentation in #2154, it occurred to me that especially for someone not familiar with the ASN.1 structures involved, it might be pretty confusing that name OIDs and signature OIDs are in the same namespace.

I'd like tab completion to work in `bpython`, for example :).  So it would be good to split https://cryptography.io/en/latest/x509/reference/#name-oids and https://cryptography.io/en/latest/x509/reference/#signature-algorithm-oids into separate namespaces in the code as they are in the docs.

**Comment by reaperhulk** [comment]
@glyph do you see this as `x509.oid.name.COMMON_NAME` and `x509.oid.signaturealgorithm.ECDSA_WITH_SHA512`? I'm happy to put these in separate modules, although I think we probably will leave them aliased in their original location without deprecation (unless someone has a compelling reason that we should deprecate).

**Comment by glyph** [comment]
I was actually thinking classes, like `x509.oid.Name.COMMON_NAME` and `x509.oid.SignatureAlgorithm.ECDSA_WITH_SHA512`.  Leaving them aliased for a while seems reasonable, it doesn't seem like it would be much of a maintenance burden.

**Comment by alex** [comment]
This is done.
