### ISSUE TITLE
Bring branch coverage up to 100%

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2182]
The following lines have partial coverage:

- https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/rsa.py#L241
- https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/rsa.py#L431

**Comment by reaperhulk** [comment]
This is resolvable via the same method as #2553. We'd just need to add a single `1.0.0t` builder. Once that one lands I can put in a PR for this.
