### ISSUE TITLE
Random number generation docs should mention ints

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2190]
https://cryptography.io/en/latest/random-numbers/ doesn't say what to do if you want an integer, instead of bytes.

**Comment by alex** [comment]
`int.from_bytes(os.urandom(16), "big")` is strictly speaking the right answer.

**Comment by alex** [comment]
Except python 2.6 :-(

**Comment by alex** [comment]
A fun test might be to just put the `int.from_bytes()` bit in teh docs and see who complains?

**Comment by wbond** [comment]
Probably everyone who is using Python 2.7 will complain also since it is 3.2+.

**Comment by alex** [comment]
@reaperhulk do you have thoughts about whether to recommend `int.from_bytes` (py3 only), make our `int_from_bytes` public, or some third option I haven't thought of.

**Comment by reaperhulk** [comment]
I'm inclined to say `int.from_bytes()` or `int(uuid.UUID4())` ("only" 128-bit, but py2/py3)
