### ISSUE TITLE
CertificateBuilder Extensions Support

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2192]
We should support this minimum set of extensions for our 1.0 release:

- [x] SubjectKeyIdentifier
- [x] AuthorityKeyIdentifier
- [x] AuthorityInformationAccess
- [x] CRLDistributionPoints
- [x] KeyUsage
- [x] ExtendedKeyUsage
- [x] SubjectAlternativeName
- [x] BasicConstraints

Not blockers for tenth release but tracking:
- [x] CertificatePolicies (#2220)
- [x] OCSPNoCheck (PR coming after current ones land)
- [x] IssuerAlternativeName
- [x] InhibitAnyPolicy (PR coming after current ones land)
- [x] NameConstraints

**Comment by reaperhulk** [comment]
SubjectKeyInformation and AuthorityKeyInformation have hashes of public key data that they want. Specifically they'd like to have the SHA1 hash of the BIT STRING value of "subjectPublicKey" (which is embedded in the subjectPublicKeyInfo structure). There's two primary ways we can do this.

* We can defer to OpenSSL (which is a pain but can probably be done with some calls to `X509_PUBKEY_set` and de-opaquing part of the `X509_PUBKEY` struct). This will require us to add a new attribute to the PublicKey interfaces (`key_identifier_hash` or something).
* We can do it ourselves in a classmethod on SubjectKeyInformation. This will require checking for each key type, converting to numbers, encoding the numbers into the appropriate sequence via pyasn1, then hashing the resulting bytes (which we can do with hashlib so we don't need to know what backend the key came from).

Both ways kind of suck, but I'm leaning towards the latter right now. Opinions?

**Comment by alex** [comment]
Err, why not just `public_key.public_bytes(Encoding.DER,
Format.SubjectPublicKeyInfo)`?

On Tue, Aug 4, 2015 at 5:05 PM, Paul Kehrer <notifications@github.com>
wrote:

> SubjectKeyInformation and AuthorityKeyInformation have hashes of public
> key data that they want. Specifically they'd like to have the SHA1 hash of
> the BIT STRING value of "subjectPublicKey" (which is embedded in the
> subjectPublicKeyInfo structure). There's two primary ways we can do this.
>
>    - We can defer to OpenSSL (which is a pain but can probably be done
>    with some calls to X509_PUBKEY_set and de-opaquing part of the
>    X509_PUBKEY struct). This will require us to add a new attribute to
>    the PublicKey interfaces (key_identifier_hash or something).
>    - We can do it ourselves in a classmethod on SubjectKeyInformation.
>    This will require checking for each key type, converting to numbers,
>    encoding the numbers into the appropriate sequence via pyasn1, then hashing
>    the resulting bytes (which we can do with hashlib so we don't need to know
>    what backend the key came from).
>
> Both ways kind of suck, but I'm leaning towards the latter right now.
> Opinions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2192#issuecomment-127761393>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
Because subjectPublicKeyInfo is not subjectPublicKey. The former is:

```
   SubjectPublicKeyInfo  ::=  SEQUENCE  {
        algorithm            AlgorithmIdentifier,
        subjectPublicKey     BIT STRING  }
```

So if we parse that with pyasn1 we can simplify a bit (we'll at least have the bit string without having to know the key type) but we'll still need an ASN1 parser to do it.

**Comment by alex** [comment]
ffs. ok. thanks.

On Tue, Aug 4, 2015 at 7:20 PM, Paul Kehrer <notifications@github.com>
wrote:

> Because subjectPublicKeyInfo is not subjectPublicKey. The former is:
>
>    SubjectPublicKeyInfo  ::=  SEQUENCE  {
>         algorithm            AlgorithmIdentifier,
>         subjectPublicKey     BIT STRING  }
>
> So if we parse that with pyasn1 we can simplify a bit (we'll at least have
> the bit string without having to know the key type) but we'll still need an
> ASN1 parser to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2192#issuecomment-127793090>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
I have been unable to figure out how to create name constraints extensions without either using the `NCONF` functions (which would require us translating our data into openssl conf file format -- utterly unlike every other extension and prone to bugs) or pulling the declarations from `v3_ncons.c` so that we can have `i2d_NAME_CONSTRAINTS`.

**Comment by alex** [comment]
These are all done now!
