### ISSUE TITLE
Feature Request: ANSI X9.63 KDF

### ISSUE THREAD

**Issue by bmw** [pyca/cryptography#2203]
Coming with the new [key agreement method in Let's Encrypt](https://letsencrypt.github.io/acme-spec/#rfc.section.5.6) is the use of the [ANSI X9.63 KDF](http://www.secg.org/sec1-v2.pdf) defined in section 3.6.1. It would be fantastic if support for this KDF could be added.

**Comment by alex** [comment]
So close to ConcatKDF, and yet so far away :-(

**Comment by bradmw** [comment]
I know! At first glance, the two look identical. Thanks again for all the help.

**Comment by simo5** [comment]
Why Let's encrypt is using that one ? The document you linked there explicitly says: "The NIST-800-56-Catenation-KDF should be used, except for backwards compatability with im-
plementations already using one of the three other key derivation functions."

Sigh...

**Comment by simo5** [comment]
Do you know of any test vectors for this KDF ?
I can code it up but I'd like to test it too ...

**Comment by reaperhulk** [comment]
@bradmw was this KDF recently chosen? I'd like to hear the rationale for choosing it over ConcatKDF given that the linked document explicitly states that ConcatKDF should be used except in cases where backwards compatibility is required.

**Comment by bradmw** [comment]
@reaperhulk, yes this KDF was recently chosen. You bring up an excellent point. I will bring it up with those who made that decision and get back to you. Sorry for potentially creating this issue unnecessarily.

**Comment by bradmw** [comment]
So after bringing this up with the rest of the development team, it seems that we are sticking with ANSI-X9.63-KDF.

@simo5, there appears to be some test vectors [here](http://read.pudn.com/downloads168/doc/772358/TestVectorsforSEC%201-gec2.pdf).

@reaperhulk, as for why this decision was made, I hope that @bifurcation can chime as he was the one who originally chose this KDF.

**Comment by bmw** [comment]
Per @reaperhulk's request, dropping a comment on here to check the status of this issue. This is a feature that Let's Encrypt needs supported for our launch the week of November 16th.

**Comment by Ayrx** [comment]
@simo5 Are you actively working on this? Else I can grab this and have a patch up by the weekends.

**Comment by simo5** [comment]
Working on it.

**Comment by simo5** [comment]
Btw does anyone have access to ANSI X9.63:2001 or X9.63:2011 ?
SEC1 V2 does describe the KDF but does not explicitly say what to do if the optional sharedinfo is missing. From the notiation it looks like it will be completely omitted from the input provided to the hash function, but I'd like to verify with the ANSI documents (originals paywalled).

**Comment by simo5** [comment]
Nevermind I found Test Vectors and they confirm my read
