### ISSUE TITLE
Make it possible to install Cryptography without OpenSSL

### ISSUE THREAD

**Issue by glyph** [pyca/cryptography#2214]
It should be possible to install Cryptography without the OpenSSL backend, and get all its functionality (aside from its hazmat bindings, of course).

**Comment by glyph** [comment]
I think this has been discussed elsewhere but I couldn't find a specific issue to start recording what the necessary work would be to actually make this happen.  I suspect this will be a long slog.

**Comment by reaperhulk** [comment]
#1522 is basically this.

**Comment by glyph** [comment]
Thanks for the link.  I was going to close as dup, but I think this needs to track additional work as well - like, are the other backend APIs sufficiently full-featured to do useful things (like TLS)?

**Comment by alex** [comment]
Cryptography doesn't have a TLS API.

On Wed, Aug 5, 2015 at 8:01 PM, Glyph <notifications@github.com> wrote:

> Thanks for the link. I was going to close as dup, but I think this needs
> to track additional work as well - like, are the other backend APIs
> sufficiently full-featured to do useful things (like TLS)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2214#issuecomment-128188232>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by glyph** [comment]
> Cryptography doesn't have a TLS API.

Indeed not, but right now pyOpenSSL does, and it wraps OpenSSL specifics using Cryptography.  So one prerequisite would be giving pyOpenSSL something else to depend on, ideally *eventually* providing equivalent functionality…

**Comment by alex** [comment]
I don't think that's a good direction. pyOpenSSL mirrors OpenSSL's API all
over the place, quirks and all. It is in many ways not a good TLS API (e.g.
it is wildly unsafe out of the box).

On Thu, Aug 6, 2015 at 12:33 AM, Glyph <notifications@github.com> wrote:

> Cryptography doesn't have a TLS API.
>
> Indeed not, but right now pyOpenSSL does, and it wraps OpenSSL specifics
> using Cryptography. So one prerequisite would be giving pyOpenSSL something
> else to depend on, ideally *eventually* providing equivalent
> functionality…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2214#issuecomment-128234151>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by glyph** [comment]
> I don't think that's a good direction. pyOpenSSL mirrors OpenSSL's API all
> over the place, quirks and all. It is in many ways not a good TLS API (e.g.
> it is wildly unsafe out of the box).

I think you are misunderstanding me.  I am *definitely* not suggesting that Cryptography design a pyOpenSSL-compatible or even -inspired TLS API.

pyOpenSSL provides a TLS API today.  Cryptography does not.  It would be good to deprecate pyOpenSSL; I am eagerly anticipating that, but we don't have anything to deprecate it in favor *of*.  If Cryptography were distributed without OpenSSL, that would make pyOpenSSL (and by extension, Twisted and ndg-httpsclient, among other things) useless, and broken out of the box wherever OpenSSL were not available.

So, in order for Cryptography to drop its hard dependency on OpenSSL, there would need to be some course of action for pyOpenSSL to take.  One course of action would be "give up, Cryptography already provides something better".  One course of action would be "depend on `cryptohazmat.bindings.openssl ` instead of `cryptography`" (and give up later).  I am just saying that this should be decided one way or the other in order to resolve this ticket.

**Comment by schlenk** [comment]
Especially the X509&CRL stuff is now available in both pyOpenSSL and Cryptography, with slightly different APIs, which is a pity. So deprecating the X509 & CRL API parts of pyOpenSSL in favour of the (imho) better APIs in cryptography would be one step.

TLS API is another matter.

**Comment by dstufft** [comment]
I think the short term answer would be that ``pyOpenSSL`` would depend on ``cryptography-openssl`` or whatever specifically.

**Comment by glyph** [comment]
> I think the short term answer would be that pyOpenSSL would depend on cryptography-openssl or whatever specifically.

What problem is this supposed to solve exactly? Isn't the X509 stuff exposed in Cryptography non-OpenSSL-specific?  (Also isn't it more of a medium-term solution that cryptography-openssl or whatever doesn't actually exist yet?)

**Comment by dstufft** [comment]
As far as I know, pyOpenSSL *only* depends on our OpenSSL bindings, nothing in any other layer. The problem that would be solving is splitting the backends out into their own packages which is one of the steps towards making it possible to install cryptography without having OpenSSL around.

**Comment by glyph** [comment]
> As far as I know, pyOpenSSL only depends on our OpenSSL bindings, nothing in any other layer. The problem that would be solving is splitting the backends out into their own packages which is one of the steps towards making it possible to install cryptography without having OpenSSL around.

So you're saying that `cryptography` would have an optional dependency on `cryptography-openssl`, and then `pyOpenSSL` would depend exclusively on `cryptography-openssl` which would just export the bindings?

That seems reasonable…

**Comment by reaperhulk** [comment]
Our shift away from modular backends makes this not relevant for now. Since we still have interfaces this is achievable by a package implementing the interfaces separately. If and when that becomes a thing we might still want to split the interfaces into their own separate package, but for now I'm closing this.
