### ISSUE TITLE
Documentation of DSA signature references incorrect RFC

### ISSUE THREAD

**Issue by viraptor** [pyca/cryptography#2246]
Documentation of DSA signatures (https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dsa/#signing) references RFC 6979 which sounds strange. Same for the naming of de/encoding functions at https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils/#cryptography.hazmat.primitives.asymmetric.utils.decode_rfc6979_signature

But that RFC doesn't actually define the {r,s} encoding. The actual asn1 module can be found in RFC 3279 which defines both dsa-with-sha1 signature and Dss-Sig-Value which is the {r,s} sequence.

The references to RFC 6979 are actually unfortunate, because it defines deterministic DSA signatures, while cryptography.io exposes the randomised version using openssl's `DSA_sign`.

**Comment by reaperhulk** [comment]
Ugh, I'm not even sure why I thought 6979 defines the ASN.1 sequence for dss-sig-value. It, in fact, states that there's no standard:
```
How a signature is to be
       encoded is not covered by the DSA and ECDSA standards themselves;
       a common way is to use a DER-encoded ASN.1 structure (a SEQUENCE
       of two INTEGERs, for r and s, in that order).
```

Maybe we should alias the name to encode_sigvalue or something similar to that.
