### ISSUE TITLE
add a get_extension_by_class to Extensions

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2255]
We don't really need to require an OID and it would be friendlier to pass the class.

**Comment by queenp** [comment]
Hi, I expressed an interest in this earlier on IRC, but don't quite get what the issue entails. Happy to do legwork reading up, but is there anywhere else I could read up on the API design/milestone stuff going on or to figure out what's required?

**Comment by reaperhulk** [comment]
We have a method on the `Extensions` class called `get_extension_by_oid`. This issue is for adding a method called `get_extension_by_class` that takes an extension class (e.g. `BasicConstraints`) as an argument and returns the associated `Extension`.

**Comment by queenp** [comment]
Gottit, thanks.

**Comment by alex** [comment]
This is done!
