### ISSUE TITLE
pypy installs don't seem to pick up OpenSSL libs

### ISSUE THREAD

**Issue by dhermes** [pyca/cryptography#2275]
After the `>=1.0` upgrade, our PyPy builds on Travis started to fail:
https://travis-ci.org/google/oauth2client/jobs/75439836
https://travis-ci.org/google/oauth2client/jobs/75439618
https://travis-ci.org/google/oauth2client/jobs/75349545

```python
...
    from OpenSSL import crypto
  File "/home/travis/build/google/oauth2client/.tox/pypy/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/travis/build/google/oauth2client/.tox/pypy/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/home/travis/build/google/oauth2client/.tox/pypy/site-packages/OpenSSL/_util.py", line 3, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/travis/build/google/oauth2client/.tox/pypy/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 11, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: No module named cryptography.hazmat.bindings._openssl
```

ISTM this could be caused by the system headers being ignored / missed during install, but I haven't dove deeply into your `setup.py` or other parts of your install process.

**Comment by alex** [comment]
Cryptography 1.0 requires pypy 2.6 or newer; you appear to be using 2.5 or so. (Unfortunately that's teh version of pypy that travis ships :-()

**Comment by dhermes** [comment]
Ahhh! Thanks for the quick reply.

**Comment by alex** [comment]
Yeah. It's a shitty situation :-( I'm sorry about that. I'm going to ping
the travis-ci folks about getting a new pypy deployed, they have the
changes to their config, they just need to update their dev environment.

For now I think your best bet would be to pin cryptography to <1.0 on your
CI. (On a personal note, thanks for testing with PyPy!)

On Thu, Aug 13, 2015 at 10:43 AM, Danny Hermes <notifications@github.com>
wrote:

> Ahhh! Thanks for the quick reply.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2275#issuecomment-130710253>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dhermes** [comment]
@alex Sure thing! Is it worth trying to support pypy 2.5 or less or should we suggest to users that they upgrade? (FWIW I've never heard from anyone using `oauth2client` on `pypy`.)

**Comment by reaperhulk** [comment]
@dhermes The changes we made to switch to the out-of-line API mode supported in cffi 1.0+ are pretty substantial (#1986). We discussed trying to support both but decided we'd prefer to encourage users to upgrade (which we know isn't ideal, sorry!). The advantages of the new approach are just too big to ignore though.

**Comment by dhermes** [comment]
It seems like the right move. I had forgotten about the nightmare of pyca/pyopenssl#137 until you closed it.

Asking `pypy` users to upgrade doesn't seem to be a drastic thing, as they are already early adopter types.
