### ISSUE TITLE
Random number generation docs are misleading

### ISSUE THREAD

**Issue by zed** [pyca/cryptography#2278]
[The docs recommend against `random` module APIs and advocate `os.urandom()`](https://github.com/pyca/cryptography/blob/ae9ae087aeddb2157a6588a424ff5b14243f748c/docs/random-numbers.rst).

There is [`random.SystemRandom()`](https://docs.python.org/3/library/random.html#random.SystemRandom) that is built on top of `os.urandom()`:

```
>>> import random
>>> r = random.SystemRandom()
>>> r.getrandbits(160)
993486520646701389716655680137901746842047255567
>>> r.randint(2, 10)
4
>>> r.choice("abc")
'c'
>>> L = list(range(10))
>>> L
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> r.shuffle(L)
>>> L
[3, 7, 1, 8, 2, 4, 0, 9, 6, 5]
```

I see that `getrandbits(160)` already has been reinvented as `int.from_bytes(os.urandom(20), byteorder="big")`.

**Comment by reaperhulk** [comment]
While `random.SystemRandom().getrandbits()` is absolutely a valid call, after discussion in IRC and #2313 we've decided that we'd prefer not to recommend usage of a module that contains many non-cryptographically safe methods. We believe "always use os.urandom" is simpler and less likely to lead to mistakes.

**Comment by zed** [comment]
I don't know about you but I'm not sure that I would implement on the first try `.shuffle()` efficiently (without looking at its source first) or `.randint()` without a tiny-tiny bias in the result. It doesn't look "simpler or less likely to lead to mistakes."

I would understand if you said that these methods require an implementation with special properties like for example [`HMAC.hexdigest()` to limit timing attacks](https://docs.python.org/3/library/hmac.html#hmac.compare_digest).
