### ISSUE TITLE
Use utf-8 strings in generated certs

### ISSUE THREAD

**Issue by markokr** [pyca/cryptography#2291]
Currently when adding unicode string to cert it end up as t61string or bmpstring.
Those are really ancient formats that are annoying to support in new code.

With some digging I would following workaround:

```
from cryptography.hazmat.backends.openssl import backend
backend._lib.ASN1_STRING_set_default_mask_asc(b"utf8only")
```
As the comment says:

>  utf8only : only use UTF8Strings (RFC2459 recommendation for 2004)

Please make it default.  There are already bunch of root certs using this setting, so it's safe to enable for private certs too, at 2015...

**Comment by reaperhulk** [comment]
@markokr could you provide some code to reproduce? We should already be using MBSTRING_UTF8 types everywhere, but this is definitely a bug if we missed a spot. Changing the global default is also an option and is what we've done in PyOpenSSL but I'd like to fully understand what's going on here before making any changes.

**Comment by markokr** [comment]
MBSTRING_UTF8 simply says that *incoming* string is utf8.  But then OpenSSL goes on to decide what the outgoing string will be:  https://github.com/openssl/openssl/blob/master/crypto/asn1/a_mbstr.c#L77

Thats what the set-default does - to tell what the outgoing should be.

**Comment by reaperhulk** [comment]
@markokr understood, but can you provide a reproducer that demonstrates a case where it chooses T61 or BMP? I've been testing on 0.9.8zg and 1.0.2d and all our current unicode test cases create utf8string ASN.1 output, so I'd like to add a test case to confirm the improper behavior.

**Comment by markokr** [comment]
https://github.com/markokr/libusual/blob/master/test/ssl/mkcerts.py

remove the utf8only setting, then the complex1 cert will have L= as t61, and ST= as bmp.

Ubuntu 12.04, OpenSSL 1.0.1

**Comment by reaperhulk** [comment]
Okay I see the problem. Modern OpenSSLs (even the 0.9.8 series) actually set this mask by default while 12.04 does not.

So we'll go ahead and add it to our backend initialization (although since it's a global arguably binding might make sense). Thanks for the report @markokr!

**Comment by markokr** [comment]
Ok I see.  The change was committed Jun 1 2014, so it's not something that can be depended on for few years yet.
