### ISSUE TITLE
Request Signing Recipe Proposal

### ISSUE THREAD

**Issue by russjones** [pyca/cryptography#2317]
This is a proposal for a yet unnamed request signing recipe to be included in cryptography.io.

## What is request signing?

Plain HTTP communication between hosts is susceptible to a variety of security vulnerabilities. Some of the common vulnerabilities revolve around:

* Integrity: An active attacker can tamper with the content of a HTTP request without the recipients knowledge.
* Authenticity: The recipient of an HTTP request can not verify the identity of the sender.
* Confidentiality: A well positioned passive attacker can observe HTTP requests not intended for them.

If paired with Transport Layer Security (TLS), two of the three issues are mitigated (confidentiality and integrity). However, due to the slow adoption of TLS Mutual Authentication, authenticity is difficult to provide in certain situations like those that will be described in the following sections.

Request signing aims to target two of the three issues (integrity and authenticity). When paired with TLS, the third issue is mitigated as well (confidentiality).

## Uses of request signing

Request signing has several common use cases:

* Signing webhooks. Webhooks are a common callback pattern used in modern web applications. They are used by a wide variety of Software-as-a-Service (SaaS) providers like GitHub, Stripe, Dropbox, and Mailgun. Signing webhooks allows the recipient to verify the sender was indeed the assumed party.
* Signing API requests. Signing API requests allows the recipient web service to verify the senders identity and prevent replay attacks. A wide variety of vendors such as Amazon Web Services (AWS) and Flickr use request signing in their API.
* Micro-service communication. Request signing is used by micro-services as a lightweight method for micro-services to  verify the identity of each other.

## Common mistakes when implementing request signing

Request signing is not conceptually complex to understand which makes implementing it deceptively simple. Below is a list of common security vulnerabilities that arise when implementing request signing:

* Length extension attacks: This is typically caused by the use of a homegrown message authentication code (MAC) instead of a keyed-hash message authentication code (HMAC).
* MITM attacks: Caused by either not signing, or incorrectly signing, part of the request body.
* Replay attacks: Omitting or incorrectly checking the timestamp field.
* Collision attacks: Poor use of a delimiter that allows multiple messages to hash to the same value.
* Weak Key Generation: Weak sources of random are used when random material is generated.
* Timing attacks: Constant time comparison is not used.

## Why should request signing be included in cryptography.io as a recipe?

Request signing is a very common task that is frequently re-implemented by software developers. As noted in a previous section, because of it's deceptive simplicity, it is frequently implemented with a wide variety of security vulnerabilities. Also, even if the sender of the signed HTTP request takes the up-most care in developing a secure approach and implementation, the recipient may not implement checking the request correctly.

As such, it would be a significant boon for software developers to have a common algorithm and implementation that both the sender and recipient can use for request signing.

## Proposed Specification

If the proposal for the inclusion of the recipe is accepted, a specification as well as reference implementation in multiple languages are ready to go.

**Comment by reaperhulk** [comment]
@russjones Is there a repository containing the spec that we can look at?

**Comment by dreid** [comment]
While there does not appear to be any extant standards for Request signing there is [draft-cavage-http-signatures](https://tools.ietf.org/html/draft-cavage-http-signatures-04) which was most recently published in January and expired in July.

It seems to be being developed as part of the Web Payments working group and is based on Joyent's HTTP signature scheme, implemented as [node-http-signatures](https://github.com/joyent/node-http-signature)

I think this is a common problem and worthy of a recipe in cryptography, I look forward to reading the spec and discussing how it differs from the standards track draft above.

**Comment by reaperhulk** [comment]
@russjones any movement here?

**Comment by russjones** [comment]
@reaperhulk Sorry, been swamped with other work this last week. Once I apply a few final touches to the spec, I'll post it. Should be done this week.

**Comment by russjones** [comment]
@reaperhulk @dreid Specification is ready: https://github.com/russjones/request-signing/blob/master/spec.md

**Comment by russjones** [comment]
@reaperhulk @dreid @alex Any further comments on this issue?

**Comment by simo5** [comment]
That draft seem quite hand wavy and not very well defined.
Something directly based on Jose Web Signature would probably be more appropriate.

**Comment by russjones** [comment]
@simo5 What are the areas that you feel it's not well defined? That can be fixed.

**Comment by simo5** [comment]
Compare https://tools.ietf.org/html/draft-cavage-http-signatures-04 with https://tools.ietf.org/html/rfc7515 to see what I mean, the format is not specified in an unambiguos enough way afaict and there are no vectors, also it is not clear why the specification doesn't just use a JWS token, which would immediately give a standars approved signature scheme with algorithm negotiation and a host of existing implementations where the only thing to define is how to pack the request data to perform the signature.

**Comment by russjones** [comment]
@simo5 Fair point, I'll go back and make it less unambiguous and ping you again.

With respect why look at my request-signing proposal over JWS, I had few reasons for writing this proposal.  The main being that JWS has quite a number of features, modes, and toggles. This can be confusing for novice users, difficult for the implementer, and more dangerously provide a false sense of security to everyone.

Here are two examples: 

1.  What algorithm should be used? JWS supports a variety of them, including `None`. This has actually caused problems for a variety of JWS library implementations: [Critical vulnerabilities in JSON Web Token libraries](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/).

2. The `jti` claim used to mitigate replay attacks is optional. How does a novice user know that the optional `jti` claim should be used and how to generate it? If that's to be left to the developers writing libraries, only 1 of the 3 Python implementations on the JWS website actually supports `jti` checking. Only 7 out of the 31 implementations overall support `jti` checking.

Note, I am no expert on JWS or it's implementations, so feel free to correct me if I am wrong on any of this.

**Comment by simo5** [comment]
The issue in 1. just makes it clear how easy it is to make mistakes, but what we can do in cryptography is to give a recipe that properly uses JWS. It is not a reason though to invent your own, let's use what exists and has been standardized and will probably only improve going forward.

As for 2 what do you need is A) a clear definition of the required attribute for the 'request-header' application, B) test vectors that wil clearly cause failures if jti or any other field you deem required is missing, C) a reference implementation that makes it mandatory. Again none of this warrants creation of a new format for a prolem that has just been solved and standardized not even a few months ago and has all the flexibility you need.

As for implementations I wrote https://github.com/simo5/jwcrypto so  I may be biased toward JWS and friends, but I would certainly be happy to donate that code for integration i cryptography so that it could be the base of a recipe for http signed requests.

HTH.

**Comment by russjones** [comment]
@simo5 I took a brief look at jwcrypto, it comes in at about 2,176 lines of code while an implimentation of what I am proposing comes in at [300 lines of code in one file](https://github.com/mailgun/pylemma/blob/master/lemma/httpsign.py). In addition, take a look at the code, httpsign in lemma is significantly simpler to read, reason about, and understand. While lines of code in of itself is not a qualifier of good or bad code, it does point to a specification that is overly complex which does lead to security vulnerabilities.

As a side note, it seems that jwcrypto also does not support `jti` and after looking at the code for the single Python implementation that supposedly does, it does not either.

**Comment by simo5** [comment]
@russjones I do not think making line count comparisons between two projects with different scope makes much sense. Your implementation would be even smaller if it used an existing JWS implementation :-)

As for jti, it is defined in JWT not in JWS, and it is something the application needs to decide to provide. I can clearly amend the implementation to make it easier to do, but that's an orthogonal issue, all your specification has to define is that it is required for your use.

All I am saying is that there is a standard, it fits the purpose, it is normally a good idea to use it and specialize it as needed instead of inventing a new one, unless there are serious flaws or other reasons why the existing standard doesn't work.

**Comment by russjones** [comment]
@simo5 Sure, however I think everyone can agree that simpler software that meets the same security goals as something more complex is something to strive for.

Tell you what, let me go back and make some changes to the request signing specification I have proposed and let's take another look. I like the idea of putting it on firmer ground (good catch!) and should make the implementation more clear.

**Comment by simo5** [comment]
On 15/10/15 11:43, Russell Jones wrote:
> @simo5 Sure, however I think everyone can agree that simpler
> software that meets the same security goals as something more complex
> is  something to strive for.

As an abstract statement it can be agreed upon, but the devil is in the 
details.
Is something trivially simpler always better ? I do not think so, 
because you are still re-implementing a bunch of code, which means, 
probably reintroducing a lot of bugs that have been already fixed in the 
existing standard/code bases.

So it is not so simple.

> Tell you what, let me go back and make some changes to the request
 > signing specification I have proposed and let's take another look. I
 > like the idea of putting it on firmer ground (good catch!) and should
 > make the implementation more clear.

Ack

-- 
Simo Sorce * Red Hat, Inc * New York

**Comment by russjones** [comment]
@simo5 I've updated my request signing proposal to make it much more clear. Thanks for the push to get it done! :)

Is there anything else you think can be cleaned up?

**Comment by simo5** [comment]
The more I look at it the more I think you should simply use JWS and just define on top what claims are required (timestamp, etc..) and how headers are encoded, and call it a day.

Btw you do not need a nonce and a timestamp if you are using them only for replayu attacks, you can achieve the same result with a lot less effort by using a (prefixed) timestamp + counter/ (in case you sign multiple messages within the same clock tick).

It makes it much easier to efficiently handle checks as you do not need a huge cache, messages are sent in order anyway, so no need to handle out of order messages.
(The prefix is needed to allow the use of clusters/load balancers where each 'prefix' may have a potentially slightly different clock and definitely local counter)

**Comment by reaperhulk** [comment]
@dreid you've expressed interest in this in the past, would you mind taking a look? I'm curious if you agree with simo's opinion that the spec should be defined on top of JWS.

**Comment by lvh** [comment]
-1 for JWS; +1 for the generic idea of using existing standards. JWS suffers from kitchen sink problems, and makes poor recommendations within those sinks. What's a `Recommended+`? I don't know.

Looking over the comments, it seems like this specification tries to fill the same gap as the Cavage draft. Is there some reason the recipe should pick one over the other? Emulating an existing standard seems like mostly a good idea.

**Comment by reaperhulk** [comment]
@lvh if we were to be hyper opinionated about only picking a single decent option from JWS would that be acceptable?

**Comment by lvh** [comment]
That would be better, but you'd presumably want to select for the subset of commonly supported ciphersuites, and I don't think that intersects well with the particularly nice ones; that said, there's hardly anything wrong with the AES-256-CBC-HMAC-SHA256 one; IIRC that's _practically_ Fernet anyway...

**Comment by russjones** [comment]
To answer some of the questions raised:

1. @simo5: Sorry, I am not quite clear on the approach you are suggesting with using a timestamp + counter, can you clarify? Are you suggesting that the server send each request with a timestamp and counter value (the counter representing the nth request in that timestamp) and the client maintain synchronization to ensure the request has not been repeated? If so, are you not simply offloading parts of the work to the client and parts to the server? Using a SaaS provider as an example, wouldn't the server have to maintain a map of: `(timestamp, counter, host)` because it will be submitting requests to a wide variety of hosts. On the client end, to ensure synchronization, wouldn't the client have to accept a wider range of valid counters to ensure resynchronization in-case of message loss like in HOTP? I could be misunderstanding your proposal, if so, can you clarify?

2. @lvh: I like the Cavage draft in general, however if I recall correctly, it does not cover in much detail how the client should handle implementing verification of the incoming request in a safe manner. That leaves half of the puzzle open for interpretation, my goal with this proposal was to cover both sides and close that gap. Also, it's not clear when/if it will become a standard as it's still a draft.

**Comment by simo5** [comment]
On the server you can have a single counter, it increases monotonically per time tick, and it doesn't matter what clients get as long as the next thing they can ever get is a higher counter (within the same time tick).
For the client the counter is simply an easier way to deal with reaply checks than a nonce.
With nonces you have to keep a cache of all the nonces you've seen so far, and check against that list for each new message arriving, which can be quite a performance issue if you exchanger a lot of messages as the size of the array to check grows linearly with the number of messages.
If you use a counter all you need to do is to keep the last counter seen, and drop as "replayed" anything that has a lower timestamp/counter.
Basically you trade a table lookup with a simple "greater than" comparison. Makes the implementation simpler and easier to understand, also does not unnecesseraily deplete entropy on the server. (/dev/urandom is also a performance issue when used too much)
The only price is that you cannot allow out of order messages, but we are talking about a protocol running on TCP not UDP. If multithreaded clients are a concern you can always fall-back top treating counters like nonces and storing each of them, and do a loockup, you never lose that option.

**Comment by russjones** [comment]
Hi @simo5,

I like the idea of counters, you're right they are really simple to work with and that is a very nice property, however it seems that they have a couple of problems in this situation:

1. A counter based approach does not work well in a distributed environment. For example, take a SaaS service like Mailgun, we may have 10-20 different servers that sign and send webhooks. That means you have to synchronize the state of the counter across 10-20 servers to ensure it is always increasing. Distributed counter synchronization is both non-trivial and probably out of the scope of this proposal.

2. HTTP requests can arrive out of order. TCP (transport layer) only guarantees in-order delivery of un-ordered IP packets (network layer). Application layer traffic like HTTP can arrive out of order unless you have logic at the application layer that guarantees in-order delivery like HTTP pipelining.

3. Use of `/dev/urandom` does not deplete entropy on the server. The only issue with low entropy seems to occur at startup. However, in the virtualized world we live in, this is not a problem as the virtual machine will have a good source of entropy even at boot time thanks to things like VirtIORNG. Here is a good article on `/dev/urandom` that addresses your concerns: http://www.2uo.de/myths-about-urandom/


However, I do think there is a valid concern here. If you use what I have proposed without TLS, you can potentially see replay attacks because the nonce cache is local and not distributed. This needs to be addressed and I'll update my specification with a section on security considerations to reflect this.

**Comment by simo5** [comment]
Hi @russjones,
I had some of your questions coming, so here's my take.

1. it si ture that you do not want to sync multiple servers, that is ok, one additional datum can be a service number/name as parte of the "nonce" so that you can still use a counter, but you use one per "identifier". This also avoid issues with (exceedingly rare, granted) potential collisions among different servers when random nonces are used.

2. HTTP1.1 and HTTP/2 are pipelined, however do you really expect to receive out of order replies from a server ? The fact you use a counter somehow does synchronize a bit on the server side already as you need to deal with a single counter sharing state.

3. my problem with urandom has nothing to do with entropy, it is about performance. Each call to /dev/urandom is a full system call, which means context switch/rescheduling, all that.

This is the result of a simple test on my machine:
> $ time dd if=/dev/zero of=/dev/null bs=512 count=1000000
> 1000000+0 records in
> 1000000+0 records out
> 512000000 bytes (512 MB) copied, 0.585331 s, 875 MB/s

> real	0m0.590s
> user	0m0.085s
> sys	0m0.503s

> $ time dd if=/dev/urandom of=/dev/null bs=512 count=1000000
> 1000000+0 records in
> 1000000+0 records out
> 512000000 bytes (512 MB) copied, 71.6925 s, 7.1 MB/s

> real	1m11.697s
> user	0m0.133s
> sys	1m11.582s

**Comment by russjones** [comment]
I've updated the specification with a section on [security considerations](https://github.com/russjones/request-signing/blob/master/spec.md#security-considerations).

@simo5: It looks like your computer can generate 7.1 megabytes of random material per second based off the output of `dd`. Each nonce is 16 bytes, which means your computer can sign 443,750 requests per second. Can you provide the specific use case that you are concerned with where signing over 400,000 HTTP requests per second is the bottleneck for your application?

@lvh, @reaperhulk, @dreid: Can you take another look, any comments, objections, or improvements that can be made?

**Comment by simo5** [comment]
@russjones if all my computer ever did was generating random I think 7.1M/s would probably be ok, but that's not what my computer does all the time, what matters is the difference between the first and second test, which is 2 orders of magnitude. It means reading /dev/urandom is really slow even comparing to another device (ie this does not account the context switching).
If you do not care about the performance profile of a server applicatrion that is fine though.

**Comment by reaperhulk** [comment]
I'm adding this to the thirteenth milestone so we can finish discussion and make a decision on whether or not to move forward in that cycle.

**Comment by reaperhulk** [comment]
We discussed this a bit in person and there was an agreement that this (if it is going to move forward) needs to be pursued more on the IETF side. Closing for now.
