### ISSUE TITLE
Enable "Protected Branches" GitHub feature.

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#2321]
So GitHub just rolled out a few [feature](https://github.com/blog/2051-protected-branches-and-required-status-checks) that disables force pushes on certain branches and requires that status checks passes before the merge button works.

We should enable it on this (and all PyCA) projects.

**Comment by reaperhulk** [comment]
Yeah we talked about it on IRC. We'll be enabling it when it's available (it's not yet and the blog post actually says "over the next few weeks").

**Comment by reaperhulk** [comment]
Spoke too soon. Went and checked and it was there. They're on now.
