### ISSUE TITLE
Instructions for Static Wheels on Linux

### ISSUE THREAD

**Issue by Lukasa** [pyca/cryptography#2338]
It'd be great if we could deploy static wheels on Linux to allow python users to get the most up-to-date OpenSSL without affecting the rest of their distribution. However, as @reaperhulk and I found, this isn't totally trivial to do.

Obviously we can't generally distribute static wheels, Linux is painful like that, but we can definitely publish instructions for how to build and use them yourself. If we can work out how to do it, I'm happy to write those up.

**Comment by Natim** [comment]
> Obviously we can't generally distribute static wheels

Why one for x86 and one for x86_64  wouldn't work?

**Comment by reaperhulk** [comment]
@Lukasa good news!

Here's how to do this:

```bash
curl -O https://openssl.org/source/openssl-1.0.2d.tar.gz
tar zxvf openssl-1.0.2d.tar.gz
cd openssl-1.0.2d
./config no-shared -fPIC --prefix=/home/<myuser>/openssl
make && make install
cd ~
virtualenv tempvenv
source tempvenv/bin/activate
CFLAGS="-I/home/<myuser>/openssl/include" LDFLAGS="-L/home/<myuser>/openssl/lib" pip wheel cryptography
pip install wheelhouse/cryptography*
ldd tempvenv/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so 
	linux-vdso.so.1 =>  (0x00007fff14467000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2d69a86000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d696c1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2d6a21b000)
python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"
OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by Lukasa** [comment]
@reaperhulk Awesome! Let me see if I can add some useful other flags to that to disable other stuff that should *definitely* be disabled (SSLv2, for example), and then contribute something to the docs.

**Comment by Lukasa** [comment]
Ok, this looks like a suitable Bash script that works even in super-old systems (cough cough Ubuntu 12.04). It requires a compiler, libffi, and the Python headers.

```bash
set -e

OPENSSL_VERSION="1.0.2d"
CWD=$(pwd)

virtualenv env
. env/bin/activate
pip install -U setuptools
pip install -U wheel pip
curl -O https://openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
tar zxvf openssl-${OPENSSL_VERSION}.tar.gz
cd openssl-${OPENSSL_VERSION}
./config no-shared no-ssl2 -fPIC --prefix=${CWD}/openssl
make && make install
cd ..
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel cryptography
```

This doesn't use a validating virtualenv, but that's ok, I think people should be validating this separately. That gives a `.whl` for cryptography that can be dumped into virtualenvs elsewhere. It also gives a cffi `.whl` that I think obviates the need for a C compiler on the target box.

One note for older systems: the new install environment will need the `wheel` package and a newish `pip` to make this work.

**Comment by powellchristoph** [comment]
Very nice! Thank you for providing this.

**Comment by geradcoles** [comment]
@Lukasa  - I suggest adding `--no-cache-dir` when building the wheel to avoid the problem I encountered [here](https://github.com/certifi/python-certifi/issues/26).

**Comment by Lukasa** [comment]
Good suggestion, I'll open another pull request.
