### ISSUE TITLE
Elliptic curve serialization/deserialization from point value byte strings

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#2346]
For ECDH key exchange and ECDSA signing/verification in AsyncSSH, I need the ability to serialize and deserialize EC point value encoded as byte strings from/to EC public keys.

The encoding of the point values into octet strings is described in http://www.secg.org/sec1-v2.pdf in section 2.3.3. This encoding is used by PKCS#1/PKCS#8 DER and PEM encoding of EC keys, as well as by SSH (with its own encoding of strings and integers replacing DER/PEM), so the existing DER/PEM serialization may already include this support. I'd just like to see it broken out so it can be used without constructing a full EC DER/PEM public key.

The serialization depends on the curve, as the number of bytes used to encode the x & y values of the point vary based on the curve's key size. That information is already available in EllipticCurvePublicNumbers, though, via curve.key_size. It just needs to be rounded up to the next even number of bytes. For now, I've coded this myself and it's just a few lines, but it would be nice to have this built into PyCA to avoid callers having to directly construct EllipticCurvePublicNumbers from raw x and y values. Here's an example of the encode and decode functions given the key length of the curve expressed in bytes:

```python
def decode_ec_point(keylen, data):
    """Decode an octet string into an elliptic curve point"""

    if data == b'\x00':
        return None, None
    elif data.startswith(b'\x04'):
        if len(data) == 2*keylen + 1:
            return (int.from_bytes(data[1:keylen+1], 'big'),
                    int.from_bytes(data[keylen+1:], 'big'))
        else:
            raise ValueError('Invalid elliptic curve point data length')
    else:
        raise ValueError('Unsupported elliptic curve point type')

def encode_ec_point(keylen, x, y):
    """Encode an elliptic curve point as an octet string"""

    if x is None:
        return b'\x00'
    else:
        return b'\x04' + x.to_bytes(keylen, 'big') + y.to_bytes(keylen, 'big')
```

The "None, None" return value here is how the "infinity" EC point value is serialized. There's also an encoding which does "point compression" to represent the y value as a single bit that's not supported here yet as I haven't needed it, but it is described in the link above. Since it involves some hairy math (prime modulo square root), we'd probably want to see if it is something supported by a backend if we wanted to add that.

**Comment by wbond** [comment]
Also note that EC point compression is covered by https://www.google.com/patents/US6252960 until 2018. I ended up deciding not to support it in my library because of this issue.

**Comment by alex** [comment]
As far as I can tell, basically nothing supports compressed points.

On Wed, Sep 16, 2015 at 10:54 AM, Will Bond <notifications@github.com>
wrote:

> Also note that EC point compression is covered by
> https://www.google.com/patents/US6252960 until 2018. I ended up deciding
> not to support it in my library because of this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2346#issuecomment-140766192>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by ronf** [comment]
Yeah - I thought I remembered seeing a patent issue with point compression when I did the original investigation a while ago, but I didn't have a chance to confirm that before posting the note above, so I left out that detail. Thanks for the clarification.

Given that the patent only covers point compression, supporting the 0x00 and 0x04 forms of serialization should not infringe it.

**Comment by wbond** [comment]
@ronf Yes, sorry if my comment was unclear. The only thing that is covered by the patent is the `\x02` and `\x03` prefixed compressed forms. Uncompressed points using the `\x04` prefix are not patented, to my knowledge.

**Comment by alex** [comment]
Completed in #2447.
