### ISSUE TITLE
Document stdlib Random token/password generator

### ISSUE THREAD

**Issue by ncoghlan** [pyca/cryptography#2347]
I'm not sure this is in scope for the cryptography package, but while the `int.from_bytes(os.random(num_bytes))` recipe is fairly clear for securely generating a random integer, it's not particularly how to safely generate a secure text token based on os.urandom data.

Pyramid apparently uses `binascii.hexlify(os.urandom(n))` for secure token generation, while Django uses `random = random.SystemRandom(); ''.join(random.choice(alphabet) for _ in range(n))`

This is a common source of recommendations to use the standard library's random module, and I'm not aware of any standalone third party packages that cover it (it's not part of cryptography, passlib, or itsdangerous, which where the ones I checked)

**Comment by dstufft** [comment]
I normally use the same thing that Pyramid uses personally, though if someone knows how you generated it you need a longer password than you would for the Django one because it uses an alphabet of only 16 letters whereas Django's is at least 52 IIRC.

**Comment by mrjefftang** [comment]
This would be useful to prevent people from walking into the situation identified @ https://inventropy.us/blog/a-tale-of-lost-entropy

**Comment by reaperhulk** [comment]
I'm not necessarily opposed to a password recipe. Are any password generators (like the ones in 1password or lastpass) well-specified? It'd be nice to be able to tweak the parameters (within reason) to match various restrictions. There are also passphrases (e.g. diceware) which might muddy the waters a bit.

**Comment by ncoghlan** [comment]
The main 4 things folks seem to generate are:

* a given number of bits of entropy as raw bytes (`os.urandom(bits//8)`)
* integers with a given number of bits of entropy (`int.from_bytes(os.urandom(bits//8))`)
* hex digits with a given number of bits of entropy (`binascii.hexlify(os.urandom(bits//8))`)
* text with a given number of characters from a given alphabet

Given cryptography's scope, I think adding the "hex digits" pattern to the randomization page in the documentation makes sense, but the last one doesn't.

An alternative for that might be to suggest `base64.urlsafe_b64encode(os.urandom(bits//8))` to produce a URL friendly token that's shorter than a hex digit based one.

**Comment by Ayrx** [comment]
Are we talking about adding documentation or adding an actual recipe?

**Comment by ncoghlan** [comment]
I was talking about adding additional recipes to https://cryptography.io/en/latest/random-numbers/.

That already covers bytes and integers, so the additional examples would be:

    >>> hex_token = binascii.hexlify(os.urandom(20))
    >>> text_token = base64.urlsafe_b64encode(os.urandom(20))

**Comment by Ivoz** [comment]
UUID4's aren't specifically cryptographic, but they designed to specifically be as unique as possible. Which is what most people want text tokens for.

**Comment by dstufft** [comment]
I don't think we should recommend something that silently switches to use ``random`` instead of failing when it doesn't have ``os.urandom`` available.

**Comment by alex** [comment]
Going to declare this is now a documentation issue to point people to the new stdlib `secrets` module.
