### ISSUE TITLE
Python 3.6 incompatibility because of getargspec

### ISSUE THREAD

**Issue by xZise** [pyca/cryptography#2382]
Hi, on testing pywikibot on 3.6 I noticed that your package uses `inspect.getargspec` which has been removed in 3.6 after it has been deprecated in 3.5 (although the documentation mentions it has been deprecated since Python 3).

I know that Python 3.6 hasn't been released yet but I just wanted to let you know so you have enough time to prevent issues before it is released.

Here the Travis build: https://travis-ci.org/xZise/pywikibot-core/jobs/82446934

**Comment by reaperhulk** [comment]
Thanks for the report! We use it here (https://github.com/pyca/cryptography/blob/master/src/cryptography/utils.py#L70) to check interface implementations, so we'll need to determine what the new approach needs to be.

**Comment by alex** [comment]
I think we just need to call `getfullargspec` when it's available. I've got
a patch I'll send up when I'm back on my other machine.

On Tue, Sep 29, 2015 at 8:59 AM, Paul Kehrer <notifications@github.com>
wrote:

> Thanks for the report! We use it here (
> https://github.com/pyca/cryptography/blob/master/src/cryptography/utils.py#L70)
> to check interface implementations, so we'll need to determine what the new
> approach needs to be.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2382#issuecomment-144050782>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by Ayrx** [comment]
@alex `getfullargspec()` is deprecated as well. The recommendation in the docs is to use `signature()` instead.

**Comment by alex** [comment]
I love chains of deprecations!

On Tue, Sep 29, 2015 at 9:35 AM, Terry Chia <notifications@github.com>
wrote:

> @alex <https://github.com/alex> getfullargspec() is deprecated as well.
> The recommendation in the docs is to use signature() instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2382#issuecomment-144060207>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by Ayrx** [comment]
Complicating this issue is that Python 2.7 doesn't have `signature()` (or `getfullargspec()` even).

**Comment by xZise** [comment]
Now on pywikibot we have solved that problem by replicating the result on Python 3.5+ by using `signature()` wikimedia/pywikibot-core@baf31f1b. And for the other way around I asked the devs of `future` PythonCharmers/python-future#157, although nothing has happened there and I'm not sure what you policies regarding third party packages is (we use `future` a lot to support Python 2.6).
