### ISSUE TITLE
Any interest in adding support for public key fingerprints?

### ISSUE THREAD

**Issue by bjmc** [pyca/cryptography#2394]
It would be convenient for me if I could use cryptography to easily get the key fingerprint (as [described in RFC 4716](https://tools.ietf.org/html/rfc4716#section-4)) for SSH public keys. I'm imagining something simple along the lines of: 

    key = serialization.load_ssh_public_key(fileobj.read(), default_backend())
    return key.fingerprint()

And maybe it could take a parameter like `key.fingerprint(hashes.SHA1)` to allow for different hash algorithms (I believe Amazon EC2 uses sha1 fingerprints while OpenSSH uses md5).

Would this be a feature appropriate to include in cryptography?

I'm happy to write it up and submit a pull request, but I wanted to get feedback first to see if others were interested.

**Comment by reaperhulk** [comment]
Fingerprints would be useful, but our public key objects are not solely for SSH so we'll need to name it something like `rfc4716_fingerprint` and document that it is a hash of public key elements as defined in rfc4253. (And whatever RFC might define it for NIST EC keys)

I am :+1: on it taking a hash instance as an argument.

**Comment by bjmc** [comment]
Thanks for the quick reply.

I agree we don't want this to be SSH-exclusive. I know OpenSSL [also has a 'fingerprint' feature](https://stackoverflow.com/questions/4803799/how-to-calculate-x-509-certificates-sha-1-fingerprint), which uses a different algorithm.

Would you prefer separate methods, like `rfc4716_fingerprint` and `openssl_fingerprint` (or whatever better name if there's an RFC for it) or would it be better to have one `fingerprint` method that takes format arguments, similar to how the `public_bytes` method works?

**Comment by reaperhulk** [comment]
I **think** I prefer `fingerprint` taking an enum as an arg, but I'd like to hear from @alex or @dstufft on this as well.

**Comment by alex** [comment]
I don't feel strongly.

**Comment by reaperhulk** [comment]
Okay, let's go ahead with `fingerprint` and an enum for the fingerprint type then if you're still interested in implementing this @bjmc

**Comment by bjmc** [comment]
Thanks for the input, everyone. I'll see if I have some time later this week to get this implemented.
