### ISSUE TITLE
Random number generation docs and os.urandom vs SystemRandom

### ISSUE THREAD

**Issue by eukaryote** [pyca/cryptography#2410]
The "random number generation" doc (https://cryptography.io/en/latest/random-numbers/) cautions against using the "standard random module APIs" and recommends only using `os.urandom` directly, with no mention of `random.SystemRandom`. Is this intentional, or just an oversight?

Doesn't using the random API via `random.SystemRandom` give the benefits of using `os.urandom` and the convenience of the random API?

If I'm overlooking something and there is a reason to use `os.urandom` directly rather than through `random.SystemRandom`, it would be helpful to include the reasoning in the doc.

**Comment by alex** [comment]
Yes, `random.SystemRandom` is fine. We suggest avoiding the `random` module in order to keep the advice simple, and easily auditable.
