### ISSUE TITLE
Documentation: Encoding.DER new in 0.9, not 0.8

### ISSUE THREAD

**Issue by kuba** [pyca/cryptography#2423]
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/?highlight=encoding.der#cryptography.hazmat.primitives.serialization.Encoding.DER confusingly suggests that `0.8` supports it. According to the changelog and my testing, it only work with `0.9+`.

This is a follow-up from https://github.com/letsencrypt/letsencrypt/issues/1012.

**Comment by reaperhulk** [comment]
Whoops! Let's get that fixed.

**Comment by alex** [comment]
I suspect the confusion is that `DER` itself was added in `0.8`, but nothing worked with it until `0.9`?

**Comment by reaperhulk** [comment]
Yep, but that's a distinction without meaning for our consumers. I'm going to go ahead and add 0.9 to the DER attribute

**Comment by alex** [comment]
:+1:

On Sat, Oct 17, 2015 at 10:24 AM, Paul Kehrer <notifications@github.com>
wrote:

> Yep, but that's a distinction without meaning for our consumers. I'm going
> to go ahead and add 0.9 to the DER attribute
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2423#issuecomment-148918829>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
