### ISSUE TITLE
RFC: HashContext.digest() method and hashlib compatibility

### ISSUE THREAD

**Issue by moreati** [pyca/cryptography#2424]
The following is an aborted proposal for making `Hash` objects able to standin for `hashlib` objects from the stdlib. The more I looked at it the less I liked it. I'm creating this issue just so there's a point of reference for anyone interested, please feel free to close it.

`hashes.Hash` objects implement the HashContext interface, this interface couples returning the digest with disposal of the hash state.

```python
>>> h = hashes.Hash(hashes.SHA256(), backend=default_backend())
>>> h.update(b"abc123")
>>> h.finalize()
'l\xa1=R\xcap\xc8\x83\xe0\xf0\...x80\x90'
>>> h.update(b"foo")
Traceback (most recent call last):
cryptography.exceptions.AlreadyFinalized: Context was already finalized.
```

Adding a `.update()` that returned the same hash, but didn't dispose of the state would bring Hash instances closer to the interface defined by `hashlib` objects. The following table shows the current state of affairs.

| `hashes.Hash` instance | `hashlib.new` instance |
|---------------------------------|--------------------------------|
| h.algorithm.name | h.name |
| h.algorithm.digest_size | h.digest_size |
| h.algorithm.block_size | h.block_size |
| h.update() | h.update() |
| h.copy() | h.copy() |
| -- | h.digest() |
| -- | h.hexdigest() |
| h.finalize() | -- |

**Comment by reaperhulk** [comment]
Yeah when we originally built our hashing interface we considered making it hashlib compatible but ultimately decided it was okay not to. We may revisit (at least for something like `hexdigest`) in the future, but not yet.

Thanks for writing it down though!
