### ISSUE TITLE
Public Key Documentation Issue?

### ISSUE THREAD

**Issue by theonewolf** [pyca/cryptography#2426]
I was wondering if this documentation was wrong: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.CertificateBuilder

Specifically, the snippet of code:

```python
>>> private_key = rsa.generate_private_key(
...     public_exponent=65537,
...     key_size=2048,
...     backend=default_backend()
... )
>>> public_key = rsa.generate_private_key(
...     public_exponent=65537,
...     key_size=2048,
...     backend=default_backend()
... ).public_key()
```

Which to me feels like you are creating a public key which is divorced from the private key in the first line?

Should this instead be:

```python
>>> private_key = rsa.generate_private_key(
...     public_exponent=65537,
...     key_size=2048,
...     backend=default_backend()
... )
>>> public_key = private_key.public_key()
```

Or am I completely wrong about how this interface is supposed to be used?

**Comment by alex** [comment]
What this code is trying to demonstrate is create a certificate, so you are a CA with a private key and a certificate, and then you have only the public key of the certificate you are trying to sign. I agree that it's presented very confusingly though.

**Comment by theonewolf** [comment]
Ah, I was assuming the first example you'd want to show would be a bootstrapped, self-signed CA creation (although I realize later on the ca bit is set to False).

I'm trying to create a self-signed root CA.  Does an example exist for that?

**Comment by reaperhulk** [comment]
No, but we should add one to the tutorial https://cryptography.io/en/latest/x509/tutorial/

To self-sign all you need to do is drop the public_key generation line in the example and change

```builder = builder.public_key(public_key)``` into ```>>> builder = builder.public_key(private_key.public_key())```.

Then set the extensions as you need :)

**Comment by theonewolf** [comment]
Yep, it was super easy.  Just did that.  Thanks for the help / acknowledgement :-)

Also I think it would be nice in the example to show saving of the certificate and private key to disk.  I figured it out, and it was fairly simple, but it would help.

So adding this to the example (could contain typos):

```python
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, NoEncryption

with open('self-ca.crt', 'wb') as cafile:
    cafile.write(certificate.public_bytes(Encoding.PEM))

with open('self-ca.key', 'wb') as keyfile:
    keyfile.write(private_key.private_bytes(Encoding.PEM, PrivateFormat.TraditionalOpenSSL, NoEncryption()))
```

**Comment by alex** [comment]
This was improved with #2512.
