### ISSUE TITLE
Copy/paste error in load_elliptic_curve_private_numbers

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#2428]
In hazmat/backends/interfaces.py, the following function is defined:

```python
    @abc.abstractmethod
    def load_elliptic_curve_private_numbers(self, numbers):
        """
        Return an EllipticCurvePublicKey provider using the given numbers.
        """
```

The comment here should say that it returns an EllipticCurvePrivateKey, not public key. This appears to be a copy/paste error from the function above it.

**Comment by alex** [comment]
Nice catch, thanks!
