### ISSUE TITLE
Documentation of DSA keys loading is lacking

### ISSUE THREAD

**Issue by viraptor** [pyca/cryptography#2432]
The documentation defines a few ways of getting the DSA key loaded, but it's not very clear about what format is expected. Specifically "load_der_public_key()" is referenced as one of the options, but there's no mention of whether it expects spki-type "algorithm oid + parameters + x", or something completely different.

**Comment by reaperhulk** [comment]
@viraptor It supports the DER form of PKCS8 as well as the OpenSSL-style bare ASN.1 sequence [version, p, q, g, public, private] (version is always zero).

**Comment by reaperhulk** [comment]
Oh, sorry, `load_der_public_key` expects a subjectPublicKeyInfo structure as well.

**Comment by reaperhulk** [comment]
We'd be happy to merge any PR that makes that more clear :smile:
