### ISSUE TITLE
Need elliptic curve private value as a byte string

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#2451]
Similar to wanting to get the EllipticCurvePublicNumbers x & y values to be output as an EC point byte string, I have a need in AsyncSSH to get the EllipticCurvePrivateNumbers private value as a byte string. In this case, the encoding is simple as it is just "to_bytes" call on the integer value, but to encode it properly requires knowing the key size of the curve in bytes, and it's ugly to have to pull that out of the curve to do the encoding externally.

Would it be possible to add something like a "private_bytes()" method on EllipticCurvePrivateNumbers which did this? The implementation would be something like:

``` python
            keylen = (self.curve.key_size + 7) // 8
            return self.private_value.to_bytes(keylen, 'big')
```

For completeness, it would also be useful to have a "from_private_bytes()" class method which constructed an EllipticCurvePrivateNumbers object from the bytes and an EllipticCurvePublicNumbers object, rather than taking the private value as an integer. This could also sanity check that the byte string is the right length before converting it.

**Comment by reaperhulk** [comment]
I assume this is something SSH forces you to do? Is this need present in other protocols that you're aware of?

**Comment by ronf** [comment]
Actually, SSH needs the integer version of this value, which is already available as a property in EllipticCurvePrivateNumbers. The need for the string version of it comes up when doing PKCS#1 and PKCS#8 encoding/decoding of an EC certificate to/from DER or PEM format. However, generating this string value requires knowing the curve's key size in bytes and that feels to me like it is something that should be kept within the key class rather than in the PKCS encode/decode functions.

**Comment by reaperhulk** [comment]
This and #3487 may be related.

**Comment by reaperhulk** [comment]
Since we have byte serialization for curve25519 and curve448-based things and NIST keys don't have strongly defined serialization for this I think we're going to close this for now. If we want to implement a specific one (e.g. if SECG has one) then we should go ahead and open a new issue and get it taken care of. (This decision brought to you by quarantine-induced triage)
