### ISSUE TITLE
Need a way to look up an EC curve by its parameters

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#2452]
When decoding EC PKCS#8 certificates, there are a couple of different representations. One form uses a named curve OID to specify the curve to use, and it's straightforward to have a lookup table that maps OIDs to cryptography curve objects. However, the other form passes in the EC parameters (p, a, b, the generator point byte string, and the order). It would be nice if there was some way to ask cryptography to match these curve parameters against its supported curves. Unfortunately, none of the curve parameters are exposed at all in the current EllipticCurve implementation (outside of the backends, at least). Is there some way to ask the backends to do this matching, or to make the curve parameters available so the matching could be done elsewhere?

**Comment by reaperhulk** [comment]
All these values are fixed, so it seems reasonable to add them as properties on the curve class? Would that work for you @ronf?

**Comment by ronf** [comment]
Yes, that sounds like it would work nicely.

**Comment by reaperhulk** [comment]
If you'd like to put in a PR adding it to the interface + classes we can review it and get it landed. The only question I really have is what types all the values should have.

**Comment by ronf** [comment]
I started to look into this more closely tonight.

It looks like one complication is that PyCA defines curves based on both prime and binary finite fields. The parameters for each of the two are slightly different, though. They both involve setting parameters a and b for the curve and a generator point and have an associated order, but the definition of the field involves a prime value p in one case and an exponent value m and polynomial function f (which can be encoded as an integer) in the other.

How should we represent this in the curve properties? Should all the curves define p, m, and f but set the values which are not applicable to None, or should we do something like having a boolean 'is_prime' property which is defined for all of the curves and only define p for prime curves and m & f for binary curves?

Also, for the generator point, I was thinking of providing it as x & y integer values, but it might be nice to also provide a property which can return the point encoded as a byte string for calling code that prefers that. Unfortunately, the encode function is currently defined on EllipticCurvePublicNumbers rather than EllipticCurve itself. Should I move that up to EllipticCurve and have the EllipticCurvePublicNumbers methods just call the method on the curve?

**Comment by ronf** [comment]
After sleeping on it, I think something like the following is a better way to deal with encoding the field type:

```python
class EllipticCurveField(object):
    """Field type of an EllipticCurve"""


class EllipticCurvePrimeField(EllipticCurveField):
    def __init__(self, p):
        self._p = p

    p = utils.read_only_property("_p")

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.p == other.p

    def __ne__(self, other):
        return not self == other

    def __repr(self):
        return "<EllipticCurvePrimeField(p={0.p})>".format(self)


class EllipticCurveBinaryField(EllipticCurveField):
    def __init__(self, m, f):
        self._m = m
        self._f = f

    m = utils.read_only_property("_m")
    f = utils.read_only_property("_f")

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.m == other.m and self.f == other.f

    def __ne__(self, other):
        return not self == other

    def __repr(self):
        return "<EllipticCurveBinaryField(m={0.m}, f={0.f})>".format(self)
```

Each EllipticCurve would have a "field" property which would be of type EllipticCurveField that could be compared for equality along with the other parameters common to all field types.

**Comment by reaperhulk** [comment]
I was going to suggest a similar approach. :+1: from me.

**Comment by ronf** [comment]
I just submitted a pull request for this in #2476.

**Comment by alex** [comment]
After a year plus of sitting on this, I'm going to close it. Protocols should already restrict themselves to less than "supporting every curve possible", which means you need logic for that -- further, with the move to curves with different structures like x25519, the API for this becomes further muddled. We'd rather people write the logic for their specific protocol than trying to express all of this.

**Comment by ronf** [comment]
I don't expect this to change your mind, but to be clear the whole point of this change was to allow protocols to only support specific curves. Given the way PKCS#8 is defined, the encoding with "explicit parameters" means we need to be able to look up a curve from a list or supported curves by passing in the parameters, as there are only parameter values and not a curve name encoded in the PKCS#8 encoding in that case.
