### ISSUE TITLE
Binary Wheels for Python.org Python

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2465]
Currently we ship OS X wheels marked as compatible with the 10.10 SDK for Python 2.6, 2.7, 3.3, 3.4, 3.5, and pypy. This covers users of tools like pyenv and system Python on 10.10 (Yosemite) and 10.11 (El Capitan). However, python.org's Python is built against the 10.6 SDK and therefore users of it will not download our wheels. This occurs even if the user is on 10.10 or 10.11.

One potential solution to this would be to simply mark the wheel as compatible with 10.6+. This would resolve the issue, but would create a new problem where users on 10.6 and 10.7 would see errors in the commoncrypto backend on import. Not really an option.

Rather than that, my proposed solution is to use our 10.7 builder (currently available in the jenkins infrastructure) to generate a wheel (which will not have the commoncrypto entry point or shared object), rename it to mark it as 10.6 compatible, and then upload it. It is my tentative understanding that this will produce a binary that will work for all users, albeit without commoncrypto support even on 10.8+ where it would normally be available. Resolving that issue will require the splitting of our backends, an ongoing and unpleasant issue I have no desire to tackle today. :sparkles: 

## Motivation

There is an increasing prevalence of users on OS X El Capitan having trouble installing cryptography. This is caused by using a python installation where we do not have a wheel available coupled with the removal of the OpenSSL development headers by Apple. Combined with conflicts in the linker/include search path (see: https://langui.sh/2015/07/24/osx-clang-include-lib-search-paths/) users are extremely unlikely to be able to successfully install cryptography from source without following the homebrew/macports install instructions (https://cryptography.io/en/latest/installation/#building-cryptography-on-os-x) or possessing significant knowledge around C build arcana. Additionally, the install instructions claim that users on Yosemite and above should be able to just type `pip install cryptography`, an aspirational statement that is broken in the presence of python.org installation.

## Outstanding Questions

These are probably mostly for @dstufft :)

* Is it safe to rename a wheel? I see there is some data in the `WHEEL` file inside the wheel itself that notes what its original compatibility target was.
* What are the specificity rules for wheels now? If a user is on 10.10 or 10.11 and attempts to install cryptography when both 10.6 and 10.10 wheels are uploaded, which one will be downloaded? I vaguely recall this may have changed recently?
* What python.org pythons do we want to do this for (maybe just 2.7 first, 3.5 later)? Are they all built against the 10.6 SDK?

**Comment by dstufft** [comment]
* It should be safe to rename it, you might want to adjust the data inside it too. However I think that if you build it using Python.org Pythons it'll automatically be compiled against the 10.6 SDK.
* On all currently released versions of pip it will prefer an older SDK over a newer SDK. That's been reversed in the develop branch of pip but hasn't been released yet.
* Pretty sure they are all built against 10.6. Not sre what versions we want to do it for though. We probably have to deal both with new installs (2.7/3.5) and existing installs (<3.5, 2.6?). Not sure what the numbers shake out to look like.

**Comment by reaperhulk** [comment]
I'll have to test a build against python.org python. Do you have a rough ETA for the next release of pip? The current behavior isn't ideal but won't kill us -- just means a percentage of mac users will get a binary wheel without commoncrypto support.

**Comment by reaperhulk** [comment]
I can confirm building using python.org pythons (2.7, 3.3, 3.4, 3.5) all result in a 10.6sdk wheel that does not include commoncrypto. I've added them to our wheel builder job. If no one has any objections I'll probably upload them tomorrow. Note that until a new pip is released this means users will not download the 10.10+ wheel (and thus will not use commoncrypto temporarily).

**Comment by alex** [comment]
They've been uploaded.
