### ISSUE TITLE
osrandom engine already registered

### ISSUE THREAD

**Issue by nyanloutre** [pyca/cryptography#2473]
I use the Emby plugin for Kodi and it raise an error related to cryptography : 
RuntimeError: osrandom engine already registered

**Comment by reaperhulk** [comment]
Try upgrading to the latest cryptography if you're not on 1.1. It may resolve it, although the underlying problem is not resolved. See: #2299 (closing in favor of that issue)

**Comment by nyanloutre** [comment]
Thanks for the answer,

I have cryptography 1.0.1 on Ubuntu 15.10, what is the best manner to upgrade it ?
Should I use pip ? Because the packet python-cryptography is up to date

**Comment by reaperhulk** [comment]
Yeah you'll need to use pip to install 1.1 Be sure to uninstall the system package first though. You'll also need gcc/libssl-dev/libffi-dev to compile it. Please let us know if 1.1 resolves your issue!

**Comment by nyanloutre** [comment]
Yeah, thanks that worked with pip !
