### ISSUE TITLE
"Illegal instruction: 4" crash on OS:X when importing OpenSSL backend

### ISSUE THREAD

**Issue by alexander-lazarov** [pyca/cryptography#2474]
I had strange problems with python apps crashing with the following error:

```bash
$ scrapy
Illegal instruction: 4
```

I managed to reproduce the problem by doing the following:
```
Python 2.7.10 (default, Nov 10 2015, 09:57:20)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography.hazmat.backends.openssl.backend
Illegal instruction: 4
```

Same thing happens with python 3.4:
```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cryptography.hazmat.backends.openssl.backend
Illegal instruction: 4
```
I downgraded `cryptography` to `1.0.2` and it works without problems, so the error is in version `1.1` only.

I'm running OS:X El Capitan. Click [here](https://gist.github.com/alexander-lazarov/61f465b00ed1337b3b7e) for the crash log.

**Comment by grhaonan** [comment]
I met an different error when scrapy is run with 1.1 cryptography and it is solved by downgrading to 1.0.2.

OS:X EI Capitan
------------------------------------------------------------------------------------------------------------------------------------
File "/Library/Python/2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
    errors
cryptography.exceptions.InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this.

**Comment by reaperhulk** [comment]
Ugh, @alexander-lazarov this should be resolved now (the 10_6 wheels were built improperly and right now the current pip release will prefer the 10_6 wheel over 10_10).

**Comment by alexander-lazarov** [comment]
I think it downloads the 10_10 wheel:

```
$ pip install cryptography
Collecting cryptography
  Downloading cryptography-1.1-cp27-none-macosx_10_10_intel.whl (2.3MB)
```

**Comment by reaperhulk** [comment]
@alexander-lazarov I deleted the 10_6 wheels, which would have caused the illegal instruction error. Do you get the error with a fresh download?

**Comment by alexander-lazarov** [comment]
It's bug-free now, thanks!
