### ISSUE TITLE
Strange issue pip installing cryptography

### ISSUE THREAD

**Issue by OOPMan** [pyca/cryptography#2478]
Hi guys, I just encountered a rather odd series of issues with cryptography that seem to be related to pip caching the installation or something.

I'll try to explain the situation quickly and how I fixed it:

I'm running Ubuntu 15.10 and using the LaunchPad PyPy packages. Currently running PyPy 4.0.0 with everything in a virtualenv in my dev directory. I recently decided to start testing my Flask web app with uWSGI. At this point I discovered that the PyPy packages from LaunchPad do not include libpypy-c.so so 

I downloaded the PyPy 4.0.0 source and proceeded to compile my own PyPy from scratch with --shared enabled in order to generate the libpypy-c.so file. An hour and half later  have my .so file and I'm feeling lazy so I just copy it into the bin folder for my virtualenv to see if uWSGI will play ball. 

It seems to, for a short time but then I run into a very odd error when attempting to do 
```from PIL import Image```, which generates an exception of the form 
```
File "/home/adamj/Development/Tools/Python/VirtualEnv/x86_64/recomed-pypy-4.0.0-kubuntu.old/site-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: cannot import name '_imaging'
```

This only happens when running under uWSGI so I figured that maybe transplanting the .so file compiled on my system into the virtualenv created from the LaunchPad PyPy packages is the issue and decided to use my new custom PyPy build to create a fresh venv. 

A few minutes later and I have a new venv to throw at uWSGI. Start up my app except now I get a whole new error when my app attempts to make use of the Google API Python client. Specifically:
```CryptoUnavailableError('No crypto library available',)```. A bit of digging in the source reveals that this is happening when oauth2client.crypt is imported by google-api-python-client. Some more digging reveals oauth2client requires either PyCrypto (A no-go for PyPy) or PyOpenSSL (Which uses cryptography). A bit more digging and experimentation reveals that something is wrong with the cryptography install in my venv. 

Although all the expected .so files are present under cryptography.hazmat.bindings, actually attempting to use them (For example, by trying https://cryptography.io/en/latest/x509/tutorial/#creating-a-certificate-signing-request-csr) fails with an error about being unable to import the bindings.

We're finally coming to the end of the tail. I tried a bunch of things including upgrading and reinstalling cryptography but with no luck. Finally, I tried the following:
```
pip uninstall crytography
pip install cryptography --no-cache-dir --no-binary :all:
```
After doing this cryptography finally started working in my new venv and I was able to run my app with no errors under uWSGI.

I'm not sure if this is a cryptography issue or a pip issue? Any ideas?

**Comment by reaperhulk** [comment]
It's possible this is a cache problem. Significantly less likely that it is a cryptography issue given the success you had with the latter command. Have you tried deleting your wheel cache and then installing again without the additional args to see if the problem is resolved?

**Comment by OOPMan** [comment]
I'm going to do some more more testing tomorrow and see if I can replicate the issue again. Will give you guys an update.

**Comment by OOPMan** [comment]
Okay, I did another test downloading the compiled PyPy executables from the PyPy site and was able to replicate the issue.

It definitely seems to be a caching issue. Uninstalling cryptography and re-installing it with --no-cache-dir fixed the issue.

I shall open a ticket on pip.

**Comment by OOPMan** [comment]
It seems this relates to https://github.com/pypa/pip/issues/2882 and https://github.com/pyca/cryptography/issues/2006.

**Comment by OOPMan** [comment]
As a final note, replication instructions are as follows:

1. Spin up a fresh Ubuntu VM using something like EC2 or Digital Ocean
2. Install wget, build-essential, libssl-dev and libffi-dev
3. Install pypy using the PPA found at https://launchpad.net/~pypy/+archive/ubuntu/ppa
4. Install pip: ```wget -qO- https://bootstrap.pypa.io/get-pip.py |  /usr/bin/pypy```
5. Install virtualenv: ```/usr/bin/pip install virtualenv```
6. Create a new virtualenv: ```/usr/bin/virtualenv /tmp/venvA```
7. Install cryptography and oauth2client: ```/tmp/venvA/bin/pip install cryptography oauth2client```
8. Verify cryptography: ```/tmp/venvA/bin/pypy -m oauth2client.crypt```
9. Download and extract https://bitbucket.org/pypy/pypy/downloads/pypy-4.0.0-linux64.tar.bz2 to /tmp
10. Install pip: ```wget -qO- https://bootstrap.pypa.io/get-pip.py |  /tmp/pypy-4.0.0-linux64/bin/pypy```
11. Install virtualenv: ```/tmp/pypy-4.0.0-linux64/bin/pip install virtualenv```
12. Create a new virtualenv: ```/tmp/pypy-4.0.0-linux64/bin/virtualenv /tmp/venvB```
13. Install cryptography and oauth2client: ```/tmp/venvB/bin/pip install cryptography oauth2client```
14. Verify cryptography broken: ```/tmp/venvB/bin/pypy -m oauth2client.crypt```

Step 14 should produce output of the form:
```
ImportError: No encryption library found. Please install either PyOpenSSL, or PyCrypto 2.6 or later
```

**Comment by cmutzel** [comment]
Having what might be a similar issue here.  I don't understand the details enough to know if it is the same root cause:
https://github.com/pyca/cryptography/issues/2681

**Comment by OOPMan** [comment]
@cmutzel Did you try re-installing with the --no-cache-dir argument? If the issue is the same then that will fix it...
