### ISSUE TITLE
Add KDF in Feedback Mode from NIST SP 800-108 

### ISSUE THREAD

**Issue by jared-mess** [pyca/cryptography#2479]
A KDF that uses Pseudorandom Functions. Accepts the typical input `derivation key`, but also accepts a `Label` that identifies the purpose, and an optional `Context` that contains the information related to the derived keying material. Looks like it's similar to `HKDFExpand()`, but with a couple of additional input parameters.

http://csrc.nist.gov/publications/nistpubs/800-108/sp800-108.pdf

**Comment by Ayrx** [comment]
Is there a use case for this KDF?

**Comment by jared-mess** [comment]
The 800-108 KDFs enable you to generate many secret keys from a single secret key. This isn't a great practical example, but it's easy to explain and hopefully understand as a use case. Let's assume you have hundreds or even thousands of personal online accounts (netflix, amazon, et cetera). Let's say you want to store all of these credentials on your laptop so you don't have to remember them. Instead of encrypting every single credential with a symmetric key, you could just derive all your passwords from that symmetric key. That way you don't need to store anything at all (except maybe the salt value and iteration count you used for the PBDKF2 key). Now, if your laptop is lost or stolen, all the adversary has is a salt value. The stolen laptop doesn't affect you at all, you can still continue to derive all your account passwords on your new laptop (as long as you can access the PBDKF2 salt). 

Pseudocode example.
```
import os
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.kdf.feedbackkdf import FeedbackKDF

salt = os.urandom(16)

# Use a password for the initial key
my_pbkdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=salt, iterations=10000, backend=default_backend())
secret_key = my_pbkdf.derive(b'1n$ecur3P@ssword')

# Instead of storing your netflix secret, it can just be derived from the secret_key
netflix_fbkdf = FeedbackKDF(algorithm=hashes.SHA256(), length=32, label='netflix', context='me@gmail.com', backend=default_backend())
netflix_key = netflix_fbkdf(secret_key)
print(binascii.hexlify(netflix_key))

# Same goes for every other account
amazon_fbkdf = FeedbackKDF(algorithm=hasehs.SHA256(), length=32, label='amazon', contenxt='me@gmail.com', backend=default_backend())
amazon_key = amazon_fbkdf(secret_key)
print(binascii.hexlify(amazon_key))
```

I can implement this and make a pull request unless people have an issue with it.

**Comment by reaperhulk** [comment]
A quick search indicates at least one RFC (6803) uses this KDF, although I didn't find any other examples. http://csrc.nist.gov/groups/STM/cavp/key-derivation.html#kbkdfvs is a source for test vectors.

RFC 6803 uses Camellia, CMAC, and this KDF. We already have Camellia and CMAC so this KDF would complete the requirements. Of course, it's an open question whether anyone is clamoring for the ability to implement RFC 6803 using our project.

Are there any other use cases in current specs?

**Comment by reaperhulk** [comment]
This is complete
