### ISSUE TITLE
Hash by name or list of supported hashes desired

### ISSUE THREAD

**Issue by etrauschke** [pyca/cryptography#2492]
At the moment it seems fairly complicated to get to a certain hash algorithm because you need to know the class name. It would be nice if there is either a helper function which allows to get a hash class by its OpenSSL name (like 'sha1' or 'sha256') or at least a list of supported hashes so that someone could cycle through them and search for them by the name attribute of the different Hash classes.

**Comment by alex** [comment]
We definitely won't add support for OpenSSL names. As for a list, this can be found either by reading our documentation, or with `from cryptography.hazmat.primitives import hashes; print dir(hashes)`. The class names are self-explanatory.

**Comment by etrauschke** [comment]
You already have the OpenSSL names in the Hash classes as names.
And `print dir(hashes)` gives me not just the hash classes but also all the other attributes of that class:
```>>> print dir(hashes)
['AlreadyFinalized', 'Hash', 'HashAlgorithm', 'HashBackend', 'HashContext', 'MD5', 'RIPEMD160', 'SHA1', 'SHA224', 'SHA256', 'SHA384', 'SHA512', 'UnsupportedAlgorithm', 'Whirlpool', '_Reasons', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'abc', 'absolute_import', 'division', 'print_function', 'six', 'utils']
```

Not sure how you can programmatically get anything from the documentation.

Yes I agree, this is possible now by poking into all the attributes of the classes and check which one of those is an actual Hash algorithm. But I wouldn't consider this an interface.

Or let me ask you this: If you had to evaluate a signature in a program, how do you figure out which algorithm to use to verify this signature?

**Comment by alex** [comment]
I hardcode a list of supported algorithms for this signature verification,
I definitely do not want to attempt to introspect or dynamically support
things.

On Tue, Nov 24, 2015 at 1:52 PM, Erik Trauschke <notifications@github.com>
wrote:

> You already have the OpenSSL names in the Hash classes as names.
> And print dir(hashes) gives me not just the hash classes but also all the
> other attributes of that class:
> ```>>> print dir(hashes)
> ['AlreadyFinalized', 'Hash', 'HashAlgorithm', 'HashBackend',
> 'HashContext', 'MD5', 'RIPEMD160', 'SHA1', 'SHA224', 'SHA256', 'SHA384',
> 'SHA512', 'UnsupportedAlgorithm', 'Whirlpool', '*Reasons', '__builtins_*',
> '*doc*', '*file*', '*name*', '*package*', 'abc', 'absolute_import',
> 'division', 'print_function', 'six', 'utils']
>
>
> Not sure how you can programmatically get anything from the documentation.
>
> Yes I agree, this is possible now by poking into all the attributes of the classes and check which one of those is an actual Hash algorithm. But I wouldn't consider this an interface.
>
> Or let me ask you this: If you had to evaluate a signature in a program, how do you figure out which algorithm to use to verify this signature?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2492#issuecomment-159370869>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by etrauschke** [comment]
So everybody has to keep their own private list of algorithm names? Seems not very useful to me but I guess this is what I have to do here.

**Comment by tiran** [comment]
Dynamic support is easy to implement. 

```
>>> {h.name: h for h in hashes.HashAlgorithm._abc_registry}
{'sha1': <class 'cryptography.hazmat.primitives.hashes.SHA1'>, 'sha224': <class 'cryptography.hazmat.primitives.hashes.SHA224'>, 'sha384': <class 'cryptography.hazmat.primitives.hashes.SHA384'>, 'sha256': <class 'cryptography.hazmat.primitives.hashes.SHA256'>, 'sha512': <class 'cryptography.hazmat.primitives.hashes.SHA512'>, 'ripemd160': <class 'cryptography.hazmat.primitives.hashes.RIPEMD160'>, 'md5': <class 'cryptography.hazmat.primitives.hashes.MD5'>, 'whirlpool': <class 'cryptography.hazmat.primitives.hashes.Whirlpool'>}
```

If you don't like approach, then Cryptography could re-use register_interface to add classes to a registry class attribute of the interface class:

```
diff --git a/src/cryptography/utils.py b/src/cryptography/utils.py
index 4449e85..84a1fbd 100644
--- a/src/cryptography/utils.py
+++ b/src/cryptography/utils.py
@@ -23,6 +23,8 @@ def register_interface(iface):
     def register_decorator(klass):
         verify_interface(iface, klass)
         iface.register(klass)
+        if hasattr(iface, 'registry'):
+            iface.registry[klass.name] = klass
         return klass
     return register_decorator
``` 

Simply add a registry dict to some classes and you get a registry for free. A registry is useful in a couple of other places, for example ciphers, ciper modes etc.
```
@six.add_metaclass(abc.ABCMeta)
class HashAlgorithm(object):
    registry = {}
```

**Comment by etrauschke** [comment]
Thanks, that actually solved my problem but I wouldn't consider this a
user-friendly interface.

Erik
