### ISSUE TITLE
Enforce X.509 length restrictions?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2497]
RFC 5280 defines upper bounds for the allowable length of various fields in [Appendix A](http://tools.ietf.org/html/rfc5280#appendix-A). We should discuss how to enforce this (e.g. 64 character limit for common name).

**Comment by alex** [comment]
Enforcing these seems good to me. I wonder if we need to split it into `CertificateBuilder` and `RawCertificateBuilder`, where `Raw` doesn't do any of the validation for folks who are trying to generate test certs?

**Comment by reaperhulk** [comment]
OpenSSL actually enforces this (at least CN length limit). Setting a subject_name of `x509.Name([x509.NameAttribute(x509.NameOID.COMMON_NAME, u"0"*65)])` will trigger it.

**Comment by intgr** [comment]
+1 to finding a better way to report these length limit errors. Currently the error may occur much later after the name has been set on the builder, and the message is rather unhelpful, doesn't even point out the erroneous field:

> Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=218603671, lib=13, func=122, reason=151, reason_text=b'error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long')])

**Comment by alex** [comment]
As you noted, OpenSSL enforces these. I don't think we need to do anything here.
