### ISSUE TITLE
Use less memory compiling extensions

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2509]
https://github.com/letsencrypt/letsencrypt/issues/1081

**Comment by alex** [comment]
Filed a bug against cffi asking for this: https://bitbucket.org/cffi/cffi/issues/235/split-large-ffi-objects-into-multiple

**Comment by alex** [comment]
@reaperhulk you appear to be the last one to have looked at this -- from the cffi issue it looks like maybe it has a chance at working?

**Comment by reaperhulk** [comment]
It might be possible. I did a few small experiments trying to merge together multiple smaller shared objects. I ran into some issues but it seemed likely they were my fault. If someone has time to revisit this it's probably viable now (although we need to come up with a reasonable way to instrument memory consumption during compile to know whether this approach improves the situation).

**Comment by alex** [comment]
While we have not solved this, it's worth noting that now that we ship linux wheels, the situation should be significantly improved.

**Comment by alex** [comment]
Ok, we're now shipping wheels to most users which has strongly mitigated this.

It's not clear that doing better is possible without cffi changes (but it might be, we're not positive) -- we haven't heard complaints about this in a long time though, if we do hear more we can reevaluate.
