### ISSUE TITLE
Send a pull request to OpenSSL to add i2d_NAME_CONSTRAINTS

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2516]
Filing this here because it's the best place to track it.

**Comment by reaperhulk** [comment]
https://mta.openssl.org/pipermail/openssl-dev/2016-January/004004.html

**Comment by alex** [comment]
Conclusion seems to be that we should use `X509_add1_ext_i2d` and friends.

**Comment by alex** [comment]
Should we close this issue?

**Comment by reaperhulk** [comment]
I think so.
