### ISSUE TITLE
Provide wheels for Python 3.4/3.5 on Windows

### ISSUE THREAD

**Issue by patrys** [pyca/cryptography#2521]
`pycryptodome` has a very broad set of wheels available: https://pypi.python.org/pypi/pycryptodome

They greatly reduce the time we have to spend supporting our users (and new users often get stuck at `pip install`).

**Comment by alex** [comment]
We have wheels available for Python 3.4 and 3.5 for both 32 bit and 64 bit windows: https://pypi.python.org/pypi/cryptography

If you can show a specific case that we're missing a wheel for we can reopen this issue.

**Comment by patrys** [comment]
Sorry, I'm so tired I filled this for the wrong package. :sparkles:

**Comment by alex** [comment]
hah! cheers.
