### ISSUE TITLE
Support DES Encryption/Decryption

### ISSUE THREAD

**Issue by johnthagen** [pyca/cryptography#2523]
While DES is not suitable for new projects given its small key size, many legacy systems and protocols still use DES in varying ways.  Being able to be compatible with those systems from a well-documented and well-maintained Python cryptographic library would be very useful.

I would imagine DES would be placed into the [weak ciphers](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#weak-ciphers) package.

**Comment by reaperhulk** [comment]
3DES provides single DES simply by providing the same DES key * 3. This comes with an obvious performance penalty but I'd like to see a concrete case where DES performance is the bottleneck before we add more insecure ciphers.

**Comment by alex** [comment]
Unless DES had a not insecure use case, I'd be loathe to incentivize it by providing a faster implementation. I'm going to close this for now, we can reopen if there's a usecase.

**Comment by johnthagen** [comment]
My bad guys, I missed the fact that ``cryptography`` supports 3DES (and thus by extension DES, albeit in a somewhat round-about way).  I was looking for DES/3DES in the weak ciphers portion of the documentation, not realizing that 3DES is technically "secure" from practical attacks and as such it would be in the Symmetric encryption section.

For others' reference who may stumble onto this issue: https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/?highlight=3des#cryptography.hazmat.primitives.ciphers.algorithms.TripleDES

I don't have a use case where performance is critical, and thus support the decision to close this ticket.  Thanks for taking the time to educate me.
