### ISSUE TITLE
CRL X509_REVOKED Memory Issue

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2557]
In OpenSSl, `X509_CRL *` have a stack of `X509_REVOKED *`. In our parsing code we iterate over that using the `sk_X509_CRL_*` functions. However, `X509_REVOKED *` does not have a refcount, so it is freed when `X509_CRL_free` is called (which we register as a `gc` callback so it is called when the crl reference drops out of scope). Unfortunately, this is not safe. A user may choose to iterate the crl and save a `RevokedCertificate` instance, but this will point to garbage memory if the crl drops out of scope.

Ideally we could resolve this by incrementing the refcount, but since `X509_REVOKED *` doesn't have a refcount we're going to need to either retain the entire CRL struct for the lifetime of any sub-component (cue handwaving about how to do that) or else dupe every X509_REVOKED and pay the performance/memory penalty associated with that.

**Comment by alex** [comment]
It seems like all we need to do is add a private attribute on the `_RevokedCertificate` which points the the `_CRL`?

**Comment by reaperhulk** [comment]
Good handwaving, that seems like it'd work perfectly. PR comin'.
