### ISSUE TITLE
Overly loose None checking in x509 extensions causing ValueError to be thrown

### ISSUE THREAD

**Issue by danielknell** [pyca/cryptography#2640]
When parsing some certificates I hit the following error:

ValueError: authority_cert_issuer and authority_cert_serial_number must both be present or both None

It turns out that the cert at fault has authority_cert_serial_number equal to 0, after a little digging i found that this chokes on the following code:

```python
if authority_cert_issuer or authority_cert_serial_number:
    if not authority_cert_issuer or not authority_cert_serial_number:
        raise ValueError(
            "authority_cert_issuer and authority_cert_serial_number "
            "must both be present or both None"
        )
```

found at https://github.com/pyca/cryptography/blob/5660526e6baadb10a1969a32a2dda3bc14c78133/src/cryptography/x509/extensions.py#L159

as authority_cert_serial_number can be falsey should it not be checked with is None / is not None?

**Comment by alex** [comment]
Yup, this is a bug, I've tagged it for our next release.

**Comment by danielknell** [comment]
thank you ^_^
