### ISSUE TITLE
Add a jenkins job for pyopenssl

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#2656]
We should add a jenkins job that checks pyopenssl (both current PyPI and master branch) on merges to cryptography master.

**Comment by reaperhulk** [comment]
The motivation for this is the recent breakage caused by pyOpenSSL depending on the EVP_PKEY struct not being opaque.

**Comment by reaperhulk** [comment]
https://jenkins.cryptography.io/job/pyopenssl-smoke/ now has tests against current pyopenssl master and is triggered as a downstream job from `cryptography-master`. No release test yet.

**Comment by alex** [comment]
Going to call this done for now.
