### ISSUE TITLE
Cryptography 1.2.1 causes Python 2.7 on Windows x64 to crash on shutdown

### ISSUE THREAD

**Issue by hawkowl** [pyca/cryptography#2658]
Python: 2.7.10, 64bit
CFFI: 1.4.2
Cryptography: 1.2.1

When I run `trial twisted.test.test_sslverify` on Windows, the tests pass but after Trial finishes, Python crashes (shows up with a "Python has stopped working"). This does not happen on Cryptography 1.1.2, and it is the only changed variable in the buildbot.

I (think?) I can get crash dumps, if it'd help.

**Comment by reaperhulk** [comment]
Yeah, if you could get a dump that would be helpful.

**Comment by hawkowl** [comment]
not very useful, but here's the stack
<img width="478" alt="screen shot 2016-01-09 at 22 38 45" src="https://cloud.githubusercontent.com/assets/3307100/12216586/d99ff648-b721-11e5-82d0-4150354357ce.png">

**Comment by hawkowl** [comment]
(also a note, I have this on Windows 7, 64bit, with 64bit Python 2.7 -- but I haven't confirmed that it happens/doesn't happen on other Windowses, bitsesnesses, or Pythonses)

**Comment by alex** [comment]
This should be fixed by a patch just landed on `cffi`'s default branch. Can you try installing that and confirm this if this is fixed?

**Comment by hawkowl** [comment]
Works fine, thanks :D
