### ISSUE TITLE
Cryptography 1.2+ breaks freezegun

### ISSUE THREAD

**Issue by felliott** [pyca/cryptography#2662]
Hello,

With the release of cryptography-1.2.0, my freezegun-using tests have started crashing.  The traceback looks like:

````
Traceback (most recent call last):
  File "breaker2.py", line 10, in <module>
    with freezegun.freeze_time('2015-10-31 12:00:01'):
  File "/Users/fitz/.virtualenvs/cgdb/lib/python3.4/site-packages/freezegun/api.py", line 321, in __enter__
    self.start()
  File "/Users/fitz/.virtualenvs/cgdb/lib/python3.4/site-packages/freezegun/api.py", line 374, in start
    for module_attribute in dir(module):
TypeError: unorderable types: str() < int()
````

The crash occurs on [this line](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L375) when freezegun attempts to `dir()` on `_cffi_backend._extern_py`.  That module has integer keys in its `__dict__` method, causing the above error.  The dump of the `__dict__` looks like this:

````
{4441887152: (<ctype 'void(*)(int, int, char *, int)'>,
              <bound method type._lock_cb of <class 'cryptography.hazmat.bindings.openssl.binding.Binding'>>,
              b'\x00\x00\x00\x00\x00\x00\x00\x00',
              None),
 4441887184: (<ctype 'int(*)(char *, int, int, void *)'>,
              <function _pem_password_cb at 0x1077e3488>,
              b'\x00\x00\x00\x00\x00\x00\x00\x00',
              None),
 4441887216: (<ctype 'int(*)(unsigned char *, int)'>,
              <function _osrandom_rand_bytes at 0x108b6f2f0>,
              b'\xff\xff\xff\xff\x00\x00\x00\x00',
              None),
 4441887248: (<ctype 'int(*)()'>,
              <function _osrandom_rand_status at 0x108b6f378>,
              b'\x00\x00\x00\x00\x00\x00\x00\x00',
              None),
 '__doc__': None,
 '__loader__': None,
 '__name__': '_cffi_backend._extern_py',
 '__package__': None,
 '__spec__': None}
````

The suspect commit is 830af271de1c9c358, when cryptography was updated to use cffi's static callbacks.  [Here is a sample script that demonstrates the breakage.](https://gist.github.com/felliott/4547366a649dac4df6d1)

I'm relatively new to Python, so I'm not sure if this is a bug in cffi, cryptography, or freezegun. I'm happy to refile elsewhere if needed.  Please let me know if you need any more information.  Thank lyou very much and have a great day!

Cheers,
Fitz

**Comment by alex** [comment]
This looks like a bug with Freezegun. Although unusual, there's no real guarantee that there'll be only string keys in a module's `__dict__`.  I could also be convinced that this is a `cffi` bug. Definitely not a cryptography one though :-)

**Comment by felliott** [comment]
Sounds good.  I'll try reporting it on freezegun. Thank you!
Cheers,
Fitz 
On Jan 10, 2016 5:51 PM, Alex Gaynor <notifications@github.com> wrote:This looks like a bug with Freezegun. Although unusual, there's no real guarantee that there'll be only string keys in a module's __dict__.  I could also be convinced that this is a cffi bug. Definitely not a cryptography one though :-)
