### ISSUE TITLE
pip install cryptography with -t argument does not create module/egg

### ISSUE THREAD

**Issue by cmutzel** [pyca/cryptography#2681]
Working on Amazon linux (i.e. Amazon Linux AMI 2015.09.1 x86_64 HVM GP2) available from their marketplace
_____
**Problem**:
*Ran this*
`pip install cryptography`

*Checking the result*
`python -c 'import cryptography'`

*^^ works fine*

But, this does not work:

*Ran*
`/usr/local/bin/pip install cryptography -t installed`

*output from pip*
`...blah blah...`
`Successfully installed cffi-1.5.0 cryptography-1.2.1 enum34-1.1.2 idna-2.0 ipaddress-1.0.16 pyasn1-0.1.9 pycparser-2.14 setuptools-19.4 six-1.8.0`

*checking the result*

`[ec2-user@ip-10-0-0-214 ~]$ ls installed
easy_install.py              idna                        ipaddress.pyc  pyasn1-0.1.9.dist-info         setuptools-19.4.dist-info
easy_install.pyc             idna-2.0.dist-info          _markerlib     pycparser                      six-1.10.0.dist-info
enum                         ipaddress-1.0.16.dist-info  pkg_resources  pycparser-2.14-py2.7.egg-info  six.py
enum34-1.1.2-py2.7.egg-info  ipaddress.py                pyasn1         setuptools                     six.pyc`

**Some other context:**
`[ec2-user@ip-10-0-0-214 ~]$ uname -a
Linux ip-10-0-0-214 4.1.10-17.31.amzn1.x86_64 #1 SMP Sat Oct 24 01:31:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
`[ec2-user@ip-10-0-0-214 ~]$ python --version
Python 2.7.10`
[ec2-user@ip-10-0-0-214 ~]$ pip --version
pip 8.0.0 from /usr/local/lib/python2.7/site-packages (python 2.7)

ec2-user@ip-10-0-0-214 ~]$ pip list
aws-cfn-bootstrap (1.4)
awscli (1.9.18)
Babel (0.9.4)
backports.ssl-match-hostname (3.4.0.2)
boto (2.38.0)
botocore (1.3.18)
cffi (1.5.0)
chardet (2.0.1)
cloud-init (0.7.6)
colorama (0.2.5)
configobj (4.7.2)
cryptography (1.2.1)
docutils (0.11)
ecdsa (0.11)
enum34 (1.1.2)
idna (2.0)
iniparse (0.3.1)
ipaddress (1.0.16)
Jinja2 (2.7.2)
jmespath (0.7.1)
jsonpatch (1.2)
jsonpointer (1.0)
kitchen (1.1.1)
lockfile (0.8)
MarkupSafe (0.11)
paramiko (1.15.1)
PIL (1.1.6)
pip (8.0.0)
ply (3.4)
pyasn1 (0.1.9)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pystache (0.5.3)
python-daemon (1.5.2)
python-dateutil (2.1)
pyxattr (0.5.0)
PyYAML (3.10)
requests (1.2.3)
rsa (3.1.2)
setuptools (19.4)
simplejson (3.6.5)
six (1.8.0)
urlgrabber (3.9.1)
urllib3 (1.8.2)
virtualenv (12.0.7)
yum-metadata-parser (1.1.4)

*Have also tried with sudo and then I get this error:*
[ec2-user@ip-10-0-0-214 standalone_with_virtual]$ /usr/local/bin/pip install cryptography -t vendored --force-reinstall --no-deps
Collecting cryptography
  Using cached cryptography-1.2.1.tar.gz
Installing collected packages: cryptography
  Running setup.py install for cryptography ... done
Successfully installed cryptography-1.2.1
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 357, in run
    for item in os.listdir(lib_dir):
OSError: [Errno 2] No such file or directory: '/tmp/tmpZ6sWGM/lib/python'

Looks like a pip problem but I thought I would check here first?

**Comment by reaperhulk** [comment]
You might try downgrading to pip 7.1.2 to see if that works (and if it does file an issue with pip!). This definitely does not look like a cryptography issue though.

**Comment by cmutzel** [comment]
Okay, I seem to having the problem with several other libraries that are being installed under /usr/local/lib64.  I'll close and reopen something with pip. 

Thanks for the quick reply!
