### ISSUE TITLE
 UnsupportedAlgorithm: RSA is not supported by the backend

### ISSUE THREAD

**Issue by nchammas** [pyca/cryptography#2687]
I'm having trouble using [AsyncSSH](https://github.com/ronf/asyncssh) to connect to EC2 instances using my RSA private key. The error I'm getting from AsyncSSH seems to be coming from Cryptography:

```
.../lib/python3.5/site-packages/cryptography/hazmat/backends/multibackend.py in load_rsa_private_numbers(self, numbers)
    148 
    149         raise UnsupportedAlgorithm("RSA is not supported by the backend",
--> 150                                    _Reasons.UNSUPPORTED_PUBLIC_KEY_ALGORITHM)
    151 
    152     def load_rsa_public_numbers(self, numbers):

UnsupportedAlgorithm: RSA is not supported by the backend
```

This seems related to #1958. I followed a [tip provided there](https://github.com/pyca/cryptography/issues/1958#issuecomment-102637673) and ran the following:

```python
>>> from cryptography.hazmat.backends import default_backend
>>> print(default_backend()._backends)
[]
```

Any pointers for how to debug this?

I installed Cryptography 1.2.1 on OS X via AsyncSSH:

```sh
pip install 'asyncssh[bcrypt,libnacl]'
```

**Comment by reaperhulk** [comment]
Is this in a virtualenv? What version of python and pip are you using?

**Comment by nchammas** [comment]
Yep, in a virtual env.

```
$ python3 --version
Python 3.5.1
$ pip3 --version
pip 8.0.2 from .../venv/lib/python3.5/site-packages (python 3.5)
```

**Comment by reaperhulk** [comment]
Did you run the `_backends` check using ipython? What do you get if you just run `python -c "from cryptography.hazmat.backends import default_backend; print(default_backend()._backends)"`?

If that's still empty what happens if you do `from cryptography.hazmat.bindings import _openssl`?

**Comment by nchammas** [comment]
:open_mouth: Good catch. I *was* running that previous check from iPython.

Here's the check you requested from the command line:

```sh
$ python3 -c "from cryptography.hazmat.backends import default_backend; print(default_backend()._backends)"
[<cryptography.hazmat.backends.commoncrypto.backend.Backend object at 0x11066cda0>, <cryptography.hazmat.backends.openssl.backend.Backend object at 0x11066c4e0>]
```

Why would the results be different?

I guess this explains some of the weirdness I was seeing. My real problem is with my application, which I run from the command line. But I opened up iPython to try to narrow down the issue and in the process hit this separate error about RSA backends. So perhaps they are two different issues.

**Comment by reaperhulk** [comment]
If you install ipython into your virtual env it should work properly. Your other issue is probably independent of this one.

**Comment by nchammas** [comment]
Okie doke! Yep, I don't have iPython installed on the virtual env. Thanks for the quick help.
