### ISSUE TITLE
Add CertificateBuilder.from_certificate API

### ISSUE THREAD

**Issue by Lukasa** [pyca/cryptography#2689]
Frequently I find myself wanting to make relatively minor changes to a certificate. Cryptography's CertificateBuilder class is fantastic for this (much better than the equivalent OpenSSL incantations), but it ends up being relatively laborious to manually transpose each field in the certificate one by one into a certificate builder.

It'd be nice to have a shortcut that lets you build a CertificateBuilder from an already present Certificate object.

**Comment by reaperhulk** [comment]
This is mostly going to look like:

```

    @classmethod
    def from_certificate(cls, certificate):
        builder = cls()
        builder.issuer_name = certificate.issuer
        builder.subject_name = certificate.subject
        builder.public_key = certificate.public_key()
        builder.serial_number = certificate.serial_number
        builder.not_valid_before = certificate.not_valid_before
        builder.not_valid_after = certificate.not_valid_after
        for ext in certificate.extensions:
            builder.add_extension(ext.value, ext.critical)

        return builder
```

However I'm not sure how useful this is since we don't allow you to change an item once you've set it.

**Comment by alex** [comment]
Except replace teh assignment with method calls :-) But yeah, the
only-assign-once bit means this pattern isn't super useful.

On Mon, Jan 25, 2016 at 8:29 PM, Paul Kehrer <notifications@github.com>
wrote:

> This is mostly going to look like:
>
>
>     @classmethod
>     def from_certificate(cls, certificate):
>         builder = cls()
>         builder.issuer_name = certificate.issuer
>         builder.subject_name = certificate.subject
>         builder.public_key = certificate.public_key()
>         builder.serial_number = certificate.serial_number
>         builder.not_valid_before = certificate.not_valid_before
>         builder.not_valid_after = certificate.not_valid_after
>         for ext in certificate.extensions:
>             builder.add_extension(ext.value, ext.critical)
>
>         return builder
>
> However I'm not sure how useful this is since we don't allow you to change
> an item once you've set it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2689#issuecomment-174759097>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by reaperhulk** [comment]
uhh, yeah, oops.

**Comment by Lukasa** [comment]
Hmm.

How clever can we be here, and how clever is it worth being? We could, for example, have the user provide a filter that either whitelists in or blacklists out the parameters they want. But that starts getting weird and tricky and subtle bugs can enter that kind of code, so I don't know how I feel about it.

**Comment by alex** [comment]
Can you think of an API that's good?

**Comment by reaperhulk** [comment]
Going once...going twice... :grinning:

**Comment by alex** [comment]
No one can come up with a good API here, going to close this for now, feel free to reopen if anyone thinks this is so critical it should be kept open absent a concrete task.
