### ISSUE TITLE
Fernet decrypt with future token gives blank error message

### ISSUE THREAD

**Issue by jsayles** [pyca/cryptography#2706]
I'm using the Fernet secret key encryption/decryption on two different systems.  If the time of the two systems is off with the encryption server being in the future, the decrypt method throws an error and the error message is blank.  A more descriptive error message would be helpful.

Both systems are Ubuntu machines running Python 2.7.10.

**Comment by reaperhulk** [comment]
Thanks for the report! If you're setting the ttl to None then we resolved this issue #2682, which will go out in the next major release.

**Comment by jsayles** [comment]
It does look like #2682 will resolve this issue.  Thank you!
