### ISSUE TITLE
Intermittent segfault on Debian unstable / i386

### ISSUE THREAD

**Issue by mithrandi** [pyca/cryptography#2711]
I'm getting a segfault non-deterministically running the test suite on Debian unstable i386. I have not been able to reproduce the segfault on amd64, and it doesn't happen every time, but there seems to be a fairly high probability that I'll get a segfault somewhere during the test run.

An example of one such backtrace during a full test run is: https://gist.github.com/mithrandi/347185c625358b6ab9b9

I have reproduced the segfault (at least, I assume it's the same one) on Python 2.7, Python 3.4, and Python 3.5.

Running `tests/hazmat/backends/test_openssl.py::TestOpenSSLSerializationWithOpenSSL::test_pem_password_cb` by itself seems to segfault every time on 2.7, and with high probability on 3.x. Occasionally, the following test failure is observed instead of a segfault:
```
self = <tests.hazmat.backends.test_openssl.TestOpenSSLSerializationWithOpenSSL object at 0xedf1e9ac>

    def test_pem_password_cb(self):
        password = b'abcdefg'
        ffi_cb, userdata = backend._pem_password_cb(password)
        handle = backend._ffi.new_handle(userdata)
        buf = backend._ffi.new('char *')
        assert ffi_cb(buf, len(password) + 1, False, handle) == len(password)
        assert userdata.called == 1
>       assert backend._ffi.string(buf, len(password)) == password
E       assert b'abcdcfg' == b'abcdefg'
E         At index 4 diff: 99 != 101
E         Use -v to get the full diff

tests/hazmat/backends/test_openssl.py:619: AssertionError
```
An example of a backtrace from one of these is here: https://gist.github.com/mithrandi/5c1e09486154a092c5bb

As the backtraces differ, I'm not entirely sure there's only one bug here, but it seems likely that they're related at least.

**Comment by mithrandi** [comment]
Ah, the 2.7 backtrace (running the single test) is different to the 3.x one: https://gist.github.com/mithrandi/77d94af7476c5eea5ed5

**Comment by reaperhulk** [comment]
Do you get the exception if you downgrade cffi to 1.3.x? (That will force it to use an older code path for callbacks)

**Comment by reaperhulk** [comment]
s/exception/SIGSEGV

**Comment by mithrandi** [comment]
Yes, same behaviour with cffi 1.3.1.

**Comment by mithrandi** [comment]
I've racked up a significant number of test runs on amd64 without any segfaults, incidentally, so I'm fairly certain the problem doesn't exist there.

**Comment by reaperhulk** [comment]
Huh, well that would seem to argue against it being related to static callbacks. This sounds more like a misdeclaration in an arch-dependent type's width? Very odd that the pem_password_cb test triggers this though...

**Comment by reaperhulk** [comment]
Super confused on the crash occurring with cffi 1.3.1 though since that 2.7 trace looks *exactly* like the static callback crash on shutdown bug...

**Comment by mithrandi** [comment]
I've sampled a few more traces and I get traces all over the show (sometimes it crashes during the test run, sometimes at shutdown, ...) so I think it's just generalized memory corruption due to an overflow/underrun/whatever.

**Comment by reaperhulk** [comment]
Do you see this crash on 1.1.2 on i386?

**Comment by mithrandi** [comment]
That particular test didn't exist in 1.1.2, but I copied it over and ran it with the following results:

Python 2.7, cffi 1.3.1: no crash
Python 2.7, cffi 1.5.0: no crash
Python 3.4, cffi 1.3.1: occasional segfaults and test failures due to corruption (fifth byte in the buffer is overwritten, as above)
Python 3.4, cffi 1.5.0: occasional segfaults and failures
Python 3.5, cffi 1.3.1: occasional segfaults and failures
Python 3.5, cffi 1.5.0: no crash

I note that when the test fails instead of segfaulting, it's always that same fifth byte that's been corrupted.

**Comment by alex** [comment]
This should be fixed by a patch just landed on `cffi`'s default branch. Can you try installing that and confirm this if this is fixed?

**Comment by alex** [comment]
Can you run with everything compiled under ASAN and see if we can pintpoint where the bug is?

**Comment by mithrandi** [comment]
`cffi` default doesn't seem to change everything. I guess I'll give the ASAN thing a shot, but that's a big pain so I might be a while ;P

**Comment by mithrandi** [comment]
I ran with (I think!) CPython 3.5, libffi, cffi, libssl, and cryptography recompiled with clang + ASAN; unfortunately, it didn't seem to do much. I get runs with the test failure that don't trip ASAN at all, I get segfaults with an ASAN-provided stack trace that doesn't seem to provide any information that gdb wasn't already providing, and I get failures like this which also seem to be unhelpful: https://gist.github.com/mithrandi/2b0fa115203001edd1b4

**Comment by mithrandi** [comment]
Okay, figured out the problem: the test is just bogus. `_ffi.new('char *')` allocates a buffer of size 1 (a single char); on 64-bit platforms, this gets aligned to 8 bytes, which is big enough to fit the 6 char password; on 32-bit platforms, this gets aligned to 4 bytes, so the 6 char overflows and we crash.
