### ISSUE TITLE
Fernet exposes ciphertext creation time in plaintext, without opt-out

### ISSUE THREAD

**Issue by thejh** [pyca/cryptography#2714]
Fernet encryption stores the token creation time in the token, in plaintext, without a supported way to opt out of that. From a privacy perspective, that's not optimal.

I believe that it would make sense to:

 - Let the caller specify whether he wants to store the current time. If he doesn't want to, just store zero as time - if someone tries to decrypt the token and unexpectedly does enforces TTL, decryption will just fail. (I would prefer an opt-in here, but since you probably want to keep the API stable, I guess this would have to be opt-out?)
 - Perhaps consider moving the time into the encrypted part and only check it after successful HMAC verification. This has two effects: It prevents third parties from seeing how old the message is (I think that's a good thing) and it introduces a slight timing difference that might allow an attacker to determine whether an expired message was valid once (which I think doesn't matter much in comparison).

**Comment by reaperhulk** [comment]
Cryptography only implements the Fernet spec, so discussion about this is really best directed to https://github.com/fernet/spec

**Comment by Ayrx** [comment]
Just a plug for one of my own libraries: if you want to encrypt data with an API very similar to that of Fernet but without the TTL check and all that stuff (but with the ability to add arbitrary associated data), check out [python-aead](https://github.com/Ayrx/python-aead).

It's a very thin layer of pure Python on top of cryptography so if you can install cryptography you can install python-aead.

**Comment by reaperhulk** [comment]
I'm going to go ahead and close this as an upstream fernet issue, but if there's something you feel we can do without altering the spec feel free to reopen/comment.

**Comment by whit537** [comment]
> Time has blunted my memory a bit, but the main concern we originally had (although credit goes to @dstufft for originally raising the issue) was around the fact that Fernet's wire format exposes a plaintext timestamp. For some use cases this is useful and it is possible to use this safely, but it represents a chink in the "bulletproof can't use it wrong" armor we desire.

Additional discussion at https://github.com/pyca/cryptography/issues/2900#issuecomment-217213039.
