### ISSUE TITLE
Bindings-only point-release

### ISSUE THREAD

**Issue by hynek** [pyca/cryptography#2715]
hi,

recently a bunch of bindings have been added to cryptography in order to implement a few pyOpenSSL methods that are empty since 0.14.

Since 1.3 is far away, @reaperhulk indicated he might do a 1.2 point release with them.  Is that going to happen?  While I dread it, I would like to get pyOpenSSL 16.0.0 out of the door ASAP and those methods are the last unresolved blocker.

**Comment by alex** [comment]
@hynek Is https://github.com/pyca/cryptography/pull/2703 what you need backported? Anything else?

**Comment by hynek** [comment]
Maybe it would be best to implement the missing methods in PRs and once the master builds pass do the release.

**Comment by alex** [comment]
That sounds like a great strategy!

**Comment by reaperhulk** [comment]
I am happy to do the release with the bindings once we've landed them. Just so I remember: we should also backport the fernet timestamp fix and the char pointer vs array fix in the tests so the tests can pass reliably on 32-bit.

**Comment by hynek** [comment]
FTR, https://github.com/pyca/pyopenssl/pull/422 is r4r.  It's unlikely that we'll need any more bindings so you may proceed I guess?


FWIW, I'm leaving on vacation on Tuesday, so it would be nice if we could release once I'm back. :) pyOpenSSL has been cooking far too long. :-/

**Comment by alex** [comment]
From a scheduling perspective, we have to do a security release on Tuesday
to go with the OpenSLS release occurring. So, once that ships we can do the
bindings point release.

On Sun, Feb 28, 2016 at 2:50 AM, Hynek Schlawack <notifications@github.com>
wrote:

> FTR, pyca/pyopenssl#422 <https://github.com/pyca/pyopenssl/pull/422> is
> r4r. It's unlikely that we'll need any more bindings so you may proceed I
> guess?
>
> FWIW, I'm leaving on vacation on Tuesday, so it would be nice if we could
> release once I'm back. :) pyOpenSSL has been cooking far too long. :-/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2715#issuecomment-189816880>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
@reaperhulk do we want to do this, or just a 1.3?

**Comment by reaperhulk** [comment]
Assuming our timeline for 1.3 ends up being acceptable I'd rather just do it as 1.3 (Taking a look at the post-triage milestone I'd say...1-2 weeks?)
