### ISSUE TITLE
Throw a specific exception when no backends are available

### ISSUE THREAD

**Issue by djc** [pyca/cryptography#2717]
In e.g. #1958, an exception is thrown that in some cases appears to be due to the fact that no backends are available. It might be nice if in these cases a specific exception would be thrown.

**Comment by alex** [comment]
Thinking more, is there any reason we shouldn't make this a constructor error for `MultiBackend`? /cc @reaperhulk

**Comment by reaperhulk** [comment]
The only obstacle I see there is that we currently use an empty multibackend to test for various unsupported calls, but that's exactly the scenario that's causing confusion now so it makes sense to me that we should change it.

**Comment by alex** [comment]
I don't think there's any legitimate configuration with an empty
multibackend.

On Tue, Mar 1, 2016 at 11:16 PM, Paul Kehrer <notifications@github.com>
wrote:

> The only obstacle I see there is that we currently use an empty
> multibackend to test for various unsupported calls, but that's exactly the
> scenario that's causing confusion now so it makes sense to me that we
> should change it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2717#issuecomment-191050445>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
Promoting to 1.3.
