### ISSUE TITLE
SystemError: <built-in method cast of CompiledFFI object at 0x7f596a19f300> returned a result with an error set

### ISSUE THREAD

**Issue by vain** [pyca/cryptography#2728]
I'm using https://github.com/pyldap/pyldap to connect to an LDAP server. When retrieving data from that server, I get the following error:

    From cffi callback <function _osrandom_rand_bytes at 0x7f5969f2e6a8>:
    StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/blablabla/virtualenv/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 74, in _osrandom_rand_bytes
        signed = ffi.cast("char *", buf)
    SystemError: <built-in method cast of CompiledFFI object at 0x7f596a19f300> returned a result with an error set

Now, when I apply the following patch to `cryptography/hazmat/bindings/openssl/binding.py`, the error disappears:

    --- binding.py	2016-02-22 14:17:22.361357770 +0100
    +++ binding.py	2016-02-22 14:17:58.681028780 +0100
    @@ -68,6 +67,10 @@
                   name="Cryptography_rand_bytes",
                   error=-1)
     def _osrandom_rand_bytes(buf, size):
    +    try:
    +        raise Exception("dummy exception to force error clear")
    +    except Exception:
    +        pass
         signed = ffi.cast("char *", buf)
         result = os.urandom(size)
         signed[0:size] = result

I'm on Arch Linux with Python 3.5.1. I installed the packages using `pip`:

    (virtualenv) $ pip freeze
    cffi==1.5.2
    cryptography==1.2.2
    idna==2.0
    Jinja2==2.8
    Mako==1.0.3
    MarkupSafe==0.23
    passlib==1.6.5
    pyasn1==0.1.9
    pycparser==2.14
    pyldap==2.4.25
    requests==2.9.1
    six==1.10.0
    wheel==0.26.0

Do you have any idea what could be happening here? How could I try to debug the issue?

I'm not even sure what `SystemError: ... returned a result with an error set` is supposed to mean. "Error set" as in "a set of errors" or "an error (flag) has been set"?

I'm working on writing a minimal program that triggers the bug -- no luck so far. The error happens in a large and complex application.

I'm very sorry for the vague bug report. Any help is highly appreciated.

**Comment by vain** [comment]
Here's another important detail. Consider the following patch to `cryptography/hazmat/bindings/openssl/binding.py`:

    --- binding.py	2016-02-22 14:17:22.361357770 +0100
    +++ binding.py	2016-02-22 14:30:57.444092067 +0100
    @@ -64,10 +63,15 @@
         return wrapper
     
     
    +def foo():
    +    return
    +
    +
     @ffi_callback("int (*)(unsigned char *, int)",
                   name="Cryptography_rand_bytes",
                   error=-1)
     def _osrandom_rand_bytes(buf, size):
    +    foo()
         signed = ffi.cast("char *", buf)
         result = os.urandom(size)
         signed[0:size] = result

Now I get the following error:

    From cffi callback <function _osrandom_rand_bytes at 0x7fdd9cfeb730>:
    StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/blablabla/virtualenv/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 74, in _osrandom_rand_bytes
        foo()
    SystemError: PyEval_EvalFrameEx returned a result with an error set

That simple call to `foo()` triggers the bug.

That's why my exception in the first bug says `"dummy exception to force error clear"`. I assume some kind of error flag (?!) is set and virtually any function call will cause an exception.

**Comment by reaperhulk** [comment]
This looks like it may be a cffi issue related to static callbacks. I'm unfortunately not going to have time to look at this soon, but hopefully this can be turned into a reduced test case and reported upstream if so.

**Comment by reaperhulk** [comment]
I'm going to close this for now since we haven't gotten more feedback. If this is still occurring with the latest version feel free to reopen.

**Comment by vain** [comment]
Yeah, sorry. No problems recently. Automagically resolved itself. :/
