### ISSUE TITLE
RSA encrypt without padding

### ISSUE THREAD

**Issue by lfrodrigues** [pyca/cryptography#2735]
I have some pycrypto code that I'm converting to cryptography. I have converted everything except the RSA functions. 

pycrypto (from what I understood) has no padding, so I can't convert this: 
```
RSA_key = RSA.construct((int(publicKeyModulus, 16),int(publicKeyExponent, 16)))
cipher_text = RSA_key.encrypt(VALUE, 0)[0]
```

**Comment by alex** [comment]
You are correct that we don't support this. Unpadded RSA is extremely insecure, unless there's an extremely compelling reason to add it, I think I'd prefer to just say it's unsupported.

**Comment by lfrodrigues** [comment]
My pycrypto code was converted from Java (bouncycastle) that is used in a legacy code base. Somehow it was implemented without it, the only way that I can connect to destination servers is without padding. 

Will you consider adding it in the hazmat layer? If not I guess the solution is to use pycrypto just for this part. But anyone else wanting to move from pycrypto to a more secure/audited code base that has same problem as me can't move.

**Comment by alex** [comment]
I think for now I'm going to call this WontFix for cryptography; even by hazmat layer standards unpadded RSA is too unsafe.

FWIW, you can implement RSA yourself with `public_numbers` / `private_numbers`, if you don't care much about performance RSA encryption is just `pow(message, public.e, public.n)`.

**Comment by FelixSchwarz** [comment]
@alex, @lfrodrigues I'd like to thank both of you for your input which really helped me solving a similar problem.

Just in case someone needs to do the same thing here is some code example (**THIS IS INSECURE** - DO NOT USE THIS):

    import math
    input_ = b'...'
    # you can get e/n using ".public_numbers()" on a cryptography _RSAPublicKey
    e = ...
    n = ...
    keylength = math.ceil(n.bit_length() / 8)
    input_nr = int.from_bytes(input_, byteorder='big')
    crypted_nr = pow(input_nr, e, n)
    crypted_data = crypted_nr.to_bytes(keylength, byteorder='big')

I hesitated to post this because **you should not use this if you are interested in security!** However I have a case where RSA "encryption" is used as a kind of cryptographic hash (don't ask, it was written in a governmental spec) where this kind of code is required.

**Comment by elad** [comment]
@alex FWIW, I've seen a need for this when playing with TPM and attestation. See https://github.com/sweis/aiktools/blob/master/aikchallenge.c#L205-L214

**Comment by reaperhulk** [comment]
@elad That code does OAEP padding and then calls encrypt passing `RSA_NO_PADDING` because it has previously padded the payload. To replicate that in cryptography you'd just use OAEP directly during the encrypt call.

**Comment by elad** [comment]
@reaperhulk I've seen a Python version of that code that also insists on doings its own TPM-specific OAEP padding: https://github.com/mjg59/python-tss/blob/master/pytss/attestationutils.py#L365-L371

I haven't read the actual specification, but are you suggesting that this is "cargo-culted" and in fact there's nothing special about this kind of padding and it can be rewritten like this? (taken from the documentation)

```python
message = b"encrypted data"
ciphertext = public_key.encrypt(
    message,
    padding.OAEP(
        mgf=padding.MGF1(algorithm=hashes.SHA1()),
        algorithm=hashes.SHA1(),
        label=None
    )
)
```

**Comment by reaperhulk** [comment]
Ah, TPM's implement RSA OAEP with an OAEP encoding parameter of "TCPA". The sample code in the `aikchallenge.c` example uses `RSA_padding_add_PKCS1_OAEP` to add the encoding parameter. Encoding parameter is just another term for label. So to support the TPM use case the actual code would be:

```python
message = b"encrypted data"
ciphertext = public_key.encrypt(
    message,
    padding.OAEP(
        mgf=padding.MGF1(algorithm=hashes.SHA1()),
        algorithm=hashes.SHA1(),
        label=b"TCPA"
    )
)
```

(See also #3883 where we implemented OAEP label support specifically in response to the TPM use case)

**Comment by nirizr** [comment]
FWIW, I encountered this issue while implementing a protocol that has a proprietary padding scheme. Adding a "padding.MANUAL_PADDING" that does nothing may be a compromise between directing users in the secure direction while allowing for the advanced user.

I ended up using `pow` instead, but using the same APIs feels clearer.
