### ISSUE TITLE
x509.AuthorityKeyIdentifier documented use is buggy

### ISSUE THREAD

**Issue by jrabbit** [pyca/cryptography#2758]
[Docs here](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.AuthorityKeyIdentifier.from_issuer_public_key)

used in some of my own code like so:
```python
builder.add_extension(
    x509.AuthorityKeyIdentifier.from_issuer_public_key(ca_cert.public_key()), critical=False
    )
```
https://gist.github.com/jrabbit/e84b3c593e18bcf7d2dd#file-cert-py-L57
output cert fails to verify in `openssl x509 verify` & `certtool --verify`

the AKI it computes seems to be the SKI?

**Comment by alex** [comment]
Is there any chance you can make the example generate the CA cert/key in memory so that the example is runnable standalone?

**Comment by jrabbit** [comment]
https://gist.github.com/jrabbit/e6d6bed8a13dae019a8e so this works so maybe it's the CA cert being read wrong?

**Comment by jrabbit** [comment]
I can provide the ca cert it's not sensitive

**Comment by jrabbit** [comment]
Ok when loading from a gnutls generated CA cert/key it has issues. https://gist.github.com/jrabbit/009ca3e92a0ab5ae8ad6 not just this set but a fresh one without the unicode also. I'll see if cryptography generated key loaded from disk has issues in a bit

**Comment by reaperhulk** [comment]
It looks like the issue here is that the method of generating the key identifier that we use doesn't mesh with the way it is generated by gnutls (RFC 5280 defines two methods but also says "go nuts and make your own": https://tools.ietf.org/html/rfc5280#section-4.2.1.2)

I can make this work just fine with the gnutls cert by changing the the AKI generation to do this (which just copies the CA's SKI digest value to the cert's AKI key_identifier):

```
    ext = ca_cert.extensions.get_extension_for_class(x509.SubjectKeyIdentifier)
    builder = builder.add_extension(
        x509.AuthorityKeyIdentifier(
            key_identifier=ext.value.digest, 
            authority_cert_issuer=None, 
            authority_cert_serial_number=None),
        ext.critical
        )
```

One way we could handle this would be to add a `AuthorityKeyIdentifier.copy_from_ca_ski(cert)`, although that would fail if the parent certificate does not have a SKI.

**Comment by alex** [comment]
`AKI.from_issuer_subject_key_identifier(cert)` sounds like a great solution.

On Sun, Mar 6, 2016 at 4:25 PM, Paul Kehrer <notifications@github.com>
wrote:

> It looks like the issue here is that the method of generating the key
> identifier that we use doesn't mesh with the way it is generated by gnutls
> (RFC 5280 defines two methods but also says "go nuts and make your own":
> https://tools.ietf.org/html/rfc5280#section-4.2.1.2)
>
> I can make this work just fine with the gnutls cert by changing the the
> AKI generation to do this (which just copies the CA's SKI digest value to
> the cert's AKI key_identifier):
>
>     ext = ca_cert.extensions.get_extension_for_class(x509.SubjectKeyIdentifier)
>     builder = builder.add_extension(
>         x509.AuthorityKeyIdentifier(
>             key_identifier=ext.value.digest,
>             authority_cert_issuer=None,
>             authority_cert_serial_number=None),
>         ext.critical
>         )
>
> One way we could handle this would be to add a
> AuthorityKeyIdentifier.copy_from_ca_ski(cert), although that would fail
> if the parent certificate does not have a SKI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2758#issuecomment-193000323>.
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
