### ISSUE TITLE
Google App Engine Support?

### ISSUE THREAD

**Issue by ChrisDenton** [pyca/cryptography#2764]
Would support for Google App Engine be at all possible? I'm not familiar with the cryptography source but I'd guess it'd require using pycrypto as a backend (as it's the only relevant [supported C library](https://cloud.google.com/appengine/docs/python/tools/libraries27#runtime-libraries)) which may not be ideal.

**Comment by alex** [comment]
In theory you could write a `cryptography` backend that used `PyCrypto`, but this is not something we'd ever support natively. Sorry, there's not much we can do about App Engine's limitations.

**Comment by ChrisDenton** [comment]
I suspected as much. Thanks anyway.
