### ISSUE TITLE
Using isinstance(<input>, bytes) won't work in Python 2.x

### ISSUE THREAD

**Issue by mtourne** [pyca/cryptography#2765]
I'm hitting a roadblock using some functions in cryptography which insist that my input be of type 'bytes', which is not possibly in Python 2.7. It can be either 'str' or 'bytearray'.

From the Python 2.7 documentation (5.6 Sequence Types): "There are seven sequence types: strings, Unicode strings, lists, tuples, bytearrays, buffers, and xrange objects."

From the Python 3.2 documentation (5.6 Sequence Types): "There are six sequence types: strings, byte sequences (bytes objects), byte arrays (bytearray objects), lists, tuples, and range objects."

**Comment by alex** [comment]
In Python2 `bytes` is an alias for `str`, this code works fine and is extensively tested.
