### ISSUE TITLE
Add the ability to mark a binding as deprecated

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2785]

**Comment by mriedem** [comment]
+1, the 1.3 release dropped cryptography.x509.load_der_x509_certificate without warning and breaks openstack/glance tests.

**Comment by alex** [comment]
We really didn't. That function exists and works fine.

On Mon, Mar 21, 2016 at 10:59 AM, Matt Riedemann <notifications@github.com>
wrote:

> +1, the 1.3 release dropped cryptography.x509.load_der_x509_certificate
> without warning and breaks openstack/glance tests.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2785#issuecomment-199326563>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by mriedem** [comment]
Yeah, I see that now. For some reason the mock of that is blowing up with an AttributeError when run against cryptography 1.3. sigmavirus24 was looking further.

**Comment by reaperhulk** [comment]
@mriedem There is a bug related to missing `__delattr__` that was just fixed in master: https://github.com/pyca/cryptography/pull/2845 This is likely the source of your problem.

**Comment by reaperhulk** [comment]
We're going to be doing a 1.3.1 with the delattr backport shortly to handle this mocking situation.

**Comment by alex** [comment]
In practice removing bindings is always controlled by the underlying library removing them, in which case there's not much we can do.

Since we generally continue to expose the API when linking against older versions of the library, downstreams remain backwards compatible for those users, and only users on newer versions break. We saw this with pyOpenSSL and OpenSSL 1.1.0.

So there doesn't really seem like there's a lot to fix here.
