### ISSUE TITLE
cryptography 1.3 breaks pyOpenSSL 0.15.1

### ISSUE THREAD

**Issue by cybertron** [pyca/cryptography#2837]
Getting the following traceback when trying to use cryptography 1.3 with pyOpenSSL 0.15.1:

Traceback (most recent call last):
  File "os_cloud_config/tests/test_keystone_pki.py", line 36, in test_create_ca_and_signing_pairs
    self.assertTrue(ca_key.check())
  File "/home/fedora/os-cloud-config/.tox/py27/lib/python2.7/site-packages/OpenSSL/crypto.py", line 243, in check
    if _lib.EVP_PKEY_type(self._pkey.type) != _lib.EVP_PKEY_RSA:
AttributeError: '_cffi_backend.CDataGCP' object has no attribute 'type'

Looks possibly related to https://github.com/pyca/cryptography/commit/8c66f74a94d96b5eae23413118ee0ab05d1a52bc

I'm not sure whether this needs to be fixed in cryptography or pyOpenSSL, but since it was the cryptography release that broke it I'm starting here.

**Comment by reaperhulk** [comment]
This is definitely an issue (we opaqued this struct in 1.2, reverted it in 1.2.1 for pyOpenSSL, but left it opaqued in 1.3). pyOpenSSL master has a fix for this issue, but I'm not sure when @hynek is planning to release. We'll leave this open while we figure out which side is going to do a release to fix this :)

**Comment by hynek** [comment]
16.0 should come ASAP *after* https://github.com/pyca/pyopenssl/pull/422 is merged.

**Comment by glyph** [comment]
Is there a quick workaround here for making `pip install twisted[tls]` work in the interim?

**Comment by hynek** [comment]
pin cryptography to <1.3?  A release should happen as soon ppl to review https://github.com/pyca/pyopenssl/pull/453 and the subsequent release PRs are awake.

**Comment by reaperhulk** [comment]
16.0.0 is now out so the solution is to upgrade. Thanks for the report!
