### ISSUE TITLE
Add functionality to serialize ssh public keys (created with load_ssh_public_key)

### ISSUE THREAD

**Issue by GaretJax** [pyca/cryptography#2851]
`cryptography.hazmat.primitives.serialization.load_ssh_public_key` allows to read OpenSSH public keys, but there is currently no functionality to serialize such a key back to the same format.

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_ssh_public_key

**Comment by reaperhulk** [comment]
This is a dupe of #1744, which is currently in the next milestone. Thanks for letting us know that there's demand for it though!

**Comment by GaretJax** [comment]
Thanks @reaperhulk... I searched for load_ssh_public_key and couldn't find anything. :-)
