### ISSUE TITLE
Uknown hazmat backend issue on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by orion-napofearth** [pyca/cryptography#2853]
I'm getting an error when running a very simple test of Fernet on Ubuntu 12.04 LTS after upgrading from `cryptography 0.9` to `1.3.1`.

Using the sample code found at https://cryptography.io/en/latest/fernet/ I get:

```
(virtualenv)root@web-dev# python
Python 2.7.3 (default, Dec 18 2014, 19:10:20) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.fernet import Fernet
>>> key = Fernet.generate_key()
>>> f = Fernet(key)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/mediagraph/src/web/build/virtualenv/local/lib/python2.7/site-packages/cryptography-1.3.1-py2.7-linux-x86_64.egg/cryptography/fernet.py", line 32, in __init__
    backend = default_backend()
  File "/opt/mediagraph/src/web/build/virtualenv/local/lib/python2.7/site-packages/cryptography-1.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/opt/mediagraph/src/web/build/virtualenv/local/lib/python2.7/site-packages/cryptography-1.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'
>>> 
```

The cryptography egg is built from source on pypi. Any thoughts on what might be going wrong here? Much appreciated.

**Comment by alex** [comment]
How did you install `cryptography`? This error is caused by using an old version of `setuptools`. `pip install cryptography` will install a new version of `setuptools`.

**Comment by orion-napofearth** [comment]
Thanks @alex for the quick response! An old version of setuptools might indeed be the issue. It looks like I have something that is fairly old

```
python -m easy_install --version
distribute 0.6.24
```

Is this dependency something that changed between `cryptography 0.9` and `1.3.1`?

**Comment by alex** [comment]
Yes, it did. It started with cryptography 1.3:
https://github.com/pyca/cryptography/commit/30e199e0fb220a17b3089508a59d29a2924f10e4

On Fri, Mar 25, 2016 at 8:08 PM, Orion Reblitz-Richardson <
notifications@github.com> wrote:

> Thanks @alex <https://github.com/alex> for the quick response! An old
> version of setuptools might indeed be the issue. It looks like I have
> something that is fairly old
>
> python -m easy_install --version
> distribute 0.6.24
>
> Is this dependency something that changed between cryptography 0.9 and
> 1.3.1?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2853#issuecomment-201604276>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by orion-napofearth** [comment]
I verified that after running {{pip install --upgrade distribute}} the test does pass. Unfortunately we do our own python packaging, so I'll need to determine how to exactly get that dependency in. Thank you for your help, though! That was incredibly helpful.

**Comment by ik-grit** [comment]
setuptool appears to be the cause of the issue. this worked for me

wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python

**Comment by fusco** [comment]
thanks @ik-grit , it works like a charm !
