### ISSUE TITLE
Redundant exclude in setup.py's find_packages

### ISSUE THREAD

**Issue by RazerM** [pyca/cryptography#2854]
I think the call can be reduced from 

```python
find_packages(
    where="src", exclude=["_cffi_src", "_cffi_src.*", "tests", "tests.*"]
)
```

to
```python
find_packages(where="src", exclude=["_cffi_src", "_cffi_src.*"])
```

because of the `where="src"`. I verified by printing the output from setup.py

**Comment by reaperhulk** [comment]
Thanks for the report. Would you like to put in a PR to correct this?

**Comment by RazerM** [comment]
Yeah, I'll create a PR shortly.
