### ISSUE TITLE
_key_identifier_from_public_key is pretty slow

### ISSUE THREAD

**Issue by mithrandi** [pyca/cryptography#2856]
Sure, okay, it even has a comment warning about this: https://github.com/pyca/cryptography/blob/master/src/cryptography/x509/extensions.py#L35

I just ran into this in the context of doing some testing; the bulk of the runtime in the test is issuing certificates in my fake CA, as part of that I'm using `SubjectKeyIdentifier.from_public_key` and `AuthorityKeyIdentifier.from_issuer_public_key`; I can cache the latter, but not the former.

**Comment by alex** [comment]
Can you construct a benchmark for this issue that we can work towards optimizing? (A simple script that creates a public key, and then calls `AuthorityKeyIdentifier.from_issuer_public_key` is probably sufficient.

**Comment by mithrandi** [comment]
I couldn't resist getting *slightly* fancy, here's a self-calibrating benchmark::
```python
from __future__ import print_function

import time

from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa


def main():
    key = rsa.generate_private_key(
        public_exponent=65537, key_size=2048, backend=default_backend())

    public_key = key.public_key()
    start = time.time()
    n = 0
    while time.time() < start + 0.1:
        x509.SubjectKeyIdentifier.from_public_key(public_key)
        n += 1
    n *= 50

    start = time.time()
    for _ in xrange(n):
        x509.SubjectKeyIdentifier.from_public_key(public_key)
    end = time.time()
    print((end - start) / n, n)


if __name__ == '__main__':
    main()
```
Results on my desktop machine: ~1.8 ms/call on CPython 2.7.11. (Output values are ms/call, and calls/sec)

**Comment by alex** [comment]
FWIW, it's about 3x faster under PyPy. I'm starting to profile now.

**Comment by alex** [comment]
On PyPy (with the lovely `vmprof` :-)), it's about 50% the stuff in `_key_identifier_from_public_key` and maybe 33% in the `pyasn1` decoding. Very little time in `public_bytes`.

The best solution might be to have a `public_bytes` that goes directly to SPKI as bits, that way we skip the decode phase, and get bytes directly out which can be fed to SHA1. Downside is that it involves exposing vaguely internal details in the public API. What do you think @reaperhulk ?

**Comment by alex** [comment]
http://vmprof.com/#/68579e518cab75db05b7bbdce6fbbc40?id=1,2,0&view=flames is the `vmprof` for pypy btw.
