### ISSUE TITLE
More clearly document the perils of SHA-1

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#2859]
The docs currently tell you it's deprecated by NIST, but we should indicate in more detail the nature of its flaws: https://cryptography.io/en/latest/hazmat/primitives/cryptographic-hashes/#sha-1

**Comment by collisdigital** [comment]
Worth pointing to NIST directly? E.g. http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r4.pdf from Jan-16 shows uses for SHA hashes, including SHA-1. Also generally http://csrc.nist.gov/publications/PubsFIPS.html#fips180-4 

Not sure if these are the latest but it seems they usually put a cover page on docs once they have been archived pointing to newer versions.
