### ISSUE TITLE
ValueError: '\x7f\x00\x00\x01' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by hongbin** [pyca/cryptography#2870]
I ran into a value error: '\x7f\x00\x00\x01' does not appear to be an IPv4 or IPv6 address. Below is the steps to reproduce:

```
$ openssl genrsa -out client.key 4096
$ cat > client.conf << END
[req]
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no
[req_distinguished_name]
CN = Your Name
[req_ext]
extendedKeyUsage = clientAuth
subjectAltName = IP:127.0.0.1
END
$ openssl req -new -days 365 \
    -config client.conf \
    -key client.key \
    -out client.csr
$ cat > test.py << END
from cryptography.hazmat.backends import default_backend
from cryptography import x509

csr_content=None
with open('client.csr', 'r') as f:
    csr_content = f.read()
csr = x509.load_pem_x509_csr(csr_content, backend=default_backend())
csr.extensions
END
$ python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    csr.extensions
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/x509.py", line 364, in extensions
    return _CSR_EXTENSION_PARSER.parse(self._backend, x509_exts)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 240, in parse
    value = handler(backend, ext_data)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 418, in _decode_subject_alt_name
    _decode_general_names_extension(backend, ext)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 412, in _decode_general_names_extension
    general_names = _decode_general_names(backend, gns)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 61, in _decode_general_names
    names.append(_decode_general_name(backend, gn))
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 137, in _decode_general_name
    ip = ipaddress.ip_address(data)
  File "/usr/local/lib/python2.7/dist-packages/ipaddress.py", line 116, in ip_address
    address)
ValueError: '\x7f\x00\x00\x01' does not appear to be an IPv4 or IPv6 address
```

**Comment by alex** [comment]
Can you attach the contents of `client.csr`?

**Comment by hongbin** [comment]
Here you go:

$ cat client.csr
-----BEGIN CERTIFICATE REQUEST-----
MIIEkDCCAngCAQAwFDESMBAGA1UEAxMJWW91ciBOYW1lMIICIjANBgkqhkiG9w0B
AQEFAAOCAg8AMIICCgKCAgEAtTx0Pw9mLHep9o5dkYJe/OQMbN1x4ZXJ2Fyyyvec
gERqxWZgu3HFrEMpTEYzd2uexsz7mEbyKIFPNeWsUQMLvcutjFCgcZpOlrhzySEi
hAo6U8BSPSvtWzX5MGxfiBF0yX/sK30KXMEyY4rHzPvGeig37PK+vBsuB9yylJxT
H0GiriblbAMD0IXtnE0fYGpYDJJTw75ehpngfNoADzMtRaclAvzidKPvLmfrr+r/
+ut7UFVijKKoNncyeG5B47Z7uyVf7NcxkPPZqJEpgRILMx7Mfu40fAUAnUSARShl
MsfgP53Je6GMynNDigbYuxrJDzYAh7kwE2NHctqBCok4gl66nYVk5DDdVibh3NIi
fvXmc7ZeRl9t5eSfcQMtmr1xSmf0bVR2sJUlGnXbXlJ9MADl40MDSkhCT893sgCR
JPiz8vGrCASltp40oUu1yFfwJ7G1/jZA2itvvfy6FR50xEP8nqNvEGLMA1dL0r1d
FDcxG20xIKjnzRI0i9FmzBa0/QFdtzUndkiiOYPVK4AL1EbdQIA81QubwIwEZzUE
FuYO2IlYcwLKh6spYiCa7ilbHdR1nQJ8IvLLS3nETE3Ar2PRA3VKvhpQ39DQerHb
N/kfZ7puyIWpURvAx34dQ4+WZZREh+toMfuw10r3BGYNvbGCg65YBLJEcvmXj2rH
t5kCAwEAAaA3MDUGCSqGSIb3DQEJDjEoMCYwEwYDVR0lBAwwCgYIKwYBBQUHAwIw
DwYDVR0RBAgwBocEfwAAATANBgkqhkiG9w0BAQsFAAOCAgEApENwRGinm8i8cv1l
/TH4NXmq+aMmr95wEWQBZECksZVPhnG/HQmAaoAByZb3+dbAqpkYB5hfn1QrwCik
kuZG6SSMa6fGPmdlp6yW+fgicbuJKw7iagqKN6zkld4Hhgl5427l55qJp3HAzViF
xV4IIM8TiNnidH8lbThnLakpG8/mJWOfq0APaskgk7QZHz0hTkPCrdXK0Z7Shc5w
PDN7mLd02oUBkhUFcy2mDR9CmjIXkpkJ4T/zrO/pzuORR6fni6YEVi6if6cNeNKp
VQG6wI8UWXgHVerlLx10mVigYQNKFRtuo/pvm/Es/Dn/LbZzqlDX3oLtBwodrFsL
Xkn10Me8j+oh4LnuDIr194hWRpN3DxMGiRADX0+Ndl9Xj1H75LfWue6WjMYy09UH
7wMIXub5te5Us0BkWyA/O/XYqql9zXpxwiMRvbi0VRG/AP7P8SK4weP3PCAEE2bC
n5702ktd89WQHzKGjfPDu3NmubTRjg6Ack04kQUBs6qbIHDGg11Jh1BQ2aUHLNaW
Dn2WB62B8y3KsT7jjNmWryD+c/xbWajWGhnErLuMTYsiblULV0K2go59xR7Z0T7P
QN/FXN29NEWnECyfFkUISCqu0OLapiVztPvf1bvYfvbjhgwO5GZOwCkP7gKve8kT
rEH9HFwDBU67i01c0goMN2GDAuQ=
-----END CERTIFICATE REQUEST-----

**Comment by alex** [comment]
This works ok for me, what version of `ipaddress` do you have?

```
>>>> s = """
.... -----BEGIN CERTIFICATE REQUEST-----
.... MIIEkDCCAngCAQAwFDESMBAGA1UEAxMJWW91ciBOYW1lMIICIjANBgkqhkiG9w0B
.... AQEFAAOCAg8AMIICCgKCAgEAtTx0Pw9mLHep9o5dkYJe/OQMbN1x4ZXJ2Fyyyvec
.... gERqxWZgu3HFrEMpTEYzd2uexsz7mEbyKIFPNeWsUQMLvcutjFCgcZpOlrhzySEi
.... hAo6U8BSPSvtWzX5MGxfiBF0yX/sK30KXMEyY4rHzPvGeig37PK+vBsuB9yylJxT
.... H0GiriblbAMD0IXtnE0fYGpYDJJTw75ehpngfNoADzMtRaclAvzidKPvLmfrr+r/
.... +ut7UFVijKKoNncyeG5B47Z7uyVf7NcxkPPZqJEpgRILMx7Mfu40fAUAnUSARShl
.... MsfgP53Je6GMynNDigbYuxrJDzYAh7kwE2NHctqBCok4gl66nYVk5DDdVibh3NIi
.... fvXmc7ZeRl9t5eSfcQMtmr1xSmf0bVR2sJUlGnXbXlJ9MADl40MDSkhCT893sgCR
.... JPiz8vGrCASltp40oUu1yFfwJ7G1/jZA2itvvfy6FR50xEP8nqNvEGLMA1dL0r1d
.... FDcxG20xIKjnzRI0i9FmzBa0/QFdtzUndkiiOYPVK4AL1EbdQIA81QubwIwEZzUE
.... FuYO2IlYcwLKh6spYiCa7ilbHdR1nQJ8IvLLS3nETE3Ar2PRA3VKvhpQ39DQerHb
.... N/kfZ7puyIWpURvAx34dQ4+WZZREh+toMfuw10r3BGYNvbGCg65YBLJEcvmXj2rH
.... t5kCAwEAAaA3MDUGCSqGSIb3DQEJDjEoMCYwEwYDVR0lBAwwCgYIKwYBBQUHAwIw
.... DwYDVR0RBAgwBocEfwAAATANBgkqhkiG9w0BAQsFAAOCAgEApENwRGinm8i8cv1l
.... /TH4NXmq+aMmr95wEWQBZECksZVPhnG/HQmAaoAByZb3+dbAqpkYB5hfn1QrwCik
.... kuZG6SSMa6fGPmdlp6yW+fgicbuJKw7iagqKN6zkld4Hhgl5427l55qJp3HAzViF
.... xV4IIM8TiNnidH8lbThnLakpG8/mJWOfq0APaskgk7QZHz0hTkPCrdXK0Z7Shc5w
.... PDN7mLd02oUBkhUFcy2mDR9CmjIXkpkJ4T/zrO/pzuORR6fni6YEVi6if6cNeNKp
.... VQG6wI8UWXgHVerlLx10mVigYQNKFRtuo/pvm/Es/Dn/LbZzqlDX3oLtBwodrFsL
.... Xkn10Me8j+oh4LnuDIr194hWRpN3DxMGiRADX0+Ndl9Xj1H75LfWue6WjMYy09UH
.... 7wMIXub5te5Us0BkWyA/O/XYqql9zXpxwiMRvbi0VRG/AP7P8SK4weP3PCAEE2bC
.... n5702ktd89WQHzKGjfPDu3NmubTRjg6Ack04kQUBs6qbIHDGg11Jh1BQ2aUHLNaW
.... Dn2WB62B8y3KsT7jjNmWryD+c/xbWajWGhnErLuMTYsiblULV0K2go59xR7Z0T7P
.... QN/FXN29NEWnECyfFkUISCqu0OLapiVztPvf1bvYfvbjhgwO5GZOwCkP7gKve8kT
.... rEH9HFwDBU67i01c0goMN2GDAuQ=
.... -----END CERTIFICATE REQUEST-----
.... """
>>>> from cryptography import x509
>>>> from cryptography.hazmat.backends import default_backend
>>>> c = x509.load_pem_x509_csr(s, default_backend())
>>>> c.extensions
<Extensions([<Extension(oid=<ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)>, critical=False, value=<ExtendedKeyUsage([<ObjectIdentifier(oid=1.3.6.1.5.5.7.3.2, name=clientAuth)>])>)>, <Extension(oid=<ObjectIdentifier(oid=2.5.29.17, name=subjectAltName)>, critical=False, value=<SubjectAlternativeName(<GeneralNames([<IPAddress(value=127.0.0.1)>])>)>)>])>
>>>>
```

**Comment by hongbin** [comment]
`$ pip freeze | grep -i ipaddress
ipaddress==1.0.16
py2-ipaddress==3.4.1
`

**Comment by alex** [comment]
What's `py-ipaddress`? I'd try uninstalling that.

**Comment by mithrandi** [comment]
You will probably need to remove both and then reinstall ipaddress, as the files overlap.

**Comment by alex** [comment]
Yeah, the problem is `py2-ipaddress`:
```
(tempenv-0c57298710d13) ~ $ pip install ipaddress
Collecting ipaddress
Installing collected packages: ipaddress
Successfully installed ipaddress-1.0.16
(tempenv-0c57298710d13) ~ $ python -c "import ipaddress; ipaddress.ip_address('\x7f\x00\x00\x01')"
(tempenv-0c57298710d13) ~ $ pip install py2-ipaddress
Collecting py2-ipaddress
Installing collected packages: py2-ipaddress
Successfully installed py2-ipaddress-3.4.1
(tempenv-0c57298710d13) ~ $ python -c "import ipaddress; ipaddress.ip_address('\x7f\x00\x00\x01')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alex_gaynor/.virtualenvs/tempenv-0c57298710d13/site-packages/ipaddress.py", line 116, in ip_address
    address)
ValueError: '\x7f\x00\x00\x01' does not appear to be an IPv4 or IPv6 address
```

**Comment by hongbin** [comment]
Hi, I wonder if it is possible to make cryptography to be compatible with py2-ipaddress? I am working on OpenStack and we have a big dependency tree. Both cryptography and py2-ipaddress are our important dependency. It is hard to remove one of them. In particular, to remove py2-ipaddress, we need to convince docker-py to remove it, but I believe it is hard since they probably have a good reason to use it....

**Comment by mithrandi** [comment]
The `py2-ipaddress` backport is not API compatible with the stdlib `ipaddress` module (the `ip_address` function needs to be passed `bytearray` instead of `bytes` for packed addresses). As a result, having py2/py3 compatible code that relies on `py2-ipaddress` is quite challenging.

I glanced briefly at `docker-py` and they're only ever passing unpacked addresses, for which they use `six.text_type`, so I think they could use the `ipaddress` backport instead of the `py2-ipaddress` backport without any changes.
