### ISSUE TITLE
Having trouble with pip install cryptography

### ISSUE THREAD

**Issue by mrbm** [pyca/cryptography#2872]
Having some strange errors that are blocking me from installing cryptography
Basic set up:
ubuntu 14.04LTS, openSSL 1.0.1f
build-essential is already the newest version.
python-dev is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.

extra 4gig for a swap file.

Now when running: pip install cryptography

I get the following:

```
Collecting cryptography
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached cryptography-1.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography)
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_9eeE3/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpXsf2kgpip-wheel- --python-tag cp27:
```

Output from the command seems normal until getting to the following:

```
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files matching '*' found under directory 'vectors'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
  creating build/temp.linux-x86_64-2.7
  generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
  generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
  building '_openssl' extension
  creating build/temp.linux-x86_64-2.7/build
  creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
  x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
  Please submit a full bug report,
  with preprocessed source if appropriate.
  See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
  
  ----------------------------------------
  Failed building wheel for cryptography
```

Any ideas? Did a new ubuntu package in the last couple days possible create a conflict? I seemed to not be having issues a couple days ago.

Thoughts? Thanks

**Comment by alex** [comment]
Do you have the latest version of GCC (`apt-get update && apt-get upgrade`)?

On Thu, Apr 14, 2016 at 2:46 PM, mrbm <notifications@github.com> wrote:

> Having some strange errors that are blocking me from installing
> cryptography
> Basic set up:
> ubuntu 14.04LTS, openSSL 1.0.1f
> build-essential is already the newest version.
> python-dev is already the newest version.
> libffi-dev is already the newest version.
> libssl-dev is already the newest version.
>
> extra 4gig for a swap file.
>
> Now when running: pip install cryptography
>
> I get the following:
>
> Collecting cryptography
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   SNIMissingWarning
> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning
>   Using cached cryptography-1.3.1.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)
> Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography)
> Building wheels for collected packages: cryptography
>   Running setup.py bdist_wheel for cryptography ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_9eeE3/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpXsf2kgpip-wheel- --python-tag cp27:
>
> Output from the command seems normal until getting to the following:
>
>   warning: manifest_maker: standard file '-c' not found
>
>   reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
>   reading manifest template 'MANIFEST.in'
>   no previously-included directories found matching 'docs/_build'
>   warning: no previously-included files matching '*' found under directory 'vectors'
>   writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
>   running build_ext
>   generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
>   creating build/temp.linux-x86_64-2.7
>   generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
>   generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
>   building '_openssl' extension
>   creating build/temp.linux-x86_64-2.7/build
>   creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
>   x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
>   x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
>   Please submit a full bug report,
>   with preprocessed source if appropriate.
>   See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
>
>   ----------------------------------------
>   Failed building wheel for cryptography
>
> Any ideas? Did a new ubuntu package in the last couple days possible
> create a conflict? I seemed to not be having issues a couple days ago.
>
> Thoughts? Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2872>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by mrbm** [comment]
I did run that yesterday, and just did (apt-get update && apt-get upgrade) just in case. All up to date.

**Comment by alex** [comment]
Not sure what to say, if your GCC is crashing that's a GCC bug not a
cryptography bug. The fact that we haven't seen a ton of reports of this on
a relatively common platform means it's probably _somehow_ specific to your
machine, though I have no idea how.

On Thu, Apr 14, 2016 at 2:56 PM, mrbm <notifications@github.com> wrote:

> I did run that yesterday, and just did (apt-get update && apt-get upgrade)
> just in case. All up to date.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2872#issuecomment-210099214>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by mrbm** [comment]
Okay thanks. Even though I set the swap size to 4 gigs, I'm going to try an increase the memory on the machine. I'll write back.

**Comment by mrbm** [comment]
So increasing the servers ram (its a digital ocean box) did the trick. What's weird is that I had performed the same commands 3 days ago on a box with the same amount of ram without issue. So I guess some of the new things have eaten up the ram and have now increased the min requirements.

Thanks for writing back so quick.

**Comment by alex** [comment]
No problem. We've got an open issue for decreasing RAM usage #2509.

**Comment by mrbm** [comment]
Again appreciate the fast feeback! Glad the ram ussage is being looked into, hope its resolved soon. This is a dependency for the letsencrypt.  Am I wrong in thinking this could be a pretty serious issue, for example...people use lets encrypt on their server. Its free, so expect it to be used on a lot of servers that don't have a ton of ram. At first seems to be working, but part of the set up many people will do is creating a cron job that runs every week to check if the 90 day expiration is nearing. It gets near that 90 day, then does its upgrade routines with the dependancies requiring more ram, then... re-getting of the certificates fails and then surprise! All the SSL is ruined on the server.

**Comment by jklance** [comment]
Ironically, the use case describe by mrbm above is what brought me here looking for a solution to exactly this problem!

**Comment by reaperhulk** [comment]
:( Sorry about that. We're dependent on potential improvements in cffi to fix RAM usage, although we're also investigating delivering binary wheels for linux which would remove the entire compilation step. There are some challenges associated with that path though, so there's no concrete timeline as yet.

**Comment by jklance** [comment]
Oh, no worries; now that I have a solution in-hand, I was able to move forward with my task--I was more sharing my amusement that mrbm's proposed use case is, as it turns out, exactly spot-on :)

**Comment by mrbm** [comment]
@reaperhulk god speed...danger danger
