### ISSUE TITLE
__hash__() missing on EllipticCurvePublicNumbers and EllipticCurvePrivateNumbers

### ISSUE THREAD

**Issue by ned14** [pyca/cryptography#2887]
RSAPublicNumbers implements \__hash__:

    def __hash__(self):
        return hash((self.e, self.n))

Why doesn't EllipticCurvePublicNumbers and EllipticCurvePrivateNumbers similarly implement \__hash__?

**Comment by reaperhulk** [comment]
That's an oversight. If you'd like to contribute a PR we'll be happy to review!
