### ISSUE TITLE
 Add support for Elliptic Curve Points Compact Representation

### ISSUE THREAD

**Issue by marcogiglio** [pyca/cryptography#2893]
I was surprised to see that the library doesn't support the EC point compact representation for patents reasons, as claimed here https://github.com/pyca/cryptography/issues/2346. If you read the patent linked, it instead refers to a different scheme of compression, where only one of the point is transmitted with no additional bit from the other.
The compact representation defined [here](http://tools.ietf.org/html/rfc6090#appendix-C) has been public domain for more than 30 years, since it was presented in the 1985 paper by Millers [Use of Elliptic Curves in Cryptography](http://link.springer.com/chapter/10.1007%2F3-540-39799-X_31#page-1).  In general, it has growing support in software: for example, node crypto module supports it by default and so does most of Bitcoin/crypto-currencies related software. 
I noticed the lack of this feature because I need this for reducing the on-chain size of some encrypted data for an Ethereum smart contract. Is it a feasible feature to have not to far in the future?

**Comment by alex** [comment]
It's technically possible, but I don't think we have any current plans to implement this, protocol usage of compressed points is relatively rare (except X25519, which needs a different API anyways).

If you were interested in contributing a patch, we'd certainly review it.

**Comment by earonesty** [comment]
For now, @marcogiglio you can use the "coincurve" library if you're using secp256k1.     Also, you could probably modify this library a bit to do what you need: https://github.com/tuxxy/hazmat-math/blob/master/hazmat_math/operations.py

**Comment by earonesty** [comment]
See: https://github.com/pyca/cryptography/pull/4419

**Comment by reaperhulk** [comment]
This is now done and will be in the 2.5 release
