### ISSUE TITLE
make specific doc versions available on RtD

### ISSUE THREAD

**Issue by whit537** [pyca/cryptography#2897]
I find myself wanting to permalink to specific versions of `cryptography`'s docs, but I don't see that these are available, only `latest` and `stable`:

![screen shot 2016-05-04 at 6 20 01 pm](https://cloud.githubusercontent.com/assets/134455/15031185/da6dfbde-1224-11e6-9ec3-cfb1d35b1344.png)

I can link to specific doc versions on GitHub, but it'd be nice to use https://cryptography.io/.

**Comment by reaperhulk** [comment]
We've traditionally considered our docs evergreen and we note differences between versions with the rst identifiers `versionchanged` and `versionadded`. Closing since we're not likely to change this approach in the absence of a compelling counterargument.
