### ISSUE TITLE
migrate the security program to HackerOne

### ISSUE THREAD

**Issue by whit537** [pyca/cryptography#2898]
Right now `cryptography`'s [security program](https://github.com/pyca/cryptography/blob/1.3.2/docs/security.rst#reporting-a-security-issue) is to email `alex.gaynor@gmail.com`. That's suboptimal because it makes @alex a bottleneck and it makes security issues difficult to track.

Over in @Gratipay we've had [a good experience](https://gratipay.news/transparent-security-c864d03d6f60) with [HackerOne](https://hackerone.com/). I believe Django has some [experience](https://hackerone.com/django) with it as well (ya)?

I propose using HackerOne for PyCA's security program instead of Alex's Gmail. :)

**Comment by alex** [comment]
@reaperhulk This sounds pretty reasonable to me, what do you think?

**Comment by alex** [comment]
Ok, in progress of migrating. HackerOne's UX causes this to take a while. Closing this now.
