### ISSUE TITLE
better specify Fernet version

### ISSUE THREAD

**Issue by whit537** [pyca/cryptography#2899]
The `cryptography` docs [link](https://github.com/pyca/cryptography/blob/1.3.2/docs/fernet.rst#implementation) to the `master` branch of the Fernet spec, which is a mutable resource, a moving target. The version number [advertised](https://github.com/fernet/spec/blob/0250c594a266036afb39aa574b88d9283810be47/Spec.md) by Fernet on the current `master`,  0x80, is [ambiguous](https://github.com/fernet/spec/issues/14). The `cryptography` [source](https://github.com/pyca/cryptography/blob/1.3.2/src/cryptography/fernet.py) gives no direct indication as to what version it implements.

What precise version of Fernet does `cryptography` implement?

**Comment by alex** [comment]
Cryptography implements the only version of fernet that exists in real life. Though you've noted that in theory some ambigiuty exists, in reality I have never seen any confusion about this, and all the fernet libraries in various langauges implement the same standard.
