### ISSUE TITLE
Expose extension data for UnsupportedExtension

### ISSUE THREAD

**Issue by rudolphfroger** [pyca/cryptography#2901]
Hi,
When a critical unrecognized extension is found in a certificate a UnsupportedExtension is raised. This exception holds the OID but not the extension data. I'd like to parse this unrecognized extension data myself but can't access it by catching the exception. Would it be acceptable to also encapsulate the extension data in the UnsupportedExtension exception?

Thanks, Rudolph

**Comment by rudolphfroger** [comment]
BTW, I'll happily write a pull request if that will help

**Comment by reaperhulk** [comment]
Attach it to the exception? That seems like a good approach. Our goal with raising the exception is to comply with the spirit of RFC 5280, which says:
```
A certificate-using system MUST reject the certificate if it encounters
a critical extension it does not recognize or a critical extension
that contains information that it cannot process.
```

Raising the exception but dropping the ASN.1 encoded data in it would allow users of this library to catch and process such extensions properly (or not catch them and by default the parser will fail appropriately).

So yes, please do submit a PR! If you haven't yet, take a quick glance at our [submitting patches](https://cryptography.io/en/latest/development/submitting-patches/) documentation to avoid some of the common pitfalls for new contributors.

**Comment by rudolphfroger** [comment]
Thanks, hopefully my PR complies with your policies.
