### ISSUE TITLE
set up a "meta" repo

### ISSUE THREAD

**Issue by whit537** [pyca/cryptography#2904]
Reticketing from https://github.com/pyca/cryptography/issues/2902#issuecomment-217587804 ...

I appreciate the work you all are doing in the (self-appointed, and only *mostly* tongue-in-cheek) "Python Cryptographic Authority." [Afaict](https://github.com/gratipay/gratipay.com/pull/3998#issuecomment-217597420), your code and documentation quality is _way_ better than the alternatives, and you _seem_ to be making good decisions for the rest of us. I would trust you even more if I saw a little more formal accountability, e.g., some sort of documented policy about what gets discussed and decided where ("the public record may not reflect the consensus of the project" doesn't sound right), the process for becoming a member of the Authority, perhaps even a more formal relationship with the PSF, etc. You've got the bureaucracy dial turned a *little* too low for my tastes.

Some sort of "meta" repo could be a good next step. Issues such as https://github.com/pyca/cryptography/issues/2161 demonstrate the need: "I'd also like to consider adopting this across PyCA entirely."

**Comment by whit537** [comment]
#2898 would also fit better in a pyca/pyca repo, since it's scoped to PyCA.

**Comment by alex** [comment]
No plans to do this.
