### ISSUE TITLE
Missing symbol on El Capitan OS X 10.11.4

### ISSUE THREAD

**Issue by mdsrosa** [pyca/cryptography#2906]
```
$ python django/app/manage.py runserver --settings=settings.guilherme
File "/Users/guilhermediego/workspace/api/django/app/records/models.py", line 18, in <module>
    from util.crypto import get_key, encrypt, decrypt
  File "/Users/guilhermediego/workspace/api/django/app/util/crypto.py", line 3, in <module>
    from cryptography.fernet import Fernet
  File "/Users/guilhermediego/.virtualenvs/api/lib/python2.7/site-packages/cryptography/fernet.py", line 17, in <module>
    from cryptography.hazmat.primitives import hashes, padding
  File "/Users/guilhermediego/.virtualenvs/api/lib/python2.7/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: dlopen(/Users/guilhermediego/.virtualenvs/api/lib/python2.7/site-packages/_cffi_backend.so, 2): Symbol not found: _PyUnicodeUCS2_AsASCIIString
  Referenced from: /Users/guilhermediego/.virtualenvs/api/lib/python2.7/site-packages/_cffi_backend.so
  Expected in: flat namespace
 in /Users/guilhermediego/.virtualenvs/api/lib/python2.7/site-packages/_cffi_backend.so
```

Looks like `_PyUnicodeUCS2_AsASCIIString` symbol is missing

**Comment by reaperhulk** [comment]
This is a python ucs2 vs ucs4 compile issue with cffi. How did you compile your Python? (You're ucs4 which isn't wrong, just curious how you obtained it)

**Comment by matheus-iclinic** [comment]
@reaperhulk Python was first installed using homebrew `brew install python` which installed Python 2.7.11, then I installed `pyenv` to manage multiple versions and installed `Python 2.7.10` and `Python 3.5.1`. The error occurs when running with Python 2.7.10.

**Comment by mdsrosa** [comment]
@reaperhulk Python was first installed using homebrew brew install python which installed Python 2.7.11, then I installed pyenv to manage multiple versions and installed Python 2.7.10 and Python 3.5.1. The error occurs when running with Python 2.7.10.

**Comment by reaperhulk** [comment]
Thanks @mdsrosa. I've confirmed that pyenv also builds UCS4 now. To resolve this we need to push up some cffi ucs4 wheels. I'm going to be modifying our build systems to produce both ucs2 and ucs4 wheels so that users will be able to pull the correct one. Unfortunately users on out of date pip will still pull the wrong one (as pip prior to that is unaware of the proper tag), but we can add some information to explain that upgrading to pip8+ will fix the issue.

**Comment by reaperhulk** [comment]
I have expanded the build matrix for both cryptography and cffi to add ucs4 2.7 wheels on OS X. pip install should now work without issue.
