### ISSUE TITLE
Generated CFFI code produces an always true comparison

### ISSUE THREAD

**Issue by npmccallum** [pyca/cryptography#2908]
CFFI generates the following:

    static int _cffi_const_ENGINE_METHOD_NONE(unsigned long long *o)
    {
      int n = (ENGINE_METHOD_NONE) <= 0;
      *o = (unsigned long long)((ENGINE_METHOD_NONE) << 0);  /* check that ENGINE_METHOD_NONE is an integer */
      return n;
    }

The first comparison is always true. This issue was picked up by a Coverity scan. If you wish to ignore the issue, I'm fine with that. I only want to bring it to your attention in case it might introduce a subtle bug.

**Comment by alex** [comment]
I don't think there's any problem here, it's just how CFFI generates this code.
