### ISSUE TITLE
Add support for JSON Web Encryption (JWE) to hazmat layer

### ISSUE THREAD

**Issue by collisdigital** [pyca/cryptography#2912]
As recently discussed in #2900 this issue can be used to track progress against adding support for JWE (https://tools.ietf.org/html/rfc7516) to the hazmat layer.

JWE is independently implementable from JWS (https://tools.ietf.org/html/rfc7515) and JWT (https://tools.ietf.org/html/rfc7519) - which can be used as payloads within a JWE.

**Comment by collisdigital** [comment]
I've raised this for JWE based on the thinking that JWS/T could be discussed as separate issues (later?) but if you think its better to do it as one issue now I can rename/update this one to cover all three.

**Comment by collisdigital** [comment]
My first question is where JWE would sit in cryptography, none of the hazmat modules 'backends', 'bindings' and 'primitives' seem appropriate, would this be a new layer?

**Comment by tiran** [comment]
My colleague @simo5 has developed https://jwcrypto.readthedocs.io/ . It uses cryptography internally.

**Comment by collisdigital** [comment]
@tiran @simo5; @reaperhulk had suggested that folding another project into cryptography may be preferable to starting from scratch for JW(S,E,T), is it something you'd be interested in? I'm not a maintainer here I'm just getting the options on the table for discussion so I don't know if jwcrypto would be an acceptable choice or how compatible it is with this project (that will be up to the cryptography team to decide).

**Comment by simo5** [comment]
@collisdigital funny you ask that, I already offerd @reaperhulk in the past to fold jwcrypto in, if he is interested :)
That said, JWE clearly is not hazmat, as it sits on top of primitives.
It may be in cryptography or may just be a sister project like pyopenssl, not for me to decide, but I am interested in merging in my project if thre is interest. I would hate to have Yet another implementation of the same stuff and waste resources.

**Comment by reaperhulk** [comment]
@simo5 I think I've been convinced (both by our conversations in the past and #2900) that it makes sense for it to live in cryptography now. Due to the number of possible algorithm choices (and the complexity of knowing which ones might be non-optimal) I'm not a big fan of it living at the recipe layer though. I would, however, like to hear @alex's input since he may agree or disagree.

**Comment by alex** [comment]
If you're going to offer an API with dozens of choices, it's got to be
primitives.

Alex

On Mon, May 16, 2016 at 11:03 AM, Paul Kehrer <notifications@github.com>
wrote:

> @simo5 <https://github.com/simo5> I think I've been convinced (both by
> our conversations in the past and #2900
> <https://github.com/pyca/cryptography/issues/2900>) that it makes sense
> for it to live in cryptography now. Due to the number of possible algorithm
> choices (and the complexity of knowing which ones might be non-optimal) I'm
> not a big fan of it living at the recipe layer though. I would, however,
> like to hear @alex <https://github.com/alex>'s input since he may agree
> or disagree.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2912#issuecomment-219448693>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by alex** [comment]
We've decided this isn't a great fit for pyca/cryptography, however we encourage people to use the `josepy` package from the Let's Encrypt team if they need this family of standards.
