### ISSUE TITLE
Unnecessary setuptools version bump breaks package dependencies

### ISSUE THREAD

**Issue by offero** [pyca/cryptography#2918]
We are using an older version of Scrapy that cannot be installed using a newer version of setuptools because the expected package structure has been changed. In short, it doesn't package data files the same as it used to. We have a hard stop on setuptools 5.8 right now because of it. We are working to bump the package, but dealing with legacy code is not so straight forward. PyOpenSSL depends on recent versions of cryptography and cryptography now depends on Setuptools 11.3. Thus, we will have to put a hard limit on both packages for the moment and miss updates to PyOpenSSL or cryptography. If the 1 line change is the only reason to update setuptools, I request that you revert the commit.

Commit: 30e199e0fb220a17b3089508a59d29a2924f10e4
https://github.com/pyca/cryptography/commit/30e199e0fb220a17b3089508a59d29a2924f10e4#commitcomment-17603088

**Comment by alex** [comment]
Is this an issue with recent releases of Scrapy, or only older releases?

On Wed, May 25, 2016 at 12:25 PM, Chris <notifications@github.com> wrote:

> We are using an older version of Scrapy that cannot be installed using a
> newer version of setuptools because the expected package structure has been
> changed. In short, it doesn't package data files the same as it used to. We
> have a hard stop on setuptools 5.8 right now because of it. We are working
> to bump the package, but dealing with legacy code is not so straight
> forward. PyOpenSSL depends on recent versions of cryptography and
> cryptography now depends on Setuptools 11.3. Thus, we will have to put a
> hard limit on both packages for the moment and miss updates to PyOpenSSL or
> cryptography. If the 1 line change is the only reason to update setuptools,
> I request that you revert the commit.
>
> Commit: 30e199e
> <https://github.com/pyca/cryptography/commit/30e199e0fb220a17b3089508a59d29a2924f10e4>
> 30e199e#commitcomment-17603088
> <https://github.com/pyca/cryptography/commit/30e199e0fb220a17b3089508a59d29a2924f10e4#commitcomment-17603088>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pyca/cryptography/issues/2918>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by offero** [comment]
Older releases. I believe they have since changed their package structure and use of setup.py

**Comment by alex** [comment]
How old a release are we talking about? I'm disinclined to drop this forward motion for an old package which was relying on a setuptools bug.

**Comment by reaperhulk** [comment]
@offero Could you give us a few details on why you need an older scrapy combined with the latest cryptography? Since new scrapy + new cryptography works I'm not sure why we need to make a change here.

**Comment by offero** [comment]
We are still using 0.16.4 of Scrapy. We have a little effort to put into upgrading from it. It's on my todo list and a high priority, but for the moment we are stuck.

**Comment by offero** [comment]
@reaperhulk If we upgrade PyOpenSSL for other requirements, it requires a later version of cryptography, which requires a later version of setuptools.

**Comment by alex** [comment]
Your best bet would be to run a small local fork, or use an older version of pyOpenSSL, we're not going to make this change for such an old platform with extremely limited use.

**Comment by offero** [comment]
Ok. Thanks for the consideration.

**Comment by danielkza** [comment]
This causes real annoyance when deploying to Ubuntu 14.04, which has setuptools 3.3. Installation of `cryptography` seems to succeeded, but fails at runtime when running Ansible. Replacing the packaged version of setuptools is an inconvenience that I would rather not have.

**Comment by reaperhulk** [comment]
Due to various issues this has been reverted as of https://github.com/pyca/cryptography/commit/a5865d9b630df7586785b683ed145b977ad7e0c4

It will appear in the next cryptography release (either 1.5.1 or 1.6)
