### ISSUE TITLE
AES GCM code sample in documentation is invalid

### ISSUE THREAD

**Issue by PimvanderEijk** [pyca/cryptography#2923]
The example for https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/

claims to return:

_a secret message!_

But instead returns:

_NameError: name 'key' is not defined_

**Comment by alex** [comment]
You need to provide your own `key` variable, as documented with `AES`.

**Comment by PimvanderEijk** [comment]
Yes that is obvious but the documentation claims this is an example that 
can be run to generate a particular output, whereas it generates an 
exception.
