### ISSUE TITLE
Heavy use of isinstance introduces significant performance penalty

### ISSUE THREAD

**Issue by chschmitt** [pyca/cryptography#2931]
I am currently writing a custom library for token generation and verification (very much like fernet). Since the encrypted payload is quite short (at most a few hundred bytes), I ran a quick benchmark and profiling to see how many cycles of generation and verification can be done per second. I noticed that about 12% of the time are spent in `isinstance` checks, most of them originating from cryptography's constructors, but also from `update` methods.

For each encryption/signature and decryption/verfication, I create and use a `modes.CBC`, a `ciphers.Cipher`, a `padding.PKCS7`, a `hmac.HMAC` and a `hashes.SHA256`. `encryptor()` and `decryptor()` are called respectively. So, for each cycle, there are 12 constructor or factory method calls. In comparison to that, there are about 40 `isinstance` calls per cycle. 

![profile](https://cloud.githubusercontent.com/assets/16899624/15646544/7ae2923a-265e-11e6-8ebd-0327243dd6af.png)

**Comment by reaperhulk** [comment]
This is probably going to be a challenging thing to resolve. These isinstance checks are used to be able to provide useful error msgs without going several functions deeper into the stack before blowing up with an inscrutable exception. :(

**Comment by alex** [comment]
Unless there's a specific thing we can optimize here, I'm going to close this. PyPy happily removes this overhead, and there's not much we can do about the fact that CPython doesn't, without compormising on UX.
