### ISSUE TITLE
openssl.c:423:27: fatal error: openssl/e_os2.h: No such file or directory

### ISSUE THREAD

**Issue by djc** [pyca/cryptography#2941]
See https://bugs.gentoo.org/show_bug.cgi?id=584806. This happened with 1.3.1.

Any suggestions?

**Comment by alex** [comment]
I'm pretty sure the answer is to upgrade to 1.3.2, but I'm falling asleep. Will look in the morning.

**Comment by reaperhulk** [comment]
Yes, this is an issue with LibreSSL and was resolved in 1.3.2.
