### ISSUE TITLE
Add OPENSSL_config binding

### ISSUE THREAD

**Issue by agladkov** [pyca/cryptography#2972]
By default openssl does not load config, so there are no ability to use additional engine like "gost".
Need to call `OPENSSL_config(NULL)` or build bindings with `OPENSSL_LOAD_CONF` defined ([man OPENSSL_config](https://www.openssl.org/docs/manmaster/crypto/OPENSSL_config.html))

**Comment by reaperhulk** [comment]
We're happy to take a PR for this. `OPENSSL_config` has been deprecated in 1.1.0 but is still present so we can add this binding while preserving compatibility.

**Comment by agladkov** [comment]
Since 1.1.0 there are `OPENSSL_init_crypto` for this purpose.
I'll prepare PR for `OPENSSL_config` and check existed PR for 1.1.0 (#2826)
