### ISSUE TITLE
Add a new recipe for CA/PKI

### ISSUE THREAD

**Issue by derwolfe** [pyca/cryptography#2975]
I'd like to propose that a new CA/PKI module be added to the recipes in `cryptography`. The module would be responsible for most of the functionality that the [easyrsa](https://github.com/OpenVPN/easy-rsa) project currently provides.

I've recently been working with easyrsa, and while it works well for its intended purpose, it would be nice to have a python interface available, instead of needing to shell out to a command line utility. 
In my opinion, this fits `cryptography`'s problem domain well. Such a module could provide another opinionated API, that would, by default, do the right things when setting up a CA.

As far as features are concerned, my recent experience suggests that the following functionality would provide a useful starting point:

1. Generate the keys and certificates needed to build a CA
2. Issue client and server certificates with or without passwords using a previously generated CA
3. Revoke certificates issued from a previously generated CA
4. Generate certificate revocation lists from a previously generated CA
5. Generate certificate signing requests for a previously generated CA

Does this seem like a feature you'd like `cryptography` to provide, or would you rather it lived in a separate third-party project?

Also, I fully intend on working on this, whether it lives in `cryptography` or not :).

Thanks!

**Comment by reaperhulk** [comment]
Do you envision this as a simplistic but easy to use PKI for devs or a broader tool capable of meeting the needs of organizations that need to operate internal (or perhaps even globally rooted) CAs?

The latter is a more challenging goal, but I think building a tool an "easy tool for devs" will result in major limitations in its capabilities. I think this makes the most sense as a separate project outside of the PyCA org. Eventually we might want to pull it in but I don't want to commit the whole of PyCA to maintenance of a project like this until after it has demonstrated some value and traction.

**Comment by reaperhulk** [comment]
(I am willing to spend time on this as well. I'd like to believe I've learned some lessons from building this exact tool in other languages.)

**Comment by derwolfe** [comment]
> Do you envision this as a simplistic but easy to use PKI for devs or a broader tool capable of meeting the needs of organizations that need to operate internal (or perhaps even globally rooted) CAs?

My initial goal is for this to be a simpler PKI tool for devs that can be used as a python package. My use case at the moment is that I'm spinning up infrastructure that uses mutually authenticated TLS and I'd like to automate the creation of both the CA and the client and server certificates used by the applications under test.

It sounds like the best way forward is for this to live in a separate project that consumes cryptography. 

Thanks for you feedback :)
