### ISSUE TITLE
Padding argument for modes that require padding

### ISSUE THREAD

**Issue by palaviv** [pyca/cryptography#2981]
Currently when you are using a symmetric encryption with a mode that require padding your code will look something like this:

```py
import os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding

backend = default_backend()
key = os.urandom(32)
iv = os.urandom(16)
secret_data = b"secret"

padder = padding.PKCS7(128).padder()
padded_data = padder.update(secret_data) + padder.finalize()


cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=backend)
encryptor = cipher.encryptor()
ciphertext = encryptor.update(padded_data) + encryptor.finalize()
```

I would like to suggest that when a mode require padding you will be able to pass a padding object to the mode object and it will be used automatically in the encryption / decryption. The same example will look like this:
```py
import os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding

backend = default_backend()
key = os.urandom(32)
iv = os.urandom(16)
secret_data = b"secret"

cipher = Cipher(algorithms.AES(key), modes.CBC(iv, padding=padding.PKCS7(128)), backend=backend)
encryptor = cipher.encryptor()
ciphertext = encryptor.update(secret_data) + encryptor.finalize()
```

**Comment by palaviv** [comment]
Are there any rejections for this feature? If not I will start working on a PR to implement this.

**Comment by alex** [comment]
Ugh, sorry we lost track of this issue. We considered this API a long time ago, but ultimately decided that we wanted them to be independently composable, for me the reasoning behind that hasn't changed -- @reaperhulk you?

**Comment by reaperhulk** [comment]
I sympathize with the desire to reduce boilerplate, but I agree with Alex on this.
