### ISSUE TITLE
rsa.rsa_recover_prime_factors() should return p > q

### ISSUE THREAD

**Issue by djc** [pyca/cryptography#2990]
The documentation for `rsa_recover_prime_factors()` warns that it returns `p` and `q` such that `p < q`. However, things like OpenSSL and BoringSSL seem to require that `p > q`. Given this, would it be feasible to change the order around in cryptography so that it lines up with OpenSSL?

See also: http://crypto.stackexchange.com/questions/18084/in-rsa-why-does-p-have-to-be-bigger-than-q-where-n-p-times-q. @briansmith can provide more commentary if needed.

**Comment by briansmith** [comment]
I think OpenSSL and BoringSSL do accept the keys with `p` < `q`, but some software doesn't work (as well) with them currently. As noted in the linked-to documentation above, retyurning a key with `p` < `q` is more consistent with OpenSSL and so things are more likely to interoperate better. And, it's an easy thing to do.

**Comment by reaperhulk** [comment]
I have no objection to swapping them. I don't think I'd even consider this to be a change that would require a deprecation/new function. If you'd like to submit a PR to swap them (and update the docs) I'll be happy to review.

**Comment by djc** [comment]
To play devil's advocate, the documentation is very explicit about `p < q`. What if someone read this and choose to fix it up by swapping `p` and `q`?

**Comment by djc** [comment]
See #3010 for an attempt at a PR.
