### ISSUE TITLE
Expose actual salt_length if padding.PSS.MAX_LENGTH is used

### ISSUE THREAD

**Issue by joernheissler** [pyca/cryptography#3008]
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/  suggests to use salt_length=padding.PSS.MAX_LENGTH for signing with PSS padding.
To verify a signature, the salt_length must be known and cannot be determined from the signature.

Assuming in the verifier that the signer used MAX_LENGTH is not a proper solution as the signer is free to use different salt lengths. Some implementations may not even support the MAX_LENGTH feature, e.g. I couldn't find anything in BouncyCastle so far.

RFC3447 which specified the PSS algorithm also specifies an ASN.1 structure "RSASSA-PSS-params" for use in the "AlgorithmIdentifier" structure. It contains the parameters used for creating the signature, including the salt length.

I think we need a way to expose the result of _get_rsa_pss_salt_length to the user when creating a signature.
Alternatively, remove padding.PSS.MAX_LENGTH and add a function which computes this value so the user can pass the result back with the salt_length parameter.

**Comment by reaperhulk** [comment]
`rsa.calculate_max_pss_salt_length(key, hash_algorithm)` would do this. Takes the key object and an instance of the hash algorithm and returns an integer. We can then switch the OpenSSL backend to using it.

**Comment by alex** [comment]
that sounds ok to me

**Comment by AbhishekVijayan** [comment]
Is the salt length determined using **salt_length=padding.PSS.MAX_LENGTH** in bits or bytes?

**Comment by reaperhulk** [comment]
Bytes (we'd happily merge a PR that makes that clear)
