### ISSUE TITLE
Retrieving the signature algorithm name

### ISSUE THREAD

**Issue by martenlehmann** [pyca/cryptography#3009]
When looking into the details of a certificate, I'm used to see a signature algorithm name like `sha256WithRSAEncryption` with `openssl x509 -noout -text` or `SHA-256 with RSA Encryption` when looking at it with Chrome.  Both versions are just a representation of the OID `1.2.840.113549.1.1.11`, i.e. a combination of the signing algorithm and the hash algorithm.

With the `x509.signature_hash_algorithm` property I can access the hash algorithm of the certificate, yet I can't find an easy way to access the signing algorithm as well.

The `x509.oid.SignatureAlgorithmOID` class defines several constants, e.g.

```python
RSA_WITH_SHA256 = ObjectIdentifier("1.2.840.113549.1.1.11")
```

and the `x509.oid` module defines a dictionary of `_OID_NAMES`, e.g.

```python
SignatureAlgorithmOID.RSA_WITH_SHA256: "sha256WithRSAEncryption"
```

So basically, this information is incorporated into the cryptography library already.

Due to the nature of the dictionary `x509.oid._SIG_OIDS_TO_HASH`, e.g.

```python
SignatureAlgorithmOID.RSA_WITH_SHA256.dotted_string: hashes.SHA256(),
SignatureAlgorithmOID.ECDSA_WITH_SHA256.dotted_string: hashes.SHA256(),
SignatureAlgorithmOID.DSA_WITH_SHA256.dotted_string: hashes.SHA256()
```

the signing algorithm gets lost, so `x509.signature_hash_algorithm` only returns to the hash algorithm (as the property name suggests). Once I retrieved the signature algorithm OID on my own, I can retrieve the name with

```python
x509.oid._OID_NAMES[x509.oid.ObjectIdentifier('1.2.840.113549.1.1.11')]
```

as well. So if there was a function similar to `x509.signature_hash_algorithm` returning

```python
x509.oid._OID_NAMES[oid]
```

rather than

```python
x509._SIG_OIDS_TO_HASH[oid]
```

I'd be happy. :) I don't want to mess up the currently very clean interface though, so maybe there's a simpler way to retrieve the same information that I missed somehow?

**Comment by reaperhulk** [comment]
You can obtain the sum of that data by looking at the type of the public key object + `signature_hash_algorithm` right now. Is there a specific reason you need the OID itself? I suppose the requirement to do `isinstance(cert.public_key(), RSAPublicKey)` is itself inelegant.

**Comment by alex** [comment]
Err, that's not correct, you need the issue's public key, rigth?

On Tue, Jun 21, 2016 at 9:13 AM, Paul Kehrer <notifications@github.com>
wrote:

> You can obtain the sum of that data by looking at the type of the public
> key object + signature_hash_algorithm right now. Is there a specific
> reason you need the OID itself? I suppose the requirement to do isinstance(cert.public_key(),
> RSAPublicKey) is itself inelegant.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyca/cryptography/issues/3009#issuecomment-227435093>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAADBG68mmv3m95hgIHWSWM-BI5NPznUks5qN-N2gaJpZM4I6tT8>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by reaperhulk** [comment]
You're not going to find mixed chains in the wild (having said that someone will prove me wrong...and alex did in IRC), but we should do better. When we originally designed this API we tried to explicitly avoid returning stringly typed information like `sha256WithRSAEncryption`. We could return the OID object itself of course (e.g. `cert.signature_oid`), but maybe we need an analog to `signature_hash_algorithm` like `signature_key_type` which returns...what. The only thing I can think of off the top of my head is the class of key that did the signing (e.g. `EllipticCurvePublicKey` or `RSAPublicKey`) but that's not great. Maybe we start with just exposing the OID.

**Comment by alex** [comment]
We may want to think a bit about what this API looks like in a theoretical
world where people actually issue RSA-PSS certs?

On Tue, Jun 21, 2016 at 9:23 AM, Paul Kehrer <notifications@github.com>
wrote:

> You're not going to find mixed chains in the wild (having said that
> someone will prove me wrong...and alex did in IRC), but we should do
> better. When we originally designed this API we tried to explicitly avoid
> returning stringly typed information like sha256WithRSAEncryption. We
> could return the OID object itself of course (e.g. cert.signature_oid),
> but maybe we need an analog to signature_hash_algorithm like
> signature_key_type which returns...what. The only thing I can think of
> off the top of my head is the class of key that did the signing (e.g.
> EllipticCurvePublicKey or RSAPublicKey) but that's not great. Maybe we
> start with just exposing the OID.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyca/cryptography/issues/3009#issuecomment-227437782>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAADBAzgJ92TyhovTGpr0DxQqtMus0Yjks5qN-XIgaJpZM4I6tT8>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by reaperhulk** [comment]
If we just expose the OID we can sidestep that issue for the moment since RSA-PSS is `1.2.840.113549.1.1.10` and then there's a separate sequence defining the PSS params. I'd rather solve this issue and then tackle PSS params as a separate one (when the time comes). I think a PR for `signature_algorithm_oid` covers this.
