### ISSUE TITLE
Post-mortem: Direct push of commit to master

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3018]
pyca/cryptography has a development policy requiring that all commits be in PRs, all PRs be reviewed, and all CI be green before we merge a PR. Unfortunately, this morning a commit was accidentally pushed to master directly (https://github.com/pyca/cryptography/commit/ca9b989ef5e27e88776cb6f3464e2f54ccd834c5).

As a post-hoc review, this is a simple documentation change that fixes a syntax error. 👍 to merging.

**How are we going to prevent this occurring in the future?**

GitHub has a concept of required status checks in protected branches. Protected branches disable the ability to force push to master for anyone and status checks prohibit pushes to master except via PRs that have passing status checks. However, there is a separate flag to "include administrators" in the requirement. If that is unchecked (as it is by default) then admins can merge PRs even if required status checks are failing. We previously left this unchecked because on occasion codecov has issues (comparing against the wrong base, never reporting status, etc) that prevent all the checks from succeeding even when the PR itself is fine.

This choice has now been revisited and status checks are enforced for admins. We have enabled required checks for Travis CI and our 3 jenkins CI jobs (jenkins/pr, jenkins/docs, jenkins/pep8). This prevents accidental pushes to master while preserving our ability to merge even if codecov is having trouble. In practice we will continue to require 100% coverage and in the vast majority of cases codecov's status checks will be required before we merge a PR.

**Comment by alex** [comment]
Thanks for writing this up. Now that we've mitigated this with protected branches, can we close?

**Comment by reaperhulk** [comment]
Yeah let's go ahead and close
