### ISSUE TITLE
No documentation for ECDSA verification

### ISSUE THREAD

**Issue by palaviv** [pyca/cryptography#3030]
While working on #3029 I noticed that ECDSA has no section in the documentation for verification. Both RSA and DSA has such section.

**Comment by alex** [comment]
Huh, that's quite an oversight.

**Comment by ralienpp** [comment]
I stumbled upon this void in the documentation while tackling a problem. As I gradually understand how this works, I can write a doc and submit a pull request. Is anyone already working on this, by any chance?

**Comment by reaperhulk** [comment]
I don't believe anyone is working on this so we welcome your contribution!
