### ISSUE TITLE
No method for rsa decryption with public key

### ISSUE THREAD

**Issue by triostones** [pyca/cryptography#3033]
Hi!

I have some data which is encrypted with rsa private key in java program. 

But I have to decrypt it in python program only using the public key.

I found that there is no method to do this in cryptography.

Did I miss some information in document?
OR Is there really no method about this?

**Comment by joernheissler** [comment]
You usually don't encrypt with private keys.
I think an example would help here. Can you attach the public key and the encrypted data?

**Comment by alex** [comment]
Decryption with public keys is only really usable as a primitive for providing signatures, we directly provide a signature API: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#signing

**Comment by triostones** [comment]
I am sorry for the late reply.

Actually, the feature I was looking for is [`RSA_private_encrypt`](https://wiki.openssl.org/index.php/Manual:RSA_private_encrypt(3)), which handle RSA signatures at a low level. It was called as RSA encryption in earlier RSA standard. But it seems that cryptography didn't expose the feature as python functions.
