### ISSUE TITLE
1.4 Test failure TestRSACertificate.test_cert_serial_warning

### ISSUE THREAD

**Issue by lfam** [pyca/cryptography#3034]
While testing an upgrade of the GNU Guix python-cryptography package from 1.3.2 to 1.4, I encountered the following failure of ```TestRSACertificate.test_cert_serial_warning[backend0]```.

```
=================================== FAILURES ===================================
____________ TestRSACertificate.test_cert_serial_warning[backend0] _____________

self = <tests.test_x509.TestRSACertificate object at 0x7fffe0fa7978>
backend = <cryptography.hazmat.backends.openssl.backend.Backend object at 0x7ffff3020278>

    def test_cert_serial_warning(self, backend):
        cert = _load_cert(
            os.path.join("x509", "PKITS_data", "certs", "GoodCACert.crt"),
            x509.load_der_x509_certificate,
            backend
        )
    
        with warnings.catch_warnings():
            warnings.simplefilter("always", utils.DeprecatedIn10)
>           with pytest.deprecated_call():
E           TypeError: deprecated_call() missing 1 required positional argument: 'func'

tests/test_x509.py:516: TypeError
============ 1 failed, 83123 passed, 3222 skipped in 164.91 seconds ============
```

The dependency graph is using Python 3.4.3 and Hypothesis 3.1.0. Please let me know what other information I can provide to help debug this failure.

**Comment by alex** [comment]
What version of py.test are you using

**Comment by lfam** [comment]
I'm using 2.7.3.

**Comment by alex** [comment]
Try a newer pytest

On Fri, Jul 1, 2016 at 8:29 PM, lfam <notifications@github.com> wrote:

> I'm using 2.7.3.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyca/cryptography/issues/3034#issuecomment-230073052>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAADBKqGx-sq76w8Qu8CmG0MJbYeO3W9ks5qRbEDgaJpZM4JDjvP>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by lfam** [comment]
Okay, thank you for clarifying the requirement. I will re-open if this problem persists with the newer version of pytest.

**Comment by alex** [comment]
I believe 2.9.0 is the minimum version.

On Fri, Jul 1, 2016 at 8:39 PM, lfam <notifications@github.com> wrote:

> Okay, thank you for clarifying the requirement. I will re-open if this
> problem persists with the newer version of pytest.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyca/cryptography/issues/3034#issuecomment-230073731>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAADBD2BKBApRFjt6pVcnQst9hLNQkAjks5qRbM-gaJpZM4JDjvP>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6
