### ISSUE TITLE
Do not define __about__ / __title__ / other unofficial magic names

### ISSUE THREAD

**Issue by merwok** [pyca/cryptography#3039]
From discussion on 5f12a1b89a46:

If the PyCA wants to demo best Python practices in addition to best crypto practices, it should not use magic (dunder) names for Python attributes or filenames. Python core formally reserves ownership of all magic names, and can define meaning for new magic names in any new feature release (e.g. __matmul__ method in 3.5, __main__.py file in 2.7); it's already bad that some popular projects like ORMs or web frameworks rely heavily on custom magic names.

**Comment by dstufft** [comment]
I don't think this is any more true for ``__whatever__`` names as it is for anything else, Python might *claim* that it is, but I don't believe that it is the case. Two of these names are taken right out of examples  from PEP 8:

```
"""This is the example module.

This module does stuff.
"""

from __future__ import barry_as_FLUFL

__all__ = ['a', 'b', 'c']
__version__ = '0.1'
__author__ = 'Cardinal Biggles'

import os
import sys
```

For ``__version__`` specifically, there are a number of tools in the Python ecosystem that look for such a thing (like for example, Sentry I believe) and is [documented in the packaging guide](https://packaging.python.org/single_source_version/). This is also used in [numerous places in the standard library](https://github.com/python/cpython/search?q=__version__&utf8=%E2%9C%93) including the standard library reach out and looking at ``pip.__version__`` and this usage of this attribute is part of a (deferred) [PEP](https://www.python.org/dev/peps/pep-0396/) and has been mentioned in the documentation of Python itself:

> The __version__ attribute has been dropped from the email package. The email code hasn't been shipped separately from the stdlib for a long time, and the __version__ string was not updated in the last few releases.

It is also [documented](https://docs.python.org/2/library/curses.html#curses.version) as part of the public API for the curses module and in the [examples](https://docs.python.org/3.6/library/unittest.html#skipping-tests-and-expected-failures) for the unittest module.

Given all of that I think it's safe to say that ``__version__`` is never going to break and is a defacto standard if not an official standard and I'd be against *not* exposing a ``cryptography.__version__`` variable.

The same is true, though to a lesser degree for the ``__author__``, ``__email__``, and ``__copyright__`` variable.

For everything but ``__version__`` I don't really care what we do. I made them dunder names for consistency and no other reason. I don't even care if we remove them all, rename ``__about__.py`` to ``_version.py`` and only export ``__version__``.

**Comment by alex** [comment]
@dstufft ok with closing this then?

**Comment by dstufft** [comment]
Fine with me.
