### ISSUE TITLE
Cryptography_rand_bytes  Function Crashing Apache

### ISSUE THREAD

**Issue by aabraamyan** [pyca/cryptography#3042]
One of my Django (1.8) projects is facing this strange error involving the cryptography_rang_bytes function which occurs during "form submission" on a website. Which of course is a POST request followed by some processing.

Here is the error I've received from my logs.

> [Wed Jul 13 19:14:35.928632 2016] [cgi:error] [pid 5353] [client 172.31.31.165:27720] AH02811: script not found or unable to stat: /var/www/cgi-bin/php5
> [Wed Jul 13 19:14:38.799711 2016] [cgi:error] [pid 5353] [client 172.31.31.165:27720] AH02811: script not found or unable to stat: /var/www/cgi-bin/php5-cgi
> **extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.**
> [Wed Jul 13 20:01:01.350692 2016] [mpm_prefork:notice] [pid 1044] AH00173: SIGHUP received.  Attempting to restart
> [Wed Jul 13 20:01:01.740546 2016] [so:warn] [pid 1044] AH01574: module wsgi_module is already loaded, skipping
> [Wed Jul 13 20:01:01.763434 2016] [auth_digest:notice] [pid 1044] AH01757: generating secret for digest authentication ...
> [Wed Jul 13 20:01:01.764102 2016] [lbmethod_heartbeat:notice] [pid 1044] AH02282: No slotmem from mod_heartmonitor
> [Wed Jul 13 20:01:01.766258 2016] [mpm_prefork:notice] [pid 1044] AH00163: Apache/2.4.18 (Amazon) mod_wsgi/3.5 Python/3.4.3 configured -- resuming normal operations
> [Wed Jul 13 20:01:01.766281 2016] [core:notice] [pid 1044] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
> **extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.**

The bold errors are repeated several hundred times.

**Comment by reaperhulk** [comment]
This is caused by the same issue that caused random initialization problems in the past. If you follow the advice here: https://cryptography.io/en/latest/faq/#starting-cryptography-using-mod-wsgi-produces-an-internalerror-during-a-call-in-register-osrandom-engine it should resolve it. If you still have problems feel free to reopen!
