### ISSUE TITLE
Non-RFC conformant X509 certificate serial number is generated

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#3064]
https://tools.ietf.org/html/rfc5280  4.1.2.2.  Serial Numbers

`Conforming CAs MUST NOT  use serialNumber values longer than 20 octets.`

Well, let's look to source code:

cryptography/hazmat/backends/openssl/backend.py :
```python
def _int_to_bn(self, num, bn=None):
    ...
    binary = num.to_bytes(int(num.bit_length() / 8.0 + 1), "big")
    ...
```

cryptography/x509/base.py:
```python
class CertificateBuilder:
    def serial_number(self, number):
        if utils.bit_length(number) > 160
```

Since serial number should be positive, for my example below it should add additional zero.

Sample program:
```python
import datetime
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.x509 import NameOID
key = rsa.generate_private_key(public_exponent=65537, key_size=512, backend=default_backend())
serial = int.from_bytes(b'\xff' * 20, 'big')
subj = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, 'qwe')])
builder = x509.CertificateBuilder()
builder = builder.subject_name(subj)
builder = builder.issuer_name(subj)
builder = builder.not_valid_before(datetime.datetime.today())
builder = builder.not_valid_after(datetime.datetime.today())
builder = builder.serial_number(serial)
builder = builder.public_key(key.public_key())
cert = builder.sign(private_key=key, algorithm=SHA256(), backend=default_backend())
print(cert.public_bytes(encoding=serialization.Encoding.PEM).decode('ascii'))
```

`./qwe.py | openssl asn1parse -inform pem  -i` gives:

```
...
13:d=2  hl=2 l=  21 prim:   INTEGER           :FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
...
```

Note 21 byte (!)

**Comment by socketpair** [comment]
![bug](https://cloud.githubusercontent.com/assets/1157412/17203553/a883ecb4-54b9-11e6-87fd-5baf6ab5612c.png)

Note leading zero

**Comment by socketpair** [comment]
The problem in that `bit_length()` mean length in bits of number in UNSIGNED representation, while ASN.1 requires integer to be signed.

```
6.5.3.15. Unsigned Integer

          An integer that is limited in range to non-negative values 
          including zero. For the purposes of this Standard, the sign
          bit is considered part of the Unsigned Integer value. This 
          type cannot be expressed as an ASN.1 INTEGER type, because
          an INTEGER always uses the sign bit.
```

**Comment by socketpair** [comment]
Also, 
1. `int(num.bit_length() / 8.0 + 1` should be replaced with `num.bit_length() +7 // 8 `. Using floating point to calculate byte lengths is overkill.
2. zero serial number should be just disallowed, or workarounds should be done (`if num == 0: return 1`)

**Comment by reaperhulk** [comment]
Thanks for the report, this is indeed a bug. Your third point should be covered by:

```python
        if number < 0:
            raise ValueError('The serial number should be non-negative.')
```

Which is the check prior to the bit length check, but we should alter it to encompass 0 and update the text to say "Serial numbers must be positive integers" or something to that effect.

Are you interested in providing a PR?

**Comment by socketpair** [comment]
Yes, I can try to make PR, but structure is so complex and I afraid that it will not be complete.
