### ISSUE TITLE
Python3 setup.py test requires root privileges

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#3068]
* `python3 setup.py build` works OK
* `python3 setup.py install --user` works OK
* `python3 setup.py test` FAILED

```
$ python3.5 setup.py test
running test
running install
Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-29608.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.5/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

Traceback (most recent call last):
  File "setup.py", line 333, in <module>
    **keywords_with_side_effects(sys.argv)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 101, in finalize_options
    [sys.executable, "setup.py", "install"], cwd="vectors"
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.5', 'setup.py', 'install']' returned non-zero exit status 1

```

**Comment by reaperhulk** [comment]
I'm not sure if there's a way around this, although if someone has ideas we're happy to improve it. Our test vectors are a separate package, but we want them to be available in the test env. We accomplish this by installing them and then running the tests. Our preferred testing method (`tox`) will create a virtualenv and do this, but `setup.py test` will not do that for you.

**Comment by socketpair** [comment]
1. Why not to remove that command from setup.py ?
2. Another way is to install using `--user` while installing separate package.

**Comment by socketpair** [comment]
Also, I'm not familiar with tox. Can you add instruction how to run tests ?

**Comment by alex** [comment]
https://cryptography.io/en/latest/development/getting-started/#running-tests

**Comment by reaperhulk** [comment]
We have the command in `setup.py` because several Linux distribution packagers have requested that it be there for their workflow, but as @alex noted we have documentation on the preferred way to run the test suite.

**Comment by alex** [comment]
There doesn't appear to be anything that can be done here.

**Comment by erolgerceker** [comment]
sudo python3 setup.py test

> * `python3 setup.py build` works OK
> * `python3 setup.py install --user` works OK
> * `python3 setup.py test` FAILED
> 
> ```
> $ python3.5 setup.py test
> running test
> running install
> Checking .pth file support in /usr/local/lib/python3.5/dist-packages/
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/test-easy-install-29608.pth'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /usr/local/lib/python3.5/dist-packages/
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://pythonhosted.org/setuptools/easy_install.html
> 
> Please make the appropriate changes for your system and try again.
> 
> Traceback (most recent call last):
>   File "setup.py", line 333, in <module>
>     **keywords_with_side_effects(sys.argv)
>   File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
>     cmd_obj.ensure_finalized()
>   File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
>     self.finalize_options()
>   File "setup.py", line 101, in finalize_options
>     [sys.executable, "setup.py", "install"], cwd="vectors"
>   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3.5', 'setup.py', 'install']' returned non-zero exit status 1
> ```

try this;

sudo python3 setup.py test
