### ISSUE TITLE
Port our jenkins stuff to use Jenkinsfile

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3075]

**Comment by reaperhulk** [comment]
github pull request builder does not support jenkinsfile at this time https://github.com/janinko/ghprb/issues/409

**Comment by reaperhulk** [comment]
As @alex noted yesterday in IRC, homebrew appears to have successfully switched to using jenkins pipelines. See: https://bot.brew.sh/job/Homebrew/job/homebrew-core/job/PR-12356/ and https://github.com/Homebrew/homebrew-core/blob/master/Jenkinsfile
