### ISSUE TITLE
Can't compile cryptography on CoreOS

### ISSUE THREAD

**Issue by basharov** [pyca/cryptography#3105]
CoreOS doesn't ship with a C compiler so `pip install cryptography` fails with this error:

>     running egg_info
>     writing src/cryptography.egg-info/PKG-INFO
>     writing dependency_links to src/cryptography.egg-info/dependency_links.txt
>     writing entry points to src/cryptography.egg-info/entry_points.txt
>     writing requirements to src/cryptography.egg-info/requires.txt
>     writing top-level names to src/cryptography.egg-info/top_level.txt
>     warning: manifest_maker: standard file '-c' not found
> 
>     reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     no previously-included directories found matching 'docs/_build'
>     warning: no previously-included files matching '*' found under directory 'vectors'
>     writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
>     running build_ext
>     generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
>     creating build/temp.linux-x86_64-2.7
>     generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
>     generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
>     building '_openssl' extension
>     creating build/temp.linux-x86_64-2.7/build
>     creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
>     cc -O2 -fPIC -Wimplicit -I/home/core/pypy/include -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
>     unable to execute 'cc': No such file or directory
>     error: command 'cc' failed with exit status 1

Is there a way to workaround this? May be it's possible to download and use precompiled version of cryptography?

**Comment by reaperhulk** [comment]
There are two ways to work around this. You can build a CoreOS box, add all the required dependencies, `pip wheel cryptography` and then use that wheel on your CoreOS box without a compiler (you will still need libffi and openssl installed on the target machine of course), or you can experiment with `manylinux1` wheels (https://github.com/reaperhulk/cryptography-manylinux1). Be aware that the latter may currently cause issues with being able to validate TLS certificates properly, so if your use case for this project involves pyOpenSSL it is not recommended.
