### ISSUE TITLE
Reduce the API surface of our bindings

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3115]
When we initially started this project we bound many functions very quickly so that we wouldn't need to constantly add functions one at a time to gain functionality. This resulted in an API surface that's needlessly large compared to the feature set we expose. We should pare it down where possible. This will have the added benefit of slightly reducing our memory requirements for compilation (refs #2509).

The one negative is that we have had a few users add bindings for their own purposes that we do not use in cryptography or pyopenssl. We should hopefully be able to catch that by looking at git history for a given function to see what PR added it, but it's something to watch out for.

**Comment by noonat** [comment]
Do you just want to remove all unused bindings (other than the user added ones), or is there a subset of unused ones that you want to keep around?

**Comment by reaperhulk** [comment]
@noonat This problem has become more complex than originally assumed. cryptography may not be using a binding, but pyOpenSSL or pypy (for their new ssl module), or several other consumers might be directly using the binding without our knowledge. Removing any of them is going to be challenging. If we want to pursue this we'll probably need to go through every binding and make a list of everything where we can't determine the reason they're present. Then we'd need to implement a wrapper function that raises a warning of some kind when they're called so we can try to flush out consumers.

I'm not entirely sure it's worth this level of effort 😢

**Comment by alex** [comment]
Going to close this; at present it's not particularly actionable since we have no idea which bindings (if any) can be removed.

We're basically doing this implicitly as we remove older versions of OpenSSL and unused conditional  bindings (which are really most of the complexity anyways)
