### ISSUE TITLE
cipher instances reject non string literal

### ISSUE THREAD

**Issue by Patrick1114** [pyca/cryptography#3125]
Hi, I've encountered an issue regarding encryption and decryption objects of cryptography.hazmat.primitives.ciphers's Cipher. For example:
`ciphertext = cryptorInstance.update(b"string literal" ) + cryptorInstance.finalize()` 
works fine, however placing a space: 
`ciphertext = cryptorInstance.update(b "string literal" ) + cryptorInstance.finalize()` 
raises a syntax error.
For my use, I wanted to take a string stored in a variable ( that is dynamic, so I can't hardcode it like in the example above), and pass it as a parameter:
`        messageStr = "string literal"
        ciphertext = cryptorInstance.update(b messageStr) + cryptorInstance.finalize()
`
Is there a way I could pass a non-string literal? I've tried turning the parameter into the tuple (b messageStr), and Google has been less than helpful with information.

**Comment by reaperhulk** [comment]
The bug there is that prefixing `b` in front of a string makes it a byte string and we require byte strings to be passed. You can obtain a byte string from a "regular" string by using `encode`.
