### ISSUE TITLE
Memory leak in _encode_name

### ISSUE THREAD

**Issue by joernheissler** [pyca/cryptography#3134]
#!/usr/bin/python3

    import cryptography.hazmat.backends.openssl.backend as backend
    from cryptography.hazmat.backends.openssl.encode_asn1 import _encode_name_gc
    from cryptography.x509.oid import NameOID
    from cryptography import x509
    import gc

    n = [x509.NameAttribute(NameOID.COMMON_NAME, 'Hello')]

    while True:
        _encode_name_gc(backend, n)
        gc.collect()

The result from _encode_name_entry is not garbage collected. _encode_name calls X509_NAME_add_entry which creates a copy of it. The original is never freed.

**Comment by reaperhulk** [comment]
Thanks for the report! I've submitted a PR to fix this. Please review it if you get a chance. 😄

**Comment by joernheissler** [comment]
Looks good to me.
