### ISSUE TITLE
Broken “Edit on GitHub” link in documentation

### ISSUE THREAD

**Issue by alexwlchan** [pyca/cryptography#3137]
I was reading the following page: https://cryptography.io/en/latest/_modules/cryptography/hazmat/primitives/ciphers/algorithms/#TripleDES

I click the “Edit on GitHub” button, which tries to take me to: https://github.com/pyca/cryptography/blob/master/docs/_modules/cryptography/hazmat/primitives/ciphers/algorithms.rst

That page gets a 404 error.

At a glance, is it because this page is auto-generated from a Python file, and not actually a new document in its own right? (I’d dig into this properly, but I’m a bit busy right now, and raising an issue so this doesn’t get forgotten.)

**Comment by alex** [comment]
Unfortunately there's nothing we can do about this; this is a bug in one of Sphinx and ReadTheDocs. The "edit on github" buttons work on docs pages that aren't generated from a module.
