### ISSUE TITLE
AttributeError("'EntryPoint' object has no attribute 'resolve'",)

### ISSUE THREAD

**Issue by naveensinghal** [pyca/cryptography#3149]
Hi @alex ,

I have few issues related to PyOpenSSL & Cryptography packages in Python. Can you please help in resolving these, if possible ? 

Python Code which initiates the Error:
```
print("Salt: %s" % salt)
server_key = pyelliptic.ECC(curve="prime256v1")
print("Server_key: %s" % server_key)
server_key_id = base64.urlsafe_b64encode(server_key.get_pubkey()[1:])

http_ece.keys[server_key_id] = server_key
http_ece.labels[server_key_id] = "P-256"
encrypted = http_ece.encrypt(data, salt=salt, keyid=server_key_id,
            dh=self.receiver_key, authSecret=self.auth_key)
```

Value of "Salt" is getting displayed in 100% of the cases. But
If value of "Server Key:" gets displayed, I see the the following EntryPoint Error because of http_ece.encrypt() call:
`AttributeError("'EntryPoint' object has no attribute 'resolve'",)`
(Ref. File Link: [https://github.com/martinthomson/encrypted-content-encoding/blob/master/python/http_ece/__init__.py#L128](url) )

Otherwise I get the following Error because of pyelliptic.ECC() call:
`Exception('[OpenSSL] EC_KEY_generate_key FAIL ... error:00000000:lib(0):func(0):reason(0)',)`
(Ref. File Link: [https://github.com/yann2192/pyelliptic/blob/master/pyelliptic/ecc.py#L214](url) )

Other Details:
Partial Requirements.txt:
```
cryptography==1.5
pyelliptic==1.5.7
pyOpenSSL==16.1.0
```

The Django App is running on Debian8 Google Compute Engine VM Instance using Apache and mod_wsgi.

Can you please help in resolving this issue ?
Please let me know if any more information is required.

Thanks,

**Comment by alex** [comment]
I'm not sure how you installed cryptography, but this is caused by using an old version of setuptools.

**Comment by naveensinghal** [comment]
How can i check the version of setuptools installed on my VM ?

**Comment by naveensinghal** [comment]
Ran this command: 
sudo pip freeze --all |grep setuptools

and got this: 
setuptools==27.1.2

**Comment by naveensinghal** [comment]
@alex , Can you please suggest the correct way to reinstall the cryptography & the setuptools ? 

Thanks,

**Comment by dstufft** [comment]
What does ``python -c 'import pkg_resources; print(pkg_resources.__file__)'`` do?

**Comment by naveensinghal** [comment]
Running this command resulted in:
~/.local/lib/python2.7/site-packages/pkg_resources/__init__.pyc

This seems to be wrong, i think. But don't know the correct value too. :P

**Comment by dstufft** [comment]
What about ``python -c 'import sys; print(sys.path)'``?

**Comment by naveensinghal** [comment]
Running  "python -c 'import sys; print(sys.path)'" resulted in:

['', '/opt/projects/myproject-google/myproject', '/opt/projects/myproject-google/venv/lib/python2.7/site-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '~/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat']

**Comment by dstufft** [comment]
Is there a ``setuptools``, ``pkg_resources``, or ``setuptools-*.(egg|dist)-info`` inside of /opt/projects/myproject-google/venv/lib/python2.7/site-packages?

**Comment by naveensinghal** [comment]
Ran sudo ls  /opt/projects/myproject-google/venv/lib/python2.7/site-packages
Got: 
easy_install.py   _markerlib  pip-1.5.6.dist-info  pkg_resources.pyc  setuptools-5.5.1.dist-info
easy_install.pyc  pip	      pkg_resources.py	   setuptools

**Comment by dstufft** [comment]
Does ``python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'`` give you a different result than ``/opt/projects/myproject-google/venv/bin/python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'``?

What about ``/opt/projects/myproject-google/venv/bin/python -c "import pkg_resources; print(pkg_resources.__file__)"``?

The script you're running that is invoking it, how are you invoking it? Is it ``python <the script>``, ``/opt/projects/myproject-google/venv/bin/python <the script>``, or is it it's own command like ``<the script>``?

**Comment by naveensinghal** [comment]
[Command]: python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'

[Output]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

**Comment by naveensinghal** [comment]
[Command]: sudo python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'

[Output]
<cryptography.hazmat.backends.multibackend.MultiBackend object at 0x7fd3f8a58bd0>

**Comment by naveensinghal** [comment]
[Command]: /opt/projects/myproject-google/venv/bin/python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'

[Output]:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cryptography.hazmat.backends
```

**Comment by naveensinghal** [comment]
[Command]: /opt/projects/myproject-google/venv/bin/python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cryptography.hazmat.backends
```

[Command]: /opt/projects/myproject-google/venv/bin/python -c "import pkg_resources; print(pkg_resources.__file__)"

[Output]:
/opt/projects/myproject-google/venv/lib/python2.7/site-packages/pkg_resources.pyc

**Comment by dstufft** [comment]
So I think I've worked out what's happening here.

You have a currently active virtual environment located at ``/opt/projects/myproject-google/venv`` which was created with ``--system-site-packages``. When that virtual environment was created, setuptools 5.5.1 was installed into it. Now you also have setuptools 27.1.2 and cryptography installed to ``~/.local/`` which is visible inside of the virtual environment because it was created with ``--system-site-packages``. So when you try and import cryptography the virtual environment setuptools/pkg_resources takes precedence and since it's an older version it makes things go boom.

I think you can fix things by just upgrading the setuptools inside of your virtual environment, however I would suggest starting over and *not* using ``--system-site-packages``. It kind of creates weird problems like this and really shouldn't be used unless you really need to.

**Comment by naveensinghal** [comment]
Would creating a new Virtual Environment from starting resolve the problem ? 

I mean running these commands from `/opt/projects/myproject-google/myproject` path:
```
sudo rm -rf ../venv
sudo virtualenv ../venv
source ../venv/bin/activate
sudo pip install -r requirements.txt
deactivate
```

would resolve the issue ?

**Comment by dstufft** [comment]
Yea I think so.

**Comment by naveensinghal** [comment]
Ran The following 5 commands from /opt/projects/myproject-google/myproject path:
```
sudo rm -rf ../venv
sudo virtualenv ../venv
source ../venv/bin/activate
sudo pip install --upgrade -r requirements.txt
deactivate
```

While Installing requirements, it said: 
`Requirement already up-to-date:` 
for every single requirement.

**New Results:**
**Command** `python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'`

**Output**
`<cryptography.hazmat.backends.multibackend.MultiBackend object at 0x7ff83a838d50>`


**Command** `/opt/projects/myproject-google/venv/bin/python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'`

**Output**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cryptography.hazmat.backends
```

**Command** `/opt/projects/myproject-google/venv/bin/python -c "import pkg_resources; print(pkg_resources.__file__)"`

**Output**
`/opt/projects/myproject-google/venv/lib/python2.7/site-packages/pkg_resources.pyc`

**Comment by dstufft** [comment]
Huh, what is your ``virtualenv --version``?

**Comment by naveensinghal** [comment]
sudo virtualenv --version
1.11.6

Error Trace while pressing 'Execute Script' button from Browser: 
```
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 153, in new_request
    credentials._refresh(orig_request_method)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 765, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 792, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 1501, in _generate_refresh_request_body
    assertion = self._generate_assertion()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/service_account.py", line 386, in _generate_assertion
    key_id=self._private_key_id)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 97, in make_signed_jwt
    signature = signer.sign(signing_input)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_openssl_crypt.py", line 97, in sign
    return crypto.sign(self._key, message, 'sha256')
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2656, in sign
    _openssl_assert(final_result == 1)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 61, in openssl_assert
    exception_from_error_queue(error)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('rsa routines', 'RSA_setup_blinding', 'BN lib'), ('rsa routines', 'RSA_EAY_PRIVATE_ENCRYPT', 'internal error')]

Inside ecc.py, _generate()
key: 140465228008272
Exception: [OpenSSL] EC_KEY_generate_key FAIL ... error:00000000:lib(0):func(0):reason(0)
```

**Comment by dstufft** [comment]
Do you have a ``PYTHONPATH`` environment variable set?

**Comment by naveensinghal** [comment]
**Command**: `echo $PYTHONPATH`
**Output**: `:/opt/projects/myproject-google/venv/lib/python2.7/site-packages/:/usr/local/lib/python2.7/dist-packages`

**Comment by dstufft** [comment]
Can you unset that, and then try

```
source ../venv/bin/activate
sudo pip install --upgrade -r requirements.txt
deactivate
```

?

**Comment by naveensinghal** [comment]
Unsetted the Pythonpath. Still the same issue.

```
export PYTHONPATH=
source ../venv/bin/activate
sudo pip install --upgrade -r requirements.txt
deactivate
```

echo $PYTHONPATH is now blank

**Comment by dstufft** [comment]
Did it say requirements were already satisfied?

**Comment by naveensinghal** [comment]
yes `Requirement already up-to-date:` for every single requirement

**Comment by dstufft** [comment]
Is the environment variable ``VIRTUALENV_SYSTEM_SITE_PACKAGES`` set? Do you have a ``~/.virtualenv/virtualenv.ini`` file?

**Comment by naveensinghal** [comment]
No ~/.virtualenv/virtualenv.ini file exist.

**Comment by naveensinghal** [comment]
**Command**: `echo $PYTHONPATH`
**Output**: [blank]

**Command**: `python -c 'import pkg_resources; print(pkg_resources.__file__)'`
**Output**: ~/.local/lib/python2.7/site-packages/pkg_resources/__init__.pyc

**Command**: `python -c 'import sys; print(sys.path)'`
**Output**: ['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '~/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/opt/projects/myproject-google/myproject', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat']

**Command**: `ls  /opt/projects/myproject-google/venv/lib/python2.7/site-packages`
**Output**:
easy_install.py   _markerlib  pip-1.5.6.dist-info  pkg_resources.pyc  setuptools-5.5.1.dist-info
easy_install.pyc  pip         pkg_resources.py     setuptools

**Command**: `python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'`
**Output**: `<cryptography.hazmat.backends.multibackend.MultiBackend object at 0x7ff83a838d50>`


**Command** `/opt/projects/myproject-google/venv/bin/python -c 'from cryptography.hazmat.backends import default_backend; print(default_backend())'`

**Output**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cryptography.hazmat.backends
```

**Command**: `/opt/projects/myproject-google/venv/bin/python -c "import pkg_resources; print(pkg_resources.__file__)"`

**Output**: `/opt/projects/myproject-google/venv/lib/python2.7/site-packages/pkg_resources.pyc`

**Comment by naveensinghal** [comment]
@dstufft @reaperhulk 

Can you please suggest some Workaround for this ? 
(Stuck on this issue since few days now)

Thanks,

**Comment by naveensinghal** [comment]
@dstufft  You are awesome. Thanks a lot.

Just upgraded my virtualenv version and recreated the project virtual env. with new version. And it worked. New Virtualenv now has updated setuptools version.
(Refer previous post for commands)
