### ISSUE TITLE
P_SHA1 support

### ISSUE THREAD

**Issue by kislyuk** [pyca/cryptography#3151]
The WS-Security standard uses a subset of TLS called P_SHA-1 as described [here](http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512/ws-secureconversation-1.3-os.html#_Toc162064056). This is useful when interfacing with some SOAP-based APIs and implemented in e.g. https://github.com/leandrob/node-psha1, https://github.com/FROGGS/p6-Digest-PSHA1.

It would be nice if cryptography included functions to handle this.

**Comment by joernheissler** [comment]
This is quite a highlevel function. Aside from Fernet, there seems to be only primitives.
I wouldn't know what the best place in Cryptography lib is to put random algorithm like that one.
I've given it a try to implement it. No idea if the output is correct. 

    #!/usr/bin/python3

    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import hmac
    from io import BytesIO


    class PHash:
        """
        Implementation of https://tools.ietf.org/html/rfc5246#section-5
        """

        def __init__(self, algo, secret, seed, backend=default_backend()):
            self._hmac = hmac.HMAC(secret, algo, backend=backend)
            self._seed = seed
            self._a = seed
            self._leftover = b''

        def read(self, n):
            buf = BytesIO()
            buf.write(self._leftover)
            while buf.tell() < n:
                a = self._hmac.copy()
                a.update(self._a)
                self._a = a.finalize()

                h = self._hmac.copy()
                h.update(self._a)
                h.update(self._seed)
                buf.write(h.finalize())
            buf.seek(0)
            result = buf.read(n)
            self._leftover = buf.read()
            return result

    if __name__ == '__main__':
        from cryptography.hazmat.primitives import hashes

        p = PHash(hashes.SHA1(), b'HelloWorld', b'blahblah')
        print(p.read(42).hex())
        print(p.read(123).hex())

**Comment by alex** [comment]
I think this is a bit too obscure to be included in cryptography itself. WS-Security is a relatively uncommon standard (also a pretty bad one), and cryptography provides the API's to implement it yourself.
