### ISSUE TITLE
Suport for signature algorithm 1.3.14.3.2.29 (sha1RSA)

### ISSUE THREAD

**Issue by anthrotype** [pyca/cryptography#3160]
Hi,

I encountered an issue while attempting to verify the signature of a certificate.
My code looks like this:

``` python
verifier = public_key.verifier(signature, padding.PKCS1v15(), cert_signed.signature_hash_algorithm)
```

Works fine with most certificates but for some it raises:

```
File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 120, in signature_hash_algorithm
    "Signature algorithm OID:{0} not recognized".format(oid)
cryptography.exceptions.UnsupportedAlgorithm: Signature algorithm OID:1.3.14.3.2.29 not recognized
```

It seems the OID "1.3.14.3.2.29" is not in the list of supported `SignatureAlgorithmOID`.
https://github.com/pyca/cryptography/blob/master/src/cryptography/x509/oid.py#L123

I found a reference to this OID on MSDN website:
https://msdn.microsoft.com/en-gb/library/ff635603.aspx

They identify it as `sha1RSA`, i.e. the same as OID "1.2.840.113549.1.1.5".

Should `cryptography` add support for this signature algorithm OID?

Possibly related links:
https://bugzilla.mozilla.org/show_bug.cgi?id=405966
https://lists.gnupg.org/pipermail/gnutls-help/2013-October/003252.html

**Comment by reaperhulk** [comment]
@anthrotype yeah looks like we need to add this as an alternate OID for sha1WithRSA, thanks for the report.

**Comment by anthrotype** [comment]
Thanks!

**Comment by mandeep** [comment]
I'd like to work on this if possible. Is there a preference on how alternate OIDs are added to oid.py?

**Comment by alex** [comment]
I think my preference would be to add it to the mapping, but not put it in the enum. Haven't thought too hard about this though.

**Comment by mandeep** [comment]
@reaperhulk @alex Sorry for losing track of this. Got caught up in midterms :(
