### ISSUE TITLE
how to silence openssl backend cast warnings

### ISSUE THREAD

**Issue by hackers-terabit** [pyca/cryptography#3167]
Getting this:

/usr/lib64/python3.4/site-packages/cryptography/hazmat/backends/openssl/backend.py:307: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)

I was using PBKDF2HMAC and aes with gcm mode, how can I quiet this? can you fix it please?

**Comment by reaperhulk** [comment]
Upgrade to 1.5.1, which fixes this.

**Comment by hackers-terabit** [comment]
Thank you sir,that fixed it. I did a pip install yesterday so I figured it was up to date,did an --upgrade now and it works :)
