### ISSUE TITLE
Error generating certificate with not_valid_after = 9999-12-31 23:59:59

### ISSUE THREAD

**Issue by jmcfcosta** [pyca/cryptography#3194]
Hi, 
While trying to generate a certificate with not_valid_after = 9999-12-31 23:59:59, I'm getting the following error: 
cryptography.exceptions.InternalError: Unknown OpenSSL error. (...) ([_OpenSSLErrorWithText(code=218992813L, lib=13, func=217, reason=173, reason_text='error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time')]).

I'm using Windows 8, 64-bit with Python 2.7.12, cryptography(1.5.2)
The same code works in Ubuntu.

After doing some further testing, I noticed it will work for year values below 3000. 
Any hints/workarounds?

**Comment by alex** [comment]
@reaperhulk we should make this return a clean error, instead of InternalError

**Comment by njsmith** [comment]
Curiously, the machine I have here (Windows 10, Python 3.6) seems to accept any date up to January 19, 3001, but January 20, 3001 fails.

Just in case anyone else runs into this and wants to know what the limit is.
