### ISSUE TITLE
Test failure of test_numeric_string_x509_name_entry

### ISSUE THREAD

**Issue by lfam** [pyca/cryptography#3196]
Hi,

I'm working on distro packaging for GNU Guix. Currently we package cryptography-1.3.4.

While upgrading some of the core packages on our system, one of cryptography's tests started failing, like this:

```
=================================== FAILURES ===================================
___________ TestGOSTCertificate.test_numeric_string_x509_name_entry ____________

self = <tests.hazmat.backends.test_openssl.TestGOSTCertificate object at 0x7fffe2191e80>

    @pytest.mark.skipif(
        backend._lib.OPENSSL_VERSION_NUMBER < 0x1000000f,
        reason="Requires a newer OpenSSL. Must be >= 1.0.0"
    )   
    def test_numeric_string_x509_name_entry(self):
        cert = _load_cert(
            os.path.join("x509", "e-trust.ru.der"),
            x509.load_der_x509_certificate,
            backend
        )   
        with pytest.raises(ValueError) as exc:
>           cert.subject
E           Failed: DID NOT RAISE

tests/hazmat/backends/test_openssl.py:674: Failed
============= 1 failed, 80170 passed, 20 skipped in 152.54 seconds =============
```

Can you say what it means that this assertion was not raised? Is it a real problem for us or is it safe to disable the test?

By the way, we are working on upgrading our Python packages so that we can package the latest release of cryptography. But if this test failure is spurious, we can make the package build again more quickly than if we upgraded the core of our Python package graph.

**Comment by reaperhulk** [comment]
If you're running a newer OpenSSL (1.0.2i+) this test will fail on older versions of cryptography because 1.0.2i+ supports NUMERICSTRING conversion (https://github.com/pyca/cryptography/blob/master/tests/hazmat/backends/test_openssl.py#L731-L736). So yes, you can ignore this failure.

**Comment by lfam** [comment]
Right, we are building cryptography against OpenSSL 1.0.2j. I'll disable that test.
