### ISSUE TITLE
Implement x400Address and ediPartyName GeneralName types

### ISSUE THREAD

**Issue by frasertweedale** [pyca/cryptography#3200]
When _cryptography_ encounters x400Address or ediPartyName GeneralName
types, it throws an exception.  If someone wants to perform general cert or
CSR parsing/inspect, this is a problem.

Let us discuss what API could look like.

If we accept that:
- the main use case we are trying to solve is "don't blow up if we encounter these name types", and
- the actual use cases of X.400 addresses and EDI are marginal and therefore it is acceptable to provide implementors with the raw data from these name types, and
- if in the future X.400 or EDI surge in popularity and we want to implement "better" types then we can add methods/properties/subtypes to expose the data in a more "friendly" way...

then it is probably fine to implement `X400Name` and `EDIPartyName` types that extend `GeneralName` and provide as their `value` the unparsed inner DER as `bytes`.

**Comment by reaperhulk** [comment]
Yes, `X400Name` and `EDIPartyName` objects that looks roughly like:

```python
@utils.register_interface(GeneralName)
class X400Name(object):
    def __init__(self, value):
        self._value = value
```

would let us expose this without erroring and give us a path forward to implement it more completely in the future.

Are you seeing this crop up in the wild?

**Comment by frasertweedale** [comment]
Haven't seen them in the wild, but I definitely want the programs I work on to not fail if they encounter such a certificate.

They don't have to be able to interpret the data, just not fail if it occurs :)

I started to work on this feature but OpenSSL has bugs in GeneralName serialisation/deserialisation for EDIPartyName and I think also X400Addres.  So... I guess this goes on the backburner until those are addressed.
until that's sorted out.

**Comment by reaperhulk** [comment]
In 2+ years we haven't seen this in the wild and OpenSSL's support is still spotty to my knowledge. If and when these types become relevant we can revisit but for now I'm going to close this.
