### ISSUE TITLE
Update PyPy3 to 5.5.0 in install.sh

### ISSUE THREAD

**Issue by TiberiumPY** [pyca/cryptography#3204]
There was PyPy3 5.5.0 release, so we need to update PyPy3 version in .travis/install.sh to the latest

**Comment by reaperhulk** [comment]
pypy3-5.5 is still an alpha release. We'll officially restore support for pypy3 once that goes final.

**Comment by TiberiumPY** [comment]
Guys, it's easy to do. And this version isn't alpha

**Comment by reaperhulk** [comment]
Consider for a moment that we might have concerns that run beyond your view of this issue. Maybe we care about what platforms we officially support and want to ensure we update our documentation to reflect the (re-)addition of PyPy3 support, maybe the presence of an older version in our install scripts but no corresponding support in the library has deeper implications, maybe we care about the amount of time our CI takes to cycle given the myriad configurations we run (for the record, currently 24 on Travis and 28 on Jenkins) and want to carefully consider additions to it, and maybe PyPy3 5.5  is still an alpha release despite your protestations to the contrary (pypy.org explicitly lists it as such on the homepage, on the downloads page with a warning, and in the filenames). Please strongly consider asking additional questions about reasoning or politely disagreeing with our statements in the future.
