### ISSUE TITLE
RSA key generation

### ISSUE THREAD

**Issue by tejasatreja14292** [pyca/cryptography#3205]
I am trying to generate a RSA key but all i can get is the private key 
public_private_key = rsa.generate_private_key(public_exponent=65537,key_size=1024,backend=default_backend())

private_key = public_private_key.private_bytes(encoding=serialization.Encoding.PEM,format=serialization.PrivateFormat.TraditionalOpenSSL,encryption_algorithm=serialization.NoEncryption()) 

now how do I get the modulus ,e,primes etc

Please help and I am sorry for placing this as an issue

**Comment by alex** [comment]
Components of the public key are available on the corresponding public key's public numbers:

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey.public_key

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPublicKey.public_numbers
