### ISSUE TITLE
[help wanted] 

### ISSUE THREAD

**Issue by jonathannaguin** [pyca/cryptography#3206]
Hi, 

I have some difficulties with the following code:
```
sr_private_key = serialization.load_pem_private_key(/**/, password=None, backend=default_backend())

decrypted = sr_private_key.decrypt(encrypted_text, padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None))
```

The above works perfectly when I run it in my Mac OS El Capitan, but fails when I run it in a AWS EC2 instance:
```
raceback (most recent call last):
  File "test.py", line 33, in <module>
    decrypted = sr_private_key.decrypt(encrypted_text, padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256(), label=None))
  File "/usr/local/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 407, in decrypt
    return _enc_dec_rsa(self._backend, self, ciphertext, padding)
  File "/usr/local/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 53, in _enc_dec_rsa
    _Reasons.UNSUPPORTED_PADDING
cryptography.exceptions.UnsupportedAlgorithm: This combination of padding and hash algorithm is not supported by this backend.
```
I believe that the OpenSSL version could be related to this issue, but not sure, this is what I get when I run it in the EC2:
```
python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"
OpenSSL 1.0.1k-fips 8 Jan 2015
```
And this is from my Mac:
```
python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"
OpenSSL 1.0.2j  26 Sep 2016
```

Could this be the cause of the issue? Is this OpenSSL built-in inside cryptography?

Thanks!

**Comment by reaperhulk** [comment]
Yes, on Mac we ship the latest 1.0.2 OpenSSL, but on Linux it will use the system version. 1.0.1k-fips is unlikely to support SHA256 MGF1, so you may need to change that to SHA1.

**Comment by reaperhulk** [comment]
(Of note, there is no known security risk in using SHA1 for the mask generation function. SHA1's weaknesses are not an issue there.)

**Comment by jonathannaguin** [comment]
I tried to change the hash to be SHA1, but unfortunately the decryption fails.
Not sure if helps but the encrypted text was generated using Bouncy Castle in Java (OAEPWithSHA256AndMGF1Padding).
What alternatives do I have to use cryptography with 1.0.2 in Linux?

**Comment by reaperhulk** [comment]
You'll have to compile it yourself or use a newer distro that ships 1.0.2 (Ubuntu 16.04 for example). We have some instructions but it's frankly difficult to do correctly unless you're reasonably comfortable with how the linux linker works.
