### ISSUE TITLE
 Multibackend cannot be initialized with no backends/ py2exe

### ISSUE THREAD

**Issue by gloriousrootkit** [pyca/cryptography#3208]
Hello
I am programing client - server app. Before compiling everything works without problem but after compiling with py2exe I have this error:

ValueError: Multibackend cannot be initialized with no backends. If you are seeing this error when trying to use default_backend() please try uninstalling and reinstalling cryptography.

**Comment by reaperhulk** [comment]
This is a bug with the way py2exe works with setuptools entry points and not a bug in cryptography. See #2039 and #2155 for additional references.

**Comment by Ayrx** [comment]
@reaperhulk Given the volume of such issues filed does it make sense to add a note in the exception itself pointing out the issues these libraries have with entry points?

**Comment by reaperhulk** [comment]
Probably so, although the phrasing might be tricky
