### ISSUE TITLE
Allow to specify text IO in Python3 for PEM-files

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#3209]
For example, `serialization.load_pem_public_key()` should also accept files opened with 'rt' mode

**Comment by reaperhulk** [comment]
Are PEM files text or are they bytes that have a constrained set of values? If the former than we should allow strings for PEM, but I'm not sure if I agree that they are.

**Comment by ronf** [comment]
PEM files should always be plain ASCII. There are fixed headers and trailers and everything in between is limited to the subset of characters used in Base64 encoding.

That said, I can see an argument for allowing either bytes or str values, or files opened in either binary or text mode. If anything but this subset of ASCII is used, though, it should trigger an error.

**Comment by socketpair** [comment]
Is this pem-file valid ?

```

Всем превед, ЙА медвед!!!

-----BEGIN CERTIFICATE REQUEST-----
MIIB9TCCAWACAQAwgbgxGTAXBgNVBAoMEFF1b1ZhZGlzIExpbWl0ZWQxHDAaBgNV
BAsME0RvY3VtZW50IERlcGFydG1lbnQxOTA3BgNVBAMMMFdoeSBhcmUgeW91IGRl
Y29kaW5nIG1lPyAgVGhpcyBpcyBvbmx5IGEgdGVzdCEhITERMA8GA1UEBwwISGFt
aWx0b24xETAPBgNVBAgMCFBlbWJyb2tlMQswCQYDVQQGEwJCTTEPMA0GCSqGSIb3
DQEJARYAMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCJ9WRanG/fUvcfKiGl
EL4aRLjGt537mZ28UU9/3eiJeJznNSOuNLnF+hmabAu7H0LT4K7EdqfF+XUZW/2j
RKRYcvOUDGF9A7OjW7UfKk1In3+6QDCi7X34RE161jqoaJjrm/T18TOKcgkkhRzE
apQnIDm0Ea/HVzX/PiSOGuertwIDAQABMAsGCSqGSIb3DQEBBQOBgQBzMJdAV4QP
Awel8LzGx5uMOshezF/KfP67wJ93UW+N7zXY6AwPgoLj4Kjw+WtU684JL8Dtr9FX
ozakE+8p06BpxegR4BR3FMHf6p+0jQxUEAkAyb/mVgm66TyghDGC6/YkiKoZptXQ
98TwDIK/39WEB/V607As+KoYazQG8drorw==
-----END CERTIFICATE REQUEST-----
```

**Comment by ronf** [comment]
I don't believe so. It is legal to have multiple sections each delimited by "-----BEGIN <section_type>-----" and "-----END <section_type>-----" in the same file, and the parser can skip over some sections to get to whatever you are trying to load, or can load multiple sections in a case like loading multiple certificates that form a certificate chain. I don't believe any text is allowed outside of these section headers, though, ASCII or not.

**Comment by socketpair** [comment]
https://tools.ietf.org/html/rfc7468

**Comment by ronf** [comment]
For what its worth, the original question was about PEM, whereas RFC 7468 is a much more recent specification. I've run into problems in the past tools not handling files with such extra text outside of the PEM blocks. However, I'll concede given this new spec that it's probably worth allowing it, as long as you have some way of knowing the character encoding when dealing with non-ASCII encodings.

**Comment by reaperhulk** [comment]
I'm going to leave this open since RFC 7468 should probably be aspirational, but since the principle underlying library won't handle this well right now we'll have to implement stripping ourselves and that's not going to be high priority.

**Comment by alex** [comment]
After further review with @reaperhulk I'm going to close this. The only way to reliably support ASCII PEM boundaries inside arbitrary content is to treat that content as raw bytes; which is the format files are in.
