### ISSUE TITLE
pip install cryptography does not install version 1.6

### ISSUE THREAD

**Issue by rramani80** [pyca/cryptography#3237]
Any reason why pip install cryptography is not installing the latest version 1.6 and Or do i need to compile it from source

**Comment by alex** [comment]
There is no 1.6 release of cryptography, 1.5.3 is the most recent release.

**Comment by rramani80** [comment]
However in the documentation of x.509 cert object there is a method
signature_algorithm.oid which says it's only available in version 1.6

Ram

**Comment by alex** [comment]
Yes, that means it'll be available in the 1.6 release when that happens.

**Comment by rramani80** [comment]
Thank you Alex
