### ISSUE TITLE
ChaCha20 Support

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3264]
Two things to answer here. Are we going to add ChaCha20 (separate from ChaCha20Poly1305)? It can be useful as a component in constructing other things so I think the answer is yes.

If yes, then how do we want to handle nonce/iv? The spec calls it a 96-bit nonce/iv with a 32-bit block counter. OpenSSL treats it as a single 128-bit value. Do we want to just treat it as an opaque byte string or separate out the two arguments and have the backends compose them as necessary? I'm leaning towards opaque byte string and documenting the way in which they're concatenated.

refs #2968

**Comment by reaperhulk** [comment]
To thicken the plot a bit I haven't actually figured out how to make test vectors 2 and 3 pass (https://tools.ietf.org/html/rfc7539#appendix-A.2)

**Comment by ronf** [comment]
OpenSSH's version of Chacha20Poly1305 is different than what is used in TLS. As a result, I needed to be able to make separate calls to each of those to make things work. I'm currently using libnacl/libsodium for this, with some added shims to allow me to directly call some libsodium functions that libnacl doesn't normally expose. Specifically, here are the primitives I'm depending on:

For chacha20:

nacl.crypto_stream_chacha20_keybytes()
nacl.crypto_stream_chacha20_noncebytes()
nacl.crypto_stream_chacha20(buf, buflen, nonce, key)
nacl.crypto_stream_chacha20_xor_ic(outbuf, inbuf, buflen, nonce, ctr, key)

For poly1305:

nacl.crypto_onetimeauth_poly1305_bytes()
nacl.crypto_onetimeauth_poly1305_keybytes()
nacl.crypto_onetimeauth_poly1305(outtag, msg, msglen, polykey)
nacl.crypto_onetimeauth_poly1305_verify(intag, msg, msglen, polykey)

My wrappers look something like:

    crypt_chacha20(key, data, nonce, ctr) -> encrypted/decrypted data
    compute_poly1305_tag(data, nonce) -> tag
    verify_poly1305_tag(data, nonce, tag) -> bool

The high level API is:

    crypt_len(data, nonce) -> encrypted/decrypted data containing len
    encrypt_and_sign(header, plaintext, nonce) -> ciphertext, tag
    verify_and_decrypt(header, ciphertext, nonce, tag) -> plaintext or None (if verify fails)

The "header" here is a 32-bit length of the plaintext, and the nonce is a 64-bit counter that is incremented for each message. There are separate encrypt/decrypt calls for the header and message, with different chacha20 keys. Also, the header encrypt sets ctr=0 and the message encrypt sets ctr=1. The poly1305 tag is computed over the concatenation of the header and ciphertext and verified before the ciphertext is decrypted.

**Comment by reaperhulk** [comment]
Thanks for the info @ronf! Unfortunately for your purposes, OpenSSL doesn't expose poly1305 as an independent MAC (d'oh), but it's good to be aware of this use case for us.

**Comment by ronf** [comment]
No problem - while it'd be great to get all my crypto functions through a single dependency on "cryptography" eventually, the libnacl/libsodium version is working for me in the meantime.

**Comment by ronf** [comment]
The latest version of OpenSSL seems to now expose both ChaCha20 by itself (as EVP_chacha20) and Poly1305 by itself (using EVP_PKEY_POLY1305 in something like EVP_new_raw_private_key). Would it be possible to make a PyCA (non-AEAD) ChaCha20 cipher and a PyCA Poly1305 MAC using these? That would give me the primitives I need to implement the SSH variant of the AEAD ChaCha20-Poly1305 cipher/MAC combo.

I've managed to find the primitive Poly1305_* and ChaCha20_ctr32 functions in the OpenSSL library that could also be used for this via something like ctypes, but they are not part of the public API, so I really don't want to go that route. The right thing to do here is to go through the EVP layer, but I think it'd be better to do that using the usual abstractions PyCA provides.

**Comment by reaperhulk** [comment]
Looks like Poly1305 may work through `EVP_DigestSign*`. I'm :+1: on exposing these for exactly the reasons you need them (they're hazmat primitives useful for implementing things like ssh support)

**Comment by reaperhulk** [comment]
I probably shouldn't have reopened this since we did add ChaCha20 itself in cryptography 2.1, so going to close in favor of #4798
