### ISSUE TITLE
Mention the Linux packaging situation in our installation docs?

### ISSUE THREAD

**Issue by Ayrx** [pyca/cryptography#3280]
It was [brought up][0] that our installation docs do not mention that we are packaged by Linux distros. This may be a concern to some people. Do we want to fix that?

[0]: https://github.com/mailpile/Mailpile/pull/1684#issuecomment-262445332

**Comment by reaperhulk** [comment]
Based on that issue it looks like the idea is that users who want to go down the distribution path for obtaining their dependencies may not realize that we are packaged in every major distro at this point? I'm fine with mentioning we're packaged, but it should note that the way to get the most up to date version will always be PyPI.

I don't really want to wade into that issue right now but you might want to remind them that dlitz actively wants people to stop using PyCrypto. One prominent reason is that PyCrypto contains bespoke implementations of various primitives which are likely vulnerable to a variety of attacks. It is generally preferable to use more vetted code.

**Comment by alex** [comment]
I'm going to declare that the answer is "no". Using distro packaging produces are a horrible long tail of people using older versions with strange patches.
