### ISSUE TITLE
Symbol not found: _PyArg_UnplackTuple on Python 3.3 from python.org

### ISSUE THREAD

**Issue by jscottcarr** [pyca/cryptography#3284]
I've installed _cryptogrphy_ without errors.  All of the dependancies are met.  This is with Python 3.3 on the current release of MacOS (10.12).  I've installed cryptography in order to use jwcrypto.  But the import of cryptography is failing.

Here's the import line:

`from jwcrypto import jwt, jwk`

I get this error:
```pytb
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2403, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1794, in run
    launch(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Users/scottcarr/PycharmProjects/Participants/lion_bridge.py", line 1, in <module>
    from jwcrypto import jwt, jwk
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/jwcrypto/jwt.py", line 9, in <module>
    from jwcrypto.jwe import JWE
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/jwcrypto/jwe.py", line 10, in <module>
    from cryptography.hazmat.primitives import constant_time, hashes, hmac
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so, 2): Symbol not found: _PyArg_UnpackTuple
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so
  Expected in: /Library/Frameworks/Python.framework/Versions/3.3/Resources/Python.app/Contents/MacOS/Python
 in /Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so
```
Any help would be appreciated!

**Comment by gappleto97** [comment]
I'm also getting this.

https://travis-ci.org/p2p-today/p2p-project/jobs/179927248

**Comment by reaperhulk** [comment]
Hmm, it looks like the travis job is installing from python.org (version 3.3.5). @jscottcarr your paths also imply you're running using python.org python, is that the case?

I can't replicate this with 3.3.6 installed via pyenv, but before I go off building VMs I'd like to confirm that it's python.org python :)

**Comment by gappleto97** [comment]
Yes. Mine is installing via python.org's ftp server. Can't speak for @jscottcarr though

**Comment by reaperhulk** [comment]
Okay I've replicated the bug. Not sure what's going on here yet though

**Comment by jscottcarr** [comment]
Thanks Paul.  Standing by.  Let me know how I can help.

 

-- jsc

Scott Carr

**Comment by reaperhulk** [comment]
While I continue to be baffled, you should be able to work around the issue by doing this (assuming you have homebrew openssl installed):

`LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography --no-binary cryptography`

**Comment by reaperhulk** [comment]
That may not actually work unless you also uninstall cffi first (you'll need to make it `--no-binary cryptography,cffi` then). Please confirm that if you can!

**Comment by reaperhulk** [comment]
Brain dump of current situation:

* This has only been reported on Python 3.3.
* It occurs when installing the wheel built using pyenv python 3.3.6 (or 3.3.5, haven't tested older than that) but running on python.org 3.3.5.
* In both the working and failing case a dump of the symbol table via `nm` looks identical and shows:

```
                 U _PyArg_UnpackTuple
```
Additionally, the shared object shows that it's linked solely against libsystem. I believe `PyArg_UnpackTuple` should be provided by libpython, which is (presumably?) loaded when Python starts.

I'll investigate this more as time permits, but perhaps this information will help anyone else who might want to investigate.

**Comment by gappleto97** [comment]
Is it possible you're supposed to be using `PyArg_ParseTupleAndKeywords`? I have code in the linked test which use that method instead, and everything passes on that front.

**Comment by reaperhulk** [comment]
We no longer ship 3.3 wheels and 3.3 support is being dropped in the next release so time has solved this (very weird) issue on our behalf...
