### ISSUE TITLE
Need to access the actual name given for an OID and not just the dotted string

### ISSUE THREAD

**Issue by DelboyJay** [pyca/cryptography#3293]
Hi,

I'm porting from pyOpenSSL to Cryptography. I have some test cases that are comparing the values of the different subject attributes. Here is the pyOpenSSL code for what I was doing before:

self.assertEqual("MyCommonName", csr_cert_object.get_subject().CN)

How do I do this in the Cryptography library? It seems that I'm not supposed to access the NameAttribute->ObjectIdentifier->_name attribute and I cannot find a public method to get this value. Can we not also on top of what you already have and give access to the data in the same way as pyOpenSSL, as that is much more convenient?

**Comment by DelboyJay** [comment]
I found a way of doing what I need without accessing any protected variables. It's more code than would be needed for the pyOpenSSL approach but I guess it will have to do.

**Comment by reaperhulk** [comment]
The unfortunate reality is that those names are not really standardized and can vary by implementation (not for all of them, but it does happen). Due to that we don't want to commit to a public API exposing them. The best we can do is `NameOID.COMMON_NAME`, etc. Sorry 😢

**Comment by tiran** [comment]
@DelboyJay For CPython I created bindings for ```OBJ_txt2obj()``` and ```OBJ_nid2obj()```. ```OBJ_txt2obj()``` either takes an OID (second argument 0) or a name (short or long) and returns an ASN1_OBJECT. With the object you can fetch the NID which then allows you to fetch short name, long name and description.

All primitives are already available in cryptography. It's just a matter of reimplementing https://hg.python.org/cpython/file/tip/Modules/_ssl.c#l4133

**Comment by couling** [comment]
> The unfortunate reality is that those names are not really standardized and can vary by implementation (not for all of them, but it does happen). Due to that we don't want to commit to a public API exposing them. The best we can do is `NameOID.COMMON_NAME`, etc. Sorry

I'd like to ask for a little more detail on this decision.  Are the node names listed in the [RFCs](https://tools.ietf.org/html/rfc5280) incomplete or are they somehow not standard enough?

**Comment by reaperhulk** [comment]
There are multiple OIDs not listed in RFC5280 that are used in the wild, so yeah it's mostly a function of not being comfortable using names that are non-canonical. Users who want these types of names can quickly build their own object that allows assignment via string naming if they want.
