### ISSUE TITLE
Should we replace "unserialize" with "deserialize"?

### ISSUE THREAD

**Issue by jgehrcke** [pyca/cryptography#3338]
A few exception messages in cryptography's code base use the verb *"unserialize"* whereas the verb *"deserialize"* seems to be the more common (and correct?) one.

The same topic came up in the discussion around the Wikipedia article about Serialization where the (only) argument is:

> As far as I know, "deserialize" is the correct term. The article uses ["unserialize"] only for PHP, where the deserialization function is called "unserialize", and for external links, where the title uses this word.

([source](https://en.wikipedia.org/wiki/Talk:Serialization#Unserialize_or_deserialize.3F))

Certain applications might pass through this exception message to user-facing entities and then users might wonder about the weird verb "unserialize" -- that's why I think it's worth discussing a change towards the more common verb.

On the other hand, while application code should not too tightly depend on the exact exception message string emitted by this library, of course there is the risk of breakage (which is tolerable in this case, I think).

Happy to read about your opinions.

P.S. 

A colleague hypothesized that

> `de` is usually used with verbs, and `un` with adjectives.

There also is [a thread about the topic](https://www.reddit.com/r/lolphp/comments/247u3e/dear_god_today_i_just_realized_that_phps) in the "lolphp" subreddit, claiming that 

>  #php's `unserialize()` is grammatically incorrect. It should be `deserialize()`.

-- however, except for the usual funny-stupid arguments found there I didn't find a compelling explanation for _why_ it's incorrect.

In fact, someone in the thread even says 

> deserialize is grammatically valid (similar to decipher or decode), but unserialize is also grammatically valid (similar to undo or python's unpickle).

Another maybe interesting data point: a Google search for `unserialize site:python.org` yields ~ 400 search results, whereas the search term `deserialize site:python.org` yields ~ 2500 search results.

:christmas_tree: Isn't Christmas time the time to think about the boring stuff? :-)

**Comment by alex** [comment]
👍  for replacing unserialize with deserialize.

**Comment by jgehrcke** [comment]
Thanks for the quick response @alex! I submitted https://github.com/pyca/cryptography/pull/3339.
