### ISSUE TITLE
RC4 key size limit

### ISSUE THREAD

**Issue by palaviv** [pyca/cryptography#3340]
Why is RC4 key size limited to `[40, 56, 64, 80, 128, 160, 192, 256]` bit where it actually can be up to 2048 bit? In addition is there a specific reason this specific key sizes were chosen?

**Comment by reaperhulk** [comment]
The chosen key sizes are based on the existence of test vectors to confirm the implementation is correct for a given algorithm/key size. We don't expose primitives we can't verify.

**Comment by palaviv** [comment]
I actually found now that there was already an old issue about this #2494.
