### ISSUE TITLE
File encrypt/decrypt example in docs

### ISSUE THREAD

**Issue by dwich** [pyca/cryptography#3341]
I searched the docs and the web and couldn't find an example how to encrypt and decrypt a file. One famous example on StackOverflow is based on PyCrypto but I couldn't find any based on this project. PyCrypto is not maintained three years so I'm missing any safe example.

If there's any, could you please add to the docs? It would be helpful. Thanks a lot!

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/fernet/ is the best choice provided you are encrypting data small enough to be kept in memory. If not, https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/ provides examples for encrypting and decrypting in chunks.
