### ISSUE TITLE
_openssl.cpython-35m-x86_64-linux-gnu.so , is this file dynamically generated during installing?

### ISSUE THREAD

**Issue by mobilestack** [pyca/cryptography#3343]
`ImportError: /home/tony/.envs/p35_apns/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.cpython-35m-x86_64-linux-gnu.so: undefined symbol: EC_GROUP_new_curve_GF2m`

I used v1.7.1.  I met this error with a high possibility that due to my openssl version is not successfully upgraded to a bigger version than 1.0.0 . What I wonder how is that .so file is generated? And what dependencies does it need to be generated?

I will upgrade my openssl, configure its lib files, and reinstall cryptography. Besides this, do I need to recompile Python or nginx, etc?

**Comment by reaperhulk** [comment]
This typically occurs when there is a mismatch between the C headers and the actual OpenSSL library. With any linux distribution released in the past 4 years or so you just need a compiler and the openssl + dev package (as well as libffi + dev package for cffi). If you are attempting to upgrade OpenSSL independently from your distribution then things get much more complex and require significant knowledge of the C toolchain.

**Comment by mobilestack** [comment]
@reaperhulk thanks for your response. I have tried several time to upgrade openssl for my centOS 6.4, but failed. Noticed that our cloud server provider does not have an openssl dev package in line with the newer version openssl that I tried to install, neither can I download it from other way easily. Google around, tried hours and hours, not working.

So what I did is to use another new server, which is Ubuntu 16.04, since it is upgraded every 6 month with relatively new packages, now all works fine now.

**Comment by archit1012** [comment]
I have 2 machines both has same "uname -a" and openssl version "OpenSSL 1.0.1e-fips 11 Feb 2013"
one is VM and other is physical machine, 
build works fine on VM but this two libraries (_ssl.cpython-35m-x86_64-linux-gnu.so, 
_hashlib.cpython-35m-x86_64-linux-gnu.so) are missing from build on physical machine ...

What could be the issue?

**Comment by reaperhulk** [comment]
Those two libraries are both part of the standard library of python and are unrelated to pyca/cryptography, sorry.
