### ISSUE TITLE
Enable Cryptography_STATIC_CALLBACKS for Python 3

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#3348]
Now with locks and osrandom engine in C, is there any reason left to use dynamic callbacks for Python 3.5+? src/_cffi_src/openssl/callbacks.py still has the workaround for #2970. Starting with 1.7.0, ```bindings.ffi_callback()``` is only used for the password callback.

**Comment by reaperhulk** [comment]
Yep we can revert that now.
