### ISSUE TITLE
Replace pyasn1 with asn1crypto

### ISSUE THREAD

**Issue by ofek** [pyca/cryptography#3363]
Replacing pyasn1 with @wbond's excellent  [asn1crypto](https://github.com/wbond/asn1crypto) will result in a non-trivial performance increase (4x based on decoding tests) ameliorating our [public key digest computation](https://github.com/pyca/cryptography/pull/3361#issuecomment-274328410) situation, better extensibility in future, access to a pythonic API, and the removal of our pyasn1_modules test dependency.

Conversion is complete in #3361.

**Comment by wbond** [comment]
@ofek Just for your info, some previous conversation happened at #2162
