### ISSUE TITLE
LibreSSL 2.5.1 includes (some) 102_VERIFICATION_ERROR_CODES

### ISSUE THREAD

**Issue by lluixhi** [pyca/cryptography#3378]
Specifically, it adds:
```
X509_V_ERR_HOSTNAME_MISMATCH
X509_V_ERR_EMAIL_MISMATCH
X509_V_ERR_IP_ADDRESS_MISMATCH
```

So at the moment the build fails.

Is it wise to add another define so that with LibreSSL 2.5.1+ cryptography will report those errors? Or does this make the code too complex?

**Comment by lluixhi** [comment]
Here's the kludgy solution that simply prevents the compile-time error:
```
diff -Naur cryptography-1.7.1.orig/src/_cffi_src/openssl/x509_vfy.py cryptography-1.7.1/src/_cffi_src/openssl/x509_vfy.py
--- cryptography-1.7.1.orig/src/_cffi_src/openssl/x509_vfy.py	2017-02-01 12:29:59.080728417 -0800
+++ cryptography-1.7.1/src/_cffi_src/openssl/x509_vfy.py	2017-02-01 12:31:48.017895844 -0800
@@ -221,10 +221,13 @@
 static const long X509_V_ERR_SUITE_B_INVALID_SIGNATURE_ALGORITHM = 0;
 static const long X509_V_ERR_SUITE_B_LOS_NOT_ALLOWED = 0;
 static const long X509_V_ERR_SUITE_B_CANNOT_SIGN_P_384_WITH_P_256 = 0;
+#if !CRYPTOGRAPHY_OPENSSL_102BETA2_OR_GREATER || \
+    (defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER < 0x2050100fL)
 static const long X509_V_ERR_HOSTNAME_MISMATCH = 0;
 static const long X509_V_ERR_EMAIL_MISMATCH = 0;
 static const long X509_V_ERR_IP_ADDRESS_MISMATCH = 0;
 #endif
+#endif
 
 /* OpenSSL 1.0.2beta2+ verification parameters */
 #if CRYPTOGRAPHY_OPENSSL_102BETA2_OR_GREATER && \
```

**Comment by lluixhi** [comment]
Just saw #3247, is this still relevant?

**Comment by lluixhi** [comment]
Actually reading that issue, and seeing that 2.5.1 does not include any of those functions, all we can do is hide it behind that conditional, isn't it..

**Comment by reaperhulk** [comment]
libressl.org still lists 2.5.x as a dev release. Does a version of OpenBSD ship with it? I'm pretty annoyed that they added those constants but forgot to actually add the functions, so I'm disinclined to try supporting a broken version unless it's shipping actively.

**Comment by reaperhulk** [comment]
I'm going to close this to consolidate into #3247. We can continue conversation there.
