### ISSUE TITLE
cryptography is missing the possibility to read CSR attributes?

### ISSUE THREAD

**Issue by AnthonyDeroche** [pyca/cryptography#3384]
Hello,

I'm trying to read custom attributes embedded in CSR with the lib and I'm not able to do so.

Attributes are display by openssl -req [...] -text just before the "requested extensions" section and after the "subject public key info" section.

There is a getter named "X509_REQ_get_attr" in the C code of openssl, so I assume it is possible to get them easily using appropriate binding.

Any help would be great!

Thanks

**Comment by reaperhulk** [comment]
You are correct that cryptography currently doesn't support custom attributes in x509 requests, only requested extensions. Adding this feature is certainly possible, but will require adding bindings and then proposing and implementing an API.

**Comment by wilrodriguez** [comment]
This would be a really helpful feature. I'm hoping to add a challenge password to my CSRs.
