### ISSUE TITLE
Can't install on VirtualEnv - Fedora 25

### ISSUE THREAD

**Issue by fanttazio** [pyca/cryptography#3386]
Hello,

I have been able to install Cryptography on Fedora 25 but when I activate my VirtualEnv, I'm not able to install it on that environment:

Confirming installation on OS itself:
[osboxes@osboxes CiscoDevNet]$ pip3 list | grep crypto
cryptography (1.5.3)
[osboxes@osboxes CiscoDevNet]$

I've pasted the output to Pastebin to avoid making this thread big -->   [http://pastebin.com/DQwsCSCa]

[osboxes@osboxes CiscoDevNet]$ python3 -V
Python 3.5.2
[osboxes@osboxes CiscoDevNet]$ pip3 -V
pip 9.0.1 from /usr/lib/python3.5/site-packages (python 3.5)

Any idea what I'm missing?

Thanks

**Comment by alex** [comment]
```
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
```

something appears to be wrong with your GCC/build chain. I don't know anything about fedora, but that's your issue, this is not a cryptography bug.

**Comment by tiran** [comment]
You are missing a package: 
```
dnf install redhat-rpm-config
```

**Comment by fanttazio** [comment]
@tiran Thanks man. It fixed the problem.
