### ISSUE TITLE
64 bit key size for Fernet

### ISSUE THREAD

**Issue by erikreppel** [pyca/cryptography#3397]
We would really like to be able to use 64byte instead of 32byte keys with `fernet` but the class is currently hard coded to [only allow 32byte key](https://github.com/pyca/cryptography/blob/master/src/cryptography/fernet.py#L35). Would you guys be willing to accept a pr that also allows for 64byte keys?

**Comment by alex** [comment]
Do you mean 64-byte?

Fernet implements an existing standard, so if you want to propose changes it should go to the spec's repo first.

**Comment by erikreppel** [comment]
Yeah, sorry, under caffeinated, 64byte

**Comment by reaperhulk** [comment]
Since this is a spec issue I'm going to go ahead and close it here.
