### ISSUE TITLE
x509.serial deprecation not in changelog

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#3398]
```x.509.serial``` was deprecated in favor of ```x509.serial_number``` in version 1.4. Deprecation was added in commit e295f3ab615775c3549b7bc2e051af5cff801619. Changelog for 1.4 https://cryptography.readthedocs.io/en/latest/changelog/#id9 doesn't mention deprecation.

Could you please update the changelog with deprecation information?

**Comment by reaperhulk** [comment]
I would look favorably upon a PR 👍

**Comment by tiran** [comment]
thx :)

I was too busy to create a PR in time.
