### ISSUE TITLE
Does this package support Python 3?

### ISSUE THREAD

**Issue by cclauss** [pyca/cryptography#3400]
On 19 February 2017, Python 3 will be 3,000 days old!  We are interested to see if we can get **at least 50%** of the [Top 5,000 PyPI packages](http://python3wos.mybluemix.net/5000) to compatible with Python 3 by that date.  We are *really* close and given that this package is in the PyPI Top 5,000, we seek your assistance in pushing us over that threshold.

  So, if this package *already supports Python 3* then please consider adding an appropriate [trove classifier](https://pypi.python.org/pypi?%3Aaction=list_classifiers) "*Programming Language :: Python :: 3*" to this package's PyPI page so that tools can automaticly determine its Python 3 compatibility.

**Comment by reaperhulk** [comment]
Sigh, automated issues. For future people searching: cryptography supports Python 3 and has since it was created. Our trove classifiers are specific to Python 3.x version though, which is what caused this issue to be filed.

**Comment by mithrandi** [comment]
In addition, the generic classifier appears to be there already:

https://github.com/pyca/cryptography/blob/a39b20d6fff2c943cca15139605c73ded0d070f0/setup.py#L295

https://pypi.python.org/pypi/cryptography
