### ISSUE TITLE
Support for globally suppressing library linking flags on non-Windows platforms

### ISSUE THREAD

**Issue by maxbelanger** [pyca/cryptography#3403]
In our tooling, we use a custom library name (`ssl-static` and `crypto-static`) to differentiate static builds of OpenSSL and simplify linking with other libraries. We'd like the ability to suppress the `-lssl -lcrypto` globally (not just on macOS) so that we can use `LDFLAGS` et al when building through `requirements.txt` file. Here's a [patch](https://gist.github.com/maxbelanger/cc7762a70c8a6bf73beb9b065a3e6a12) demonstrating what we currently do (not a PR as I suspect this isn't correct beyond our use). What would be the best way to achieve this?

**Comment by alex** [comment]
@reaperhulk do you have an opinion here?

**Comment by reaperhulk** [comment]
I talked a bit with @irinarentaria about this a few weeks ago. I believe she's planning to send a PR with a more generic set of env vars. I'm fine with it becoming more generic.
