### ISSUE TITLE
linking against OpenSSL broken due to partially missing EC symbols

### ISSUE THREAD

**Issue by phi-gamma** [pyca/cryptography#3419]
Linking of the latest Git master (500047b1c3cbfbd8f4ad6f52865ed98cd59fecb3)
fails on FC25:

    building '_openssl' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o -L/usr/lib64 -lssl -lcrypto -lpython2.7 -o /mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/src/cryptography/hazmat/bindings/_openssl.so
    building '_constant_time' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_constant_time.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_constant_time.o
    gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_constant_time.o -L/usr/lib64 -lpython2.7 -o /mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/src/cryptography/hazmat/bindings/_constant_time.so
    building '_padding' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_padding.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_padding.o
    gcc -pthread -shared -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_padding.o -L/usr/lib64 -lpython2.7 -o /mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/src/cryptography/hazmat/bindings/_padding.so
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/_pytest/config.py", line 320, in _importconftest
        mod = conftestpath.pyimport()                                                                       
      File "/usr/lib/python2.7/site-packages/py/_path/local.py", line 662, in pyimport
        __import__(modname)                                                                                 
      File "/mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/tests/conftest.py", line 10, in <module>
        from cryptography.hazmat.backends.openssl import backend as openssl_backend                         
      File "/mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/src/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>                                                                              
        from cryptography.hazmat.backends.openssl.backend import backend                                    
      File "/mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/src/cryptography/hazmat/backends/openssl/backend.py", line 48, in <module>                                                                              
        from cryptography.hazmat.bindings._openssl import lib as _lib                                       
    ImportError: /mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/src/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_POINT_set_affine_coordinates_GF2m                                               
    ERROR: could not load /mnt/local/rpmbuild/BUILD/cryptography-1.8.dev1/tests/conftest.py
    
    error: Bad exit status from /var/tmp/rpm-tmp.AVKlbD (%check)

Note that Fedora ships a crippled version of OpenSSL (1.0.2k) that lacks a
number of symbols whose presence python-cryptography assumes. Defining
``OPENSSL_NO_EC2M`` doesn’t seem to do the trick. I had to patch the sources
like so:

    diff --git a/src/_cffi_src/openssl/ec.py b/src/_cffi_src/openssl/ec.py
    index d1745054..a88c4cb2 100644
    --- a/src/_cffi_src/openssl/ec.py
    +++ b/src/_cffi_src/openssl/ec.py
    @@ -45,18 +45,24 @@ void EC_GROUP_clear_free(EC_GROUP *);
     
     EC_GROUP *EC_GROUP_new_curve_GFp(
         const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *);
    +/*
     EC_GROUP *EC_GROUP_new_curve_GF2m(
         const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *);
    +*/
     EC_GROUP *EC_GROUP_new_by_curve_name(int);
     
     int EC_GROUP_set_curve_GFp(
         EC_GROUP *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *);
     int EC_GROUP_get_curve_GFp(
         const EC_GROUP *, BIGNUM *, BIGNUM *, BIGNUM *, BN_CTX *);
    +/*
     int EC_GROUP_set_curve_GF2m(
         EC_GROUP *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *);
    +*/
    +/*
     int EC_GROUP_get_curve_GF2m(
         const EC_GROUP *, BIGNUM *, BIGNUM *, BIGNUM *, BN_CTX *);
    +*/
     
     int EC_GROUP_get_degree(const EC_GROUP *);
     void EC_GROUP_set_asn1_flag(EC_GROUP *, int);
    @@ -119,14 +125,20 @@ int EC_POINT_get_affine_coordinates_GFp(const EC_GROUP *,
     int EC_POINT_set_compressed_coordinates_GFp(const EC_GROUP *, EC_POINT *,
         const BIGNUM *, int, BN_CTX *);
     
    +/*
     int EC_POINT_set_affine_coordinates_GF2m(const EC_GROUP *, EC_POINT *,
         const BIGNUM *, const BIGNUM *, BN_CTX *);
    +*/
     
    +/*
     int EC_POINT_get_affine_coordinates_GF2m(const EC_GROUP *,
         const EC_POINT *, BIGNUM *, BIGNUM *, BN_CTX *);
    +*/
     
    +/*
     int EC_POINT_set_compressed_coordinates_GF2m(const EC_GROUP *, EC_POINT *,
         const BIGNUM *, int, BN_CTX *);
    +*/
     
     size_t EC_POINT_point2oct(const EC_GROUP *, const EC_POINT *,
         point_conversion_form_t,
    @@ -175,7 +187,9 @@ const EC_METHOD *EC_GFp_simple_method();
     const EC_METHOD *EC_GFp_mont_method();
     const EC_METHOD *EC_GFp_nist_method();
     
    +/*
     const EC_METHOD *EC_GF2m_simple_method();
    +*/
     
     int EC_METHOD_get_field_type(const EC_METHOD *);
     
    @@ -339,25 +353,39 @@ static const long Cryptography_HAS_EC = 1;
     #if defined(OPENSSL_NO_EC) || defined(OPENSSL_NO_EC2M)
     static const long Cryptography_HAS_EC2M = 0;
     
    +/*
     const EC_METHOD *(*EC_GF2m_simple_method)() = NULL;
    +*/
     
    +/*
     int (*EC_POINT_set_affine_coordinates_GF2m)(const EC_GROUP *, EC_POINT *,
         const BIGNUM *, const BIGNUM *, BN_CTX *) = NULL;
    +*/
     
    +/*
     int (*EC_POINT_get_affine_coordinates_GF2m)(const EC_GROUP *,
         const EC_POINT *, BIGNUM *, BIGNUM *, BN_CTX *) = NULL;
    +*/
     
    +/*
     int (*EC_POINT_set_compressed_coordinates_GF2m)(const EC_GROUP *, EC_POINT *,
         const BIGNUM *, int, BN_CTX *) = NULL;
    +*/
     
    +/*
     int (*EC_GROUP_set_curve_GF2m)(
         EC_GROUP *, const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *);
    +*/
     
    +/*
     int (*EC_GROUP_get_curve_GF2m)(
         const EC_GROUP *, BIGNUM *, BIGNUM *, BIGNUM *, BN_CTX *);
    +*/
     
    +/*
     EC_GROUP *(*EC_GROUP_new_curve_GF2m)(
         const BIGNUM *, const BIGNUM *, const BIGNUM *, BN_CTX *);
    +*/
     #else
     static const long Cryptography_HAS_EC2M = 1;
     #endif

**Comment by reaperhulk** [comment]
cc @tiran since I'd like to know why FC25's OpenSSL is missing symbols that we should be able to detect via preprocessor variables. (Or maybe we have a bug)

**Comment by reaperhulk** [comment]
I just built a Fedora 25 docker image (`docker run -ti fedora:25 /bin/bash`), installed the requisite dependencies:

```
dnf install openssl-devel libffi-devel gcc python-devel git python-virtualenv redhat-rpm-config
git clone https://github.com/pyca/cryptography
cd cryptography
virtualenv .venv
source .venv/bin/activate
pip install .
python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"
```

This worked without error. Since this is working in a vanilla Fedora 25 environment I'm going to go ahead and close this, but if you can figure out what is triggering it in your specific case and it turns out to be a cryptography bug please file a new issue.
