### ISSUE TITLE
Fix idna exception

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3424]
Version 2.3 (released today) contains this change: https://github.com/kjd/idna/commit/ebefacd3134d0f5da4745878620a6a1cba86d130

This causes one of our tests to fail and our documentation to be wrong, as `UnicodeError` is no longer the base exception class for errors with idna encode/decode. The simplest fix is probably to just add to wrapper functions _idna_encode and _idna_decode that just try: idna.{en,de}code() except IDNAError: raise UnicodeError

**Comment by alex** [comment]
Should we reach out to upstream to confirm this isn't a bug?

**Comment by reaperhulk** [comment]
We certainly can. A change in exception hierarchy like this is a pretty big interface break. Maybe there's another way to make the change they need without doing this, I don't know.

**Comment by Lukasa** [comment]
So my understanding of *why* upstream did this is kjd/idna#36: specifically, that in [these lines of code](https://github.com/kjd/idna/blob/master/idna/core.py#L266-L270) an `idna` exception is thrown, and there is a `except UnicodeError: pass` block there. Now, the easiest way to escape this was to make the change that was made in `idna`, but it certainly isn't the only way: for example, the block could have checked for the more specific exception first and re-raised. Regardless, it may be worth reaching out.

**Comment by reaperhulk** [comment]
Filed as https://github.com/kjd/idna/issues/43

**Comment by reaperhulk** [comment]
(Resolved with idna 2.4)
