### ISSUE TITLE
how much ram does this package require?

### ISSUE THREAD

**Issue by rlam3** [pyca/cryptography#3443]
how much ram does this package require?
i'm running into installation problems with this package due to virtual memory running out

**Comment by alex** [comment]
To install, or to import?

**Comment by reaperhulk** [comment]
cryptography requires a significant amount of RAM to compile due to the way it does code generation and how gcc handles large files. You can potentially lower the RAM requirement a bit by using clang, but for now this remains a limitation.

**Comment by rlam3** [comment]
is there a workaround when you have only 1 gig on server?

**Comment by reaperhulk** [comment]
I believe 1GB is generally enough, but if you're running out you can enable swap temporarily, build it on another VM with the same packages and transfer over a wheel, install it from your OS (if you're on a recent distro), or install clang and do `CC=clang pip install cryptography` and see if that helps.
