### ISSUE TITLE
Cryptography Installation is failing with error error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by pgbidkar** [pyca/cryptography#3444]
Platform Details:
OS: CentOS
Python Version: 3.6 & 2.7.13
openssl version: OpenSSL 1.0.2k  26 Jan 2017

Installed prerequired packages
(PY36) [worker@sc2-rdops-vm02-dhcp-95-86 PY36]$ sudo yum install gcc libffi-devel python-devel openssl-devel
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * epel: mirror.sjc02.svwh.net
Setting up Install Process
Package gcc-4.4.7-3.el6.x86_64 already installed and latest version
Package libffi-devel-3.0.5-3.2.el6.x86_64 already installed and latest version
Package python-devel-2.6.6-37.el6_4.x86_64 already installed and latest version
Package openssl-devel-1.0.0-27.el6_4.2.x86_64 already installed and latest version
Nothing to do

Cryptography Installation is failing with error
 gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/worker/PY36/include -I/usr/local/lib/python3.6.0/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o
    build/temp.linux-x86_64-3.6/_openssl.c:478:26: error: openssl/cmac.h: No such file or directory
    build/temp.linux-x86_64-3.6/_openssl.c:2185: warning: function declaration isn’t a prototype
    build/temp.linux-x86_64-3.6/_openssl.c:2186: warning: function declaration isn’t a prototype
    build/temp.linux-x86_64-3.6/_openssl.c:2187: warning: function declaration isn’t a prototype
    build/temp.linux-x86_64-3.6/_openssl.c:2204: warning: function declaration isn’t a prototype
    build/temp.linux-x86_64-3.6/_openssl.c:2262: warning: function declaration isn’t a prototype
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_const_OPENSSL_NPN_NEGOTIATED’:
    build/temp.linux-x86_64-3.6/_openssl.c:10486: error: ‘OPENSSL_NPN_NEGOTIATED’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:10486: error: (Each undeclared identifier is reported only once
    build/temp.linux-x86_64-3.6/_openssl.c:10486: error: for each function it appears in.)
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:21028: error: expected ‘)’ before ‘*’ token
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_CMAC_CTX_copy’:
    build/temp.linux-x86_64-3.6/_openssl.c:21036: error: ‘CMAC_CTX’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21036: error: ‘x0’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21037: error: expected ‘;’ before ‘const’
    build/temp.linux-x86_64-3.6/_openssl.c:21051: error: expected expression before ‘)’ token
    build/temp.linux-x86_64-3.6/_openssl.c:21058: error: ‘x1’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21062: error: expected ‘)’ before ‘const’
    build/temp.linux-x86_64-3.6/_openssl.c:21062: error: expected ‘;’ before ‘__builtin_alloca’
    build/temp.linux-x86_64-3.6/_openssl.c:21070: warning: implicit declaration of function ‘CMAC_CTX_copy’
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:21081: error: expected ‘)’ before ‘*’ token
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_CMAC_CTX_free’:
    build/temp.linux-x86_64-3.6/_openssl.c:21089: error: ‘CMAC_CTX’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21089: error: ‘x0’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21097: error: expected expression before ‘)’ token
    build/temp.linux-x86_64-3.6/_openssl.c:21105: warning: implicit declaration of function ‘CMAC_CTX_free’
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:21117: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_CMAC_CTX_new’:
    build/temp.linux-x86_64-3.6/_openssl.c:21125: error: ‘CMAC_CTX’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21125: error: ‘result’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21129: warning: implicit declaration of function ‘CMAC_CTX_new’
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:21141: error: expected ‘)’ before ‘*’ token
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_CMAC_Final’:
    build/temp.linux-x86_64-3.6/_openssl.c:21149: error: ‘CMAC_CTX’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21149: error: ‘x0’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21166: error: expected expression before ‘)’ token
    build/temp.linux-x86_64-3.6/_openssl.c:21196: warning: implicit declaration of function ‘CMAC_Final’
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:21207: error: expected ‘)’ before ‘*’ token
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_CMAC_Init’:
    build/temp.linux-x86_64-3.6/_openssl.c:21215: error: ‘CMAC_CTX’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21215: error: ‘x0’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21236: error: expected expression before ‘)’ token
    build/temp.linux-x86_64-3.6/_openssl.c:21281: warning: implicit declaration of function ‘CMAC_Init’
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:21292: error: expected ‘)’ before ‘*’ token
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_f_CMAC_Update’:
    build/temp.linux-x86_64-3.6/_openssl.c:21300: error: ‘CMAC_CTX’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21300: error: ‘x0’ undeclared (first use in this function)
    build/temp.linux-x86_64-3.6/_openssl.c:21317: error: expected expression before ‘)’ token
    build/temp.linux-x86_64-3.6/_openssl.c:21340: warning: implicit declaration of function ‘CMAC_Update’
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_EVP_PKEY_CTX_set_rsa_mgf1_md’:
    build/temp.linux-x86_64-3.6/_openssl.c:35835: warning: implicit declaration of function ‘EVP_PKEY_CTX_set_rsa_mgf1_md’
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_SSL_CTX_set_next_proto_select_cb’:
    build/temp.linux-x86_64-3.6/_openssl.c:49156: warning: implicit declaration of function ‘SSL_CTX_set_next_proto_select_cb’
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_SSL_CTX_set_next_protos_advertised_cb’:
    build/temp.linux-x86_64-3.6/_openssl.c:49215: warning: implicit declaration of function ‘SSL_CTX_set_next_protos_advertised_cb’
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_SSL_SESSION_set1_id_context’:
    build/temp.linux-x86_64-3.6/_openssl.c:50475: warning: implicit declaration of function ‘SSL_SESSION_set1_id_context’
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_SSL_get0_next_proto_negotiated’:
    build/temp.linux-x86_64-3.6/_openssl.c:50708: warning: implicit declaration of function ‘SSL_get0_next_proto_negotiated’
    build/temp.linux-x86_64-3.6/_openssl.c: In function ‘_cffi_d_SSL_select_next_proto’:
    build/temp.linux-x86_64-3.6/_openssl.c:52547: warning: implicit declaration of function ‘SSL_select_next_proto’
    build/temp.linux-x86_64-3.6/_openssl.c: At top level:
    build/temp.linux-x86_64-3.6/_openssl.c:70839: error: ‘_cffi_d_CMAC_CTX_copy’ undeclared here (not in a function)
    build/temp.linux-x86_64-3.6/_openssl.c:70840: error: ‘_cffi_d_CMAC_CTX_free’ undeclared here (not in a function)
    build/temp.linux-x86_64-3.6/_openssl.c:70841: error: ‘_cffi_d_CMAC_CTX_new’ undeclared here (not in a function)
    build/temp.linux-x86_64-3.6/_openssl.c:70842: error: ‘_cffi_d_CMAC_Final’ undeclared here (not in a function)
    build/temp.linux-x86_64-3.6/_openssl.c:70843: error: ‘_cffi_d_CMAC_Init’ undeclared here (not in a function)
    build/temp.linux-x86_64-3.6/_openssl.c:70844: error: ‘_cffi_d_CMAC_Update’ undeclared here (not in a function)
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/worker/PY36/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wp5m96dy/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pig037j1-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/worker/PY36/include/site/python3.6/cryptography" failed with error code 1 in /tmp/pip-build-wp5m96dy/cryptography/

**Comment by reaperhulk** [comment]
This is a header/linker mismatch between the custom OpenSSL you've installed and the one that comes with your CentOS. Linking against custom OpenSSL can be very challenging on linux and is outside the scope of support we can provide here. We do have some information to help, but it's still difficult to get right: https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-linux

**Comment by lxw0109** [comment]
Hi, @pgbidkar . I got the same error information, how did you fix it?  : )

**Comment by pgbidkar** [comment]
Hi @lxw0109 You tried installing $sudo yum install gcc libffi-devel python-devel openssl-devel?

Thanks

**Comment by lxw0109** [comment]
@pgbidkar Thank you. In my situation, it's still not working after installing the above packages(My fault, this is because of my outdated software sources, please read on). 
When I read [this page](https://github.com/pyca/cryptography/issues/3376), I think maybe I have installed some packages with outdated version. So I ran the following commands:
```bash
$ sudo apt-get update
$ sudo apt-get upgrade --fix-missing
```
It works. 
I think if I installed the required version of packages you suggested, it might be working. Thank you.
