### ISSUE TITLE
Is AES-256 supported?

### ISSUE THREAD

**Issue by tedmiston** [pyca/cryptography#3446]
Hi, I'm working on a project that shares encrypted values with an existing Node system using AES 256 via [crypto-js][1].  What I would like to do is encrypt / decrypt the values in Python with cryptography as well.

I'm trying to understand if AES 256 is currently supported?

I wasn't able to answer this clearly myself from the docs.  For example, I see references to 256-bit key sizes in [some tests][2] and mentions of 256-bit keys in [the AES algorithm class docs][3] but the Fernet class (which seems to be the encouraged app user level interface) looks to use 128 bits for the AES key per the docs and linked spec.  On the other hand, this library seems to be referenced as the modern replacement for others such as PyCrypto.

AES 256 seems like a common use case, so finding myself poking around the hazmat layer concerned me that I may be missing a higher level interface like the Fernet class but using AES 256.

[1]: https://www.npmjs.com/package/crypto-js
[2]: https://github.com/pyca/cryptography/blob/a5865d9b630df7586785b683ed145b977ad7e0c4/tests/hazmat/primitives/test_aes.py#L195
[3]: https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/?highlight=aes#cryptography.hazmat.primitives.ciphers.algorithms.AES

**Comment by alex** [comment]
Yes, cryptography supports AES256, as this example demonstrates: https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/?highlight=aes#cryptography.hazmat.primitives.ciphers.Cipher

Fernet is a specific recipe that implements a pre-defined protocol, it happens to use AES128.

**Comment by tedmiston** [comment]
Thank you, @alex — exactly what I was looking for.

**Comment by dahiya2495** [comment]
`if encryption_format == AES256:
            chunksize = 64*1024
            outputfile = "test.xlsx"
            filesize = str(os.path.getsize(input_file)).zfill(32)
            IV = ''

            for i in range(16):
                IV += chr(random.randint(0, 0xFF))

            encryptor = AES.new(encryption_key, AES.MODE_CBC, IV)

            with open(input_file, 'rb') as infile:
                with open(outputfile, 'wb') as output_file:
                    output_file.write(filesize)
                    output_file.write(IV)

                    while True:
                        chunk = infile.read(chunksize)

                        if len(chunk) == 0:
                            break
                        elif len(chunk) % 32 != 0:
                            chunk += ' ' * (32 - (len(chunk) % 32))

                        output_file.write(encryptor.encrypt(chunk))`
