### ISSUE TITLE
Please can you add X509_STORE_CTX_get0_cert() to the OpenSSL ffi?

### ISSUE THREAD

**Issue by omnicognate** [pyca/cryptography#3454]
This method is needed in order to get the cert that is being validated, given an X509_STORE_CTX*. Prior to 1.1.0 , this information was obtained by directly getting the "cert" member of the struct this pointed to, but in 1.1.0 this struct has been made internal/opaque and its layout changed. The X509_STORE_CTX_get0_cert() accessor was added at this time. Without it, SSL_CTX_set_cert_verify_callback(), which is in the ffi, is useless because you can't get the cert in your callback implementation.

**Comment by reaperhulk** [comment]
Thanks for the report -- makes sense to me. #3455 adds this.

**Comment by omnicognate** [comment]
That was quick - thanks!
