### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'libeay32.lib'

### ISSUE THREAD

**Issue by Headmaster11** [pyca/cryptography#3483]
When I try to install cryptography, I get the following error:
LINK : fatal error LNK1181: cannot open input file 'libeay32.lib'

How to fix this?

system: windows 7, 64-bit

**Comment by alex** [comment]
Can you please provide the full error message? Also, what version of `pip` are you using?

**Comment by Headmaster11** [comment]
Yes, problem was in pip version. Thanks for help

Maybe it would help someone in future:
if you use `pip==7.0.1` you should upgrade it

**Comment by alex** [comment]
Glad to hear that upgrading `pip` fixed the issue.
