### ISSUE TITLE
utils.int_to_bytes behavior on 0s

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3493]
It currently returns `b"\x00"`. Is that correct, or should it return `b""`?

All the callers but one provide an explicit length, so they're not effected. The only effected called site is in the SSH key serializer.

**Comment by reaperhulk** [comment]
Without considering implementation complexity I'd say the "proper" byte serialization of a zero is a null byte and not an empty byte string.

**Comment by alex** [comment]
Ok, looking at what twisted does in the case of `0`, it's also not an empty string. I declare this case to be uninteresting. Sorry for wasting everyone's time.
