### ISSUE TITLE
expose property or method for modulus data on x509, req and rsa objects 

### ISSUE THREAD

**Issue by scottidler** [pyca/cryptography#3494]
I looked through the documentation [here]( https://cryptography.io/en/latest/) as well as the source code [here](https://github.com/pyca/cryptography) and can't find a way to access the **modulus** data for these three ssl objects.  I want to correlate the three objects through their modulus values.  Here I have piped through an md5 hash for brevity.

`$> openssl rsa -in some-name.key -modulus -noout 2>/dev/null | openssl md5`
`$> (stdin)= b88611656cf12d5b17186483e4b4d1b8`
`$> openssl req -in some-name.csr -modulus -noout 2>/dev/null | openssl md5`
`$> (stdin)= b88611656cf12d5b17186483e4b4d1b8`
`$> openssl x509 -in some-name.crt -modulus -noout 2>/dev/null | openssl md5`
`$> (stdin)= b88611656cf12d5b17186483e4b4d1b8`

Please note that the three values are the same as these objects are related: x509 -> req-> crt

1) If this is possible, the documentation should be updated to show how
2) If not, the code should be updated to have a property or method to access these values
3) Otherwise, state explicitly that this will not be developed

**Comment by reaperhulk** [comment]
The modulus you're looking for will be `cert.public_key().public_numbers().n`. Note that is the decimal value and not a big-endian byte string, but for the purposes of comparison you don't need to do this at all and can instead do `cert.public_key().public_numbers() == csr.public_key().public_numbers()` (The numbers objects implement `__eq__`).

If you have ideas of where this can be added to the documentation please send a PR!

**Comment by alex** [comment]
I'm going to close this, since this functionality does exist. To echo @reaperhulk though, if there are ways we could improve our documentation, please file bugs!

**Comment by scottidler** [comment]
Thank you very much for the information.  I agree the ability to compare, via a decimal in this case, is part of what I am after.  However, the hashes will be different if I use this decimal from pyca/cryptograpy and the openssl cli tool uses the character bytes.  I would like both to match.  So in that sense the interface available is **not** exposed in pyca/cryptography.  It also sounds like it is not something you are planning to implement.  But I do have my answer, so thank you.

**Comment by scottidler** [comment]
```python
def _create_modhash(key):                                                       
    modulus_int = key.private_numbers().public_numbers.n                        
    modulus_hex = hex(modulus_int).rstrip('L').lstrip('0x').upper()             
    modulus_bytes = 'Modulus={modulus_hex}\n'.format(**locals()).encode('utf-8')              
    md5 = hashlib.md5()                                                         
    md5.update(modulus_bytes)                                                   
    return md5.hexdigest() 
```
I was able get the hash value I was after thanks to @reaperhulk mention above.  I am leaving this here in case anyone wants to see how to do this.
