### ISSUE TITLE
1.8.1 fails to build with libressl-2.5.3

### ISSUE THREAD

**Issue by Gottox** [pyca/cryptography#3500]
python-cryptography fails to build with the newest libressl release due to added defines.

The issue can be fixed by adding this patch: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/python-cryptography/patches/fix-libressl-2.5.3.patch

**Comment by ryandesign** [comment]
Looks like a duplicate of #3247.

**Comment by alex** [comment]
Yes, this is a dupe of that.
