### ISSUE TITLE
wishlist: DTLS 1.2 methods

### ISSUE THREAD

**Issue by chrysn** [pyca/cryptography#3501]
Please consider adding the ``DTLSv1_2_*method`` symbols to the openssl bindings (``DTLSv1_*method`` are present at least in the latest release, but the newer ``DTLS_*method`` and the ``DTLSv1_2_*method`` are missing). It seems to me that adding those is sufficient to utilize DTLS 1.2 in the Python OpenSSL bindings.

DTLS version 1.2 is mandated for the transport layer security suite of the CoAP protocol that is increasingly being rolled out in IoT devices.

**Comment by alex** [comment]
@chrysn we're happy to merge a PR for this, but we're unlikely to get to it on our own. Cheers.
