### ISSUE TITLE
Drop support for macOS 10.7 and 10.8

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3503]
According to BigQuery 99.5% of our downloads were from 10.10+ in the last month (99.9% from 10.9+). Query:

```sql
SELECT
  ROUND(100 * SUM(CASE WHEN INTEGER(REGEXP_EXTRACT(details.system.release, r"^([^\.]+)")) >= 13  THEN 1 ELSE 0 END) / COUNT(*), 1),
  COUNT(*) as download_count,
FROM
  TABLE_DATE_RANGE(
    [the-psf:pypi.downloads],
    DATE_ADD(CURRENT_TIMESTAMP(), -31, "day"),
    DATE_ADD(CURRENT_TIMESTAMP(), -1, "day")
  )

where
 details.system.name = "Darwin" and file.project='cryptography'
```

This provides ample justification for reworking our test infra. Right now we build against 10.7, 10.9, and 10.10 in our Jenkins, and 10.10, 10.11, and 10.12 in our Travis configs. How should we re-allocate our resources?

**Comment by alex** [comment]
I'm in favor of dropping 10.7 and 10.8 -- this gives us the same minimimum version as Chrome and Firefox.

**Comment by reaperhulk** [comment]
Any opinion on the distribution of builds between jenkins and travis? We can't do 10.9 builds in Travis. Maybe we do 10.9, 10.10, and 10.12 (and use the sierra builder as our wheel builder)?

Right now we do our wheel builds on 10.10 and 10.7 because we wanted to have macOS wheels that didn't have commoncrypto (for 10.6/10.7). With the new model we'll still get 10.6 SDK wheels since that's what python.org Pythons ship, but users of `default_backend()` on those platforms will get failures if commoncrypto is invoked. (all 0.1% or less of them)

**Comment by alex** [comment]
It seems like the easiest thing is to just dump some of our current jenkins builders, and leave travis alone. And then once we have everything working we can rebalance.

**Comment by alex** [comment]
Now that we've increased our builder capacity, shifting builds to jenkins is far less critical to our productivity. So, I think we should:

- Remove the 10.7 builder from Jenkins
- Replace the 10.7 wheel builder with a 10.9 wheel builder
- Change our docs to reflect the new minimum version -- do we need a deprecation cycle for this? 99.9% honestly seems high enough that we can skip it.
