### ISSUE TITLE
Handling of non-RFC compliant datetime value

### ISSUE THREAD

**Issue by paulx509** [pyca/cryptography#3512]
RFC 5280 says times are YYYYMMDDHHMMSSZ

_parse_asn1_generalized_time in decode_asn1.py strictly implements this and fails if this format is not met

```
    print cert.not_valid_after
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 94, in not_valid_after
    return _parse_asn1_time(self._backend, asn1_time)
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 734, in _parse_asn1_time
    return _parse_asn1_generalized_time(backend, generalized_time)
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 758, in _parse_asn1_generalized_time
    return datetime.datetime.strptime(time, "%Y%m%d%H%M%SZ")
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '20300829100529+0000' does not match format '%Y%m%d%H%M%SZ'
```
However the standard openssl library is more forgiving and still handles the datetime. Should cryptography also handle non-RFC compliant datetime?

Openssl outputs:
```
        Validity
            Not Before: Sep  3 10:05:35 2010 GMT
            Not After : Aug 29 10:05:29 2030
```

**Comment by Lukasa** [comment]
For my part, I consider the question to be: should cryptography handle datetimes that *are* ASN.1 GeneralizedTime, but which *do not* meet the requirements of RFC 5280 § 4.1.2.5.2?

**Comment by alex** [comment]
Where did you get a certificate that errors in this way?

**Comment by bobsthecoder** [comment]
Scanning the internet on 443

**Comment by reaperhulk** [comment]
@bobsthecoder if you could provide a sample cert that demonstrates this it'd be useful (we'll need a test if we choose to handle this case).

When it comes to x509 parsing my philosophy is pragmatism. If this is a reasonably common scenario then we should accept that and parse the "invalid" data, but if we're talking a one in a million cert I'd be in favor of staying intolerant. Is this something we could quantify with a tool like crt.sh?

**Comment by alex** [comment]
I'm not sure this can be queried using the public interface with either crt.sh or censys; but we can reach out to the maintainers if it'd be helpful in quantifying.

I'm also pro-pragmatism, but very unenthusiastic about making this change. You can't just issue random garbage and call it an x.509 cert.

**Comment by bobsthecoder** [comment]
Leave this with me and I will try to get some stats to test the size of the issue.

**Comment by alex** [comment]
Thanks!

**Comment by paulx509** [comment]
Oh my there is a lot of rubbish in the time field! I have changed the module to return the 'time' back to me without formatting so that I can look at it later.

./cryptography/hazmat/backends/openssl/decode_asn1.py

```
    #return datetime.datetime.strptime(time, "%Y%m%d%H%M%SZ")
    return time
```
I will update this once I have done more analysis.

**Comment by reaperhulk** [comment]
@paulx509 any news?

**Comment by alex** [comment]
Going to close this, can reopen if/when there's data.
