### ISSUE TITLE
Install issues with openssl 1.0.2k

### ISSUE THREAD

**Issue by chubbz327** [pyca/cryptography#3518]
Hi All, 

Attempting to install via pip3.5 results in numerous redefinition errors
```
static ossl_inline void RSA_get0_factors(const RSA *r, const BIGNUM **p,
                             ^
    build/temp.linux-x86_64-3.5/_openssl.c:3098:6: error: redefinition of 'RSA_get0_crt_params'
     void RSA_get0_crt_params(const RSA *r,
          ^
    In file included from /home/dbarthol/workspaces/orchestrator/common/include/openssl/x509.h:96:0,
                     from /home/dbarthol/workspaces/orchestrator/common/include/openssl/cms.h:58,
                     from build/temp.linux-x86_64-3.5/_openssl.c:483:
    /home/dbarthol/workspaces/orchestrator/common/include/openssl/rsa.h:610:25: note: previous definition of 'RSA_get0_crt_params' was here
     static ossl_inline void RSA_get0_crt_params(const RSA *r,
                             ^
```
My openssl version is 1.0.2k
Python is  3.5.3

Thanks in advance for your help

**Comment by alex** [comment]
What OS are you on and what version of cryptography are you installing?

**Comment by chubbz327** [comment]
Ubuntu 14.4
cryptography 1.8.1

**Comment by reaperhulk** [comment]
`RSA_get0_crt_params` is a function added in 1.1.0. The headers you're pointing at appear to be in your home directory and not the ones provided by Ubuntu, so are you sure you're not actually attempting to compile against 1.1.0?  Additionally, `static ossl_inline void RSA_get0_crt_params` is not what upstream OpenSSL 1.1.0 uses as a definition in its headers (https://github.com/openssl/openssl/blob/master/include/openssl/rsa.h#L197). Are these headers somehow modified?

**Comment by chubbz327** [comment]
cat README
 OpenSSL 1.0.2k 26 Jan 2017
   ...

I am not using the version of openssl as provided by ubuntu, we are using a custom ssl with 1.1 compatibility.

**Comment by alex** [comment]
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2k/crypto/rsa/rsa.h#L610 is what that line is in the OpenSSL 1.0.2k as it exists upstream. I'd try redownloading OpenSSL 1.0.2k.

**Comment by alex** [comment]
Going to close this, since this seems to be self-inflicted. Our list of supported OpenSSL versions can be found at https://cryptography.io/en/latest/installation/, with your custom OpenSSL you're unfortunately on your own.
