### ISSUE TITLE
Trailing whitespace in pem test vector

### ISSUE THREAD

**Issue by kaduk** [pyca/cryptography#3522]
vectors/cryptography_vectors/asymmetric/Traditional_OpenSSL_Serialization/key1.pem has a trailing space character on the last line ("-----END RSA PRIVATE KEY----- ").  This causes a failure in the openssl test suite when I attempt to apply strict whitespace checking for private key loading.  (Arguably openssl should not break compatibility like that in a major release series, so I will back out that change, but did want to point out that there is trailing whitespace here, in case it is desired to remove it.)

**Comment by alex** [comment]
That vector is originally from OpenSSL's tests, so if upstream would like to remove the trailing whitespace, I have no problem doing so. Do you want to send a PR?

**Comment by alex** [comment]
Err, sorry that one comes from gnutls, but the space is something we added by accident:

https://gitlab.com/gnutls/gnutls/commit/f16ef39ef0303b02d7fa590a37820440c466ce8d#1c6ed56e181259ab27d6c38f04d56eb1c90c1816_0_54

**Comment by reaperhulk** [comment]
👍 to removing the trailing whitespace
