### ISSUE TITLE
Add binding for OP_NO_TLSv1_3

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#3526]
OpenSSL 1.1.1 will introduce ```OP_NO_TLSv1_3```. Let's add the flag to cryptography now so that modules like PyOpenSSL can expose it.

see https://github.com/pyca/pyopenssl/issues/624 and https://bugs.python.org/issue29136

**Comment by alex** [comment]
We don't generally add bindings until they're in a released version of OpenSSL.

**Comment by tiran** [comment]
It may make sense to deviate from the rule and make an exception. If OpenSSL 1.1.1 will come with TLS 1.3 enabled, libraries are going to run into all sorts of trouble. For example if both sides have TLS 1.3 enabled but the library does not enable TLS 1.3 cipher suites, the handshake will prefer TLS 1.3 but fail with no matching ciphers.

With ```SSL_OP_NO_TLSv1_3``` available now, libraries can opt out from TLS 1.3 more easily than ```getattr(module, 'SSL_OP_NO_TLSv1_3', 0)```.

**Comment by alex** [comment]
They're going to need that anyways, since our bindings don't expose non-existent values.

I'm against making this constant special; if we want to provide a prettier API, it can be at the pyOpenSSL layer, not cryptography.

**Comment by reaperhulk** [comment]
This will be landed pretty much the moment 1.1.1 is released anyway (whenever that is). Just to be clear: the risk of not doing this right now is that users consuming an unreleased OpenSSL linked against pyca/cryptography and then consumed via pyOpenSSL will encounter problems if they attempt to communicate with servers that are TLS 1.3 intolerant?

**Comment by tiran** [comment]
@reaperhulk that's one possible issue. An even less likely issue involves TLS termination devices and firewalls that inspect traffic on higher levels.

The biggest issue are the new TLS 1.3 cipher suites. If an application overrides the default set of cipher suites and does not include TLS 1.3 suites, then handshake between TLS 1.3 enabled servers and clients will fail. It's pretty common to replace OpenSSL's cipher suite selection with a custom list of trusted ciphers.

Applications and libraries like PyOpenSSL and Twisted have to change for TLS 1.3 no matter what. :/
