### ISSUE TITLE
Compile Error: open CFI at the end of file; missing .cfi_endproc directive

### ISSUE THREAD

**Issue by paulcyr** [pyca/cryptography#3528]
When I attempt to install Cryptography using pip, it takes a pretty long time (~10 minutes) and then fails.

I am running on:

- Amazon Linux AMI 2017.03 on a t2.nano instance
- Python 2.7.12
- pip 9.0.1

The command used was: `sudo /usr/local/bin/pip install cryptography`

This was the output: 

	Collecting cryptography
	  Using cached cryptography-1.8.1.tar.gz
	Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/site-packages (from cryptography)
	Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/site-packages (from cryptography)
	Requirement already satisfied: packaging in /usr/local/lib/python2.7/site-packages (from cryptography)
	Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography)
	Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/dist-packages (from cryptography)
	Requirement already satisfied: enum34 in /usr/local/lib/python2.7/site-packages (from cryptography)
	Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography)
	Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib64/python2.7/site-packages (from cryptography)
	Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/site-packages (from packaging->cryptography)
	Requirement already satisfied: pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography)
	Installing collected packages: cryptography
	  Running setup.py install for cryptography ... error
		Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z3I5dg/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__fiinstall --record /tmp/pip-EK5G7p-record/install-record.txt --single-version-externally-managed --compile:
		running install
		running build
		running build_py
		creating build
		creating build/lib.linux-x86_64-2.7
		creating build/lib.linux-x86_64-2.7/cryptography
		copying src/cryptography/__init__.py -> build/lib.linux-x86_64-2.7/cryptography
		copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-2.7/cryptography
		copying src/cryptography/fernet.py -> build/lib.linux-x86_64-2.7/cryptography
		copying src/cryptography/utils.py -> build/lib.linux-x86_64-2.7/cryptography
		copying src/cryptography/__about__.py -> build/lib.linux-x86_64-2.7/cryptography
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat
		copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat
		creating build/lib.linux-x86_64-2.7/cryptography/x509
		copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-2.7/cryptography/x509
		copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
		copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/x509
		copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-2.7/cryptography/x509
		copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-2.7/cryptography/x509
		copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-2.7/cryptography/x509
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
		copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
		copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
		copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
		copying src/cryptography/hazmat/backends/multibackend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
		copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
		copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
		copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
		copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/twofactor
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
		copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
		copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
		copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
		copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/ciphers
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/interfaces
		copying src/cryptography/hazmat/primitives/interfaces/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/interfaces
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/kdf
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/primitives/asymmetric
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
		copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
		copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
		copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/openssl
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
		copying src/cryptography/hazmat/bindings/commoncrypto/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
		copying src/cryptography/hazmat/bindings/commoncrypto/binding.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/bindings/commoncrypto
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/openssl
		creating build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
		copying src/cryptography/hazmat/backends/commoncrypto/__init__.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
		copying src/cryptography/hazmat/backends/commoncrypto/backend.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
		copying src/cryptography/hazmat/backends/commoncrypto/hashes.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
		copying src/cryptography/hazmat/backends/commoncrypto/hmac.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
		copying src/cryptography/hazmat/backends/commoncrypto/ciphers.py -> build/lib.linux-x86_64-2.7/cryptography/hazmat/backends/commoncrypto
		running egg_info
		writing requirements to src/cryptography.egg-info/requires.txt
		writing src/cryptography.egg-info/PKG-INFO
		writing top-level names to src/cryptography.egg-info/top_level.txt
		writing dependency_links to src/cryptography.egg-info/dependency_links.txt
		writing entry points to src/cryptography.egg-info/entry_points.txt
		warning: manifest_maker: standard file '-c' not found

		reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
		reading manifest template 'MANIFEST.in'
		no previously-included directories found matching 'docs/_build'
		warning: no previously-included files matching '*' found under directory 'vectors'
		writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
		running build_ext
		generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
		creating build/temp.linux-x86_64-2.7
		generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
		generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
		building '_openssl' extension
		creating build/temp.linux-x86_64-2.7/build
		creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
		gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fparam=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/buil
		{standard input}: Assembler messages:
		{standard input}:232636: Warning: end of file not at end of a line; newline inserted
		{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
		gcc: internal compiler error: Killed (program cc1)
		Please submit a full bug report,
		with preprocessed source if appropriate.
		See <http://bugzilla.redhat.com/bugzilla> for instructions.
		error: command 'gcc' failed with exit status 4

		----------------------------------------
	Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z3I5dg/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replp-EK5G7p-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-z3I5dg/cryptography/

**Comment by reaperhulk** [comment]
Could you tail your system logs and see if you see an `out of memory` during compile?

**Comment by paulcyr** [comment]
I do indeed see that error. I also see that there is no swap. I suppose I should add a swap and try again? Any idea how much memory is required?

	Apr 29 23:52:21 ws1 kernel: [6424280.410198] cc1 invoked oom-killer: gfp_mask=0x24201ca, order=0, oom_score_adj=0
	Apr 29 23:52:21 ws1 kernel: [6424280.424638] cc1 cpuset=/ mems_allowed=0
	Apr 29 23:52:21 ws1 kernel: [6424280.426979] CPU: 0 PID: 7364 Comm: cc1 Tainted: G            E   4.4.44-39.55.amzn1.x86_64 #1
	Apr 29 23:52:21 ws1 kernel: [6424280.428575] Hardware name: Xen HVM domU, BIOS 4.2.amazon 12/09/2016
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  0000000000000000 ffff88001a3c7a70 ffffffff812cd3df ffff88001a3c7c58
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  0000000000000000 ffff88001a3c7b00 ffffffff811d084d ffff88001ee2fb20
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  ffffffff810b34b1 0000000000000000 0000000000000010 ffffffff817e1741
	Apr 29 23:52:21 ws1 kernel: [6424280.428575] Call Trace:
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff812cd3df>] dump_stack+0x63/0x84
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff811d084d>] dump_header+0x5e/0x1d8
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff810b34b1>] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff81165865>] oom_kill_process+0x205/0x3d0
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff81165ec1>] out_of_memory+0x431/0x480
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff8116af8e>] __alloc_pages_nodemask+0x91e/0xa60
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff811aef58>] alloc_pages_current+0x88/0x120
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff81162294>] __page_cache_alloc+0xb4/0xc0
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff811644a8>] filemap_fault+0x188/0x3e0
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffffa0122ed6>] ext4_filemap_fault+0x36/0x50 [ext4]
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff8118befd>] __do_fault+0x3d/0x70
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff81190337>] handle_mm_fault+0xf27/0x1870
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff8105ed03>] __do_page_fault+0x183/0x3f0
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff8105ef92>] do_page_fault+0x22/0x30
	Apr 29 23:52:21 ws1 kernel: [6424280.428575]  [<ffffffff814f1d98>] page_fault+0x28/0x30
	Apr 29 23:52:21 ws1 kernel: [6424280.513066] Mem-Info:
	Apr 29 23:52:21 ws1 kernel: [6424280.514756] active_anon:105749 inactive_anon:4105 isolated_anon:0
	Apr 29 23:52:21 ws1 kernel: [6424280.514756]  active_file:297 inactive_file:316 isolated_file:0
	Apr 29 23:52:21 ws1 kernel: [6424280.514756]  unevictable:0 dirty:0 writeback:0 unstable:0
	Apr 29 23:52:21 ws1 kernel: [6424280.514756]  slab_reclaimable:3476 slab_unreclaimable:4726
	Apr 29 23:52:21 ws1 kernel: [6424280.514756]  mapped:20747 shmem:21808 pagetables:3651 bounce:0
	Apr 29 23:52:21 ws1 kernel: [6424280.514756]  free:1118 free_pcp:55 free_cma:0
	Apr 29 23:52:21 ws1 kernel: [6424280.565672] Node 0 DMA free:1900kB min:88kB low:108kB high:132kB active_anon:11304kB inactive_anon:552kB active_file:0kB inactive_file:24kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15988kB managed:15904kB mlocked:0kB dirty:0kB writeback:0kB mapped:2736kB shmem:2892kB slab_reclaimable:552kB slab_unreclaimable:616kB kernel_stack:32kB pagetables:488kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:152 all_unreclaimable? yes
	Apr 29 23:52:21 ws1 kernel: [6424280.600907] lowmem_reserve[]: 0 454 454 454
	Apr 29 23:52:21 ws1 kernel: [6424280.604070] Node 0 DMA32 free:2572kB min:2680kB low:3348kB high:4020kB active_anon:411692kB inactive_anon:15868kB active_file:1188kB inactive_file:1240kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:507904kB managed:487140kB mlocked:0kB dirty:0kB writeback:0kB mapped:80252kB shmem:84340kB slab_reclaimable:13352kB slab_unreclaimable:18288kB kernel_stack:2000kB pagetables:14116kB unstable:0kB bounce:0kB free_pcp:220kB local_pcp:220kB free_cma:0kB writeback_tmp:0kB pages_scanned:19632 all_unreclaimable? yes
	Apr 29 23:52:21 ws1 kernel: [6424280.630593] lowmem_reserve[]: 0 0 0 0
	Apr 29 23:52:21 ws1 kernel: [6424280.633584] Node 0 DMA: 15*4kB (UM) 24*8kB (UM) 17*16kB (UM) 13*32kB (UM) 15*64kB (UM) 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 1900kB
	Apr 29 23:52:21 ws1 kernel: [6424280.642342] Node 0 DMA32: 167*4kB (UME) 238*8kB (U) 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2572kB
	Apr 29 23:52:21 ws1 kernel: [6424280.650322] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
	Apr 29 23:52:21 ws1 kernel: [6424280.654931] 22433 total pagecache pages
	Apr 29 23:52:21 ws1 kernel: [6424280.657065] 0 pages in swap cache
	Apr 29 23:52:21 ws1 kernel: [6424280.658997] Swap cache stats: add 0, delete 0, find 0/0
	Apr 29 23:52:21 ws1 kernel: [6424280.661689] Free swap  = 0kB
	Apr 29 23:52:21 ws1 kernel: [6424280.663724] Total swap = 0kB
	Apr 29 23:52:21 ws1 kernel: [6424280.665720] 130973 pages RAM
	Apr 29 23:52:21 ws1 kernel: [6424280.667423] 0 pages HighMem/MovableOnly
	Apr 29 23:52:21 ws1 kernel: [6424280.669610] 5212 pages reserved
	Apr 29 23:52:21 ws1 kernel: [6424280.686624] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
	Apr 29 23:52:21 ws1 kernel: [6424280.691845] [ 1509]     0  1509     2724       98      11       3        0         -1000 udevd
	Apr 29 23:52:21 ws1 kernel: [6424280.697478] [ 2021]     0  2021     2340      124       9       3        0             0 dhclient
	Apr 29 23:52:21 ws1 kernel: [6424280.702762] [ 2147]     0  2147     2340      119       9       3        0             0 dhclient
	Apr 29 23:52:21 ws1 kernel: [6424280.708073] [ 2215]     0  2215    60326      563      22       3        0             0 rsyslogd
	Apr 29 23:52:21 ws1 kernel: [6424280.714716] [ 2237]     0  2237     1094       37       8       3        0             0 rngd
	Apr 29 23:52:21 ws1 kernel: [6424280.719523] [ 2255]    32  2255     8826       98      23       3        0             0 rpcbind
	Apr 29 23:52:21 ws1 kernel: [6424280.724243] [ 2276]    29  2276     9968      201      24       3        0             0 rpc.statd
	Apr 29 23:52:21 ws1 kernel: [6424280.729156] [ 2307]    81  2307     5447       61      14       3        0             0 dbus-daemon
	Apr 29 23:52:21 ws1 kernel: [6424280.735099] [ 2482]     0  2482   147191     6028     223       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.739776] [ 2509]     0  2509    29880      145      14       3        0             0 crond
	Apr 29 23:52:21 ws1 kernel: [6424280.744972] [ 2523]     0  2523     4266       41      14       3        0             0 atd
	Apr 29 23:52:21 ws1 kernel: [6424280.749716] [ 2573]     0  2573     1614       30       9       3        0             0 agetty
	Apr 29 23:52:21 ws1 kernel: [6424280.755043] [ 2576]     0  2576     1077       22       8       3        0             0 mingetty
	Apr 29 23:52:21 ws1 kernel: [6424280.760581] [ 2579]     0  2579     1077       24       7       3        0             0 mingetty
	Apr 29 23:52:21 ws1 kernel: [6424280.765872] [ 2581]     0  2581     1077       23       8       3        0             0 mingetty
	Apr 29 23:52:21 ws1 kernel: [6424280.771061] [ 2583]     0  2583     1077       24       8       3        0             0 mingetty
	Apr 29 23:52:21 ws1 kernel: [6424280.776291] [ 2585]     0  2585     1077       24       7       3        0             0 mingetty
	Apr 29 23:52:21 ws1 kernel: [6424280.781617] [ 2588]     0  2588     1077       23       8       3        0             0 mingetty
	Apr 29 23:52:21 ws1 kernel: [6424280.787270] [ 3169]     0  3169    12031      139      27       3        0             0 vsftpd
	Apr 29 23:52:21 ws1 kernel: [6424280.793296] [25187]     0 25187    19985      205      39       3        0         -1000 sshd
	Apr 29 23:52:21 ws1 kernel: [6424280.797996] [25220]     0 25220    13238      107      27       3        0         -1000 auditd
	Apr 29 23:52:21 ws1 kernel: [6424280.802627] [25252]     0 25252    15459      791      33       3        0             0 nginx
	Apr 29 23:52:21 ws1 kernel: [6424280.807180] [25253]   498 25253    15729     1387      34       3        0             0 nginx
	Apr 29 23:52:21 ws1 kernel: [6424280.811781] [25284]    93 25284    24141      254      49       3        0             0 exim
	Apr 29 23:52:21 ws1 kernel: [6424280.816393] [30470]    48 30470   147191     1966     209       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.821171] [ 1763]    48  1763   147191     1966     209       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.826056] [ 4264]    48  4264   217702    21775     272       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.831058] [13153]    48 13153   266009    20191     288       5        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.835879] [13411]    48 13411   216523    20286     271       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.841104] [13413]    48 13413   216916    20021     272       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.846424] [13414]    48 13414   216795    20347     271       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.852837] [13417]    48 13417   217290    20512     270       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.858808] [13841]    48 13841   147191     1966     209       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.864239] [14328]     0 14328    29977      275      60       3        0             0 sshd
	Apr 29 23:52:21 ws1 kernel: [6424280.869409] [14330]   500 14330    29977      285      57       3        0             0 sshd
	Apr 29 23:52:21 ws1 kernel: [6424280.875241] [14331]   500 14331    28838      112      14       4        0             0 bash
	Apr 29 23:52:21 ws1 kernel: [6424280.880044] [ 4994]    48  4994   147191     1966     209       4        0             0 httpd
	Apr 29 23:52:21 ws1 kernel: [6424280.884764] [ 7223]     0  7223    46549      159      47       4        0             0 sudo
	Apr 29 23:52:21 ws1 kernel: [6424280.889304] [ 7224]     0  7224    28335      107      11       3        0             0 certbot-auto
	Apr 29 23:52:21 ws1 kernel: [6424280.894093] [ 7236]     0  7236    28340      117      11       3        0             0 certbot-auto
	Apr 29 23:52:21 ws1 kernel: [6424280.899265] [ 7280]     0  7280    28340      116      11       3        0             0 certbot-auto
	Apr 29 23:52:21 ws1 kernel: [6424280.904133] [ 7281]     0  7281    68052    10321      90       3        0             0 pip
	Apr 29 23:52:21 ws1 kernel: [6424280.909260] [ 7360]     0  7360    56415     5387      66       3        0             0 python2.7
	Apr 29 23:52:21 ws1 kernel: [6424280.914106] [ 7363]     0  7363    27945       30      11       3        0             0 gcc
	Apr 29 23:52:21 ws1 kernel: [6424280.918985] [ 7364]     0  7364    79894    42127     112       3        0             0 cc1
	Apr 29 23:52:21 ws1 kernel: [6424280.924157] [ 7365]     0  7365    37720     8207      31       4        0             0 as
	Apr 29 23:52:21 ws1 kernel: [6424280.929269] Out of memory: Kill process 7364 (cc1) score 325 or sacrifice child
	Apr 29 23:52:21 ws1 kernel: [6424280.936551] Killed process 7364 (cc1) total-vm:319576kB, anon-rss:168508kB, file-rss:0kB

**Comment by paulcyr** [comment]
I added a 1 GB swap, and it installed successfully.

Could I make a feature request to include a check for sufficient memory and/or provide a clearer error message?

**Comment by alex** [comment]
Unfortunately there's not much we can do; the exact amount of memory varies by compiler/platform, and all the code here is controlled by setuptools/GCC itself. Closing as there's not much we can do here.
