### ISSUE TITLE
key_size attribute not available on elliptic curve public keys?

### ISSUE THREAD

**Issue by konklone** [pyca/cryptography#3540]
I'm getting `'_EllipticCurvePublicKey' object has no attribute 'key_size'` when using `cryptography` -- it looks like RSA and DSA keys have this attribute defined. This looks like a potentially inconsistent API? Or, am I using it wrong?

**Comment by reaperhulk** [comment]
On elliptic curves you have to call `key_size` on the `EllipticCurve` class (so it'd be `key.curve.key_size`). This is definitely an inconsistency, but also relates to #1478 in that `key_size` is an inappropriate term for the degree and order of the curve (which may, but do not have to be, the same). I'm not sure how to fix this, although it's clearly a confusing API as structured 😞

**Comment by konklone** [comment]
Thank you for adding the convenience method for this!
