### ISSUE TITLE
Difficult to introspect on what kind of public key type a certificate uses

### ISSUE THREAD

**Issue by konklone** [pyca/cryptography#3541]
I use `cryptography` to walk through PEMs as I encounter them, and one operation I do is establish the type of public key in use.

Right now, the `public_key` method returns one of several classes based on the key type, and it looks like the key classes themselves don't give a method to ask what key type it is.

To illustrate what I mean, [here's my code right now](https://github.com/18F/domain-scan/blob/0bce58cbd5570c7996e71bf1827bcf56a6dbc8b4/scanners/sslyze.py#L232-L239):

```
        if leaf_key.__class__ == cryptography.hazmat.backends.openssl.rsa._RSAPublicKey:
            leaf_key_type = "RSA"
        elif leaf_key.__class__ == cryptography.hazmat.backends.openssl.dsa._DSAPublicKey:
            leaf_key_type = "DSA"
        elif leaf_key.__class__ == cryptography.hazmat.backends.openssl.ec._EllipticCurvePublicKey:
            leaf_key_type = "ECDSA"
        else:
            leaf_key_type == str(leaf_key.__class__)
```

This is also obviously hinging on a particular backend, if you look at the class strings -- these are the class types that actually came out when I introspected on them. The classes meant to be used as an abstraction by the backends aren't in use when I actually check the class of a key.

Anyway, I'm fully aware that this is a kludge -- and if there's a way I missed to do this that avoids this kludge, I'll happily switch.

**Comment by alex** [comment]
The correct way to test a key's type would be:

```py
from cryptography.hazmat.primitives.asymmetric import ec, dsa, rsa

if isinstance(key, rsa.RSAPublicKey):
    # ...
elif isinstance(key, dsa.DSAPublicKey):
    # ...
elif isinstance(key, ec.EllipticCurvePublicKey):
    # ...
else:
    # ... weird!
```

Is there some place we can could document this to make it easier to find?

**Comment by alex** [comment]
@konklone do you have a suggestion for where to put these docs?

**Comment by konklone** [comment]
I'm not really familiar enough with the cryptography docs to make an informed suggestion. But maybe the [Primitives section](https://cryptography.io/en/latest/hazmat/primitives/)?
