### ISSUE TITLE
Codecov coverage is broken

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3562]
At the moment codecov is claiming that we're missing coverage on a few lines, however those lines are definitely covered by our windows builders (see: https://codecov.s3.amazonaws.com/v4/raw/2017-05-20/12CC0B01F9906FB96C880A8A0ACFBA30/846ae1c789ed2d611a888295f97bf25d3e36085b/7f4eb148-48c4-44e2-bbb4-59495d150985.txt). The claimed missing lines are: https://codecov.io/gh/pyca/cryptography/src/e53129a39c1ac08a15a72481a8712615ef873cf7/src/cryptography/hazmat/backends/openssl/backend.py#L803 (and a few others in that file).

This appears to be an issue with codecov, but it blocks our ability to merge for the moment since we're unsure if there is actually missing coverage that is being hidden by these false positives. cc @stevepeak

**Comment by stevepeak** [comment]
Can you please rebuild or confirm fix on next upload. Rolled back and will review more shortly. Thanks.

**Comment by alex** [comment]
Confirmed this is fixed, thanks Steve!
