### ISSUE TITLE
how to encrypt a file using hazmat (AES 256 CBC) ?

### ISSUE THREAD

**Issue by NourEddineX** [pyca/cryptography#3568]

**Comment by alex** [comment]
An example of using AES in CBC mode can be found here: https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.Cipher

Please note that unless you need to interoperate with an existing protocol, you may be better off with https://cryptography.io/en/latest/fernet/
