### ISSUE TITLE
Fernet and replay attacks

### ISSUE THREAD

**Issue by samfrances** [pyca/cryptography#3570]
Apologies if this is not the right forum for this inquiry.

Does Fernet have any recipes or built-in ability to prevent replay attacks, other than the `ttl` option (which seems, correct me if I'm wrong, to leave a window of opportunity)?

I have tried some toy methods, but I'm wary of getting anywhere near hazmat or rolling my own cryptography in a more serious setting. If someone could point to a built-in method or an established recipe, that would be very useful.

**Comment by reaperhulk** [comment]
Fernet is a stateless recipe. To protect against replay attacks you need a stateful protocol. Unfortunately we have nothing in the recipes that can help you with that at this time.

**Comment by samfrances** [comment]
Ah, that's a shame. Thanks for getting back to me so quickly, anyway.
