### ISSUE TITLE
Remove hazmat from the "hazardous" modules

### ISSUE THREAD

**Issue by crushedice2000** [pyca/cryptography#3602]
I think that the `hazmat` part of the module is not needed nor leads to good code. Maybe it should be removed (providing backwards compatibility, of course).

Example of old name: 

    cryptography.hazmat.primitives

Example of new name:

    cryptography.primitives

Mainly, I think that is enough warning to tell the developer the implicit risks of using these methods.

Please tell me if I'm wrong and/or consider my proposal.

**Comment by alex** [comment]
Nope, having `hazmat` in the module name is very intentional, so that the possibility for mistakes is front of mind when using it.

**Comment by crushedice2000** [comment]
I know that it's *very* intentional, but I think that warning the user on the documentation and docstrings is enough. There is no need to uglify the code of the people that *knows* what they're doing. Or not?

**Comment by reaperhulk** [comment]
That only helps at the moment when the developer originally writes the code. Devs who join the project later or people auditing the code can use `hazmat` as a signifier that the code in question is dangerous and always deserves additional scrutiny. This philosophy is core to the project, so there is very little chance we'll be removing `hazmat` from the module path.

**Comment by crushedice2000** [comment]
Well. I don't like it. As all the material classified as "hazardous" doesn't have any implicit risk unless misused, I don't see the point of handling it as polonium in the meal.

However, even if I don't like this approach, it seems good enough to remain this way.

**Comment by crushedice2000** [comment]
Two last things:

1. Why `cryptography.hazmat.primitives.serialization` is considered hazardous?
2. What do you find better of the hazmat namespace than adding some comments in the code? I think that isn't a good idea to force the developer so.
