### ISSUE TITLE
Raw RSA encryption and decryption (without padding)

### ISSUE THREAD

**Issue by crushedice2000** [pyca/cryptography#3604]
Is possible to realize this insecure operation? Obviously, having a `bytes`object of the key length.

**Comment by alex** [comment]
This is currently not supported, and we're unlikely to add support -- I'm not aware of any major protocols that require this, so the footgun-to-utility ratio isn't very good. What is your usecase?

**Comment by crushedice2000** [comment]
I'm migrating an old Python code that uses PyCrypto to implement a highly unsafe legacy and rare-as-a-green-dog protocol. Implementing it only for me is a madness.

Understanding all the hazards that it carries 😈 would you accept a PR implementing this?

**Comment by reaperhulk** [comment]
Chef needs this as well (mentioned in https://github.com/pyca/cryptography/issues/1648 somewhere in the comments).

Since we already have support for `Prehashed` it would now be possible to do a `Textbook` that you pass to get raw RSA operations.

**Comment by crushedice2000** [comment]
I exactly need to do this (as suggested by @reaperhulk [here](https://github.com/pyca/cryptography/issues/1648#issuecomment-124893694):

    signature = key.sign(data, padding.PKCSv15(), None)

Also I would need to `verify` (do the inverse process).

***

@alex: Is not elegant, but is the best solution I can find for now. Thanks!

**Comment by alex** [comment]
PKCS#1v15 is different from raw RSA encryption. You should be able to accomplish it using the `Prehashed` helper @reaperhulk mentioned.

**Comment by crushedice2000** [comment]
@alex: I've tried already the `Prehashed`helper without luck. To end horrifying you, I need to stuff 112 bits of data into a 200 bit message. The rest is PKCS#1 1.5 `0xFF` padding.

**Comment by crushedice2000** [comment]
I'll probably try to familiarize with your code and do a PR implementing what I need (if you assure me that will be accepted, of course).

I think that implementing raw RSA, as stated in my first post, will allow more flexibility. Also, if the primitives are hazardous, let's go mad and expose *textbook* RSA! 😈 Seriously, this would allow custom implementations of rare padding algorithms and any uncommon protocol using your library.

If you prefer accept the implementation of the `Prehashed` helper with custom algorithms for signing and verification, it will be fine for my case, but that dozen of human beings around the world which need access to the low-level RSA functions will be sad. 😠 

If you choose not to implement it, please let me know so I can refine the odd job posted above. Else, let's discuss the implementation details.

**Comment by alex** [comment]
I remained opposed to adding this, the increased flexibility comes at the expense of increased confusion and potential for mistakes in the API. Hazmat is not an excuse for failure to balance these concerns against the utility of new functionality. Unless @reaperhulk feels strongly I will close this.

**Comment by crushedice2000** [comment]
Ok. However, I think that is a good idea to allow the developer to craft custom recipes backed by an strong and flexible API.

However, thanks for your patience and dedication.

**Comment by alex** [comment]
Closing for now. If you disagree @reaperhulk feel free to reopen.
