### ISSUE TITLE
Is the distinction between FUNCTIONS/MACROS still useful?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3606]
Near the outset of this project we decided to try to ensure that function signatures we declare and the ones that OpenSSL declares are identical. We originally took this path because we wanted to avoid scenarios where we declared a type as int when in reality it was size_t or other potentially dangerous mismatches, but a consequence of our approach is that it also breaks on constification.

Should we remove this distinction now? We've had numerous examples of breakage (most recently today: https://github.com/openssl/openssl/pull/3360#issuecomment-304051546) occurring due to additions of `const` in various OpenSSL releases, and I can't think of a case where we caught any significant bug in this fashion.

**Comment by alex** [comment]
Can someone remind me what bad thing happens if we declare a function as taking an `int` but really it takes a `size_t`?

**Comment by reaperhulk** [comment]
That one might be a bad example, but if we say `long` and it takes an `int` (and we're on x86_64 and not on Windows) I'm not sure what cffi/libffi will do.

**Comment by alex** [comment]
Ok, so we say `long` and it takes an `int` (assuming 64-bit and 32-bit widths respectively):

If we pass a value that's `> 2 ** 32` will anything raise an error? What does passing a value `> 2 ** 32` do if they are both correctly int?

**Comment by reaperhulk** [comment]
A bit of quick exploration:

```
import cffi


ffi = cffi.FFI()
ffi.cdef("long add(long a, long b);")
lib = ffi.verify("""
   int add(int a, int b) {
       return a + b;
   }
lib.add(2**33, 0) => 0
lib.add(2**32, -1) => -1
lib.add(2**31, 0) => -2147483648
""")

When properly declaring as int cffi captures this:

```
lib.add(2**31, 0)
OverflowError: integer 2147483648 does not fit '32-bit int'
```

**Comment by alex** [comment]
So basically, our current arrangement does catch bugs.

I wonder if there's something more involved way we could get there int
wins, but without the const troubles

**Comment by alex** [comment]
Hmm, if it's compile with `-Wconversion -Werror` do we get an error as expected

**Comment by reaperhulk** [comment]
We enabled `-Wconversion` in #3727 and #3728 and now #3695 will remove this distinction since it is no longer useful. Yay!

**Comment by alex** [comment]
This is done.
