### ISSUE TITLE
Return the Hash instance when issuing hash.update

### ISSUE THREAD

**Issue by crushedice2000** [pyca/cryptography#3618]
Wouldn't be good to return the current `Hash` instance when running `hash.update(data)`? This would allow to make a digest easily if you don't need to update it:

    digest = hashes.Hash(hashes.SHA1(), backend=default_backend())
    hash = digest.update(message).finalize()

I think that the only change to make in the code is returning `self` [here](https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/hashes.py#L93).

**Comment by alex** [comment]
Because `HashContext`s are mutable, we do not want to return `self`, to make clear that one is mutating the underlying object. This convention is used consistently in our codebase.

**Comment by crushedice2000** [comment]
Ok. Thanks. Seems like my coding practices are not sane. 😄
