### ISSUE TITLE
Release automation fixes

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3646]
With the new `release.py` the following issues occurred during the 1.9 release:

* `git tag -s` failed until I signed something separately (to prime gpg-agent's password caching for signing?)
* both `twine` uploads failed

At least some of this may be unfortunate interaction with gpg-agent/gnupg2 for signing (but the second twine command was purely uploading wheels so not sure why that failed)

**Comment by alex** [comment]
Immediate action item is to make sure failures include the stderr in the error message so that we can debug.

**Comment by reaperhulk** [comment]
The combination of `gnupg2` and `git` requires `GPG_TTY` to be set to work properly. So at least `git tag -s` should work now (and we'll see about twine)

**Comment by reaperhulk** [comment]
twine uploads still failed in the 2.0 release. Here's the output:

```
Exception: (['twine', 'upload', '-s', 'dist/cryptography-2.0*', 'vectors/dist/cryptography_vectors-2.0*'], 2, b'usage: twine [-h] [--version] {register,upload}\ntwine: error: the following arguments are required: command, args\n')
```

Additionally, triggering the wheel builder failed with

```
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://ci.cryptography.io/job/cryptography-support-jobs/job/wheel-builder/build?querystringremoved
```

**Comment by alex** [comment]
Ok, the problem with uploads is that we should not be using globs, I will take fixing that.

**Comment by reaperhulk** [comment]
The twine invocation to upload the wheels also failed and it does not use globs. No useful traceback came out of that though 😢

**Comment by alex** [comment]
That was diagnosed as "we pass all the paths as a single space separated string in argv, instead of in N argv entries":

https://github.com/pyca/cryptography/blob/master/release.py#L136

that should be `run("twine", "upload", *paths)`

**Comment by alex** [comment]
(And I'll send a PR for that as soon as we're reopened master for dev)

**Comment by alex** [comment]
I think everything here is fixed.
