### ISSUE TITLE
Question: Better to use HKDF w/o salt or Scrypt with reused salt when no password storage?

### ISSUE THREAD

**Issue by johnwheeler** [pyca/cryptography#3657]
My use case is that my users are required to type a password to decrypt their data. There is no password storage. I am currently using HKDF without a salt because I don't want users to have to supply a salt. Would it be wiser to use Scrypt with a salt that I reuse for every encrypt/decrypt?

Sorry for double posting in the IRC channel...

**Comment by reaperhulk** [comment]
Crypto advice like this is unfortunately not really something we can provide. That said, HKDF is not meant for passwords (it's fast, and you want password-based KDFs to be slow) so even absent the salt question Scrypt is a better candidate for your use case.
