### ISSUE TITLE
Deprecate Asymmetric Signature and Verification Contexts

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3659]
I think we should deprecate these contexts (probably an extended deprecation cycle since it's likely that these APIs are used quite a bit) and steer people exclusively to using the one-shot sign/verify APIs. As part of this we can expand the documentation on Prehashed to show an example of how you can incrementally hash a large file and then pass that hash to the one-shot APIs. Hooray composition.

refs #3656 and #3658

**Comment by alex** [comment]
This seems good, and facilitates better uptake of eddsa signatures.

**Comment by alex** [comment]
(This will have to be a very extended deprecation, it goes without saying)
