### ISSUE TITLE
Add CCM support

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3668]
As noted in #2968 it would be very useful if we could expose CCM for users implementing protocols that unfortunately chose to utilize that mode. This feature is blocked on #3667 because that issue will answer the question of where these new functions will live and how we'll go about building the APIs.

**Comment by reaperhulk** [comment]
@gpotter2 you mentioned a desire for this in the previous issue. Would a one-shot interface work for you? e.g.

```python
ctx = CCM(key)
ct = ctx.encrypt(iv, data, associated_data) # ct would have the CCM tag appended to it.
pt = ctx.decrypt(iv, data, associated_data) # decrypt would take the data as ciphertext||tag
```

I realize you might need the tag separately for your use case, but slicing ct[-16:] isn't a big deal. The main question is whether there's any burning need for a streaming interface (e.g. encrypting very large payloads).

**Comment by mtury** [comment]
Indeed we don't expect the processing of the message to be split up, and the size of the encrypted data isn't much of an issue to us. Also, there's already some slicing going on on our side anyway.

I'd have to devise a hackish way to handle the different crypto interfaces for GCM and CCM in our own AEAD interface, but if it's the easiest way to go for you, we'll gladly make do!

**Comment by alex** [comment]
FWIW, if it makes your life easier, I'd like for us to add a GCM API that uses the AEAD style.

**Comment by reaperhulk** [comment]
There is a WIP PR up (#3700) that adds CCM support. @mtury if you get a chance it'd be great if you could see if this works for you.

**Comment by mtury** [comment]
Works great indeed. I was able to validate old CCM encryption tests which I had commented out. I was also able to make my test server talk with an openssl s_client with a CCM cipher suite. The tag_length option even enables us to use CCM_8. Thanks! :D

Regarding the unified API project, this would make maintenance easier on both projects. This does not seem a priority, but once things settle down, I'd be glad to have that.

**Comment by reaperhulk** [comment]
It is unlikely that I won't implement `AESGCM` right after CCM lands, so you can reasonably expect both to be in cryptography 2.0

**Comment by reaperhulk** [comment]
Since this surprised me I'll put it here: OpenSSL didn't expose EVP layer CCM until 1.1.0. So widespread availability of this on the linux side will be dependent on shipping a manylinux1 wheel (#2970) for now.

**Comment by reaperhulk** [comment]
This is complete with 2.0 (AESCCM, AESGCM, and ChaCha20Poly1305 AEAD classes are now available)
