### ISSUE TITLE
Failed to install from wheel

### ISSUE THREAD

**Issue by MisterMorden** [pyca/cryptography#3690]
I'm running Python 3.4.2 32-bit on Windows.  When installing from pip failed, I tried to download the wheel from the pypi website (cryptography-1.9-cp34-cp34m-win32.whl), but that failed too.  The error message I received is "cryptography-1.9-cp34-cp34m-win32.whl is not a supported wheel on this platform."  Is that not the correct wheel or is there something else I'm missing?

**Comment by reaperhulk** [comment]
What version of pip are you running?

**Comment by MisterMorden** [comment]
1.5.6

**Comment by reaperhulk** [comment]
Please upgrade your pip (`python -m pip install -U pip` on windows) and then try installing (you should just be able to do `pip install cryptography`).

**Comment by MisterMorden** [comment]
That worked.  Thank you!

**Comment by reaperhulk** [comment]
Glad it's solved!
