### ISSUE TITLE
Regression when built with openssl 1.0.2

### ISSUE THREAD

**Issue by asavah** [pyca/cryptography#3692]
commit 6a0718f
introduced a regression if cryptography is built on system with openssl 1.0.2

```
'module' object has no attribute 'SCT_LIST_free'
```

AFAIK SCT_* functions are present in openssl 1.1.0 and higher, but not in 1.0.x

Shouln't there be some kind of version check here https://github.com/pyca/cryptography/blob/6a0718faddbc7b6b57f86417f6daa468c18ea248/src/cryptography/hazmat/backends/openssl/decode_asn1.py#L605 ?

**Comment by alex** [comment]
I think the version check needs to be in the caller of that function.

Thanks for catching this before it released!
