### ISSUE TITLE
cant install on debian with python3.6

### ISSUE THREAD

**Issue by kakulukia** [pyca/cryptography#3697]
i installed python3.6 on my debian box and am not able to install cryptography with this python version.
I installed that python version via the debian experimental branch.
The installation is possible under the system python3.4 tho. What might be missing?

Here is the error report:
------------------------
pip install cryptography
Collecting cryptography
  Using cached cryptography-1.9.tar.gz
Requirement already satisfied: idna>=2.1 in /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: asn1crypto>=0.21.0 in /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: six>=1.4.1 in /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: cffi>=1.7 in /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/lib/python3.6/site-packages (from cryptography)
Requirement already satisfied: pycparser in /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/lib/python3.6/site-packages (from cffi>=1.7->cryptography)
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gx_v2d9w/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2v0r_kb8pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-3.6
  creating build/lib.linux-i686-3.6/cryptography
  copying src/cryptography/utils.py -> build/lib.linux-i686-3.6/cryptography
  copying src/cryptography/__about__.py -> build/lib.linux-i686-3.6/cryptography
  copying src/cryptography/fernet.py -> build/lib.linux-i686-3.6/cryptography
  copying src/cryptography/exceptions.py -> build/lib.linux-i686-3.6/cryptography
  copying src/cryptography/__init__.py -> build/lib.linux-i686-3.6/cryptography
  creating build/lib.linux-i686-3.6/cryptography/hazmat
  copying src/cryptography/hazmat/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat
  creating build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/extensions.py -> build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/name.py -> build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/oid.py -> build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/general_name.py -> build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/base.py -> build/lib.linux-i686-3.6/cryptography/x509
  copying src/cryptography/x509/__init__.py -> build/lib.linux-i686-3.6/cryptography/x509
  creating build/lib.linux-i686-3.6/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends
  copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends
  creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/interfaces.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
  creating build/lib.linux-i686-3.6/cryptography/hazmat/bindings
  copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings
  creating build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
  creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
  creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
  creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
  copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
  creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
  copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
  creating build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
  copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
  running egg_info
  writing src/cryptography.egg-info/PKG-INFO
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt
  writing entry points to src/cryptography.egg-info/entry_points.txt
  writing requirements to src/cryptography.egg-info/requires.txt
  writing top-level names to src/cryptography.egg-info/top_level.txt
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files matching '*' found under directory 'vectors'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  running build_ext
  generating cffi module 'build/temp.linux-i686-3.6/_padding.c'
  creating build/temp.linux-i686-3.6
  generating cffi module 'build/temp.linux-i686-3.6/_constant_time.c'
  generating cffi module 'build/temp.linux-i686-3.6/_openssl.c'
  building '_openssl' extension
  creating build/temp.linux-i686-3.6/build
  creating build/temp.linux-i686-3.6/build/temp.linux-i686-3.6
  i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-Ze4Ftr/python3.6-3.6.1=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/andy/.virtualenvs/schichtsalat-1SpGlnG5/include/python3.6m -c build/temp.linux-i686-3.6/_openssl.c -o build/temp.linux-i686-3.6/build/temp.linux-i686-3.6/_openssl.o
  i686-linux-gnu-gcc: error: /usr/share/dpkg/no-pie-compile.specs: Datei oder Verzeichnis nicht gefunden
  error: command 'i686-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Failed to build cryptography
Installing collected packages: cryptography
  Running setup.py install for cryptography ... error
    Complete output from command /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gx_v2d9w/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ag4pjbki-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/include/site/python3.6/cryptography:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-3.6
    creating build/lib.linux-i686-3.6/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-i686-3.6/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-i686-3.6/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-i686-3.6/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-i686-3.6/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-i686-3.6/cryptography
    creating build/lib.linux-i686-3.6/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat
    creating build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-i686-3.6/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-i686-3.6/cryptography/x509
    creating build/lib.linux-i686-3.6/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends
    creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/interfaces.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives
    creating build/lib.linux-i686-3.6/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings
    creating build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/backends/openssl
    creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-i686-3.6/cryptography/hazmat/bindings/openssl
    running egg_info
    writing src/cryptography.egg-info/PKG-INFO
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing entry points to src/cryptography.egg-info/entry_points.txt
    writing requirements to src/cryptography.egg-info/requires.txt
    writing top-level names to src/cryptography.egg-info/top_level.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-i686-3.6/_padding.c'
    creating build/temp.linux-i686-3.6
    generating cffi module 'build/temp.linux-i686-3.6/_constant_time.c'
    generating cffi module 'build/temp.linux-i686-3.6/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-i686-3.6/build
    creating build/temp.linux-i686-3.6/build/temp.linux-i686-3.6
    i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-Ze4Ftr/python3.6-3.6.1=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/andy/.virtualenvs/schichtsalat-1SpGlnG5/include/python3.6m -c build/temp.linux-i686-3.6/_openssl.c -o build/temp.linux-i686-3.6/build/temp.linux-i686-3.6/_openssl.o
    i686-linux-gnu-gcc: error: /usr/share/dpkg/no-pie-compile.specs: Datei oder Verzeichnis nicht gefunden
    error: command 'i686-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/home/andy/.virtualenvs/schichtsalat-1SpGlnG5/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gx_v2d9w/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ag4pjbki-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/andy/.virtualenvs/schichtsalat-1SpGlnG5/include/site/python3.6/cryptography" failed with error code 1 in /tmp/pip-build-gx_v2d9w/cryptography/

**Comment by mithrandi** [comment]
The file referenced (`/usr/share/dpkg/no-pie-compile.specs`) is in the `libdpkg-perl` package on Debian, so installing that package should solve the immediate problem.

The fact that Python is trying to use it while building a C extension has to do with how you built Python (which I'm guessing you did yourself since there is no Debian version with both python3.4 and python3.6), so rebuilding Python 3.6 may also solve the problem, but I'd probably need to know more about how you did that to speculate further on the matter.

**Comment by kakulukia** [comment]
awesome!! it worked!

Like i said i used the debian experimental package from 
deb http://ftp.de.debian.org/debian experimental main
