### ISSUE TITLE
Can't find _cffi_backend

### ISSUE THREAD

**Issue by ulandreman** [pyca/cryptography#3703]
I'm running Python 2.7 that comes packages with IBM SPSS Statistics 24.  I use cyptogoraphy because another the ESRI Workbench python routines use it.  When I run the routines, I end up with an error message: from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: No module named _cffi_backend

Any idea of what I need to do to fix this?

Thanks!

**Comment by reaperhulk** [comment]
That error msg typically means the wrong version of cffi is installed in the module path that it's using. Try upgrading cffi perhaps?

**Comment by ulandreman** [comment]
Thanks for the suggestion.
I downloaded cffi-1.10.0-cp27-cp27m-win32.whl from https://pypi.python.org/pypi/cffi? and added 
the line import cffi
to \Python\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py

I get the same message.
Am I supposed to be doing something more or differently?

**Comment by reaperhulk** [comment]
You'll need to install the wheel into your site-packages via a tool like pip. You don't need to modify any of the code. If that's not available to you in this environment then you'll need to reach out to people who know more about the way SPSS packages its Python environment. Sorry :(

**Comment by ulandreman** [comment]
Thanks again.  I've reached out to the SPSS Statistics python guru for his advice.

**Comment by alex** [comment]
Going to close this, since it's not actionable for us and appears to be a bug elsewhere.

**Comment by Data-Diver** [comment]
I'm using windows server 2016 and running Windows Defender service.
I try to install cryptography using pip.
but Windows Defender delete "cffi\_cffi_backend.cp36-win_amd64.pyd" everytime.
Dedenfer's deleting reason is "Trojan:Win32/Skeeyah.l" detect from cryptography sources.

cryptography is included malware? is really safe?
