### ISSUE TITLE
Wheel Naming Issue for OSX

### ISSUE THREAD

**Issue by judy2k** [pyca/cryptography#3706]
The release of 1.9 has my OSX laptop attempting to build from source again, instead of downloading the binary wheel. Installing cryptography 1.8 downloads the wheel as expected.

I notice the new OSX wheels all have a platform tag of 'intel', whereas before it was 'x86_64'. The specification for wheel naming [specifies](https://www.python.org/dev/peps/pep-0425/#platform-tag) that the platform tag should be the result of running the following (I've included the result I get with Python 3.6.0 and 2.7.12)

```python
>>> distutils.util.get_platform().replace('-', '_').replace('.', '_')
'macosx_10_11_x86_64'
```

... and the relevant parts of my pip log:

1.8
```
pip install cryptography==1.8 --upgrade --no-cache-dir
Collecting cryptography==1.8
  Downloading cryptography-1.8-cp27-cp27mu-macosx_10_10_x86_64.whl (1.4MB)
```

1.9
```
pip install cryptography==1.9 --upgrade --no-cache-dir
Collecting cryptography==1.9
  Downloading cryptography-1.9.tar.gz (409kB)
```

(While I'm here, I'd just like to say I :heart: the cryptography library. Thanks!)

**Comment by tdsmith** [comment]
Can I ask what version of pip you're using? The intel and x86_64 specs are compatible (intel means a fat binary containing both x86_64 and i386 arches) and I think recent pips understand that.

**Comment by reaperhulk** [comment]
I didn't ship a cp27mu wheel for 1.9 on Mac and you have that build. Where does your python come from? To my knowledge on Mac wide Unicode was only briefly a thing when pyenv switched the default, but they switched back long ago.

**Comment by alex** [comment]
Closing this due to lack of follow up. Will re-open once there's more information.
