### ISSUE TITLE
BN_zero Build error when building against OpenSSL 1.1

### ISSUE THREAD

**Issue by djkurtz** [pyca/cryptography#3712]
```
../cryptography-1.9-python2_7/temp.linux-x86_64-2.7/_openssl.c:21074:10: error: returning 'void' from a function with incompatible result type 'int'
  return BN_zero(x0);
         ^~~~~~~~~~~
../../../../../../usr/include/openssl/bn.h:155:27: note: expanded from macro 'BN_zero'
#  define BN_zero(a)      BN_zero_ex(a)
                          ^~~~~~~~~~~~~
../cryptography-1.9-python2_7/temp.linux-x86_64-2.7/_openssl.c:21097:12: error: assigning to 'int' from incompatible type 'void'
  { result = BN_zero(x0); }
           ^ ~~~~~~~~~~~
```
OpenSSL 1.1 deprecated the version of BN_zero() from 0.9.8 that returned 1 on success.
See https://www.openssl.org/docs/man1.1.0/crypto/BN_zero.html

**Comment by reaperhulk** [comment]
Is your OpenSSL built with `no-deprecated`? Cryptography currently requires quite a few deprecated functions to assist with us remaining compatible across our entire supported range of OpenSSL versions.

**Comment by reaperhulk** [comment]
Looking into this a bit more there are a huge number of functions that have been deprecated that we still need to have around for pyOpenSSL. We'll slowly chip away at this over time but it has to be a long-term goal to build with `no-deprecated`.

**Comment by djkurtz** [comment]
Sorry, I haven't had a chance to cycle back to this issue.  From what I remember, yes, I was building openssl 1.1 without "no-deprecated". However, this was the only change needed get it to build (other deprecated functions just generated warnings).  So, I think fixing this one issue should be both forwards and backwards compatible w/rt openssl ABI.

**Comment by schlenk** [comment]
Any progress on the build against an openssl with 'no-deprecated'?
