### ISSUE TITLE
Potentially kill WithSerialization?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3715]
While technically correct, users find it confusing that our keys implement multiple interfaces. This can not only result in users not knowing when a key will implement a given interface, but sometimes not finding the serialization methods at all and mistakenly believing they're unsupported.

As discussed in IRC, maybe we should consider removing the *WithSerialization interfaces and moving those methods onto the primary key interfaces. If and when we support opaque keys we can handle that by raising NotImplementedError on the methods in question (we could also do something like add an `in_hardware` property, etc).

**Comment by alex** [comment]
Maybe we could rename `Key` -> `OpaqueKey`, `KeyWithSerialization` -> `Key`. The naming feels vaguely wrong, but it makes the types still correct, and then we just document `load_pkcs11_uri` as returning `OpaqueKey`.

**Comment by reaperhulk** [comment]
How do we deal with the confusion of implementing multiple interfaces? Renaming might help a bit but we still have the case that a key would implement both key and opaquekey and users would need to realize the union of those methods are available on their object.

**Comment by alex** [comment]
I think the biggest win is what when you clicked a link to `RSAPrivateKey` you'd get something with the `private_bytes` method instead of needing to go searching.

Also we should replace language in the docs like `Extends RSAPrivateKey.` with `This interface includes all the methods on RSAPrivateKey`.

**Comment by reaperhulk** [comment]
#3721 might actually make this good enough for now.

**Comment by reaperhulk** [comment]
I'm going to say that with the improved docs this is good enough for now. We can open another issue if we want to make further changes.
