### ISSUE TITLE
KDF documentation mismatch: bytes vs bits

### ISSUE THREAD

**Issue by PeterHamilton** [pyca/cryptography#3733]
After doing some work with the KDF functions, I noticed an issue with the documentation (`docs/hazmat/primitives/key-derivation-functions.rst`). The `length` fields are often defined as `The desired length of the derived key in bytes.`. However, some of the examples clearly use bits as the `length` value (e.g., `KBKDFHMAC` uses 256, lines 637 vs 654).

I'm not too familiar with all of the different KDF functions and their parameters but the docs may need a cursory review to match the examples with the parameter descriptions.

**Comment by reaperhulk** [comment]
The examples don't show anything other than deriving and verifying so in one sense the amount of output doesn't matter. However, it looks like the choice of 256 (which would indeed be a long key and too long for pretty much every key-based operation in this project) is confusing. I'd be fine with changing it to a smaller length to avoid any perception of bits/bytes mixup.

**Comment by PeterHamilton** [comment]
Ok, that's what confused me. I'd never heard of a 256-byte key. Thanks for taking a look.

**Comment by reaperhulk** [comment]
Thanks for reporting it. To say we care deeply about our docs being useful would be an understatement. #3734 should resolve this!
