### ISSUE TITLE
x509_builder.sign(ec_key, hashes.MD5()) produces an assertion error from OpenSSL

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3737]
`'error:100C508A:elliptic curve routines:pkey_ec_ctrl:invalid digest type'`

It should error with a clean python exception, not an `InternalError`.

**Comment by reaperhulk** [comment]
Does MD5 signing fail on RSA/DSA as well?

**Comment by alex** [comment]
Worked fine with RSA. Don't know about DSA, since the code I'm writing has no plans to support it :-)

**Comment by reaperhulk** [comment]
Confirmed this happens with CSRs too for both ECDSA and DSA. Maybe we should consider just disallowing MD5 entirely.

**Comment by reaperhulk** [comment]
In fact, PR coming :)

**Comment by alex** [comment]
PR disallowing MD5?

**Comment by reaperhulk** [comment]
yep.

```

        if (isinstance(algorithm, hashes.MD5)):
            raise ValueError("MD5 is not a supported hash algorithm for certs/CSRs")
```

**Comment by alex** [comment]
This will break my tests which ensure my x509 validator doesn't accept MD5, but I'll live :-)

**Comment by alex** [comment]
(Hot take: maybe we shouldn't support MD5 at all?)

**Comment by reaperhulk** [comment]
I think it might be reasonable to deprecate it. Users who need MD5 for something like a splaying algorithm can just do `hashlib.md5(data).digest()` after all...

**Comment by alex** [comment]
"splaying"? (But yes, the only thing us removing support for really means is removing it as a marker in APIs like x.509, signatures, etc.)

**Comment by reaperhulk** [comment]
Fixed
