### ISSUE TITLE
Consider caching parsed extensions in x509.Certificates

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3747]
Right now they get re-parsed on every access, this can be somewhat expensive, we should consider caching them on first access

**Comment by alex** [comment]
FWIW, I measured this a about a 40% win on my test suite of x.509 validations.

**Comment by reaperhulk** [comment]
What's the absolute improvement?

**Comment by alex** [comment]
From 1 second to .5-.6 seconds.

**Comment by reaperhulk** [comment]
😁 still probably worth doing (and a thing we've talked about previously)
