### ISSUE TITLE
Signer/Verifier deprecation warning has wrong stacklevel

### ISSUE THREAD

**Issue by nchammas** [pyca/cryptography#3798]
Seeing this with Cryptography 2.0:

```
.../python3.5/site-packages/cryptography/hazmat/backends/openssl/rsa.py:477: DeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  _warn_sign_verify_deprecated()
.../python3.5/site-packages/cryptography/hazmat/backends/openssl/rsa.py:382: DeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  _warn_sign_verify_deprecated()
```

I see a few open issues related to deprecations (e.g. #3794), but I'm not sure if any of them cover this particular message.

**Comment by alex** [comment]
These are intentional, cryptography is emitting them! Though it looks like we got the `stacklevel` argument wrong. Whatever package is using cryptography should port itself to use the `sign` and `verify` methods.

I'm going to retitle this bug to be about updating the `stacklevel` we use.

**Comment by nchammas** [comment]
Ah, I thought Cryptography was using some deprecated methods within itself (which, on reflection, would be weird). I'll check downstream (I'm guessing Paramiko?) and open issues on the appropriate project if necessary.

**Comment by alex** [comment]
@nchammas https://github.com/paramiko/paramiko/pull/979

**Comment by alex** [comment]
Hopefully fixing `stacklevel` will make this more obvious for folks.
