### ISSUE TITLE
Don't create py33 wheels, we dropped support

### ISSUE THREAD

**Issue by johnthagen** [pyca/cryptography#3801]
In the release notes for 2.0:

> BACKWARDS INCOMPATIBLE: Support for Python 3.3 has been dropped.

But Windows wheels are provided on PyPI. Was this intentional?

Example:
[cryptography-2.0-cp33-cp33m-win32.whl](https://pypi.python.org/packages/2c/22/b1765a075b7317a0381e59b0c604859289eeb6be0d57781e69d004b45989/cryptography-2.0-cp33-cp33m-win32.whl#md5=5b023bebbcb48ac8b71964d037403fbc)

**Comment by alex** [comment]
rofl, that's amazing.

**Comment by alex** [comment]
I guess we'll leave them for now, and I'll make this bug "don't create py33 wheels"

**Comment by reaperhulk** [comment]
Whoops!
