### ISSUE TITLE
UnsupportedAlgorithm: Backend object does not implement ScryptBackend

### ISSUE THREAD

**Issue by brysontyrrell** [pyca/cryptography#3822]
I'm using Scrypt in an application for deriving and verifying keys from a password and I'm getting an error when I deploy it to an Ubuntu 16.04 Docker container:

```
    return Scrypt(salt=salt, length=32, n=2**14, r=8, p=1, backend=backend)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/kdf/scrypt.py", line 29, in __init__
    _Reasons.BACKEND_MISSING_INTERFACE
cryptography.exceptions.UnsupportedAlgorithm: Backend object does not implement ScryptBackend.
```

The backend is being created from `backend = default_backend()`. All of the dependencies listed in the installation docs are installed and there are no issues with installing the module itself.

Python 2.7.12
cryptography 1.9

**Comment by reaperhulk** [comment]
`scrypt` requires OpenSSL 1.1.0 which does not ship with Ubuntu 16.04. However, if you have an up-to-date pip you can install cryptography 2.0+ and get a wheel that links against 1.1.0 which will resolve this issue.

**Comment by brysontyrrell** [comment]
That was a very simple fix. Thank you very much @reaperhulk !
