### ISSUE TITLE
is LibreSSL supported? (can't compile on OpenBSD 6.1 release)

### ISSUE THREAD

**Issue by plavcik** [pyca/cryptography#3837]
I'm trying install cryptography on OpenBSD 6.1 release to Python 2.7 via
    LIBRESSL_VERSION_NUMBER=2.5.5 pip install cryptography

but I got this error

    cc -pthread -fno-strict-aliasing -O2 -pipe -DNDEBUG -O2 -pipe -fPIC -fPIC -I/usr/local/include/python2.7 -c build/temp.openbsd-6.1-amd64-2.7/_openssl.c -o build/temp.openbsd-6.1-amd64-2.7/build/temp.openbsd-6.1-amd64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    cc1: error: -Werror=sign-conversion: No option -Wsign-conversion
    error: command 'cc' failed with exit status 1

    cc -v
    Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.1/4.2.1/specs
    Target: amd64-unknown-openbsd6.1
    Configured with: OpenBSD/amd64 system compiler
    Thread model: posix
    gcc version 4.2.1 20070719

**Comment by njsmith** [comment]
I think the problem here is that you're using a gcc from 2007.

**Comment by alex** [comment]
Yes  if you look at that error message, the problem is a missing compiler flag:

`cc1: error: -Werror=sign-conversion: No option -Wsign-conversion`

upgrade to a modern gcc or clang and this should be solved.

**Comment by plavcik** [comment]
thank you for quick reply

may I suggest to add this lines to installation instructions?

OpenBSD 6.1 with LibreSSL is supported

pkg_add llvm
CC=clang pip install cryptography

thank you, Jiri
