### ISSUE TITLE
Use stable anchors in changelog rst

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#3839]
The changelog documentation uses auto-generated, incremental anchor names, e.g. https://cryptography.readthedocs.io/en/latest/changelog/#id7. The auto-generated ids are not stable and change over time. At the moment id7 refers to release 1.8. As soon as a next release comes out, id 7 will reference to 1.8.1 instead of 1.8, and so on.

**Comment by alex** [comment]
Do you know what the right rST syntax for this is?

**Comment by tiran** [comment]
I used the script to modify the changelog. Sphinx does not accept IDs that start with a number, so I had to add ``v`` prefix. Sphinx also changes ``v2.0`` to anchor id ``v2-0`` when it generates HTML.

```
#!/usr/bin/python3
import re

VER = re.compile('^(\d\.[\d\.]*).*')

lines = []

with open('CHANGELOG.rst') as f:
    for line in f:
        mo = VER.match(line)
        if mo is not None:
            v = mo.group(1).replace('.', '-')
            lines.append('\n.. _v{}:\n\n'.format(v))
        lines.append(line)

with open('CHANGELOG.rst', 'w') as f:
    f.write(''.join(lines))
```

**Comment by tiran** [comment]
I also tried http://www.sphinx-doc.org/en/stable/ext/autosectionlabel.html . It does not seem to work for included files like CHANGELOG.rst.
