### ISSUE TITLE
openssl tests fail

### ISSUE THREAD

**Issue by richsalz** [pyca/cryptography#3851]
I am not sure if this is an OpenSSL issue or a wrongly-written test here.

Please see https://github.com/openssl/openssl/issues/4103 for full details.  Sample error:
```
____ ERROR at setup of TestPKCS7.test_invalid_padding[128-] ____

self = {'TRAVIS_PULL_REQUEST_BRANCH': '', 'rvm_version': '1.29.2 (latest)', 'LC_CTYPE': 'en_US.UTF-8', 'RUBY_VERSION': 'ruby-...st/../include -I/home/travis/build/mouse07410/openssl/test/../include -L/home/travis/build/mouse07410/openssl/test/..'}
key = 'PYTEST_CURRENT_TEST'
item = 'tests/hazmat/primitives/test_padding.py::TestPKCS7::()::test_invalid_padding[128-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00] (setup)'

    def __setitem__(self, key, item):
>       putenv(key, item)
E       TypeError: must be string without null bytes, not str

../venv-pycrypto/lib/python2.7/os.py:471: TypeError
__ ERROR at teardown of TestPKCS7.test_invalid_padding[128-] ___
```

**Comment by reaperhulk** [comment]
@richsalz It's a bug with pytest 3.2.0. We've blacklisted that version in current master.

**Comment by alex** [comment]
Ugh. This is the same as #3835 -- specifically the latest version of our test runner breaks our tests. If you bump your dependency to pin to "whatever `master` is today" you should get the fix for this.

**Comment by reaperhulk** [comment]
@alex I'm going to open an issue to discuss whether we should do requires.io style dep pinning for our test deps so that consumers who vendor (like OpenSSL) won't experience this sort of breakage in the future.

**Comment by alex** [comment]
Sounds like a plan. I'll close this since I think @richsalz has his answer.
