### ISSUE TITLE
Use pyup/requires to pin our test dependencies?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3852]
Right now we don't pin our test dependencies, so when a test dep is upgraded the next test run immediately pulls it. This is normally fine, but occasionally causes regressions due to bugs or interface changes. We can (and should) fix them in master, but we run into issues where we're forced to backport those fixes to release branches and also occasionally see breakage from downstream consumers who vendor us (#3851). If we pin our test deps and use pyup.io or requires.io to automatically send PRs every time said dependencies are updated we can avoid this issue in the future.

**Comment by alex** [comment]
Can those services send PRs to `setup.py`, instead of `requirements.txt`?

**Comment by reaperhulk** [comment]
I believe requires.io can, although I don't know if we can whitelist only the test/docs deps.

**Comment by reaperhulk** [comment]
Looks like this isn't really practical for now. Oh well.
