### ISSUE TITLE
Sign an CSR from a .pem file

### ISSUE THREAD

**Issue by CromefireHD** [pyca/cryptography#3853]
Please make it possible to load a CSR from a .pem file and sign it to enable cryptography to be used to manage CAs

**Comment by reaperhulk** [comment]
Cryptography supports loading of PEM encoded certificate signing requests right now. Additionally, it supports generation and signing of certificates. The [documentation for X509](https://cryptography.io/en/latest/x509/) contains information on how to do this.

**Comment by CromefireHD** [comment]
I thought I read everything, but I somehow missed it, sorry

**Comment by CromefireHD** [comment]
I think, it is still missing information about signing a CSR (convert to a certificate). If it's not missing please link it in the first Tutorial for more clarity.

**Comment by reaperhulk** [comment]
To build a certificate from a CSR you just use the CertificateBuilder and copy what you need from the CSR into the new certificate. Typically with a CA this is just copying the public key, setting a standard set of extensions (commonly known as a "certificate profile"), setting the subject DN to the values that the CA has validated, and setting the issuer DN to the value of the subject DN of the issuing certificate. Importantly, at no time should a real CA (e.g. one that operates a registration authority to validate requests and may or may not have globally trusted roots) actually copy the values (other than the public key itself) directly from a CSR into a certificate.

**Comment by Cromefire** [comment]
Is there no need for the signature on the on the csr?
