### ISSUE TITLE
Document that on OpenBSD you'll need to install a modern compiler

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3854]
Follow up to #3812 -- since OpenBSD defaults to a decade old compiler, we should add something to our install doc.

**Comment by warner** [comment]
Another update from our OpenBSD friends: installing the gcc-4.9.4 "port" doesn't change the `/usr/bin/cc` compiler, instead it adds a new `/usr/bin/egcc` executable. I don't believe python will notice the new compiler (especially since the system `/usr/bin/python` was built with the system `/usr/bin/cc`).

So adding instructions to "upgrade your compiler" won't be as simple as recommending a package to install: I think it would also require deleting the system compiler and symlinking in the newer one, which is a bit extreme (and would probably break other expectations of the OS). If there's a way to tell `pip` to use a different compiler binary, or if there's some environment variable that controls how setuptools uses the compiler, that might work.

**Comment by alex** [comment]
Pretty sure `distutils` respects `$CC`

**Comment by warner** [comment]
Cool. We also just tested adding a symlink from `~/bin/cc` to `/usr/bin/egcc`, and that worked too (so apparently `distutils` is doing a `$PATH` lookup, rather than an absolute `/usr/bin/cc`).

**Comment by warner** [comment]
We've confirmed that `pkg_add -v gcc-4.9.4p4; export CC=/usr/local/bin/egcc` works.

**Comment by reaperhulk** [comment]
I can't leave this issue alone without mentioning that it is absolutely stunning to me that the latest version of OpenBSD ships with a default compiler that is over a decade old (gcc 4.2.1 released July 18, 2007). What the hell.

**Comment by alex** [comment]
That version of gcc definitely does not have `-fstack-protector-strong`. Security!

**Comment by warner** [comment]
I'm told that OpenBSD-6.2 will switch to LLVM, which should help somewhat :)

**Comment by alex** [comment]
That would help!

**Comment by djames1** [comment]
@reaperhulk The reason the compiler version is so old is because that is the last version of GCC released under GPLv2, and the OpenBSD devs have issues with the new terms added to GPLv3. They maintain their own fork with a ton of patches reimplementing features from later GCC releases.

**Comment by cypa** [comment]
on openbsd 6.3 it wont compile with clang also

building '_openssl' extension
    creating build/temp.openbsd-6.3-amd64-2.7/build
    creating build/temp.openbsd-6.3-amd64-2.7/build/temp.openbsd-6.3-amd64-2.7
    clang -fno-strict-aliasing -OPT:Olimit=0 -O2 -pipe -DNDEBUG -O2 -pipe -fPIC -fPIC -I/usr/local/include/python2.7 -c build/temp.openbsd-6.3-amd64-2.7/_openssl.c -o build/temp.openbsd-6.3-amd64-2.7/build/temp.openbsd-6.3-amd64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.openbsd-6.3-amd64-2.7/_openssl.c:2155:25: warning: implicit conversion changes signedness: 'const int' to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
            return session->master_key_length;
            ~~~~~~ ~~~~~~~~~^~~~~~~~~~~~~~~~~
    build/temp.openbsd-6.3-amd64-2.7/_openssl.c:2157:27: warning: implicit conversion changes signedness: 'const int' to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
            outlen = session->master_key_length;
                   ~ ~~~~~~~~~^~~~~~~~~~~~~~~~~
    build/temp.openbsd-6.3-amd64-2.7/_openssl.c:2269:19: warning: incompatible pointer to integer conversion initializing 'const long' with an expression of type 'void *' [-Wint-conversion]
    static const long SSL_OP_NO_DTLSv1 = NULL;
                      ^                  ~~~~
    build/temp.openbsd-6.3-amd64-2.7/_openssl.c:2270:19: warning: incompatible pointer to integer conversion initializing 'const long' with an expression of type 'void *' [-Wint-conversion]
    static const long SSL_OP_NO_DTLSv1_2 = NULL;
                      ^                    ~~~~
    build/temp.openbsd-6.3-amd64-2.7/_openssl.c:2334:6: error: conflicting types for 'X509_get0_signature'
    void X509_get0_signature(ASN1_BIT_STRING **psig, X509_ALGOR **palg,
         ^
    /usr/include/openssl/x509.h:906:6: note: previous declaration is here
    void X509_get0_signature(const ASN1_BIT_STRING **psig,

**Comment by cypa** [comment]
with egcc (GCC) 4.9.4 got this error

    creating build/temp.openbsd-6.3-amd64-2.7/build/temp.openbsd-6.3-amd64-2.7
    /usr/local/bin/egcc -fno-strict-aliasing -OPT:Olimit=0 -O2 -pipe -DNDEBUG -O2 -pipe -fPIC -fPIC -I/usr/local/include/python2.7 -c build/temp.openbsd-6.3-amd64-2.7/_openssl.c -o build/temp.openbsd-6.3-amd64-2.7/build/temp.openbsd-6.3-amd64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    cc1: error: argument to '-O' should be a non-negative integer, 'g', 's' or 'fast'
    error: command '/usr/local/bin/egcc' failed with exit status 1

**Comment by cypa** [comment]
this?
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=174525
