### ISSUE TITLE
Once OpenSSL 1.1.1 comes out - don't use our custom ENGINE on it

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3867]
1.1.1 has a new DRBG system, which does good things. We can drop our custom engine when we're using it.

**Comment by alex** [comment]
Note to self: make sure OpenSSL either enables the at-fork behavior, or do it ourselves.

**Comment by reaperhulk** [comment]
https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_init_crypto.html is what we'll want to bind and pass `OPENSSL_INIT_ATFORK`. We should confirm this will properly register fork handlers on any platform we care about.

**Comment by reaperhulk** [comment]
#4714 implements this so we can discuss it more there.

**Comment by reaperhulk** [comment]
Okay, the complexity and risk this adds isn't worth it until we can entirely ditch our custom engine for the OpenSSL one. Closing for now.

**Comment by tiran** [comment]
According to your ticket https://github.com/openssl/openssl/issues/9859 OpenSSL 1.1.1d+ is now guaranteed to have a fork-safe DRBG. Can we skip the custom osrandom engine for OpenSSL >= (1, 1, 1, 4) ?

**Comment by reaperhulk** [comment]
We could, yes. I would review such a patch :)
