### ISSUE TITLE
x509 import asn1crypto(asn1crypto>=0.21.0)，but asn1crypto has a bug fixed and has not new release

### ISSUE THREAD

**Issue by anhkgg** [pyca/cryptography#3868]
in file `cryptography/src/cryptography/x509/extensions.py`, import asn1crypto
```
from asn1crypto.keys import PublicKeyInfo
```
cryptography limit asn1crypto>=0.21.0，but the newest release version has bug fixed in：
[https://github.com/wbond/asn1crypto/commit/64ab19707acb644772a9ac3d94479fbe79b49365](https://github.com/wbond/asn1crypto/commit/64ab19707acb644772a9ac3d94479fbe79b49365).

asn1crypto has not release the fixed commit.

so. when i use cryptography on Python 2, the unicode string here may raise a UnicodeDecodeError as it
tries to join a bytestring path to the unicode name "crypto"

Please show me a solution. Thanks!

**Comment by reaperhulk** [comment]
File an issue against asn1crypto requesting a release please.

**Comment by anhkgg** [comment]
@reaperhulk https://github.com/wbond/asn1crypto/issues/68#issuecomment-323489475

**Comment by reaperhulk** [comment]
Closing since this is an asn1crypto issue. Hopefully @wbond can get a release out soon!

**Comment by wbond** [comment]
Sorry for the delay – moved out of one place, got stuck in limbo, then moved into the new place and got sick right after! Hoping to have the release happen soon.
