### ISSUE TITLE
Support for AES-IGE mode of operation

### ISSUE THREAD

**Issue by Lonami** [pyca/cryptography#3875]
[I know it's only used for Telegram](https://www.mgp25.com/AESIGE/), but it would be nice to have it directly in this Python module.

**Comment by alex** [comment]
We are unlikely to add something which such limited usage, particular Telegram, given it's poor cryptographic history.

**Comment by Lonami** [comment]
In case anyone is bothered here's a [C implementation](https://github.com/kokke/tiny-AES-c/pull/91) for it I wrote myself for the [tiny AES](https://github.com/kokke/tiny-AES-c) library.

**Comment by reaperhulk** [comment]
It wouldn’t be a maintenance burden, but any proposal for adding it needs to come up with a way to convey that it is a bad mode that shouldn’t exist and is provided solely for compatibility purposes.

**Comment by Lonami** [comment]
Good documentation, perhaps? An "important" or "note" block perhaps with with bold words "It is not encouraged to use X unless you know what you're doing" or "You shouldn't use X and favour Y".

**Comment by reaperhulk** [comment]
We do that in some other places and it's as good as we know how to do right now. I would review an IGE patch at this point as I believe that while it's an awful mode we should support the things needed to interoperate with major projects (Even if those major projects made some very, very weird choices). Ignoring it is just encouraging people to look in more dangerous locations/do more dangerous things.

To be clear, here's what is needed to land IGE:

- [ ] Test vectors (https://www.links.org/files/openssl-ige.pdf) converted into NIST compatible form (see: https://github.com/pyca/cryptography/blob/cd4de3ce6dc2a0dd4171b869e187857e4125853b/vectors/cryptography_vectors/ciphers/AES/CBC/CBCGFSbox128.rsp) and information about them added to `test-vectors.rst`. This should be the first PR.
- [ ] The actual implementation (which is actually pretty simple, follow the form of CBC)
- [ ] Tests using those vectors (see `test_aes.py`)
- [ ] Docs describing it and noting that it is bad and provided for compatibility purposes only

**Comment by Lonami** [comment]
So, may we reopen the issue to keep track of the progress?

**Comment by reaperhulk** [comment]
Okay, maintaining a separate set of bindings and dedicated code just for a single (bad) cipher mode is not something we're willing to do so the answer remains no on adding support.

**Comment by habnabit** [comment]
Yikes! Didn't know it was this bad. Thanks for humoring the idea, at least.
