### ISSUE TITLE
Addition of a utility method to MultiFernet to aid in primary key rotation and re-encryption

### ISSUE THREAD

**Issue by derwolfe** [pyca/cryptography#3882]
I've been using `MultiFernet` and recently needed to rotate the primary key. While `MultiFernet` makes encrypting and decrypting secrets easy, it doesn't provide a utility to re-encrypt all secrets with a new primary key. I'd like to add a method to `MultiFernet` that does exactly this - I also have some code with tests that already do so :).

Benefits: by making key rotation for `MultiFernet` a thing that cryptography solves, it is one less concern that consumers of cryptography need to worry about.

Negatives:
1. It is possible that consumers won't want to take a list of their secrets and reencrypt them as a separate step - that is, were I implementing this myself, I might want to associate some data with the secret to make sure that I've not somehow altered which secret was associated with what.
2. Arguably, key rotation isn't a problem specific to Fernet. That said, my opinion is that this _is_ `MultiFernet` specific - `MultiFernet` already provides utility to allow the user to operate with multiple keys at a time.

As for the implementation, it could simply consist of a new method on `MultiFernet` named `rotate`. The `MultiFernet` instance has keys to decrypt all messages with the new primary being first in the list of keys. `rotate` would take a list of secrets and return a list of secrets re-encrypted with the new primary key. If any error occurred during re-encryption or decryption, that error would be raised as if `encrypt` or `decrypt` had been used directly.

What do you think?

**Comment by reaperhulk** [comment]
Conceptually I like the idea of simplifying rotation. What do you envision it doing if you supply a token that is already encrypted under the current key? Does it re-encrypt with a new random IV or just pass it through? What do you do with tokens that have a ttl?

**Comment by derwolfe** [comment]
> What do you envision it doing if you supply a token that is already encrypted under the current key? Does it re-encrypt with a new random IV or just pass it through?

My current implementation decrypts the token and then reencrypts using a new random IV. I've chosen this because it allows us to leverage the current `Multifernet` `encrypt` and `decrypt` methods without modification.

> What do you do with tokens that have a ttl?

I've planned on allowing users to supply a single `TTL` to use for the entire list of tokens to be reencrypted. If one token fails decryption because its `TTL` has expired, then the entire re-encryption operation would fail. I'm definitely not sure if this is a reasonable API.

**Comment by reaperhulk** [comment]
Okay, I think re-encrypting anything passed is a reasonable behavior.

(Disclaimer: I hate fernet TTLs)
It seems okay to me to say that a user passing an iterable of items for re-encryption is responsible for verifying before passing that any given token has not expired. Caveat: we have no public method to check for token validity short of just calling decrypt -- maybe we should?

**Comment by derwolfe** [comment]
Perfect. I'll put up a PR that just re-encrypts.

>Caveat: we have no public method to check for token validity short of just calling decrypt -- maybe we should? 

I could go either way on this; I've not been a user of TTLs so I'm not sure if this is a thing that users want. But! I don't think it would be difficult at all to add - the code for verifying this is effectively already present in https://github.com/pyca/cryptography/blob/master/src/cryptography/fernet.py#L87-L96.

Do the other fernet implementations expose public methods for checking token validity? I don't think that the ruby, clojure, or go implementations do.
