### ISSUE TITLE
OAEP label support

### ISSUE THREAD

**Issue by srihanfb** [pyca/cryptography#3883]
This was discussed over in #1663, and at the time the decision was to pass on adding support for OAEP labels: (https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/rsa.py#L60)

The TCG TPM2 spec makes use of OAEP labels, so there's now an actual use case for this. (TPM2_MakeCredential->CryptSecretEncrypt->CryptRsaEncrypt  in https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-4-Supporting-Routines-01.38-code.pdf)

**Comment by reaperhulk** [comment]
Hmm, okay. Supporting OAEP labels does seem useful given that use case. Thanks for filing a new issue!

**Comment by reaperhulk** [comment]
To land support for this we need some test vectors. It doesn't look like OpenSSL has any and I haven't found them in boring yet (although it's possible they're there, I just don't know the boring project structure very well)

**Comment by reaperhulk** [comment]
https://boringssl-review.googlesource.com/c/boringssl/+/19964 (thanks to David Benjamin for generating a vector here)

**Comment by srihanfb** [comment]
I started asking around, but looks like you've already located some test vectors. thanks for tracking those down.

**Comment by alex** [comment]
https://boringssl.googlesource.com/boringssl/+/ce3773f9fe25c3b54390bc51d72572f251c7d7e6

**Comment by srihanfb** [comment]
Thanks so much! Really appreciate the responsiveness. 

One follow up question: when is the next major release planned? Happy to pull master for now, but would like to move to a supported release once it's possible.

**Comment by alex** [comment]
At a guess, about a month. Just a guess though.
