### ISSUE TITLE
Support for X509_NAME_hash on x509.Name objects

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#3886]
I'm trying to interoperate with a program that implements a "CA path" mechanism for efficient lookup of certificates in a directory. That tool relies on OpenSSL's X509_NAME_hash function to compute the hash (which is returned as a 32-bit integer).

I see that this request came up last year in #3011, and that issue was closed with a response that the application should do its own hashing on the raw bytes of the name. The problem with that solution is that OpenSSL does some rather esoteric "canonicalization" of the X.509 names before computing the hash, and I really don't want to try and replicate all of that in my own code. Since my goal is specifically to interoperate with OpenSSL, I'd really like a way to access its canonicalization code, at least when using the OpenSSL backend. Is there any way a backend-specific function could be provided for this purpose?

In looking at the code, the specific canonicalization I've found so far involves not only things like trimming leading, trailing, and multiple spaces in names and converting them to lowercase, but also even more subtle things like converting the ASN.1 type of the values in some cases from PrintableString to UTF8String, so it requires some very low-level mucking around where you unpack and re-pack the ASN.1 encoding.

I understand that OpenSSL's hash is pretty ugly, and in fact that it changed in OpenSSL 1.x vs. prior releases, so it's not the best thing to rely on. However, there are tools out there which still use it, and it looks like X509_NAME_hash may already have a binding in cryptography. It just isn't exposed in a way that lets me use it without relying on internals of the existing cryptography OpenSSL backend.

For what it's worth, pyOpenSSL already supports this, but I haven't found a good way to convert x509.Name objects to pyOpenSSL's X509Name. I can't even do this by converting to DER bytes, as pyOpenSSL doesn't provide a way to import an X.509 name as DER bytes.

**Comment by alex** [comment]
FWIW, if you have a full cert object, you can convert the `cryptography.x509.Certificate` to an `OpenSSL.crypto.X509` with `X509.from_cryptography`.

**Comment by ronf** [comment]
Yeah, that's true, and I am doing that kind of conversion on certs to perform certificate chain validation right now, since that's not something that cryptography can do directly yet.

For the specific case of finding certificates to build a trust chain, I could probably make this work by asking pyOpenSSL to compute the issuer hash of the certificate I'm starting from. While pyOpenSSL only provides subject_name_hash() and not issuer_name_hash(), doing cert.get_issuer().hash() seems to work. I was really hoping to provide a more abstract API where only the subject name and not a full cert was required, though.

Also, my long-term goal is to remove the dependency on pyOpenSSL -- the ONLY reason I added it was for the certificate chain validation. Everything else I do (including all certificate generation) is already 100% cryptography-based. So, I think this would still make a good addition into cryptography.

**Comment by reaperhulk** [comment]
Where are you getting your x509.Name objects from? Part of the issue here is that we don't keep a backend specific representation alive within the x509.Name class and we don't support parsing the DER directly. For a certificate this is easily computable from the bindings, however. To do it you'll call `X509_get_subject_name` on the x509 object and then call `X509_NAME_hash` on that. To do it directly from DER we'd need to bind `d2i_X509_NAME`

**Comment by ronf** [comment]
You're right - in my current code, there's no case where I'm starting from DER of just a raw name. At the moment, I support three cases:

  * A comma/plus/equals-separated text string (which I had to do my own parsing of to convert it to a list of RDNs, each of which is a set of OID/value pairs
  * The RDNs of an existing name, to make a copy of it
  * A DER or PEM certificate I ask cryptography to load which I then access the subject or issuer of

In all cases, I end up with a cryptography.x509.Name, and that's what I was hoping to have the hash() method on.

That said, I guess I don't have much use for calling this hash() function in the context of the first two cases. I mainly use those for constructing subject and issuer values to feed into the certificate builder or for building up names that I can use to match against names I extract from certificates. So, perhaps having this only available as something like a subject_name_hash() and issuer_name_hash() on x509.Certificate would be good enough (and for now I could hack that by using pyOpenSSL).

**Comment by reaperhulk** [comment]
You can also avoid pyOpenSSL (for this case) with this bit of code. Given a cryptography `x509.Certificate` object named cert: `cert._backend._lib.X509_NAME_hash(cert._backend._lib.X509_get_issuer_name(cert._x509))`

That obviously touches non-public API and we won't guarantee it, but thus far we haven't wanted to make changes to those private attributes since we first added x509 support.

These hashes are so incredibly OpenSSL (and OpenSSL version) specific I think that functionality probably will remain in pyOpenSSL and not be hoisted into cryptography for the foreseeable future.
