### ISSUE TITLE
OCSP Support

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3887]
This is a meta-issue to track the various PRs and the overall state of OCSP support in cryptography.

Current state: nothing done!

**Comment by reaperhulk** [comment]
Some discussion here: https://github.com/pyca/cryptography/pull/4261#issuecomment-410908923

**Comment by reaperhulk** [comment]
We can now both parse and generate OCSP requests and responses in master. Closing as fixed for 2.4.

**Comment by FranklinYu** [comment]
Is there any example how do we send out OCSP requests with this module? I would like to send OCSP request and save the response in a file.

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/x509/ocsp/#creating-requests documents how to create requests. You must send encoded requests via POST (DER encoded) or GET (base64 encoded) to the OCSP server yourself.

**Comment by FranklinYu** [comment]
@reaperhulk Thanks. I read the details in [RFC 6960](https://tools.ietf.org/html/rfc6960#appendix-A); shall we link to that RFC in the OCSP page of our documentation? Or even better, also provides an example using requests library? I think others may also benefit from that.

**Comment by reaperhulk** [comment]
We'd be happy to take a docs PR for this!

**Comment by FranklinYu** [comment]
Would the OCSP Request Builder also tell me the endpoint URL?

**Comment by reaperhulk** [comment]
No, you'll need to parse that out of the certificate. It will be in the AuthorityInformationAccess extension.

**Comment by FranklinYu** [comment]
Does it make sense to include this in the OCSP Request Builder? I can PR if you like

**Comment by reaperhulk** [comment]
Destination of request is separate from building it. An example showing this complete flow is very welcome but I don’t think it makes sense to add anything to the builder.
