### ISSUE TITLE
Support GeneralizedTime/UTCTime choice in notBefore and notAfter

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3927]
We tried to be clever and automatically Do The Right Thing™ per RFC 5280 with regard to encoding the not valid before and not valid after times as UTCTime (through 2049) and GeneralizedTime (thereafter). Unfortunately, sometimes governments don't read RFCs. As seen on the mailing list (https://mail.python.org/pipermail/cryptography-dev/2017-September/000815.html) the Brazilian government has a specification that requires the use of GeneralizedTime in all scenarios. So, we probably need to expand the API to allow selection of the underlying ASN1 time type.

References:

http://antigo.iti.gov.br/images/noticias/indice-noticias/2016/03_marco/Portaria_Padrao_CIE-v3.3.pdf
http://antigo.iti.gov.br/noticias/indice-de-noticias/5061-iti-disponibiliza-padrao-nacional-da-carteira-de-identificacao-estudantil-cie-2

**Comment by reaperhulk** [comment]
#3896 might be somewhat relevant to this.

**Comment by reaperhulk** [comment]
Right now our code uses ASN1_TIME_set to automatically obey RFC 5280. To support this case we'll need to generate GENERALIZEDTIME and UTCTIME ourselves when a type is passed, but we also need to error if a user tries to use UTCTime for a date >= 2050 (since that is not encodable).

The impedance mismatch between ASN.1, X.509, RFCs, and governments is frustrating.

**Comment by reaperhulk** [comment]
I think we're probably not going to add support for this. Our API isn't designed to carry this metadata, and in general it shouldn't have to (the RFC is very clear in this regard, notwithstanding a government's choice to mandate otherwise).

I don't think I want to make the API significantly more complex (and the underlying code substantially harder to maintain and reason about) to support this edge case. I'll leave this open until #3896 (which is vaguely related) lands in case I change my mind, but provisionally we're not going to do this.

**Comment by ftbarata** [comment]
Hi @reaperhulk , firstly, sorry for my low skill. From your penultimate post, it seems that it's possible to use GeneralizedTime type until year < 2050, is it correct? If so, how to do it? But if I misunderstood, do you have ANY recommendation for me to solve this? (mainly the easiest way)

**Comment by reaperhulk** [comment]
It is not possible to do it without changing the code in ways we're not going to support. You'll need to find another tool to accomplish this, sorry :(

**Comment by alex** [comment]
I'm going to close this; this is in direct contravention of the RFC, and the use cases are few and far between.

If I found myself in a situation where I needed this, I'd probably maintained a patched fork of cryptography.

**Comment by ftbarata** [comment]
Hi everyone. Two years later I'm here to ask if Generalized Time is now available.

**Comment by alex** [comment]
No, as my last comment indicates, we closed this as "WONTFIX".
