### ISSUE TITLE
Cryptography 2.1 Invalid Environment Marker: Python_verison < '3'

### ISSUE THREAD

**Issue by BelieveMeJake** [pyca/cryptography#3964]
Today cryptography version 2.1 got released, and we are installing twilio 6.4.1, which has a dependency on cryptography>=1.3.4, therefore grabbing the latest version.

When installing twilio==6.4.1 or cryptography==2.1 i get some nice errors, stating I do not have python3 (I am using Python 2.7):

`Downloading/unpacking cryptography>=1.3.4 (from twilio==6.4.1->-r requirements.txt (line 3))
  Downloading cryptography-2.1.tar.gz (441kB): 441kB downloaded
  Running setup.py (path:/foo/bar/venv/build/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'
`

For now, I am telling my requirements to install in a different order to get a non-broken version:
cffi==1.10
cryptography==1.9
twilio==6.4.1

**Comment by alex** [comment]
What version of setuptools are you using?

This problem is almost certainly solved by upgrading to a more recent version.


I'm going to close this, but if that doesn't solve it please leave a comment so we can reopen.
