### ISSUE TITLE
python_implementation is not defined

### ISSUE THREAD

**Issue by ckochenower** [pyca/cryptography#3965]
The following stack trace is given when pip installing cryptography 2.1
<pre>
Collecting cryptography
Exception:
Traceback (most recent call last):
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 561, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2774, in extras
    return [dep for dep in self._dep_map if dep]
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2797, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2830, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2827, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'python_implementation' is not defined
</pre>
Python Version: Python 2.7.7

The following are the currently installed python packages:
aci (9.1.x)
asn1crypto (0.23.0)
backports-abc (0.5)
backports.ssl-match-hostname (3.5.0.1)
certifi (2017.7.27.1)
cffi (1.11.2)
chardet (3.0.4)
coverage (4.4.1)
cryptography (2.0)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
idna (2.6)
ipaddress (1.0.18)
Jinja2 (2.9.6)
jsonschema (2.6.0)
linecache2 (1.0.0)
MarkupSafe (1.0)
mock (2.0.0)
nose (1.3.7)
pbr (3.1.1)
pip (7.1.2)
psutil (5.3.1)
pycparser (2.18)
pycrypto (2.6.1)
PyInstaller (3.1.1)
pyOpenSSL (17.3.0)
PyYAML (3.12)
repoze.lru (0.7)
requests (2.18.4)
setuptools (18.2)
simple-crypt (4.1.7)
singledispatch (3.4.0.3)
six (1.11.0)
tornado (4.5.2)
traceback2 (1.4.0)
unittest2 (1.1.0)
urllib3 (1.22)
wheel (0.24.0)

**Comment by ckochenower** [comment]
The installation of cryptography version 2.0 does NOT strack trace.

**Comment by alex** [comment]
What version of setuptools are you using?

This problem is almost certainly solved by upgrading to a more recent version.

I'm going to close this, but if that doesn't solve it please leave a comment so we can reopen.

**Comment by ckochenower** [comment]
@alex - Can you please clarify what "upgrading to a more recent version" means? 2.1 is currently the latest version of cryptography. Are you referring to a newer version of python and/or pip?

**Comment by alex** [comment]
Oops, sorry I dropped a word. A more recent version of setuptools.

**Comment by ckochenower** [comment]
I upgraded setuptools to 36.5.0 (latest version) and the installation of crypto 2.1 continues to stacktrace with an identical stacktrace.

Steps to reproduce:

1. Create a python virtualenv using python 2.7.7
2. pip install cryptography. As of today, version 2.1 will stacktrace. Version 2.0 does NOT stacktrace.

<code>
>virtualenv --python=python2.7 --always-copy venv

(venv)> python --version
Python 2.7.7

(venv)> pip list
backports-abc (0.5)
backports.ssl-match-hostname (3.5.0.1)
certifi (2017.7.27.1)
chardet (3.0.4)
coverage (4.4.1)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
idna (2.6)
jsonschema (2.6.0)
mock (2.0.0)
nose (1.3.7)
pbr (3.1.1)
pip (7.1.2)
pycrypto (2.6.1)
repoze.lru (0.7)
requests (2.18.4)
setuptools (36.5.0)
simple-crypt (4.1.7)
singledispatch (3.4.0.3)
six (1.11.0)
tornado (4.5.2)
urllib3 (1.22)
wheel (0.24.0)

(venv)> pip install cryptography==2.1
Collecting cryptography==2.1
Exception:
Traceback (most recent call last):
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/req/req_set.py", line 561, in _prepare_file
    set(req_to_install.extras) - set(dist.extras)
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2774, in extras
    return [dep for dep in self._dep_map if dep]
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2797, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2830, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2827, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'python_implementation' is not defined
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
</code>

**Comment by alex** [comment]
Interesting, reopening.

Can you try upgrading pip as well?

**Comment by ckochenower** [comment]
That did it!

<code>
(venv)> pip install --upgrade pip
/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-9.0.1

(venv)> pip install cryptography==2.1
Collecting cryptography==2.1
/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/tmp/installer/web/ui/venv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached cryptography-2.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography==2.1)
  Using cached cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography==2.1)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography==2.1)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Requirement already satisfied: idna>=2.1 in ./venv/lib/python2.7/site-packages (from cryptography==2.1)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python2.7/site-packages (from cryptography==2.1)
Collecting ipaddress; python_version < "3" (from cryptography==2.1)
  Using cached ipaddress-1.0.18-py2-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography==2.1)
Installing collected packages: pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography
Successfully installed asn1crypto-0.23.0 cffi-1.11.2 cryptography-2.1 enum34-1.1.6 ipaddress-1.0.18 pycparser-2.18
(venv)autobuild@us-devops-build10:/tmp/installer/web/ui>
</code>

So we now know that the latest version of setuptools in combination with the latest version of pip resolves the issue. However, the community might want to know the minimum version of both that will work.

Thanks for your help.

**Comment by alex** [comment]
Glad it worked. We'll try to fine-tune the docs for this.

**Comment by mattclay** [comment]
Versions of pip prior to 8.1.2 are not able to install cryptography 2.1 due to this error.

This means that, for example, Ubuntu 16.04 LTS (which has pip 8.1.1) cannot install cryptography 2.1 without using a newer version of pip.

**Comment by reaperhulk** [comment]
Reopening this because we've improved the situation with #3970, which we'll be backporting to a 2.1.1 release. We'll close this once 2.1.1 is out.

**Comment by reaperhulk** [comment]
The fix for this is now in 2.1.1. Note that we still require a newer pip and setuptools than 2.0.3, so if you stumble upon this issue and think you have thes ame problem please upgrade those two things before filing a new issue.

**Comment by mattclay** [comment]
@reaperhulk What is the minimum version of pip you're aiming to support?

**Comment by reaperhulk** [comment]
The confluence of setuptools/pip and distributions unvendoring various dependencies (such as the `pkg_resources 0.0.0` nonsense from Ubuntu) makes it very difficult to state what the true minimum is. I **think** pip 6 will work with setuptools 20.7+ (possibly 18.0?), but after testing about 50 permutations I start getting confused. (And of course you won't get a manylinux1 wheel unless you're on pip 8.1+)

Ultimately we just want to utilize setuptools environment markers. `requests` currently does this so it's definitely achievable, although they only use `python_version` while we use both `python_version` and `platform_python_implementation` (2.1 used `python_implementation`, which caused the issue in Xenial).
