### ISSUE TITLE
'enum34' should be installed on Python 3.3

### ISSUE THREAD

**Issue by remram44** [pyca/cryptography#3978]
'enum34' gets correctly installed on Python 2.7 but not on Python 3.3, which leads on a crash on that version. While I do not know if you should be supporting 3.3, this seems like an easy fix.

The [current requirement](https://github.com/pyca/cryptography/blob/0a42f4eba88c380c08ae84a2803676843d61451c/setup.py#L283) is:
```
":python_version < '3'": ["enum34", "ipaddress"],
```

**Comment by alex** [comment]
We stopped supporting Python 3.3 in cryptography2.0: https://cryptography.io/en/latest/changelog/#v2-0
