### ISSUE TITLE
in window OS Unable to load certificate

### ISSUE THREAD

**Issue by sspankaj** [pyca/cryptography#3980]
python version 2.7.13
cryptography version 2.1.1
**my code is**
def generate_app_key():
			appkey_string = get_app_key()
			return encrypt_using_public_key(appkey_string)

def encrypt_using_public_key(data):
	backend = default_backend()

	cert = x509.load_der_x509_certificate(
		open("C:\Users\pankaj.TOUCHINC\PycharmProjects\gst\GSTN_G2A_SANDBOX_UAT_public.cer").read(),backend)
	public_key = cert.public_key()
	binary_data = public_key.encrypt(bytes(data),padding.PKCS1v15())
	return base64.encodestring(binary_data)

error ValueError: Unable to load certificate

but it working fine in ubuntu...

**Comment by tiran** [comment]
You have to open the file in binary mode.

**Comment by sspankaj** [comment]
it is working now thanks
