### ISSUE TITLE
python_version 3 required now as of 2.1 ?

### ISSUE THREAD

**Issue by bfloydgsn** [pyca/cryptography#3981]
Collecting cryptography>=1.9 (from pyOpenSSL>=0.13->gsutil)
  Downloading cryptography-2.1.1.tar.gz (441kB)
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    

previous versions worked fine. FYI

**Comment by alex** [comment]
This is because you have an out-of-date setuptools (and possibly an out of date pip as well). Please upgrade them and let us know if that solves this for you.

**Comment by anlutro** [comment]
How do you define out of date? I ran into this issue on a plain Ubuntu 14.04 machine, which is running setuptools 3.3.

**Comment by alex** [comment]
I believe we require setuptools 18.5 or newer
