### ISSUE TITLE
Add valid signature support for decryption after encryption token runs through another file

### ISSUE THREAD

**Issue by simonsterj** [pyca/cryptography#3982]
cryptography = 2.1.1  
cffi = 1.11.2  
pip = 9.0.1  
python = 3.5.2  

https://stackoverflow.com/questions/46735960/cryptography-token-object-raises-exception-and-cannot-decrypt-even-though-the-to  

The exception: `InvalidSignature("Signature did not match digest.")` followed by, `InvalidToken` will raise even if the token running through the `f.decrypt()` method is proper.  
It will happen in the occasion that the token was saved outside the original program that it was originally encrypted/created in.  
Is this a built-in safety feature? Is there a work-around to it?

**Comment by alex** [comment]
As far as I can tell your example program generates a new key every single it runs; the key used when decrypting must be the same as was used to encrypt it.

**Comment by simonsterj** [comment]
@alex Thanks for the response. That's definitely the problem.
