### ISSUE TITLE
Initial PKCS7 Support

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#3983]
Let's actually implement a very small subset of functionality and start expanding from there. If we implement what's needed to support the use case of [ROCA](https://github.com/crocs-muni/roca/blob/master/roca/detect.py#L1610-L1612) and [apk_parse](https://github.com/ph4r05/apk_parse/blob/master/apk_parse/apk.py#L332-L333) that's only a few functions:

`load_pem_pkcs7`, `load_der_pkcs7`, and a `PKCS7` object that looks roughly like:

```python
class PKCS7(object):
    @abstractmethod
    def signer_certificates(self):
        pass
```

where `signer_certificates` is a list of `Certificate` objects.

No verify support, no signature checking, no detached/attached, etc etc.

(Putting this up to remind myself to look into it more deeply soon. This may not be a practical MVP)

Refs #1621

**Comment by reox** [comment]
btw here is the androguard solution to read pkcs7 ;) 
https://github.com/androguard/androguard/blob/master/androguard/core/bytecodes/apk.py#L978-L1017

I would really like the possibility to just load the whole file into cryptography!

**Comment by utkonos** [comment]
Asked to add my use case here:
For processing signed malware. The use case is to use pefile to identify the DER data in the PE file, read that data into a variable, and finally parse that data using `cryptography`.

**Comment by hughsie** [comment]
I was asked to add my use case too:

For the LVFS we have to do the following two things:

 * Get the signer serial from a PKCS#7 detached signature
 * Verify a detached PKCS#7 signature against a certificate and a blob of binary data

I'm trying to convert my codebase away from Popen('certtool') which does support PKCS#7.

**Comment by alex** [comment]
We've landed initial pkcs7 support. Folks can file separate bugs for follow up feature requests.
