### ISSUE TITLE
cryptography/hazmat/bindings/openssl/binding.py ERROR

### ISSUE THREAD

**Issue by mrcarv** [pyca/cryptography#3985]
I get this error running miniconda's conda command. It's intermittent.

```
Traceback (most recent call last):
  File "/python/miniconda3/bin/conda-env", line 7, in <module>
    from conda_env.cli.main import main
  File "/python/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 38, in <module>
    from . import main_create
  File "/python/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 8, in <module>
    from conda.cli import common, install as cli_install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_load_locations'
```

So I edited binding.py and changed build_conditional_library to:
```
def build_conditional_library(lib, conditional_names):
    conditional_lib = types.ModuleType("lib")
    conditional_lib._original_lib = lib
    excluded_names = set()
    for condition, names_cb in conditional_names.items():
        if not getattr(lib, condition):
            excluded_names.update(names_cb())

    for attr in dir(lib):
        if attr not in excluded_names:
            try:
                setattr(conditional_lib, attr, getattr(lib, attr))
            except:
                print('ATTR error', lib, attr)

    return conditional_lib
```

Just included the try except block. When I run conda now, it always works. Sometimes without the added output, sometimes it show this:
```
ATTR error <Lib object for '_openssl'> X509_STORE_load_locations
ATTR error <Lib object for '_openssl'> d2i_OCSP_REQUEST_bio
ATTR error <Lib object for '_openssl'> d2i_PKCS12_bio
ATTR error <Lib object for '_openssl'> d2i_PKCS7_bio
ATTR error <Lib object for '_openssl'> d2i_PKCS8PrivateKey_bio
ATTR error <Lib object for '_openssl'> d2i_PKCS8_PRIV_KEY_INFO_bio
ATTR error <Lib object for '_openssl'> d2i_PUBKEY_bio
ATTR error <Lib object for '_openssl'> d2i_RSAPublicKey
ATTR error <Lib object for '_openssl'> d2i_RSA_PUBKEY
ATTR error <Lib object for '_openssl'> d2i_RSA_PUBKEY_bio
```

I don't know the library to know the cause, but this fixed the issue and conda works just fine. Maybe it can help.

Thank you.

**Comment by alex** [comment]
How did you install cryptography? I don't see how this could be possible with our code.

My only bet would be if somehow you had a new version of our python code with an old version of our C code.

**Comment by mrcarv** [comment]
I use miniconda (https://conda.io/miniconda.html). Cryptography is installed by default in this python distribution, I believe.

The OS is Ubuntu 16.04.3 LTS (with all updates).

The 'root' virtualenv (installed by default by conda) has the following packages:
$ conda env export -n root
name: root
channels:
- defaults
dependencies:
- asn1crypto=0.22.0=py36h265ca7c_1
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.7.27.1=py36h8b7b77e_0
- cffi=1.10.0=py36had8d393_1
- chardet=3.0.4=py36h0f667ec_1
- conda=4.3.30=py36h5d9f9f4_0
- conda-env=2.6.0=h36134e3_1
- cryptography=2.0.3=py36ha225213_1
- idna=2.6=py36h82fb2a8_1
- libedit=3.1=heed3624_0
- libffi=3.2.1=h4deb6c0_3
- libgcc-ng=7.2.0=h7cc24e2_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- ncurses=6.0=h06874d7_1
- openssl=1.0.2l=h077ae2c_5
- packaging=16.8=py36ha668100_1
- pip=9.0.1=py36h8ec8b28_3
- pyasn1=0.3.7=py36h0f28794_0
- pycosat=0.6.2=py36h1a0ea17_1
- pycparser=2.18=py36hf9f622e_1
- pyopenssl=17.2.0=py36h5cc804b_0
- pyparsing=2.2.0=py36hee85983_1
- pysocks=1.6.7=py36hd97a5b1_1
- python=3.6.3=hc9025b9_1
- readline=7.0=hac23ff0_3
- requests=2.18.4=py36he2e5f8d_1
- ruamel_yaml=0.11.14=py36ha2fb22d_2
- setuptools=36.5.0=py36he42e2e1_0
- six=1.10.0=py36hcac75e4_1
- sqlite=3.20.1=h6d8b0f3_1
- tk=8.6.7=h5979e9b_1
- urllib3=1.22=py36hbe7ace6_0
- wheel=0.29.0=py36he7f4e38_1
- xz=5.2.3=h2bcbf08_1
- yaml=0.1.7=h96e3832_1
- zlib=1.2.11=hfbfcf68_1
- pip:
  - ruamel-yaml==0.11.14

**Comment by alex** [comment]
So I just created a fresh Ubuntu Trusty docker container, `apt update && apt upgrade`, then `curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`, ran the installer, but I can't seem to get it to fail the way you're seeing.

Is this something you're able to reproduce from a fresh image?

**Comment by mrcarv** [comment]
With a fresh install I can't reproduce it.

I thought conda packed most of the libraries with it. That's why I use it. Some packages that require compilation and take a long time to install are available precompiled, including some OS libraries.

Any suggestions on how could I find out which library is being used?

**Comment by alex** [comment]
Can you try `find /python/miniconda3/ -name _openssl.so` and then `strings <path> | grep OpenSSL`?

**Comment by alex** [comment]
Oh, also `ldd <path>`.

**Comment by mrcarv** [comment]
There's no _openssl.so anywhere on the system. I closest I found was:
```
$ ldd /python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so                                                                                                     
        linux-vdso.so.1 =>  (0x00007ffd085bb000)
        libssl.so.1.0.0 => /python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/../../../../../libssl.so.1.0.0 (0x00007f935f5ce000)
        libcrypto.so.1.0.0 => /python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/../../../../../libcrypto.so.1.0.0 (0x00007f935f18e000)
        libpython3.6m.so.1.0 => /python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/../../../../../libpython3.6m.so.1.0 (0x00007f935ec4a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f935ea2d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f935e663000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f935e45f000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f935e25c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f935e054000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f935dd4b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f935fb2e000)
$ strings /python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so | grep OpenSSL
OpenSSL 1.0.2l  25 May 2017
OpenSSL_add_all_algorithms
OpenSSL_version
OpenSSL_version_num
_cffi_d_OpenSSL_version
_cffi_f_OpenSSL_version
_cffi_d_OpenSSL_version_num
_cffi_f_OpenSSL_version_num
_cffi_d_OpenSSL_add_all_algorithms
_cffi_f_OpenSSL_add_all_algorithms

```

**Comment by alex** [comment]
`_openssl.abi3.so` was the right thing, good call.

I don't really understand what the issue is here.

My best suggestion is to see if you can figure out how the system got setup and into this state.

**Comment by mrcarv** [comment]
I really just recall doing regular updates, otherwise I wouldn't have posted a bug report. So I was assuming incorrectly my system was just like a fresh install. Since we established this is not the case, there must be something odd in here.
Thank you very much for your help.

**Comment by alex** [comment]
If you ever happen across a way to reproduce this from scratch, please let us know!
