### ISSUE TITLE
Tutorial for self-signed certificate uses b"localhost" byte string

### ISSUE THREAD

**Issue by jeroenp** [pyca/cryptography#3986]
from https://cryptography.io/en/latest/x509/tutorial/#creating-a-self-signed-certificate:

...     x509.SubjectAlternativeName([x509.DNSName(b"localhost")]),

My cryptography==2.0.3 complains that it wants a unicode instead of bytes for the DNSName. That sounds entirely reasonable to me.

**Comment by tiran** [comment]
You are reading the documentation for 2.1, b'localhost' is correct for 2.1. U-labels have been deprecated, https://cryptography.io/en/latest/changelog/#v2-1

**Comment by reaperhulk** [comment]
U-labels have been deprecated but to aid backwards compatibility we still require string rather than bytes. So this is a bug, thanks for the report @jeroenp

**Comment by ronf** [comment]
Is the plan to allow both bytes and strings for now, as long as the strings contain only ASCII (including possibly A-labels), or will it only allow strings?

**Comment by reaperhulk** [comment]
The API as landed in 2.1 allows only strings and raises a deprecationwarning if the string passed contains anything non-ascii. bytes are not currently allowed (mostly so we don't have the weird asymmetry of an API that takes bytes and returns string on calls to `value`).

**Comment by ronf** [comment]
Got it, thanks!
