### ISSUE TITLE
Pantsbuild fails to install cryptography-2.1.1

### ISSUE THREAD

**Issue by jincetomvinfy** [pyca/cryptography#3987]
I try to run a dockerized pants build for a scala project and it fails with an error message "**error in cryptography setup command: Invalid environment marker: python_version < '3'** ". I haven't manually specified anything to install cryptography. In the documentation of cryptography I could see that it happens either because of pip or setuptools is out of date. I tried to update this and there was no difference. It was working fine till 12 October 2017 (approx) and  later it turned to be not functional.

I use the following versions of

Ubuntu -14.04

python -2.7.4

pants -1.0.0 (tried upgrading to 1.1.0 but no difference).

Any guidance would be highly appreciated.

**Comment by tiran** [comment]
Upgrade to the latest version of ``setuptools`` and ``pip``, https://cryptography.readthedocs.io/en/latest/faq/#installing-cryptography-fails-with-invalid-environment-marker-python-version-3

**Comment by jincetomvinfy** [comment]
I already tried updating that. But that didn't resolve the issue and I have already mentioned that in the question

**Comment by alex** [comment]
Can you include a full traceback?

**Comment by jincetomvinfy** [comment]
please find the full traceback


![image](https://user-images.githubusercontent.com/28563214/31771332-5a076f60-b4f9-11e7-9c13-3569506852ec.png)

**Comment by jincetomvinfy** [comment]
![image](https://user-images.githubusercontent.com/28563214/31771376-8ae46930-b4f9-11e7-82c6-de43f2a9080e.png)

**Comment by jincetomvinfy** [comment]
![image](https://user-images.githubusercontent.com/28563214/31771393-9f630ef2-b4f9-11e7-8aea-33900fad3b99.png)

**Comment by jincetomvinfy** [comment]
![image](https://user-images.githubusercontent.com/28563214/31771416-b123198e-b4f9-11e7-9f75-682f0a00927e.png)

**Comment by jincetomvinfy** [comment]
![image](https://user-images.githubusercontent.com/28563214/31771545-242cb0ca-b4fa-11e7-9682-b75c84d2be3d.png)

**Comment by jincetomvinfy** [comment]
![image](https://user-images.githubusercontent.com/28563214/31771558-32efc048-b4fa-11e7-88c8-d756b71c956e.png)

**Comment by alex** [comment]
In the future, please post tracebacks as text, rather than as images, it makes things much simple to read.

Can you try upgrading to a newer version of pants, at least 1.1.2 or great.

**Comment by jincetomvinfy** [comment]
I tried to update pants to 1.2.0 which is the stable version after 1.1.0 (which I had already tried). But the problem is, our codebase is large and it has several dependencies that can't be resolved by this new version of pants. Since the migration is a time consuming task, and our team is blocked by this issue, can there be any other alternative work around?

**Comment by alex** [comment]
From my reading of the pex source code, it pins the version of setuptools it uses, and the versions it supports were bumped in more recent releases.

You'd have to ask the pants/pex team if there's a workaround on their side.

**Comment by jincetomvinfy** [comment]
Okay thanks for the info, if you come to any solution from your side, please keep us posted here.

**Comment by aayush26** [comment]
```
 Downloading cryptography-2.1.1.tar.gz (441kB)

100% |████████████████████████████████| 450kB 2.3MB/s

Complete output from command python setup.py egg_info:

error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'

----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0R7v1L/cryptography/
```
Is this error related to it? This error recently started to come while building my repo in Travis CI. Earlier, this issue never came.

```
$ python --version

Python 2.7.10 (7e8df3df9641, Jun 14 2016, 13:58:02)

[PyPy 5.3.1 with GCC 4.8.2]

$ pip --version

pip 8.1.2 from /home/travis/virtualenv/pypy-5.3.1/site-packages (python 2.7)
```

**Comment by alex** [comment]
That error indicates an out of date version of setuptools, please try upgrading it.

**Comment by aayush26** [comment]
@alex From which version of setuptools, this issue should be resolved?

**Comment by alex** [comment]
18.5 or greater I believe.

Closing this issue as there's no cryptography bug here.
