### ISSUE TITLE
Add a test in our wheel builder that all .so's are noexecstack

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#3994]
Follow up to #3993

**Comment by jlaine** [comment]
How can I test a change to the Jenkins config?

It looks like we need something like:

    unzip tmpwheelhouse/*.whl -d execstack.check
    (execstack execstack.check/cryptography/hazmat/bindings/*.so | grep '^X') && exit 1

**Comment by reaperhulk** [comment]
You can't directly test the change, what you'd need to do is grab the docker image and run the script yourself to see if it works as expected.

```docker run --rm -ti pyca/cryptography-manylinux1:x86_64 /bin/bash``` will get you in.
