### ISSUE TITLE
cryptography fails during install to directory and not regular ubuntu install.

### ISSUE THREAD

**Issue by jayzalowitz** [pyca/cryptography#3999]
Collecting cryptography>=2.0.0 (from moto->-r requirements.txt (line 10))
  Downloading cryptography-2.1.2.tar.gz (441kB)
    100% |████████████████████████████████| 442kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'

This keeps those of us who deploy lambdas from being able to locally install.

**Comment by alex** [comment]
What version of setuptools are you using? Can you try upgrading to the most recent version and see if you're still able to reproduce?

**Comment by jayzalowitz** [comment]
Ill be back in a couple minutes, its within circleci enterprise at the moment so it will defs take a second.

**Comment by jayzalowitz** [comment]
That worked. 
Maybe consider setuptools > x as a dep of this package? 
pip install  --upgrade setuptools
Collecting setuptools
  Downloading setuptools-36.6.0-py2.py3-none-any.whl (481kB)
    50% |████████████████                | 241kB 5.3MB/s eta 0:00:01    100% |████████████████████████████████| 483kB 1.2MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed setuptools-36.6.0

**Comment by alex** [comment]
Unfortunately setting setuptools as a dep doesn't work -- it errors out while reading setup.py, before any of the dependencies are installed.

**Comment by jayzalowitz** [comment]
A better error message on setup.py?

**Comment by alex** [comment]
Good idea.
