### ISSUE TITLE
Add bindings for signature algorithm API

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#4006]
``SSL_CTX_set1_sigalgs_list()`` et al are required to limit the signature algorithm in order to enforce a specific certificate type. For example Facebook uses a ECDSA server cert by default. In order to enforce RSA certs with TLS 1.2 or 1.3, ``SSL_CTX_set1_sigalgs_list(ctx, "RSA+SHA256:RSA+SHA384)`` can be used to retrieve cert with RSA PKCS#1 v1.5 signature. For TLS 1.2 it is also possible to limit the supported cipher suites to ``aRSA``. This trick will no longer work with TLS 1.3, though.

Background: https://bugs.python.org/issue31892

https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set1_sigalgs.html

https://www.openssl.org/docs/manmaster/man3/SSL_get_shared_sigalgs.html

**Comment by alex** [comment]
Makes sense. What version were these added in?

**Comment by tiran** [comment]
OpenSSL: 1.0.2 final
LibreSSL: n/a
