### ISSUE TITLE
cffi Dependency Specification Issue

### ISSUE THREAD

**Issue by hensleyjo** [pyca/cryptography#4013]
I installed cryptography==2.0.3 about a month ago via pip with no issue and implemented my project successfully, however, today when setting this up on my other partner's machines an issue occurred where the certificate_transparency module could not be imported. The cffi specification set on cryptography for pip installations specifies cffi > 1.7, but cffi put out a non-backwards compatible version that does not work with cryptography 2.0.3. The cffi version I had installed was 1.10.0 and this played nicely with the version of cryptography I need to use, but the new version (1.11.0) causes these module errors for certificate_transparency. The cffi dependency should not specify any version > 1.7 for the protection of installing non-backwards compatible versions. Until cryptography can play nicely with the newer versions of cffi, the dependency should be set to > 1.7, < 1.11. I was able to resolve this by specifying the version of cffi to install, but fixing this would save time for those who encounter and have to debug this issue. Thank you in advance for any feedback.

**Comment by reaperhulk** [comment]
We directly test cryptography in our CI system against the latest verson of cffi (see: https://travis-ci.org/pyca/cryptography/jobs/298282187#L569 for an example) with no issues. Can you provide instructions to replicate this in a fresh virtualenv?

**Comment by reaperhulk** [comment]
Closing in the absence of any way to reproduce. If you can provide a reproducer in a clean virtualenv please let us know!
