### ISSUE TITLE
Does using generate_private_key guarantees that the key is not 1 or the order of the EC group ?

### ISSUE THREAD

**Issue by karamjaber** [pyca/cryptography#4023]
In the API It is written about the function  **ec.generate_private_key(...)**: 

> Generate a new private key on curve for use with backend.

Does that gurantees that the key generated is not 1 or the order of the EC group ?
If no, Is there a way to validate that ? 
Because this function returns an instance of the object **EllipticCurvePrivateKey** and in the class it self i can't see a function which can give us the private key itself

**Comment by reaperhulk** [comment]
You can serialize the key to numbers via `private_numbers` if you want to look at the private scalar. Key generation is done via OpenSSL's default keygen function (https://github.com/openssl/openssl/blob/198c42f5af0d2cc0eb4789c7597b68b6b10cc97a/crypto/ec/ec_key.c#L198-L247) which prevents the key from being zero or the order of the group.
