### ISSUE TITLE
Staticly built version

### ISSUE THREAD

**Issue by scj643** [pyca/cryptography#4033]
Would it be possible to staticly compile for iOS 
This is to close https://github.com/omz/Pythonista-Issues/issues/49
Pythonista is an iOS app that’s a python IDE and I’ve been trying to push this so we can use more libraries in Pythonista.

**Comment by alex** [comment]
You can compile pyca/cryptography in any way that the python build toolchain supports -- our wheels are statically linked against OpenSSL for example.

I'm not sure I understand the question beyond that.

**Comment by alex** [comment]
No follow up, closing. We can reopen if it's determined there's something for us to do.
