### ISSUE TITLE
Is there any way to save key to file for using ECC?

### ISSUE THREAD

**Issue by Chenng** [pyca/cryptography#4042]
I want to use ECDH for my crypto but as I want to reuse the public and private key. So is there anyway to save and load the key or any other way to solve the problem? Thank you.

**Comment by alex** [comment]
We _strongly_ advise you not to reuse ECDH key pairs. Doing so makes it a long lived key, and means you don't get the useful operational security properties present in forward-secure systems.

That said, you can serialize private keys with: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKeyWithSerialization.private_bytes

And the equivalent `public_bytes` method on public keys.
