### ISSUE TITLE
[Feature Request] Make it possible to serialize X25519 keys

### ISSUE THREAD

**Issue by danielkza** [pyca/cryptography#4043]
From what I was able to find in the documentation, there is currently no way to serialize generated Curve25519 keys for later use. I want to use cryptography to generate keys to be used with OpenSSH. I can serialize RSA and ECDSA keys using their corresponding `private_bytes` and `public_bytes` methods, but there is nothing similar for the 25519 variants.

**Comment by alex** [comment]
What does OpenSSH use long-lived X25519 keys for?

**Comment by danielkza** [comment]
@alex Ed25519 is a supported for both host and user authentication as far as I can tell from the [OpenSSH documentation](https://man.openbsd.org/ssh-keygen#t). `ssh-keygen -t ed25519` can generate them, but I just noticed the private key is always stored in the "new" OpenSSH private key format, that looks like:

```
-----BEGIN OPENSSH PRIVATE KEY-----
{material}
-----END OPENSSH PRIVATE KEY----- 
```

Is it currently supported in cryptography? I've only found references to the OpenSSH *public* key format in the serialization documentation.

**Comment by alex** [comment]
We currently do not have any Ed25519 support; we have X25519, but the keys aren't simply interchangable.

#3509 tracks adding Ed25519 support.

**Comment by danielkza** [comment]
@alex I see, thanks for the clarification.

**Comment by ronf** [comment]
[AsyncSSH](http://asyncssh.readthedocs.io) is a Python package capable of supporting Ed25519 keys for SSH, including serializing/deserializing both public and private keys of that type in OpenSSH format. I'm the author of it, and would be happy to help if you have any questions about it.

**Comment by alex** [comment]
I should probably mention you can get an Ed25519 from PyNACL, which we also maintain: https://pynacl.readthedocs.io/en/stable/signing/

**Comment by danielkza** [comment]
@ronf @alex Thank you both very much. I'll evaluate both options with care.
