### ISSUE TITLE
ImportError: cannot import name certificate_transparency

### ISSUE THREAD

**Issue by TobCar** [pyca/cryptography#4049]
Hello I understand multiple people are having an issue importing certificate_transparency and I have another use case. When py2exe is used to compile a program into an executable and it uses a library that requires cryptography it cannot import certificate_transparency from the generated executable. The program runs fine when launching from Eclipse. I installed cryptography automatically when I installed the library I was using but I uninstalled it while debugging and reinstalled it. I also tried reverting back to cryptography 1.4 but I just got a different import error. Any thoughts?

**Comment by alex** [comment]
This looks like it's probably the same cause as #4046

**Comment by ReckyXXX** [comment]
Hi, I had a similar problem while packaging OpenSSL with py2exe, and found a solution just adding cffi to packages list in setup.py:

```
from distutils.core import setup
import py2exe

setup(
    options={
        'py2exe': {
            'packages': ['cffi']
        }
    },
    console=['myapp.py']
)
```
