### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by rgupta2** [pyca/cryptography#4055]
I am unable to build one of my projects written few months ago using Scrapy which has cryptography as a dependency. Its showing following error -

```
Downloading/unpacking cryptography>=2.1.4 (from pyOpenSSL->Scrapy==1.4.0->-r /app/requirements.txt (line 3))
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: platform_python_implementation != 'PyPy'
```

As I have no control over Scrapy's dependencies and I have been using Scrapy 1.4.0, latest release, alongwith Python 3, I am not sure what are my options now? Has there been any recent changes in cryptography package which could have led to above issue? 

Following is the command I use to install the dependencies

> pip3 install -r requirements.txt

Following is what my requirements.txt looks like

```
lxml==3.8.0
psycopg2==2.7.3.1
Scrapy==1.4.0
Twisted==17.5.0
validators==0.12.0
tweepy==3.5.0
```

I also posted the same on [Stackoverflow](https://stackoverflow.com/questions/47766609/unable-to-build-scrapy-based-project-due-to-invalid-environment-marker-error).

**Comment by alex** [comment]
This looks like an error due to having an out of date pip or setuptools.
Can you try updating them?

**Comment by rgupta2** [comment]
@alex Super thanks for the tip. It worked.
