### ISSUE TITLE
Feature: add function to format big numbers

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#4057]
i.e. this code:

```python
def format_bignum(num: int, separator=':'):
    return separator.join('%02x' % i for i in cryptography.utils.int_to_bytes(num))
```
or equivalent. Sometimes it's apropriate to set separator to `' '`.

**Comment by alex** [comment]
This feels outside the scope of cryptography to me; this is just a general string formatting function.

What do you think @reaperhulk ?

**Comment by reaperhulk** [comment]
Yeah I'm not in favor of this living in cryptography. Colon separated hex is purely presentational, which is obviously a useful thing in some contexts, but I think properly lives in whatever library/tool wants to do it.
