### ISSUE TITLE
Stop using ERR_error_string with a static buffer

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4058]
This is thread unsafe and bad and stuff:

* https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/bindings/openssl/binding.py#L58-L60
* https://github.com/pyca/cryptography/blob/master/tests/hazmat/backends/test_openssl.py#L128-L129

**Comment by tiran** [comment]
``ERR_error_string_n`` is available since 0.9.6. CPython doesn't use the dangerous one.
