### ISSUE TITLE
What encoding to use to decode the bytes we get from finalize in hmac?

### ISSUE THREAD

**Issue by karamjaber** [pyca/cryptography#4060]
For example in the following code : 
```
>>> from cryptography.hazmat.backends import default_backend
>>> from cryptography.hazmat.primitives import hashes, hmac
>>> h = hmac.HMAC(key, hashes.SHA256(), backend=default_backend())
>>> h.update(b"message to hash")
>>> finalizedVal = h.finalize()
```
I want to decode it to a string to send it over a chat which sends string.
What i did is the following 
`finalizedVal.decode(Some_decoding) `

None of the decoding i found decoded this.

**Comment by alex** [comment]
The output of an HMAC is raw bytes, you can't decode it as a string.

If you want to use it somewhere you need text, you'll need to convert it to something like hex or base64.
