### ISSUE TITLE
Why not use `EC_POINT_clear_free` and `BN_clear_free`?

### ISSUE THREAD

**Issue by tuxxy** [pyca/cryptography#4065]
Hey, folks!

Just a question -- why aren't `EC_POINT_clear_free` and `BN_clear_free` used? Instead, `EC_POINT_free` and `BN_free` are used.

It is my understanding that the formerly named functions clear the memory, then free it. This is safer compared to just freeing the memory.

Are there issues associated with using this? I already know about the nuances with how memory is handled on the system (ie: swap files, etc).

Much less, why aren't these simply exposed in the `backend`? `EC_POINT_clear_free` is exposed, but `BN_clear_free` is not.

**Comment by alex** [comment]
This would be a good addition.

**Comment by reaperhulk** [comment]
For anyone who wants to tackle this, a good way would be ~3 PRs.  Exposing `BN_clear_free`, using `BN_clear_free` in appropriate places, and using `EC_POINT_clear_free` in appropriate places.

**Comment by tuxxy** [comment]
With this said, maybe it would also be a good idea to expose and use `BN_secure_new` where possible, too?

@alex @reaperhulk Any thoughts on this?

**Comment by tuxxy** [comment]
@reaperhulk I'm bringing my discussion of `EC_POINT_clear_free` over here.

It seems that `EC_POINT_free` is only used in one place, as far as I can tell, and it's on a public value.

Using similar logic to the work on implementing `BN_clear_free`, should we just skip using `EC_POINT_clear_free`, then? See L1394 on `hazmat.backends.openssl.backend.py`

**Comment by reaperhulk** [comment]
Yeah let's skip it then.

**Comment by tuxxy** [comment]
Alright. I think #4072 will close out this issue, then. 🐧
