### ISSUE TITLE
`dh.generate_parameters` wasn't supported before 1.7

### ISSUE THREAD

**Issue by thomwiggers** [pyca/cryptography#4067]
As far as I can tell, the docs claiming support for `dh.generate_parameters` (and other things) starting from version 0.9 are wrong. The git blame suggests that these were first included in tag 1.7: https://github.com/pyca/cryptography/blame/master/docs/hazmat/primitives/asymmetric/dh.rst

I think they were first added by https://github.com/pyca/cryptography/commit/495f21a9c61befd4a61054dd1b6080164a7400e9#diff-6be0e8a855120dce88594543c96c1a05 which also touches the changelog of 1.7.

**Comment by reaperhulk** [comment]
It looks like we added the key interfaces in 0.9 but didn’t implement DH until 1.7. So we should update the docs as suggested. I’ll do that tonight if no one beats me to it.

**Comment by alex** [comment]
Nice catch. I'll let you get it @reaperhulk :-)
