### ISSUE TITLE
SSH public key format unclear

### ISSUE THREAD

**Issue by ericwb** [pyca/cryptography#4088]
After reading through the documentation and looking at the  cryptography.hazmat.primitives.serialization.load_ssh_public_key(data, backend) API, it's unclear exactly what format of public key is expected/allowed.

The docs state they are OpenSSH public keys, but then refers to RFC 4253 (which section is unknown).  But OpenSSH does not serialize its public keys according to the SSH standard spec.  The actual spec for serializing SSH keys is RFC 4716.  OpenSSH has its own format documented here: http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/usr.bin/ssh/PROTOCOL.certkeys?content-type=text/plain

So I think the docs just need some tweaking.  Easiest would be to remove mention of RFC 4253 and replace with PROTOCOL.certkeys.  

But it would also be very useful to support the official spec for persisting public keys (RFC 4716 ) and not be OpenSSH specific.

**Comment by reaperhulk** [comment]
Thanks for the report -- updating the docs sounds like a good idea. We could also potentially support RFC 4716, but I'd like to know what actually uses it before accepting a PR.

**Comment by ronf** [comment]
Multiple SSH products support RFC 4716 format, but I believe this format was initially used by the commercial SSH2 product from ssh.com.

If you are looking for RFC 4716 support in Python, my AsyncSSH package supports several public key formats including PKCS#1 DER and PEM, PKCS#8 DER and PEM, OpenSSH, and RFC 4716. AsyncSSH makes use of cryptography for all its low-level crypto, but it doesn't currently rely on cryptography for SSH key serialization, as AsyncSSH's implementation of that predates the one currently in cryptography.
