### ISSUE TITLE
Conditional dependencies use a deprecated(?) format

### ISSUE THREAD

**Issue by hynek** [pyca/cryptography#4090]
Let me start with the problem: installing `cryptography` using the currently heavily pushed `pipenv` on Python 2 is subtly broken (enum34 and ipaddress are missing from lock files), because they can’t handle the way conditional dependencies are currently set (extras_require, AFAIK that was never part of any standard?).

The currently blessed way to encode them is [PEP 508](https://www.python.org/dev/peps/pep-0508/) and it would be great if `cryptography` could switch to it. If you want more details, I’m trying to keep an up-to-date blog post about it: https://hynek.me/articles/conditional-python-dependencies/

In doubt, I’m sure @dstufft has opinions too. :)

**Comment by alex** [comment]
The syntax we use is supported by the widest range of pip and setuptools versions. Changing to use the more modern syntax involves breaking a non-trivial portion of our users. See discussions on https://github.com/pyca/cryptography/pull/3508 and others.

pipenv should grow support for `extra_requires` IMO.

Closing this as there's nothing we can do here without breaking our users.

**Comment by hynek** [comment]
They claim they literally can’t.

Great, Python packaging is officially shitty again if Pipenv becomes actually popular. :(

**Comment by alex** [comment]
Link to an issue? I don't see how that could be true.

**Comment by hynek** [comment]
JFTR the bug is here: https://github.com/pypa/pipenv/issues/1303

**Comment by hynek** [comment]
also JFTR as far as I can tell, the oldest pip supporting the PEP 508 is pip 1.4 from 2013.

**Comment by Zac-HD** [comment]
Also related to pypa/pipenv#1353.

While pip 1.4 may support installing *binary wheels* with conditional dependencies in `install_requires`, old versions of setuptools choke this format so it breaks installation of source distributions.  I don't know exactly when this started working, but there are definitely older setuptools in the wild 😢
