### ISSUE TITLE
Support x.509 Attribute Certificates

### ISSUE THREAD

**Issue by Blackjack92** [pyca/cryptography#4103]
Hello,

I checked the `cryptography` documentation and the internet but have not found any related information.
Does the `cryptography` module support _x.509 Attribute Certificates_?
If it does, how could an _AC_ be created?
If not, will this be supported in the near future?

Thanks in advance!

Furthermore, I checked the abstract `Certificate` class, this class contains a `public_key` which is no part of the _Attribute Certificate_.

**Comment by alex** [comment]
We don't believe this is a widely used standard, we're going to close this for now -- if there's some large scale usage we're not aware of we can reconsider.
