### ISSUE TITLE
Need help building cryptography for iOS

### ISSUE THREAD

**Issue by cculianu** [pyca/cryptography#4105]
This isn't a bug or a feature request.  I'm a totally exasperated objective-c/iOS programmer that's been tasked with importing a python-based app to iOS that depends on this cryptography lib.

I'm out of my domain here because I don't really "get" how to build Python packages that have native .so libs in them for another platform.

This setup.py stuff seems to "automagically" work -- but when you want to do something custom -- I have no idea how.

How do I build this cryptography package for iOS as an arm7, arm64, (and x86_64 for simulator) package?  In particular the .so libs this package produces need to be for those platforms as well.

Apologies if this is in the wrong place for this -- I just needed to ask.

**Comment by reaperhulk** [comment]
Unfortunately we don't test this configuration or have any experience building it in this fashion. Hopefully others out there with more experience dealing with Python on iOS can assist 😞

**Comment by cculianu** [comment]
Ha, I scoured the net.  There are 7 billion people in the world.  It appears I'm the only one that wants to do this.  So I feel special!

I'll take a stab at it today or tomorrow or in the coming weeks. If I actually manage to do it, I'll be sure to publish my results on github and/or let you guys know about it.

Thanks for replying!

PS: If anyone ends up reading this issue and has done it -- PLEASE WRITE HERE!

**Comment by stevenwinfield** [comment]
You might get some help from the guy who release the various
[Python for iOS](https://itunes.apple.com/us/app/python-2-7-for-ios/id485729872?mt=8) apps - a lot of the python standard libraries have bits implemented in C that he would have had to compile.
It's not exactly the same as distutils/setuptools, but I bet a lot of the issues are the same.
