### ISSUE TITLE
Documentation uses SHA1 in RSA encryption/decryption

### ISSUE THREAD

**Issue by stevenwinfield** [pyca/cryptography#4116]
The documentation for [encryption](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#encryption) and [decryption](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#decryption) with RSA shows SHA1 being used in with OAEP, even though SHA1's use is [discouraged](https://cryptography.io/en/latest/hazmat/primitives/cryptographic-hashes/?highlight=SHA1#sha-1).

[RFC 3447 Appendix B.1](https://tools.ietf.org/html/rfc3447.html#appendix-B.1) only recommends the SHA family of hashing algorithms for use with OAEP, so perhaps SHA1 should be replaced with SHA256 in the code snippets?

**Comment by reaperhulk** [comment]
SHA1's current weakness doesn't significantly compromise the security assumptions in OAEP, but we should still switch the examples to avoid confusion.

OpenSSL 1.0.1 only supports SHA1 OAEP but the usage of that is dropping rapidly and our docs jobs test on 1.0.2 or 1.1.0 so 👍

**Comment by stevenwinfield** [comment]
Great, thanks!
