### ISSUE TITLE
ImportError: hazmat/bindings/_constant_time.so: undefined symbol: PyInt_FromLong

### ISSUE THREAD

**Issue by codingjoe** [pyca/cryptography#4126]
Since I upgrade to the latest version (2.1.4) I get this error. I don't remember on which version I was before. I am currently testing old version, I'll keep yo posted.

I created the lambda function using docker and amazonlinux as well as pip:
```
pip install cryptography
```

```
File "/var/task/main.py", line 85, in get_token
bearer = jwt.encode(payload, PEM, algorithm='RS256').decode(encoding='UTF-8')
File "/var/task/jwt/api_jwt.py", line 56, in encode
json_payload, key, algorithm, headers, json_encoder
File "/var/task/jwt/api_jws.py", line 102, in encode
key = alg_obj.prepare_key(key)
File "/var/task/jwt/algorithms.py", line 205, in prepare_key
key = load_pem_private_key(key, password=None, backend=default_backend())
File "/var/task/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
from cryptography.hazmat.backends.openssl.backend import backend
File "/var/task/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
from cryptography.hazmat.backends.openssl.backend import backend
File "/var/task/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
from cryptography import utils, x509
File "/var/task/cryptography/x509/__init__.py", line 8, in <module>
from cryptography.x509.base import (
File "/var/task/cryptography/x509/base.py", line 16, in <module>
from cryptography.x509.extensions import Extension, ExtensionType
File "/var/task/cryptography/x509/extensions.py", line 18, in <module>
from cryptography.hazmat.primitives import constant_time, serialization
File "/var/task/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
from cryptography.hazmat.bindings._constant_time import lib
ImportError: /var/task/cryptography/hazmat/bindings/_constant_time.so: undefined symbol: PyInt_FromLong
```

**Comment by codingjoe** [comment]
Never mind. Seems to be a zipping issue with Travis-Ci.

**Comment by michalc** [comment]
@codingjoe I'm running into something that sounds similar on Travis-CI... if it's ok to ask, what was your issue and how did you resolve?

**Comment by codingjoe** [comment]
Hi if you use the travis-ci deploy, it does ignore hidden files (.dot-files).
One of the binaries of cffi is build into a hidden folder. Creating my own zip fixed the issue for me.

**Comment by appleEyeBall** [comment]
Still having this issue! Can you please explain what you mean by creating your own zip file?

**Comment by codingjoe** [comment]
@appleEyeBall in my example I was deploying from Travis-CI directly to AWS lambda. The Travis-CI deployment routine does not add hidden files (.dot-files) to the ZIP archive it uploads to AWS.
So I created my own ZIP archive to upload to AWS.

Anyhow, in the meantime you Travis-CI added a feature where you can change the default and include hidden files, see my example here: https://github.com/FussyFox/flake8/blob/5b118ab9f6e47c5d779d9800f0c78b2018404042/.travis.yml#L22

**Comment by Vikramsinh** [comment]
I have install pysftp library using yu**m install pysftp -t** . on AMI linux command prompt and make zip file of it and upload it to AWS lambda layer. but still I am getting

> Undefined Symbol: PyInt_FromLong

Please help

**Comment by codingjoe** [comment]
@Vikramsinh did you check if the file ends up on AWS?
