### ISSUE TITLE
problem with -param_enc explicit option of openssl

### ISSUE THREAD

**Issue by fantamiracle** [pyca/cryptography#4135]
If a pair of public key and private key is generated with -param_enc explicit:
```
openssl ecparam -name secp256k1 -genkey -param_enc explicit -out private-key2.pem
openssl ec -in private-key2.pem -pubout -out public2.pem
```
understandingly so, loading public key throws an exception as follows:
```
>>> x="-----BEGIN PUBLIC KEY-----\nMIICXDCCAc8GByqGSM49AgEwggHCAgEBME0GByqGSM49AQECQgH/////////////\n////////////////////////////////////////////////////////////////\n/////////zCBngRCAf//////////////////////////////////////////////\n///////////////////////////////////////8BEFRlT65YY4cmh+SmiGgtoVA\n7qLacluZsxXzuLSJkY7xCeFWGTlR7H6TexZSwL07sb8HNXPfiD0sNPHvRR/Ua1A/\nAAMVANCeiAApHLhTlsxnFzkyhKqg2mS6BIGFBADGhY4GtwQE6c2ePstmI5W0Qpxk\ngTkFP7Uh+CivYGtNPbqhS1537+dZKP4dwSei/6jeM0izwYVqQpv5fn4xwuW9ZgEY\nOSlqeJo7wARcil+0LH0b2Zj1RElXm0RoF6+9Fyc+ZiyX7nKZXvQmQMVQuQE/rQdh\nNTxwhqJywkCIvpR2n9FmUAJCAf//////////////////////////////////////\n////+lGGh4O/L5Zrf8wBSPcJpdA7tcm4iZxHrrtvtx6ROGQJAgEBA4GGAAQBxJvx\n43vqrPVp+nodhUPignKflS/TdPKjOjoFDz0/Gi40i+WoBd06ZyRY70W7gs8QFllY\nu4Pl3BPOJIMJODqGG/8BmS/Kxhv3Q/tZCE+lvlb7xYXyShyCFqcjoDXpCQmunJiq\n/07D8A2ifrSVmb08TG4A5ozR/64Dy+d8PVx8C3XH7sA=\n-----END PUBLIC KEY-----"
>>> ca_pu = serialization.load_pem_public_key(x.encode(), backend=default_backend())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/primitives/serialization.py", line 24, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1025, in load_pem_public_key
    return self._evp_pkey_to_public_key(evp_pkey)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 520, in _evp_pkey_to_public_key
    return _EllipticCurvePublicKey(self, ec_cdata, evp_pkey)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/ec.py", line 236, in __init__
    sn = _ec_key_curve_sn(backend, ec_key_cdata)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/ec.py", line 37, in _ec_key_curve_sn
    "ECDSA certificates with unnamed curves are unsupported "
NotImplementedError: ECDSA certificates with unnamed curves are unsupported at this time
```
I am wondering if it is something that is in the pipeline for implementation.

**Comment by pierrecdn** [comment]
Reading the source https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/ec.py#L35, it seems to me that it's related to the OpenSSL backend.

But it's weird since you (and I) used openssl itself to create the key.

**Comment by reaperhulk** [comment]
We have no plans to implement explicit parameter support at this time. What's your use case where this is needed?

**Comment by pierrecdn** [comment]
In my case, load a bunch of certificates, then distribute them to load-balancers.
I need to get their type (RSA, DSA, ECDSA) to know if they should be distributed for the same FQDN space, since you may want to add multiple certs for one service, so that outdated clients can be served using RSA.

**Comment by reaperhulk** [comment]
Why does that require explicit parameter encoding? Public key type is unambiguous without explicit param encoding. Explicit param encoding for EC is generally used to allow creation of custom curves, but that's not a widely used feature. In fact, named curves are the only thing supported by effectively all TLS implementations.

**Comment by pierrecdn** [comment]
I'm not 100% sure about what we're talking here, I'm also a bit noob on this library and don't want to interfere too much with the original issue, so I'll try to sum-up. Feel free to ask for another ticket if needed.

If I create a X509 cert based on ECs, like that:
```
$ openssl version
OpenSSL 1.1.0g  2 Nov 2017
$ openssl ecparam -name prime256v1 -genkey -param_enc explicit -out private-key.pem
$ openssl req -new -x509 -key private-key.pem -out cert.pem -days 730
```
I then try to load it using cryptography: 
```
!/usr/bin/python3

from cryptography import x509
from cryptography.hazmat.backends import default_backend

import sys 

cert_file = open(sys.argv[1],"r")
certificate = cert_file.read()
x509_cert = x509.load_pem_x509_certificate(certificate.encode(), default_backend())
try:
  print(x509_cert.public_key())
except RuntimeError as e:
  print(e)
```
I get:
```
$ ./key_type.py cert.pem 
ECDSA certificates with unnamed curves are unsupported at this time
```
It's OK with RSA.

Does it sounds normal?

**Comment by reaperhulk** [comment]
That's all correct, but there is no need to use `-param_enc` in your EC command. By default OpenSSL will use the named curve form, which is fully supported by this project (and everywhere else).

**Comment by pierrecdn** [comment]
Nice, works for me, many thanks, I didn't understand well this parameter.

**Comment by reaperhulk** [comment]
Closing as it appears the existing feature set is sufficient for the use cases presented (explicit parameter encoding being unnecessary for any named curve)
