### ISSUE TITLE
[Feature Request] Add key size constants for symmetric ciphers.

### ISSUE THREAD

**Issue by tuxxy** [pyca/cryptography#4137]
Similar to PyNaCl, there is a `KEY_SIZE` constant. This is accessed via `SecretBox.KEY_SIZE`.

Currently, we provide key generation methods like https://cryptography.io/en/latest/hazmat/primitives/aead/#cryptography.hazmat.primitives.ciphers.aead.ChaCha20Poly1305.generate_key.

It would be nice to declare a constant such as `KEY_SIZE` within this `ChaCha20Poly1305` class and all similar classes. This could also probably extend to `NONCE_SIZE` in some cases.

In other examples, there is no defined size or `generate_key` method and it is up to the user to generate the proper amount of bytes via a secure random source.

**Comment by reaperhulk** [comment]
This is an easy thing to add to the `ChaCha20Poly1305` class, but is a bit trickier for any construction allowing multiple key sizes. We could counter that by having `key_size` be the union of int and frozenset, but that's pretty ugly...

**Comment by tuxxy** [comment]
Yeah, that sounds pretty bad.

Could it be possible to use a dict instead? For example in `cryptography.hazmat.primitives.ciphers.algorithms.AES` have a dict `key_size` that is:

```
key_size = {
    'AES256': 32,
    'AES192': 24,
    'AES128': 16,
}
```

**Comment by reaperhulk** [comment]
A dict approach like that would technically work, but then requires users to introspect the `key_size` attribute to learn what the dictionary keys are in addition to determining if it is a dict or an int. I think the nature of the cryptography APIs (and the underlying ciphers it supports) is such that `key_size` isn't a practical abstract property. It is a nice idea but I think we can't implement this in a useful fashion and therefore this should be closed. Thoughts @alex?

**Comment by alex** [comment]
I concur.
