### ISSUE TITLE
ECB mode broken?

### ISSUE THREAD

**Issue by bluemagic5** [pyca/cryptography#4138]
Hi I tried the following code and it's giving me a TypeError: _check_aes_key_length() missing 1 required positional argument: 'algorithm' 
I know ECB is not secure but I wanted to try it out and it would seem that in modes.py, line 128 might be an issue?
#encrypts the paddedtext with AES-ECB-256 standard
    backend = default_backend()
    cipher = Cipher(algorithms.AES(key), modes.ECB, backend=backend)
    encryptor = cipher.encryptor()
    ciphertext = encryptor.update(paddedtext.encode(encoding='UTF-8')) + encryptor.finalize()

**Comment by reaperhulk** [comment]
This is an unfortunate error msg because the real problem is that you need an *instance* of `ECB` and not the class itself (e.g. `modes.ECB()` and not `modes.ECB`). We can improve this error msg by validating that `mode` is an instance of `modes.Mode` in the `Cipher` constructor.

**Comment by alex** [comment]
I want to emphasize that in nearly all contexts, `ECB` is horribly insecure, and if you are developing a design that relies on it, I strongly encourage you to reconsider.

**Comment by reaperhulk** [comment]
As added color: we primarily expose ECB to allow implementors to create new modes on top of the raw AES primitive. It is almost entirely useless outside of this use case. If you're looking to encrypt data most of the time `Fernet` is the right answer.

**Comment by bluemagic5** [comment]
Ah sorry I'm new to python and that threw me off. I was basing it off the documentation on CBC mode. Thanks! I'm just doing this for a class and I know ECB is horribly insecure.
