### ISSUE TITLE
make Certificate JSON Serializable

### ISSUE THREAD

**Issue by jcrowgey** [pyca/cryptography#4142]
I'm using this project to load certificates which I then serialize as JSON.

Would this project be interested in a PR with a toJSON method for the Certificate class?

**Comment by alex** [comment]
There is no standard JSON serialization for X.509 certificates, and we're not interested in creating our own standard, so this isn't something we'd want to expose.

**Comment by jcrowgey** [comment]
I understand.  Thank you.

**Comment by jcrowgey** [comment]
FWIW: there is this: https://www.itu.int/itu-t/workprog/wp_item.aspx?isn=13581

JER: a standard for JSON Encoding Rules for ASN1 structures.

**Comment by jcrowgey** [comment]
And now there is this, too: https://github.com/jcrowgey/x5092json
