### ISSUE TITLE
Generate asymmetric key from modulus and exponent

### ISSUE THREAD

**Issue by darwinyip** [pyca/cryptography#4153]
Is it possible to generate the asymmetric key (e.g. RSA) by supplying my own exponent and modulus?

**Comment by alex** [comment]
Currently the only API for generating RSA keys takes a `key_size` and `public_exponent`

**Comment by reaperhulk** [comment]
This is really asking to derive `d` (the private exponent) given `e` (public exponent) and `n` (modulus). If that was possible it would mean you could derive the private key given any public key, breaking RSA completely.
