### ISSUE TITLE
Issue 2.2.2 release for OpenSSL 1.1.0h

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4170]
https://www.openssl.org/news/secadv/20180327.txt

**Comment by alex** [comment]
- [ ] homebrew openssl update (https://github.com/Homebrew/homebrew-core/pull/25837)
- [ ] update windows wheel builder's openssl
- [ ] update manylinux1 wheel builder
- [ ] changelog on 2.2.x branch
- [ ]  release
- [ ] forward port changelog

**Comment by reaperhulk** [comment]
Windows 1.1.0h builds are complete and deployed to the builders.
