### ISSUE TITLE
Segfault installing via pip3 on Raspberry Pi 3B

### ISSUE THREAD

**Issue by doug-e7systems** [pyca/cryptography#4176]
Hi:

The following produces a segfault 100% of the time I try it. I tried this on 2 different Raspberry Pi 3B computers at least 6 times.

This is simplified from a larger install.
To reproduce, get the latest Raspbian image (2018-03-13-raspbian-stretch.zip) and boot the Pi with it.

Then ssh into the box and run

```
pi@raspberrypi:~ $ pip3 install cryptography
pi@raspberrypi:~ $ pip3 install paramiko
Segmentation fault

```
The log below is from running
`pip3 -vvv install cryptography > cryptography_log.txt`

[cryptography_log.txt](https://github.com/pyca/cryptography/files/1858608/cryptography_log.txt)

I am not sure if this is paramiko, cryptography or the Raspberry Pi. Any pointers would be greatly appreciated.

Thanks!

**Comment by reaperhulk** [comment]
The log provided doesn't really show any useful information, but if you don't have swap enabled please do that and see if it successfully installs. `cryptography` unfortunately requires a lot of memory to compile.

**Comment by doug-e7systems** [comment]
Hi:
I created a 4GB swap file and tried again.  No change.  The steps below work fine on Debian Jessie.  I started getting this failure when I switched to Debian Stretch.

If you have any ideas how I might track this down, please let me know.

Full output below.

```
pi@raspberrypi:~ $ pip3 install cryptography
Collecting cryptography
  Downloading https://www.piwheels.org/simple/cryptography/cryptography-2.2.2-cp35-cp35m-linux_armv7l.whl (888kB)
    100% |████████████████████████████████| 890kB 268kB/s 
Collecting six>=1.4.1 (from cryptography)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 2.0MB/s 
Collecting asn1crypto>=0.21.0 (from cryptography)
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 1.4MB/s 
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography)
  Downloading https://www.piwheels.org/simple/cffi/cffi-1.11.5-cp35-cp35m-linux_armv7l.whl (304kB)
    100% |████████████████████████████████| 307kB 389kB/s 
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography)
  Downloading https://www.piwheels.org/simple/pycparser/pycparser-2.18-py2.py3-none-any.whl (209kB)
    100% |████████████████████████████████| 215kB 404kB/s 
Installing collected packages: six, idna, asn1crypto, pycparser, cffi, cryptography
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.2.2 idna-2.6 pycparser-2.18 six-1.11.0
pi@raspberrypi:~ $ pip3 install paramiko
Collecting paramiko
  Downloading paramiko-2.4.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 1.1MB/s 
Collecting pyasn1>=0.1.7 (from paramiko)
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.7MB/s 
Collecting cryptography>=1.5 (from paramiko)
  Using cached https://www.piwheels.org/simple/cryptography/cryptography-2.2.2-cp35-cp35m-linux_armv7l.whl
Collecting bcrypt>=3.1.3 (from paramiko)
  Downloading https://www.piwheels.org/simple/bcrypt/bcrypt-3.1.4-cp35-cp35m-linux_armv7l.whl (52kB)
    100% |████████████████████████████████| 61kB 124kB/s 
Collecting pynacl>=1.0.1 (from paramiko)
  Downloading https://www.piwheels.org/simple/pynacl/PyNaCl-1.2.1-cp35-cp35m-linux_armv7l.whl (422kB)
    100% |████████████████████████████████| 430kB 128kB/s 
Collecting idna>=2.1 (from cryptography>=1.5->paramiko)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko)
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.5->paramiko)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.5->paramiko)
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.11.5-cp35-cp35m-linux_armv7l.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.5->paramiko)
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.18-py2.py3-none-any.whl
Installing collected packages: pyasn1, idna, asn1crypto, six, pycparser, cffi, cryptography, bcrypt, pynacl, paramiko
Successfully installed asn1crypto-0.24.0 bcrypt-3.1.4 cffi-1.11.5 cryptography-2.2.2 idna-2.6 paramiko-2.4.1 pyasn1-0.4.2 pycparser-2.18 pynacl-1.2.1 six-1.11.0
Segmentation fault

```

**Comment by alex** [comment]
Can you either run directly under GDB or configure your machine to dump a core file and let us know where it's crashing?

**Comment by doug-e7systems** [comment]
Thanks for the reply, I will give GDB a try and let you know what I come up with.

Thanks again.

**Comment by doug-e7systems** [comment]
A quick progress update.  I got the Pi to dump a core file, I am trying to get the python debug symbols to load so I can figure out more...

This is a weird bug, it does not occur on x86, only on ARM.  Pip actually generates a valid whl, which I can use for installs just fine.  But if I let pip try and generate the whl, that's when I get the segfault.

Really weird.  Anyhow, I'll let you know how I get on.

**Comment by geofft** [comment]
Can you post the backtrace from the core dump even if you don't have symbols? There might be enough details to make some educated guesses.

**Comment by karlg100** [comment]
looks like the busted package is cffi

{code}
pip install --no-cache-dir cffi
Collecting cffi
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
    100% |████████████████████████████████| 440kB 5.3MB/s 
Collecting pycparser (from cffi)
  Downloading https://www.piwheels.org/simple/pycparser/pycparser-2.18-py2.py3-none-any.whl (209kB)
    100% |████████████████████████████████| 215kB 1.1MB/s 
Installing collected packages: pycparser, cffi
  Running setup.py install for cffi ... done
Successfully installed cffi-1.11.5 pycparser-2.18
{code}

**Comment by reaperhulk** [comment]
Since this appears to not be cryptography, I'll go ahead and close.

**Comment by nigels-com** [comment]
cffi-1.12.1 seems to pip install OK.

It's pyOpenSSL that seems to be the problem for me.

```
$ uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

$ pip install --no-cache-dir cffi
Collecting cffi
  Downloading https://files.pythonhosted.org/packages/bc/81/47bd0404f2cb5363edb371e3b15da6387b5e9b80122e5b81be8b8f411e9b/cffi-1.12.1.tar.gz (453kB)
    100% |████████████████████████████████| 460kB 6.6MB/s 
Collecting pycparser (from cffi)
  Downloading https://www.piwheels.org/simple/pycparser/pycparser-2.19-py2.py3-none-any.whl (111kB)
    100% |████████████████████████████████| 112kB 160kB/s 
Installing collected packages: pycparser, cffi
  Running setup.py install for cffi ... done
Successfully installed cffi-1.12.1 pycparser-2.19
```

**Comment by geofft** [comment]
@nigels-com What version of pip are you using? We believe this bug might be pypa/pip#5405, fixed in pip v18 and up. Can you `pip install -U pip` first?

**Comment by nigels-com** [comment]
Hey thanks!  It works now.

```
$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
$ pip install -U pip
...
$ ~/.local/bin/pip -V
pip 19.0.3 from /home/pi/.local/lib/python2.7/site-packages/pip (python 2.7)
```
