### ISSUE TITLE
OpenSSL 1.1.1 Features/Tasks

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#4197]
This is a meta bug to track the various things we should do once 1.1.1 is released.

- [x] Add a 1.1.1 builder to CI (#4112)
- [x] ed25519 signing (#3509) (#4114)
- [x] SHA3 digests (#4573)
- [x] SHAKE (#4611)
- [x] SHA512-224, SHA512-256 (#4575)
- [x] X448 kex (#4136)
- [x] ed448 (#4610)
- [x] Add binding for SSL_CTX_set_ciphersuites (#4255)

The last published OpenSSL release schedule (https://www.openssl.org/policies/releasestrat.html) targets a release around May 15, 2018 so we're around a month away from final.

I'm tentatively 👍 on shipping a wheel with 1.1.1 as soon as we have some features that can use it, but if others feel strongly about waiting a bit to see if there are bug fix releases we can discuss it.

**Comment by maqp** [comment]
OpenSSL 1.1.1 has finally been [released](https://www.openssl.org/blog/blog/2018/09/11/release111/).

**Comment by reaperhulk** [comment]
This was finished with 2.6
