### ISSUE TITLE
ImportError: cryptography/hazmat/bindings/_constant_time.abi3.so: undefined symbol: PyObject_CallMethod

### ISSUE THREAD

**Issue by seanlittle** [pyca/cryptography#4262]
Hello,

I need some wisdom trying to fix a problem that I have spent quite a lot of time trying to fix myself. I am following the tutorial here: https://docs.python.org/3/extending/embedding.html#very-high-level-embedding. I am embedding the python3 interpreter in another application. I have everything I need working from the other application until I attempt to import a library (scapy-python3) which is using the cryptography library. Here is the specific python import statement that causes the problem:

from cryptography.hazmat.bindings._constant_time import lib

And here is the error message:
ImportError: /usr/local/lib/python3.6/site-packages/cryptography/hazmat/bindings/_constant_time.abi3.so: undefined symbol: PyObject_CallMethod
Error: Call to interact failed

Here is the version of the software that I am running:
python: 3.6.5
pip: 10.0.1
setuptools: 39.2.0
cffi: 1.11.5
cryptography: 2.2.2
openssl: 1.0.2k-fips

Other information: I am pretty sure that this is a problem specific to my environment, since I am able run my embedded application on another system. I am running CentOS 7. I would really appreciate some hints for debugging this. I see that PyObject_CallMethod is not defined in that shared object. Is there some other object that must be loaded first? I can confirm that PyObject_CallMethod is defined in my libpython3.6m.so.1.0. What else can I do?

Thanks in advance.

**Comment by alex** [comment]
`PyObject_CallMethod` is provided by libpython, so for whatever reason your dynamic linker isn't resolving symbols in `_constant_time.abi3.so` in `libpython3.6m.so.1.0`. I'm afraid I don't have a suggestion for why this is, your best bet is probably to set the environment variables for the dynamic linker to print out debug info and see where that leads you.

**Comment by palmkevin** [comment]
Hi @seanlittle, did you succeed in finding a solution for this problem? I do have the same problem...

**Comment by palmkevin** [comment]
Hi folks, I found the solution for my problem. It could be that it solves yours too.
Please have a look at the [cffi documentation](https://cffi.readthedocs.io/en/latest/embedding.html). They mention this:

> On some Linux distributions, notably Debian, the .so files of CPython C extension modules may be compiled without saying that they depend on libpythonX.Y.so. This makes such Python systems unsuitable for embedding if the embedder uses dlopen(..., RTLD_LOCAL). You get the error undefined symbol: PyExc_SystemError. See issue # 264.

In the [referenced issue #264](https://bitbucket.org/cffi/cffi/issues/264/), there is a workaround described by "Guillaume Valadon". This workaround worked for me!
