### ISSUE TITLE
All zero fernet token

### ISSUE THREAD

**Issue by nachonavarro** [pyca/cryptography#4265]
Hi,

Is there a way to find out which message must be encrypted to give the all zero bytes (for a pre-specified number of bytes) token?

In other words, finding out what X is in:
```python
from cryptography.fernet import Fernet
key = Fernet.generate_key()
f = Fernet(key)
token = f.encrypt(X)
token == b'AAAAAAAAAAAAAAAA=='
# prints True
```

PS: For those who are interested, I'm trying to get the formula on the Row Reduction section
on Garbled Circuits (see [https://en.wikipedia.org/wiki/Garbled_circuit#Row_reduction](https://en.wikipedia.org/wiki/Garbled_circuit#Row_reduction))

Thanks!

**Comment by alex** [comment]
No, Fernet tokens utilize a random IV and use HMAC to authenticate both ciphertext and the IV, thus there is no way to know a priori that a given input will produce a particular output -- as is required for IND-CPA.
