### ISSUE TITLE
PyPy3 - Import error from openssl, undefined symbol: d2i_DHxparams

### ISSUE THREAD

**Issue by hydratk** [pyca/cryptography#4274]
When importing in PyPy3 from _openssl, error is raised undefined symbol: d2i_DHxparams.
This error does not occur in PyPy2 or CPython.

Can you give some advice how to correct it?
Thank you

**versions**:
cryptography 2.2.2
pip 9.0.1
Python 3.5.3 PyPy 5.10.1 with GCC 7.2.0
libffi-dev 3.1~rc1+r3.0.13-12ubuntu0.2
libssl-dev 1.0.1f-1ubuntu2.25
openssl 1.0.1f-1ubuntu2.25

**error** (cryptography functions called within paramiko):
ERROR:paramiko.transport:Unknown exception: /root/.pyenv/versions/pp3/site-packages/cryptography/hazmat/bindings/_openssl.pypy3-510-x86_64-linux-gnu.so: undefined symbol: d2i_DHxparams
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/paramiko/transport.py", line 1933, in run
ERROR:paramiko.transport:    self._handler_table[ptype](self, m)
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/paramiko/transport.py", line 2032, in _negotiate_keys
ERROR:paramiko.transport:    self.kex_engine.start_kex()
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/paramiko/kex_ecdh_nist.py", line 32, in start_kex
ERROR:paramiko.transport:    self._generate_key_pair()
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/paramiko/kex_ecdh_nist.py", line 53, in _generate_key_pair
ERROR:paramiko.transport:    self.P = ec.generate_private_key(self.curve, default_backend())
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
ERROR:paramiko.transport:    from cryptography.hazmat.backends.openssl.backend import backend
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
ERROR:paramiko.transport:    from cryptography.hazmat.backends.openssl.backend import backend
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 53, in <module>
ERROR:paramiko.transport:    from cryptography.hazmat.bindings.openssl import binding
ERROR:paramiko.transport:  File "/root/.pyenv/versions/pp3/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
ERROR:paramiko.transport:    **from cryptography.hazmat.bindings._openssl import ffi, lib**
ERROR:paramiko.transport:ImportError: /root/.pyenv/versions/pp3/site-packages/cryptography/hazmat/bindings/_openssl.pypy3-510-x86_64-linux-gnu.so: **undefined symbol: d2i_DHxparams**

**Comment by alex** [comment]
Apologies for our slow response. This error would happen if you'd compiled cryptography against one version of OpenSSL (> 1.1.0) but linked it against an older version.

**Comment by tcanabarro** [comment]
For future reference, we were also dealing with this **`undefined symbol: d2i_DHxparams`** issue. [We followed these instructions](https://github.com/mattsb42/codebuild-python-cryptography-custom-openssl) to download the OpenSSL source, build it in a separate directory, and the build the `cryptography` lib pointing to the custom OpenSSL.

I'm replicating [the script](https://github.com/mattsb42/codebuild-python-cryptography-custom-openssl/blob/master/build_cryptography_custom_openssl.sh) below just in case the original repo is gone:

```shell
#!/bin/bash
set -e
CWD=$(pwd)
virtualenv env -p python$PYTHON_VERSION
. env/bin/activate
pip install -U setuptools
pip install -U wheel pip
curl -O https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
tar xvf openssl-${OPENSSL_VERSION}.tar.gz
cd openssl-${OPENSSL_VERSION}
./config no-shared no-ssl2 -fPIC --prefix=${CWD}/openssl
make && make install
cd ..
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-use-wheel cryptography
```

Actually at the end we used **`pip install cryptography --no-binary cryptography`** instead of the `pip wheel` version.
