### ISSUE TITLE
Error while setting up developer environment: ImportError: The 'enchant' C library was not found

### ISSUE THREAD

**Issue by abhn** [pyca/cryptography#4279]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
  - cffi version: 1.11.5
  - pip version: 10.0.1
  - setuptools version: 39.2.0
  - python: 3.6.5
  - cryptography: latest master branch

* How you installed ``cryptography``
  - cloned the repository
  - followed the build instructions listed here: https://cryptography.io/en/latest/installation/
  - followed the developer dependency setup listed here: https://cryptography.io/en/latest/development/getting-started/#development-dependencies

* Clear steps for reproducing your bug
  - on running `pip install --requirement dev-requirements.txt`, I get the error `ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.` for the pyenchant package
  - I can confirm I have enchant installed as can be seen in the screenshots.

Please request any additional information that might be useful in solving this issue. The system is running Arch on Linux 4.16.13

![screenshot from 2018-06-12 20-08-14](https://user-images.githubusercontent.com/6270406/41299046-33adf3e8-6e80-11e8-99ab-a9ac4ac3e14c.png)
![screenshot from 2018-06-12 20-08-45](https://user-images.githubusercontent.com/6270406/41299047-33ef2822-6e80-11e8-8267-75b78678db11.png)

Can anyone guide me to fix this? Thanks in advance.

**Comment by reaperhulk** [comment]
If you have `enchant` installed via your arch package manager (as it looks like you do) then you'll want to debug this with pyenchant.

**Comment by abhn** [comment]
Okay, I'll check with that.

**Comment by abhn** [comment]
For any fellow contributor who finds this issue, I fixed it by cloning the pychant repo (https://github.com/rfk/pyenchant), making this change: https://github.com/rfk/pyenchant/pull/128/commits/da45fcfbdda5a79e6c1cc3b41d8ec9f2fadc297a and then `pip setup.py install` from the directory. 

Pyenchant is unmaintained now, and hence this wasn't fixed. 

We can close this issue. Thanks.
