### ISSUE TITLE
how to deal with signature_algorithm?

### ISSUE THREAD

**Issue by wjmwjmwb** [pyca/cryptography#4282]
EllipticCurvePrivateKey.sign(self, data, signature_algorithm):

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.sign

and an example

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.ECDSA
