### ISSUE TITLE
Custom ECDSA tests failing on PyPy only...

### ISSUE THREAD

**Issue by gpotter2** [pyca/cryptography#4283]
[This question is invalid, and has been edited]

**Summary:** we had some failing ECDSA tests only on PyPy
**Answer:** the use of the deprecated `publickey.signer` does not work on PyPy. This use was not expected, and this failure made us aware that our code was wrongly using this deprecated function, instead of the up-to-data `sign`
**Fix:** force code to use the new function when running on PyPy

**Comment by alex** [comment]
What is the failure I should be seeing in the log? Is it the `AssertionError`?

**Comment by gpotter2** [comment]
That’s the part where I’m confused :/ in our test we then have `assert [result from verify]` so the only error I have to provide isn’t really one... I don’t really have any clue of the failure :(

**Comment by gpotter2** [comment]
Will add some additional infos... please wait

**Comment by gpotter2** [comment]
Sorry for bothering, after some testing, it appears that the old `signer` function simply does not work on PyPy

**Comment by reaperhulk** [comment]
This should definitely still work on pypy3. We run all our tests on both pypy3 and pypy in CI.

**Comment by gpotter2** [comment]
It does so locally, but using Travis (OpenSSL 1.0.1f) on a Linux build, it worked with RSA but not ECDSA
