### ISSUE TITLE
[Feature request] expose BIGNUM prime methods

### ISSUE THREAD

**Issue by qstokkink** [pyca/cryptography#4287]
For our research (@Tribler) we use OpenSSL's `BN_generate_prime_ex` and `BN_is_prime_ex` through custom bindings. Is this something you would want to support in your bindings (hazmat backend)?

If you're interested, I can turn https://github.com/qstokkink/cryptography/commit/31d2bc21e60c6842be2927aa576834b3cf2bf6a4 into a polished PR.

**Comment by reaperhulk** [comment]
These are stable functions that exist in all our supported versions (as well as boringssl, a target we would like to support). I'm not opposed to adding them to our bindings. However, some caveats:

* I'm not convinced we want to add any methods to the Python layer that use these.
* If we're not a direct consumer of these functions then when we do cleanup PRs we have to use our git history/fallible human memories to figure out why they were bound. This is a bit of a pain and means we can't 100% guarantee we won't remove them in the future (although we haven't done that to a consumer yet)

**Comment by qstokkink** [comment]
Thanks for the response, I'll just PR the C bindings then without the Python layer.
I'll also add some inline comments to the bindings that link to our project (or this issue).
