### ISSUE TITLE
Is this bug?

### ISSUE THREAD

**Issue by MohamedKaizen** [pyca/cryptography#4295]
When i try to use Authenticated encryption in AESGCM mode this what happens:
![screenshot 5](https://user-images.githubusercontent.com/35686076/41835297-bf55e412-785f-11e8-8dc8-5019bda7fb12.png)
When I try to encrypt  the encrypted message  it's show me the original message. is this how AESGCM  work??

**Comment by alex** [comment]
No, AES-GCM is a XOR-based cipher, so this is expected.

It's important to note that doing this requires reusing the same `nonce`, which our docs specifically say is catastrophic: https://cryptography.io/en/latest/hazmat/primitives/aead/#cryptography.hazmat.primitives.ciphers.aead.AESGCM.encrypt
