### ISSUE TITLE
Unable to verify RSA signature on server side (RSA/sha256/PSS)

### ISSUE THREAD

**Issue by morkyy** [pyca/cryptography#4296]
I signed a message on the client using the [forge library](https://github.com/digitalbazaar/forge#rsa) and when going over to server side I'm failing to verify that signature and  get `InvalidSignature`.

```js
//Client Side
var md = forge.md.sha256.create();
            md.update(encryptedVote, 'utf8');
            var pss = forge.pss.create({
            md: forge.md.sha256.create(),
            mgf: forge.mgf.mgf1.create(forge.md.sha256.create()),
            saltLength: 20
            });
            var signature = privateKey.sign(md, pss);
```
```python
#server side
user_public_key_loaded.verify(
            signature,
            enc_encrypted_vote,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=20
            ),
            hashes.SHA256()
        )
```
I have set all hashing algorithms to SHA256 and I'm using the same length salt. The signature verification function takes the correct inputs.

**Comment by VMois** [comment]
Please, specify version of python, cryptography and also include example of way how you get an encryptedVote and enc_encrypted_vote.

**Comment by VMois** [comment]
This code works for me:
node 8.11
```js
const forge = require('node-forge');
const fs = require('fs');
const rsa = forge.pki.rsa;
const pki = forge.pki;

const keypair = rsa.generateKeyPair({bits: 2048, e: 0x10001});
const privateKey = keypair.privateKey;
const publicKey = keypair.publicKey;

const pemPublic = pki.publicKeyToPem(publicKey);
fs.writeFileSync('./pub_key', pemPublic);

const md = forge.md.sha256.create();
md.update('sign this');
var pss = forge.pss.create({
  md: forge.md.sha256.create(),
  mgf: forge.mgf.mgf1.create(forge.md.sha256.create()),
  saltLength: 32
});
const signature = privateKey.sign(md, pss);
const bufferSig = Buffer.from(signature, 'ascii');
fs.writeFileSync('./signature', bufferSig);
```

python 3.4.2
```python
from cryptography.hazmat.primitives.serialization import load_pem_public_key
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding

with open('pub_key', 'rb') as myfile:
	public_pem_data = myfile.read()

with open('signature', 'rb') as sig:
	signature = sig.read()

chosen_hash = hashes.SHA256()
key = load_pem_public_key(public_pem_data, backend=default_backend())

data = b"sign this"
key.verify(
	signature,
    data,
    padding.PSS(
        mgf=padding.MGF1(hashes.SHA256()),
        salt_length=32
    ),
	hashes.SHA256()
)
```

It's not a browser, but I think you have a problem with encoding/decoding somewhere. Maybe something during sending and receiving. If you specify more info, it will be easier to help.

**Comment by morkyy** [comment]
I was suspecting the same. I'm using python 3.5.2 and cryptography version 2.2.2.
I'm creating the RSA keypair using cryptography and store it encrypted on the database. I serialize the private key to JSON send it to the client and on the client I decrypt the private key. Up to the decryption of the private key I can verify that everything works as expected I've done testing that shows that decrypted private key on the client is the same as the one created on the server.

After wards what I'm doing on the client is this.

```
var md = forge.md.sha256.create();
            md.update(encryptedVote, 'latin-1');
            var pss = forge.pss.create({
            md: forge.md.sha256.create(),
            mgf: forge.mgf.mgf1.create(forge.md.sha256.create()),
            saltLength: 20
            });
            var signature = privateKey.sign(md, pss);

            var base64Signature = forge.util.encode64(signature);
            var base64EncryptedVote = forge.util.encode64(encryptedVote);

            var voteAndSignatureObject = {base64EncryptedVote, base64Signature};
            var voteAndSignature = JSON.stringify(voteAndSignatureObject);
```

```
And I send `voteAndSignature` back to the server.

On the server.

encrypted_vote = request.POST['vote_and_signature']
encrypted_vote_obj = json.loads(encrypted_vote)
vote_list = list(encrypted_vote_obj.values())
b64_encrypted_vote = vote_list[0]
b64_signature = vote_list[1]
encrypted_vote = base64.b64decode(b64_encrypted_vote)
signature = base64.b64decode(b64_signature)

user_public_key = Profile.objects.get(id=request.user.id).public_key
user_public_key_loaded = load_pem_public_key(user_public_key, backend=default_backend())

try:

    user_public_key_loaded.verify(
        signature,
        encrypted_vote,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=20
        ),
        hashes.SHA256()
     )
except Exception:
     # Redisplay the question voting form.
     return render(request, 'voting/detail.html', {
         'question': question,
         'error_message': "We couldn't verify your vote.",
     })
```


I'm following a similar procedure in another part of my code and I face the same issues. Sometimes the signature is verified while some others it's not. If I change the encoding on the client in this line             `md.update(encryptedVote, 'latin-1');` the signature is never verified.

I noticed that in your example in this line `md.update(encryptedVote, 'latin-1');` you ommit the encoding part. Is there a reason for doing that?

**Comment by VMois** [comment]
I have found that whatever you use `latin-1` or `utf-8` or nothing in md.update() verify doesn't throw InvalidSignature error.

**Comment by VMois** [comment]
Your problem is in python.
```python
encrypted_vote_obj = json.loads(encrypted_vote)
vote_list = list(encrypted_vote_obj.values())
b64_encrypted_vote = vote_list[0]
b64_signature = vote_list[1]
```
Sometimes vote_list could change position of signature with encrypted_vote. One time it's in 0, second in 1, and so on.
@morkyy

**Comment by morkyy** [comment]
@VMois I just realized the same a couple of minutes ago. I know it's completely out of the scope of the issue but is here any chance you could suggest a different way of doing this? I would really appreciate it!

**Comment by VMois** [comment]
No problems. I feel completely stupid that I didb't realized it earlier)
This code should work:
```python
encrypted_vote_obj = json.loads(json_string)
data = base64.b64decode(encrypted_vote_obj['vote']) # use key from your json
signature = base64.b64decode(encrypted_vote_obj['signature'])
```

**Comment by VMois** [comment]
`values()` in python could transform dict in a different way each time, so values are not always in the same positions. I'm glad that code works. If you haven't any questions, please close the issue.

**Comment by reaperhulk** [comment]
Thanks for helping out here, glad it’s resolved!
