### ISSUE TITLE
dynamodb-encryption tests failing

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4297]
https://travis-ci.org/pyca/cryptography/jobs/397017357

@mattsb42-aws can you take a look at this?

If they're not resolved soonish we'll need to disable.

**Comment by mattsb42-aws** [comment]
Taking a look. This is interesting; I've just been noticing that some of our other projects that use Hypothesis are also failing with the same error...

**Comment by mattsb42-aws** [comment]
Looks like something in Hypothesis 3.64.0 is breaking things. Investigating...

**Comment by mattsb42-aws** [comment]
https://github.com/awslabs/aws-dynamodb-encryption-python/pull/77 << should be merged no later than tomorrow morning (PST)

**Comment by reaperhulk** [comment]
Thanks Matt!

**Comment by mattsb42-aws** [comment]
This is merged now. You all should be unblocked.

**Comment by alex** [comment]
Confirmed. Thanks.
