### ISSUE TITLE
Don't initialize locks in OpenSSL 1.1.0+

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4315]
https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/bindings/openssl/binding.py#L143

We currently check if `CRYPTO_get_locking_callback()` is `NULL` to know if we need to set up our own locks. However, on OpenSSL 1.1.0, it's _always_ `NULL`, because the system provides it's own locking callback.

We can save some memory and speed up initialization a smidge by skipping this logic if we're on a version of OpenSSL that provide it's own locking.

**Comment by alex** [comment]
For anyone interested in working on this, my recommendation would be to make compilation of the locking callbacks in `callbacks.py` conditional on being `CRYPTOGRAPHY_OPENSSL_LESS_THAN_110`, and then check the appropriate flag in `binding.py`.

**Comment by tuxxy** [comment]
I noticed that there is already a var `Cryptography_HAS_LOCKING_CALLBACKS`. Looks like it was done about two years ago. Are you wanting this removed in favor of using `CRYPTOGRAPHY_OPENSSL_LESS_THAN_110` instead?
