### ISSUE TITLE
Encryption an Folder

### ISSUE THREAD

**Issue by StefanMeier12** [pyca/cryptography#4317]
Hi, I'm just learning python.
Encryption with Python is very interesting. I would like to encrypt and decrypt the EBeispielordner1 folder. It would also be interesting to have several
Can encrypt folders in a single slide, e.g.

E/Beispielordner1

E/Beispielordner2

E/Beispielordner3

I would like to start this program from the console without GUI.

Of course there are many encryption programs, but it would be interesting to be able to use a Python encryption program without backdoor.

**Comment by alex** [comment]
pyca/cryptography provides access to various encryption algorithms. Composing them into an application is the responsibility of the user. We're not able to provide introductory Python support here, only support for our library.
