### ISSUE TITLE
Deprecate *Numbers Classes

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#4320]
They were originally put in place to give us a least common denominator serialization/deserialization, but we haven't derived much from having them and we've seen several disadvantages (#4235). Let's figure out how to deprecate and remove them.

# RSA

Our primary use of the numbers classes is to assemble a key from NIST test vectors that provide hex-encoded integers and loading ssh public keys.

# EllipticCurve

We have `from_encoded_point` on `EllipticCurvePublicNumbers`, which we should move to a function. We additionally use the numbers classes to deserialize NIST test vectors.

# DSA

Surprising no one, we use them for deserializing test vectors and as an intermediate stage when loading ssh public keys.

# DH

...deserializing test vectors.

We almost certainly have some users who use these classes externally to load things, but deprecating them should shake those use cases out so we can determine what to do.

**Comment by ronf** [comment]
In AsyncSSH, I currently rely on the *Numbers classes for both constructing keys and for accessing the raw public and private values (and params in the DSA case), as I have my own serialization and deserialization functions. Part of that is historical since Cryptography didn't know how to serialize keys in SSH format when I first wrote the code, but even now I think there are still some formats that I support which haven't made it into Cryptography yet, including support for RFC 4716 SSH public keys, Ed25519 keys, and  "new" OpenSSH format private keys. I also expect I'll soon be looking to support Ed448 keys.

Included in the above is the ability to support encrypted OpenSSH private keys, which introduces a dependency on bcrypt. I don't know if this is something Cryptography would want to take on (though it does already have support for OpenSSH format public keys), but I'll definitely need some way to construct keys from and access  raw public & private numbers if I have to implement this serialization myself.

For EC keys, I also need support for encode_point() and from_encoded_point(), though I'd be fine if those were provided as standalone functions.

**Comment by reaperhulk** [comment]
Thanks for weighing in @ronf, your project likely represents a good example of what we need to be able to support to effectively deprecate these classes.

**Comment by dainnilsson** [comment]
We use the *Numbers classes in several of our libraries when interfacing with systems where standardized serialization isn't used (coming from or going to devices with limited processing power typically).

Some examples of this include:

Converting between Cryptography and COSE formatted keys:
https://github.com/Yubico/python-fido2/blob/master/fido2/cose.py

Converting between key formats to/from a FIDO 2 authenticator:
https://github.com/Yubico/python-fido2/blob/master/fido2/ctap2.py#L745

The *Number classes are also of use when interfacing with the YubiHSM 2:
https://developers.yubico.com/YubiHSM2/
Importing private keys into the device requires the raw components of keys. As does extracting the public key from a key pair on the device.

**Comment by reaperhulk** [comment]
@dainnilsson thanks for the context! Removing these classes seems like it may not actually be desirable. Our primary motivation was improving situations like `from_encoded_point` on the ECNumbers class, but https://github.com/pyca/cryptography/pull/4419 will deprecate that and move it to a classmethod so perhaps that's good enough.

I'm interested in how yubihsm does signing -- did you ever look at implementing the backend interfaces so that you could have yubi-backed instances of keys and just use the cryptography APIs? We've started moving away from the backend system because there didn't seem to be any interest from others in implementing it, but yubihsm support in python seems like an example of where that approach would have worked?

**Comment by dainnilsson** [comment]
I haven't looked at implementing the backend interface from cryptography, but that does sound like a pretty neat idea. I agree that it sounds like a valid use case , assuming there is interest for it.

We're planning on releasing a new version of our python-yubihsm library soon, and making it open source. I'll add a reminder to add a link to it here once we do!

**Comment by reaperhulk** [comment]
Great, look forward to seeing it. We might be willing to revisit our thoughts around backend deprecation if something like YubiHSM was interested in implementing that in the future. It would then give you an API that looks something like (a small amount of hand-waving, but this is mostly what we tried to make possible):

```python
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec

from yubico.hsm.serialization import load_private_key


# Totally made up idea of how to get a handle to a private key on the HSM
private_key = load_private_key(b"yubihsmidentifier", b"slotpassword")
data = b"this is some data I'd like to sign"
signature = private_key.sign(data, ec.ECDSA(hashes.SHA256()))
```

or perhaps a more interesting example, using our X509 API to build and sign a certificate using a private key in the HSM:

```python
import datetime

from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

from yubico.hsm.serialization import load_private_key


# Totally made up idea of how to get a handle to a private key on the HSM
private_key = load_private_key(b"yubihsmidentifier", b"slotpassword")


one_day = datetime.timedelta(1, 0, 0)
public_key = private_key.public_key()
builder = x509.CertificateBuilder()
builder = builder.subject_name(x509.Name([
    x509.NameAttribute(NameOID.COMMON_NAME, u'cryptography.io'),
]))
builder = builder.issuer_name(x509.Name([
    x509.NameAttribute(NameOID.COMMON_NAME, u'cryptography.io'),
]))
builder = builder.not_valid_before(datetime.datetime.today() - one_day)
builder = builder.not_valid_after(datetime.datetime.today() + (one_day * 30))
builder = builder.serial_number(x509.random_serial_number())
builder = builder.public_key(public_key)
builder = builder.add_extension(
    x509.SubjectAlternativeName(
        [x509.DNSName(u'cryptography.io')]
    ),
    critical=False
)
builder = builder.add_extension(
    x509.BasicConstraints(ca=False, path_length=None), critical=True,
)
certificate = builder.sign(
    private_key=private_key, algorithm=hashes.SHA256(),
)
```

**Comment by reaperhulk** [comment]
I'm convinced that removing these is not the right path now. Instead we should continue to add better APIs that we promote over these where possible, but have numbers as a final fallback (as indeed it was originally intended)
