### ISSUE TITLE
Add method to check if cert is in CRL?

### ISSUE THREAD

**Issue by magnuswatn** [pyca/cryptography#4330]
Hi,

I am using `cryptography` to check certificates against CRLs, to see if they are revoked, and I find the current CRL implementation a little lacking. To check if a certificate is revoked, I have to retrieve all the `RevokedCertificate` from the `CertificateRevocationList` and see if any of them has the same serial as the certificate in question (if there's a better way, please let me know!). This is time consuming on big CRLs.

I have played around with `X509_CRL_get0_by_serial()` and `X509_CRL_get0_by_cert()` from OpenSSL, and have found them to drastically improve performance.

So, what do you think about adding a function to `CertificateRevocationList` that checks if a specified certificate is in the CRL? I'm thinking `is_certificate_revoked` or `get_revoked_certificate` which can return a `RevokedCertificate`.

Thanks for making cryptography!

**Comment by reaperhulk** [comment]
`get_revoked_certificate` sounds like a good method to add. So it would return `None` or an instance of `RevokedCertificate` corresponding to the serial number provided? I don't see a reason to require users to pass an entire `Certificate` object for this purpose.

**Comment by reaperhulk** [comment]
I went ahead and implemented the idea since it was easy 😄

**Comment by magnuswatn** [comment]
Heyhey, nice! Looks good :+1:

**Comment by magnuswatn** [comment]
Just wanted to say thanks for the positive response and quick fix here @alex @reaperhulk. This was a noticeable performance improvement for my app.

Thanks!
