### ISSUE TITLE
Unknown Extension when signing certificate: CT Precertificate OID 1.3.6.1.4.1.11129.2.4.3

### ISSUE THREAD

**Issue by ricketybridge** [pyca/cryptography#4333]
Although support for CT Precertificate OID 1.3.6.1.4.1.11129.2.4.3 appears to have been added [for parsing](https://github.com/pyca/cryptography/issues/3325), when I try to sign a certificate that has this extension via CertificateBuilder, I get the following errors:

`KeyError: <ObjectIdentifier(oid=1.3.6.1.4.1.11129.2.4.2, name=Unknown OID)>`

`During handling of the above exception, another exception occurred:`

. . . 

`NotImplementedError: Extension not supported: <ObjectIdentifier(oid=1.3.6.1.4.1.11129.2.4.2, name=Unknown OID)>`

I'm running cryptography 2.2.2, python 3.6.5, pip3 10.0.1, macOS.

**Comment by reaperhulk** [comment]
This is because we haven't implemented support for creating CT precerts yet, just parsing. Hopefully we'll be able to add this for the next release (we've added it to that milestone)
