### ISSUE TITLE
Import error on embedded Python

### ISSUE THREAD

**Issue by jairoxyz** [pyca/cryptography#4335]
I am trying to use cryptography in Kodi 17 and am getting the same error as posted in another thread:

```
from cryptography.hazmat.bindings._padding import lib
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

I have built cryptography following the guide for building-cryptography-on-windows using Visual Studio Build Tools 2017 on Win Server 2012 x64. Environment Variables for Command-Line Builds were set with vcvarsall.bat x86 because Kodi is a 32 bit application:

```
Kodi compiled Dec 10 2017 by MSVC 190024215 for Windows NT x86 32-bit version 10.0 (0x0A000000)
Python 2.7.13 (default, Jul 13 2017, 20:56:54) [MSC v.1900 32 bit (Intel)]
```

My build host Python environment is as follows:

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
pip 10.0.1 from c:\Python27\lib\site-packages\pip (python 2.7)
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.2.2 enum34-1.1.6 idna-2.7 ipaddress-1.0.22 pycparser-2.18
OpenSSL package used: openssl-1.1.0h-2010-x86.zip
```

To reproduce the error:

- install Kodi 17 on Windows and open it
- enable logging under Settings->System
- download tester addon [plugin.video.cryptotest.zip](https://www51.zippyshare.com/v/s3iY7zkj/file.html)
- install the tester add-on inside Kodi under Addons->Install from repository->..->Install from Zip file
- open tester addon under Addons->Video Addons
- view kodi.log file under \kodi_install_dir\temp

I can also reproduce the error outside Kodi when using the package built for Python 2.7 32bit on Python 2.7 64bit in a standalone project. It works fine though with Python 2.7 32bit on my Windows 10 64bit PC.
According to https://cryptography.io/en/latest/installation/#supported-platforms you tested on 64bit Windows, so maybe this doesn't work at all on 32bit Windows?

Please note I have done the same exercise successfully with pycryptodome.

Thanks in advance.

**Comment by reaperhulk** [comment]
It seems likely that this works for most users of Kodi since we haven't gotten any other problem reports? We build wheels for both 32-bit and 64-bit Windows Python and test them in CI, so this is likely a very environment-specific problem. I'm closing since we haven't seen any additional activity, but if others are seeing this problem feel free to comment.
