### ISSUE TITLE
segfault when reinstall cffi or cryptography after import cryptography

### ISSUE THREAD

**Issue by HD650** [pyca/cryptography#4358]
segfault happens during python garbage collection if you import some module from `cryptography` first and then reinstall `cryptography` or `cffi`. Like this:
```
# only some modules in cryptography will trigger this
from cryptography.hazmat.bindings._padding import lib
import gc, pip

# force reinstall cryptography or cffi will both trigger this issue
pip.main(['install', '--ignore-installed', 'cffi'])

# during garbage collection the segfault happen
gc.collect()
Segmentation fault
```
This will happen in both python2 and python3, and actually you don't need to reinstall in the same process, after `from cryptography.hazmat.bindings._padding import lib`, you can start another terminal and reinstall `cryptography` or `cffi`, then the garbage collection will trigger the problem.
To import a package and then reinstall it is a weird action, but it happened here https://github.com/ansible/ansible/issues/42546 (In short, a program called ansible import `cryptography` at the beginning, then the user wants ansible to reinstall `cffi`, and then segfault).

The traceback of segfault:
```
#0  0x000000000051fe14 in visit_decref (op=0x7fffe5032680 <Lib_Type>, data=0x0) at Modules/gcmodule.c:360
#1  0x000000000045bbaf in dict_traverse (op=0x7fffe5cf11a8, visit=0x51fddc <visit_decref>, arg=0x0)
    at Objects/dictobject.c:2198
#2  0x000000000051fefe in subtract_refs (containers=0x80d1f0 <generations+80>) at Modules/gcmodule.c:385
#3  0x0000000000520e9f in collect (generation=2) at Modules/gcmodule.c:925
#4  0x0000000000521bb8 in PyGC_Collect () at Modules/gcmodule.c:1440
#5  0x0000000000506922 in Py_Finalize () at Python/pythonrun.c:455
#6  0x000000000050a07c in Py_Exit (sts=0) at Python/pythonrun.c:1792
```
It seems python try to garbage collect a dict at `0x7fffe5cf11a8`, and that dict contains some borken field`0x7fffe5032680`. These fields of that dict might be useful:
```
{
        .......
    "Lib": 0x7fffe5032680, # The PyObject instance cause this segfault, contains NULL value, seems already released
    "__file__": "/usr/local/lib/python2.7/site-packages/_cffi_backend.so",
    "__name__": "_cffi_backend"
        .......
}
```
Envirnoment infomation: `cffi==1.11.5`, `cryptography==2.3`, `pip==10.0.1`, `setuptools==39.2.0`

**Comment by alex** [comment]
I believe this is actually a pip bug: https://github.com/pypa/pip/issues/5366#issuecomment-388580714

It's fixed on pip master, but not in a release. Going to provisionally close this, but please leave a comment if you can reproduce on pip master and we'll reopen this.

**Comment by HD650** [comment]
@alex You are right, it's a problem in pip, I try the solution there and it works. Thanks!
