### ISSUE TITLE
Question - How to encrypt with multiple keys and decrypt with any of them

### ISSUE THREAD

**Issue by jfmatth** [pyca/cryptography#4368]
Thank you for this library, it's awesome!

Question - Is it possible to have two keys to encrypt something, but use either of the keys to decrypt?

This is a feature of GNUPG, but i'm unable to use that library for what i need.

thanks,

**Comment by reaperhulk** [comment]
cryptography provides a base set of primitives (and a limited number of higher level constructs for specific use cases). cryptography does not have a premade solution for your issue, so to build what you want you'll need to compose multiple primitives together. Doing this yourself when you're not intimately familiar with cryptographic concepts and their extremely numerous pitfalls is not recommended. Sorry!

**Comment by jfmatth** [comment]
@reaperhulk ,

Thanks for your response.  Understood.

J
