### ISSUE TITLE
support CT extending with openssl 1.0 line

### ISSUE THREAD

**Issue by blshkv** [pyca/cryptography#4373]
CT was added to openssl 1.1 (see http://www.certificate-transparency.org/certificate-transparency-in-openssl) and cryptography supports it. It can be verified using the following command:
```openssl s_client -connect google.com:443 -ct```

However, openssl 1.0 line seems supports it as well, see the following:
https://blog.pierky.com/certificate-transparency-manually-verify-sct-with-openssl/
It can be verified using the following:
```openssl s_client -connect sslanalyzer.comodoca.com:443 -status </dev/null```
or a tool linked in that blog post (https://github.com/pierky/sct-verify).

It would help a lot if cryptography could support both lines since a lot of Linux distros are still on 1.0 and might take awhile to migrate to 1.1. It would resolve issues with tools which relays on cryptography, for example:
https://github.com/nabla-c0d3/sslyze/issues/323

**Comment by reaperhulk** [comment]
Correcting myself: SCTLists are not ASN.1. They contain some ASN.1 (the signature) and are wrapped in an ASN.1 octet string, but they are TLS encoded.

**Comment by blshkv** [comment]
So openssl guys said that they will not help. So it's up to you if you want to parse it.

**Comment by alex** [comment]
I don't think we're going to do this -- it'd require adding a bunch of code for the SCT format, and as time goes on OpenSSL<1.1 is getting rarer and rarer.
