### ISSUE TITLE
PKCS11 and ENGINE

### ISSUE THREAD

**Issue by m32** [pyca/cryptography#4385]
I'm trying to enable PKCS11 thru ENGINE_* calls but pyca somehow ignores SO_PATH.
So far so good, but calling LOAD fails with wrong shared module path.
Can someone tell me what I'm making wrong ?

code:
        _e = lcc.ENGINE_by_id("dynamic")
        if _e is None:
            print 'dynamic engine unavailable'
            return

        def proc(e, cmd, a, z):
            rc = lcc.ENGINE_ctrl_cmd_string(e, cmd, a, z)
            print(cmd, a, '=', rc)
            return rc

        rc = proc(_e, "SO_PATH", "/usr/lib/ssl/engines/libpkcs11.so", 0)
        rc = proc(_e, "ID", "pkcs11", 0)
        rc = proc(_e, "DIR_LOAD", "0", 0)
        rc = proc(_e, "LIST_ADD", "1", 0)
        rc = proc(_e, "LOAD", "", 0)
        
        lcc.ENGINE_free(_e)
        e = lcc.ENGINE_by_id("pkcs11")

output of strace:
write(1, "******************** pkcs11\n", 28******************** pkcs11
write(1, "('SO_PATH', '/usr/lib/ssl/engine"..., 57('SO_PATH', '/usr/lib/ssl/engines/libpkcs11.so', '=', 1)
write(1, "('ID', 'pkcs11', '=', 1)\n", 25('ID', 'pkcs11', '=', 1)
write(1, "('DIR_LOAD', '0', '=', 1)\n", 26('DIR_LOAD', '0', '=', 1)
write(1, "('LIST_ADD', '1', '=', 1)\n", 26('LIST_ADD', '1', '=', 1)
write(1, "('LOAD', '', '=', 0)\n", 21('LOAD', '', '=', 0)
open("/opt/pyca/cryptography/openssl/lib/engines-1.1/pkcs11.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by reaperhulk** [comment]
You appear to be using the cryptography wheel. That wheel is built statically against OpenSSL 1.1.0, but disables dynamic engine support (https://github.com/pyca/infra/blob/master/cryptography-manylinux1/install_openssl.sh#L23). This means you can't load an engine like this. In your code you check to see if `_e` is `None` but the actual response will be a cffi `NULL` so it's not telling you that dynamic is unavailable.

 You can build cryptography against your system OpenSSL (which will allow this behavior) by passing `pip install cryptography --no-use-binary cryptography`. You'll need a compiler and the dev headers for both openssl and python to do this.
