### ISSUE TITLE
How to sign double-sha256 hashed messages?

### ISSUE THREAD

**Issue by black-wolfie** [pyca/cryptography#4387]
I was migrating from ```ecdsa``` to ```cryptography``` package, and I need to sign the double-sha256 hash of a message. In ```ecdsa``` it's:

``` from hashlib import sha256```
```signature = private_key.sign_digest(sha256(sha256( message.encode() ).digest()).digest()), sigencode = ecdsa.util.sigencode_string )```

I'm confused on how to do this in ```cryptography```, it seems like the following is only doing 1 ```sha256``` hash?

```signature = private_key.sign(message.encode(), ec.ECDSA(hashes.SHA256()))```

Many thanks!

**Comment by reaperhulk** [comment]
You can do this with Prehashed (https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils/?highlight=prehashed#cryptography.hazmat.primitives.asymmetric.utils.Prehashed). Just do your double hash and then pass the bytes, noting that it's prehashed.
