### ISSUE TITLE
Versions past 2.1.4 publish python 3.4 OSX wheel only

### ISSUE THREAD

**Issue by zsimic** [pyca/cryptography#4404]
cryptography [2.1.4](https://pypi.org/project/cryptography/2.1.4/#files) published OSX wheels for python 2.7, 3.4, 3.5 and 3.6

However, all versions after that, for example [2.3.1](https://pypi.org/project/cryptography/2.3.1/#files) published OSX wheels for python 2.7 and 3.4 only.

Would it be possible to publish OSX wheels for python 3.5, 3.6 and 3.7 as well consistently for new versions of cryptography?

**Comment by zsimic** [comment]
I'm using pip 18.0, `pip wheel` does download `cryptography-2.3.1-cp34-abi3-macosx_10_6_intel.whl` however `pex` (v1.4.5) does not consider that wheel to be valid when I try to create a pex package.

Perhaps this is a pex bug then. I'm not an expert on wheels, but I understand what you're saying - the wheel you publish should be sufficient, yet pex doesn't think so.

**Comment by reaperhulk** [comment]
Yeah that sounds like a pex bug

**Comment by zsimic** [comment]
Thank you very much! I learned something :) (abi3 wheels) and let the pex team know (https://github.com/pantsbuild/pex/issues/539)
