### ISSUE TITLE
setup.py _openssl.c:1834:14: error: unknown type name 'ENGINE_CMD_DEFN'

### ISSUE THREAD

**Issue by st301gpman** [pyca/cryptography#4412]
Trying to install cryptography on an IBM i platform in the PASE environment. It is a virtual AIX environment.

I am using Python 3.6, pip 18, cryptography 2.3.1, cffi 1.11.5 and setuptools 36.0.1

I have downloaded and unpacked the tar.gz and running the setup.py i get all the following warnings and errors in the attached log. The main one that seems to be holding everything up is this one
_openssl.c:1834:14: error: unknown type name 'ENGINE_CMD_DEFN'
[cryptography2.log](https://github.com/pyca/cryptography/files/2316216/cryptography2.log)

**Comment by reaperhulk** [comment]
That error msg makes it appear that OpenSSL is compiled without ENGINE support. Is `OPENSSL_NO_ENGINE` defined in `opensslconf.h`?

**Comment by st301gpman** [comment]
appears so. OpenSSL is supplied for this platform by IBM. What are my options?

#ifndef OPENSSL_NO_ENGINE
# define OPENSSL_NO_ENGINE
#endif
