### ISSUE TITLE
Conversion to PuTTY's .ppk format

### ISSUE THREAD

**Issue by TakingItCasual** [pyca/cryptography#4413]
I'm working with AWS EC2 .pem private keys. I've discovered I need to use puttygen to convert .pem keys to PuTTY's .ppk format to be able to use PuTTY on Windows. I haven't been able to discover how to bypass the GUI for a purely command line solution. Could this package provide a method for converting keys to the .ppk format?

**Comment by reaperhulk** [comment]
I believe the linux version of puttygen can do this. You could execute that via docker for windows or the  windows subsystem for linux? The putty key format is not really documented and it isn't a standard so I don't think we'd be interested in supporting serialization directly in cryptography though.

**Comment by TakingItCasual** [comment]
Isn't .ppk the de facto standard for Windows SSH keys though? Docker feels like overkill, given I need this for an automation script, and it should work for down to Windows 7, so no subsystem. It's frustrating for SSH keys to be such a roadblock to what feels like it should be a simple problem. The puttygen command forces a GUI on you on Windows, so the official method can't even be automated.
