### ISSUE TITLE
[question] openssl dhparam

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#4414]
Please tell me (and maybe in the doc) how to implement that using Cryptography ?

`openssl dhparam -dsaparam -outform PEM -out /var/cache/squid/dhparams.2048.pem 2048`

**Comment by reaperhulk** [comment]
Generate parameters with https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dh/#cryptography.hazmat.primitives.asymmetric.dh.generate_parameters

and then serialize with https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dh/#cryptography.hazmat.primitives.asymmetric.dh.DHParameters.parameter_bytes

Generating DSA parameters and converting to DH parameters (which that command does) can be accomplished by calling dsa.generate_parameters, getting the DSAParameterNumbers, making a DHParameterNumbers object, converting it to a DHParameters object, and then calling parameter_bytes as above.
