### ISSUE TITLE
Memory Cleaning Ideas

### ISSUE THREAD

**Issue by earonesty** [pyca/cryptography#4437]
Openssl objects automatically clean memory on free.   Which is cool.   But python objects don't.   What's more, builtins like int's and bytes can't be marked as "clean on free" (which would be cool if they could!).

When handling keys, this library should probably return "cleanable" objecs, like bytearray's ... which the caller can easily wipe clean of key material as needed.    Requiring immutable objects like int's and bytes forces the caller to use unsafe tactics.

Realistically, it's very hard to custody memory in python.   I've tried, and I wrote some tools to unit test memory cleaning routines.   But at least the library itself should make it easier for the user when possible.

**Comment by reaperhulk** [comment]
refs #4409 and #4621. We can leave this open as a tracking issue for supporting bytes-like types for loading and serializing asymmetric keys as well.

**Comment by reaperhulk** [comment]
This is now effectively done. We now support bytes-like on (I believe) all key material arguments. Coupled with loading from a file and writing into a buffer via `read_into` it's now possible to clean memory, although it's still the caller's responsibility to zero the bytearray.
