### ISSUE TITLE
[RFC] Package based on cryptography to use OpenSSL Engine(HSM) keys is now available

### ISSUE THREAD

**Issue by space88man** [pyca/cryptography#4446]
Please excuse the hijack — this is a sidekick package to make OpenSSL Engine keys implement cryptography interfaces

https://github.com/space88man/cryptography_engine

Since the cffi exposes the ENGINE_* functions I thought to make a package that actually uses them.
The private keys are sufficiently duck-typed that the X.509 certificate creation and signing example in the docs actually works.

Hope that you will continue to keep these functions available and would love to hear your comments.

**Comment by alex** [comment]
Thanks for the heads up.

If you're interested in contributing parts of this upstream, we're interested in some day supporting hardware backed keys in cryptography itself. There'd probably need to be some substantial API changes, but we're happy to discuss and review pull requests.
