### ISSUE TITLE
get_revoked_certificate_by_serial_number breaks signature validation on CertificateRevocationList

### ISSUE THREAD

**Issue by magnuswatn** [pyca/cryptography#4456]
Hi,

Using the `get_revoked_certificate_by_serial_number` method on CertificateRevocationList will make OpenSSL sort the content of the CRL, and thus changing it.

This can be demonstrated with the following snippet:

```
def main():
    with open("crl.crl", "rb") as open_file:
        crl = x509.load_der_x509_crl(open_file.read(), default_backend())

    print(base64.b64encode(hashlib.sha256(crl.tbs_certlist_bytes).digest()).decode())
    crl.get_revoked_certificate_by_serial_number(123)
    print(base64.b64encode(hashlib.sha256(crl.tbs_certlist_bytes).digest()).decode())
```

This will return two different hashes. This then makes the signature validation on the CRL fail (tried using both `tbs_certlist_bytes` and `is_signature_valid`).

Not a big deal (I'm guessing most will verify the signature on the CRL before checking if the certificate is in it), but I'm thinking a note in the documentation would be nice. I scratched my head quite a bit before understanding why a previously good CRL suddenly failed signature validation :-)

Thanks!

**Comment by alex** [comment]
What the heck...

This is definitely not a docs bug, this is a for-real bug.
