### ISSUE TITLE
asn1crypto uses system default libcrypto instead of cryptography's one.

### ISSUE THREAD

**Issue by methane** [pyca/cryptography#4460]
When buidling uwsgi, Python, and cryptography, we can specify custom location of OpenSSL.
We use such option to use OpenSSL different from system's default one.

But asn1crypto loads system libcrypto for faster `inverse_mod()` implementation.
https://github.com/wbond/asn1crypto/blob/master/asn1crypto/_perf/_big_num_ctypes.py#L35

This may cause trouble.  In our case, it caused SEGV in uwsgi application because
ABI is incompatible from libcrypto used by uwsgi.  
We can avoid this SEGV by removing `_perf` directory in the asn1crypto.  But I want
mixing incompatible OpenSSL is avoided by default.

How about embed asn1crypto without `_perf` module, or with custom `_perf` module using
cryptography's OpenSSL?   
"Embedding asn1crypto without `_perf`" seems supported:
https://github.com/wbond/asn1crypto/blob/master/changelog.md#0182

**Comment by reaperhulk** [comment]
Are you are compiling your own cryptography against your own custom OpenSSL, not the statically linked wheels we provide via PyPI? If so, are you statically or dynamically linking? What call are you making that causes the segfault?

**Comment by reaperhulk** [comment]
Ah, you filed https://github.com/wbond/asn1crypto/issues/113 (which is likely where any potential workaround would live anyway)

**Comment by njsmith** [comment]
This is another casualty of https://github.com/unbit/uwsgi/issues/1590, see https://github.com/wbond/asn1crypto/issues/113#issuecomment-419278662

**Comment by wbond** [comment]
I just commented at https://github.com/wbond/asn1crypto/issues/113#issuecomment-419279419 explaining that in all likelihood, the libcrypto dependency will be dropped since asn1crypto will likely drop the ability to compute the public key from a private key. Instead it will likely defer to a true crypto package.

**Comment by reaperhulk** [comment]
Thanks for the update @wbond, we'll go ahead and close it on this side for now :)

**Comment by methane** [comment]
Thank you!
I was not sure this issue should be fixed by which side so I filed issue on both project.
But it seems removing libcrypto dependency from asn1crypto is the simplest and
the best solution to me.

**Comment by wbond** [comment]
Just for historical reference, version 1.0.0 of asn1crypto dropped the libcrypto dependency.
