### ISSUE TITLE
More descriptive error msg for certificate loading

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#4498]
When we fail to load a PEM certificate we do this: https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L1151

Given that people occasionally attempt to load valid certs that don't have proper line wrapping (see: https://github.com/pyca/cryptography/issues/4487 and https://github.com/pyca/cryptography/issues/4085) should we alter the text to say something about how what a valid PEM looks like and that they should check their cert?

**Comment by andrealmeid** [comment]
Can I get this one? :)

**Comment by reaperhulk** [comment]
Sure, we'd be happy to review a PR to fix this.
