### ISSUE TITLE
Use O_CLOEXEC when opening up /dev/urandom

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4500]
https://github.com/pyca/cryptography/blob/master/src/_cffi_src/openssl/src/osrandom_engine.c#L109-L122

We should just use `O_CLOEXEC` instead of the `fcntl` dance, which has the benefit of being faster, shorter, and more sandboxing friendly.

**Comment by njsmith** [comment]
It also fixes a race condition (if another thread forks in between the `open` and the `fcntl`).
