### ISSUE TITLE
[Feature request] Add a partial-rsa-key-handling function for computing "d"

### ISSUE THREAD

**Issue by vpelletier** [pyca/cryptography#4503]
Creating an `RSAPrivateKey` from individual components requires having `p`, `q`, `d`, `dmp1`, `dmq1`,  `iqmp` and (as public components) `n` and `e`.

Some protocols, such as [OpenPGP smartcard](https://gnupg.org/ftp/specs/), supports transmiting private keys (in the case of OpenPGP: storing a computer-generated RSA private key in a smartcard) without proviging `d`, `dmp1`, `dmq1`, `iqmp` and (strictly speaking) `e` (but `e` is specified as being the classical 65537 when ommitted, so it can be considered as always provided).

`cryptography` provides functions to compute `dmp1`, `dmq1` and `iqmp`, but does not provide a way of computing `d`, while it can be computed using `e` and `p` and `q`.

It would be nice to provide such function, and any associated warning, as part of https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#handling-partial-rsa-private-keys .

**Comment by reaperhulk** [comment]
I'm going to close this since nobody has stepped forward to write it and we've seen no further requests. If someone stumbles on this closed issue, we're happy to take a PR for this.
