### ISSUE TITLE
fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory

### ISSUE THREAD

**Issue by hopefulguowei** [pyca/cryptography#4508]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

**Comment by alex** [comment]
You should either upgrade your version of pip such that you get a wheel, or you need to install the openssl development headers.
