### ISSUE TITLE
Signing with RSA-PSS with SHA-256 + BLAKE2s for hashing fails

### ISSUE THREAD

**Issue by RobertoPrevato** [pyca/cryptography#4538]
Hi,
This is a request for information, because I am not sure whether this is a bug or I am trying to do something conceptually wrong. I am trying to use BLAKE2s to generate an hash, then sign using RSA-PSS with SHA-256, like in the example below.

```python
        signature = configured_key.sign(
            payload,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.BLAKE2s(32)  # < it fails if I try to create the hash using BLAKE2s
            # hashes.SHA256()  < it works if I create the hash using SHA256
        )
```

Using **hashes.BLAKE2s** as the last argument, causes this error:
```
            raise InternalError(
                "Unknown OpenSSL error. This error is commonly encountered when "
                "another library is not cleaning up the OpenSSL error stack. If "
                "you are using cryptography with another library that uses "
                "OpenSSL try disabling it before reporting a bug. Otherwise "
                "please file an issue at https://github.com/pyca/cryptography/"
                "issues with information on how to reproduce "
                "this. ({0!r})".format(errors_with_text),
>               errors_with_text
            )
E           cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([])
```

Is it wrong what I am trying to do? If not, I will add details about versions of all software I am using.

PS. Thank You for your amazing work on this library.

Kind Regards,
Roberto

**Comment by reaperhulk** [comment]
Thanks for the report!

OpenSSL doesn't support the use of blake2 for RSA-PSS signatures so this unfortunately won't work, but actually there is a separate bug cryptography has that causes it to fail before it can even error with `[_OpenSSLErrorWithText(code=67682461, lib=4, func=140, reason=157, reason_text=b'error:0408C09D:rsa routines:check_padding_md:invalid digest')]`. 

We need to put in a PR to properly build the string to get the digest by using `backend._build_openssl_digest_name`, and then we'll need to add a branch (and test) to catch unsupported algorithms.

**Comment by reaperhulk** [comment]
Here's the set of supported digests as of OpenSSL 1.1.1: https://github.com/openssl/openssl/blob/040a03470c7c5bf95fe8e6143db7bef357a22833/crypto/rsa/rsa_pmeth.c#L371-L385

**Comment by RobertoPrevato** [comment]
Hi Paul,
Thank You for your quick answer and kind explanation! I am impressed you already created a PR, kudos to that. 
I understand I should leave this bug open, it will be closed automatically when pull request completes?

**Comment by reaperhulk** [comment]
Yes, this will automatically close when that PR is merged.
