### ISSUE TITLE
Error when using this library on aws lambda

### ISSUE THREAD

**Issue by tuseau** [pyca/cryptography#4549]
Hi,

This is probably an issue that amazon need to fix themselves, but thought I'd report it anyway. I get the following error on aws lambda:

/var/task/cryptography/hazmat/bindings/_padding.so: undefined symbol: PyInt_FromLong

My code is pretty simple, its just a copy&paste of the sample for encrypting some data to aes:

-------------------------
from cryptography.fernet import Fernet

key = Fernet.generate_key()
f = Fernet(key)
token = f.encrypt(b"my deep dark secret")
print(token)
-------------------------

It works fine locally using PyCharm (or whatever IDE you want).

Has anyone experienced the same? Is there a workaround perhaps?

**Comment by tuseau** [comment]
I don't know actually. How do I find out?

**Comment by reaperhulk** [comment]
You have some sort of deployment pipeline to push code to lambda. cryptography needs to be packaged as part of that, so you'll need to look at how you're doing it. I know people are using cryptography successfully on lambda by both using the manylinux1 wheel directly and by building their own wheel using an amazon linux docker container.
