### ISSUE TITLE
hashes.update may be vulnerable to collisions

### ISSUE THREAD

**Issue by miguelvargasmartin** [pyca/cryptography#4558]
Not sure this is a cryptography.io bug or if it's carried over from OpenSSL. But if real, it is major as it is very easy to find collisions in SHA256. More particularly, one can generate two sets of strings that lead to breaking weak collision resistance; i.e., given a message M it is possible to find a message M' such that SHA256(M)=SHA256(M'). Here is some code to see this:
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
digest = hashes.Hash(hashes.SHA256(), backend=default_backend())
digest.update(bytes(241))
digest.update(bytes(151))
digest.update(bytes(7))
print(digest.finalize())
digest1 = hashes.Hash(hashes.SHA256(), backend=default_backend())
digest1.update(bytes(19))
digest1.update(bytes(151))
digest1.update(bytes(229))
print(digest1.finalize())
```
The output is two identical hash values (`b'\x815\x8eX\xee\xcd:6\xc8\x8f@\x07\x172\xdb\x0b\xe7\x9c\xe4\xa7\x10\xe2\x9c\xca`\xb2\xf7i\xbb\xaa\xc7k'`) built from two distinct messages. Many more collisions can be found easily.

This was found using Python 3.6 with cryptography 2.3.1, openssl 1.02, all bundled with Anaconda.

Thank you.

**Comment by alex** [comment]
I don't think this program is doing what you think it's doing `bytes(19)` returns `b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'`, that is, 19 `\x00` bytes. So all you've done is hash the same string, constructed different ways -- both of these are simply the hash of 399 `\x00` bytes.

**Comment by miguelvargasmartin** [comment]
Yes, of course. I totally missed that and it got me off guard. Thank you.
