### ISSUE TITLE
osrandom_init function returns incorrect error code

### ISSUE THREAD

**Issue by Mirraz** [pyca/cryptography#4594]
If in `osrandom_init` function `getrandom` syscall returns an error `EAGAIN` (or other unexpected error), then error is put to openssl error queue by `ERR_PUT_error`, but function `osrandom_init` itself returns non-error code `1`. So code called `osrandom_init` thinks that everything is fine and not consumes error from openssl error queue so this error stays in openssl error queue and leads to random errors later.

https://github.com/pyca/cryptography/blob/master/src/_cffi_src/openssl/src/osrandom_engine.c#L300
https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L135

Also why on `EAGAIN` error there is no fallback to `/dev/urandom`?

**Comment by reaperhulk** [comment]
cc @tiran

**Comment by reaperhulk** [comment]
This is now fixed via #4620
