### ISSUE TITLE
Decide when to drop support for OpenSSL 1.0.1

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4600]
Here's the current data on downloads for sdists:

<img width="675" alt="screen shot 2018-11-21 at 11 21 26 am" src="https://user-images.githubusercontent.com/772/48857893-9c143680-ed7f-11e8-82ec-11fbdb3385bb.png">

Getting closer to 10%, which is great. The following OS's default OpenSSLs are effected:

- Ubuntu Trusty
- Debian Jessie (1.0.2 is available in jessie-backports)

SQL to compute these stats:

```sql
SELECT
  STRFTIME_UTC_USEC(timestamp, "%Y-%m") AS yyyymm,
  ROUND(100 * SUM(CASE
        WHEN SUBSTR(REGEXP_EXTRACT(details.openssl_version, r"^OpenSSL ([^ ]+) "), 0, 5) = "1.0.1" THEN 1
        ELSE 0 END) / COUNT(*), 1) AS percent_101,
  ROUND(100 * SUM(CASE
        WHEN SUBSTR(REGEXP_EXTRACT(details.openssl_version, r"^OpenSSL ([^ ]+) "), 0, 5) = "1.0.2" THEN 1
        ELSE 0 END) / COUNT(*), 1) AS percent_102,
  ROUND(100 * SUM(CASE
        WHEN SUBSTR(REGEXP_EXTRACT(details.openssl_version, r"^OpenSSL ([^ ]+) "), 0, 5) = "1.1.0" THEN 1
        ELSE 0 END) / COUNT(*), 1) AS percent_110,
  ROUND(100 * SUM(CASE
        WHEN SUBSTR(REGEXP_EXTRACT(details.openssl_version, r"^OpenSSL ([^ ]+) "), 0, 5) = "1.1.1" THEN 1
        ELSE 0 END) / COUNT(*), 1) AS percent_111,
  COUNT(*) AS download_count
FROM
  TABLE_DATE_RANGE( [the-psf:pypi.downloads],
    DATE_ADD(CURRENT_TIMESTAMP(), -1, "year"),
    CURRENT_TIMESTAMP() )
WHERE
  details.openssl_version IS NOT NULL
  AND file.project = 'cryptography'
  AND file.type = 'sdist'
GROUP BY
  yyyymm
ORDER BY
  yyyymm DESC
LIMIT
  100
```

**Comment by ohemorange** [comment]
For Certbot, about 9% of our users are on trusty and another 9% on jessie. We're in backports anyway so that's not so big a problem. Happy to EOL when trusty does though; it's only reasonable to support so far back.

**Comment by reaperhulk** [comment]
@ohemorange does certbot use wheels on deployments outside of deb/rpm where possible?

**Comment by ohemorange** [comment]
We release wheels, but directly installing a wheel is not the correct way to use Certbot; see instructions for each platform at https://certbot.eff.org/

**Comment by reaperhulk** [comment]
![image](https://user-images.githubusercontent.com/161495/53310537-46a07600-38e8-11e9-882a-fcd1b9c6c0a8.png)
A little bit of backsliding here. Ubuntu 14.04 support is terminated as of April 2019 so looking in May/June might be interesting.

**Comment by alex** [comment]
Really good progress here:

![image](https://user-images.githubusercontent.com/772/58384703-e71f3880-7fb2-11e9-9453-1c53eaab5187.png)

**Comment by alex** [comment]
We currently emit a warning on 1.0.1, the next milestone is raising an error on 1.0.1, unless you set an env var. After that we delete the code entirely.

Shall our threshold for raising an error be 1%?

**Comment by reaperhulk** [comment]
Our cycle with 1.0.0 and 0.9.8 was:

* Warn we're going to drop support at some point
* Warn we're going to drop support next release
* Release where it only works via env var
* Release where all support is gone

I think when we hit 2% I'm good with going to step 2 and if it hasn't made it down to 1% by step 3 oh well.

**Comment by alex** [comment]
The majority of 1.0.1 downloads are from: Ubuntu 14.04 (EOL), Debian Jessie, and OracleServer 6.4.

**Comment by alex** [comment]
![image](https://user-images.githubusercontent.com/772/59555796-27f0e880-8f86-11e9-8628-1b83054a7cc6.png)

More forward progress. Same distros.

**Comment by alex** [comment]
We're declaring this process "decided" and I'll file a new issue to track the release.
