### ISSUE TITLE
AES Decrypt，It ends with a few characters less than the original data. the end "hW+WY4Dx" miss

### ISSUE THREAD

**Issue by x-falcon** [pyca/cryptography#4633]
original data
`b'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeFDLUD78Gaaqc0P03xsaW/em5Y5GdANm3+yfbmftXLfMIXstIpaZCH7SXGM8z+PNCdXE4QLV8LS/EKLHhm511ceHxmaWSUA8hT355W/9T89rZ0m2FJZRujEeJUFOvAnixiCQqcyza8WHqDF/JjWBocIwKUsGCzd91SscIYL3ShjDIolyR9T2O5YkI6aenSvfL/7yZv8aQA7QbRrf4l5w+8lAStltyqbeoW8FYwQwTJ8KNwY2wN6HDT02BhZBznV9HuIe1578YSMmOJ1gOk7OeYCdmhkw2LPOXTI60LzmamRNUF2ACPQNYvCV4rEjnbLWC1wS0GPyQ+utAyn4eI9wbAgMBAAECggEBAJdAFHofm0+nyd5x6/P/+qM9neB4suTGfoHymWvUTL1MeziZL0R0JW7lnx5FdGGGTU9XI1xXngNL1zt3J+drD+u8O1FL/ttOkW9zb8UB5jzsWYJ+8b58IMLF4bbgsY4BVeg7u735oXQgcDpyYQ6prh6TgJ1LTaZjxqxg2HuZP89P9o1OGFf1G1z/N5pSLTfnldDVHzaTPQntvyJCuPsqmG3+cBqDeJJbH9LDy0/XsOCIxDvFlJBEEOOBG9jFEKyyqpVOK7LHAjlaG8kNuOe0flwT8dIvh9pRAfNFKpts212WkiR/EHR/WSiP5Kr5jDPKLlI7P9TQSzT8BZFJP84jKsECgYEA9xd7yFIUVn6nAc4Npp3sawq6NDKkOx5FFudQEkPO5OhUTLCEpsHcW5NvJ0AcTHCWQplUE67gQ3H3ua2fY2oiu8HTpSNU7b43aYVPyMvB6/+dfkM2Yc8iFRGYhK4raFzkReYkgjBHO4LTL89ayXBSmkxU3fko4d08x1JtjVH8LKECgYEA5hXcW/NQX8mZDujPVNkA9gUw0PaSDsRb0MgO7IQk++hTeavCS4V8AHtt/gmw+mMke4SrJEvRVL34hEqMTKzGku+2u3CtzYkkZ4kYJuuEvFLoaWfDI8lBpA9FquphCUGYYRq7gjMSuqxftb8rRThgmX4oWIwxj/ppw3oaA3sxszsCgYAh3kcqOw3smSmdFrhKSUU5mtvRAcv/CnQf4o7YIhE+0RWU+XEFRndE2h2XPLNkSt5dvJSIqiS1Oe7htYmuX8LpB3VSIlimybbgsNQxyrQG/B+DSgUvPOwIBURpk1IB2RG0/wmsCqAI6TK3T+26xLmdyq6rSlavNtr42zSG9WDiYQKBgQCeru8GX53MIk60cK4ld3BpPJU5WQTMuHIWYROh3VVggw+nN2VODqbB8l6euPJdDalooswhwUSC7G4MVxnB+9sMFdVyGrlTqsT3vx5wITivZYKyx4RXFwN1ca77vJ/l8V51gilWF4FQS3fK8iiWmdZNpiuPPkkkYnE1Bu4P/pP9ZwKBgAutknbiXdNsS028Ilk/LzYxP0P3DW9UrhdxZ/LTjZIpbO0sUHCuVDC70M41NmgzzC1XLJhNGXu8Sm5shc3kZ2sfjVKt1rL7aejULGwvgLUvCRNFilXbX0wbpTW+OM5e1wNNcdG1kPxaecx7hbH6QYJpGu2p5F6DE8UchW+WY4Dx'`

Decrypt Data
`b'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeFDLUD78Gaaqc0P03xsaW/em5Y5GdANm3+yfbmftXLfMIXstIpaZCH7SXGM8z+PNCdXE4QLV8LS/EKLHhm511ceHxmaWSUA8hT355W/9T89rZ0m2FJZRujEeJUFOvAnixiCQqcyza8WHqDF/JjWBocIwKUsGCzd91SscIYL3ShjDIolyR9T2O5YkI6aenSvfL/7yZv8aQA7QbRrf4l5w+8lAStltyqbeoW8FYwQwTJ8KNwY2wN6HDT02BhZBznV9HuIe1578YSMmOJ1gOk7OeYCdmhkw2LPOXTI60LzmamRNUF2ACPQNYvCV4rEjnbLWC1wS0GPyQ+utAyn4eI9wbAgMBAAECggEBAJdAFHofm0+nyd5x6/P/+qM9neB4suTGfoHymWvUTL1MeziZL0R0JW7lnx5FdGGGTU9XI1xXngNL1zt3J+drD+u8O1FL/ttOkW9zb8UB5jzsWYJ+8b58IMLF4bbgsY4BVeg7u735oXQgcDpyYQ6prh6TgJ1LTaZjxqxg2HuZP89P9o1OGFf1G1z/N5pSLTfnldDVHzaTPQntvyJCuPsqmG3+cBqDeJJbH9LDy0/XsOCIxDvFlJBEEOOBG9jFEKyyqpVOK7LHAjlaG8kNuOe0flwT8dIvh9pRAfNFKpts212WkiR/EHR/WSiP5Kr5jDPKLlI7P9TQSzT8BZFJP84jKsECgYEA9xd7yFIUVn6nAc4Npp3sawq6NDKkOx5FFudQEkPO5OhUTLCEpsHcW5NvJ0AcTHCWQplUE67gQ3H3ua2fY2oiu8HTpSNU7b43aYVPyMvB6/+dfkM2Yc8iFRGYhK4raFzkReYkgjBHO4LTL89ayXBSmkxU3fko4d08x1JtjVH8LKECgYEA5hXcW/NQX8mZDujPVNkA9gUw0PaSDsRb0MgO7IQk++hTeavCS4V8AHtt/gmw+mMke4SrJEvRVL34hEqMTKzGku+2u3CtzYkkZ4kYJuuEvFLoaWfDI8lBpA9FquphCUGYYRq7gjMSuqxftb8rRThgmX4oWIwxj/ppw3oaA3sxszsCgYAh3kcqOw3smSmdFrhKSUU5mtvRAcv/CnQf4o7YIhE+0RWU+XEFRndE2h2XPLNkSt5dvJSIqiS1Oe7htYmuX8LpB3VSIlimybbgsNQxyrQG/B+DSgUvPOwIBURpk1IB2RG0/wmsCqAI6TK3T+26xLmdyq6rSlavNtr42zSG9WDiYQKBgQCeru8GX53MIk60cK4ld3BpPJU5WQTMuHIWYROh3VVggw+nN2VODqbB8l6euPJdDalooswhwUSC7G4MVxnB+9sMFdVyGrlTqsT3vx5wITivZYKyx4RXFwN1ca77vJ/l8V51gilWF4FQS3fK8iiWmdZNpiuPPkkkYnE1Bu4P/pP9ZwKBgAutknbiXdNsS028Ilk/LzYxP0P3DW9UrhdxZ/LTjZIpbO0sUHCuVDC70M41NmgzzC1XLJhNGXu8Sm5shc3kZ2sfjVKt1rL7aejULGwvgLUvCRNFilXbX0wbpTW+OM5e1wNNcdG1kPxaecx7hbH6QYJpGu2p5F6DE8Uc'`

my code:
```
# -*-coding:utf-8-*-
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
import base64


def aes_decrypt(key, data):
    """
    decrypt aes by ecb mode
    :param key: bin
    :param data: bin
    :return: bin
    """
    algorithms_ = algorithms.AES(key)
    cipher = Cipher(algorithms_, modes.ECB(), backend=default_backend())
    decryptor = cipher.decryptor()
    return decryptor.update(data)


def aes_encrypt(key, data):
    """
    decrypt aes by ecb mode
    :param key: bin
    :param data: bin
    :return: bin
    """
    algorithms_ = algorithms.AES(key)
    cipher = Cipher(algorithms_, modes.ECB(), backend=default_backend())
    encryptor = cipher.encryptor()
    return encryptor.update(data)

if __name__ == '__main__':
    aesKey = b"pI3UfYGBWXR938Ui0ngNsmOsJ675kYcfqhzG86l7K24="
    data=b'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeFDLUD78Gaaqc0P03xsaW/em5Y5GdANm3+yfbmftXLfMIXstIpaZCH7SXGM8z+PNCdXE4QLV8LS/EKLHhm511ceHxmaWSUA8hT355W/9T89rZ0m2FJZRujEeJUFOvAnixiCQqcyza8WHqDF/JjWBocIwKUsGCzd91SscIYL3ShjDIolyR9T2O5YkI6aenSvfL/7yZv8aQA7QbRrf4l5w+8lAStltyqbeoW8FYwQwTJ8KNwY2wN6HDT02BhZBznV9HuIe1578YSMmOJ1gOk7OeYCdmhkw2LPOXTI60LzmamRNUF2ACPQNYvCV4rEjnbLWC1wS0GPyQ+utAyn4eI9wbAgMBAAECggEBAJdAFHofm0+nyd5x6/P/+qM9neB4suTGfoHymWvUTL1MeziZL0R0JW7lnx5FdGGGTU9XI1xXngNL1zt3J+drD+u8O1FL/ttOkW9zb8UB5jzsWYJ+8b58IMLF4bbgsY4BVeg7u735oXQgcDpyYQ6prh6TgJ1LTaZjxqxg2HuZP89P9o1OGFf1G1z/N5pSLTfnldDVHzaTPQntvyJCuPsqmG3+cBqDeJJbH9LDy0/XsOCIxDvFlJBEEOOBG9jFEKyyqpVOK7LHAjlaG8kNuOe0flwT8dIvh9pRAfNFKpts212WkiR/EHR/WSiP5Kr5jDPKLlI7P9TQSzT8BZFJP84jKsECgYEA9xd7yFIUVn6nAc4Npp3sawq6NDKkOx5FFudQEkPO5OhUTLCEpsHcW5NvJ0AcTHCWQplUE67gQ3H3ua2fY2oiu8HTpSNU7b43aYVPyMvB6/+dfkM2Yc8iFRGYhK4raFzkReYkgjBHO4LTL89ayXBSmkxU3fko4d08x1JtjVH8LKECgYEA5hXcW/NQX8mZDujPVNkA9gUw0PaSDsRb0MgO7IQk++hTeavCS4V8AHtt/gmw+mMke4SrJEvRVL34hEqMTKzGku+2u3CtzYkkZ4kYJuuEvFLoaWfDI8lBpA9FquphCUGYYRq7gjMSuqxftb8rRThgmX4oWIwxj/ppw3oaA3sxszsCgYAh3kcqOw3smSmdFrhKSUU5mtvRAcv/CnQf4o7YIhE+0RWU+XEFRndE2h2XPLNkSt5dvJSIqiS1Oe7htYmuX8LpB3VSIlimybbgsNQxyrQG/B+DSgUvPOwIBURpk1IB2RG0/wmsCqAI6TK3T+26xLmdyq6rSlavNtr42zSG9WDiYQKBgQCeru8GX53MIk60cK4ld3BpPJU5WQTMuHIWYROh3VVggw+nN2VODqbB8l6euPJdDalooswhwUSC7G4MVxnB+9sMFdVyGrlTqsT3vx5wITivZYKyx4RXFwN1ca77vJ/l8V51gilWF4FQS3fK8iiWmdZNpiuPPkkkYnE1Bu4P/pP9ZwKBgAutknbiXdNsS028Ilk/LzYxP0P3DW9UrhdxZ/LTjZIpbO0sUHCuVDC70M41NmgzzC1XLJhNGXu8Sm5shc3kZ2sfjVKt1rL7aejULGwvgLUvCRNFilXbX0wbpTW+OM5e1wNNcdG1kPxaecx7hbH6QYJpGu2p5F6DE8UchW+WY4Dx'
    ciphertext = base64.b64encode(aes_encrypt(base64.b64decode(aesKey),data))
    print(aes_decrypt(base64.b64decode(aesKey),base64.b64decode(ciphertext)))
```

**Comment by x-falcon** [comment]
@reaperhulk The code has been posted.

**Comment by reaperhulk** [comment]
You must use padding or supply data such that it aligns to the block size of the algorithm when encrypting with ECB mode (which is a bad mode that you should not use if at all possible). In this case your `data` is 1218 bytes, which is 2 modulo 16. If you were calling `finalize()` (which you should always do) you would have seen a `ValueError` exception that explained the problem.
