### ISSUE TITLE
Unknown OpenSSL error on letsencrypt renewal

### ISSUE THREAD

**Issue by sermad-shah** [pyca/cryptography#4644]
Hi.. I installed lets encrypt certificate successfully on my website 76 days ago with no issues.. today I tried to renew it got the following error message:

Cert is due for renewal, auto-renewing…
Plugins selected: Authenticator standalone, Installer None
Attempting to renew cert (MYDOMAIN.com) from /etc/letsencrypt/renewal/MYDOMAIN.com.conf produced an unexpected error: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=2147893649, lib=128, func=100, reason=401, reason_text=b’error:80064191:lib(128):osrandom_init:getrandom() initialization failed with EAGAIN. Most likely Kernel CPRNG is not seeded yet.’), _OpenSSLErrorWithText(code=2147897744, lib=128, func=101, reason=400, reason_text=b’error:80065190:lib(128):osrandom_rand_bytes:getrandom() initialization failed.’), _OpenSSLErrorWithText(code=67665923, lib=4, func=136, reason=3, reason_text=b’error:04088003:rsa routines:RSA_setup_blinding:BN lib’)]). Skipping.
All renewal attempts failed. The following certs could not be renewed:
/etc/letsencrypt/live/MYDOMAIN.com/fullchain.pem (failure)

I have no idea about "cryptography".. I didn't installed it myself earlier.. I am using tomcat 8.5.34 web-server on Ubuntu 16.04 LTS.. I have "OpenSSL 1.0.2g" I dont know how to check version "cryptography". How do I avoid this error and renew my site certificate.. sorry if this is not a place to ask such issues.

**Comment by alex** [comment]
It looks like you're trying to run `certbot` at very early boot, before your kernel's CSPRNG has been initialized. I'm not sure under what circumstances this can happen on Ubuntu 16.04.

**Comment by sermad-shah** [comment]
I did restarted my Ubuntu 16.04 instance and immediately tried to run certbot and got the error mentioned above, after few hours I tried again and it worked for me.. thanks

**Comment by alex** [comment]
FWIW, my understanding was that Ubuntu should save entropy on shutdown and restore it on boot, so it's surprising to me that by the time your userland was up that the CSPRNG wouldn't be seeded.

FWIW in our next release we'll simply block until the CSPRNG is seeded, and therefore you wouldn't get this error (but it might be slow).
