### ISSUE TITLE
OCSP: Support for SingleResponse extensions

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#4660]
RFC 6960 defines several extensions that are supposed to be part of OCSP singleResponses. e.g. Archive Cutoff and CRL references. It's currently not possible to add extensions to `cryptography.x509.ocsp._SingleResponse`.

asn1crypto currently supports [these extensions](https://github.com/wbond/asn1crypto/blob/master/asn1crypto/ocsp.py#L345-L356) for this. Note this for some reason also includes `2.5.29.29`, which is not mentioned RFC 6960, AFAICT.

**Comment by reaperhulk** [comment]
Thanks for the report. We were holding off on implementing single response extensions until we had a consumer that wanted them. This can be added within the existing API (which doesn't directly expose single response for simplicity reasons) by having a list of extensions be an arg to `add_response` in the builder and adding `single_response_extensions` to `OCSPResponse` itself (to go with its existing `extensions` method). Is there a specific set of single response extensions you see as useful?

**Comment by mathiasertl** [comment]
My OCSP responder (which is build with asn1crypto so far) only uses the certificate_issuer extension, but mainly because some tutorial suggested using that extension. I'm not sure if it's really required. 

Perhaps it would be a good thing to investigate what current responders e.g. from LetsEncrypt to. I will investigate.

**Comment by mathiasertl** [comment]
I have tested a few OCSP responders using OpenSSL 1.1.0j, the version shipping with Debian stable. I have used my own responder to verify that the tool indeed does display (Single)Response extensions.

I have tested LetsEncrypt, GoDaddy, Google, Yahoo, GeoTrust and RapidSSL.

None return any response extensions or SingleRepsonse extensions. They don't even include a Nonce!

So I am unsure how to proceed. These extensions are probably never used for validation by any real world clients, so they could be ignored. OTOH, this would enable me to implement a more complete responder, and cryptography includes some other fairly obscure extensions. So... you decide. :-)

**Comment by reaperhulk** [comment]
Yeah that is what I expected. I think for now we'll say that we're willing to accept a patch, but it won't be a priority until we find a use case where something else is using these extensions.

**Comment by hablutzel1** [comment]
You have an use case in eIDAS EU regulation as implemented in France. From https://www.ssi.gouv.fr/uploads/2019/05/eidas_issuance-qualified-certificates_v1.1_anssi.pdf:

> The ECSP must ensure the availability of the revocation status at any time and beyond the validity period
> of the certificate.
> ...
> b. if the ECSP implements an OCSP responder, the latter should:
> i. include the extension "archive cutoff", as provided in RFC 6960, with a date
> identical to the starting date of the validity of the certificate of the CA; and
> ii. keep the revocation status of the certificate available after it has expired.

**Comment by alex** [comment]
This is done: https://cryptography.io/en/latest/x509/ocsp/#cryptography.x509.ocsp.OCSPResponse.single_extensions
