### ISSUE TITLE
Recipe for single-session secure HTTPS tunnel

### ISSUE THREAD

**Issue by abitrolly** [pyca/cryptography#4665]
Arguably the best scenario for introducing people to `cryptography` is how to create a secure tunnel between two PCs for sharing confidential data. HTTPS looks logical in this context, because most people are already familiar with green lock at the address bar and various browser warnings.

How possible is it for `cryptography` to get API (as simple as possible) and recipe that show people how to build those tunnels?

The scenario is file sharing using one time `client certificate` that is generated on server and then passed to client together with URL over some external channel (QR code, ...). Client then uses the certificate to create HTTPS connection to server URL to download the file. Server should validate client certificate (by asking to sign something, not just checking fingerprint) and create encrypted connection using it. If certificate is not valid, expired, can't sign, it should fail.

If `cryptography` doesn't deal with HTTPS connection encryption, the recipe can help to clarify its role in the ecosystem.

**Comment by alex** [comment]
Cryptography does not currently have any TLS APIs, while we're interested in this, it's unlikely to be forthcoming soon.

FWIW, if this is a problem you need a solution for, https://github.com/warner/magic-wormhole is probably the best solution for a protocol for secure transport with one time secret sharing.

**Comment by abitrolly** [comment]
@alex you won't believe that, but https://github.com/warner/magic-wormhole/issues/320  :D

**Comment by alex** [comment]
We haven't taken any action on this for a year and a half. I think for now it's fair to say this is beyond the scope of the cryptographic recipes we're providing.
