### ISSUE TITLE
[Optimization request] Handle Customized ObjectIdentifier on Loading DER certificate Method

### ISSUE THREAD

**Issue by HoiPangCHEUNG** [pyca/cryptography#4675]
Hi There, I am working on a project in which I need to load a certificate using
x509.load_der_x509_certificate(data, backend) 
(see this link for description:  https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_der_x509_certificate)

It works perfectly fine in most cases, **however, when the certificate data contains cusotmized Oid**, it won't work anymore.

Could anyone please give some advice or comment? 
Thank you for your attention.

**Comment by alex** [comment]
What do you mean "doesn't work"? Can you give an example?

**Comment by alex** [comment]
Closing since there's no response. If there's more info we can reopen.
