### ISSUE TITLE
About Fernet Limitations

### ISSUE THREAD

**Issue by ivcuello** [pyca/cryptography#4677]
I was using **cryptography.hazmat.primitives.asymmetric.rsa** module to perform RSA encryption of json messages, to my surprise some of the jsons being encrypted where bigger than expected which caused me some issues with RSA encryption.

I chose to switch my encryption strategy by using RSA encryption to encrypt a random generated symmetric key which will be used to encrypt my message on each request and I was planning to use the **cryptography.fernet.Fernet** class to achieve the message encryption, while reading the docs in [https://cryptography.io/en/latest/fernet/](https://cryptography.io/en/latest/fernet/), I saw there were limitations on large file sizes, but there wasn't any size or range specified in detail. 

* How large does the content has to be in order to cause issues ?

* Is there any suggested size margin ?

* Is performance and speed the only thing to worry about ?

I did made a script to test the limitations but I didn't find anything out of the ordinary (please use python 3.6+ in order to run it if you need).

```python
import sys
import json
from datetime import datetime

from secrets import token_hex
from cryptography.fernet import Fernet

def meassure(function, **kwargs):
    """
        Measures a function execution time.
    """
    start = datetime.now()
    function(kwargs)
    end = (datetime.now() - start).microseconds // 1000
    print(f'Function finished in {end} millis')

def test_fernet(base_data: dict):
    key = Fernet.generate_key()
    f = Fernet(key)
    json_str = json.dumps(base_data).encode()
    print('Encrypting json of size {}'.format(sys.getsizeof(json_str)))
    message = f.encrypt(json_str)
    print('Decrypting string of size {}'.format(sys.getsizeof(message)))
    message = f.decrypt(message)

iterations = 1000000
base_data = { 'data': [] }

for i in range(iterations):
    base_data['data'].append(token_hex())

print('Data gen finished')
meassure(test_fernet, **{'base_data': base_data})
```

**Comment by alex** [comment]
The only limit to the size of the data Fernet can encrypt is that you need the whole string in memory, so you can't encrypt something larger than RAM (+ swap).
