### ISSUE TITLE
cryptography 2.4.2 breaks after upgrade from 2.3.1

### ISSUE THREAD

**Issue by herman0x00** [pyca/cryptography#4678]
I encountered the following error after upgrading my cryptography from 2.3.1 to 2.4.2

  File "C:\Users\Herman\Anaconda3\envs\noct\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: The specified module could not be found.

Any solutions?

**Comment by herman0x00** [comment]
I also experience the same issue on a new environment with cryptography 2.4.2 freshly installed,

**Comment by herman0x00** [comment]
This issue occurs only on Python 3.7. Python 3.6 is fine

**Comment by alex** [comment]
Closing without more information. We can reopen if you can share more details.
