### ISSUE TITLE
In FIPS mode, cryptography-2.3.1 throws error during sftp

### ISSUE THREAD

**Issue by kparamas** [pyca/cryptography#4682]
Note - FIPS mode is enabled on the setup.

Software versions:
python-2.7.5-68.el7.x86_64
cryptography-2.3.1
cffi-1.11.5-4.el7.x86_64

openssl-1.0.2k-3.el7.centos.x86_64
openssl-perl-1.0.2k-3.el7.centos.x86_64
xmlsec1-openssl-1.2.20-5.el7.x86_64
openssl-libs-1.0.2k-3.el7.centos.x86_64

**The same issue is not seen with cryptography-2.0.3**

We use paramiko to sftp a file. This below error is seen in crypto library.

paramiko-scp-1.10.2-4.el7.x86_64
paramiko-2.4.2-4.el7.x86_64

```
INFO     SFTP /var/avenda/tips/dump/config/auto-backup-tips-2019-01-11-05-21-01.tar.gz -> 10.21.5.42:/root/CP-32032/10.21.4.68/auto-backup-tips-2019-01-11-05-21-01.tar.gz
DEBUG    starting thread (client mode): 0x9b2e3f90L
DEBUG    Local version/idstring: SSH-2.0-paramiko_2.4.2
DEBUG    Remote version/idstring: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
INFO     Connected (version 2.0, client OpenSSH_7.2p2)
DEBUG    kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] server encrypt:[u'chacha20-poly1305@openssh.com', u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG    Kex agreed: ecdh-sha2-nistp256
DEBUG    HostKey agreed: ssh-ed25519
DEBUG    Cipher agreed: aes128-ctr
DEBUG    MAC agreed: hmac-sha2-256
DEBUG    Compression agreed: none
ERROR    Unknown exception: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])
ERROR    Traceback (most recent call last):
ERROR      File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 2010, in run
ERROR        self._handler_table[ptype](self, m)
ERROR      File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 2126, in _negotiate_keys
ERROR        self.kex_engine.start_kex()
ERROR      File "build/bdist.linux-x86_64/egg/paramiko/kex_ecdh_nist.py", line 32, in start_kex
ERROR        self._generate_key_pair()
ERROR      File "build/bdist.linux-x86_64/egg/paramiko/kex_ecdh_nist.py", line 53, in _generate_key_pair
ERROR        self.P = ec.generate_private_key(self.curve, default_backend())
ERROR      File "/usr/lib64/python2.7/site-packages/cryptography-2.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/primitives/asymmetric/ec.py", line 287, in generate_private_key
ERROR        return backend.generate_elliptic_curve_private_key(curve)
ERROR      File "/usr/lib64/python2.7/site-packages/cryptography-2.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1338, in generate_elliptic_curve_private_key
ERROR        self.openssl_assert(res == 1)
ERROR      File "/usr/lib64/python2.7/site-packages/cryptography-2.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 105, in openssl_assert
ERROR        return binding._openssl_assert(self._lib, ok)
ERROR      File "/usr/lib64/python2.7/site-packages/cryptography-2.3.1-py2.7-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py", line 76, in _openssl_assert
ERROR        errors_with_text
ERROR    InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])
ERROR    
ERROR    Failed to sftp/scp report:Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])
```

**Comment by kparamas** [comment]
Even pip update cryptography throws similar error:

sh-4.2# pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 602kB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.2
    Uninstalling pip-8.1.2:
      Successfully uninstalled pip-8.1.2
Successfully installed pip-18.1
sh-4.2# pip install idna
Requirement already satisfied: idna in /usr/lib/python2.7/site-packages (2.8)
sh-4.2# pip install --upgrade cryptography
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/cryptography/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/cryptography/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/cryptography/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/cryptography/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/cryptography/
Could not fetch URL https://pypi.org/simple/cryptography/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/cryptography/ (Caused by SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)) - skipping
Requirement already up-to-date: cryptography in /usr/lib64/python2.7/site-packages/cryptography-2.3.1-py2.7-linux-x86_64.egg (2.3.1)
Requirement already satisfied, skipping upgrade: idna>=2.1 in /usr/lib/python2.7/site-packages (from cryptography) (2.8)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages/asn1crypto-0.22.0-py2.7.egg (from cryptography) (0.22.0)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in /usr/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from cryptography) (1.10.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.7 in /usr/lib64/python2.7/site-packages/cffi-1.11.5-py2.7-linux-x86_64.egg (from cryptography) (1.11.5)
Requirement already satisfied, skipping upgrade: enum34 in /usr/lib/python2.7/site-packages/enum34-1.1.6-py2.7.egg (from cryptography) (1.1.6)
Requirement already satisfied, skipping upgrade: ipaddress in /usr/lib/python2.7/site-packages/ipaddress-1.0.16-py2.7.egg (from cryptography) (1.0.16)
Requirement already satisfied, skipping upgrade: pycparser in /usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography) (2.14)

**Comment by reaperhulk** [comment]
@kparamas The error `FIPS_drbg_generate:not instantiated` strongly implies that the FIPS mode RNG has not been started. Cryptography doesn't use FIPS mode at all by default (and runs a custom ENGINE that replaces the OpenSSL RNG with the OS-provided one to provide fork safety), so are you doing something like calling `FIPS_mode_set` somewhere?

**Comment by alex** [comment]
No response, will reopen if there's something for us to do here.

**Comment by kparamas** [comment]
@reaperhulk - We set FIPS mode in the grub2 conf. Is there an additional place where FIPS_mode_set should be called for the cryptography library? 
How to enable FIPS mode here?

Tried updating to latest cryptography-2.4.2, but still seeing this error.

sh-4.2# rpm -qa | grep cryptog
cryptography-2.4.2-4.el7.x86_64

        linux16 /vmlinuz-3.10.0-514.26.2.aruba.el7.x86_64 root=UUID=7789b292-0b7c-4dfd-92ef-2e72ef017f67 ro panic=30 console=tty0 console=ttyS0,9600n8 fips=1 boot=/dev/sda1 clocksource= clocksource_failover=acpi_pm pcie_aspm=off selinux=0 crashkernel=auto biosdevname=0 net.ifnames=1 rhgb LANG=en_US.UTF-8 nomodeset
        initrd16 /initramfs-3.10.0-514.26.2.aruba.el7.x86_64.img

**Comment by kparamas** [comment]
Another setup, where fips is enabled. Check fips mode returns true. So, it is initialized.  

sh-4.2# ./fips-test.py 
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2

OPENSSL_VERSION: OpenSSL 1.0.1e-fips 11 Feb 2013
FIPS_mode(): 1
FIPS_mode(): 1
SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
Traceback (most recent call last):
  File "./fips-test.py", line 35, in <module>
    print("MD5: {:s}".format(hashlib.md5(text).hexdigest()))
ValueError: error:060A80A3:digital envelope routines:FIPS_DIGESTINIT:disabled for fips

InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])

**Comment by reaperhulk** [comment]
MD5 is not a valid algorithm in FIPS mode, so that will never work.

**Comment by reaperhulk** [comment]
But you're also seeing a problem when not using MD5? Can you show us code that can replicate the issue? (If we can do it in a CentOS docker container that would be great)

**Comment by kparamas** [comment]
Right. That is expected. We are not using MD5 now. Still we see this issue.
How to fix this not instantiated?

InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])

**Comment by kparamas** [comment]
> But you're also seeing a problem when not using MD5? Can you show us code that can replicate the issue? (If we can do it in a CentOS docker container that would be great)

Note: I have applied this patch in paramiko-2.4.2 to avoid using MD5 for get fingerprint:
Paramiko patch - https://github.com/paramiko/paramiko/pull/1103/commits/8e0b7ef85fc72d844dee80688060001a3fba8ad0

**Comment by kparamas** [comment]
This is the code snippet. It fails in ssh.connect line 198.
Sorry I don't have a docker to show this. Can I attach my rpms?

sh-4.2# rpm -qa | grep bcrypt
python-bcrypt-3.1.4-1.x86_64
sh-4.2# rpm -qa | grep nacl
python-pynacl-1.2.1-1.x86_64
sh-4.2# rpm -qa | grep cryptography
cryptography-2.0.3-4.el7.centos.x86_64
sh-4.2# rpm -qa | grep paramiko
paramiko-scp-1.10.2-4.el7.centos.x86_64
paramiko-2.4.2-4.el7.centos.x86_64

```
190     def execute(self, req_id, cmds):
191         """ Execute given commands over SSH. """
192         log.debug('r:%s SSH %s => %s', req_id, cmds, self.ip)
193         with eventlet.Timeout(self.timeout):
194             ssh = paramiko.SSHClient()
195             try:
196                 t0 = time.time()
197                 ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
198                 ssh.connect(self.ip, username=self.host.username, password=self.host.password, timeout=self.conn_timeout)
199                 t = self.time_since(t0)
200                 if t > self.WARN_TIME_LIMIT:
201                     log.warn('r:%s ssh connect ip:%s took %.3f sec', req_id, self.ip, t)
202 
203                 if len(cmds) == 1:
204                     self._exec(ssh, cmds[0], req_id)
205                 else:
206                     self._multi_exec(ssh, cmds, req_id)
207 
208                 log.debug('r:%s SSH cmds => %s completed ', req_id, self.ip)
209             finally:
210                 self.ssh_close(ssh)
```

Error:

line 198, in execute
    ssh.connect(self.ip, username=self.host.username, password=self.host.password, timeout=self.conn_timeout)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 397, in connect
    t.start_client(timeout=timeout)
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 587, in start_client
    raise e
InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=755437694L, lib=45, func=113, reason=126, reason_text='error:2D07107E:FIPS routines:FIPS_drbg_generate:not instantiated')])

**Comment by kparamas** [comment]
Also a simple pip install would also fail:

sh-4.2# curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1660k  100 1660k    0     0   290k      0  0:00:05  0:00:05 --:--:--  394k
sh-4.2# python get-pip.py 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)': /simple/pip/
  Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError("bad handshake: Error([('FIPS routines', 'FIPS_drbg_generate', 'not instantiated'), ('SSL routines', 'ssl3_send_client_key_exchange', '')],)",),)) - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
