### ISSUE TITLE
Can I use the rsa key of pkcs#12 for SHA1withRSA signature?

### ISSUE THREAD

**Issue by zoujinbin** [pyca/cryptography#4686]
Hello~ I hava a rsa key pair of pkcs#12(corresponding private key file is "test.pfx", public key file is "test.cer"). And now I want to use the rsa key to signature and verify. What should I do for it?

**Comment by alex** [comment]
Beginning with version 2.5 (not yet released), you can load a PKCS12 key: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#pkcs12
