### ISSUE TITLE
ffi.gc Callback/RuntimeError Warnings

### ISSUE THREAD

**Issue by FlorianSauer** [pyca/cryptography#4738]
Hello, i'm currently having an issue with "strange error messages" randomly printed in my program.
I'm having this issue on 3 different platforms and can't really find the error source.
Im guessing its some kind of garbage collection mechanism thats having issues with (maybe) rsa objects.

The Error messages look like this:

```
From callback for ffi.gc <cdata 'EVP_CIPHER_CTX *' 0x64607480>:
RuntimeError: maximum recursion depth exceeded while calling a Python object
From callback for ffi.gc <cdata 'EVP_PKEY *' 0x6460e390>:
RuntimeError: maximum recursion depth exceeded while calling a Python object
From callback for ffi.gc <cdata 'RSA *' 0x64604140>:
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Im having this issue on 3 different machines.

- a Raspberry with Raspbian
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
$ python --version
Python 2.7.9
```

- an Ubuntu machine
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
$ python --version
Python 2.7.12
```

- a Surface Book with Windows 10 Pro Version 1803
```
$ python --version
Python 2.7.15
```

All devices use Cryptography Version 2.5, installed with root/administrator privileges via pip.

I don't really know where this error comes from, because i never see any tracebacks or other hints.
The error messages just sort of "pop up".
My code is very close to the docs-examples ([https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/)).

Is it possible to produce this kind of error messages with the RSA modules with more or less the same code as from the docs-examples?
Is this a Bug?

**Comment by reaperhulk** [comment]
This could possibly be a bug, but we need some code that can actually replicate it before we can investigate. Do you have a way to build a reduced test case that shows this behavior?

**Comment by FlorianSauer** [comment]
I was finally able to create a test case that triggered the error messages.

Basicly a not fully functioning proxy object caused an attribute lookup loop.
The garbage collector tried to lookup attributes of a storage object, which was behind/inside the proxy object.
However this only happens when i use cryptography objects. When i store 'normal' python objects this error does not occur.

Here is a link to a GIST with the test code.
[https://gist.github.com/FlorianSauer/3bfcbf2bcb5bee4e580260b4dc266887](https://gist.github.com/FlorianSauer/3bfcbf2bcb5bee4e580260b4dc266887)

**Comment by alex** [comment]
Starting looking at this, initial minimization of the test case:

```py
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa


class KeyStorage(object):
    """
    Object to store RSA public and private keys
    """
    def __init__(self, public=None, private=None):
        self.public = public
        self.private = private


class ProxyObject(object):
    """
    Proxy object with State Pattern
    """

    def __init__(self, storage):
        self.storage = storage
        self.all_states = (storage, self)

    def __getattr__(self, attr):
        return self.storage.__getattribute__(attr)

    def __setattr__(self, name, value):
        if hasattr(self, 'storage') and hasattr(self.storage, name):
            return setattr(self.storage, name, value)
        return super(ProxyObject, self).__setattr__(name, value)


class TestApp(object):
    """
    Test for cryptography issue "ffi.gc Callback/RuntimeError Warnings #4738"
    https://github.com/pyca/cryptography/issues/4738
    """

    def __init__(self):
        self.server_private_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=1024,
            backend=default_backend()
        )
        self.server_public_key = self.server_private_key.public_key()
        self.server_private_key_pem = self.server_private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption()
        )
        self.server_public_key_pem = self.server_public_key.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo)

    def test_threaded_cryptography_objects(self):
        context = ProxyObject(KeyStorage())
        context.private = serialization.load_pem_private_key(
            self.server_private_key_pem, password=None,
            backend=default_backend())
        context.public = serialization.load_pem_public_key(
            self.server_public_key_pem, backend=default_backend())

    def test_rsa_proxy(self):
        for i in xrange(100):
            self.test_threaded_cryptography_objects()


if __name__ == "__main__":
    app = TestApp()
    app.test_rsa_proxy()
```
