### ISSUE TITLE
Cannot encrypt and decrypt without IV (initialization vector key)

### ISSUE THREAD

**Issue by dgofman** [pyca/cryptography#4742]
Hi, OpenSSL supporting aes-256-cbc encryption without iv and with -nosalt argument.

echo cryptography | openssl enc -e -aes-256-cbc -nosalt -a -k S3kr3tK3y
>>>   IUwZy4DjcPGmzLG9/EOJNQ==

echo IUwZy4DjcPGmzLG9/EOJNQ== | openssl enc -d -aes-256-cbc -nosalt -a -k S3kr3tK3y
>>>  cryptography

I used NodeJS library for encrypt/decrypt my password.

```
var crypto = require('crypto'),
	algorithm = 'aes-256-cbc';

encrypt: function(str, encrypt_passwd) {
		var cipher = crypto.createCipher(algorithm, encrypt_passwd);
		return cipher.update(str, 'utf8', 'base64') + cipher.final('base64');
},

decrypt: function(str, encrypt_passwd) {
		var decipher = crypto.createDecipher(algorithm, encrypt_passwd);
		return decipher.update(str, 'base64','utf8') + decipher.final('utf8').trim();
},
```

How can I execute the same encryption algorithm using Python library?

**Comment by alex** [comment]
There is no such thing as using CBC mode without an IV. These libraries must be providing some sort of default IV (which is generally not secure), you'll have to figure out what their default is.

**Comment by dgofman** [comment]
The library exists however you are not supporting.  http://oldmanlab.blogspot.com/2014/12/ios-decrypting-aes-http-data.html

**Comment by dgofman** [comment]
Or using des-ede. https://jiavictor.wordpress.com/2017/05/26/generate-same-3des-aes-128-aes-256-encrypted-message-with-python-php-java-and-openssl/

**Comment by reaperhulk** [comment]
This library supports AES CBC (which *always* requires an IV, there is no exception). Your issue is that you need to determine exactly how your particular situation is using AES CBC so you can perform the same operation with this library. It is unreasonable to ask the authors of this library to research and determine what your interoperability issue is. You will need to look at the source code to figure it out yourself.

We *also* support 3DES EDE, so again, you'll need to figure this out yourself.

**Comment by dgofman** [comment]
Please, can you give me a bit of advice and sample what algorithm should I use?
Our admin team during the production deployment will encrypt the "password" for the production database using "some magic key". The "encrypted password" and "magic key" will be pass to Python application via command line. I need to decrypt the password at runtime. Before I used "-aes-256-cbc -nosalt" in my nodejs applications. What should I use in Python. The secret key should be simple not HEX value or IV.

**Comment by alex** [comment]
Figuring out your interoperability problems is not part of the scope of this project.

**Comment by dgofman** [comment]
So you cannot support existing feature from Crypto.Cipher import AES library. I already using your library in my code for JWT token generation. I will prefer using only one crypto library in my code. 

https://joelinoff.com/blog/?p=885

**Comment by dgofman** [comment]
Plus I cannot install pycrypto on Windows OS without Visual Studio. That reason why I am using  cryptography

**Comment by alex** [comment]
We fully provide AES-CBC mode. What we do not do provide is figuring out your interoperability requirements.
