### ISSUE TITLE
OCSP: support overriding produced_at

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#4746]
Please support setting the produced_at flag for OCSP-responses.

`OCSPResponseBuilder` currently does not allow setting `produced_at` according to the documentation. Instead, it's set to the current UTC time during signing. 

For some reason, even setting the current time with freezegun does not affect the produced_at flag, setting the real current time instead. This makes it impossible to test this property in the test-suite. Additionally, it seems sensible to set this to the same value as the `this_update` property, but my test-suite shows that this is occasionally off by a single second (without using freezegun of course).

**Comment by mathiasertl** [comment]
Damn! I'll file an issue with OpenSSL.

**Comment by alex** [comment]
Please do share a link when you file it.
