### ISSUE TITLE
expose AES GCM example outside of hazmat

### ISSUE THREAD

**Issue by graingert** [pyca/cryptography#4749]
the Cryptography docs have a really nice example of how to correctly implement AES-GCM encrypt/decrypt it would be handy if this was exposed as a function outside of `hazmat` akin to Fernet.

https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.modes.GCM

see also: https://github.com/pyca/cryptography/issues/2493

**Comment by reaperhulk** [comment]
As mentioned in the PR while the example is a good one, we don't actually want to expose this outside of hazmat. We have the `aead` implementation as a safer one-shot, but the API still requires you to pick a `nonce`. While this was a deliberate choice, it does mean that there exists a failure mode where users re-use `nonce` with catastrophic results. Additionally, GCM is a fragile mode in general and without significantly more mitigation (through the use of framing and per-frame key derivation) I don't believe it is sufficiently safe for a recipe.
