### ISSUE TITLE
generate_elliptic_curve_private_key() generates a 62 byte key for the same curve

### ISSUE THREAD

**Issue by dpradha** [pyca/cryptography#4751]
I am relatively new to this library. The generate_elliptic_curve_private_key() get's a ec.SECP256K1() curve. Most of the times, when I call this function I get a 32 bytes key. However, a couple of times, I get a 62 byte key with the same curve.

`
from cryptography.hazmat.backends.openssl.backend import Backend
`
`
private_key = self.backend.generate_elliptic_curve_private_key(ec.SECP256K1())
`

Does anyone have an idea as to what might be causing this anomaly?

**Comment by reaperhulk** [comment]
What do you mean you get a 32 byte key? We provide no API for directly obtaining the private scalar in that fashion so some example code would be useful here.

**Comment by alex** [comment]
No additional information after several days. We'll happily reopen this once there's more details.
