### ISSUE TITLE
ImportError when importing hashes

### ISSUE THREAD

**Issue by renatoliveira** [pyca/cryptography#4770]
I am getting the following error when trying to import `hashes` into one of my scripts.

    Traceback (most recent call last):
    File "src/keygen.py", line 2, in <module>
        from cryptography.hazmat.primitives.asymmetric import hashes
    ImportError: cannot import name 'hashes' from 'cryptography.hazmat.primitives.asymmetric' (/Users/renatoliveira/Documents/GitHub/mytelegrambot/botenv/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/__init__.py)

The script starts with:

    import argparse
    from cryptography.hazmat.primitives.asymmetric import hashes #import fails here
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.primitives import serialization, padding
    from cryptography.hazmat.backends import default_backend

Python 3.7.2 on macOS 10.14.3.
cryptography is 2.5
cffi is 1.12.1
pip is 19.0.3
setuptools is 40.8.0

If it helps, running LibreSSL 2.8.3.

Python installed using homebrew, everything else using pip.

Steps to reproduce:

1. Create a folder in the desktop.
2. Create a virtual env.
3. Install the library.
4. Write the script.
5. Try to run it in a terminal.

---

Could really use some help here. I honestly don't know if this is an issue with the library or some dependency, like `six`.

I added Pdb on asymmetric's __init__ file to see if I could get a hint on what is going on, and all I could get is a "KeyError" during the execution:

    (Pdb) s
    KeyError: 'six'
    > <frozen importlib._bootstrap>(166)_get_module_lock()

**Comment by alex** [comment]
What version of virtualenv are you using to create the venv?

**Comment by renatoliveira** [comment]
Sorry, should've specified that in the original post:

I'm creating the virtual environment using Python's recommended way: ```python3 -m venv <venvdir>```.

**Comment by alex** [comment]
Oh, wait the problem is that `hashes` isn't in `cryptography.hazmat.primitives.asymmetric`, it's in `cryptography.hazmat.primitives`.

Is there some documentation that told you it was in asymmetric?

**Comment by renatoliveira** [comment]
I believe I must've either misread it on some documentation, or I'm too tired and didn't pay attention to that, or VSCode messed with me in this one when Intellisense showed "hashes" as an option. Clearly now I understand that it was referencing the "hashes" call I needed.

So, yeah: do your imports first, then write your code. 

Thank you :)
