### ISSUE TITLE
ValueError: Unable to load certificate -- TRUSTED certificates are not supported

### ISSUE THREAD

**Issue by matinats** [pyca/cryptography#4794]
Hi,

I would like to know whether there is limitation to the size of a certificate file that can be loaded.
I have a very big certificate of 5684 lines, and the command `x509.load_pem_x509_certificate(data, default_backend()) fails with ValueError: Unable to load certificate.

````
import re
from cryptography import x509
from cryptography.hazmat.backends import default_backend
path = "/root/cert.crt"
with open(path, 'rb') as cert_file:
    data = cert_file.read()
s = re.sub(r'(?m)^\#.*\n?', '', data)
cert = x509.load_pem_x509_certificate(s, default_backend())
````

Also, I can parse it successfully with the command line `openssl x509 -noout -text -in /root/cert.crt`.

My cert.crt has this [FILE TYPE]:
```
-----BEGIN TRUSTED CERTIFICATE-----
...
-----END TRUSTED CERTIFICATE-----
```

It is feature of openssl: https://www.openssl.org/docs/man1.0.2/man1/x509.html
However, it is not part of the allowed [FILE TYPES]  in: https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file

So, trusted certificates are not supported.

adding this  line:
```
s = s.replace('TRUSTED ','')
```
It successfully loads the certificate.
Could these "TRUSTED" certificates be supported?

cffi==1.10.0
cryptography==2.2.2
pip 9.0.1 
python 2.7

**Comment by alex** [comment]
`load_pem_x509_certificate` takes a string with a single cert in it, not a chain.

**Comment by matinats** [comment]
The "TRUSTED" in the header was the issue, not the chain.

**Comment by alex** [comment]
Great, glad you were able to figure it out.

**Comment by matinats** [comment]
o, are the "trusted" certificates going to be supported?

**Comment by reaperhulk** [comment]
We have no plans to add support for this format at this time due to its rarity and non-standard nature.
