### ISSUE TITLE
Cryptography installation failure

### ISSUE THREAD

**Issue by Juniortheone** [pyca/cryptography#4797]
I tried installing cyptography but this is the error message I got;
> Traceback (most recent call last):
File "/home/vagrant/.local/bin/pip",line 7, in <module>
   from pip._internal import main
ImportError: No module named_internal

I have tried suggested solutions in similar issues but to no avail. I have tried the installation tips in the installation documents but to no avail as well.
Below are some of the commands I tried:
apt-get update
apt-get -y upgrade
apt-get install -y build-essential
apt-get install -y python2.7-dev
apt-get install -y python-pip
apt-get install -y libffi-dev
apt-get install -y libssl-dev
pip install --upgrade pip
pip install cryptography

>apt-get install build-essential libssl-dev libffi-dev python-dev

They are similar but I tried it all anyway and I also checked on google but I got similar solutions.Unfortunately,it's still not working. I tried to view the file to see what was on line 7 but I got the same error above so my guess is that it's not a cryptography problem.I checked on pip but no working solution as well.Any help will be greatly appreciated.Thanks.

System:Ubuntu 16.04.6,python2.7,running in vagrant

**Comment by alex** [comment]
This isn't a cryptography bug, your pip installation is corrupted somehow. Probably as a result of installing it with apt and then upgrading it with pip.

**Comment by Juniortheone** [comment]
@alex do you have any suggestions that can help?
