### ISSUE TITLE
Couldn't able to use fernet

### ISSUE THREAD

**Issue by kirankotari** [pyca/cryptography#4801]
I found the below code in the documentation, I have installed `cryptography 2.6.1` which is not accepting `from cryptography.fernet` I am getting following error: 
```
    self._encrypt = cryptography.fernet.Fernet(self.get_hash(self._key))
AttributeError: module 'cryptography' has no attribute 'fernet'
```
```
>>> from cryptography.fernet import Fernet, MultiFernet
>>> key1 = Fernet(Fernet.generate_key())
>>> key2 = Fernet(Fernet.generate_key())
>>> f = MultiFernet([key1, key2])
>>> token = f.encrypt(b"Secret message!")
>>> token
b'...'
>>> f.decrypt(token)
b'Secret message!'
```

**Comment by reaperhulk** [comment]
How are you importing in the first code snippet? `cryptography.fernet.Fernet` implies you're trying `import cryptography` but the base package doesn't automatically import its children. You'll need to do `from cryptography import fernet` and then `fernet.Fernet` or `from cryptography.fernet import Fernet` and you can directly call `Fernet` then.
