### ISSUE TITLE
Allow bytearray in padding and unpadding

### ISSUE THREAD

**Issue by gotyaoi** [pyca/cryptography#4805]
It looks like in the padding code, it requires the data passed to padding and unpadding to be bytes, and does not allow bytearray's. I saw in #4409 that bytes like objects were allowed as key material and such, does it make sense to allow them to be given to padders and unpadders? If so, I think it's just two instances of `_check_bytes` that would need to changed to `_check_byteslike` in https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/primitives/padding.py, line 43 and 67.

**Comment by alex** [comment]
Allowing buffers in padding seems reasonable -- though it's kind of pointless unless we change the internals of the padders, which would make tons of copies as currently written.

**Comment by gotyaoi** [comment]
I don't quite follow?

**Comment by alex** [comment]
The point of allowing buffers is that you can clear the memory, and thus be resillient to memory disclosure vulnerabilities.

Right now our padding implementation makes many copies of the memory, so even if the caller cleared _their_ copy, you wouldn't be secure against a disclosure vulnerability. Therefore we'e need to refactor the implementation to not make so many copies before we should support passing buffers.

**Comment by gotyaoi** [comment]
Ah, I see. I admit, I was only thinking of convenience in this case, after passing a bytearray to a padder and being rejected.
