### ISSUE TITLE
Cryptography test error

### ISSUE THREAD

**Issue by Juniortheone** [pyca/cryptography#4807]
I installed cryptography and run the test but this is what I got which is obviously not the expected outcome
![Screenshot from 2019-03-12 07-05-33](https://user-images.githubusercontent.com/44960997/54181306-06b7c200-4496-11e9-824a-9fbf24f50da2.png)
Python 2.7
Cryptography 2.6

**Comment by reaperhulk** [comment]
Nothing in that output appears to have anything to do with our package. It instead appears to be complaining about a missing package named `vlan` or `vconfig`. What makes you think this is a cryptography error?

**Comment by Juniortheone** [comment]
I installed cryptography and I got a message that it was successfully installed but when I run the test to check its operability, I got an error. I don't know if it's a cryptography error or not. All I was hoping for was a fix. Thank you.

**Comment by reaperhulk** [comment]
What test? It looks like you're running something using `pexpect`, so you'll want to report errors to them, but again, this error appears to describe exactly what you need to do (install either `vlan` or `vconfig` based on which distro you're running). Good luck!
