### ISSUE TITLE
OpenSSL version detected is incorrect -> spurious warnings

### ISSUE THREAD

**Issue by jbrockmendel** [pyca/cryptography#4809]
xref #3043 

Logfiles are filled with apparently-spurious warning messages:

```
$ pip list | head  # any pip call causes this
/home/pi/.local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
```

so cryptography thinks that OpenSSL is version 1.0.1, but:

```
$ openssl version
OpenSSL 1.1.0j  20 Nov 2018
```

Versions:
py2.7.13
cryptography 2.6.1
linux 4.1.19
debian9.8 (raspbian)
armv6l (32bit)

LMK if I missed anything.

**Comment by alex** [comment]
How did you install cryptography?

What does `python -c "from cryptography.hazmat.backends.openssl import backend; print(backend.openssl_version_text())` print?

**Comment by jbrockmendel** [comment]
> How did you install cryptography?

sudo pip

```
$ python -c "from cryptography.hazmat.backends.openssl import backend; print(backend.openssl_version_text())
OpenSSL 1.0.1t  3 May 2016
```

**Comment by alex** [comment]
As that indicatse, your copy of cryptography is linked against OpenSSL 1.0.1t. Did you install cryptography recently?

**Comment by jbrockmendel** [comment]
> Did you install cryptography recently?

The original installation was a couple years ago.  I recently did a round of "pip install --upgrade"/"apt-get --upgrade"/"apt-get dist-upgrade"s

**Comment by alex** [comment]
It looks to me like you're still using your installation from a few years ago, linked against whatever OpenSSL you had then probably.

My suggestion would be to completely uninstall cryptography and start fresh.

**Comment by jbrockmendel** [comment]
> My suggestion would be to completely uninstall cryptography and start fresh.

I did that moments ago and got the same result.

Could it be a `wheel` thing or something using pre-compiled (and so pre-linked) code instead of doing it fresh?

**Comment by alex** [comment]
If you had a cached wheel that was linked against OpenSSL 1.0.1t, that would certainly do it.

**Comment by alex** [comment]
FWIW, it is our _strong_ recommendation not to globally install things with `sudo pip` because it tends to produce very difficult to debug situations.

**Comment by jbrockmendel** [comment]
welp, doing a pip install with `--no-cache-dir` fixed the issue on one of the Pis, but not the other.  Will report back if I learn anything more.

**Comment by alex** [comment]
Great. For now I'm going to close this as there doesn't seem to be any pyca/cryptography bug here, will reopen if there's reason to reconsider that.
