### ISSUE TITLE
UnicodeEncodeError in x509 name (Python 2.7)

### ISSUE THREAD

**Issue by kulikjak** [pyca/cryptography#4810]
I recently updated cryptography from 2.1.4 to 2.5 (Python 2.7) and now I am getting UnicodeEncodeError errors. Here is shortened traceback:

```
.....
  File "/usr/lib/python2.7/vendor-packages/cryptography/x509/name.py", line 258, in __repr__
    return "<Name({0})>".format(self.rfc4514_string())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 38: ordinal not in range(128)
```

The actual line it's trying to encode is here:
```C=CO,O=Sociedad Cameral de Certificación Digital - .....```.

I checked the previous version and there is a change from `list(self)` to `self.rfc4514_string()` and the string is automatically escaped to `Sociedad Cameral de Certificaci\xf3n Digital`. I tried to add `.encode('utf-8')` and it looked like it fixed the problem, but I don't understand this library and exactly how this string is used, and so I don't know if it's a correct fix.

**Comment by reaperhulk** [comment]
We clearly shouldn't error generating a repr. We could just do `{0!r}` to have it insert the unicode repr. Thanks for the report, we'll get this fixed.

**Comment by kulikjak** [comment]
Thank you - change you proposed works.
