### ISSUE TITLE
osrandom_engine dosn't use SYS_getrandom in Linux

### ISSUE THREAD

**Issue by kwist-sgr** [pyca/cryptography#4815]
> $ uname -a
Linux host 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools`` you're using
Python: 2.7, 3.5, 3.6

* How you installed ``cryptography``
via pip

* Clear steps for reproducing your bug
> $ mkvirtualenv test-2
> $ pip install cryptography
> $ pip list
asn1crypto    0.24.0 
cffi          1.12.2 
cryptography  2.6.1  
enum34        1.1.6  
ipaddress     1.0.22 
pip           19.0.3 
pkg-resources 0.0.0  
pycparser     2.19   
setuptools    40.8.0 
six           1.12.0 
wheel         0.33.1
> $ python
```python
>>> from cryptography.hazmat.backends.openssl.backend import Backend
>>> backend = Backend()
>>> backend.osrandom_engine_implementation()
u'/dev/urandom'
>>> backend._ffi.string(backend._lib.Cryptography_osrandom_engine_name).decode('ascii')
u'osrandom_engine /dev/urandom'
```

But SYS_getrandom available:
```c
// test_getrandom.c
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/syscall.h>
#include <linux/random.h>

int main(int arg, char *argv[])
{
    char dest[1];
    long n = syscall(SYS_getrandom, dest, sizeof(dest), 0);
    int e = errno;
    if (n == sizeof(dest)) {
        printf("works: %d\n", dest[0]);
    };
    printf("n=%ld, errno=%d\n", n, e);
    return 0;
}
```
> $ gcc -o test_getrandom test_getrandom.c
> $ chmod a+x test_getrandom
> $ ./test_getrandom 
works: 48
n=1, errno=0

**Comment by reaperhulk** [comment]
Did you install cryptography from source or via the `manylinux1` wheel? Due to the sheer age of `manylinux1` it does compile using `getrandom`. `manylinux2010` will resolve this but isn't ready yet.

**Comment by kwist-sgr** [comment]
> Did you install cryptography from source or via the `manylinux1` wheel? Due to the sheer age of `manylinux1` it does compile using `getrandom`. `manylinux2010` will resolve this but isn't ready yet.

How i can check this?

I use installing via pip (it means install via the wheel manylinux1?)
> $ pip install cryptography

**Comment by reaperhulk** [comment]
Yeah if you have a newer pip and aren't on alpine linux then you'll have the manylinux1 wheel. It'd probably be useful for us to add a simple command to check, but this will tell you:

```
python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend._ffi.string(backend._lib.X509_get_default_cert_file()))"
```

If the output is "/opt/pyca/cryptography/openssl/cert.pem" then you're using `manylinux1`.

If you want it to use `SYS_getrandom` you'll need to compile cryptography yourself. You can do this via the instructions on our [install](https://cryptography.io/en/latest/installation/#building-cryptography-on-linux) page, but be aware that you'll also lose access to some features like ed25519/ed448 signing unless your distro is running the absolute latest OpenSSL.

**Comment by reaperhulk** [comment]
https://github.com/pyca/cryptography/pull/4816 should actually resolve this in the future such that we attempt to use SYS_getrandom even with a manylinux1 wheel.
