### ISSUE TITLE
PrecertPoison ExtensionOID  has no name

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#4817]
In cryptography 2.6.1, the PrecertPoison extension has no name defined:

```
>>> import cryptography
>>> cryptography.__version__
'2.6.1'
>>> from cryptography.x509.oid import ExtensionOID
>>> ExtensionOID.KEY_USAGE
<ObjectIdentifier(oid=2.5.29.15, name=keyUsage)>
>>> ExtensionOID.PRECERT_POISON
<ObjectIdentifier(oid=1.3.6.1.4.1.11129.2.4.3, name=Unknown OID)>
```

**Comment by reaperhulk** [comment]
We should add that to `x509.oid._OID_NAMES`. Are you aware of a camelCase style name? I don't see one in the typical OID registries. Hooray non-canonical friendly names...

**Comment by mathiasertl** [comment]
> Are you aware of a camelCase style name?

If you mean if I'm aware of a standard that mandates these names: I'm not aware of any.

btw, maybe a good idea: write a test that loops over all `ExtensionOID` members and see if it's in `OID_NAMES`.
