### ISSUE TITLE
Create SCTs in Python?

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#4820]
I cannot figure out how to create a `cryptography.x509.certificate_transparency.SignedCertificateTimestamp` object. It seems to me as if the constructor implementation is just missing. The test-suite also only instantiates such objects by loading them from an existing certificate.

This makes it impossible to add the extension to a newly created certificate. If there is indeed just the constructor missing, I would happily write a pull request.

All of these fail:

```
>>> from cryptography import x509
>>> from cryptography.x509 import certificate_transparency as ct
>>> ct.SignedCertificateTimestamp(version=ct.Version.v1, log_id=b'1', timestamp=datetime.utcnow(), entry_type=ct.LogEntryType.PRE_CERTIFICATE)
TypeError: SignedCertificateTimestamp() takes no arguments
>>> ct.SignedCertificateTimestamp(ct.Version.v1, b'1', datetime.utcnow(), ct.LogEntryType.PRE_CERTIFICATE)
TypeError: SignedCertificateTimestamp() takes no arguments
```

Maybe I'm overlooking something, but I wasn't able to find anything, apologies if I missed something in the documentation.

**Comment by reaperhulk** [comment]
We are tracking encoding SCTs in #4531. It's not just the constructor missing, unfortunately.
