### ISSUE TITLE
Error to read certificate file

### ISSUE THREAD

**Issue by rogeriocdluiz** [pyca/cryptography#4828]
I have a certificate file and i read it with:

>>> file = open("/tmp/certificate_file.pem","r")
>>> cert = file.read()

In cert variable i got the certificate.

>>> cert

'-----BEGIN CERTIFICATE-----\nMIIHCDCCBPCgAwIBAgIIMKvzX2nqL+4wDQYJKoZIhvcNAQENBQAwczEfMB0GA1UE\nAwwWQUMgRXF1aXBhbWVudG9zIE1QRiB2MDE1MDMGA1UECwwsQXV0b3JpZGFkZSBD
.........
\nU08VkJ9Zz7PUugqJuK5oA+Z5qZB01FYvxev9Pv1LfpnuDGQboeQ8kse1M2UR/Qf5\n4o4h3YQnVZXPJTSdgfXADHsFdkI8ifZJN4BKiA==\n-----END CERTIFICATE-----\n'

than i do:

>>> certificado = x509.load_pem_x509_certificate(cert, default_backend())

and i got a following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rogeriol/.local/lib/python3.5/site-packages/cryptography/x509/base.py", line 50, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/home/rogeriol/.local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1163, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/home/rogeriol/.local/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 462, in _bytes_to_bio
    data_ptr = self._ffi.from_buffer(data)
TypeError: from_buffer() cannot return the address of a unicode object

----------------------------------------------------

I can parse certificate  with the command line (openssl x509 -noout -text -in <file.pem>)

**Comment by alex** [comment]
I'm guessing you are using python3. You must pass `bytes`, not `unicode` to `load_pem_x509_certificate`. You'll need to either open the file in bytes mode, or re-encode the contents before passing it to our APIs.

**Comment by rogeriocdluiz** [comment]
Thank you. 
 I re-encode file content with:

cert = file_cert.encode('raw_unicode_escape')
