### ISSUE TITLE
Deadlock while using hazmat

### ISSUE THREAD

**Issue by vovanec** [pyca/cryptography#4837]
I don't think it is fixed, neither 1.6 nor latest 2.6.1 version. I'm still seeing hang when running the test script provided in bug report.

_Originally posted by @vovanec in https://github.com/pyca/cryptography/issues/2911#issuecomment-482275293_

**Comment by vovanec** [comment]
And, suggested work around seems to be magically helping:

import cryptography.hazmat.backends.openssl.backend
cryptography.hazmat.backends.openssl.backend.activate_builtin_random()

**Comment by vovanec** [comment]
I've run into exactly the same issue as described in the original bug report (https://github.com/pyca/cryptography/issues/2911) when was dealing with random hangs in our production environment. Please let me know what information you need from my side.

**Comment by alex** [comment]
What code do you need to reproduce this? Does the script from the original project work for you? And on which OS?

**Comment by vovanec** [comment]
I easily reproduced with script from the original bug report: https://github.com/pyca/cryptography/issues/2911#issuecomment-482275293

As suggested, using cryptography.hazmat.backends.openssl.backend.activate_builtin_random() helped.

Operation system is Ubuntu Linux 14.04 (3.13.0-167-generic #217-Ubuntu SMP)
ubuntu@CustomerPortal-2-74:~$ python3 -V
Python 3.4.3

**Comment by vovanec** [comment]
In order to get test script working with older version of Python I've made small change, here it is:

```
ubuntu@CustomerPortal-2-74:~$ cat 1.py 
import asyncio

import cryptography.hazmat.backends.openssl.backend
import requests
import tornado.platform.asyncio
import tornado.web
import tornado.httpserver

try:
    from asyncio import ensure_future
except ImportError:
    from asyncio import async as ensure_future

# Will cause deadlock
cryptography.hazmat.backends.openssl.backend.activate_osrandom_engine()

 # Will fix deadlock
#cryptography.hazmat.backends.openssl.backend.activate_builtin_random()

 # Port for local server
_PORT = 10001


 # local server
class Hello(tornado.web.RequestHandler):
    def get(self):
        self.write("hello")


application = tornado.web.Application([('/', Hello)])
http_server = tornado.httpserver.HTTPServer(application, ssl_options={
    "certfile": "/tmp/cert.pem",
    "keyfile": "/tmp/key.pem",
})
tornado.platform.asyncio.AsyncIOMainLoop().install()
http_server.listen(_PORT)


@asyncio.coroutine
def tester():
    while True:
        yield from asyncio.get_event_loop().run_in_executor(
            None, lambda: requests.get(
                'https://127.0.0.1:{}'.format(_PORT), verify=False))


 # start stressing
for _ in range(11):
    ensure_future(tester())

tornado.ioloop.IOLoop.instance().start()
```

**Comment by reaperhulk** [comment]
Oops, commented on the old issue. Replicating it here: @vovanec can you create a docker container that replicates this issue? I can't replicate it and I'm not sure how it could be happening since we don't call back into Python for random bytes any more (and haven't since version 1.7)

**Comment by vovanec** [comment]
Hi @reaperhulk I cannot simply containerize instance I was seeing the problem as it runs proprietary code I'm not allowed to share. I tried creating custom Ubuntu 14.04 image recreating pip dependencies from production instance' 'pip freeze' output. Anecdotally, I don't see the problem on this custom image, so I guess something is broken in our env in terms of dependencies, either apt of pip, I am not sure. 

Please feel free to close this issue, as I cannot reproduce in clean environment.

**Comment by reaperhulk** [comment]
Okay, thanks for trying! If you manage to get a reproducer you can share please feel free to open a new issue and we'll take a look.
