### ISSUE TITLE
Support Ed25519 CSR building

### ISSUE THREAD

**Issue by thanatos** [pyca/cryptography#4845]
I would like to build a CSR (Certificate Signing Request), and sign it w/ an Ed25519 key. Such keys are newly supported in TLS v1.3. It seems `cryptography` isn't able to support these yet. For example, if I follow the example in the docs on [building a CSR](https://cryptography.io/en/latest/x509/reference/#x-509-csr-certificate-signing-request-builder-object), but use an Ed25519 key instead:

```python
from cryptography import x509  
from cryptography.hazmat.backends import default_backend  
from cryptography.hazmat.primitives import hashes 
from cryptography.hazmat.primitives import serialization  
from cryptography.hazmat.primitives.asymmetric import ed25519  
from cryptography.x509.oid import NameOID  
private_key = ed25519.Ed25519PrivateKey.generate() 
builder = x509.CertificateSigningRequestBuilder()  
builder = builder.subject_name(x509.Name([  
    x509.NameAttribute(NameOID.COMMON_NAME, u'cryptography.io'),  
]))  
builder = builder.add_extension(  
    x509.BasicConstraints(ca=False, path_length=None), critical=True,  
)  
request = builder.sign(  
    private_key, hashes.SHA256(), default_backend()  
)  
isinstance(request, x509.CertificateSigningRequest)                        
```

I get,

```
InternalError                             Traceback (most recent call last)
<ipython-input-19-36fb6c2432d3> in <module>
     14 ) 
     15 request = builder.sign( 
---> 16     private_key, hashes.SHA256(), default_backend()
     17 ) 
     18 isinstance(request, x509.CertificateSigningRequest)

/usr/lib/python3.7/site-packages/cryptography/x509/base.py in sign(self, private_key, algorithm, backend)
    426         if self._subject_name is None:
    427             raise ValueError("A CertificateSigningRequest must have a subject")
--> 428         return backend.create_x509_csr(self, private_key, algorithm)
    429 
    430 

/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py in create_x509_csr(self, builder, private_key, algorithm)
    782                 errors[0]._lib_reason_match(
    783                     self._lib.ERR_LIB_RSA,
--> 784                     self._lib.RSA_R_DIGEST_TOO_BIG_FOR_RSA_KEY
    785                 )
    786             )

/usr/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py in openssl_assert(self, ok)
    123 
    124     def openssl_assert(self, ok):
--> 125         return binding._openssl_assert(self._lib, ok)
    126 
    127     def activate_builtin_random(self):

/usr/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py in _openssl_assert(lib, ok)
     76             "issues with information on how to reproduce "
     77             "this. ({0!r})".format(errors_with_text),
---> 78             errors_with_text
     79         )
     80 

InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([])
```

I believe my local OpenSSL is capable of dealing w/ Ed25519 keys, and generating CSRs with them:

```
» openssl genpkey -algorithm ed25519 -out ed25519.key
» openssl req -new -subj '/CN=example.com/' -key ed25519.key | openssl req -noout -text
<a CSR for example.com follows>
```

I am using version 2.6.1 of `cryptography`, Python 3.7.3, and OpenSSL 1.1.1b. Pip v19.0.3, setuptools v40.8.0. I installed `cryptography` through my distribution, Arch.

(I asked about this on #cryptography-dev and was asked if I minded filing an issue for it; this is that issue. This seems related to #3509.)

**Comment by reaperhulk** [comment]
We should support eddsa signing in CSR, cert, and anywhere else OpenSSL has exposed support (e.g. CRL, OCSP). I'll look into this soon.

**Comment by felixfontein** [comment]
BTW: the same error happens with Ed448, X25519 and X448 private keys.

**Comment by felixfontein** [comment]
For creating CSRs, this can be fixed by passing `self._ffi.NULL` as the third option (digest) in https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L783 ([source](https://github.com/openssl/openssl/commit/f3021aca4a154c2ff9bd0030f7974eb6a719550d)). This fixes the CSR signing problem for Ed25519 and Ed448. (I guess that signing a certificate has the same problem, with the same solution.)

Also, X25519 and X448 probably don't make sense here at all, since these are key exchanges. Would be nice if they would cause an easier to understand error, though.

Back to Ed25519 and Ed448: I guess there are two ways to solve this. Either ignore the digest parameter for them, or require it to be `None` (and fail if it is `None` for other keys). What's the preferred solution? (Or another one, maybe?)

**Comment by markokr** [comment]
Ed25519 CRT signing already requires algorithm=None, it would be good if CSR signing matches it.

**Comment by reaperhulk** [comment]
Yeah, when we landed cert support (actually built in response to this PR) we decided to do `None`. We'll do the same for CSR support.
