### ISSUE TITLE
OpenSSH private key deserialization

### ISSUE THREAD

**Issue by dpwatrous** [pyca/cryptography#4854]
Hi there,

I'm curious if there are any plans to add deserialization support for private keys in OpenSSH format (ones that begin with: -----BEGIN OPENSSH PRIVATE KEY-----).

We currently use cryptography's PEM deserialization function to extract public keys from SSH private key files. Now that OpenSSH has switched to its own serialization format by default, we're hitting many cases where we hit a key we can't handle.

I see various issues about OpenSSH public key (de)serialization, but very little regarding private keys.

Thanks!

**Comment by reaperhulk** [comment]
We have no objection to adding them, but at the moment we purely use OpenSSL's deserialization code. To support OpenSSH someone would need to implement the ability to parse this and build an OpenSSL EVP object internally. That could potentially be accomplished by parsing and rebuilding as a PKCS8 key perhaps? Compounding the difficulty is that it'd be preferable if it was all done with writable buffers so users can zero the data if they so choose (we recently added the ability for all our sensitive data byte strings to be bytes-like to enable this capability)

**Comment by dpwatrous** [comment]
Thanks, Paul - that makes sense. I'm curious if others are interested in this functionality or if our use case is just uncommon.

**Comment by alex** [comment]
I implemented paramiko's version of the OpenSSH key deserialization, for ed25519 keys. The bigger challenge is that it uses bcrypt as its kdf, and we don't have one of those available to us in pyca/cryptography.

**Comment by reaperhulk** [comment]
Yeah I rewrote `bcrypt` using OpenBSD code instead of the solarwall implementation specifically to add `bcrypt_kdf` support, but we obviously don't have that available to us in OpenSSL.

**Comment by reaperhulk** [comment]
We talked about this at pycon and if someone wants to rewrite https://github.com/paramiko/paramiko/blob/master/paramiko/ed25519key.py with a soft dep on `bcrypt` we'd take that PR.

**Comment by markokr** [comment]
Fixed in master.
