### ISSUE TITLE
Remove pep517 hack in wheel builder

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4907]

**Comment by alex** [comment]
@reaperhulk do you have any idea what was being requested here, and if so have we fixed it, or failing that what it's blocked on?

Putting in this milestone with the intended scope of, "Figure out what the hell this ticket was for"

**Comment by reaperhulk** [comment]
I think this is the "downgrade to pip10" thing we do to avoid...I don't remember what. Something that broke us due to having a pyproject.toml. Probably the experiment to run is remove that downgrade and see if we can still build wheels?

**Comment by alex** [comment]
Tried this in #5306.

>   ERROR: Cannot build wheel for cryptography using PEP 517 when --build-option is present

I could have sworn there was a pip bug filed for this, but I can't find it.

**Comment by alex** [comment]
removing from the milestone since this seems to be a pip issue

**Comment by reaperhulk** [comment]
Done
