### ISSUE TITLE
Implement class methods for sign/verify on Poly1305

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#4908]
This issue is intended to track the discussion in #4798 around adding new class methods to Poly1305 to do single-step sign and verify operations, rather than having to construct an instance and then make calls to update and finalize/verify. Instead, the class could offer:

    Poly1305.sign(key, data)

and:

    Poly1305.verify(key, data, tag)

**Comment by jeffjyang** [comment]
👋 Hi everyone, is there anyone currently working on this? If not, I've opened a PR for the issue, let me know what you all think! https://github.com/pyca/cryptography/pull/4932

**Comment by reaperhulk** [comment]
Done
