### ISSUE TITLE
Fernet without base64 encoding/decoding

### ISSUE THREAD

**Issue by scopatz** [pyca/cryptography#4921]
Hi there, I'm interested in having a version of Fernet without the back and forth of `urlsafe_b64encode/urlsafe_b64decode`.  I am happy to write and contribute this, but I was wondering what the best way forward for this is?  I see three main options for the API:

1. Have an attr that is initialized on Fernat objects that flags whether or not to be urlsafe, defaults to True.
2. Pass in a urlsafe kwarg to all methods that might need it, defaults to True.
3. Have a totally separate class that is url-unsafe.

Thoughts?

**Comment by alex** [comment]
Fernet is an implementation of an external spec -- we don't want to maintain our own variations on it: https://github.com/fernet

So if you'd like this, the right way to make it happen is to get some official variant declared upstream. Note: the maintainers of the spec mostly view it as done, so they're not super active on PRs suggesting new functionality.

Regardless, I'm going to close this, as until it becomes part of the spec we're not going to add it.

**Comment by scopatz** [comment]
Yeah, I just read [this](https://medium.com/coinmonks/if-youre-struggling-picking-a-crypto-suite-fernet-may-be-the-answer-95196c0fec4b) which indicates that. Makes sense.
