### ISSUE TITLE
Make default_backend the default backend

### ISSUE THREAD

**Issue by FranklinYu** [pyca/cryptography#4922]
Now that it’s called `default_backend` I think it makes sense to really default to it. For example, currently the function [`cryptography.x509.load_pem_x509_certificate(data, backend)`](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_pem_x509_certificate) requires `backend`. Would be cool if this parameter is optional.

**Comment by alex** [comment]
This is already covered by #3881
