### ISSUE TITLE
Drop support for OpenSSL 1.0.1

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4923]
- [x] **2.7** as-is
- [x] **2.8** aggressive "1.0.1 will be dropped in the next release" language (https://github.com/pyca/cryptography/pull/4924)
- [x] **2.9** 1.0.1 errors unless you pass the `CRYPTOGRAPHY_ALLOW_OPENSSL_101` env var (#5022)
- [x] **3.0** Delete 1.0.1 code

**Comment by alex** [comment]
FYI: @bitprophet, @glyph, @hynek, @Lukasa, @abadger, @bmw, @ohemorange

**Comment by abadger** [comment]
Is your 3.0 bullet supposed to be Delete 1.0.1 code?  (since openssl-1.0.2 is a thing)

**Comment by reaperhulk** [comment]
@abadger yeah, that's a typo. fixed! We have no plans to drop 1.0.2 support for now.

**Comment by alex** [comment]
It's happening! https://github.com/pyca/cryptography/pull/5178
