### ISSUE TITLE
No module named 'cryptography.hazmat.bindings._constant_time'

### ISSUE THREAD

**Issue by vishal-kumar93** [pyca/cryptography#4927]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security/

**Comment by vishal-kumar93** [comment]
I am using the latest version of pip and cryptography but facing this error while running the code

**Comment by alex** [comment]
Can you give us any instructions on what you did that led to this happening, or how we might reproduce it?

**Comment by vishal-kumar93** [comment]
I am using load_pem_x509_certificate and default_backend in my code when I am running my code is throwing me the error mentioned above.

from cryptography.x509 import load_pem_x509_certificate
from cryptography.hazmat.backends import default_backend

**Comment by vishal-kumar93** [comment]
I think something wrong in cryptography\hazmat\primitives\constant_time.py

I can see this import statement
from cryptography.hazmat.bindings._constant_time import lib

When you go to the path given there is no such file.

![image](https://user-images.githubusercontent.com/26434895/59626301-21ff3100-9159-11e9-987d-b44eb1dbb472.png)

**Comment by reaperhulk** [comment]
Can you replicate this issue in a virtualenv? This sort of problem typically occurs when there are issues with the python package paths. `_constant_time` is imported from that pyd file so the correct files are present.

So does this also cause the failure? (Change the virtualenv commands to whatever you might need):

```
C:\Python37\python.exe -m venv .venv
.venv/Scripts/activate
pip install cryptography
python -c "from cryptography.hazmat.bindings._constant_time import lib"
```

That last command should not fail.

**Comment by vishal-kumar93** [comment]
I tried in using virtual env and didn't fail then why its failing when I am using without virtual env.

I am deploying my solution using serverless and its failing when i m running my code

**Comment by reaperhulk** [comment]
If you're deploying to something like AWS Lambda be aware that cryptography contains native code, which must be compiled for the target machine. To use it on lambda you must use linux binaries, while on your local machine you'll be using windows versions. Assisting with deployments like this is out of scope for our bug tracker, but there are many people doing this so you should be able to find resources online.
