### ISSUE TITLE
Can UnrecognizedExtension be used with arbitrary ASN1 types?

### ISSUE THREAD

**Issue by ericatpure** [pyca/cryptography#4947]
I tried to add a "user roles" x509 entension as documented here: https://www.spinnaker.io/setup/security/authentication/x509/

So far I haven't had any luck getting the correct encoding.  The closest I got was this:
```
def user_role_extension(role):
    USER_ROLE_OID = x509.ObjectIdentifier('1.2.840.10070.8.1')
    der_asn1 = asn1crypto.core.UTF8String(role).dump()
    return x509.UnrecognizedExtension(oid=USER_ROLE_OID, value=der_asn1)
```
But when I actually create the certificate my (already-encoded) bytes get wrapped and stored as an ASN1 octet string.

Is there a way to set a "raw" value (already encoded), or specify the type of encoding needed?

**Comment by alex** [comment]
RFC5280 indicates that the `extnValue` field of an `Extension` should always be an `OCTET STRING`
