### ISSUE TITLE
AttributeError: module 'six' has no attribute 'add_metaclass'

### ISSUE THREAD

**Issue by R-Studio** [pyca/cryptography#4951]
**Reproduction:**
import requests
import cryptography
import six

If I import one of the libraries (ntlm_auth or requests_ntlm) the following error occus:
```
@six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'
```

```
import ntlm_auth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\__init__.py", line 4, in <module>
    from . import ntlm, session_security
  File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\ntlm.py", line 9, in <module>
    from ntlm_auth.messages import AuthenticateMessage, ChallengeMessage, \
  File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\messages.py", line 12, in <module>
    from ntlm_auth.rc4 import ARC4
  File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\rc4.py", line 8, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
  File "C:\Program Files\Python37\lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "C:\Program Files\Python37\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 16, in <module>
    from cryptography.hazmat.backends.interfaces import CipherBackend
  File "C:\Program Files\Python37\lib\site-packages\cryptography\hazmat\backends\interfaces.py", line 12, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'
```

```
from requests_ntlm import HttpNtlmAuth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\requests_ntlm\__init__.py", line 1, in <module>
    from .requests_ntlm import HttpNtlmAuth
  File "C:\Program Files\Python37\lib\site-packages\requests_ntlm\requests_ntlm.py", line 5, in <module>
    from cryptography import x509
  File "C:\Program Files\Python37\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "C:\Program Files\Python37\lib\site-packages\cryptography\x509\certificate_transparency.py", line 22, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'
```

**Versions:**
Python: 3.7
cryptography: 2.7
requests: 2.22.0
requests_ntlm: 1.1.0

_PS: I use Python on a Windows System._

**Comment by R-Studio** [comment]
> **Reproduction:**
> import requests
> import cryptography
> import six
> 
> If I import one of the libraries (ntlm_auth or requests_ntlm) the following error occus:
> 
> ```
> @six.add_metaclass(abc.ABCMeta)
> AttributeError: module 'six' has no attribute 'add_metaclass'
> ```
> 
> ```
> import ntlm_auth
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\__init__.py", line 4, in <module>
>     from . import ntlm, session_security
>   File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\ntlm.py", line 9, in <module>
>     from ntlm_auth.messages import AuthenticateMessage, ChallengeMessage, \
>   File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\messages.py", line 12, in <module>
>     from ntlm_auth.rc4 import ARC4
>   File "C:\Program Files\Python37\lib\site-packages\ntlm_auth\rc4.py", line 8, in <module>
>     from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
>   File "C:\Program Files\Python37\lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 7, in <module>
>     from cryptography.hazmat.primitives.ciphers.base import (
>   File "C:\Program Files\Python37\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 16, in <module>
>     from cryptography.hazmat.backends.interfaces import CipherBackend
>   File "C:\Program Files\Python37\lib\site-packages\cryptography\hazmat\backends\interfaces.py", line 12, in <module>
>     @six.add_metaclass(abc.ABCMeta)
> AttributeError: module 'six' has no attribute 'add_metaclass'
> ```
> 
> ```
> from requests_ntlm import HttpNtlmAuth
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Program Files\Python37\lib\site-packages\requests_ntlm\__init__.py", line 1, in <module>
>     from .requests_ntlm import HttpNtlmAuth
>   File "C:\Program Files\Python37\lib\site-packages\requests_ntlm\requests_ntlm.py", line 5, in <module>
>     from cryptography import x509
>   File "C:\Program Files\Python37\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
>     from cryptography.x509 import certificate_transparency
>   File "C:\Program Files\Python37\lib\site-packages\cryptography\x509\certificate_transparency.py", line 22, in <module>
>     @six.add_metaclass(abc.ABCMeta)
> AttributeError: module 'six' has no attribute 'add_metaclass'
> ```
> 
> **Versions:**
> Python: 3.7
> cryptography: 2.7
> requests: 2.22.0
> requests_ntlm: 1.1.0
> 
> _PS: I use Python on a Windows System._

I also posted this question on: https://github.com/benjaminp/six/issues/118

**Comment by R-Studio** [comment]
I also posted this question on: https://github.com/benjaminp/six/issues/118

**Comment by reaperhulk** [comment]
Can you replicate this in a virtualenv?

**Comment by R-Studio** [comment]
> Can you replicate this in a virtualenv?

No, but i found the issue. It was my mistake. 
I copied the wrong files because the module "six" is in the root directory "C:\Program Files\Python37\Lib\site-packages" instead in a subfolder.

So you can close this issue and sorry for the trouble.
