### ISSUE TITLE
PKCS#12 generation support

### ISSUE THREAD

**Issue by trishankatdatadog** [pyca/cryptography#4952]
It would be fantastic to get native PKCS#12 support from `cryptography`.

Use case 1:

1. Code signing private key generated as PEM.
2. Code signing certificate signed and returned by root CA as PKCS#7.
3. Windows code signing tool expects private key and certificate stitched together as PKCS#12.

Related issues: #3983

**Comment by alex** [comment]
Doe #4888 address this?

**Comment by reaperhulk** [comment]
It hypothetically would, although that current API won't work (we're not going to expose PBE NIDs as public API).

**Comment by alex** [comment]
done in #5325

**Comment by trishankatdatadog** [comment]
Amazing, thanks @reaperhulk!
