### ISSUE TITLE
Missing coverage

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#4961]
![image](https://user-images.githubusercontent.com/161495/62062423-9d3f1280-b1ee-11e9-8917-c022cce2b64e.png)

https://github.com/pyca/cryptography/blob/c7681e80a68a97ba56453e7fbb960f0e59f4acad/src/cryptography/x509/extensions.py#L56-L66

If this isn't reachable we should convert these into something assert-like.

**Comment by alex** [comment]
Hm, the data here is coming from a public key's `public_bytes()` method, so yeah this is probably unreachable.
