### ISSUE TITLE
Documentation improvement for ECC verify function

### ISSUE THREAD

**Issue by boustrophedon** [pyca/cryptography#4968]
[In the documentation for EllipticCurvePublicKey.verify](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicKey.verify) it isn't mentioned anywhere that the signature should be DER encoded. The only time it is mentioned in [the documentation for the ECDSA class](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.ECDSA), where it says the output in the example code is DER encoded and can be decoded with the `asymmetric.utils.decode_dss_signature` function. This isn't mentioned in the documentation for [the output of the sign function either](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.sign)

I discovered this by [reading the test code](https://github.com/pyca/cryptography/blob/master/tests/hazmat/primitives/test_ec.py#L497), because I couldn't figure out why my signatures were valid with the Pycryptodome library but not the Cryptography library.

Proposals:
1. Update the documentation in `verify` to say that the signature should be DER encoded, and mention the utils.encode_dss_signature function
2. Update the documentation in `sign` to say that the output is DER encoded
3. Maybe have some more example code somewhere?

If these are okay then I'd be happy to submit a PR with the changes.

**Comment by reaperhulk** [comment]
Yeah we'd be happy to accept a PR improving the docs to explain the signature output encoding (and maybe mentions `decode_dss_signature` a few more times)

**Comment by boustrophedon** [comment]
I'll try to submit it tomorrow.

**Comment by reaperhulk** [comment]
Resolved by #4970. Thanks again for the report.
