### ISSUE TITLE
"AttributeError: 'AsymmetricKey' object has no attribute 'sign'"

### ISSUE THREAD

**Issue by evso9816** [pyca/cryptography#4974]
I used the below code  on my computer (Ubuntu 16.04, python 3.5.2, with the newest version of cryptography 2.7 using pip, Pycharm-com), we have the above error: "AttributeError: 'AsymmetricKey' object has no attribute 'sign'"
It might be the Python versioning, but not sure. Using the same code on Windows (Eclipse, Python 3.7), it worked. Very interesting!!!
Then, I install Python 3.7.4 with all require packages, but the same error.
Please keep us update if something new. Let me know if you need testing. - Thanks.

testing code:
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes #for signing
from cryptography.hazmat.primitives.asymmetric import utils #for hashing larger message
from cryptography.hazmat.primitives.asymmetric import padding #for signing

private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048, backend=default_backend())
public_key = private_key.public_key()

chosen_hash = hashes.SHA256()
hasher = hashes.Hash(chosen_hash, default_backend())
hasher.update(b'blabla')
hasher.update(b'Grrrrrrr')
hasher.update(b'No way')
digest = hasher.finalize()
signature = private_key.sign(digest, padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH), utils.Prehashed(chosen_hash))
print(signature)

**Comment by reaperhulk** [comment]
`AsymmetricKey` is not a class in `cryptography`, so I'm not sure where you're getting that error message?

**Comment by evso9816** [comment]
My bad!
signature = private_key.sign_ecdsa(message)
solved the problem
