### ISSUE TITLE
Add linux build for newer python versions

### ISSUE THREAD

**Issue by menmikimen** [pyca/cryptography#4976]
I've noticed that on pypi "download page" only windows version is being build for python 3.5 and newer. Is there a specific reason for that?

I'm sure many people would appreciate the ability to install this library without need for gcc, especially when using containers.

(I don't know if it's right place to make this request, please direct me to proper location if I've made a mistake)

**Comment by reaperhulk** [comment]
I'm not sure I understand the question. We build static wheels for Python 2.7, 3.4, 3.5, 3.6, and 3.7 on Windows for both 32-bit and 64-bit Python. On macOS and Linux we build static wheels for 2.7 and 3.4+ (we can't do 3.4+ on Windows so whenever a new Python is released we have to explicitly add a new wheel, but that only affects people living on the bleeding edge: e.g. 3.8 alphas/betas). Over 80% of our users get a wheel right now. Is there a wheel you think we're missing?

**Comment by menmikimen** [comment]
Thanks for your reply.

Turns out I've been using an outdated version of pip, which recognized 3.4+ wheel as 3.4 only.
Everything is working as supposed, sorry for wasting your time.
