### ISSUE TITLE
PKCS12 export functionality

### ISSUE THREAD

**Issue by iFrozenPhoenix** [pyca/cryptography#4977]
It would be desirable if the created certificates and their private key could be exported as
a pkcs12 package.
In Linux it is the normal case to use separate files for private key and certificate, but
in windows the only possibility to get the private key into the store is if it is directly
imported with the certificate as pkcs12.
So, the needed functionality includes a export functionality analog to the load functionality
of 'cryptography.hazmat.primitives.serialization.pkcs12.load_key_and_certificates()'

@reaperhulk has provided an example of the desired functionality at this post https://stackoverflow.com/questions/54677841/how-do-can-i-generate-a-pkcs12-file-using-python-and-the-cryptography-module

**Comment by jheiss** [comment]
Duplicates #4952?

**Comment by alex** [comment]
Good call, thanks.
