### ISSUE TITLE
Recent aws-dynamodb-encryption-python change broke CI

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#4979]
CC: @mattsb42-aws 

https://travis-ci.org/pyca/cryptography/jobs/579259777

**Comment by mattsb42-aws** [comment]
.... :/ that shouldn't be happening...
I'll take a look and find out why our isolation tests didn't catch this.

**Comment by alex** [comment]
Thanks for taking a look!

**Comment by mattsb42-aws** [comment]
This should be fixed now, and this particular class of error should be caught in our CI now, before any changes get into the branch you are pulling from.

**Comment by alex** [comment]
Confirmed.
