### ISSUE TITLE
Bump OpenSSL versions in CI

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#4994]
- [x] manylinux1 (blocked on https://github.com/pyca/infra/pull/241)
- [x] manylinux2010 (blocked on https://github.com/pyca/infra/pull/241)
- [x] Windows (https://github.com/pyca/infra/pull/242, blocked on https://github.com/pyca/infra/pull/241)
- [x] macOS brew (https://github.com/Homebrew/homebrew-core/pull/44139)

**Comment by alex** [comment]
These are all done, just need to do a release now.
