### ISSUE TITLE
Add more RSA functions

### ISSUE THREAD

**Issue by Legorooj** [pyca/cryptography#5004]
Could you add more RSA functions? So that cryptography can do all that pycryptodome can do?

**Comment by alex** [comment]
Can you be more specific in what functionality you're looking for?

**Comment by Legorooj** [comment]
The ability to construct the key from component sets, either `{p, q, e, d'` or `{n, e}`.
A simpler import_key function, not many different ones for different formats.
Functionality to get the RSA key factors from the `RSAKey` types, like `private_key.d` etc.
Will post the rest when I remeber them.

**Comment by reaperhulk** [comment]
You can construct a key from components via [RSAPrivateNumbers](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateNumbers) and obtain the integer values from a loaded key via the [private_numbers()](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKeyWithSerialization.private_numbers) method. (This functionality is also available on the public key).

It is a deliberate design choice to separate PEM and DER loading, but the import functions handle multiple key formats within that encoding (PKCS1 aka TraditionalOpenSSL as well as PKCS8 and both of those formats in both encrypted and unencrypted form). You can always wrap those functions with your own helper method if you desire a single loader.

**Comment by Legorooj** [comment]
How did I not see this! I read the `cryptography` docs daily! (It's my favourite python package)
Thanks, it appears that talking to a real person has solved my problem yet again.
