### ISSUE TITLE
Add to CSR streetAddress

### ISSUE THREAD

**Issue by voloxastik** [pyca/cryptography#5005]
Hi all!
How to add to CSR streetAddress?

**Comment by Legorooj** [comment]
CSR streetAddress? I'm unfamiliar with this... And can't find what it is.

**Comment by reaperhulk** [comment]
Pass [STREET_ADDRESS](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.oid.NameOID.STREET_ADDRESS) when creating a `NameAttribute` to pass to the `Name`. You can see examples of building a Name in the docs: https://cryptography.io/en/latest/x509/reference/#x-509-csr-certificate-signing-request-builder-object
