### ISSUE TITLE
Please provide a wheel file for Python 3.8

### ISSUE THREAD

**Issue by shmilylty** [pyca/cryptography#5007]
os:win10 x64
python:3.8.0beta4

**Comment by reaperhulk** [comment]
We will not be shipping a 3.8 wheel until 3.8 is released, sorry.

**Comment by shmilylty** [comment]
https://www.python.org/dev/peps/pep-0569/#id6

Python 3.8.0 final: Monday, 2019-10-21

**Comment by shmilylty** [comment]
Python 3.8.0 is the newest major release of the Python programming language, and it contains many new features and optimizations.
https://www.python.org/
https://www.python.org/downloads/release/python-380/

**Comment by alex** [comment]
Yes, we're aware. See #5010

**Comment by reaperhulk** [comment]
We also provide wheels that work fine on 3.8 for macOS and Linux already. Windows is a special case and other build issues related to openssl are likely to delay us a bit. Sorry.

**Comment by shmilylty** [comment]
@reaperhulk Thx，wait for good news~

**Comment by shmilylty** [comment]
I compiled it here, and my environment is: 

- System:  Windows 10 1903 x64
- Python:  3.8.0 amd64

1. First, go to http://slproweb.com/products/Win32OpenSSL.html to download Win32/Win64 OpenSSL Installer for Windows,. Here I download Win64 OpenSSL v1.1.1d exe, and then install it by default. 
2. Then execute the following command
```cmd
C:\WINDOWS\system32>python -V
Python 3.8.0

C:\WINDOWS\system32>pip -V
pip 19.2.3 from c:\program files\python38\lib\site-packages\pip (python 3.8)

C:\WINDOWS\system32>set Path=C:\Program Files\OpenSSL-Win64\bin;%Path%

C:\WINDOWS\system32>set LIB=C:\Program Files\OpenSSL-Win64\lib;%LIB%

C:\WINDOWS\system32>set INCLUDE=C:\Program Files\OpenSSL-Win64\include;%INCLUDE%

C:\WINDOWS\system32>pip install cryptography
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting cryptography
  Using cached https://mirrors.aliyun.com/pypi/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting six>=1.4.1 (from cryptography)
  Using cached https://mirrors.aliyun.com/pypi/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography)
  Using cached https://mirrors.aliyun.com/pypi/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
Collecting asn1crypto>=0.21.0 (from cryptography)
  Using cached https://mirrors.aliyun.com/pypi/packages/6e/1e/fb0e487b5229e5fb7b15c6d00b4e8082a3414fe62b1da4c9a905b106e672/asn1crypto-1.1.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... done
  Created wheel for cryptography: filename=cryptography-2.7-cp38-cp38-win_amd64.whl size=330764 sha256=f4832ff11ac35d906026d47757481b607ade1a9f461676d972eb4313a765e643
  Stored in directory: C:\Users\liwei05\AppData\Local\pip\Cache\wheels\a1\5c\5c\35599ab365c0cb0662c9fcf7b20a7c246393d0a183898ac245
Successfully built cryptography
Installing collected packages: six, pycparser, cffi, asn1crypto, cryptography
  Running setup.py install for cffi ... done
Successfully installed asn1crypto-1.1.0 cffi-1.12.3 cryptography-2.7 pycparser-2.19 six-1.12.0
```

**Comment by shmilylty** [comment]
[cryptography-2.7-cp38-cp38-win_amd64.whl.zip](https://github.com/pyca/cryptography/files/3728442/cryptography-2.7-cp38-cp38-win_amd64.whl.zip)

**Comment by ivankravets** [comment]
@shmilylty could you build a wheel for win32? You need to use Python 3.8 x32.

**Comment by shmilylty** [comment]
@ivankravets https://github.com/pyca/cryptography/commit/ae13fec7fcf795afc198a14daaaf6e33b0513647

**Comment by ivankravets** [comment]
@shmilylty Yes. I saw. There is no date for the final release with wheels.

@alex is it possible to get wheels from https://dev.azure.com/pyca/cryptography/_build/results?buildId=1082 ? I'm not expert with Azure services.

**Comment by reaperhulk** [comment]
@ivankravets We are running the 2.8 cryptography release right now. Within the next ~30-60 min 3.8 wheels will be available for Windows!

**Comment by ivankravets** [comment]
@reaperhulk Thank you so much for amazing work!

**Comment by reaperhulk** [comment]
Release is done!
