### ISSUE TITLE
FIPS_mode_set not working from static cryptography wheel

### ISSUE THREAD

**Issue by gumho** [pyca/cryptography#5008]
As per https://cryptography.io/en/latest/installation/#static-wheels, it should be possible to build a static wheel. When I tried building against an OpenSSL with FIPS, however, cryptography seemed to ignore fips capabilities. Here is a Dockerfile that can reproduce the exact issue:

```
FROM centos

# Install build dependencies
RUN yum groupinstall -y  "Development Tools" && \
    yum install -y python-devel libffi-devel yum install zlib-devel

# Build Fips object module
RUN curl -O https://www.openssl.org/source/openssl-fips-2.0.16.tar.gz && \
    tar xvf openssl-fips-2.0.16.tar.gz && \
    cd openssl-fips-2.0.16 && \
    ./config && \
    make && \
    make install

# Build OpenSSL
RUN curl -O https://www.openssl.org/source/openssl-1.0.2t.tar.gz && \
    tar xvf openssl-1.0.2t.tar.gz && \
    cd /openssl-1.0.2t && \
    ./config fips no-shared -fPIC --prefix=/openssl-1.0.2t/openssl && \
    make depend && \
    make && \
    make install

# Install Python dependencies
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    pip install virtualenv setuptools wheel pip


# Build cryptography
RUN CPPFLAGS="-I/openssl-1.0.2t/openssl/include" LDFLAGS="-L/openssl-1.0.2t/openssl/lib" pip wheel --no-cache --no-binary :all: cryptography && \
    pip install cryptography*.whl

# Test if fips is enabled
RUN python -c "\
from cryptography.hazmat.backends.openssl.backend import backend;\
print backend._lib.FIPS_mode_set(1);\
print ''.join([backend._lib.OPENSSL_VERSION_TEXT[i] for i in range(30)])"
```

The output for the two print statements are expected to be "1" and "OpenSSL 1.0.2t-fips 10 Sep 2019" but instead it gives "0" and "OpenSSL 1.0.2t  10 Sep 2019", indicating that FIPS is not correctly getting used.

**Comment by reaperhulk** [comment]
Thanks for the report. I'll take a closer look at this soon. Just to confirm, have you tried this with the latest master? We've added some FIPS specific handling for certain cases, but I doubt it would do anything here.

**Comment by gumho** [comment]
@reaperhulk Yep, same results with master unfortunately.

**Comment by reaperhulk** [comment]
We’ve merged a variety of additional FIPS related things into master just now, but we can’t help much with this since it’s ultimately something you’ll need to sort out with openssl itself. FIPS in openssl has a ton of restrictions related to whether you’re trying to gain CMVP via the FOM or from your underlying platform, etc etc.
