### ISSUE TITLE
Why can the `Scrypt` class only be used once? 

### ISSUE THREAD

**Issue by Legorooj** [pyca/cryptography#5011]
Apologies if this is the wrong place to ask this, I wasn't sure where to ask.

Why does the `Scrypt` class raise an `AlreadyFinalized` error if you use it more than once? I bypassed it calling the error, and called `derive` again, and the key I got was the same.

So why do you need it to raise an error?

**Comment by reaperhulk** [comment]
We do this to be consistent with our other KDF interfaces.

**Comment by Legorooj** [comment]
@reaperhulk so it would be cryptographically secure to use the interface more than once? It's a pain to have to re-create the object every time (alot alot of times).
