### ISSUE TITLE
AttributeError: 'function' object has no attribute 'sign'

### ISSUE THREAD

**Issue by biswajitjei02** [pyca/cryptography#5036]
**this error** 

```
File "C:/Users/user/PycharmProjects/mycrypto/venv/myfile1.py", line 13, in signature_1
    sig = private_key.sign(message,padding.PSS( mgf=padding.MGF1(hashes.SHA256()),
AttributeError: 'function' object has no attribute 'sign'
```

  **Code:**
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding

def generate_keys():
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048, backend=default_backend())
    public_key =private_key.public_key
    return private_key,public_key


def signature_1(message,private_key):
     sig = private_key.sign(message,padding.PSS( mgf=padding.MGF1(hashes.SHA256()),
                                                       salt_length=padding.PSS.MAX_LENGTH),hashes.SHA256())
     return sig

def verify(message,public_key):
    try:
     public_key.verify(signature,message,padding.PSS(mgf = padding.MGF1(hashes.SHA256()),
                                                    salt_length = padding.PSS.MAX_LENGTH),hashes.SHA256())
     return True

    except InvalidSignature :
     return False

if(__name__=='__main__'):
    pu,pr=generate_keys()
    print(pr)
    print(pu)
    message = b"this is message"
    sig = signature_1(message,pr)
    print(sig)

```

**Comment by alex** [comment]
Your problem is that you're doing `public_key = private_key.public_key`. `public_key` is a method, you need to call it.

**Comment by biswajitjei02** [comment]
not solved  getting same  error after doing this

**Comment by reaperhulk** [comment]
We have no public functions in our entire codebase that return other functions so please post the updated code you're running.

**Comment by biswajitjei02** [comment]
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding

def generate_keys():
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048, backend=default_backend())
    public_key =private_key.public_key()
    return private_key,public_key


def signature_1(message,private_key):
     sig = private_key.sign(message,padding.PSS( mgf=padding.MGF1(hashes.SHA256()),
                                                       salt_length=padding.PSS.MAX_LENGTH),hashes.SHA256())
     return sig

def verify(message,public_key):
      public_key.verify(signature,message,padding.PSS(mgf = padding.MGF1(hashes.SHA256()),
                                                    salt_length = padding.PSS.MAX_LENGTH),hashes.SHA256())


if(__name__=='__main__'):
    pu,pr=generate_keys()
    print(pr)
    print(pu)
    print(type(pr))
    message = b"this is message"
    sig = signature_1(message,pr)

**Comment by biswajitjei02** [comment]
if i only print the private key ,public key , type of private key then output is 
C:\Users\user\PycharmProjects\mycrypto\venv\Scripts\python.exe C:/Users/user/PycharmProjects/mycrypto/venv/myfile1.py
<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x0000025B1C149198>
<cryptography.hazmat.backends.openssl.rsa._RSAPrivateKey object at 0x0000025B1C149160>
<class 'cryptography.hazmat.backends.openssl.rsa._RSAPublicKey'>

**Comment by biswajitjei02** [comment]
found the error i was doing pu,pr=generate_keys() 
but it return private_key,public_key
