### ISSUE TITLE
Fails to build when OpenSSL is build without Certificate Transparency (CT) support

### ISSUE THREAD

**Issue by koobs** [pyca/cryptography#5067]
cryptography fails to build with compiler errors when compiled against an OpenSSL that has Certificate Transparency (CT) disabled.

Build warnings/error summary:
 * Several: `error: use of undeclared identifier  'SCT_*'`
 * Several: `error: use of undeclared identifier 'CT_LOG_*'`
 * Several: `warning: implicit declaration of function 'SCT_*' is invalid in C99`
 * Final error:

```
build/temp.freebsd-13.0-CURRENT-amd64-3.7/_openssl.c:33416:8: error: unknown type name 'ct_log_entry_type_t'
static ct_log_entry_type_t _cffi_d_SCT_get_log_entry_type(SCT const * x0)
       ^
```

Reproduction Environment:

 * Operating System: FreeBSD 13.0-CURRENT #3 r354143 (amd64)
   * FreeBSD clang version 9.0.0 (tags/RELEASE_900/final 372316) (based on LLVM 9.0.0)
 * OpenSSL: 1.1.1d-freebsd 10 Sep 2019 (via ports, with `CT` option **disabled**) 
   * `./configure: --openssldir=/usr/local/openssl  --prefix=/usr/local no-ct `
 * Python 2.7.17 / 3.7.5
 * cryptography: 2.8 (PyPI sdist)

Full build log attached:

[cryptography-2.8-no-CT-build-failure.log](https://github.com/pyca/cryptography/files/3855123/cryptography-2.8-no-CT-build-failure.log)

**Comment by reaperhulk** [comment]
This and #5113 are related in that they're configs we don't support right now and maybe should.

**Comment by reaperhulk** [comment]
(Closing this to track "unsupported configs" in #5113)
