### ISSUE TITLE
'Type[...] has no attribute "Raw"'

### ISSUE THREAD

**Issue by maqp** [pyca/cryptography#5079]
With following example code in `test.py`
    
    from cryptography.hazmat.primitives.serialization   import Encoding, PublicFormat
    from cryptography.hazmat.primitives.asymmetric.x448 import X448PrivateKey
    
    private_key = X448PrivateKey.generate()
    
    public_key = private_key.public_key().public_bytes(encoding=Encoding.Raw,
                                                       format=PublicFormat.Raw)  # type: bytes
    
    peer_public_key = X448PrivateKey.generate().public_key()
    
    shared_key = private_key.exchange(peer_public_key)
    
Running `$ python3.7 -m mypy test.py`

Shows warnings

`test.py:7: error: "Type[Encoding]" has no attribute "Raw"`
`test.py:8: error: "Type[PublicFormat]" has no attribute "Raw"`

Is this a typeshed issue, mypy issue, or does the library have a bug?

**Python version**:
`Python 3.7.5 (default, Nov 20 2019, 09:21:52)`
`GCC 9.2.1 20191008] on linux`

**cryptography version**: `2.8`

**mypy version**: `0.740`

**Comment by alex** [comment]
typeshed issue probably, we don't maintain the type hints for cryptography.

**Comment by maqp** [comment]
Ah I see. Thanks!

(Looks like mypy 0.750 was released the same day this ticket was created and typeshed updated at the same time: mypy no longer shows the warnings.)
