### ISSUE TITLE
RSA Support

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#508]
This is a tracking issue for landing RSA support. When complete we will have objects that represent public and private RSA keys and functions to allow us to generate, load, serialize, sign, encrypt, and verify. A rough list of steps adapted from @public's original list:
- [x] OpenSSL bindings
- [x] OpenSSL thread safety
- [x] OpenSSL error handling (#466)
- [x] OpenSSL `fork()` RNG solution (#377)
- [x] Interfaces and RSA key API.
- [x] Key generation (depends on RNG at the moment)
- [x] Test vectors
- [x] Signing/Verification APIs
- [x] Use RSA blinding for signing/verification
- [x] Decryption
- [x] Encryption
- [x] Use RSA blinding for encrypt/decrypt

**Comment by displague** [comment]
> This is a “Hazardous Materials” module. You should ONLY use it if you’re 100% absolutely sure that you know what you’re doing because this module is full of land mines, dragons, and dinosaurs with laser guns.

Is this still the case? Why and how so?  What kind of dragons?

Is this safe to use from a security perspective?

**Comment by reaperhulk** [comment]
The dragons are the standard crypto dragons. The RSA module is definitely ready for production use, but we want people to be very wary when using it. It is very, very easy to build cryptographic constructions that have subtle (and not so subtle) flaws rendering the signing/encryption useless.

**Comment by displague** [comment]
Does that mean that you want us to be cautious with respect to asymmetric encryption in general or specifically with the cryptography (library) implementation therein?

-- SirCmpwn

**Comment by reaperhulk** [comment]
asymmetric (and symmetric) encryption in general, not the implementation. :)

**Comment by SirCmpwn** [comment]
Excellent! We (think we) know what we're doing, so I'll go ahead and use that (also we have a legacy dataset that's already encrypted a certain way anyway).
