### ISSUE TITLE
Best of the lot, but weak in 2017 in Asymmetric Crypto

### ISSUE THREAD

**Issue by Iiridayn** [pyca/cryptography#5081]
https://www.ieee-security.org/TC/SP2017/papers/161.pdf published in 2017 shows this library is a fantastic choice for symmetric crypto tasks, but at the time was a bit confusing for asymmetric crypto. Have the identified issues already been resolved?

**Comment by Legorooj** [comment]
Define fixed.

**Comment by reaperhulk** [comment]
We talked with the paper's authors and we've improved documentation where possible. Some of the tasks in the paper  (e.g. X509 verification) are currently unsupported, but otherwise we're happy with our general posture.
