### ISSUE TITLE
Use manylinux2014 to get aarch64/ppc64le support

### ISSUE THREAD

**Issue by hrw** [pyca/cryptography#5083]
Manylinux2014 image got released some time ago. One of things it brings is support for !x86 architectures.

Cryptography is using Travis CI so two things can be joined and used to generate wheel files for aarch64 and ppc64le architectures.

Amount of software installed to be able to run 'pip install cryptography' would be cut. Also install times would be nicer.

**Comment by reaperhulk** [comment]
manylinux2014 supports aarch64? Yes we should absolutely support that (and first we should add a job to test against it). Looks like GitHub Actions doesn't support aarch64 so that's a reason to keep using Travis for now.

I care less about ppcle64, but assuming there are no nasty surprises adding a CI job there is okay too.

However...We currently generate wheels via Azure Pipelines and aarch64/ppcle64 isn't available there. We'll need a solution for that before we can actually ship wheels.

**Comment by mattsb42-aws** [comment]
FYI, CodeBuild supports ARM now[1].

[1] https://aws.amazon.com/about-aws/whats-new/2019/11/aws-codebuild-adds-support-for-arm--gpu--and-x-large-compute-typ/

**Comment by hrw** [comment]
@reaperhulk you can also use Travis CI for that.

**Comment by alex** [comment]
Hmm, so we attempted to use travis to do aarch64/ppc builds. They were outrageously slow.

On the one hand, I'd like to offer aarch64 wheels. On the other hand, we shouldn't offer wheels for platforms we're not testing, and the travis arch64 builders are simply too slow to use.

**Comment by hrw** [comment]
Can I get a link to your travis ci builds? 

Maybe you can run tests in parallel?

**Comment by alex** [comment]
https://github.com/pyca/cryptography/commit/84e3e6213d1de84893bd07c00e3616d420295511 is the commit where we added tests on these arches. https://github.com/pyca/cryptography/commit/e978ba79dc384517c1576ffc5abd55498d1485b1 is where we removed it.

https://travis-ci.org/github/pyca/cryptography/builds/679485851 was a fairly typical build with them enabled -- 2-3x the runtime of any other tests. (I guess ppc and s390x were actually ok, I suppose we could have kept them).

If you're interested in finding a way to speed up our tests, we'd love to see it! More than happy to help as we can.

**Comment by hrw** [comment]
The problem is that aarch64 cores are usually slower than x86-64 ones so processors get more of them. Will take a look.

**Comment by alex** [comment]
Abstractly I guess that's true, but AFAICT Travis provides the same number of x86-64 cores as they do aarch64 cores. (Not that it matters for this, but AFAIK both AWS and Apple's aarch64 cores are close to x86-64 in performance per core)

**Comment by reaperhulk** [comment]
I'm going to close this in favor of #5292 since quite a bit of discussion has happened there now and we just need one tracking bug.
