### ISSUE TITLE
Change the length of base64-encoded

### ISSUE THREAD

**Issue by cyang38** [pyca/cryptography#5103]
Hi there,

these are more like a question then bug:
1. How to change the length of the code? It seems very long (128-bit?)
2. It doesn't recognize the same message and encrypt differently. This might cause discrepancies for further analysis.

![image](https://user-images.githubusercontent.com/43391038/72537244-c78e9600-3849-11ea-9de1-b05a3167dd20.png)

Please let me know if you know how to resolve this.

**Comment by alex** [comment]
1. You don't. There's necessary overhead for an IV, MAC, etc.

2. It's not supposed to. You can't have semantic security without the output being randomized.
