### ISSUE TITLE
ValueError in .rfc4514_string()

### ISSUE THREAD

**Issue by adepasquale** [pyca/cryptography#5106]
Using `cryptography==2.8` and calling `.rfc4514_string()` on a subject/issuer containing empty strings raises a `ValueError` exception.

https://github.com/pyca/cryptography/blob/2.8/src/cryptography/x509/name.py#L96-L97

Is there any reason for doing so? I know this might not be good practice, but it prevents a quick and easy way to display some certificates. For example, this one from `code.jquery.com`:

https://censys.io/certificates/23723c81a723301885ba8825da77c145f84c1e181cc9ec94899b0f3dc33bbf3e

```
C=US, ST=, L=, O=jquery, OU=Certificate Authority, CN=code.jquery.com

**Comment by reaperhulk** [comment]
No this is a bug, we’d be happy to take a PR to fix this!
