### ISSUE TITLE
[Question] DHParameters with custom p and g

### ISSUE THREAD

**Issue by liona24** [pyca/cryptography#5112]
Hey,

is there a way to use DH with this library but choose p and g yourself?

All I can find is a way to derive the key given the public numbers, as stated in the [docs](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dh/#cryptography.hazmat.primitives.asymmetric.dh.DHPublicNumbers):
```python
pn = dh.DHParameterNumbers(p, g)
parameters = pn.parameters(default_backend())
peer_public_numbers = dh.DHPublicNumbers(y, pn)
peer_public_key = peer_public_numbers.public_key(default_backend())
```

However I'd rather generate private keys myself. Essentially I need something like this:

```python
parameters = dh.generate_parameters(generator=2, p=0xf00, backend=default_backend())
```

I don't care if this is bad in terms of security, this is rather educational. Obviously it is very easy to do this without this library, however I was wondering if I could still utilize it.

Thanks

**Comment by reaperhulk** [comment]
We don't support custom `p` during parameter generation, only custom `g` (and only two values are allowed for that). As you noted, it's easy to do this without `cryptography` and one of our API goals is to constrain the ability to shoot yourself in the foot wherever possible. As you already noted we have an escape hatch to allow you to import keys you generate yourself as needed!
