### ISSUE TITLE
OpenSSL with -DOPENSSL_NO_SRTP errors when initializing backend

### ISSUE THREAD

**Issue by karlw00t** [pyca/cryptography#5113]
When building OpenSSL with the -DOPENSSL_NO_SRTP flag, pyca/cryptography fails to initialize the default backend.

I built OpenSSL against OpenSSL_1_1_1-stable commit (a9a8863b7), with the following config:

```
./config --prefix=/home/ubuntu/openssl/build --openssldir=/home/ubuntu/openssl/build -DOPENSSL_NO_SRTP
make clean; make
make install
```

Then I get the following error:

```
(venv) ubuntu@ip-172-31-21-1:~/openssl/openssl$ python
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> default_backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/openssl/cryptography/src/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/ubuntu/openssl/cryptography/src/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/ubuntu/openssl/cryptography/src/cryptography/hazmat/backends/openssl/backend.py", line 75, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/ubuntu/openssl/cryptography/src/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/ubuntu/openssl/cryptography/src/cryptography/hazmat/bindings/_openssl.abi3.so: symbol SSL_CTX_set_tlsext_use_srtp version OPENSSL_1_1_0 not defined in file libssl.so.1.1 with link time reference
```
I'm running against head of cryptography (commit c0dbbb52). 

Using the same setup, and removing the `-DOPENSSL_NO_SRTP` flag to `config` I'm able to initialize the backend as expected.

Os
```
$ uname -a
Linux ip-172-31-21-1 4.15.0-1058-aws #60-Ubuntu SMP Wed Jan 15 22:35:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Python version:
```
$ python --version
Python 3.6.9
```

According this link [1], there are a few things that can be disabled in OpenSSL, and if you'll accept this as a bug, I'd be happy to create some script that goes through all the permutations of flags to find out what breaks when this project tries to use it.

[1] https://stackoverflow.com/questions/7827836/build-openssl-with-just-rsa-and-aes#7828924

**Comment by reaperhulk** [comment]
You’re welcome to figure out what flags are required, but in general we’re not likely to want to gate features. SRTP might be an exception, but we’d have to modify pyopenssl (I’m assuming that’s what uses it) to handle its absence.

**Comment by mattsb42-aws** [comment]
Hi Paul,

To provide a bit of context and clarification:

This is a specific case of the issue we talked about last year at PyCon, where the backend fails to load if certain bindings are missing from the OpenSSL ABI. In contrast, there are some bindings, such as RSA-OAEP with SHA2 hashes, that [in the absence of bindings] only fail when you try to use them rather than when you try to load the backend. Our end-goal here is for pyca/cryptography to exhibit this later behavior for any features that can be disabled in the standard OpenSSL build.

We realize that this is probably a bit of a niche use case, as I assume that the majority of pyca/cryptography users just use the wheels and their included binaries, but this is a use case that we need to support and we would like to work with you all to get pyca/cryptography to a point where it does.

We don't have a timeline on when we'll be able to start digging into this, but we wanted to get the conversation started to begin scoping the level of effort needed to address this as well as to start enumerating what changes will need to be made where.

**Comment by reaperhulk** [comment]
Ah, gotcha. I'm in favor of making us more robust where possible (and with the caveat that we need to make it testable to prevent regressions...without blowing up our test matrix). I look forward to seeing what your team makes of it :)

**Comment by reaperhulk** [comment]
`OPENSSL_NO_CT` is another flag we may want to consider. (ported that from #5067)

**Comment by omnigrok** [comment]
So, I've worked out a couple of things going on here (I'm from Matt's team).

One, setting `-DOPENSSL_NO_SRTP` as a Configure argument is an anti-pattern. OpenSSL treats this as something similar to `CFLAGS` you would set to control optimization - notably, it does not cause `#define OPENSSL_NO_SRTP` to show up in `<openssl/opensslconf.h>`, so there's no way for a consuming package to detect at compilation time that SRTP related symbols don't exist, and you're stuck detecting it at (dynamic) link time. `no-srtp` is the correct replacement, and does the right thing. We actually had a number of these options set internally; migrating them to the `no-*` variants fixed all of our missing symbol errors except those related to SRTP.

Two, `no-srtp` just needed some pretty straightforward work in the relevant FFI source's `CUSTOMIZATIONS` block and in `cryptography.hazmat.bindings.openssl._conditional`. I'm sending a PR for this shortly.

On the no-ct issue (#5067) I suspect it's probably just missing a check for `OPENSSL_NO_CT` [here](https://github.com/pyca/cryptography/blob/master/src/_cffi_src/openssl/ct.py#L68). I don't have much experience running with this configuration, personally, but `<openssl/ct.h>` basically guards its entire contents on it, so I imagine that's the problem.
