### ISSUE TITLE
Wheels for linux and python 3.5+

### ISSUE THREAD

**Issue by ardling** [pyca/cryptography#5130]
https://pypi.org/project/cryptography/#files
What is the reason for wheels for python 3.5+ is not present on pypi?

**Comment by alex** [comment]
https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-python-3-6-on-linux-or-macos

**Comment by ardling** [comment]
There are no 3.5+ wheels for linux at all, only for 3.4. `pip` in my docker is trying to do `bdist_wheel` and failing without `gcc`.

**Comment by ardling** [comment]
pip 20.0.2 correctly install `cryptography-2.8-cp34-abi3` from the wheel, thank you.
