### ISSUE TITLE
Backend._cipher_registry breaks inheritance

### ISSUE THREAD

**Issue by bladebryan** [pyca/cryptography#5135]
I want to subclass AES and TripleDES, so that my child classes keep all the good stuff and also know certain codings specified in obscure standards or proprietary command sets. Here's a minimal test case showing my problem...

This works:

	from cryptography.hazmat.primitives.cmac import CMAC
	from cryptography.hazmat.backends import default_backend

	from cryptography.hazmat.primitives.ciphers.algorithms import AES

	cm = CMAC(AES(b'asdfghjklqwertyu'), default_backend())

This fails:

	from cryptography.hazmat.primitives.cmac import CMAC
	from cryptography.hazmat.backends import default_backend

	from cryptography.hazmat.primitives.ciphers import algorithms

	class AES(algorithms.AES):
		pass

	cm = CMAC(AES(b'asdfghjklqwertyu'), default_backend())

With:

	Traceback (most recent call last):
	  File "C:/bin/Python38/min_test_fail.py", line 9, in <module>
		cm = CMAC(AES(b'asdfghjklqwertyu'), default_backend())
	  File "C:\bin\Python38\lib\site-packages\cryptography\hazmat\primitives\cmac.py", line 31, in __init__
		self._ctx = self._backend.create_cmac_ctx(self._algorithm)
	  File "C:\bin\Python38\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 724, in create_cmac_ctx
		return _CMACContext(self, algorithm)
	  File "C:\bin\Python38\lib\site-packages\cryptography\hazmat\backends\openssl\cmac.py", line 19, in __init__
		raise UnsupportedAlgorithm("This backend does not support CMAC.",
	cryptography.exceptions.UnsupportedAlgorithm: This backend does not support CMAC.

Diagnosis:

To determine whether an algorithm supports a mode, in the case AES and CMAC, Backend looks up them up in its _cipher_registry, which is a dict keyed on tuples of (type(algorithm), type(mode)). My subclass is capable of supporting CMAC, but of course it's not in _cipher_registry, so the lookup fails and Backend rejects the operation.

I can fix it by putting my subclass in the same places as the base:

	from cryptography.hazmat.backends import default_backend
	backend = default_backend()

	def cryptography_lib_cipher_inhert(base, subclass):
		for cipher, mode in list(backend._cipher_registry):
			if cipher ==  base:
				backend._cipher_registry[subclass, mode] = backend._cipher_registry[base, mode]

	cryptography_lib_cipher_inhert(algorithms.AES, AES)

Great, now my self-tests all pass again. But of course I know what that leading underscore in _cipher_registry means. As a client, I should not be messing with the library's private variables.

I think the lookup should be re-worked to respect inheritance.

My version info:

	I:\>py
	Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
	Type "help", "copyright", "credits" or "license" for more information.

	I:\>py -m pip install --upgrade cryptography
	Requirement already up-to-date: cryptography in c:\bin\python38\lib\site-packages (2.8)
	Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in c:\bin\python38\lib\site-packages (from cryptography) (1.13.2)
	Requirement already satisfied, skipping upgrade: six>=1.4.1 in c:\bin\python38\lib\site-packages (from cryptography) (1.13.0)
	Requirement already satisfied, skipping upgrade: pycparser in c:\bin\python38\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography) (2.19)

**Comment by alex** [comment]
It is not intended that you would ever subclass any type in cryptography, so this is a wont-fix for us.

**Comment by bladebryan** [comment]
Well, I cannot say you guys are slow or unresponsive.
