### ISSUE TITLE
Failure to parse a valid X.509 certificate

### ISSUE THREAD

**Issue by HQJaTu** [pyca/cryptography#5137]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
  * cryptography: 2.8
  * cffi: 1.11.5
  * pip: 20.0.2
  * setuptools: 40.8.0
* How you installed ``cryptography``
`pip3 install cryptography`
* Clear steps for reproducing your bug

This problem is easily reproducible and depending on specific data on a X.509 certificate.
Example code is trivial:
```python
from cryptography import x509
from cryptography.hazmat.backends import default_backend

st_cert = open('ftp.gijonfilmfestival.com-pem.cer', 'rb').read()
cert = x509.load_pem_x509_certificate(st_cert, default_backend())
cert.extensions
```

Emitted ValueError:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/cryptography/utils.py", line 170, in inner
    result = func(instance)
  File "/usr/local/lib64/python3.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 127, in extensions
    self._backend, self._x509
  File "/usr/local/lib64/python3.7/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 249, in parse
    "parsed".format(oid)
ValueError: The <ObjectIdentifier(oid=1.3.6.1.5.5.7.48.1.5, name=OCSPNoCheck)> extension is invalid and can't be parsed
```

Looking at the decoded ASN.1, the sequence simply has no data in it. That's because RFC 6960 in _4.2.2.2.1.  Revocation Checking of an Authorized Responder_ specifies following: 

> A CA may specify that an OCSP client can trust a responder for the
> lifetime of the responder's certificate.  The CA does so by
> including the extension id-pkix-ocsp-nocheck.  This SHOULD be a
> non-critical extension.  The value of the extension SHALL be NULL.

Code in `_X509ExtensionParser.parse()` (https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/decode_asn1.py#L245) assumes NULL value to be an error. In this particular case, it is not.

Suggested patch:
```
--- "cryptography/hazmat/backends/openssl/decode_asn1 - orig.py"        2020-02-11 20:45:23.438356100 +0200
+++ cryptography/hazmat/backends/openssl/decode_asn1.py 2020-03-14 10:30:37.076339000 +0200
@@ -243,11 +243,12 @@
             else:
                 ext_data = backend._lib.X509V3_EXT_d2i(ext)
                 if ext_data == backend._ffi.NULL:
-                    backend._consume_errors()
-                    raise ValueError(
-                        "The {} extension is invalid and can't be "
-                        "parsed".format(oid)
-                    )
+                    if not oid in [ExtensionOID.OCSP_NO_CHECK]:
+                        backend._consume_errors()
+                        raise ValueError(
+                            "The {} extension is invalid and can't be "
+                            "parsed".format(oid)
+                        )

                 value = handler(backend, ext_data)
                 extensions.append(x509.Extension(oid, critical, value))
```

A sample certificate in attached.
[ftp.gijonfilmfestival.com-cer.zip](https://github.com/pyca/cryptography/files/4332411/ftp.gijonfilmfestival.com-cer.zip)

**Comment by reaperhulk** [comment]
This is not a valid OCSPNoCheck extension. NULL in ASN.1 is `0500` in hex, while this certificate contains `160D4F435350204E6F20436865636B`. That's a sequence of length 13 with the value "OCSP No Check". That's not even valid ASN.1 since "OCSP No Check" here is just bytes in the sequence instead of an additional string tag with a length and the value OCSP No Check.

**Comment by HQJaTu** [comment]
I agree, the cert isn't 100% on the spec. The discrepancy on the actual value of this extension is a detail, with no significance. The fact, this extension exists is the only thing that should matter.

This library is supposed to be useful. When all the browsers in the world accept the certificate, why is this the only tool I can find to spit an exception and separating me from actual information the certificate contains?
