### ISSUE TITLE
error occurs when import cryptography.hazmat.bindings._constant_time

### ISSUE THREAD

**Issue by gayhub-dev** [pyca/cryptography#5143]
have try the following things:
* Upgrade to the latest version of ``setuptools`` and ``pip``  √
* Make sure you're on a supported version of OpenSSL   √
* Try with the latest version of ``cryptography``     √

and none of that works!
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using

python    2.7.17
cffi                1.14.0
cryptography        2.8
pip                   20.0.2
setuptools          41.2.0
pyOpenSSL           19.1.0

* How you installed ``cryptography``
pip install pyOpenSSL auto install dependency
* Clear steps for reproducing your bug
I build Cpython with openssl 1.1.1d with [this instruction](https://stackoverflow.com/questions/60213767/how-to-install-openssl-1-1-1-for-python-2-7) on windows 10 with msbuild tool v142 and it seems everything goes pretty wells,but when I run python -c "import OpenSSL" it gives me error like this 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\CPython-v2.7.17\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\CPython-v2.7.17\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
    from cryptography import x509
  File "C:\CPython-v2.7.17\lib\site-packages\cryptography\x509\__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "C:\CPython-v2.7.17\lib\site-packages\cryptography\x509\base.py", line 18, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\CPython-v2.7.17\lib\site-packages\cryptography\x509\extensions.py", line 20, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "C:\CPython-v2.7.17\lib\site-packages\cryptography\hazmat\primitives\constant_time.py", line 11, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ImportError: DLL load failed: The specified module could not be found
```
I have also try venv but still get the same error.
I 'm not sure if it's a path relative problem,the sys.path info are:
`['', 'C:\\CPython-v2.7.17\\PCbuild\\win32\\python27.zip', 'C:\\CPython-v2.7.17\\DLLs', 'C:\\CPython-v2.7.17\\lib', 'C:\\CPython-v2.7.17\\lib\\plat-win', 'C:\\CPython-v2.7.17\\lib\\lib-tk', 'C:\\CPython-v2.7.17\\PCbuild\\win32', 'C:\\CPython-v2.7.17', 'C:\\CPython-v2.7.17\\lib\\site-packages']`

**Comment by reaperhulk** [comment]
Unfortunately this is almost certainly something specific to your environment. We build and test on Windows for everything and import issues like this are typically related to issues with pathing or something else related to your custom Python install, which we can't support.

**Comment by PeterHassaballah** [comment]
I have the same issue but it is fired by the generate_keys() function
