### ISSUE TITLE
ED448 and ED25519 restriction to OpenSSL 1.1.1b+

### ISSUE THREAD

**Issue by schwabe** [pyca/cryptography#5164]
Hey,

I am trying to figure out why the restriction to limit ed448 and ed25519 to OpenSSL 1.1.1b and later was put into cryptography:

- The commit cd05e2ac5b8336dac78a0dd73ec9a7baa06208c6 that introduced does not give a reason
- The [OpenSSL changelog](https://www.openssl.org/news/cl111.txt) does list anything related to ed448 or ed25519 
- I modified the code and at least on Ubuntu 18.04 with OpenSSL, key creation, CSR generation and certificate signing using EdDSA works fine.

So I wondering if I am missing something or should make a PR to change the 1.1.1b requirement to 1.1.1

**Comment by alex** [comment]
It was because of https://github.com/openssl/openssl/issues/7706 and https://github.com/openssl/openssl/issues/7693
