### ISSUE TITLE
centos7.3.1611, pypy3.6-v7.3.0-linux32/pip3 install cryptography==2.9 => pip unusable

### ISSUE THREAD

**Issue by ninousf** [pyca/cryptography#5185]
hi
cryptography does not support anymore 1.0.1 openssl version, but i succeed to install on centos7.
after the installation, pip is unusable and i can not uninstall cryptography

$ ..../pip3 uninstall cryptography
....
RuntimeError: You are linking against OpenSSL 1.0.1, which is no longer supported by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

so why i succeed to install cryptography on an unsupported openssl version ?

thanks

**Comment by alex** [comment]
You can get `uninstall` to work as described here: https://cryptography.io/en/stable/faq/#importing-cryptography-causes-a-runtimeerror-about-openssl-1-0-1
