### ISSUE TITLE
Supporting OpenSSL Engines

### ISSUE THREAD

**Issue by torin-carey** [pyca/cryptography#5186]
The OpenSSL library provides a rich and extensible interface for dealing with cryptographic tokens and dedicated accelerators through the engine API.

The vast majority of the cryptography library should already be able to transparently deal with engine supplied `EVP_PKEY` instances and OpenSSL already has functions for setting the default engines for various operations, therefore the implementation could be minimal.

The main difficulty would be deciding how an engine interface would look—a separate backend wouldn't make much sense and so there would be a decision between making a backend independent engine interface or a openssl-specific interface.

At the very least I think it would be useful to add some of the `ENGINE_` functions to the [CFFI bindings](https://github.com/pyca/cryptography/blob/master/src/_cffi_src/openssl/engine.py) so that modules could piggy-back off of cryptography's cffi bindings to provide the functionality.

**Comment by alex** [comment]
What's your actual goal here? It sounds like you want to do asymmetric private keys ops on keys in hardware devices?

**Comment by torin-carey** [comment]
That's what I'm mainly interested in. It's way outside the scope of cryptography to manage PKCS11 hardware tokens and there's ample implementation for openssl engines interfacing different hardware tokens. It would shift a lot of the issues of  "Can using X tokens be supported" over to openssl.

**Comment by alex** [comment]
So, I think the actual API we want to figure out here is something like `load_pkcs11_key(...) -> returns an EC/RSA/DSA/x25519/etc. key` -- ENGINE can be the implementation, but the public API should be about the keys, not about ENGINE.

**Comment by torin-carey** [comment]
I think even mention of pkcs11 is more low-level than needed since OpenSC provide an engine for pkcs11 interfacing.

We have the `ENGINE_load_private_key` function so at the very least, we could load a key by specifying the `engine_id` of the engine and the engine specific `key_id`. At that point the user can configure openssl outside of cryptography to load specific engines.

**Comment by h-vetinari** [comment]
Note that a lot of this will change with openssl 3.0 which should land this year (the first alpha should be in a few weeks) - basically all things engine are getting (more or less [explicitly](https://github.com/openssl/openssl/pull/11082#issuecomment-585561943)) deprecated, and replaced with "providers".

I mean, it would be great to have an API for both, but if that's unrealistic, then perhaps focusing on providers is the more sustainable path.

**Comment by paulidale** [comment]
3.0 will include APIs for both engines and providers.  At some point 5+ years in the future, engines will be removed.  Given a choice, the provider interface should be used.

**Comment by h-vetinari** [comment]
>  Given a choice, the provider interface should be used.

This is what I was getting at.

**Comment by reaperhulk** [comment]
Providers are definitely a better model and hopefully we can support them. One trick will be whether they can be reasonably supported with our static wheels, e.g. is it possible to load a dynamic provider with the statically linked OpenSSL we ship? If not this gets very annoying very quickly.

**Comment by jasiek** [comment]
This would be very useful to us as well - our use case is to use keys stored in AWS KMS for signing. I share @h-vetinari's view that it would be beneficial to have support for both APIs, as some folks may be stuck on 1.1 for reasons which they do not control.

**Comment by reaperhulk** [comment]
Closing for now as #5449 hopefully covers the requirements. If not please open a new issue!
