### ISSUE TITLE
Cant you make this libarary for C# development? Please!

### ISSUE THREAD

**Issue by kumarrahulkush** [pyca/cryptography#5194]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security/

**Comment by reaperhulk** [comment]
Rewriting this library in an entirely different language is not something we're interested in. If other developers want to implement the API we've built here in C# they can, but I suspect C#'s idioms would suggest a different API anyway.

**Comment by kumarrahulkush** [comment]
thanks for confirmation
