### ISSUE TITLE
unstructuredName in CSR

### ISSUE THREAD

**Issue by ybizeul** [pyca/cryptography#5203]
I'm moving my code from shell scripts using `openssl` CLI to Cryptography.

Great experience by the way, I want to mention the documentation is excellent and the examples very useful.

Anyway, in my current code, I have two attributes that I use that are not part of the CSR subject :

`unstructuredName` and `challengePassword`

I'm not sure how to move these over to Cryptography, I was able to find useful informations on StackOverflow [here](https://stackoverflow.com/questions/54202632/openssl-optionalcompanyname-optional-company-name-in-command), but I still don't see how to implement. I'm not even sure they are used, but it's possible some CA requires it.

Thanks !

**Comment by alex** [comment]
We now supported reading these, generating them is tracked in #4902
