### ISSUE TITLE
unsupported OID 1.2.840.113549.1.9.1 ("emailAddress") in cryptography.x509.name

### ISSUE THREAD

**Issue by fabricemarie** [pyca/cryptography#5245]
Environment:
* MacOS Catalina 10.15.3 (19D76)
* Python 3.6.10
* cryptography 2.9.2
* cffi 1.14.0
* pip 20.0.2
* pycparser 2.20
* setuptools 46.1.3
* six 1.14.0
* wheel 0.34.2
* OpenSSL compatibility version 1.0.0, current version 1281.0.0

`NameAttribute` doesn't seem to support the OID `1.2.840.113549.1.9.1` found in distinguished names of issuers or subjects.

Example:
```
OpenSSL     : Subject: C=EE, O=AS Sertifitseerimiskeskus, CN=EE Certification Centre Root CA/emailAddress=pki@sk.ee
cryptography: Subject: C=EE, O=AS Sertifitseerimiskeskus, CN=EE Certification Centre Root CA, 1.2.840.113549.1.9.1=pki@sk.ee
```

Example above is from this certificate (found in list of trusted CAs in Android):
```
-----BEGIN CERTIFICATE-----
MIIEAzCCAuugAwIBAgIQVID5oHPtPwBMyonY43HmSjANBgkqhkiG9w0BAQUFADB1
MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1
czEoMCYGA1UEAwwfRUUgQ2VydGlmaWNhdGlvbiBDZW50cmUgUm9vdCBDQTEYMBYG
CSqGSIb3DQEJARYJcGtpQHNrLmVlMCIYDzIwMTAxMDMwMTAxMDMwWhgPMjAzMDEy
MTcyMzU5NTlaMHUxCzAJBgNVBAYTAkVFMSIwIAYDVQQKDBlBUyBTZXJ0aWZpdHNl
ZXJpbWlza2Vza3VzMSgwJgYDVQQDDB9FRSBDZXJ0aWZpY2F0aW9uIENlbnRyZSBS
b290IENBMRgwFgYJKoZIhvcNAQkBFglwa2lAc2suZWUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDIIMDs4MVLqwd4lfNE7vsLDP90jmG7sWLqI9iroWUy
euuOF0+W2Ap7kaJjbMeMTC55v6kF/GlclY1i+blw7cNRfdCT5mzrMEvhvH2/UpvO
bntl8jixwKIy72KyaOBhU8E2lf/slLo2rpwcpzIP5Xy0xm90/XsY6KxX7QYgSzIw
WFv9zajmofxwvI6Sc9uXp3whrj3B9UiHbCe9nyV0gVWw93X2PaRka9ZP585ArQ/d
MtO8ihJTmMmJ+xAdTX7Nfh9WDSFwhfYggx/2uh8Ej+p3iDXE/+pOoYtNP2MbRMNE
1CV2yreN1x5KZmTNXMWcg+HCCIia7E6j8T4cLNlsHaFLAgMBAAGjgYowgYcwDwYD
VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFBLyWj7qVhy/
zQas8fElyalL1BSZMEUGA1UdJQQ+MDwGCCsGAQUFBwMCBggrBgEFBQcDAQYIKwYB
BQUHAwMGCCsGAQUFBwMEBggrBgEFBQcDCAYIKwYBBQUHAwkwDQYJKoZIhvcNAQEF
BQADggEBAHv25MANqhlHt01Xo/6tu7Fq1Q+e2+RjxY6hUFaTlrg4wCQiZrxTFGGV
v9DHKpY5P30osxBAIWrEr7BSdxjhlthWXePdNl4dp1BUoMUq5KqMlIpPnTX/dqQG
E5Gion0ARD9V04I8GtVbvFZMIi5GQ4okQC3zErg7cBqklrkar4dBGmoYDQZPxz5u
uSlNDUmJEYcyW+ZLBMjkXOZ0c5RdFpgTlf7727FE5TpwrDdr5rMzcijJs1eg9gIW
iAYLtqZLICjU3j2LrTcFU3T+bsy8QxdxXvnFzBqpYe73dgzzcvRyrc9yAjYHR8/v
GVCJYMzpJJUPwssd8m92kMfMdcGWxZ0=
-----END CERTIFICATE-----
```

**Comment by reaperhulk** [comment]
RFC 4514 does not define emailAddress so we don't currently support it in the __repr__ or rfc4514_string() methods. In fact, email addresses in subject DNs are hypothetically The Wrong Thing To Do if you read the gospel of X.500, but try telling that to the web PKI. You can see that we do understand what the OID is by looking at the `issuer` attribute.

This could be fixed (very easily), but it's unclear to me if that would violate the rfc4514 string spec.

**Comment by alex** [comment]
I'm going to declare that since this is a a UI issue in a method named `rfc4514_string()` that we ought to just be following RFC 5414.
