### ISSUE TITLE
DTLS fragment setup failed

### ISSUE THREAD

**Issue by moliqingwa** [pyca/cryptography#5253]
I am using aiortc to WebRTC communication, which depends on cryptography. During DTLS handshake the DTLS package is larger than MTU (1500), so we want to fragment in DTLS, but it failed by setting this:

```
# SSL init
self.__ctx = certificate._create_ssl_context()

ssl = lib.SSL_new(self.__ctx)
self.ssl = ffi.gc(ssl, lib.SSL_free)

# Disable automatic MTU discovery.
lib.SSL_CTX_set_options(self.__ctx, lib.SSL_OP_NO_QUERY_MTU);
# Set MTU of datagrams so it fits in an UDP packet.
lib.SSL_set_mtu(self.__ctx, 1200)  # ERROR: AttributeError: module 'lib' has no attribute 'SSL_set_mtu'
```

How to setup DTLS fragment of the library? Thanks:)

**Comment by reaperhulk** [comment]
`SSL_set_mtu` is not in our bindings at this time. It sounds like we need to add it for this use case. Are you just directly using the bindings to build DTLS tunnels?

**Comment by moliqingwa** [comment]
> `SSL_set_mtu` is not in our bindings at this time. It sounds like we need to add it for this use case. Are you just directly using the bindings to build DTLS tunnels?

No, I used aiortc library, which use bio and openssl like the following way: 

```
ssl = lib.SSL_new(self.__ctx)
self.ssl = ffi.gc(ssl, lib.SSL_free)

self.read_bio = lib.BIO_new(lib.BIO_s_mem())
self.read_cdata = ffi.new("char[]", 1500)
self.write_bio = lib.BIO_new(lib.BIO_s_mem())
 self.write_cdata = ffi.new("char[]", 1500)  # currently, I have to enlarge this value to 2000 in case the handshake package larger than MTU(1500), it will be cut off of the full packet.
 lib.SSL_set_bio(self.ssl, self.read_bio, self.write_bio)
```

Current I have to parse the raw package to make it fragement rightly, I am considering if there is a nice way to handle this case?

**Comment by reaperhulk** [comment]
I think using `SSL_set_mtu` to have OpenSSL do DTLS fragmenting for you to avoid MTU issues makes sense. We can add the binding here, but it'd be nicer for users if `aiortc` exposed an API to set it rather than requiring users invoke a C function directly. You should consider opening an issue on their project as well. If you'd like to add the binding you can add it to the `FUNCTIONS` section of `_cffi_src/openssl/ssl.py` with the definition `long SSL_set_mtu(SSL *, long);`.

**Comment by moliqingwa** [comment]
Thanks a lot, I'll try it. If it's works, I'll contact to `aiortc` group. THanks again.

**Comment by moliqingwa** [comment]
Sorry to bother again, but this time the `publisher` side has connected successfully, but `subscriber` failed. Do you know why this happens? I have no idea about this issue.

![snapshot_by_wireshark](https://user-images.githubusercontent.com/6396473/82888038-6c00b180-9f7b-11ea-8458-be0b1faa2bf2.jpg)

**Comment by reaperhulk** [comment]
I don't know enough about DTLS to diagnose that issue, sorry.

**Comment by moliqingwa** [comment]
It's all right, it did a lot help for me and I am really appreciate it anyway:)
