### ISSUE TITLE
pip install fancyimpute

### ISSUE THREAD

**Issue by Santoshkumargullala** [pyca/cryptography#5258]
<img width="960" alt="pip install fancyimpute" src="https://user-images.githubusercontent.com/60222573/82830987-ce52a700-9ed4-11ea-9106-4aa343685fc2.PNG">
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security/

**Comment by alex** [comment]
This doesn't appear to have anything to do with cryptography.
