### ISSUE TITLE
cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: pthread_atfork

### ISSUE THREAD

**Issue by oddbytes** [pyca/cryptography#5260]
Hello, 

Found on Linux Synology_DS 3.2.40 #24922 Mon Aug 19 12:09:30 CST 2019 armv7l GNU/Linux synology_armada370_213j

Python 3.7.1 with cryptography 2.9.2, pip 20.1.1, cffi 1.14.0, setuptools 46.4.o

Installed with pip install 
  or
compiled with python3 setup.py build

```
python3 -c "from cryptography.hazmat.bindings._openssl import ffi"
File "<string>", line 1, in <module>
ImportError: /opt/local/lib/python3.7/site-packages/cryptography-2.9.2-py3.7-linux-armv7l.egg/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: pthread_atfork
```

Seems to be the same as #5084 but can't find the reason, as that was addressed, any hint?

Thanks

**Comment by reaperhulk** [comment]
We dynamically link pthread for this, which is normally provided by libc. Googling a bit seems to indicate libpthread is a known problem on Synology NASes.

However, this symbol is not even one we use on modern cryptography packages so we should also modify our builds to completely remove it when linking against OpenSSL >1.1.1 (d or f or whichever one fixed fork safety).

**Comment by reaperhulk** [comment]
I dug deeper here and OpenSSL (unsurprisingly) uses pthreads for locking callbacks internally. You'll need to sort out the generic Synology issue here as there's nothing really for us to do.

**Comment by oddbytes** [comment]
Thank you Paul. I'm afraid my expertise in Linux systems is not enough and I thought the problem was with the cryptography module. 
Best regards,
