### ISSUE TITLE
[Feature-Request] XChaCha20-Poly1305 Support

### ISSUE THREAD

**Issue by VeNoMouS** [pyca/cryptography#5267]
Is XChaCha20-Poly1305 support going to added into this library since its considered the safer standard over AES256-GCM?

**Comment by reaperhulk** [comment]
This library depends directly on OpenSSL and is therefore limited in its primitives to what OpenSSL supports. XChaCha20 is not a supported algorithm (and is not planned for the upcoming 3.0 release) so we won't be adding it any time soon, sorry.

**Comment by VeNoMouS** [comment]
ah, thanks for the awesome response time ❤️ and direct answer, appreciate it
