### ISSUE TITLE
OID name method should be public

### ISSUE THREAD

**Issue by nileshgr** [pyca/cryptography#5268]
I think the OID name parameter in https://cryptography.io/en/latest/_modules/cryptography/hazmat/_oid/#ObjectIdentifier should be public

**Comment by alex** [comment]
It's intentional that these are not a public API. This is because OID names aren't stable, they're not specified anywhere, they're just our best attempt to find something in common use. As a result, their only utility is for debugging, which is expressed via the `repr()`.
