### ISSUE TITLE
[Feature Request] Create PKCS12 files

### ISSUE THREAD

**Issue by sagiweissce** [pyca/cryptography#5274]
Hi,

Is it planned to add PKCS12 file creation?
Will you please be able to add it?
Currently can't be done is I need to use pyopenssl.

Thanks much,

Sagi Weiss.

**Comment by reaperhulk** [comment]
We would like to. This request already exists as https://github.com/pyca/cryptography/issues/4952 so I'll close in favor of that. The current status is that we need someone to step forward to design an API that we're happy with!
