### ISSUE TITLE
Can not create certificate with OCSP_no_check

### ISSUE THREAD

**Issue by Olegandr** [pyca/cryptography#5282]
Hi, 
I am trying to use 
`builder = builder.add_extension(x509.OCSPNoCheck, critical=False)`
but I get 
\cryptography\x509\base.py", line 567, in add_extension
    raise TypeError("extension must be an ExtensionType")
While it should be a extension type if i am reading [documentation ](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.OCSPNoCheck) right. 
Or maybe I  am missing something here. What is correct way to add OCSPNoCheck extention to the certificate?

**Comment by alex** [comment]
You need to instantiate it: `x509.OCSPNoCheck()`
