### ISSUE TITLE
[WINDOWS/OTHERS ?] Cryptography not working in embedded zip 

### ISSUE THREAD

**Issue by eblaudy** [pyca/cryptography#5293]
Hi,
For the project I'm working (WAPT) we want to use cryptography in a site-packages zip (because we deploy agents and the deployment can be faster with only one zip than multiple copy of files). Python can't loads DLLs/PYDs directly from the zip so I moved them in a DLLs directory which is in the path (he is declared in a python3X._pth). The problem is that you use relative imports for the PYDs : 
_padding.pyd
_openssl.pyd
If I change them to absolute imports it works (for ex : "from cryptography.hazmat.bindings._openssl import ffi, lib" --> "from _openssl import ffi, lib"). I think there is the same problem in others platforms :)

Would it be possible to integrate this changes in the next release? I you want I can make a PR

Lines concerned for Windows : 
https://github.com/pyca/cryptography/blob/63d337e5cc01c026e16b51a1c0b7aba40d9108ef/src/cryptography/hazmat/primitives/padding.py#L13
https://github.com/pyca/cryptography/blob/63d337e5cc01c026e16b51a1c0b7aba40d9108ef/src/cryptography/hazmat/bindings/openssl/binding.py#L14

**Comment by alex** [comment]
Changing from imports inside of cryptography is not a correct fix. If you're extracting files, you need to have them match the import structure that the library expects
