### ISSUE TITLE
Document openssl-compatible symmetric encryption

### ISSUE THREAD

**Issue by mflaxman** [pyca/cryptography#5296]
The example in the docs is very easy to follow:
https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.Cipher
```python
import os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
backend = default_backend()
key = os.urandom(32)
iv = os.urandom(16)
cipher = Cipher(algorithms.AES(key), modes.CBC(iv), backend=backend)
encryptor = cipher.encryptor()
ct = encryptor.update(b"a secret message") + encryptor.finalize()
```

So, I save these values to a file:
```python
with open("key.bin", "wb") as f:
    f.write(key)

with open("ciphertext.enc", "wb") as f:
    f.write(ct)
```

When I try to decrypt the resulting output with `openssl` I get errors:
```bash
$ openssl enc -d -aes-256-cbc -kfile key.bin -in ciphertext.enc --nosalt
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
4546301376:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:583:
```

I think I must be doing something wrong regarding the IV, salt, encoding (binary/hex), etc. Since this library uses `openssl` under the hood I figure it must be possible to generate an `openssl` compatible output!

Thanks.

**Comment by alex** [comment]
The `openssl` CLI's encryption is not acceptable to us, because it doesn't include a MAC over the input and the default key derivation is some goofy home-made MD5 based things. As a result we will neither directly implement it, nor document how to. Best of luck.

**Comment by mflaxman** [comment]
Thanks for the instant reply!

Would you be willing to surface an example for decrypting only? The use-case is someone who has a lot of files previously encrypted via something like `$ openssl enc -aes-256-cbc -k foo -in secret.txt` and wants to decrypt them with your library.

> the default key derivation is some goofy home-made MD5 based things

FYI: I believe `openssl` now uses sha256, but they upgraded to it in a non-backwards compatible way which is a whole other mess :(

**Comment by mflaxman** [comment]
For others who may be stuck on this, I found a solution that's not great but does demonstrate compatibility:
```bash
$ echo hello | openssl enc -aes-256-cbc -k foo -iv 00000000000000000000000000000000 --nosalt -base64
nnwPfnlQVMcN31lA0BbcvA==
```

Recover secret (`hello`):
```python
from base64 import b64decode
from hashlib import sha256

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
backend = default_backend()


IV = bytes.fromhex('00000000000000000000000000000000')
KEY = sha256(b'foo').digest()
CT = b64decode("nnwPfnlQVMcN31lA0BbcvA==")

cipher = Cipher(algorithms.AES(KEY), modes.CBC(IV), backend=backend)
decryptor = cipher.decryptor()
plaintext = decryptor.update(CT) + decryptor.finalize()
print(plaintext.strip())  # ignores padding issues!
```

Obviously, don't use a dangerously insecure key/IV and this has padding issues! I just wanted to show that it is indeed compatible. `openssl`s KDF is far from ideal, which is why I just side-stepped it for this example :(

People who are interested can see more here:
https://security.stackexchange.com/questions/29106/openssl-recover-key-and-iv-by-passphrase

**Comment by mflaxman** [comment]
Update:

You can pass in `-K 2C26B46B68FFC68FF99B453C1D30413413422D706483BFA0F98A5E886266E7AE` (uppercase `K`) for the same result:
```bash
$ echo hello | openssl enc -aes-256-cbc -a -K 2C26B46B68FFC68FF99B453C1D30413413422D706483BFA0F98A5E886266E7AE -iv 00000000000000000000000000000000  --nosalt
nnwPfnlQVMcN31lA0BbcvA==
```

**Comment by reaperhulk** [comment]
That's useful information, but probably not something we directly want in our documentation. Glad you figured it out though (and hopefully future searchers will find this or whatever article you write up about it!)
