### ISSUE TITLE
[Feature Request] Non-compact-representation of ECDH

### ISSUE THREAD

**Issue by the-infinity** [pyca/cryptography#5320]
While learning [how to implement ECIES](https://github.com/pyca/cryptography/issues/4093) I stumbled acress a degree of freedom you have when you use ECDH to get the data for KDF. ECDH has a compact and a full representation. This is because ECDH basicly is a multiplication of a skalar (senders private key) and a vector (receivers public key). As a result, you get a vector, reads: x and y.

cryptographys implementation returns just x. This seems to be absolutely ok: as stated in RFC 6090 this is called ["compact reprsentation" and is as secure as the full representation](https://tools.ietf.org/html/rfc6090#section-4.2).

There are other libraries which use the full representation. For sake of interoperability I think it would be a good idea to (optionally) support full representation, too.

Side-quesion, by the way: is using the x coordinate only really as secure as using the full vector, or is there any current research which prooves the RFC statement wrong?

**Comment by reaperhulk** [comment]
[Appendix C](https://tools.ietf.org/html/rfc6090#appendix-C) explains why compact representation is secure. Mathematically there are only two possible values for y for a given x on a curve.

What libraries require the full uncompressed point on ECDH?

**Comment by alex** [comment]
As far as I know, we support encoding keys as both compressed and uncompressed: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicKey.public_bytes

**Comment by reaperhulk** [comment]
@alex we do but @the-infinity is talking about the result of an ECDH `exchange`, which we return as an opaque byte string representation of the x coordinate of the resulting shared point.

**Comment by the-infinity** [comment]
[eciespy does](https://github.com/ecies/py/blob/master/ecies/utils.py#L143), and its brother and sister libraries in other languages do so, too. I'm far from being an expert, so I don't have the overview about other libraries, but because the ISO proposal is not exacly clear I thought it would be worth to have the option to get y, too.

Oh, and it was quite confusing for the start, but in the process of finding out what went wrong between my own ECIES implementation based on crytography and eciespy I learned a lot, so ...  maybe this was the hard way to learn cryptographic basics. :)

**Comment by reaperhulk** [comment]
Interesting! Those libraries are making an unusual decision compared to typical cryptographic libs in my experience. We're not going to expose this any time soon since ultimately we're using OpenSSL's APIs to do ECDH. You can recover y (although without knowing sign you have to guess if it's positive or negative) using our existing APIs if you're clever, but doing more would require significantly departing from our underlying dependencies.

**Comment by the-infinity** [comment]
Ok, thank you! Then I think discovering y is my next weekends "playing around with cryptography"-session. :)
