### ISSUE TITLE
[docs][RTD] Enable PR builds on readthedocs

### ISSUE THREAD

**Issue by webknjaz** [pyca/cryptography#5347]
TL;DR Implementing this will add an extra status in PR builds and will generate a docs preview with a unique link for each PR.

This used to be in beta but now this feature is open to the public.
Ref: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html.

**Comment by alex** [comment]
Good call, thanks. Enabled!
