### ISSUE TITLE
Why does SSH support only 1024 bit DSA keys in 3.0?

### ISSUE THREAD

**Issue by lukpueh** [pyca/cryptography#5373]
Is there a reason why the ssh serialization module does not support DSA keys with a bit length greater than 1024 in cryptography version 3.0? I could not find any information in the corresponding PR (https://github.com/pyca/cryptography/pull/5146), git log or changelog.

These are the relevant lines that were released in 3.0.

https://github.com/pyca/cryptography/blob/143f56f65cd4c78eecdd9f09fa8e0e806f01c203/src/cryptography/hazmat/primitives/serialization/ssh.py#L330-L333

And here is a serialization/deserialization snippet that worked fine on cryptography 2.9 but raises said ValueError in 3.0:

```python
from cryptography.hazmat.primitives.serialization import (load_ssh_public_key,
        Encoding, PublicFormat)
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric.dsa import generate_private_key

# Create DSA key pair with key size != 1024
dsa_key = generate_private_key(key_size=2048, backend=default_backend())

# Dump to SSH
ssh_bytes = dsa_key.public_key().public_bytes(Encoding.OpenSSH, PublicFormat.OpenSSH)

# Parse from SSH
dsa_key_parsed = load_ssh_public_key(ssh_bytes, backend=default_backend()) # BREAKS ON v3.0

# Assert that no public key info was lost in serialization
assert dsa_key.public_key().public_numbers() == dsa_key_parsed.public_numbers()
```

Context: 
The update just broke some test code in a project I maintain (https://github.com/secure-systems-lab/securesystemslib/pull/261). I'm fine in changing the test code, I just wanted to know if the change was intentional? Thanks! :)

(cc @markokr, @reaperhulk, @joshuagl)

**Comment by lukpueh** [comment]
Thanks for the quick reply and the pointer! I wasn't aware of that restriction.

We were using the ssh format only to store a DSA public key from a test gpg keychain as stand-alone file.  `gpg --export-ssh-key`, which we used to create the file, didn't mind that the key was 2048 bits long, and nor did cryptography when importing the key, until now.

I guess we can close this issue.

**Comment by reaperhulk** [comment]
DSA is also slowly being deprecated and removed from the ecosystem (for example, Go: https://github.com/golang/go/issues/40337). We have no plans for removal on our end at this time, but similarly we're not interested in expanding DSA support further.
