### ISSUE TITLE
Stop importing distutils in setup.py?

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#5384]
This warning is present in our CI:

> /home/travis/build/pyca/cryptography/.tox/packaging/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.

It is being triggered by our import in `setup.py`:

https://github.com/pyca/cryptography/blob/9e84c88ad3c5bf8b404fe86e22bdadd6b56e58ec/setup.py#L12

If we don't need this we probably should stop doing it.

**Comment by alex** [comment]
`build` doesn't exist in `setuptools`, so AFAICT we can't just change that import path.

The simplest fix is probably just to move that import down.

The other fix would be to remove the thingy in setup.py that all this exists for, the wacky argument parsing. I think maybe it's time.

**Comment by reaperhulk** [comment]
Putting this in milestone pending learning whether our experiment removing the keywords with side effects code on bcrypt is successful.
