### ISSUE TITLE
How to do OAEP without encryption (just padding)?

### ISSUE THREAD

**Issue by rgl** [pyca/cryptography#5425]
Normally, one would do OAEP with something like:

```python
ciphertext = public_key.encrypt(
    plaintext,
    cryptography.hazmat.primitives.asymmetric.padding.OAEP(
        mgf=cryptography.hazmat.primitives.asymmetric.padding.MGF1(algorithm=cryptography.hazmat.primitives.hashes.SHA256()),
        algorithm=cryptography.hazmat.primitives.hashes.SHA256(),
        label=None))
```

But how do I only do the padding?

Why? Well... I'm playing with [SmartCard-HSM-4K-Mini-SIM](https://www.cardomatic.de/epages/64510967.sf/en_GB/?ObjectPath=/Shops/64510967/Products/SmartCard-HSM-4K-SIM) and it only supports PKCS1v15... and I'm wondering how can I only do the padding, then, apply RSA.EncryptWithPKCS1v15 over that.

In theory this should give me the same characteristics as OAEP at the expense of a little overhead... but how do I do that with this library?

That OAEP object does not seem like a directly usable object, it seems to be some meta thing, that gets interpreted by the low level library somehow... and I really known nothing about this library, so any pointers would be appreciated :-)

**Comment by alex** [comment]
We do not have an API for doing OAEP padding without performing the encryption. This use case is overly niche for a general purpose cryptography library.

**Comment by rgl** [comment]
I understand, thanks anyways!

I ended up implementing this in Go at https://github.com/rgl/go-pkcs11-rsa-oaep.
