### ISSUE TITLE
any recipes for key-gen/signing/verification?

### ISSUE THREAD

**Issue by Al-Caveman** [pyca/cryptography#5427]

**Comment by alex** [comment]
Sadly, we don't currently -- signatures always require the hazmat layer, regrettably.

**Comment by Al-Caveman** [comment]
would it make sense to have recipes for these things?

**Comment by reaperhulk** [comment]
It would, but recipes are non-trivial to create since they require serious analysis and use case consideration. We are interested in implementing some of the constructions in tink, but we have no timeline for that at this time.

**Comment by Al-Caveman** [comment]
thanks sir for your efforts.  

i have a bonous off-topic question (in case you still have some extra coffee left):  care to give examples on such use case considerations can make a huge difference?
