### ISSUE TITLE
[BUG]OpenSSH Invalid Private Key on 3.1 but not 3.0

### ISSUE THREAD

**Issue by john-michaelburke** [pyca/cryptography#5440]
* Upgrade to the latest version of ``setuptools`` and ``pip``:  `Successfully installed pip-20.2.2`
* Make sure you're on a supported version of OpenSSL. : `openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.6)`
* Try with the latest version of ``cryptography``:
```
Package      Version
------------ -------
bcrypt       3.2.0
cffi         1.14.2
cryptography 3.1
paramiko     2.7.1
pip          20.2.2
pycparser    2.20
PyNaCl       1.4.0
setuptools   47.1.0
six          1.15.0

```

If none of that works, please make sure to include the following information in
your bug report:

* I stumbled on this issue while using paramiko when attempting to load an OpenSSH private key. Using cryptography 3.1,  I experience an this issue:
`ValueError: ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])`

* I uninstalled cryptography and reinstalled version 3.0 and the issue was resolved. The key loads fine. 

* To generate the type of key I experienced the issue with I ran this command:
`ssh-keygen -o -t rsa -b 4096 -C "your_email@example.com" -f test_rsa`

* Then pointing to that new key, I try to load the key using paramiko:
`python -c "import paramiko;paramiko.RSAKey.from_private_key_file('test_rsa')"`

* I apologize I am not showing steps to reproduce with cryptography. Hopefully, I was not in error posting this here.

**Comment by reaperhulk** [comment]
This is a bug in paramiko: https://github.com/paramiko/paramiko/pull/1723

You can see more info in #5434
