### ISSUE TITLE
OBJ_create binding is gone

### ISSUE THREAD

**Issue by cyrusdaboo** [pyca/cryptography#5450]
In #5356 a number of bindings were removed. This included the openssl/objects.py binding for the OBJ_create method. I have a project that uses that, and so it broke. So:

1) Can OBJ_create be added back?
2) If not, is there a way for me to "inject" this binding into cryptography myself? If so, then there is probably no need to to put it back if no one else is using it.

**Comment by alex** [comment]
Transferred this issue to the correct repo.

**Comment by reaperhulk** [comment]
Can you explain a bit more about why you need to be able to add objects to the internal OpenSSL table? Is it just shortname/longname mappings?

**Comment by alex** [comment]
No response after 5 days. Closing for now, we can reopen if there's a response.
