### ISSUE TITLE
md_gost12_256 support

### ISSUE THREAD

**Issue by spice0xff** [pyca/cryptography#5453]
Hi!
I enabled GOST in OpenSSL by added lines to file /etc/ssl/openssl.cnf.
And i see 'md_gost12_512' in output command openssl dgst --list

How i can use this hashing method in python code?

openssl: OpenSSL 1.1.1g  21 Apr 2020
os: Windows 10 Pro
python: 3.8

**Comment by reaperhulk** [comment]
We don’t have any plans to support this directly, but you can look at how our hashing works and patch cryptography to add a class that allows you to hash with an alternate digest. Look in hazmat/primitives/hashes and hazmat/backends/openssl to learn more.
