### ISSUE TITLE
linux_armv7l wheel is broken on RaspberryPi 4

### ISSUE THREAD

**Issue by ivankravets** [pyca/cryptography#5455]
See https://github.com/platformio/platformio-core/issues/3652

**Comment by alex** [comment]
We do not build the `linux_armv7l`, they're built by whoever runs https://www.piwheels.org/ You'll have to take this issue up with them.

**Comment by ivankravets** [comment]
Sorry, reported to https://github.com/piwheels/packages/issues/151
