### ISSUE TITLE
Cryptography key

### ISSUE THREAD

**Issue by avishah12345** [pyca/cryptography#5456]
I have the key set to a value. After multiple runs (key is the same), after encryption, the encrypted text is always different.
```
from cryptography.fernet import Fernet
key = b'sTie_TsMvLt41aCcbwJCN6JC43AHgsd-tj_cmrlENUM='
encrypter = Fernet(key)
encrypted_text = encrypter.encrypt(b"Hi")
print(encrypted_text)
decrypted_text = encrypter.decrypt(encrypted_text)
print(decrypted_text)
```

**Comment by tiran** [comment]
The Fernet algorithm is uses a new random initialization vector (IV) for AES-CBC every time. The random IV ensures that the cipher text is unpredictable. This a basic requirement for any secure encryption scheme.
