### ISSUE TITLE
Pickle-able hashes

### ISSUE THREAD

**Issue by mdr1384** [pyca/cryptography#5484]
**Feature Request**

It would be nice to have a pickle-able `Hash` object for calculating message digests on chunked file uploads. Even if it had to be imported separately as an "insecure" hash. I think that there is a py module called "rehash" that does it, but that does not seem to be a FreeBSD port, whereas cryptography is (though it sure would be nice if it was updated to version 3, seems [latest master](https://github.com/freebsd/freebsd-ports/blob/master/security/py-cryptography/Makefile) is still 2.6.1):

```
$ head /var/ports/workspace/ports/security/py-cryptography/Makefile
# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD: freebsd/ports/trunk/ports/security/py-cryptography/Makefile 51435 2019-04-08 23:26:04Z $

PORTNAME=       cryptography
PORTVERSION=    2.6.1
CATEGORIES=     security python
MASTER_SITES=   CHEESESHOP
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

MAINTAINER=     koobs@FreeBSD.org
```

(hope this is not a duplicate - I did search all issues open and closed for "hash" "pickle"...)

**Comment by alex** [comment]
Pickle is an incredibly poor format (see, "Pickles are for Delis, not Software" by Gaynor, A) so we're not going to support it at all.

Further, there's no standard format for serializing hash state, so I don't believe we should support this at all.
