### ISSUE TITLE
Wheels for Python 3.9

### ISSUE THREAD

**Issue by ivankravets** [pyca/cryptography#5487]
https://pypi.org/project/cryptography/#files

Thanks!

**Comment by alex** [comment]
https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-python-3-6-on-linux-or-macos

**Comment by ivankravets** [comment]
Windows?

**Comment by alex** [comment]
Also has abi3 wheels.

**Comment by ivankravets** [comment]
Thanks!

**Comment by kcalmwinds** [comment]
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\onedrivebusiness\onedrive - microsoft\pyprojects\botfolder\.venv\inclu10\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program 
> Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcbuild\temp.win-amd64-3.9\Release\_openssl.c /Fobuild\temp.win-amd64-3.9\Release\build\temp.win-amd64-3.9\Release\_openssl.obj
>   _openssl.c
>   build\temp.win-amd64-3.9\Release\_openssl.c(575): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

I am using 3.9 on windows 10 -  This looks like cryptography it is trying to build from source instead of the wheel.

pip 20.2.4

**Comment by reaperhulk** [comment]
That pip should be sufficiently new to detect and install the proper abi3 wheel we create. Try making a virtualenv and upgrading pip inside that (and then install cryptography) to ensure nothing weirder is occurring in your environment.

**Comment by kcalmwinds** [comment]
it most certainly is sufficient.  I did recreate the venv as you requested. In my testing, cryptography with just a pip install cryptography goes without a hitch.  

This is where things get a bit strange:

The botbuilder-framework requirements.txt show the following:

msrest==0.6.10
botframework-connector==4.10.0
botbuilder-schema==4.10.0
requests==2.23.0
PyJWT==1.5.3
cryptography==2.8.0
aiounittest==1.3.0

Using just pip install cryptography==2.8.0 will produce this same error.

But if I save requirements.txt removing the version constraint, it will, again throw the same error from a clone of the repository and a local install using pip install -e path

**Comment by reaperhulk** [comment]
The wheels for older versions of cryptography weren't built with `abi3` so we had to build them for every Python version. That predates 3.9 so no wheels exist.
