### ISSUE TITLE
Unable to build arm32 wheels on aarch64 kernel with 32bit userspace

### ISSUE THREAD

**Issue by aptalca** [pyca/cryptography#5490]
Hi,

I'm with linuxserver.io and we build and publish various docker images. For our multi-arch builds, we try to use native builders as much as we can, but during a backlog, we spin up some aws builders to help.

We have no issues with `pip install cryptography` in a docker build on native hardware on x86_64, armhf and aarch64.

However, a unique situation arises when we do an armhf build on an aws graviton instance (arm64). Aws instances only come with aarch64 kernel and OS. We install the 32bit docker package. And we use a 32bit docker baseimage (32bit userspace) to build the final docker image. Unfortunately while building the wheel for cryptography in our 32bit docker image, it incorrectly detects the system as aarch64 and pulls in the wrong dependencies, and as a result the build fails.

Here's a log: https://pastebin.com/HFQ5en4e
This is on an arm64 device (odroid c2), inside a 32bit docker image. When the same image is built on an armhf device, no issues.

Here's an example multiarch repo for local testing:
https://github.com/linuxserver/docker-ldap-auth

Simple way to reproduce:
1. On an aarch64 device (aws graviton or odroid c2), clone the repo: `git clone https://github.com/linuxserver/docker-ldap-auth`, enter folder
2. Build the armhf image: `docker build -f Dockerfile.armhf .`

If the above steps are done on an armhf device, it builds successfully.

Most other pip wheels build fine on an arm64 device in an arm32 docker baseimage.

At first I wasn't sure if it was a pip issue so I opened an issue on their repo, but no replies so far: https://github.com/pypa/pip/issues/8871
Further research showed this issue might be exclusive to cryptography.

Thanks

**Comment by reaperhulk** [comment]
This is very unlikely to be a cryptography specific bug since it's occurring in the build machinery. distutils/setuptools own platform/compiler detection, but cffi may also have something to do with this. Can you reproduce this with other cffi packages (or a trivial example)? The final exception (from wheel) isn't hugely relevant since you say it's compiling with the wrong platform target entirely.

**Comment by aptalca** [comment]
Thanks for the nudge in the right direction. I'm not very familiar with the wheel building process, but I will look into other cffi packages and try to narrow it down. I'll report back findings here.

**Comment by aptalca** [comment]
solved here: https://github.com/pypa/setuptools/issues/2443#issuecomment-719858779
