### ISSUE TITLE
Creating public key from byte array

### ISSUE THREAD

**Issue by RyanLiu6** [pyca/cryptography#5493]
Following Apple's instructions found [here](https://developer.apple.com/documentation/storekit/skadnetwork/verifying_an_install_validation_postback), they say to `Create an X.509 standard public key from the byte array.`

Specifically I want to create an ECDSA public key. Is this possible with cryptography?

Thanks!

**Comment by reaperhulk** [comment]
Yes, it is. Here's how:

```python
import base64
from cryptography.hazmat.primitives.serialization import load_der_public_key

key = load_der_public_key(base64.b64decode("MEkwEwYHKoZIzj0CAQYIKoZIzj0DAQEDMgAEMyHD625uvsmGq4C43cQ9BnfN2xslVT5V1nOmAMP6qaRRUll3PB1JYmgSm+62sosG"))
```

The above is both steps one and two.
