### ISSUE TITLE
Expose `SSL_write_ex`

### ISSUE THREAD

**Issue by webknjaz** [pyca/cryptography#5546]
Hello, I see that [`SSL_write`](
https://github.com/pyca/cryptography/blob/b0a3d89e0f69d6e460a4ae65a57ea2c721f9370b/src/_cffi_src/openssl/ssl.py#L167
) is exposed but `SSL_write_ex` isn't.

I think it's useful to have it for the purposes of solving https://github.com/pyca/pyopenssl/issues/176.
(That is if I'm reading [the docs](https://www.openssl.org/docs/man1.1.0/man3/SSL_write.html) right)

**Comment by reaperhulk** [comment]
We can expose this, but it's 1.1.1+ only. cryptography supports 1.1.0 so it'll need to be a conditional binding.

**Comment by webknjaz** [comment]
@reaperhulk thanks for the info! Any idea if `sendall()` can be implemented w/o it? I'm a little bit confused about whether there are any other ways to detect bytes that's actually been sent over the wire...

**Comment by reaperhulk** [comment]
@tiran may know the answer to this -- I don't know OpenSSL's TLS APIs well enough.

**Comment by webknjaz** [comment]
I think I've found what I was looking for, it _should be_ possible with `SSL_MODE_ENABLE_PARTIAL_WRITE` set: https://github.com/pyca/pyopenssl/issues/176#issuecomment-723674922.

**Comment by tiran** [comment]
Python's ssl module uses ``SSL_write``. The function uses negative values to report errors and positive values how many bytes were written successfully. Then it's a matter of slicind and dicing the send buffer and loop until all data was written. Python doesn't use ``SSL_MODE_ENABLE_PARTIAL_WRITE``.
