### ISSUE TITLE
Does crypthography support rsa asymetric encryption?

### ISSUE THREAD

**Issue by fadjer** [pyca/cryptography#5549]
Hi,

I don't understand the Danger warning in this page:
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa.html

Do you support rsa asymetric encryption or not yet ?

Many Thanks.

**Comment by alex** [comment]
Yes, it does. That page clearly documents this: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa.html#encryption

The warnings indicate that these APIs can be misused to introduce vulnerabilities, and that users should be sure they fully understand what they're doing.
