### ISSUE TITLE
Hash value verification issue image file meta data

### ISSUE THREAD

**Issue by malateshk** [pyca/cryptography#5550]
I have an image file and generated a signature by hashing it and by using private key. I can successfully verify the hash of the image with public key and signature value. 
1.  hash(imagefile) + privatekey -> Sigfile
     I get successful verification when the same is verified with public key and signature.
2.  hash(imagefile) + publickey + Sigfile -> Successful
    I modify the meta data of the image file and i want the verification to fail since the original image file is being modified.
3.  hash(imagefile_metadata_change) publickey + Sigfile -> It should "Fail" but I get "Successful"

Python code:
```
with open(public_key_filename, 'rb') as f:

 

    public_key = serialization.load_pem_public_key(f.read())

 

with open(file_to_verify, 'rb') as f:
    h = hashes.Hash(hashes.SHA256())
    h.update(f.read())
    payload = h.finalize()

 

with open(signature_filename, 'rb') as f:
    signature = f.read()

 

try:

 

    public_key.verify(signature, payload, padding.PKCS1v15(), hashes.SHA256())
    print("Success")
except cryptography.exceptions.InvalidSignature:
    print('ERROR: signature verification failed')
```

Basically I am expecting the below command simulation in python
1. openssl dgst -sha256 -binary -out hash.bin image.jpg
2. openssl pkeyutl -inkey private.key -in hash.bin -out image.sig -sign
3. openssl pkeyutl -pubin -inkey public.key -in hash.bin -sigfile image.sig -verify

I couldn't figure out where the issue is !!

**Comment by alex** [comment]
`verify` expects you to pass the message, not the hash. If you're passing the hash you should use https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils.html#cryptography.hazmat.primitives.asymmetric.utils.Prehashed

**Comment by malateshk** [comment]
@alex,
Tried as suggested.
`public_key.verify(signature, payload, padding.PKCS1v15(), utils.Prehashed(hashes.SHA256()))`
still the same result.

**Comment by reaperhulk** [comment]
This code works and was (very lightly) adapted from the test suite (in `test_rsa.py`). In the future I'd highly suggest looking at existing tests if you're having difficulty making something work.

```python
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.asymmetric.utils import Prehashed


private_key = rsa.generate_private_key(65537, 2048)
message = b"one little message"
h = hashes.Hash(hashes.SHA256())
h.update(message)
digest = h.finalize()
prehashed_alg = Prehashed(hashes.SHA256())
pkcs = padding.PKCS1v15()
signature = private_key.sign(message, pkcs, hashes.SHA256())
public_key = private_key.public_key()
public_key.verify(signature, digest, pkcs, prehashed_alg)
```

If you're still seeing failures the issue is the signature/message input and you'll need to debug how it was generated to replicate it for the verification phase. This is not something we can help with since it's specific to your particular case.
