### ISSUE TITLE
Certificate revocation (CRL)

### ISSUE THREAD

**Issue by fbzyx** [pyca/cryptography#5556]
I'm trying to make a certificate revocation list using the python cryptography library. So far I haven't been successful. I am able to generate the certificates with the same library. The certificates work because I am able to use them for a connection with MQTT. The problem is when I try to revoke one of the certificates. Then no connection works and I receive an error:

[![errors][1]][1]

It would be nice if someone would tell me what I am doing wrong or  how is the way to do it :)

In the documentation there is no chapter describing the procedure in detail.

Thanks in advance.

This is my code:
``` 
# THIS CERTIFICATE I WANT TO REVOKE
cert_to_revoke_data = open("openssl/client2.crt","rb").read() 

cert_to_revoke = x509.load_pem_x509_certificate(cert_to_revoke_data,
\backend=default_backend())

pem_cert = open("openssl/ca.crt","rb").read()          # MY CA CERT
ca_crt = x509.load_pem_x509_certificate(pem_cert, default_backend())

pem_key = open("openssl/ca.key","rb").read()           # MY CA KEY
ca_key = serialization.load_pem_private_key(pem_key,\
 password=b"test", backend=default_backend())

pem_crl_data = open("openssl/ca.crl","rb").read()   # READ MY EMPTY CRL

crl = x509.load_pem_x509_crl(pem_crl_data, backend=default_backend())
#isinstance(crl.signature_hash_algorithm, hashes.SHA256)

builder = x509.CertificateRevocationListBuilder()
builder = builder.last_update(datetime.datetime.now())
builder = builder.next_update(datetime.datetime.now()\
 + datetime.timedelta(1, 0, 0))

builder = builder.issuer_name(ca_crt.issuer)

revoked_cert = x509.RevokedCertificateBuilder()\
.serial_number(cert_to_revoke.serial_number)\
.revocation_date(datetime.datetime.now())\
.build(backend=default_backend()) # ADD SERIAL NUMBER OF
                                  # CERTIFICATE I WANT TO REVOKE

builder = builder.add_revoked_certificate(revoked_cert)

cert_revocation_list = builder.sign(private_key=ca_key,algorithm=hashes.SHA256()\
,backend=default_backend()) # SIGN NEW CRL

# SAVE CRL FILE
with open("openssl/ca.crl","wb") as f:
    f.write(cert_revocation_list.public_bytes(serialization.Encoding.PEM))  

``` 

  [1]: https://i.stack.imgur.com/OlxUY.png

**Comment by reaperhulk** [comment]
Unfortunately what specific things are required in a CRL can vary between various systems. That error is very odd for a CRL problem though since it appears to be failing during basic RSA signature check with invalid padding. Can you provide a reproducer script (with dummy certs/keys) so we can inspect the CRL serialization?

**Comment by fbzyx** [comment]
Hello thank you for your answer :)
I have made a jupyter notebook with all the steps i am doing and i have added all my certificates and private keys.

[files.zip](https://github.com/pyca/cryptography/files/5506954/files.zip)

**Comment by reaperhulk** [comment]
First thing that jumps out at me here is that you don't have any CRL extensions set. You'll likely need at least a CRL number (https://cryptography.io/en/latest/x509/reference.html#cryptography.x509.CRLNumber). Our example (https://cryptography.io/en/latest/x509/reference.html#cryptography.x509.CertificateRevocationListBuilder) doesn't have that right now, which should possibly be corrected. If you add a CRLNumber what happens?

**Comment by tiran** [comment]
The common encoding for CRL is not PEM but DER format. Applications often support just one import format. Please try to store your CRL in DER.

**Comment by fbzyx** [comment]
@tiran mosquitto MQTT works with PEM CRL files. I already checked that :D
@reaperhulk do you have maybe an example or piece of code that show me how to do that? 

I don't know how to handle the CRL number and python cryptography because I can't see any examples

**Comment by reaperhulk** [comment]
While examples are nice (we'd be happy to accept a PR), the documentation quite clearly explains how to do this. https://cryptography.io/en/latest/x509/reference.html#cryptography.x509.CertificateRevocationListBuilder.add_extension and https://cryptography.io/en/latest/x509/reference.html#cryptography.x509.CRLNumber are all you need to see.

**Comment by fbzyx** [comment]
like this?
![crl](https://user-images.githubusercontent.com/73341849/98483193-a2b74500-2206-11eb-976f-664ba5f66a28.png)

**Comment by reaperhulk** [comment]
Yes, but does it work? If not you should look closely at the difference between what your OpenSSL command produces and what cryptography produces. Cryptography uses OpenSSL so you will be able to produce the same structure. We're really only capable of helping with bugs that may exist in cryptography itself. Helping people with their applications isn't really feasible for us so you'll have to seek assistance elsewhere past this.

**Comment by fbzyx** [comment]
I will try and compare both outputs...

**Comment by fbzyx** [comment]
Hello. the crlnumber was not the problem. This is how it works:

`
# cert you want to revoke
cert_to_revoke_data = open("openssl/client1.crt","rb").read()
cert_to_revoke = x509.load_pem_x509_certificate(cert_to_revoke_data, backend=default_backend())

pem_cert = open("openssl/ca.crt","rb").read()
ca_crt = x509.load_pem_x509_certificate(pem_cert, default_backend())
pem_key = open("openssl/ca.key","rb").read()
ca_key = serialization.load_pem_private_key(pem_key, password=b"test", backend=default_backend())

# load crl
pem_crl_data = open("openssl/ca.crl","rb").read()
crl = x509.load_pem_x509_crl(pem_crl_data, backend=default_backend())

# generate a new crl object
builder = x509.CertificateRevocationListBuilder()
builder = builder.issuer_name(crl.issuer)
builder = builder.last_update(crl.last_update)
builder = builder.next_update(datetime.datetime.now() + datetime.timedelta(1, 0, 0))

# add crl certificates from file to the new crl object
for i in range(0,len(crl)):    
    builder = builder.add_revoked_certificate(crl[i])

# see if the cert to be revokek already in the list    
ret = crl.get_revoked_certificate_by_serial_number(cert_to_revoke.serial_number)

# if not, then add new revoked cert
if  not isinstance(ret, x509.RevokedCertificate):
    
    revoked_cert = x509.RevokedCertificateBuilder()\
    .serial_number(cert_to_revoke.serial_number)\
    .revocation_date(datetime.datetime.now()).build(backend=default_backend())
    
    builder = builder.add_revoked_certificate(revoked_cert)

# sign and save to new crl file
cert_revocation_list = builder.sign(private_key=ca_key,algorithm=hashes.SHA256(),backend=default_backend())

with open("openssl/ca.crl","wb") as f:
    f.write(cert_revocation_list.public_bytes(serialization.Encoding.PEM))
    
    `
