### ISSUE TITLE
Allow filtering python 2.7 and OpenSSL 1.0.2 deprecation warning.

### ISSUE THREAD

**Issue by adiroiban** [pyca/cryptography#5566]
The problem is that custom CryptographyDeprecationWarning is raised in the root package.

This was introduced in #5251

So in order to filter it, you will have to import CryptographyDeprecationWarning first.... but when you try to import it, the deprecation is raised right away.

This issue was also raised here https://github.com/pyca/cryptography/pull/5251/files#r457896629 by @webknjaz 

My suggestion is to move the deprecation raising into `hazmat.__init___`
In this way, one can import CryptographyDeprecationWarning first without raising a warning.

What do you think?

The OpenSSL 1.0.2 is present on RHEL 7 and AMAZON Linux 2

I can send a PR if you think that this is useful.

Thanks!

**Comment by alex** [comment]
Does https://cryptography.io/en/latest/faq.html#i-cannot-suppress-the-deprecation-warning-that-cryptography-emits-on-import not work?

**Comment by adiroiban** [comment]
Hi Alex, thanks for the link.

I am not using pytest.

I have a list of ignored warnings that is used by both CI testing and PROD runtime.

For now, I am just ignoring any UserWarning from cryptography .... but it would be nice to be able to ignore only the deprecation warnings.

```
import warninigs
warnings.filterwarnings(
    'ignore',
    category=UserWarning,
    module='cryptography',
    )
```

If you don't want to see any changes here, that is fine and you can just close the ticket.

I guess that 99% of the Linux users will use the PyPI wheel and have an up to date OpenSSL 

Cheers

**Comment by alex** [comment]
`warnings.filterwarnings` takes a `message` parameter which you can use to control what you're ignoring.
