### ISSUE TITLE
RSA encrypt limitation and getting the RSAPrivateNumbers 

### ISSUE THREAD

**Issue by mickiticki** [pyca/cryptography#5576]
Hello everyone. I'm pretty new to this python and crypto stuff, and despite the warnings in the documentation, I'm still interested in this world.

The point is that I have written a little script that creates and stores a private key and then uses it to encrypt and decrypt a given text.
Code:
```
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateNumbers

from time import sleep
pri_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
)

f = open("pri_key.pem", "wb")
f.write(pri_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.TraditionalOpenSSL,
    encryption_algorithm=serialization.NoEncryption(),
))
f.close()
pub_key = pri_key.public_key()
f = open("pub_key.pem", "wb")
f.write(pub_key.public_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PublicFormat.SubjectPublicKeyInfo,
))

data = input("DATA TO ENCRYPT:")
message = bytes(data, 'utf-8')

ciphertext = pub_key.encrypt(
    message,
    padding.OAEP(
        mgf=padding.MGF1(algorithm=hashes.SHA512()),
        algorithm=hashes.SHA512(),
        label=None
    )
)
plaintext = pri_key.decrypt(
    ciphertext,
    padding.OAEP(
        mgf=padding.MGF1(algorithm=hashes.SHA512()),
        algorithm=hashes.SHA512(),
        label=None
    )
)
print("ENCRYPTED DATA:\n" + str(ciphertext))
print("DECRYPTED DATA:\n" + str(plaintext))
``` 

In this regard, two questions arise:
1. Is there any possibility to get the numbers p, q (and other private numbers) from a private key (before creating it) I found the `RSAPrivateNumbers`, but I,m unable to use properly
2. I´m have some limitations using the `pub_key.encrypt()` method, in my case it does not allow me to encrypt more than 126 characters, there is a method such as Verification and Signing, to be able to update the hash if it is too long.

Thanks

**Comment by reaperhulk** [comment]
It is not possible to get numbers before you create them, no. If you want the numbers you can generate a private key and then call `private_numbers()` on the object to get those numbers. Be aware that this representation exists as an escape hatch to allow for users to transform formats. Directly using these values to perform RSA operations (e.g. via `pow()`), is extremely unwise.

Encryption under RSA cannot exceed the bit length of the modulus (minus some bytes for padding). If you need to encrypt more you should be looking at a hybrid encryption scheme where you encrypt a symmetric key and then use that to encrypt the larger payload. However, building a secure scheme like this is non-trivial and is not recommended for non-experts! If you need this, consider using `pynacl` instead.
