### ISSUE TITLE
cryptography-3.3 fails to compile while 3.2.1 succeded (pypy3)

### ISSUE THREAD

**Issue by grooverdan** [pyca/cryptography#5612]
Build failure: https://travis-ci.com/github/PyMySQL/PyMySQL/jobs/456406912#L212
success from version earlier today: https://travis-ci.com/github/PyMySQL/PyMySQL/jobs/456258876#L219

openssl-1.0.2g (https://travis-ci.com/github/PyMySQL/PyMySQL/jobs/456406912#L75)
PyPy 7.1.1-beta0 with GCC 6.2.0 20160901

Other python versions built successfully https://travis-ci.com/github/PyMySQL/PyMySQL/builds/207407464

ref: https://github.com/PyMySQL/PyMySQL/pull/907

**Comment by alex** [comment]
Looks like you're trying to build cryptography against OpenSSL 1.0.2 (on PyPy, where we can't have wheels), which this release dropped support for. We've been emitting a warning for several releases. You'll need to either build your own OpenSSL that's more recent, or upgrade to a newer OS that comes with a more modern OpenSSL.
