### ISSUE TITLE
wheels for Python 3.7/3.8 (for release 3.3.1)

### ISSUE THREAD

**Issue by moltob** [pyca/cryptography#5629]
Please provide wheels for modern Python versions 3.7 and 3.8, especially for Windows, where building from sources is not that easy in the deployment environment of a Python application.

**Comment by gluap** [comment]
Also 3.9 would be appreaciated as it is the latest stable version.

**Comment by tiran** [comment]
Cryptography provides binary wheels for Python 3.6 and newer for Windows X86_64, macOS, and Linux distros with glibc (manylinux). You need a recent version of pip that understands ``abi3`` builds. For example the wheel ``cryptography-3.3.1-cp36-abi3-win_amd64.whl`` is for X86_64 Windows versions and Python 3.6, 3.7, 3.8, 3.9, and 3.10.

Also see https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-my-python3-x-version

In case your copy of pip fails to detect and install the wheel, then upgrade pip + setuptools to latest version first.

**Comment by moltob** [comment]
Thanks for the hint, I was not yet aware of ABI specs of wheel packages. I will try this out and report. In fact that part of our logic _is_ still missing the update of setuptools, pip and wheel packages...
