### ISSUE TITLE
Unable to set _subject_name in CertificateBuilder object, resulting in a ValueError exception during the signing attempt

### ISSUE THREAD

**Issue by sumantnk** [pyca/cryptography#5630]
I am trying to write a simple function to create a certificate from a csr when I encounter this issue. The specific error message (anonimized) is:

Traceback (most recent call last):
  File "<my-file>.py", line 103, in <module>
    cert = cert_b.sign(ca_priv_key, hashes.SHA256())
  File "<my-home>/.local/share/virtualenvs/lic_svr-ic0hBQHO/lib/python3.9/site-packages/cryptography/x509/base.py", line 689, in sign
    raise ValueError("A certificate must have a subject name")
ValueError: A certificate must have a subject name

I reduced my code to this to narrow down the issue:
Contents of exp.cy:
<verbatim>
from cryptography import x509
from cryptography.x509.oid import NameOID

#create a minimal subject for certificate
subject = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, 'minimalSubjectName')])

#certificate builder
cert_b = x509.CertificateBuilder()

#set subject
cert_b.subject_name(subject)

#reproduce the issue
print(subject)
print("check :" + repr(cert_b._subject_name))
</verbatim>

On execution:
python exp.py
<Name(CN=minimalSubjectName)>
check :None

Which shows the '_subject_name' attribute to still be 'None' - same issue as the original issue

Environment details:
I am using pipenv for the virtual environment. The packages and their versions are as below:

Version information:
pipenv graph --reverse
pip==20.2.4
pycparser==2.20
  - cffi==1.14.4 [requires: pycparser]
    - cryptography==3.3.1 [requires: cffi>=1.12]
setuptools==51.0.0
six==1.15.0
  - cryptography==3.3.1 [requires: six>=1.4.1]
wheel==0.35.1

Python version used (have also tried this with version 3.7.9):
Python 3.9.0 (default, Nov 25 2020, 07:16:05) 
[GCC 7.5.0] on linux

openssl version
OpenSSL 1.1.1  11 Sep 2018

Ubuntu version used(uname -a): <VM name> 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
The ubuntu VM is deployed in a Windows laptop using Virtualbox

This seems to be too basic and I may well be missing something. The warning on accessing hazard layer is well understood. However there does not seem to be much about this issue online, hence the bug post after some head scratching for a day

**Comment by alex** [comment]
certificate builder uses an immutable builder pattern, therefore your code must be:

```py
cert_b = x509.CertificateBuilder()

#set subject
cert_b = cert_b.subject_name(subject)
```

**Comment by sumantnk** [comment]
Thank you. Appreciate the quick response!
