### ISSUE TITLE
Add a boolean has_extenstion method to x509.extensions class

### ISSUE THREAD

**Issue by israelfink** [pyca/cryptography#5675]
In '/src/cryptography/x509/extensions.py', there is a function 'get_extension_for_oid' that accepts an oid and if the oid exists, returns the oid value.
The problem is that if it didn't exist, it raises a ExtensionNotFound exception,  that is unpleasant and requires the coder to add special handling with a try except block.
Would like to suggest to add a boolean function like has_extension_for_oid(oid) that will check and return True/False whether the extension exits.

**Comment by alex** [comment]
You can implement this yourself with something like:

```py
def has_extension(extensions, oid):
    try:
        extensions.get_extension_for_oid(oid)
    except ExtensionNotFound:
        return False
    else:
        return True
```

We'd encourage you to add such a function to your own project. If we see that such a function is repeated across multiple projects, we'll consider adding it ourselves then, but for now we think this is better for people to have in their own projects.
