### ISSUE TITLE
Windows wheels on PyPI are missing for cp37 and cp38

### ISSUE THREAD

**Issue by ntamas** [pyca/cryptography#5687]
I'm not sure whether this is intentional, but it looks like there are no Windows wheels on PyPI for CPython 3.7 and 3.8 since version 3.3; the latest version that had these wheels is 3.2.1. Would it be possible to provide wheels for newer CPython versions on Windows?

**Comment by alex** [comment]
https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-my-python3-x-version

**Comment by ntamas** [comment]
Ah, sorry, I completely missed that even though I was looking for something like this!
