### ISSUE TITLE
How to sign a x509 certificate with PSS padding?

### ISSUE THREAD

**Issue by t1m0t** [pyca/cryptography#5691]
I'm trying to figure how to sign a x509 certificate with PSS padding instead of PKCS1v15 which it seems to be the default? How to set it when we sign the x509 certificate ? Actually it is to support it in the tool I've developed here: [certsGenerator](https://github.com/t1m0t/certsGenerator).
Thank you

**Comment by alex** [comment]
This is not currently supported, #2850 tracks adding it.
