### ISSUE TITLE
Trying to use ECDH P521 with Arduino P521

### ISSUE THREAD

**Issue by mariolpantunes** [pyca/cryptography#5698]
Dear all, 

I am trying to use this library EC module to perform ECDH with the [Arduino cryptographic library](https://rweather.github.io/arduinolibs/index.html). 

Up until now, I am unsuccessful at using the P521:

```
Traceback (most recent call last):
  File "/home/mantunes/git/iot-security/html/client/dh.py", line 25, in <module>
    sensor_public_key = ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP521R1(), sensor_public_key_bytes)
  File "/home/mantunes/git/iot-security/html/client/venv/lib64/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 167, in from_encoded_point
    raise ValueError("Unsupported elliptic curve point type")
ValueError: Unsupported elliptic curve point type
```

One issue that I found is that the public key from Arduino is 132 bytes, while the public key in this library is 133 bytes.
Should I pad the Arduino part with some bytes?
From what I was able to read, 132 should be the current value to the public key for the P521 algorithm.

**Comment by reaperhulk** [comment]
It sounds like you possibly have a raw set of public coordinates. cryptography requires public points to be serialized with a value denoting whether the point is compressed. What is the ordinal value of the first byte? If it isn’t 4 prefix your bytes with 0x04 and see if it loads then.

**Comment by mariolpantunes** [comment]
That work, thank you.
