### ISSUE TITLE
can't import pkcs7

### ISSUE THREAD

**Issue by CNKCQ** [pyca/cryptography#5703]
can't import pkcs7
python version: 3.9.0
pip version: 21.0
cryptography version: 3.3.1
cffi version: 1.14.4

install:

```shell
 pip install cryptography==3.3.1
```

mycode:

```python
from cryptography.hazmat.primitives.serialization import pkcs12
from cryptography.hazmat.primitives.serialization import pkcs7
```
`pkcs12` is ok

**Comment by tiran** [comment]
Can you show us the error message, please? What operating system are you using?

**Comment by CNKCQ** [comment]
> Can you show us the error message, please? What operating system are you using?

operating  system: macOS Big Sur
error message: Cannot find reference 'pkcs7' in '__init__.pyi'

**Comment by tiran** [comment]
PyCA cryptography does not provide ``.pyi`` stub files. Is the error message coming from a 3rd party tool or IDE like PyCharm?

**Comment by CNKCQ** [comment]
> PyCA cryptography does not provide `.pyi` stub files. Is the error message coming from a 3rd party tool or IDE like PyCharm?

yep, PyCharm

**Comment by tiran** [comment]
It's an UI problem in PyCharm, not a PyCA cryptography bug. It looks like they are shipping outdated stub files. You can still use the pkcs7 module in your code. Your IDE just won't do proper auto completion and code checks.

**Comment by CNKCQ** [comment]
> It's an UI problem in PyCharm, not a PyCA cryptography bug. It looks like they are shipping outdated stub files. You can still use the pkcs7 module in your code. Your IDE just won't do proper auto completion and code checks.

thanks，it works well in my demoProject (python version: 3.9.0)，but i got an error message: 'UnboundLocalError: local variable 'pkcs7' referenced before assignment' while I change the python to python@3.6.5

**Comment by CNKCQ** [comment]
> It's an UI problem in PyCharm, not a PyCA cryptography bug. It looks like they are shipping outdated stub files. You can still use the pkcs7 module in your code. Your IDE just won't do proper auto completion and code checks.

thanks, it work well!
