### ISSUE TITLE
ed25519 is not supported cryptography version: 3.2

### ISSUE THREAD

**Issue by nick2525** [pyca/cryptography#5704]
cryptography Version: 3.2 reports that ed25519 is not supported by this version of OpenSSL, but in OpenSSL 1.1.1f  ed25519 already supported.

My docker container is
lsb_release -a

Distributor ID: Ubuntu
Description: Ubuntu 20.04.1 LTS
Release: 20.04
Codename: focal

uname -a

Linux raspberrypi 5.4.83-v7+ armv7l armv7l armv7l GNU/Linux
Debug in Python, Python is in virtualenv

Python 3.9.0 (default, Oct 28 2020, 23:50:03)
[GCC 7.4.0] on linux

from cryptography.hazmat.backends import default_backend
default_backend().openssl_version_text()
'OpenSSL 1.1.1f 31 Mar 2020'

So, I have openssl version 1.1.1f
when I try in python

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
Ed25519PrivateKey.generate()
```
Traceback (most recent call last):
File "", line 1, in
File "/home/nick252/homeassistant/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 52, in generate
raise UnsupportedAlgorithm(
cryptography.exceptions.UnsupportedAlgorithm: ed25519 is not supported by this version of OpenSSL.
```
More info https://github.com/home-assistant/core/issues/45363 and also created bug in OpenSSL https://github.com/openssl/openssl/issues/13974

Sadness is that OpenSSL 1.1.1f is included in ubuntu 20.04 LTS and is unlikely to be updated, and now it's not even clear which side of the bug is on

**Comment by alex** [comment]
That's bizzare, ed25519 should be supported with any OpenSSL >=1.1.1b.

Can you tell me what happens when you run:

```py
from cryptography.hazmat.bakends import default_backend
b = default_backend()
print(b._fips_enabled, b._lib.CRYPTOGRAPHY_OPENSSL_LESS_THAN_111B)
```

**Comment by nick2525** [comment]
python3          
Python 3.9.0 (default, Oct 28 2020, 23:50:03) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.bakends import default_backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cryptography.hazmat.bakends'
>>>

**Comment by alex** [comment]
Sigh, let's try again but without typos:

```py
from cryptography.hazmat.backends import default_backend
b = default_backend()
print(b._fips_enabled, b._lib.CRYPTOGRAPHY_OPENSSL_LESS_THAN_111B)
```

**Comment by nick2525** [comment]
(homeassistant) root@raspberrypi:/home/nick252/homeassistant# python3
Python 3.9.0 (default, Oct 28 2020, 23:50:03) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> b = default_backend()
>>> print((b._fips_enabled, b._lib.CRYPTOGRAPHY_OPENSSL_LESS_THAN_111B))
(False, 1)
>>>

**Comment by tiran** [comment]
Ubuntu 20.04 should have OpenSSL 1.1.1f. What's output of ``print(hex(b._lib.OPENSSL_VERSION_NUMBER))``

**Comment by alex** [comment]
This looks to me like your cryptography was compiled against one version of OpenSSL, but linked against another. How did you install it?

**Comment by nick2525** [comment]
@tiran >>> print(hex(b._lib.OPENSSL_VERSION_NUMBER))
0x1010100f
I upgraded version of Ubuntu by 
rename in /etc/apt/sources.list
sudo sed -i 's/bionic/focal/g' /etc/apt/sources.list
and when upgrade

@alex I installed it on Ubuntu 18.04, and I think in was upgraded during migrate to 20.04

**Comment by alex** [comment]
Yes, you need to reinstall (re-compile) cryptography if you upgrade the OpenSSL its linked against.

**Comment by nick2525** [comment]
Yes remove python cache ./.cache/pip/wheels/ everywhere fixes it
