### ISSUE TITLE
undefined symbol: PyInt_FromLong

### ISSUE THREAD

**Issue by derkkila** [pyca/cryptography#5744]
Details:
Python3.7
pip 20.3.4
cryptography 3.3.1
Installed via "pip install -t . cryptography"

On my Windows development machine, this script works perfectly, however on an AmazonLinux test host, I get the following error:
```
Traceback (most recent call last):
  File "/opt/bin/modinput_wrapper/base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "/opt/bin/test_1612453828_413.py", line 80, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/bin/input_module_test_1612453828_413.py", line 67, in collect_events
    private_key = default_backend().load_pem_private_key(cert_bytes, None)
  File "/opt/bin/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/bin/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/opt/bin/cryptography/hazmat/backends/openssl/backend.py", line 117, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/opt/bin/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /opt/bin/cryptography/hazmat/bindings/_openssl.so: undefined symbol: PyInt_FromLong

ERROR/opt/bin/cryptography/hazmat/bindings/_openssl.so: undefined symbol: PyInt_FromLong
```

Not sure why the difference since I installed the exact same way on both machines.

**Comment by alex** [comment]
Can you give us some instructions for reproducing this from a fresh AmazonLinux (maybe from their docker image?)

**Comment by derkkila** [comment]
From a fresh install:
* Update python to 3.7
* update pip to 20.3
* install "pip install -t . cryptography"
* install "pip install -t . pyjwt"
* run the script below and get the error.

```
import os
import sys
import time
import datetime
from cryptography.hazmat.backends import default_backend
import jwt
#import requests
import json

APPNAME = 'app_name'
FILENAME = 'private-key.pem'
DIR_HOME = '/opt/project/'

fname = os.path.join(DIR_HOME,'etc','apps',APPNAME,'local',FILENAME)

# Get hold of the private key contents
cert_str = open(fname, 'r').read()
cert_bytes = cert_str.encode()

private_key = default_backend().load_pem_private_key(cert_bytes, None)
```

**Comment by reaperhulk** [comment]
Issues like this are most likely to arise from mismatches between multiple header versions. Depending upon how you are custom installing Python you may have different headers being used than what is being linked against or a variety of other challenges. Additionally, our wheels are compatible with Amazon Linux so you don't need to compile cryptography yourself. You can instead just have it install the manylinux wheel.

**Comment by alex** [comment]
Yes, this error almost certainly means you compiled against Python 2 headers and linked against Python3. This suggests you did the "update python to 3.7" step incorrectly.
