### ISSUE TITLE
"Broken" 3.4 release window

### ISSUE THREAD

**Issue by SeanTAllen** [pyca/cryptography#5754]
During the release for 3.4, there was/is a period of time where not all wheels were available so scripts that would work with 3.3 before the 3.4 release and should eventually work once 3.4 is completely done don't work. I discovered this while tracking down a "spooky action at distance" failure while building a docker image used for GitHub actions.

It failed with not having rust toolchain installed to build cryptography which was a transitive dependency.

It turns out that 3.4 had been released but the wheel for our alpine linux environment wasn't available. I'm assuming this "window of broken" isn't intended. If something went wrong during the release and not all wheels were created and this is a known issue, please close.

If, however, you aren't aware that during the release, there is a window were things can break because for users because not all wheels are available, please be aware that it can happen.

I'm not a heavy python user so I don't understand fully how things go together.

I would note that Docker container in question installs the latest pip before installing any dependencies. 

At this time, the problem still exists but I assume that additional wheels will appear and the problem will eventually disappear. I note that 3 additional wheels now appear at https://pypi.org/project/cryptography/3.4/#files that weren't there when I first looked after the 3.4 release.

**Comment by alex** [comment]
Yes, we're aware there was a window of breakage, and we're sorry about that. Unfortunately PyPI doesn't have any way for us to ensure all packages are uploaded/available at the same time. https://github.com/pypa/warehouse/pull/8941 will fix this, and we'll take advantage of this then to solve the issue. Not much we can do for now.

I should note: none of our wheels will work on alpine, since it uses musl libc instead of glibc.

**Comment by SeanTAllen** [comment]
@alex to clarify, the 3.3 wheels were working on alpine. when you say that non will work on alpine you are referring to things starting with 3.4, correct?

**Comment by alex** [comment]
wat. I am surprised that the 3.3 wheels would work on alpine. but if
they work, I suppose 3.4 will as well.

On Sun, Feb 7, 2021 at 3:17 PM Sean T Allen <notifications@github.com> wrote:
>
> @alex to clarify, the 3.3 wheels were working on alpine. when you say that non will work on alpine you are referring to things starting with 3.4, correct?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by SeanTAllen** [comment]
i should clarify work to "installs". the cryptography package is some transitive dependency for what i'm using so i don't know that it is actually being used at all, but it will install without using on alpine using 3.3 but not 3.4 at the moment.

**Comment by reaperhulk** [comment]
It’s very likely that the problem here is that you don’t have a rust compiler installed. 3.4 now requires rust.

**Comment by tiran** [comment]
Alex,
Alpine doesn't use the binary wheels. Latest Alpine still downloads sources:

```
$ podman run -ti alpine
/ # apk add py3-pip
/ # pip install cryptography==3.3
Collecting cryptography==3.3
  Downloading cryptography-3.3.tar.gz (539 kB)
     |████████████████████████████████| 539 kB 6.2 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
...
```

**Comment by SeanTAllen** [comment]
Gotcha, so we got caught by that. Good to know. Sorry for the noise, we have as a transitive dependency and I wasn't aware of the specific details like we were building from source. I'll lock in 3.3. Thanks for all the info.
