### ISSUE TITLE
Building wheel for cryptography (PEP 517): finished with status 'error'

### ISSUE THREAD

**Issue by jbnjohnathan** [pyca/cryptography#5765]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

I am trying to install python packages in a docker image using Alpine
During the installation I get the error message ` Building wheel for cryptography (PEP 517): finished with status 'error'`
Attaching a log file of the full error messages (too much to paste here)
[error.txt](https://github.com/pyca/cryptography/files/5940285/error.txt)

What I think are the interesting lines:
```
n0mn_8jz/cryptography_dcb1ffd003344a3cb8dd760c42e3d17b/src/rust/target/release/deps/libunindent-cf91bea16ca6ef52.rlib --cap-lints allow -C target-feature=-crt-static`
    error[E0433]: failed to resolve: use of undeclared type or module `proc_macro`
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/expr.rs:2:5
      |
    2 | use proc_macro::token_stream::IntoIter as TokenIter;
      |     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

    error[E0432]: unresolved import `proc_macro`
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/error.rs:1:5
      |
    1 | use proc_macro::{Delimiter, Group, Ident, Literal, Punct, Spacing, Span, TokenStream, TokenTree};
      |     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

    error[E0433]: failed to resolve: use of undeclared type or module `proc_macro`
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/lib.rs:117:5
        |
    117 | use proc_macro::token_stream::IntoIter as TokenIter;
        |     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

    error[E0432]: unresolved import `proc_macro`
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/expr.rs:3:5
      |
    3 | use proc_macro::{Spacing, Span, TokenStream, TokenTree};
      |     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

    error[E0432]: unresolved import `proc_macro`
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/lib.rs:118:5
        |
    118 | use proc_macro::{Delimiter, Group, Ident, Literal, Punct, Spacing, Span, TokenStream, TokenTree};
        |     ^^^^^^^^^^ use of undeclared type or module `proc_macro`

    error[E0412]: cannot find type `TokenIter` in this scope
     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/expr.rs:8:26
      |
    8 | pub fn parse(input: &mut TokenIter) -> Result<Expr> {
      |                          ^^^^^^^^^ not found in this scope

    error[E0412]: cannot find type `TokenIter` in this scope
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/indoc-1.0.3/src/lib.rs:367:48
        |
    367 | fn require_empty_or_trailing_comma(input: &mut TokenIter) -> Result<()> {
        |                                                ^^^^^^^^^ not found in this scope

    error: aborting due to 7 previous errors

    Some errors have detailed explanations: E0412, E0432, E0433.
    For more information about an error, try `rustc --explain E0412`.
    error: could not compile `indoc`
```

As part of the docker build I am upgrading, pip, wheel and setuptools
`Successfully installed pip-21.0.1 setuptools-53.0.0 wheel-0.36.2`

I am using the latest version of cryptography
`Downloading cryptography-3.4.1.tar.gz (544 kB)`

I am installing the following packages in alpine
`RUN apk --update add bash nano postgresql-dev build-base libffi-dev gcc musl-dev python3-dev libffi-dev libressl-dev cargo rust`

I added "rust" to the above to see if it made any difference but it did not.
I checked https://cryptography.io/en/latest/installation.html and https://cryptography.io/en/latest/faq.html but didn't find a solution.
I was a bit unsure about this item:
4) Ensure you have a recent Rust toolchain installed.

Any help would be appricated!

To reproduce, including my requirements.txt and Dockerfile
requirements.txt
```
Flask==1.1.2
psycopg2==2.8.6
pyyaml==5.3.1
pendulum==2.0.5
APScheduler==3.7.0
requests==2.25.1
flask-sqlalchemy==2.4.4

# Login and sessions
flask-login==0.5.0
werkzeug==1.0.1

# Tests
coverage==5.4

Flask-Script==2.0.6
Flask-Migrate==2.6.0
Flask-Testing==0.8.1
Flask-Bcrypt==0.7.1
PyJWT==2.0.1
```

Dockerfile
```
FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine-2020-12-19
RUN apk --update add bash nano postgresql-dev build-base \
    libffi-dev gcc musl-dev python3-dev libffi-dev libressl-dev cargo rust
RUN python3 -m pip install --upgrade pip wheel setuptools
COPY backend_flask/requirements.txt .
RUN pip3 install -r requirements.txt
```

**Comment by reaperhulk** [comment]
What version of rust do you have installed? The minimum version required is 1.45.0, so you may need to either upgrade alpine (3.13 includes a new enough rust) or install it outside of the package manager.

**Comment by jbnjohnathan** [comment]
Ah hmm, yeah seems its installing `(25/45) Installing rust (1.39.0-r0)`

For anyone else having the same issue, I included what I added to my Dockerfile to make it work:

```
# Install Rust, needed for pip package cryptography
ENV RUST_URL https://static.rust-lang.org/dist/rust-1.49.0-x86_64-unknown-linux-musl.tar.gz
ENV RUST_FOLDER rust-1.49.0-x86_64-unknown-linux-musl
RUN curl $RUST_URL -o rust.tar.gz
RUN tar zxvf rust.tar.gz
RUN cd $RUST_FOLDER && sh ./install.sh
```
This installed a supported version.

Thanks for the quick help!
I guess that rust is not needed for the actual running of cryptography, right? So I can uninstall it after building it.

**Comment by alex** [comment]
That's right, you only need it for installation -- FWIW instead of
uninstalling it, I recommend using multi-stage docker builds. You also
might want to use rustup, instead of hard-coding the tarball for
installing rust, YMMV.

On Mon, Feb 8, 2021 at 4:28 PM jbnjohnathan <notifications@github.com> wrote:
>
> Ah hmm, yeah seems its installing (25/45) Installing rust (1.39.0-r0)
>
> For anyone else having the same issue, I included what I added to my Dockerfile to make it work:
>
> # Install Rust, needed for pip package cryptography
> ENV RUST_URL https://static.rust-lang.org/dist/rust-1.49.0-x86_64-unknown-linux-musl.tar.gz
> ENV RUST_FOLDER rust-1.49.0-x86_64-unknown-linux-musl
> RUN curl $RUST_URL -o rust.tar.gz
> RUN tar zxvf rust.tar.gz
> RUN cd $RUST_FOLDER && sh ./install.sh
>
> This installed a supported version.
>
> Thanks for the quick help!
> I guess that rust is not needed for the actual running of cryptography, right? So I can uninstall it after building it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by jbnjohnathan** [comment]
Yeah might need to do the multistage, the image is very large now.
The reason for hardcoding a specific version is important so that builds are consistent, regardless of when in time the image is built.

**Comment by williamjacksn** [comment]
I build Alpine wheels so you don't have to.

https://github.com/alpine-wheels/index
