### ISSUE TITLE
cryptography 3.4 should not have an install_requires on setuptools_rust

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#5778]
``setup.py`` lists ``setuptools_rust`` as setup and as installation dependency. cryptography only needs ``setuptools_rust`` during setup. The additional dependency causes issues with Fedora's automatic dependency generator, see https://bugzilla.redhat.com/show_bug.cgi?id=1926181

```python

setup_requirements = ["cffi>=1.12", "setuptools-rust>=0.11.4"]


setup(
    ...
    install_requires=setup_requirements,
    setup_requires=setup_requirements,
)
```

**Comment by tom--pollard** [comment]
Also hitting this issue when trying to pip install docker-compose
