### ISSUE TITLE
pypi push for 3.4.2 incomplete

### ISSUE THREAD

**Issue by virtuald** [pyca/cryptography#5787]
Breaking twine installation because of no rust compiler installed. Looks like only 3.6 wheels are published? https://pypi.org/project/cryptography/3.4.2/#files

Reference: https://github.com/pypa/gh-action-pypi-publish/issues/56

**Comment by tiran** [comment]
These issues are explained in the FAQ and issue template:

* https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-my-python3-x-version
* https://cryptography.io/en/latest/faq.html#installing-cryptography-fails-with-error-can-not-find-rust-compiler

**Comment by webknjaz** [comment]
@alex @tiran @reaperhulk please reopen, it's a different issue. Sounds like there's a bug in your CI/CD setup that only published Python 3.6 wheels. Look for yourself: https://pypi.org/project/cryptography/3.4/#files.

**Comment by webknjaz** [comment]
Ah, nevermind, I missed that they are `abi3`. Sorry.
