### ISSUE TITLE
No wheels on PyPI for Python 3.7+

### ISSUE THREAD

**Issue by K900** [pyca/cryptography#5798]
Cryptography 3.2.1 (and earlier versions) has shipped wheels on PyPI for Python 2.7, 3.6, 3.7 and 3.8: https://pypi.org/project/cryptography/3.2.1/#files

However, none of the newer versions have wheels for 3.7 or 3.8 (or 3.9, for that matter). Is this intentional? Is there something we can do to get official builds going again?

**Comment by tiran** [comment]
See https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-my-python3-x-version

> Our Python3 wheels are abi3 wheels. This means they support multiple versions of Python. The abi3 wheel can be used with any version of Python greater than or equal to the version it specifies. Recent versions of pip will automatically install abi3 wheels.

**Comment by K900** [comment]
I missed that part - sorry!
