### ISSUE TITLE
Supporting ECDSA_SIG structures for ECDSA signing and verifying signatures

### ISSUE THREAD

**Issue by adferrand** [pyca/cryptography#5811]
As of now, `cryptography` (<= `3.4.4`) supports ECDSA signatures only through DER-encoded format. Indeed it takes advantages of OpenSSL methods `ECDSA_sign` and `ECDSA_verify` that work with this format.

In some circumstances however, a signature in DER-encoded format is not acceptable. This is the case in particular in the JSON Web Signature context, where the signatures are expected to be a simple byte concatenation `R || S` as specified in https://tools.ietf.org/html/rfc7515#appendix-A.3.

See in particular the discussion we had on that matter while implementing ECDSA in the `certbot/josepy` project: https://github.com/certbot/josepy/pull/51

I would like to contribute on `cryptography` to provide some flexibility to users around ECDSA signatures, by supporting in a way or another the `ECDSA_SIG` structure. But I would like to have some guidance from `cryptography` maintainers before doing so.

* Is there any decent workaround that would make in fact this work useless?
* Is it something in your roadmap that you would be willing to review in the short term?

For this work, I would imagine to define an `ECDSASignature` object that would reflect the `ECDSA_SIG` structure from OpenSSL, then leverage the `ECDSA_do_sign` and `ECDSA_do_verify` from OpenSSL, in order to expose two new methods in `EllipticCurvePublicKey`: `do_sign` and `do_verify`. These methods would produce or accept `ECDSASignature` instances that would give flexibility to the caller to compute the final signatures from `R` and `S` in the way it is best suited for their actual usage.

What do you think of this approach? Thanks a lot in advance!

**Comment by alex** [comment]
This can be accomplished by encoding/decoding the ASN.1 values: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils.html#cryptography.hazmat.primitives.asymmetric.utils.decode_dss_signature
