### ISSUE TITLE
Incorrect use of iterable type annotation

### ISSUE THREAD

**Issue by sodul** [pyca/cryptography#5816]
Python 3.9.1, cryptography 3.4.4

In `x509/name.py` there is an incorrect use of the `Iterable` annotation, it should be `List` or `Sequence`.

```
    def get_attributes_for_oid(self, oid) -> typing.Iterable[NameAttribute]:
        return [i for i in self if i.oid == oid]
```

The fact that the return value is marked as iterable is breaking mypy on our own code when we try to use an index on it:
```Value of type "Iterable[NameAttribute]" is not indexable```

In practice the type annotation should be relaxes for the method arguments (prefer `Iterable` or `Sequence` over `List`), but should be very specific on the return values.

The workaround for us is to call `cast()` or to ignore the type, but this breaks the whole point of using type annotation in the first place.

**Comment by alex** [comment]
fixed in https://github.com/pyca/cryptography/commit/278fece69889898f0638dd4429cf40481e18ee14

**Comment by sodul** [comment]
Thanks, is there an ETA for a release?

**Comment by alex** [comment]
Not ATM, no.

On Thu, Feb 11, 2021 at 3:46 PM Stephane Odul <notifications@github.com> wrote:
>
> Thanks, is there an ETA for a release?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by reaperhulk** [comment]
We do intend to ship a 3.4.5 though so think days not months.
