### ISSUE TITLE
Error encountered on M1 Mac

### ISSUE THREAD

**Issue by timtangcoding** [pyca/cryptography#5820]
**Versions:**
- Python 3.9.1
- cryptography  3.4.4
- cffi  1.14.5
- pip 21.0.1
-  setuptools  53.0.0

 Hello everyone.
I have installed `cryptography` as a dependency of `scrapy`(I have reinstalled it via `pip3 install cryptography`), and as I run `scrapy` the following errors occured: 

> ImportError: dlopen(/xxx/venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 2): no suitable image found.  Did find:
/xxx/venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: mach-o, but wrong architecture
/xxx/venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: mach-o, but wrong architecture

Here is the result of `file /xxx/venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so`:

`/xxx/venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Mach-O 64-bit bundle x86_64`

It seems the issue is some binary is only available on x86_64?
How could I fix it and run `cryptography` lib using the M1 chip without having to use `Rosetta`? Is `cryptography` compatible with M1 yet?

Thanks in advance.

**Comment by tiran** [comment]
cryptography does not provide binary wheels for M1, yet. There is no public build infrastructure and CI to create and test builds. Check out https://github.com/pyca/cryptography/issues/5742 and https://github.com/pyca/cryptography/issues/5702

**Comment by timtangcoding** [comment]
@tiran Thanks a lot for the quick reply. Came across the mentioned issues seems to me they were about installation issues. Overlooked that the wheels for M1 where not published yet. Thanks for pointing out.

**Comment by Ashiq5** [comment]
Sorry to comment on a closed issue but is there a solution to this problem yet? Have encountered this same error although my `file /xxx/venv/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so`

reports `xxx/venv/ImprovingDNSSEC/lib/python3.8/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Mach-O 64-bit bundle arm64`

I've had a look at the linked issues and couldn't really understand whether there is a solution. How could I fix it and run cryptography lib using the M1 chip?
