### ISSUE TITLE
Using python-jose with the cryptography backend and getting a CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by TheBubblePopped** [pyca/cryptography#5829]
Hi there, 

"CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes"

That's the error i am getting. I am using Python 3.8. How do i get rid of it?

**Comment by alex** [comment]
You can silence teh warning as documented here: https://cryptography.io/en/latest/faq.html#i-cannot-suppress-the-deprecation-warning-that-cryptography-emits-on-import

And I'd suggest filing a bug with the jose folks asking _them_ to stop using the deprecated API.
