### ISSUE TITLE
type hints: make Extension generic?

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#5830]
In the official typeshed, `cryptography.x509.Extension` is a [generic class](https://mypy.readthedocs.io/en/stable/generics.html), but in the type hinting added in 3.4, it isn't. I couldn't find a discussion about this, if there was I apologize for the duplicate. If there wasn't, anything speaking against making that change (I would create a PR).

Making Extension a generic class would allow more precise type hints, for a (very simplified, just to get the point across) example:

```
def get_pathlen(ext: x509.Extension[x509.BasicConstraints]) -> int:
    return ext.value.path_length  # this works now
```

Like I said, if you think this is a good idea, I can definitely create a PR for this!

**Comment by alex** [comment]
This makes sense to me.

On Sun, Feb 14, 2021 at 6:06 AM Mathias Ertl <notifications@github.com> wrote:
>
> In the official typeshed, cryptography.x509.Extension is a generic class, but in the type hinting added in 3.4, it isn't. I couldn't find a discussion about this, if there was I apologize for the duplicate. If there wasn't, anything speaking against making that change (I would create a PR).
>
> Making Extension a generic class would allow more precise type hints, for a (very simplified, just to get the point across) example:
>
> def get_pathlen(ext: x509.Extension[x509.BasicConstraints]) -> int:
>     return ext.value.path_length  # this works now
>
> Like I said, if you think this is a good idea, I can definitely create a PR for this!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.
