### ISSUE TITLE
Expose this project as a rust crate

### ISSUE THREAD

**Issue by eqrx** [pyca/cryptography#5844]
Hello everybody! Since cryptography is now using rust for the low level fun bits, I was wondering if there are plans to expose your work also as a rust crate. 

I understand that this project is about proving a crypto module for python, but my reasoning behind this is the following:
Your switch to rust got me interested in the language. I started coding some projects and realized that there is no crypto module in the stdlib. There are plenty of crates that provide what I need but they are all "non-official" (== maintained by people I do not trust yet). I do trust this project.

I am unaware how much and what work that would actually require but I would love to help with that (but please bear in mind that am not experienced in rust or actually implementing cryptography libs).

Thank you all for your time. :)

**Comment by alex** [comment]
While we appreciate the vote of confidence, this would be a massive undertaking, probably as significant in scope as rebuilding this library from scratch. It's well beyond the goals of this project, so sadly I'm going to close this.

FWIW, https://crates.io/crates/ring is an excellent library.

**Comment by eqrx** [comment]
Thanks for answering that so quickly and thanks for the tip!
