### ISSUE TITLE
Runtime error in AWS Lambda

### ISSUE THREAD

**Issue by joshua-nicholson** [pyca/cryptography#5845]
Hi, I am using another library (simple-salesforce) which has a dependency on this one. After the change to add Rust, I am seeing the following error when running a lamba function in AWS.

```
"errorMessage": "Unable to import module 'my_file': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError"
```

I am deploying to AWS using terraform which is built on a docker container using Alpine. I have the following line in a script executed by the docker container which got my build to succeed (originally failing due to missing rust) but I now get the above error when executing the lambda function. Is there another dependency I'm missing here?

`apk add --no-cache --update gcc musl-dev python3-dev libffi-dev openssl-dev rust cargo`

**Comment by alex** [comment]
Can you give us instructions for reproducing this? At least instructions on how to build the docker image.

**Comment by reaperhulk** [comment]
You’re compiling cryptography in alpine and then trying to use those artifacts on lambda, which doesn’t use the same underlying libc implementation. You need to build on a glibc distribution equal to or older than the Amazon Linux running in lambda or just deploy using the manylinux wheels we already ship (which will not work on alpine but will work in lambda).
