### ISSUE TITLE
Probable bug in blowfish

### ISSUE THREAD

**Issue by jaclas** [pyca/cryptography#5847]
The Blowfish algorithm in CFB mode likely has a bug. I discovered this by comparing Cryptography with the PyCryptodome library and the results obtained from http://blowfish.online-domain-tools.com/
```
key = 0123
iv = \x00\x00\x00\x00\x00\x00\x00\x00
plaintext = 0123456789012345
mode = CFB

result from Cryptography lib: D8CA8150B83DBCCAED11EBD40B157099
result from PyCryptodome:  D8300047B33F5EAD29877B65414ADD87
```

and screen from mentioned site:

![obraz](https://user-images.githubusercontent.com/17312717/108418378-719cd680-7231-11eb-92de-59485410f2a7.png)

**Comment by reaperhulk** [comment]
There is definitely a mismatch here, but the tool you've chosen fails the test vectors Bruce Schneier (the original Blowfish author) published here (look near the bottom for expected cfb output): https://www.schneier.com/wp-content/uploads/2015/12/vectors-2.txt

It's possible that these tools are using a different CFB variant and that's the mismatch, but our code simply uses OpenSSL underneath so if you believe there is a mis-implementation (and the OpenSSL implementation matches the test vectors provided) then you should file a bug with the appropriate project.
