### ISSUE TITLE
cryptography.utils import int_from_bytes deprecated

### ISSUE THREAD

**Issue by kingttx** [pyca/cryptography#5850]
Not listed on https://cryptography.io/en/latest/faq.html. 
Python 3.6.9 (installed with Ubuntu apt)
cryptography 3.4.6 (pip3)
cffi 1.14.4 (pip3)
pip 21.0.1 (pip)
setuptools 53.0.0 (pip)

Python3 commands and various python tools contain this depracation warning:
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes

**Comment by alex** [comment]
We don't list all deprecations in our FAQ. This warning has all the info needed to resolve it. You should talk to the develoeprs of `secretstorage`.
