### ISSUE TITLE
pip can't find manylinux wheel on manylinux1 container?

### ISSUE THREAD

**Issue by bsolomon1124** [pyca/cryptography#5854]
When attempting a `python3.9 -m pip install cryptography` from a `quay.io/pypa/manylinux1_x86_64:latest` Docker container, pip (21.0.1) can't seem to find a wheel for cryptography 3.4.

```
[root@32ec3bd23cdd io]# /opt/python/cp39-cp39/bin/python -m pip install -U pip wheel setuptools
Requirement already satisfied: pip in /opt/_internal/cpython-3.9.2/lib/python3.9/site-packages (21.0.1)
Requirement already satisfied: wheel in /opt/_internal/cpython-3.9.2/lib/python3.9/site-packages (0.36.2)
Requirement already satisfied: setuptools in /opt/_internal/cpython-3.9.2/lib/python3.9/site-packages (53.0.0)

[root@32ec3bd23cdd io]# /opt/python/cp39-cp39/bin/python -m pip install cryptography
Collecting cryptography
  Downloading cryptography-3.4.6.tar.gz (546 kB)
     |████████████████████████████████| 546 kB 5.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
```

The above errors out (as I would expect) with `error: Can not find Rust compiler`. I have not yet embarked on the fun that may be installing Rust on CentOS 5 :)

pip is able to find a wheel with `--only-binary`, for the 3.3.x release:

```
[root@xxx io]# /opt/python/cp39-cp39/bin/python -m pip install cryptography --only-binary cryptography
Collecting cryptography
  Downloading cryptography-3.3.2-cp36-abi3-manylinux1_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 3.2 MB/s 
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp39-cp39-manylinux1_x86_64.whl (406 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pycparser, six, cffi, cryptography
Successfully installed cffi-1.14.5 cryptography-3.3.2 pycparser-2.20 six-1.15.0
```

Any idea why pip can't find a compatible wheel for cryptography 3.4? I'm probably missing something obvious. Is it perhaps that cryptography distributes manylinux2010 and above?

**Comment by alex** [comment]
As docuemnted in our changelog (https://cryptography.io/en/latest/changelog.html#v3-4) we now ship manylinux 2010 and 2014 wheels, but not 1.

**Comment by reaperhulk** [comment]
As of cryptography 3.4 we no longer ship manylinux1 wheels (https://cryptography.io/en/latest/changelog.html#v3-4) so your guess is correct. Do you have a hard manylinux1 requirement here?

**Comment by bsolomon1124** [comment]
Thank you for confirming. That was my guess, but I wasn't able to find actual documentation that Centos5 is incompatible with manylinux2010+ (if that's indeed what the underlying issue is).

I'll attempt to switch this build to produce manylinux2010 wheels, or else pin to 3.3.

**Comment by reaperhulk** [comment]
CentOS 5 is definitely incompatible with manylinux2010 (which is based on the glibc in CentOS 6). The manylinux spec has actually been subsequently renamed to refer to the glibc version, which will potentially reduce confusion around this in the future (and make it so new pip releases don't have to become aware of newer standards).
