### ISSUE TITLE
Tips for compiling on Raspberry Pi

### ISSUE THREAD

**Issue by itsthejoker** [pyca/cryptography#5861]
Hi, all. I run a build pipeline that uses Raspberry Pis to test software, and periodically I blow away the nodes and do an automated rebuild. I'm running into the Rust issue that was vigorously debated in https://github.com/pyca/cryptography/issues/5771 -- the problem is that there doesn't seem to be a way to get the pre-compiled version on a Pi. I've:

* updated pip to the latest
* installed `wheel` prior to main installation

and it's still complaining about not having Rust. So I've added `rustc` to our pipeline, but it's massively increasing the build time. I'm at 35 minutes of compiling `cryptography` -- a process which used to take seconds -- with no end in sight. Is there anything I can do to speed up this build?

The alternatives that I'm aware of:

* pin the version to a previous version (transitive dependency through Poetry which just specifies >=2, so no go)
* use the flag to turn off rust bindings (apparently only valid for this version? So I'll have to deal with this soon again anyway, might as well deal with it now)

Any help or guidance is appreciated.

**Comment by itsthejoker** [comment]
Update: can install 3.3.2 before app installation to effectively pin the dependency, and per https://github.com/pyca/cryptography/issues/5766#issuecomment-778538695 I'm just hosed. Fantastic.

For anyone else who finds this: `pip install cryptography==3.3.2 --no-cache-dir`

**Comment by zhaojunchen** [comment]
> Update: can install 3.3.2 before app installation to effectively pin the dependency, and per [#5766 (comment)](https://github.com/pyca/cryptography/issues/5766#issuecomment-778538695) I'm just hosed. Fantastic.
> 
> For anyone else who finds this: `pip install cryptography==3.3.2 --no-cache-dir`

Thank you very much, through this command (`pip install cryptography==3.3.2 --no-cache-dir`)I successfully installed cryptography 3.3.2 version on Raspberry Pi 3B
