### ISSUE TITLE
Not a bug! Just a quick question

### ISSUE THREAD

**Issue by ocefpaf** [pyca/cryptography#5864]
Hi, first of all thanks for the crucial piece of Software you'all created and maintain!

I'm a "downstream" packager and I have a quick question on the new rust code parts/modules.

We need to specify all the licenses cryptography code base uses and it is not clear, at least to me, what are the rust part licenses. Is that documented somewhere? Could you ship license files with the sdist?

Thanks and sorry if the answer is too obvious and I could not find it.

**Comment by alex** [comment]
Our own rust code is licensed under the same terms as the Python code. Our rust dependencies have their own licenses, in the same way our Python dependencies have their own licenses. `Cargo.toml` in each rust dependency includes its license information.

**Comment by ocefpaf** [comment]
> Our own rust code is licensed under the same terms as the Python code. Our rust dependencies have their own licenses, in the same way our Python dependencies have their own licenses. `Cargo.toml` in each rust dependency includes its license information.

Cool. Thanks! So we'll have to dig into each dep Cargo.toml for them. I'll see what I can do.

**Comment by alex** [comment]
There's tools such as https://crates.io/crates/cargo-license which
will pull the license for all dependencies.

On Wed, Feb 24, 2021 at 3:03 PM Filipe <notifications@github.com> wrote:
>
> Our own rust code is licensed under the same terms as the Python code. Our rust dependencies have their own licenses, in the same way our Python dependencies have their own licenses. Cargo.toml in each rust dependency includes its license information.
>
> Cool. Thanks! So we'll have to dig into each dep Cargo.toml for them. I'll see what I can do.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by isuruf** [comment]
Thanks @alex. How do you deal with this issue in the binary wheels?
