### ISSUE TITLE
Adding SIV mode for AES

### ISSUE THREAD

**Issue by TheLazzziest** [pyca/cryptography#5877]
Hi, I haven't found [SIV](https://tools.ietf.org/html/rfc5297) mode in cryptography. Will you plan to add it ? 
The main reason is that I am looking for a deterministic encryption(DAE) in order to store data securely and predictably in order to be able to retrieve information using some sort of a secret.

**Comment by reaperhulk** [comment]
Yes we would like to add this. Unfortunately OpenSSL has only added SIV mode in 3.0, which is not yet out. We could implement this ourselves, but we prefer to keep implementations like that within OpenSSL where possible. So you can expect to see support shortly after 3.0 is released!

**Comment by tasket** [comment]
Hello:  My suggestion would be to implement the GCM-SIV mode which is faster because its based on GCM and it addresses the same issue of accidental nonce-reuse that SIV does...

https://datatracker.ietf.org/doc/rfc8452/

https://eprint.iacr.org/2017/168.pdf

**Comment by reaperhulk** [comment]
OpenSSL unfortunately hasn't implemented GCM-SIV so we can't add support for it until they do.

**Comment by beldmit** [comment]
https://github.com/openssl/openssl/issues/16721 is the OpenSSL upstream issue

**Comment by alexispondo** [comment]
h

**Comment by alex** [comment]
implemented in #7029
