### ISSUE TITLE
openssl 3.0.0 compatible cryptography version

### ISSUE THREAD

**Issue by satya-rajesh** [pyca/cryptography#5893]
While compiling observed that cryptography is not compatible with openssl 3.0.0.

cryptography is using deprecated APIs which are not present in openssl 3.0.0 (alpha).

Build status:
error: 'EVP_PKEY_CTX_set_rsa_oaep_md' redeclared as different kind of symbol
int (*EVP_PKEY_CTX_set_rsa_oaep_md)(EVP_PKEY_CTX *, EVP_MD *) = NULL;

Error: Undefined reference to FIPS_mode_set

Please provide cryptography release compatible to openssl 3.0.0

**Comment by tiran** [comment]
PR https://github.com/pyca/cryptography/pull/5250 has been work-in-progress for about 9 months now. 3.0.0 is still in alpha. I guess the PR won't be merged until OpenSSL 3.0.0 reaches beta and the API can be considered stable.

**Comment by h-vetinari** [comment]
> I guess the PR won't be merged until OpenSSL 3.0.0 reaches beta and the API can be considered stable.

@reaperhulk [mentioned](https://github.com/openssl/openssl/issues/14425#issuecomment-790679776) that there's only one OpenSSL bug left that's blocking 3.0.0 support on main.

**Comment by reaperhulk** [comment]
Closing since we have been tracking this for nearly a year already and will have support as soon as OpenSSL 3 stabilizes.
