### ISSUE TITLE
rust switch, how do these issues apply?

### ISSUE THREAD

**Issue by scrabble-auction** [pyca/cryptography#5896]
with switch to rust do these issues come into play at all?

https://github.com/rust-lang/rust/issues/40552
https://github.com/rust-lang/rust/issues/75263

these are privacy related, but known other privacy or security issues in the compiler if these are here. i say because of some findings in otherofficial rust apps like mdbook.

**Comment by alex** [comment]
I suppose these mean that on disk paths of build systems are included in the package. This is a WONTFIX from our perspective.
