### ISSUE TITLE
How to dump certificate chain into PEM file using pyopenssl module in python

### ISSUE THREAD

**Issue by srinivasev** [pyca/cryptography#5901]
I wanted to dump the complete certificate chain into PEM file. Currently, I am trying this with the OpenSSL module, as the ssl module doesn't give the methods to fetch the certificate chain(only server certificate download is available).

`import OpenSSL

def get_cert_chain(address, port=443):
    context = Context(SSLv23_METHOD)
    client = socket()
    client.connect((address, port))
    clientSSL = Connection(context, client)
    clientSSL.set_connect_state()
    clientSSL.do_handshake()
    return clientSSL.get_peer_cert_chain()

#The below certificate_chain variable contains the stack of X509 certificates
certificate_chain = get_cert_chain('www.google.com')`

Purpose : I wanted to import full chain of target IP and run the keytool import over the .pem file for adding into Wildfly truststore. But, there are no methods in X509 class to perform operations like dump the chain into .pem file and something similar to it.

Added the screenshots below for the same - (debug point)

**Is the same available using pyca/cryptography module ?**

<img width="676" alt="certificate chain 1" src="https://user-images.githubusercontent.com/11441751/110274131-2128c580-7ff4-11eb-9993-24167c95f54b.PNG">
<img width="678" alt="certificate chain 2" src="https://user-images.githubusercontent.com/11441751/110274136-22f28900-7ff4-11eb-99a5-bf3c2f3f04dc.PNG">

**Comment by reaperhulk** [comment]
`cryptography` has no public APIs for TLS connections, but `pyOpenSSL` uses the underlying bindings for TLS. Filing the exact same issue on both repositories is not really very useful. Closing in favor of https://github.com/pyca/pyopenssl/issues/999
