### ISSUE TITLE
Runtime.ImportModuleError: No module named 'cryptography.hazmat.bindings._padding'

### ISSUE THREAD

**Issue by KhanIshaq** [pyca/cryptography#5931]
Trying to run azure-storage-blob service using Python3.7 on AWS Lambda
After deployment of the zip file on AWS Lambda, when running the Lambda function using test case code is breaking with below error message.
Runtime.ImportModuleError: Unable to import module 'app/handler': No module named 'cryptography.hazmat.bindings._padding'

Upgraded pip, setuptools,  cryptography, pyopenssl but the issue is still persisting. Please find below details of 
Python Version :  3.7.0
Pip Version       : 21.0.1

pip list
Package            Version
astroid            2.5.1
atomicwrites       1.4.0
attrs              20.3.0
azure-core         1.12.0
azure-storage-blob 12.8.0
backports.zoneinfo 0.2.1
boto3              1.17.13
botocore           1.20.13
certifi            2020.12.5
cffi               1.14.5
chardet            4.0.0
colorama           0.4.4
cryptography       3.4.6
cycler             0.10.0
env                0.1.0
idna               2.10
importlib-metadata 3.4.0
iniconfig          1.1.1
isodate            0.6.0
isort              5.7.0
jmespath           0.10.0
kiwisolver         1.3.1
lazy-object-proxy  1.5.2
matplotlib         3.3.4
mccabe             0.6.1
msrest             0.6.21
numpy              1.20.1
oauthlib           3.1.0
packaging          20.9
pandas             1.1.5
Pillow             8.1.2
pip                21.0.1
pluggy             0.13.1
py                 1.10.0
pycparser          2.20
pylint             2.7.2
pyOpenSSL          20.0.1
pyparsing          2.4.7
pytest             6.2.2
python-dateutil    2.8.1
pytz               2021.1
requests           2.25.1
requests-oauthlib  1.3.0
s3transfer         0.3.4
setuptools         54.2.0
six                1.15.0
toml               0.10.2
typed-ast          1.4.2
typing-extensions  3.7.4.3
tzdata             2021.1
urllib3            1.26.3
wrapt              1.12.1
zipp               3.4.0

**Comment by alex** [comment]
How did you build your zip file?

**Comment by KhanIshaq** [comment]
The packages used were installed using below commands
python -m pip install azure-storage-blob -t .
python -m pip install --upgrade cryptography -t .
python -m pip install --upgrade cryptography -t .

The deployment and testing went as expected without any bottlenecks, using serverless deployment command.
serverless deploy --stage <stage>--region <region>
Issue was narrowed down to CI/CD pipeline and has been resolved.

Closed

Thanks
