### ISSUE TITLE
Build wheels for more python versions

### ISSUE THREAD

**Issue by ShadowJonathan** [pyca/cryptography#5935]
According to the [wheelodex](https://www.wheelodex.org/projects/cryptography/), `cryptography` currently does not publish wheels for any other version except 3.6 (`cp36`)

I suggest generating wheels for all versions [currently officially supported](https://endoflife.date/python), which means versions 3.6 through 3.9.

This greatly lifts the dependency burden of `cryptography`, especially with the recent addition of a rust compiler dependency (#5771).

I personally suggest using [cibuildwheel](https://github.com/joerick/cibuildwheel/) for something like this, but i understand if using a tool like that is not possible due to security considerations.

Nontheless, I think `cryptography` should have wheels built for more versions than `3.6`

**Comment by callahad** [comment]
Cryptography's wheels work on 3.6+, per the FAQ: https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-my-python3-x-version

**Comment by ShadowJonathan** [comment]
...huh, i personally didn't know about that.
