### ISSUE TITLE
feature/precompiled wheels

### ISSUE THREAD

**Issue by Sebi2020** [pyca/cryptography#5939]
Currently it's not possible to get a precompiled python wheel for the latest versions. It would be nice if you would add a optional precompiled python wheel rather than forcing all devs to install a complete rust toolchain manually (Which is a pain, because it forces us to download serveral 100 MBs of rust packages through cargo).

In my case this creates long build times and huge docker images if you don't remove the complete rust toolchain after building the cryptography package.

**Comment by tiran** [comment]
PyCA/cryptography provides binary wheels for most common platforms, hardware architectures on Python 3.6 and newer. You may have to update pip to a supported version. You can find more information in the FAQ entry https://cryptography.io/en/latest/faq.html#why-are-there-no-wheels-for-my-python3-x-version

**Comment by Sebi2020** [comment]
I'm using latest python and pip version!

Python 3.8.8 with PIP pip-21.0.1

**Comment by Sebi2020** [comment]
@tiran I'm using latest python and pip version!

Python 3.8.8 with PIP pip-21.0.1 on alpine Linux.

But nevermind, it always tries to compile the cryptography package. But okay, sadly this issue got closed direclty without further investigation.

**Comment by tiran** [comment]
You didn't mention Alpine in your initial post.

Alpine uses musl libc while most other Linux platforms use glibc. PyPI does not support binary wheels for musl-based systems yet. You have to wait until https://www.python.org/dev/peps/pep-0656/ is accepted and implemented.

**Comment by Sebi2020** [comment]
@tiran Thank you for your reply. I wasn't aware of python wheels not supporting musl libc.

**Comment by tiran** [comment]
You can build your own binary wheels for musl libc platforms. You just cannot upload them to official PyPI.

There is currently no standard for musl binary wheels with a stable ABI. PyPI blocks binary wheels except for a few supported platforms and stable build tags. I encourage you to read the PEP and related manylinux PEPs if you like to know more.
