### ISSUE TITLE
Camellia decryption

### ISSUE THREAD

**Issue by twilkerson1237** [pyca/cryptography#5960]
Symmetric encryption using Camellia.

Currently implementing successful encryption and decryption via WolfSSL implementation of Camellia. Currently when I am reading in the salt and IV used on my WolfSSL side and trying to decrypt the payload the python cryptography implementation of Camellia is not able to decrypt.

**Comment by alex** [comment]
Why do you think this is a bug in pyca/cryptography?

You have given us no code to examine. If you're going to file a bug, you need to provide enough information so that we can reproduce the issue.

**Comment by twilkerson1237** [comment]
Apologies, I'll give you an example.  
import hashlib
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend

key = b'SzE6pcNdUGbF0nVTNjqDj79v8JwBf7P2'
salt = b'b\xc41\xa6\x8d\xa1b\x00'
iv = b'\xd7\xfe3\x1d\x10\x85&^\xe6\x12p\xf8GZ\xb2\xa4'
cipher_text = b'\xb5\x7f\xbdpkkF\xef1\xbfX\xaf\x94\xf0\xec|V\xe4\xa8\xbe\x1a0B\xa8\x04Aq\x84\xd4\xa6M\xf8\x13\x9e<=\xbd\x1cbD\xdd\x82\xbe\\\x94\xf4m('
new_key = hashlib.pbkdf2_hmac('sha256', key, salt, 4096)
# new_key should equal 1b362a1ddb259ff3b5e79eb4536d434f79a73a5e38721c150795b3ccc26
cipher = Cipher(algorithms.Camellia(new_key), modes.CBC(iv), backend=default_backend())
dec = cipher.decryptor()
print(dec.update(data=cipher_text) + dec.finalize())

The decrypted end result should be:

"Hello there, you decrypted the string"

**Comment by alex** [comment]
This code cannot work. `"Hello there, you decrypted the string"` has a length of 37 bytes, but CBC mode requires data be padded to a multiple of the block length of the cipher. Why would you expect this to work?

**Comment by twilkerson1237** [comment]
The cipher text provide in the above code is 48 bytes.

**Comment by alex** [comment]
Sure, but the expected result is not, so there's clearly some unpadding that's not represented in this code. Since that wasn't presented, I'm concerned that this code might not be expected to work in other ways as well.

**Comment by alex** [comment]
When I attempt to _encrypt_ this value, using PKCS7 padding, the ciphertext I get is: `b'G\xd2\x01\xb6\x85s\xcd&\xbb\xd4\xbf\xee\x9bG\x03\x06\xa6\xdaz!\xef\xa1ZDx5Q\xe1\x1a\xf6*\xaa\xd3\x9e\xfa\xd3\xd1\xd7\xc0\xcd\xcbJ|\xfa)\xbb\x94\xb7'`. Why do you think our decryption is wrong, instead of wolfssl's encryption being wrong?

**Comment by twilkerson1237** [comment]
I dont think I've stated that it's wrong anywhere. I am wondering if there's anything critical from your library I could be missing.

**Comment by twilkerson1237** [comment]
I should also add that I can see in WolfSSLs implementation that they gutted the C implementation of Camellia from Nippon. So if WolfSSL is wrong then Nippon is wrong...

**Comment by alex** [comment]
There's nothing special about our camellia implementation (which is just OpenSSL's) -- and we test it with a bunch of vectors from NTT and from OpenSSL: https://github.com/pyca/cryptography/tree/main/vectors/cryptography_vectors/ciphers/Camellia

**Comment by twilkerson1237** [comment]
Fair enough, then I'll do some more digging to see what else I can fine. I'll close this.
