### ISSUE TITLE
Replace codecov with something else

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#5981]
Motivation: Very long periods of unreliability (it's been years now)

Requirements:
- Merge coverage across multiple jobs/languages
- Be highly reliable
- Present coverage results in a way we can easily process them

Options:
- Find some other SaaS -- I'm not aware of any
- Build something ourselves

Here's the sketch of a possible design built entirely out of github actions:

- At the end of every job, we upload the coverage results with https://github.com/actions/upload-artifact
- We create a new job, which depends on all of our existing jobs, for aggregating coverage
  - It pulls down all of the coverage artifacts with https://github.com/actions/download-artifact
  - It merges them together
  - If 100% coverage is acheived, it exits with a success status code -- this results in a green status on the GHA for it
  - If there's missing coverage, it computes a report of what's missing. This report is itself uploaded as an artifact, and it also leaves a comment pointing out the missing coverage. It exists with a failing status code
- We mark this new job as required to pass

Ideally the github actions stuff we build can be implemented in a somewhat generic way so it's reusable across all PyCA projects, and maybe even other projects

**Comment by webknjaz** [comment]
> Ideally the github actions stuff we build can be implemented in a somewhat generic way so it's reusable across all PyCA projects, and maybe even other projects

FYI https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action — it's alpha-quality but usable.

**Comment by reaperhulk** [comment]
We now merge coverage and fail if under 100 within actions itself for our Python code. We continue to use codecov for Rust coverage at this time.

**Comment by alex** [comment]
The _easiest_ outcome here would be a way to take an lcov file and turn it into a coverage file that coverage.py can handle.
