### ISSUE TITLE
SECURITY: CI is downloading and executing bash scripts hosted by a 3rd party

### ISSUE THREAD

**Issue by x448** [pyca/cryptography#5986]
On April 15, [Security Week reported](https://www.securityweek.com/codecov-bash-uploader-dev-tool-compromised-supply-chain-hack):

>Security response professionals are scrambling to measure the fallout from a software supply chain compromise of Codecov Bash Uploader that went undetected since January and exposed sensitive secrets like tokens, keys and credentials from organizations around the world.
>
>The hack occurred four months ago but was only discovered in the wild by a Codecov customer on the morning of April 1, 2021, the company said in a note acknowledging the severity of the breach.
> ...
> Codecov is strongly encouraging software development teams to “immediately re-roll all of your credentials, tokens, or keys located in the environment variables in your CI process.”

Example CI downloading and executing bash script hosted by a 3rd party:

https://github.com/pyca/cryptography/blob/f0b2269f7221f06aacf883b58577ffc9627e7522/.github/actions/upload-coverage/action.yml#L12-L18

It would be safer to embed python inside the workflow .yml to generate a coverage badge and detect coverage regression.  See [my workflow example](https://github.com/x448/workflows).  It was kept simple for easy review.  More features can be added.

**Comment by alex** [comment]
You were already told in https://github.com/pyca/pynacl/issues/664 that we've looked into this and aren't impacted.

Please stop filing these. I realize you're trying to be helpful, but they're just spam at this point.

**Comment by x448** [comment]
Thanks for letting me know, I didn't realize you replied and will not open issues in your projects.  The decision to continue downloading and executing bash scripts from 3rd-parties is entirely your call and not for me to judge.
