### ISSUE TITLE
[QUESTION] Not a bug - but a WARNING to others building in Docker

### ISSUE THREAD

**Issue by ortonomy** [pyca/cryptography#5991]
When building in an alpine docker with python 3.9, you've got to be really careful of this package.

Not only do you need to install build dependencies for rust, even if you delete all the dependencies post `pip install` it will leave over **250mb** or rust artefacts in `~/.cargo`. There should be a warning somewhere as this exploded my image size....

**Comment by alex** [comment]
The best solution to these problems is to use a multi-stage docker build: https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds
