### ISSUE TITLE
load_key_and_certificates requires backend but doc shows it as optional

### ISSUE THREAD

**Issue by achapkowski** [pyca/cryptography#5996]
I am using version 2.8 of the `cryptography` and I need to convert a PFX to Key/Cert files.  The sample shown below shows the method only needing the cert and password, but when you try to run the code, `backend` is required.  It would appear of I set backend=None, it will fail because all the method is doing is calling a method on that backend.  

Code:

```python
from cryptography.hazmat.primitives.serialization import pkcs12
pkcs12.load_key_and_certificates(data, password, backend)
```

See: 
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/?highlight=pfx#cryptography.hazmat.primitives.serialization.pkcs12.load_key_and_certificates

**Comment by reaperhulk** [comment]
Prior to version 3.1 `backend` was a required argument. You will need to do the following:

```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.serialization import pkcs12

pkcs12.load_key_and_certificates(data, password, default_backend())
```

**Comment by alex** [comment]
Or use a newer versoin of cryptography.

**Comment by tiran** [comment]
You can select documentation for older releases in the lower left corner, e.g.
https://cryptography.io/en/2.8/hazmat/primitives/asymmetric/serialization/

**Comment by achapkowski** [comment]
@alex pip install cryptography only installs version 2.20
