### ISSUE TITLE
openssl aes "xts duplicated keys" error is reported as "Unknown OpenSSL Error"

### ISSUE THREAD

**Issue by projectgus** [pyca/cryptography#5998]
Recent versions of openssl [explicitly reject duplicated AES-XTS keys](https://github.com/openssl/openssl/blob/c39352/crypto/evp/e_aes.c#L3119). Cryptography openssl backend reports this as an Unknown OpenSSL Error.

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
  * Python 3.8.5
  * cryptopraphy main branch (f08a7de65)
  * cffi==1.14.5
  * pip 21.0.1
* How you installed ``cryptography``
  * pip install -e .
* Clear steps for reproducing your bug

```
>>> from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
>>> from cryptography.hazmat.backends import default_backend
>>> badkey = b'\xEE'*32
>>> cipher = Cipher(algorithms.AES(badkey), modes.XTS(b'\x00'*16), backend=default_backend())
>>> cipher.encryptor().update(b'\x00'*16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/angus/tmp/cryptography/src/cryptography/hazmat/primitives/ciphers/base.py", line 109, in encryptor
    ctx = self._backend.create_symmetric_encryption_ctx(
  File "/home/angus/tmp/cryptography/src/cryptography/hazmat/backends/openssl/backend.py", line 460, in create_symmetric_encryption_ctx
    return _CipherContext(self, cipher, mode, _CipherContext._ENCRYPT)
  File "/home/angus/tmp/cryptography/src/cryptography/hazmat/backends/openssl/ciphers.py", line 115, in __init__
    self._backend.openssl_assert(res != 0)
  File "/home/angus/tmp/cryptography/src/cryptography/hazmat/backends/openssl/backend.py", line 210, in openssl_assert
    return binding._openssl_assert(self._lib, ok, errors=errors)
  File "/home/angus/tmp/cryptography/src/cryptography/hazmat/bindings/openssl/binding.py", line 80, in _openssl_assert
    raise InternalError(
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=101511351, lib=6, func=207, reason=183, reason_text=b'error:060CF0B7:digital envelope routines:aesni_xts_init_key:xts duplicated keys')])
```

We can probably submit a patch to convert this into a more user-friendly error. If that sounds good, I was wondering how you prefer to do this. For example a couple of ideas:

1. Python-side check that throws something like a ValueError when parsing the key+mode. (This makes the assumption that cryptography is OK to always reject vulnerable duplicate keys regardless of what the backend does, so I wanted to check that's OK and not going to break anything.)
2. Check the openssl error in hazmat/backends/openssl/ciphers.py and raise something specific there based on `EVP_R_XTS_DUPLICATED_KEYS` error.

Context: This was submitted by one of our users https://github.com/espressif/esptool/issues/621

Thanks very much for all the great work on this library, we really appreciate being able to rely on it!

**Comment by projectgus** [comment]
Extra thing-to-maybe-care-about is that in non-FIPS mode, openssl allows the duplicate key for decrypting. So it might be reasonable to do the check in Python but only if encrypting? or do the checks in the Python side of the backend and match the FIPS/not-FIPS logic in Python?

**Comment by reaperhulk** [comment]
I think handling the `EVP_R_XTS_DUPLICATED_KEYS` error case is the best path, assuming that error occurs in LibreSSL as well (which our CI can help confirm). If it doesn't we'll revisit. If you want to send a PR that'd be great, thank you for the kind words about the library 😄
