### ISSUE TITLE
AttributeError: function/symbol 'SHA256_init' not found in library '/usr/local/lib/python3.8/site-packages/Crypto/Util/../Hash/_SHA256.cpython-38-x86_64-linux-gnu.so': /usr/local/lib/python3.8/site-packages/Crypto/Util/../Hash/_SHA256.cpython-38-x86_64-linux-gnu.so: undefined symbol: SHA256_init

### ISSUE THREAD

**Issue by starwk** [pyca/cryptography#6004]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by reaperhulk** [comment]
We do not directly bind this symbol, which strongly implies there's something going on with your environment and not specifically with cryptography. Please provide a method to reproduce this and we can potentially help out, but the error message is insufficient.

**Comment by alex** [comment]
The paths here _strongly_ suggest you're trying to use PyCrypto, and not pyca/cryptography, which is what this repo is for.

**Comment by starwk** [comment]
> We do not directly bind this symbol, which strongly implies there's something going on with your environment and not specifically with cryptography. Please provide a method to reproduce this and we can potentially help out, but the error message is insufficient.

`>>> SHA256.new('dsfsd'.encode('utf-8'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/Crypto/Hash/SHA256.py", line 158, in new
    return SHA256Hash().new(data)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Hash/SHA256.py", line 73, in __init__
    result = _raw_sha256_lib.SHA256_init(state.address_of())
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/usr/local/lib/python3.8/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'SHA256_init' not found in library '/usr/local/lib/python3.8/site-packages/Crypto/Util/../Hash/_SHA256.cpython-38-x86_64-linux-gnu.so': /usr/local/lib/python3.8/site-packages/Crypto/Util/../Hash/_SHA256.cpython-38-x86_64-linux-gnu.so: undefined symbol: SHA256_init
`

**Comment by reaperhulk** [comment]
As @alex pointed out this is quite clearly not our project.

**Comment by starwk** [comment]
> The paths here _strongly_ suggest you're trying to use PyCrypto, and not pyca/cryptography, which is what this repo is for.

Thank you for your help. I've solved it
