### ISSUE TITLE
pip install cryptography fail

### ISSUE THREAD

**Issue by multicodemarc** [pyca/cryptography#6013]
Keep trying to install cryptography but keep receiving the error underneath, new to programming and trying to make a basic encryption/decryption script. Any help is greatly appreciated 

![image](https://user-images.githubusercontent.com/83234860/116113564-96288b00-a686-11eb-96d2-118ac47d53c0.png)

**Comment by alex** [comment]
This error doesn't involve cryptography at all -- this error is coming entirely from inside of `pip`. I expect this would mean that _any_ `pip install` command would fail.

I assume this means that your pip installation or your python installation is somehow corrupted, but we're not able to provide support for this.
