### ISSUE TITLE
Failed building wheel for cryptography on Ubuntu 16.04 32-bit

### ISSUE THREAD

**Issue by smrachi** [pyca/cryptography#6017]
Hello, 
I installed python3.9 from `ppa:deadsnakes/ppa` on Ubuntu 16.04 32-bit and I want to `pip install cryptography` but it fails building wheel for cryptography.
I tried with python3.5 (by default installed in Ubuntu 16.04), cryptography installed with no problem and everything is OK.
However, I need python3.6+. I did set environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1` but the problem didn't solved. Also installed Rust Compiler and again failed. 

I attached the log in a text file so that you will be informed what has happened.
[log.txt](https://github.com/pyca/cryptography/files/6386036/log.txt)

Used versions:

    python       3.9  (3.6+ needed)
    rustc        1.47.0
    pip          21.1
    setuptools   49.2.1
    cffi         1.14.5
    gcc          Ubuntu 5.4.0-6ubuntu1~16.04.11 5.4.0 20160609
    openSSL      1.0.2g  1 Mar 2016

Do you have any idea what is the problem? and how can it be solved? 

Thanks in advance.

**Comment by alex** [comment]
Please provide us with instructions for reproducing this (e.g. a `Dockerfile`)

**Comment by smrachi** [comment]
I'm donig it in a virtual environment in vm. Sorry, i'm not familiar with dockerfiles. 
I't can be reproduced using this steps in ubuntu 16.04 32bit: 
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.6 python3.6-dev python3.6-venv
python3.6 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install cryptography
````

**Comment by smrachi** [comment]
I did exactly the same steps in ubuntu 16.04 64-bit and it works. I've no idea what's the problem with 32-bit !

**Comment by tiran** [comment]
The project does not provide binary wheels for 32bit X86 Linux platform, only for X86_64 64bit Linux platform.

**Comment by smrachi** [comment]
So, is it possible to build the cryptography package from source for 32 bit?

**Comment by alex** [comment]
Yes, it is. Your steps to reproduce do not involve installing Rust,
which is why you get that error.

On Thu, Apr 29, 2021 at 6:55 AM Mohsen Rahchamani
***@***.***> wrote:
>
> So, is it possible to build the cryptography package from source for 32 bit?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.

**Comment by smrachi** [comment]
> Yes, it is. Your steps to reproduce do not involve installing Rust,
> which is why you get that error.
> 
> On Thu, Apr 29, 2021 at 6:55 AM Mohsen Rahchamani
> ***@***.***> wrote:
> >
> > So, is it possible to build the cryptography package from source for 32 bit?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 
> 
> -- 
> All that is necessary for evil to succeed is for good people to do nothing.
> 

My bad. Actually I installed Rust compiler by `sudo apt install rustc` before making venv, but forgot to write it in above steps.

**Comment by reaperhulk** [comment]
The error strongly suggests that `rustc` is not being found in your path. Additionally, the latest versions of cryptography do not support OpenSSL 1.0.2, which Ubuntu 16.04 ships with. Building cryptography for 32-bit with a newer OpenSSL for use on your (soon to be end of life) distribution is possible (you can look at our wheel builder for inspiration), but it is complex.
