### ISSUE TITLE
FAQ on delegating to only OS OpenSSL

### ISSUE THREAD

**Issue by chrish42** [pyca/cryptography#6049]
Hi. For reasons you may guess, I'd need to use `cryptography` in a way where it uses the operating system's OpenSSL library for its openssl backend, and where all other backends are disabled (so that if things are not supported by the OpenSSL backend, they return an error). I expect I would need to build my own version of `cryptography` for this, which is totally fine.

My question is, is this a supported mode of operation for `cryptography` when rebuilding from source? Because this would have some implications for the source code — keeping the concept of multiple backends alive, etc. Given that the OpenSSL library is still the "cryptographic library of record", I'm guessing the answer here is a "yes" until that changes, but it would be nice to have that confirmed officially in the FAQ.

So, once I get a confirmation here, I'm offering to create a pull request to update the FAQ with that information, and add a recipe there to help others who need to rebuild `cryptography` that way. Hopefully that's helpful. Thanks!

**Comment by alex** [comment]
We only have one backend, which is OpenSSL, the backends API is vestigal at this point. We document how to link against your OpenSSL on Linux here: https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-linux

But tl;dr; disable installing from wheels, andmake sure CFLAGS and LDFLAGS are correct.

**Comment by chrish42** [comment]
What about the Rust dependency being added? Won't some crypto be delegated to a Rust crypto library at some point?

**Comment by alex** [comment]
I assume your concern here is FIPS or something like that?

The stuff we're using the Rust code for is ops that we previously had
our own implementation of (e.g. PKCS7 unpadding) and ASN.1 parsing.

On Fri, May 14, 2021 at 3:02 PM Christian Hudon
***@***.***> wrote:
>
> What about the Rust dependency being added? Won't some crypto be delegated to a Rust crypto library at some point?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
All that is necessary for evil to succeed is for good people to do nothing.
