### ISSUE TITLE
[Feature request] Parse DN string into list of NameAttribute's

### ISSUE THREAD

**Issue by pprindeville** [pyca/cryptography#6050]
There seems to be no way to convert a string (or bytestring) containing a Distinguished Name or X.509 Subject into a list of corresponding NameAttributes, suitable for (example) passing to `x509.CertificateSigningRequestBuilder().subject_name()`.

There's the `rfc4154_string()` which goes in the opposite direction, however.

Using Python 3.8.2 on MacOS 11.3.1, `cryptography` 3.4.7 (installed via `pip3`).

**Comment by pprindeville** [comment]
Here's most of a naïve implementation:

```
from cryptography import x509
from cryptography.x509.oid import NameOID

import re

oidMap = {
    'CN': NameOID.COMMON_NAME,
    'C': NameOID.COUNTRY_NAME,
    'L': NameOID.LOCALITY_NAME,
    'ST': NameOID.STATE_OR_PROVINCE_NAME,
    'SP': NameOID.STATE_OR_PROVINCE_NAME,
    'S': NameOID.STATE_OR_PROVINCE_NAME,
    'STREET': NameOID.STREET_ADDRESS,
    'O': NameOID.ORGANIZATION_NAME,
    'OU': NameOID.ORGANIZATIONAL_UNIT_NAME,
    'SN': NameOID.SURNAME,
    'GN': NameOID.GIVEN_NAME,
    'T': NameOID.TITLE,
    'MAIL': NameOID.EMAIL_ADDRESS,
    'E': NameOID.EMAIL_ADDRESS,
    'PC': NameOID.POSTAL_CODE,
}

def parse_dn(s):
    """Parse a string into a set of OIDs"""

    attrs = []

    if s[0:1] != '/':
       raise ValueError
    s = s[1:]

    # need to handle escaping of the RHS, etc.
    prog = re.compile(u'([A-Z]+)=(.*)')
    for pair in s.split('/'):
        match = prog.fullmatch(pair)
        if match:
           (name, value) = match.group(1, 2)
           if not name in oidMap:
               raise ValueError
           attrs.append(x509.NameAttribute(oidMap[name], value))

    return attrs
```

**Comment by pprindeville** [comment]
Duplicate of #6165?

**Comment by reaperhulk** [comment]
I don't like the idea of having code that tries to map stringly typed things like this into more structured formats. Yes there exists a spec, but I strongly suspect that there exist dozens of slightly incompatible variants, each of which people want to work. I think I'd rather this was a mapping that users built themselves so that they can ensure it is fully compatible with whatever quirky implementation they're actually relying on. (For the record, I regret landing `rfc4154_string`)

**Comment by pprindeville** [comment]
>  I think I'd rather this was a mapping that users built themselves so that they can ensure it is fully compatible with whatever quirky implementation they're actually relying on.

_One ring to rule them all._

That's the nice thing about reference implementations: it gives people a **correct** way of doing something conveniently in their reach so they're not tempted to stray down the path of brokenness and divergence, at least not without a lot of additional unwarranted effort.

**Comment by intgr** [comment]
> code that tries to map stringly typed things like this into more structured formats.

I think you're describing serialization all formats. :) I view RFC 4514 as a just another serialization format in the cryptography domain.

You can have non-conforming implementations and vendor extensions with binary formats like X.509 as well. Like negative serial numbers ( #4843), negative RSA moduli (https://bugs.chromium.org/p/chromium/issues/detail?id=532048), I'm sure there are dozens of examples. And sometimes those situations require difficult decisions. That's just the reality of interoperability.

If `cryptography` library doesn't accept RFC 4514 support in core, users who need it will probably implement it themselves, and most likely do a worse job than this project could. I think that's a net loss for everyone -- duplicated effort and worse interoperability.

**Comment by mathiasertl** [comment]
FTR, I proposed a solution in #6166. I'm open to providing a more traditional parser solution that does not use `shlex` as well (I just think it's essentially going to be the same result).
