### ISSUE TITLE
[Feature request] Need to prime/construct CSR Builder objects from a CSR

### ISSUE THREAD

**Issue by pprindeville** [pyca/cryptography#6053]
If I receive a CSR (say via webform, email, or as a file on a thumb drive), there's no easy way to sign it via a CSR Builder object.  Requesting a way to load or construct a CSR Builder object from a CSR object.

Using Python 3.8.2 on MacOS 11.3.1, cryptography 3.4.7 (installed via pip3).

**Comment by alex** [comment]
Because which fields from a CSR may be trusted to be signed is highly contextual, we do not provide APIs which automatically map between CSRs and builders.
