### ISSUE TITLE
version 2.8: ssh connections fails with "ECDSA keys with unnamed curves are unsupported at this time" curve prime256v1 

### ISSUE THREAD

**Issue by 16raghu** [pyca/cryptography#6061]
Hi @reaperhulk / @alex,

I am new to OpenSSL. As part of work I was stepping into an issue where I was getting "ECDSA keys with unnamed curves are unsupported at this time". The OpenSSL I am using is 1.1.1.
As part of netconf connection via paramiko creating and ssh connection. And found that the curve here was prime256v1 and it looks like "backend._lib.EC_GROUP_get_asn1_flag(group)" was called before _mark_asn1_named_ec_curve(). If I change back this class "_EllipticCurvePrivateKey".

    sn = _ec_key_curve_sn(backend, ec_key_cdata)
    self._curve = _sn_to_elliptic_curve(backend, sn)
    _mark_asn1_named_ec_curve(backend, ec_key_cdata)
to
_mark_asn1_named_ec_curve(backend, ec_key_cdata)
sn = _ec_key_curve_sn(backend, ec_key_cdata)
self._curve = _sn_to_elliptic_curve(backend, sn)

it works fine. Just wanted to check If I can do this change in my system?

As this is I am facing here is while doing an ssh connection is via netconf ->paramiko->then cryptography. 
the Curve being used here is 'prime256v1' (got from print statements).

Will try to get the reproduction steps. 

Regards,
Raghu

**Comment by alex** [comment]
Well, no, you can't just change the order, if you check for the flag after you call mark, then checking the flag does nothing.

This check is intentionally there to ensure we don't load keys that aren't serialized with a named curve, why do you think your key should be loaded?

**Comment by 16raghu** [comment]
I know FIPS is not supported officially, one more observation is this only fails when fips mode is set to True.  When fips mode is set to False it still uses the same curve (prime256v1) and asn1 is set.

Now I am not able to figure out why asn1 not being set for FIPS mode.

**Comment by 16raghu** [comment]
Ignore this as our SSL library was not setting the asn1 flag in FIPS mode.
