### ISSUE TITLE
"unexpected eof while reading (_ssl.c:2471)" errors when switching to OpenSSL 3.0.0 beta1-dev

### ISSUE THREAD

**Issue by Tarnum-tst** [pyca/cryptography#6069]
Hello!

I'm using Python 3.7 with cryptography 35.0.0.dev1 on Windows. Everything was fine with OpenSSL 1.1.1k, but when switching to OpenSSL 3.0.0 beta1-dev I start receiving tons of "unexpected eof while reading (_ssl.c:2471)" while operating on established local SSL tunnel for ... website messages.
It probably could be fixed by setting SSL_OP_IGNORE_UNEXPECTED_EOF option via SSL_CTX_set_options exported from libssl DLL.

Because I'm noob in Python, I need an example of how I could do this, for example, via "src/cryptography/hazmat/bindings/openssl/binding.py" immediately after loading legacy and default providers. Thanks!

**Comment by tiran** [comment]
Hi,

the error message is unrelated to PyCA cryptography. It's coming from Python's ssl module.

I have been working on OpenSSL 3.0.0 support for Python's ssl module. However Python 3.7 is in security fix-only mode and will not get OpenSSL 3.0.0 support. You have to update to 3.8.10 or 3.9.5.
