### ISSUE TITLE
Timeout on importing `from cryptography.hazmat.primitives.ciphers import aead`

### ISSUE THREAD

**Issue by janluak** [pyca/cryptography#6088]
Hey,
I am using [cognitojwt](https://github.com/borisrozumnuk/cognitojwt) and [python-jose](https://github.com/mpdavis/python-jose) for validating a AWS Cognito JWT token in a python lambda authorizer.

For some strange reason the function times out in importing `cryptography.hazmat.backends.openssl.aead`
With some narrowing down I got to the point of line 10 from [this file](https://github.com/mpdavis/python-jose/blob/master/jose/backends/cryptography_backend.py) is failing.

Strange thing: when running the import separately at the beginning of the script there is no issue. But the import within python-jose isn't working.
Any idea?
I'm setting everything up with latest version of serverless framework and AWS Lambda python3.8 env.

isolated working import codes in AWS Lambda:
```
from cryptography.hazmat.backends.openssl import aead
<or>
from cryptography.hazmat.primitives.ciphers import Cipher, aead, algorithms, modes
```

the actual code snippet timing out (at line 10 of [python-jose file](https://github.com/mpdavis/python-jose/blob/master/jose/backends/cryptography_backend.py)):
```
from cognitojwt import decode

return decode(
            token=authorization_token,
            region=os.environ["AWS_REGION"],
            userpool_id=os.environ["USER_POOL_ID"],
            app_client_id=os.environ["USER_POOL_CLIENT_ID"]
        )["cognito:username"]
```

**Comment by alex** [comment]
The only thing I could possibly imagine is that if your kernel had no entropy for some reason, so any attempt to generate a random number blocked.

I can't imagine why that'd be the case in lambda.
