### ISSUE TITLE
Interoperability with CryptoJS

### ISSUE THREAD

**Issue by jeffkitson-music** [pyca/cryptography#6120]
This is a help wanted post. 

I am working on a project that I would like to be interoperable with CryptoJS. I found the following [gist for PyCrypto](https://gist.github.com/adrianlzt/d5c9657e205b57f687f528a5ac59fe0e), but can't quite get it right in cryptography. 

Can someone help, please?

**Comment by alex** [comment]
Docs for symmetric encryption and padding are at https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/ and https://cryptography.io/en/latest/hazmat/primitives/padding/ respectively.

If there's a specific thing that's lacking in our docs we will try to improve it, but we can't simply do the implementation for you.
