### ISSUE TITLE
multi-prime RSA key support

### ISSUE THREAD

**Issue by metalalive** [pyca/cryptography#6124]
**My question is : Does `cryptography` support multi-prime RSA key ? if not , would it be supported in future version ?**

I am working on a Python application which requires the user data to be signed and verified using  **RSA key with multiple primes** , I also need to separate each component of the private key as part of application requirement. Typically there are only 2 primes applied (which is `p` and `q`) to RSA algorithm, so I tried to figure out how to generate multi-prime RSA key (as well as load such key from external source) with this `cryptography` library  `3.4.7` (latest version as of creating this issue).

Here is minimal code sample I've tried , note `/PATH/TO/rsa_private_multi_prime.pem` is PEM file generated by my openssl (v1.1.1) C program and  it is verified by other of my C applications :
```python
with open("/PATH/TO/rsa_private_multi_prime.pem", "rb") as f:
    private_key = serialization.load_pem_private_key(f.read(), password=None)
    priv_nums = private_key.private_numbers()
    print(priv_nums.__dict__.keys())
```
the code above prints :
```
dict_keys(['_p', '_q', '_d', '_dmp1', '_dmq1', '_iqmp', '_public_numbers'])
```

After reading [the documentation for loading key from PEM file](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#key-loading) and [how openssl backend retrieves all components of a RSA private key](https://github.com/pyca/cryptography/blob/main/src/cryptography/hazmat/backends/openssl/rsa.py#L433) , I found that `_RSAPrivateKey.private_numbers()`  returns  only 2 primes (`p` and `q`) , which deos NOT cover multi-prime key case.

I've come across many online python communities , [FAQ documentation](https://cryptography.io/en/latest/faq.html),  as well as all existing issues in this repository,  unfortunately none of them describes the same question I have.  I also know that I can do this in C by building [Python C extension](https://docs.python.org/3/extending/extending.html) invoking related openSSL APIs like [RSA_generate_multi_prime_key](https://www.openssl.org/docs/man1.1.1/man3/RSA_generate_multi_prime_key.html) , and [RSA_get0_multi_prime_factors](https://www.openssl.org/docs/man1.1.1/man3/RSA_get0_multi_prime_factors.html) , but I still wonder if I can do it with `cryptography` ? thanks for reading

**Comment by alex** [comment]
We don't officially support multi-prime RSA. It's possible it works with keys loaded from PEMs by chance though.

In general we're unlikely to expand support for it, as there's not really any good reason to use it, it's strictly less secure than 2 prime RSA.

**Comment by metalalive** [comment]
> In general we're unlikely to expand support for it, as there's not really any good reason to use it, it's strictly less secure than 2 prime RSA.

Thanks for the reply, good to know about that.
