### ISSUE TITLE
Could not find a version that satisfies the requirement cryptograpy (from versions: none)

### ISSUE THREAD

**Issue by deepakjuit** [pyca/cryptography#6133]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by deepakjuit** [comment]
![image](https://user-images.githubusercontent.com/42043954/122689029-90da5d80-d23d-11eb-8e9f-00cfc7ddfd74.png)

**Comment by alex** [comment]
The package's name is `cryptography`, not `cryptograpy`
