### ISSUE TITLE
[Feature request] AES-OCB

### ISSUE THREAD

**Issue by wasamasa** [pyca/cryptography#6136]
Old issues: https://github.com/pyca/cryptography/issues/1770 https://github.com/pyca/cryptography/issues/2968

The latter mentions patent issues. There is a license issued to OpenSSL specifically, so I wouldn't expect that to be a problem. However note that as of 2021 the patents have not been renewed, thereby allowing the IP to move into public domain: https://mailarchive.ietf.org/arch/msg/cfrg/qLTveWOdTJcLn4HP3ev-vrj05Vg/. Therefore there should be no more blockers to expose that particular API.

**Comment by reaperhulk** [comment]
Interesting, I thought we had an open issue for this. Thanks for filing a new one. Yes, patent encumbrance is no longer an issue here and we can expose this. Now it's just a matter of doing the work 😄. Hopefully OpenSSL implements OCB3, although I haven't verified that yet.
