### ISSUE TITLE
Key serialisation

### ISSUE THREAD

**Issue by public** [pyca/cryptography#614]
This is a brain dump of my research of key serialisation and a space to discuss APIs for it.

Loosely there are two types of serialisation format.

 1. Ones that tell you about what they contain.
 2. Ones that don't.

In category 1 there are
 * PEM format PKCS#1 
 * All flavours of PKCS#8
 * OpenSSH (PEM PKCS#1 with different headers.)
 * JWK

In category 2 there is
 * DER format PKCS#1 

I propose we ignore category 2 until someone comes up with an obvious use-case of protocol that needs it. (paramiko/conch might be this?)

Category 1 keys are not all specified for the same range of algorithms, but they all support at the very least RSA, DSA, and ECDSA. There are also RFCs in various states of dereliction that describe serialisation for other asymmetric algorithms.

Category 1 can be further broken down into (1.A) formats that support public and private keys, (1.B) formats that only support private keys and (1.C) formats that only support public keys.

In category 1.A there are
 * PKCS#8
 * JWK

In category 1.B there is
 * PKCS#1

In category 1.C there are
 * OpenSSH
 * PEM formatted `subjectPublicKey`

PKCS#1 public keys are sometimes called "X.509 certificates" which is also kind of wrong as it's often just the raw `subjectPublicKey` data that is defined across various RFCs for each algorithm. I guess they called it asymmetric for a reason.

I propose we ignore serialised public keys at first, but keep them in mind...

This leaves private key loaders for

 * PEM PKCS#1
 * PKCS#8
 * JWK

I think PEM PKCS#1 is probably the most common of these, and it also happens to involve a lot of the work needed for OpenSSH keys. OpenSSL sometimes call this the "traditional" format.

PEM PKCS#1 has 2 flavours. Encrypted, and not encrypted. Encrypted keys are described in [RFC 1423](https://tools.ietf.org/html/rfc1423) among other places. Basically they are the same as unencrypted ones but the DER is encrypted first and some additional `DEK-Info` headers describing the encryption parameters are added to the PEM.

PEM PKCS#1 keys do not contain the key type within their base64 encoded payload. It only exists in the PEM headers.

Also some of these formats contain additional metadata about the key that it is important to retain access too. OpenSSH contains a comment value, PKCS #8 has various key usage attributes.

Currently I imagine an interface a bit like this.

```python
key = PKCS1PrivateKey.load_pem(data, password, backend)
key.private_key # The underlying {RSA,DSA,ECDSA....}PrivateKey

key = PKCS1PrivateKey(key.private_key, backend)
pem_data = key.dump_pem(algorithm, mode, PBKDF2HMAC(...), password)
```

Where unencrypted keys are created by setting basically everything to `None`, because you probably shouldn't be using those anyway. Additional key usage attributes and so on can easily be added to the specific formats interface.

- [x] OpenSSL PEM private key loading
- [x] OpenSSL PEM public key loading
- [x] OpenSSL PEM private key saving
- [x] OpenSSL PEM public key saving
- [x] PKCS8 PEM private key loading
- [x] PKCS8 PEM public key loading
- [x] PKCS8 PEM private key saving
- [ ] PKCS8 PEM public key saving
- [ ] OpenSSH private key loading
- [x] OpenSSH public key loading
- [ ] OpenSSH private key saving
- [ ] OpenSSH public key saving

**Comment by reaperhulk** [comment]
I'm going to close this in favor of more specific issues (e.g. support more encryption types, OpenSSH public key serialization, etc)
