### ISSUE TITLE
[Usage Question] Extracting Client Certificate for `requests` call

### ISSUE THREAD

**Issue by achapkowski** [pyca/cryptography#6153]
I am able to find my PKI certificate from the windows certificate store by doing the following:

```python
import wincertstore
import cryptography
from cryptography.hazmat.primitives.serialization.pkcs12 import (
    load_key_and_certificates,
)
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    PrivateFormat,
    NoEncryption,
)

backend = cryptography.hazmat.backends.default_backend()

if os.name == 'nt':
    for storename in ["MY"]: 
        with wincertstore.CertSystemStore(storename) as store:
            for cert in store.itercerts(usage=wincertstore.CLIENT_AUTH):
                if cert.get_name().lower() == certificate_name.lower():
                    pem = cert.get_pem()  # returns string with proper tags
                    #WRONG METHOD I THINK pem_x509 = load_pem_x509_certificate(data=pem.encode(), backend=backend) 
                    pk12_password = b"<some password>"
                    pk12 = load_key_and_certificates(pem.encode(), pk12_password,backend)  # builtins.ValueError: Could not deserialize PKCS12 data
```

The .NET the workflow goes something like this:

**PSEUDO CODE**
```

store = X509Store(StoreName.MY, StoreLocation.CurrentUser)
store.Open(ReadOnly)

certCollection = store.Certificate.Find(FindBySubjectName, user, False)
cert = certCollection.get_Item(0)
pkcs12 = cert.Export(...)
...

```

My goal is to use this client/PKI certificate installed on the Windows machine and pass that certificate into a `requests` call.

Am I on the right route?  I've been banging my head against the wall trying to figure this out. 

I followed the instructions in the FAQ: https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file and I am posting a question here because I am truly stuck.

**Comment by tiran** [comment]
Please don't use wincertstore any more. All supported Python versions have ``ssl.enum_certificates``.

**Comment by achapkowski** [comment]
@tiran OK on that point.  It returns the certificate as bytes, but I have the same issue.

**Comment by tiran** [comment]
The function either X.509 cert blobs or PKCS#7 blobs as ASN.1 bytes in DER format. It does not return private keys (hence the name ``itercerts`` / ``enum_certificates``). Client cert authentication requires both cert and private key.

You probably want to use OpenSSL's CAPI ENGINE instead. It provides direct integration of OpenSSL with Windows' Crypto API for client cert authentication.

**Comment by achapkowski** [comment]
pyopenssl says I should use this library over pyopenssl.  Are you saying this functionality is not exposed in cryptography?

**Comment by reaperhulk** [comment]
cryptography has key and cert facilities, but it appears you need a way to obtain the *key* from the windows cert store. cryptography can't help with that.
