### ISSUE TITLE
Problem with type annotations on HashAlgorithm

### ISSUE THREAD

**Issue by ronf** [pyca/cryptography#6157]
Python version: 3.9.5/3.10.0b2 (though this appears in other Python versions)
PyCA version 3.4.7 (latest at the current time) on macOS, installed from pre-built wheels

I've begun to use mypy on code that depends on PyCA. I had things working pretty well with an older version of Cryptography installed (probably with fewer things annotated), but I starting seeing an issue related to HashAlgorithm when using PyCA 3.4.7. My code builds a dictionary of hash algorithms as follows:

```python
from cryptography.hazmat.primitives.hashes import MD5, SHA1, SHA224
from cryptography.hazmat.primitives.hashes import SHA256, SHA384, SHA512

hashes = {h.name: h for h in (MD5, SHA1, SHA224, SHA256, SHA384, SHA512)}
```

It then expects to be able to instantiate a hash based on its name with code like:

```python
hash_instance = hashes[hash_name]()
```

When I attempt this with PyCA 3.4.7, I get the following errors:

```
/tmp/t.py:6: error: Cannot instantiate abstract class "HashAlgorithm" with abstract attributes "block_size", "digest_size" and "name"
/tmp/t.py:6: error: Invalid index type "str" for "Dict[Callable[[HashAlgorithm], str], Type[HashAlgorithm]]"; expected type "Callable[[HashAlgorithm], str]"
```

Part of the problem here appears to be that h.name is actually an abstract property resulting in the index having the "Callable[HashAlgorithm], str]" property rather than just plain "str", which is what it ends up actually being in the dictionary I create. However, I think the errors also relate to mypy thinking that I'm trying to instantiate the abstract parent class HashAlgorithm, rather than the concrete subclasses of that which are actually being placed into the dictionary.

I've worked around the issue for now by using:

```python
hashes = {
    str(h.name): h for h in (MD5, SHA1, SHA224, SHA256, SHA384, SHA512)
} # type: Mapping[str, Callable[[], HashAlgorithm]]
```

This isn't pretty, but it does seem to satisfy mypy. Suggestions are welcome as to alternatives. I'm not all that familiar with the "abc" classes the PyCA is using for classes like this and how they interact with type annotations.

**Comment by alex** [comment]
Apologies this sat so long. I think the fix here is to instantiate the hash types, so:

```py
hashes = {h.name: h for h in (MD5(), SHA1(), SHA224(), SHA256(), SHA384(), SHA512())}
```
