### ISSUE TITLE
Add X509Certificate2 Export Support

### ISSUE THREAD

**Issue by achapkowski** [pyca/cryptography#6160]
For windows systems, the ability to export and convert client certificates is needed.  Currently the only way I know how to do this is to use the pythonnet library.  

Since the cryptography package is the go-to in certificate management, I think it would be a great value add for the package.

**Comment by reaperhulk** [comment]
This feature requires platform specific code for accessing the windows cert store. However, functionality similar to the windows cert store is available on other platforms (e.g. GNOME keyring, macOS keychain, etc). Although I agree that getting access to these features through Python is great, that functionality is ultimately outside the scope of this library. We're happy for people to develop tools like this and use cryptography to parse and serialize the files though!
