### ISSUE TITLE
Attribute Error: 'x.509' object has no attribute 'extensions'

### ISSUE THREAD

**Issue by p4pifor** [pyca/cryptography#6164]
Hi,

I've installed cryptography: pip install cryptography. However, whenever I call an extension of x.509: 
**certificate.extensions.get_extension_for_oid(ExtensionOID.AUTHORITY_INFORMATION_ACCESS).value** 
I get this error "Attribute Error: 'x.509' object has no attribute 'extensions'".
Anyone could help me or give me a clue of what could it be related with? I've checked openssl and cryptography versions and they are up to date in my linux system (ubuntu 16.04)
Thanks in advance

**Comment by alex** [comment]
You have not included enough information for us to diagnose this.

Please include a full reproducible example.

**Comment by p4pifor** [comment]
Hi

************************************************** **SCRIPT** ************************************************************
import base64
import ssl
import requests
from urllib.parse import urljoin
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.x509 import ocsp
from cryptography.x509.ocsp import OCSPResponseStatus
from cryptography.x509.oid import ExtensionOID, AuthorityInformationAccessOID

from OpenSSL import crypto 

from os import path
import ssl
from socket import socket, AF_INET, SOCK_DGRAM
from logging import basicConfig, DEBUG
basicConfig(level=DEBUG)  # set now for dtls import code
from dtls import do_patch
do_patch()

def get_issuer(cert):
    aia = cert.extensions.get_extension_for_oid(ExtensionOID.AUTHORITY_INFORMATION_ACCESS).value
    issuers = [ia for ia in aia if ia.access_method == AuthorityInformationAccessOID.CA_ISSUERS]
    if not issuers:
        raise Exception(f'no issuers entry in AIA')
    return issuers[0].access_location.value


with open("/home/p4/pyton3-dtls/dtls/test/certs/server-cert.pem", "r") as f:
    certFile = f.read()
cert = crypto.load_certificate(c.FILETYPE_PEM, certFile)
ca_issuer = get_issuer(cert)


************************************************************* **OUTPUT** **************************************************

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/p4/.local/lib/python3.7/site-packages/dtls/test/simple_client.py", line 28, in get_issuer
    aia = cert.extensions.get_extension_for_oid(ExtensionOID.AUTHORITY_INFORMATION_ACCESS).value
AttributeError: 'X509' object has no attribute 'extensions'

**Comment by alex** [comment]
That's because you're using pyOpenSSL to parse the certificate, not pyca/cryptography. Documentation for parsing certificates with pyca/cryptography can be found at https://cryptography.io/en/latest/x509/reference/#loading-certificates
