### ISSUE TITLE
Creating a Certificate object from a payload of a packet which contains the certificate

### ISSUE THREAD

**Issue by p4pifor** [pyca/cryptography#6171]
Hi,

I am sending a certificate from one host(h1) to another(h2) which goes encapsulated in UDP payload. When h2 receives the packet, it is capable of extracing its payload with scapy (payld = bytes(pkt[UDP].payload)).Extracted data looks like this:

<class 'bytes'>
`b'\x00\x00\x00\x00\x04)\x00\x04&\x00\x02\x110\x82\x02\r0\x82\x01v\x02\t\x00\xb1sk\x97\x04\xb6a\x0e0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x05\x05\x000J1\x0b0\t\x06\x03U\x04\x06\x13\x02US1\x130\x11\x06\x03U\x04\x08\x13\nWashington1\x130\x11\x06\x03U\x04\n\x13\nRay CA Inc1\x110\x0f\x06\x03U\x04\x03\x13\x08RayCAInc0\x1e\x17\r140118210250Z\x17\r240116210250Z0L1\x0b0\t\x06\x03U\x04\x06\x13\x02US1\x130\x11\x06\x03U\x04\x08\x13\nWashington1\x140\x12\x06\x03U\x04\n\x13\x0bRaySrv...............`

I would like to create a Certificate object from this received data in order to build later a .pem file with it. I am trying to get it creating a CertificateBuilder as follows:

`builder= x509.CertificateBuilder()`
`builder.tbs_certificate_bytes = payld`
`print(builder)`
`with open(mypath, "wb") as f:`
     	`f.write(builder.public_bytes(serialization.Encoding.PEM))`

I know I get a CertificateBuilder object instead of a Certificate one. Afaik, the way to get a certificate object would be signing that builder with the CA's private key, however, this would en in a certificate signed twice(since it is already signed when sending from h1 to h2). Do you know any other way to do what I am trying to get?
Thanks in advance

**Comment by alex** [comment]
if you already have the DER encoded certificate, it can be loaded with https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_der_x509_certificate
