### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by kirillantonov2901** [pyca/cryptography#6197]
Installing via pip install offline on local machine. Windows 10, python 3.8.2. Having error:
Installing build dependencies ... error
Installed libraries:
setuptools-rust 0.12.1
cffi -1.14.6
pip and setuptools are latest versions
Any other libraries needed to be installed?

**Comment by tiran** [comment]
Could you please post the full error message as well as the exact versions of pip and setuptools?

**Comment by kirillantonov2901** [comment]
Pip version 21.2.3 
Setuptools 57.4.0
if u need error message in text format, please tell me

![error](https://user-images.githubusercontent.com/55129933/128690814-67b44535-7850-467e-8970-cbed1d5bcf67.jpeg)

**Comment by reaperhulk** [comment]
The error message claims the version of setuptools is too old. Since you’re also using the sdist on windows in addition to the Python packages you’ve listed you will also need MSVC and a compiled copy of OpenSSL.
