### ISSUE TITLE
Release 3.4.8 doesn't have any manylinux wheels

### ISSUE THREAD

**Issue by sethmlarson** [pyca/cryptography#6227]
See: https://pypi.org/project/cryptography/3.4.8

This is likely to cause widespread breakage due to Rust toolchain required for building from source. Obviously pinning exact versions is the "solution" but I figured if this isn't known by maintainers the wheels should be built ASAP.

**Comment by dataframing** [comment]
Yeah, running into this on a build this morning too. Happy to install `rust` on the Linux environment, just a heads-up in case the maintainers aren't aware.

**Comment by reaperhulk** [comment]
The wheels are all present now.

**Comment by reaperhulk** [comment]
Our release process currently requires uploading the sdist prior to the wheels. This brief window will go away when https://github.com/pypa/warehouse/pull/8941 (or similar) is merged or when we overhaul our release process. Until then we have a 3-10 minute window where wheels aren't available. Sorry about that!

**Comment by sethmlarson** [comment]
Could future releases be made with both sdist and wheels available immediately to avoid random transient install failures?
