### ISSUE TITLE
The library is not thread safe

### ISSUE THREAD

**Issue by socketpair** [pyca/cryptography#6256]
`ObjectIdentifier::_name` uses lazy import, which is not thread-safe.

Exactly the same issue: https://github.com/kjd/idna/issues/106

I think, could be solved by using Threading.lock...or, better, reorganize code to eliminate circular imports.

Also, it would be nice to make the property public, i.e. remove underscore from beginning.

**Comment by reaperhulk** [comment]
We don't intend to make this property public as we don't want to commit to the names as public surface. That said, moving `_OID_NAMES` into `_oid.py` will resolve the lazy import and should simplify the code anyway. If you want to submit a PR for that I'd be happy to review.
