### ISSUE TITLE
[Feature request] Support little endian CTR for AES encryption

### ISSUE THREAD

**Issue by michalc** [pyca/cryptography#6269]
WinZip's AES-encryption extension to the ZIP format uses AES in CTR mode, but in little endian encoding. It looks like Python Cryptography only supports ~little~ big endian counters, and so this makes it a bit awkward to use  to decrypt such files (and presumably, encrypt, but I've not tried).

Think it would be a useful addition to this library.

Context/links:

- There was a bit of a discussion about this in [this StackOverflow question](https://stackoverflow.com/q/69144760/1319998)
- https://github.com/danifus/pyzipper uses pycryptodomex to decrypt AES-encrypted zips
- https://github.com/uktrade/stream-unzip uses pycryptodome to decrypt AES-encrypted zips (Full disclosure: I'm involved in developing this one)

(Thanks for a great library btw!)

**Comment by reaperhulk** [comment]
We leverage OpenSSL's underlying code for this (we don't manage the counters in Python at all), so you'll probably want to open a discussion upstream with them to determine how best to support this use case. I assume you meant that winzip uses little endian while AES CTR traditionally uses big endian.

**Comment by michalc** [comment]
>  I assume you meant that winzip uses little endian while AES CTR traditionally uses big endian.

Oops yes. I've corrected the post.

Will investigate at OpenSSL's end.

**Comment by reaperhulk** [comment]
Just to follow up here, I think the probable way forward is to implement the little endian counter arithmetic in Python, encrypt generated counter blocks using a single instance of ECB mode (minimizing OpenSSL overhead), then XOR the plaintext/ciphertext into that. This is how counter mode actually works, and while it will not be as fast as doing this in pure OpenSSL if you use `update_into` you can avoid a huge number of allocations and likely get pretty reasonable performance.

**Comment by alex** [comment]
@reaperhulk for clarity, are you proposing we implement this in pyca/cryptography, or that it be implemented i user's projects?

**Comment by reaperhulk** [comment]
User project. This is an unusual requirement specific to winzip so I don’t see much value in it being inside this library. If there are more weird counters in the future maybe we'll choose to build something, but this is the first significant one in 8 years.
