### ISSUE TITLE
Any plan to support stream cipher 'Rabbit'?

### ISSUE THREAD

**Issue by lzy1g1225** [pyca/cryptography#6270]
Hi I searched whole internet there is rare library to support this cryption method - The Rabbit cipher (There is a c++ version https://cryptopp.com/wiki/Rabbit ), any plan to add Rabbit cipher into Cryptography? Thanks!

**Comment by reaperhulk** [comment]
We don't implement base cryptographic primitives directly in this project; instead they're provided by OpenSSL. Since Rabbit is part of eSTREAM it may be a candidate for inclusion in OpenSSL and you should search for open issues upstream with them (and open one if needed).
