### ISSUE TITLE
Offline installation of cryptography failing in Cloudfoundry

### ISSUE THREAD

**Issue by mlsanjaysrivatsa** [pyca/cryptography#6314]
I am trying to deploy an app in cloud foundry which has a reference to paramiko package, which in turns references the cryptography package. I would like to deploy this with complete build isolation hence I am vendoring the dependencies and pushing to CF. However I face an issue when the python buildpack tries to pip install paramiko and it fails with an not found error for the cryptography package. This works fine if I try to install unvendored (Online) or even when done locally. 

This is the command we use to download the packages to the vendor folder: pip download -r requirements.txt --no-binary :none: --dest vendor

This is the error we face: 
![image](https://user-images.githubusercontent.com/19707290/134852665-298483bc-83eb-4444-8b9a-1435d3c7870a.png)

I see the package in question while listing out the contents of the vendor directory
![image](https://user-images.githubusercontent.com/19707290/134852694-6be73779-feb5-4929-b8ca-e3626ea1692d.png)

The python version that is being used is 3.7.9 and the cryptography version needed is >=2.5

**Comment by alex** [comment]
What version of pip are you using?

**Comment by mlsanjaysrivatsa** [comment]
20.3.3 is the pip version when the packages are downloaded to the vendor directory locally. In CF the python version is 3.7.11 and the corresponding pip is used.

**Comment by reaperhulk** [comment]
This is really a packaging/install tool problem and not a cryptography problem, but is the platform you're deploying to and the platform you're downloading on identical? Linux binary wheels have a variety of limitations and what downloads via `pip download` on one machine won't necessarily work on another.

**Comment by mlsanjaysrivatsa** [comment]
So we pinned down the cryptography package to a minimum of 3.0.0 (one that is needed by us at the least) and using that version we were able to vendor in our dependencies offline. I am still not sure if there are some pip version changes that are in play but I guess we are unblocked for now.
