### ISSUE TITLE
Should the recent release be 3.5.0 and not 35.0.0?

### ISSUE THREAD

**Issue by dandhlee** [pyca/cryptography#6336]
It seems that we've jumped drastically from being `3.4.8` all of a sudden with major version bump by 32 to `35.0.0`. Unless there are that many breaking changes and cryptography was behind a huge number of breaking change releases, the version number should be reverted back to `3.5.0`.

**Comment by reaperhulk** [comment]
The very first entry in our changelog for this version explains that we've made a change: https://cryptography.io/en/latest/changelog/#v35-0-0
