### ISSUE TITLE
Version bump from 3.4.8 to 35.0.0 ?

### ISSUE THREAD

**Issue by pierresouchay** [pyca/cryptography#6339]
There seems to be a fat finger involved while bumping newer version... this version is already available on pip it seems:

https://pypi.org/project/cryptography/#history

**Comment by tiran** [comment]
No, the version is correct. Please read the [changelog](https://cryptography.io/en/latest/changelog/)

> Changed the version scheme. This will result in us incrementing the major version more frequently, but does not change our existing backwards compatibility policy.

**Comment by reaperhulk** [comment]
As @tiran noted, this is not a mistake, as the changelog notes. We changed our versioning for this release and will be using Firefox style versioning going forward.

**Comment by pierresouchay** [comment]
Just for my culture, why starting at 35.x and not 4.x?

**Comment by alex** [comment]
To make it clear we're changing our versioning scheme.
