### ISSUE TITLE
How to install cryptography from wheel on armv7l

### ISSUE THREAD

**Issue by cuu508** [pyca/cryptography#6342]
Is it possible to install cryptography on ARM system from wheel?

My hardware is Raspberry Pi 400, and I'm running my experiments from inside Docker:

```
docker run -it python:3.9-slim-buster bash
```

Software versions:

```
root@3d5804a8efb0:/tmp# uname -a
Linux 3d5804a8efb0 5.10.60-v7l+ #1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
root@3d5804a8efb0:/tmp# python --version
Python 3.9.7
root@3d5804a8efb0:/tmp# pip --version
pip 21.2.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

If I just run `pip install cryptography` it tries to build cryptography from source. Installation fails because rust is missing. I installed rust:

```
apt-get install build-essential libssl-dev libffi-dev python3-dev cargo
```

After this, `pip install cryptography` takes a long time but eventually completes with no errors. 

The rust requirement and the long build time could be avoided by using binary wheel. Does cryptography have a wheel that would work on armv7l, Linux and python 3.9? If yes, how can I make pip use it? Thanks in advance!

**Comment by alex** [comment]
We do not produce wheels for 32bit arm, only arm64.

בתאריך יום ה׳, 30 בספט׳ 2021, 10:04, מאת Pēteris Caune ‏<
***@***.***>:

**Comment by cuu508** [comment]
Thanks, OK, so there's no magic combination of pip options to make it work ;-)

Would you consider adding 32bit arm builds to the build system?

**Comment by tiran** [comment]
The BCM2711 in your Raspberry Pi 400 should support aarch64.

**Comment by alexdotgov** [comment]
(Comment from my work account)

We're not going to consider 32-bit ARM at the moment, no: https://github.com/pyca/cryptography/issues/6286
