### ISSUE TITLE
x509v3 Extended Key Usage

### ISSUE THREAD

**Issue by PhilippSelenium** [pyca/cryptography#6349]
python 3.8
cryptography: 35.0.0

When I execute openssl with:
```
openssl x509 -in /tmp/client.crt -noout -text
```
I get
```
...
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
...
```

Using cryptography like:
```
from cryptography import x509
with open("/tmp/client.crt", "rb") as f:
     crt = x509.load_pem_x509_certificate(f.read())
crt.extensions.get_extension_for_class(x509.ExtendedKeyUsage)
```
it gives me:
```
<Extension(oid=<ObjectIdentifier(oid=2.5.29.37, name=extendedKeyUsage)>, critical=False, value=<ExtendedKeyUsage([<ObjectIdentifier(oid=1.3.6.1.5.5.7.3.2, name=clientAuth)>])>)>
```

Why is the string ' TLS Web Client Authentication' missing in cryptography?

**Comment by reaperhulk** [comment]
That string is just a long name picked by OpenSSL for presentation purposes that isn't present in the actual serialized code. The OID 1.3.6.1.5.5.7.3.2 represents client authentication and has a canonical short name of "clientAuth". RFC 5280 also calls this "TLS WWW Client Authentication". Any programmatic comparison or checks should be made via the OID and not a string.

**Comment by tiran** [comment]
The value is there. OID ``1.3.6.1.5.5.7.3.2`` is TLS web client authentication. OpenSSL uses a different textual representation.

**Comment by PhilippSelenium** [comment]
Thanks for the fast reply and clarification.
But when id do:
```
crt.extensions.get_extension_for_oid(x509.ExtendedKeyUsageOID.CLIENT_AUTH.dotted_string)
```
I get:
ExtensionNotFound: No 1.3.6.1.5.5.7.3.2 extension was found

**Comment by tiran** [comment]
``get_extension_for_oid`` takes an ObjectIdentifier instance, not a str instance. Please try ``crt.extensions.get_extension_for_oid(x509.ExtendedKeyUsageOID.CLIENT_AUTH)``

**Comment by PhilippSelenium** [comment]
I tried that one before and it also threw the same error.

**Comment by tiran** [comment]
Sorry, I gave you the wrong instruction. You have to fetch EKU extension first, then check if EKU contains the desired OID:

```
eku = crt.extensions.get_extension_for_class(x509.ExtendedKeyUsage)
x509.ExtendedKeyUsageOID.CLIENT_AUTH in eku.value
```

**Comment by PhilippSelenium** [comment]
Thanks a lot!
