### ISSUE TITLE
Issue with PEM x509 cert loading in v35.0.0

### ISSUE THREAD

**Issue by PawelPeczek** [pyca/cryptography#6366]
Hi, 
I've encountered the following issue after migration from `v3.4.8` into `v35.0.0`:

`v3.4.8`:
```python
from cryptography import x509

with open("cert.pem", "rb") as f:
    cert_content = f.read()

cert = x509.load_pem_x509_certificate(cert_content)
```

`v35.0.0`:
```python
from cryptography import x509

with open("cert.pem", "rb") as f:
    cert_content = f.read()

cert = x509.load_pem_x509_certificate(cert_content)

Exception:
ValueError: Valid PEM but no BEGIN CERTIFICATE/END CERTIFICATE delimiters. Are you sure this is a certificate?
```

The certificate format seems to be valid:
```
-----BEGIN PRIVATE KEY-----
XXX
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
YYY
-----END CERTIFICATE-----
```

Just to be clear, I do expect that it may be a problem with my local setup and I do not expect community to solve all of my problems. There is also a chance that the change was intentional and I just missed something. But if that is actual bug, I wish to notify it.

Regards.

**Comment by PawelPeczek** [comment]
ok, I just found this in changelog:

```
BACKWARDS INCOMPATIBLE: The :doc:`/x509/index` PEM parsers now require that the PEM string passed have PEM delimiters of the correct type. For example, parsing a private key PEM concatenated with a certificate PEM will no longer be accepted by the PEM certificate parser.
```

**Comment by reaperhulk** [comment]
Despite the docs, we actually have decided to change this behavior to match previous expectations in this case (concatenated key and cert). That change was landed as https://github.com/pyca/cryptography/pull/6365 and will be in the next release.
