### ISSUE TITLE
/var/task/cryptography/hazmat/bindings/_openssl.abi3.so: invalid ELF header

### ISSUE THREAD

**Issue by Tom3652** [pyca/cryptography#6372]
Hello !

I am having a similar issue to #3051. 
I am deploying the following code in an AWS Lambda function (on my Mac everything works perfectly) : 

```
def check_token(token):
    try:
        n_decoded = jwt.get_unverified_header(token)
        kid_claim = n_decoded["kid"]
        response = requests.get(google_token_endpoint)
        x509_key = response.json()[kid_claim]
        key = x509.load_pem_x509_certificate(x509_key.encode('utf-8'),  backend=default_backend())
        public_key = key.public_key()
        decoded_token = jwt.decode(token, public_key, [algorithm], options=None, audience=audience)
        print(f"Decoded token : {decoded_token}")
        if decoded_token:
            return True
        return False
    except Exception as e:
        print(f"Exception while decoding token : {e}")
        return False
```

The code has some hidden variables : 
```
google_token_endpoint = "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com"
audience="myfirebase-project-ID"
token=""  # TODO : any valid token in request headers.
```

I am getting this error in my ```except``` clause : 

```
Exception while decoding token : /var/task/cryptography/hazmat/bindings/_openssl.abi3.so: invalid ELF header
```

I am using ```python 3.9```.
I have the followings versions : 

```
cryptography version : 3.4.7
cffi version : 1.14.6
pip version : 21.2.4
setuptools version : 58.0.4
```

And i have installed ```cryptography``` with : ```pip install --target ./mydir cryptography```

Should I also build under a linux host ? If yes, does it mean only install cryptography with pip under a Linux EC2 and make the zip file there ? I don't want to use containers for my lambdas.

Thanks in advance

**Comment by alex** [comment]
Yes, you must build packages for lambda on machines with the same architecture, which means x86-64 linux. You cannot build for lambda from a mac.
