### ISSUE TITLE
Add FAQ entry how to download and provide AWS Lambda bundle

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#6391]
In regular intervals users open issues because they are struggling AWS Lambda. Lambda requires a specific type of binary extensions that works on X86_64 platforms with old glib. Recent versions of pip have a way to download and unpack the correct files into a target directory. I propose to include a FAQ entry

## optionally: create virtual env and install latest pip
```
$ python3 -m venv venv
$ venv/bin/pip install -U pip setuptools
$ . venv/bin/activate
```

## download cryptography and dependencies

```
$ pip install \
    --platform manylinux2010_x86_64 \
    --implementation cp \
    --python 3.9 \
    --only-binary=:all: --upgrade \
    --target awsbundle \
    cryptography
```

This will download and unpack cryptography and all its dependencies for Python 3.9 into the ``awsbundle`` directory:

```
$ ls awsbundle/
cffi
cffi-1.14.6.dist-info
_cffi_backend.cpython-36m-x86_64-linux-gnu.so
cffi.libs
cryptography
cryptography-35.0.0.dist-info
pycparser
pycparser-2.20.dist-info
$ find awsbundle/ -name '*.so' 
awsbundle/_cffi_backend.cpython-36m-x86_64-linux-gnu.so
awsbundle/cryptography/hazmat/bindings/_openssl.abi3.so
awsbundle/cryptography/hazmat/bindings/_rust.abi3.so
```

**Comment by tiran** [comment]
@davdunc David, could you forward this FAQ to the docs team at AWS? Thanks!

**Comment by zhaowb** [comment]
Just to mention the error message from AWS Lambda function, to help people to see this page faster (because it took me hours to find solutions).

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'main': /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)
Traceback (most recent call last):
```

For people using pipenv, you might need to use this method (in top post) to replace what pipenv installed.
I failed to find a way to do the same thing in pipenv.

**Comment by wangsha** [comment]
for pipenv
```bash
pipenv run pip install \                                                                                             
    --platform manylinux2010_x86_64 \
    --target=~/.local/share/virtualenvs/your_pipenv_dir/lib/python3.9/site-packages \
    --implementation cp \
    --python 3.9 \
    --only-binary=:all: --upgrade \
    cryptography
```

**Comment by reaperhulk** [comment]
A note for people finding this after cryptography 38.0.0 is released: We no longer ship manylinux2010 wheels. You will instead need to target `manylinux2014` or `manylinux_2_17` at minimum (the latter is an alias for the former).
