### ISSUE TITLE
missing exception in cryptography.exceptions.InvalidToken

### ISSUE THREAD

**Issue by ttyhpy** [pyca/cryptography#6405]
I would like to react on the error if the cipher-key with which a text was encrypted exists in the same place but the content was exchanged because someone exchanged this key by mistake or on purpose.

in the backward function decrypt(encryptedtxt) an exception occurs.

in this case from my point of view first the error 'InvalidSignature' is raised.
is triggered first, but during error handling the error 'InvalidToken' is also triggered.
but i can't find it in the list of treatable errors from cryptography.exceptions.
the only thing left is to do a general handling in 'try... except Exception', which again needs an 'interpretation' of this exception to exclude other errors.

So my question is if this behavior is intended or if it is a bug.

If it also seems to be programmed clumsy in the example ... I would be glad about a feedback

>Versions
>python                    3.8.12          h7840368_1_cpython    conda-forge
>cryptography              3.4.7            py38hd7da0ea_0    conda-forge
[test_cryptography_exception-InvalidToken.txt](https://github.com/pyca/cryptography/files/7324846/test_cryptography_exception-InvalidToken.txt)
[test_cryptography_exception-InvalidToken_Traceback.txt](https://github.com/pyca/cryptography/files/7324848/test_cryptography_exception-InvalidToken_Traceback.txt)

**Comment by alex** [comment]
That's because `InvalidToken` lives in the `fernet` module: `from cryptography.fernet import InvalidToken`.

**Comment by reaperhulk** [comment]
(Documented here: https://cryptography.io/en/latest/fernet/#cryptography.fernet.InvalidToken)

**Comment by ttyhpy** [comment]
hellex and reaperhulk, 

thanks for the help in reading the full docs on cryptography.fernet.Fernet.decrypt(...) before i use it.
and sorry for the bumps on the head, which you surely got when the head hit the tabletop several times.
