### ISSUE TITLE
Release a new version with Python 3.10 support

### ISSUE THREAD

**Issue by xyb** [pyca/cryptography#6414]
I know that Cryptography just released https://github.com/pyca/cryptography/milestone/37 15 days ago, but it would be great if we could release a new version with Python 3.10 support for those who rely on this package soon. Thanks!

**Comment by reaperhulk** [comment]
The 35.0 release works fine with Python 3.10 and all our wheels will auto-install under 3.10 as well (see: https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version)
