### ISSUE TITLE
I have got the public key from the server. How can I use cryptography for RSA encryption？

### ISSUE THREAD

**Issue by RayEu** [pyca/cryptography#6416]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by RayEu** [comment]
> https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#encryption

I've seen this, but the public key in the document is generated by the private key. 
like this,  public_key = private_key.public_key()

How can I set the existing public key？

**Comment by RayEu** [comment]
just like JS:
var b=new JSEncrypt
b.setPublicKey(decodeURIComponent(window.pubKey))
b.encrypt(e.join(","))

now, I have got the public key from the server.  
like "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqG........gQIDAQAB\n-----END PUBLIC KEY-----\n"

so how can i set public key, like js   'b.setPublicKey(pubkey)'

**Comment by reaperhulk** [comment]
We have load functions for public keys. Please read the documentation.
