### ISSUE TITLE
Getting cert's subject name hash

### ISSUE THREAD

**Issue by dirkfeytons** [pyca/cryptography#6456]
I'm updating a codebase from pyOpenssl to cryptography 35.0 but hit the problem that I need the (OpenSSL-specific) hash of a cert's subject name to be able to save the cert on the filesystem with that special `<hash>.0` name for OpenSSL's lookup purposes.

I found that this was discussed back in 2017 in #3886 but the workaround given there doesn't seem to work for me.
Since there have been some changes in the way backends are used I updated that code to (assuming `cert` is a cryptography cert acquired via `x509.load_pem_x509_certificate(cert_data)`):
```python
backend = default_backend()
hash = backend._lib.X509_NAME_hash(backend._lib.X509_get_subject_name(cert._x509))
```

First of all, this triggers the warning message `CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.` of which I'm not really sure what it means. Even after updating pyOpenSSL to 21.0.0 this warning remains.

Second, and most important, the value returned by the code above doesn't match the value returned by pyOpenSSL or OpenSSL CLI.

Any advise would be appreciated.

**Comment by reaperhulk** [comment]
Hmm, that's unfortunate. OpenSSL specific behavior isn't really something we want in our standard APIs, but it sounds like your ideal would be something like `sha1(openssl_normalize(cert.subject.public_bytes()))`.

Separately, can you provide a reproducer that raises that deprecation warning with the latest pyopenssl and latest cryptography? There shouldn't be any paths like that in pyOpenSSL 21.0 so if you're still seeing that we may have missed something.

**Comment by reaperhulk** [comment]
You're seeing the warning because you're calling `cert._x509`, which we now only provide as a fallback for old versions of pyOpenSSL.

I think this is probably a valid use case for using pyOpenSSL's cert handling, as it does have `X509.subject_name_hash()` for this. You can use `X509.from_cryptography_cert` to convert in the latest pyOpenSSL without triggering the deprecation warning.
