### ISSUE TITLE
Support SSH certificates

### ISSUE THREAD

**Issue by mjpieters** [pyca/cryptography#6458]
Please add support for exposing all information contained in [SSH certificates](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.certkeys), as well as generating new keys.

Currently, the [SSL public key loader](https://github.com/pyca/cryptography/blob/f0b2269f7221f06aacf883b58577ffc9627e7522/src/cryptography/hazmat/primitives/serialization/ssh.py#L648-L690) does load, but then _discard_ certificate information.

Can that information please be made available? Ideally, if you have the private key that was used to sign the public key, the ability to verify the signature would be invaluable.

And going in the other  direction, please add support for *generating* such keys. That would require that you can create a SSH certificate object on which you can set a serial (arbitrary uint64), type (user or host), key id, principals, valid dates, critical options and extensions. Signing then only has to generate a nonce and signature to write back to disk.

**Comment by MarkusTeufelberger** [comment]
Golang has a nice implementation too by the way, in case you don't want to read OpenSSH code: https://pkg.go.dev/golang.org/x/crypto/ssh#Certificate

**Comment by reaperhulk** [comment]
Tracking:

- [ ] Vectors (#7984)
- [ ] Parser
- [ ] Builder
- [ ] Deprecate DSA in existing code

There will also be some refactor PRs as we go, including #7982 and #7983.

**Comment by reaperhulk** [comment]
And we're done 😄
