### ISSUE TITLE
Unknown OpenSSL error

### ISSUE THREAD

**Issue by hinst** [pyca/cryptography#6482]
Good day

I am getting an error from `cryptography` when I try to run my Python app:

> cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126615813, lib=15, reason=786693, reason_text=b'error:078C0105:common libcrypto routines::init fail')])

* OS: Windows 10
* Python version: 3.8
* How I installed `cryptography`:
   * Running command `pip install -r requirements.txt`
   * I have no way of knowing the version of the `cryptography` package because it is not on the list in `requirements.txt`
* The app crashes immediately at the start

If none of that works, please make sure to include the following information in
your bug report:

**Comment by alex** [comment]
No answer for a week, closing.
