### ISSUE TITLE
More explicitly document backend deprecation

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#6499]
We have previously made it so `backend` isn't a required argument, but we've referred to them as `optional`. We should update our docs to note that backends are not only not required, they're not recommended. Since a huge number of callers pass backends these functions will all continue to take the argument for the foreseeable future (many years!), but it's probably time to officially deprecate `backend`.

As part of this do we also want to remove the backend section of our docs?

**Comment by alex** [comment]
I'd go so far as to say we should delete the docs for them!

**Comment by reaperhulk** [comment]
I think we can call this complete for the moment. At some point we'll want to revisit the entire way we parametrize over backend in the tests but I don't have the ambition for it at the moment.
