### ISSUE TITLE
Question About Nonces

### ISSUE THREAD

**Issue by ArchGryphon9362** [pyca/cryptography#6543]
Since when must a nonce be 8 bytes in length minimum, I used to always use it with 4 bytes but after a Windows reinstall I had to reinstall python (and there for had to update all my pip libraries), and in the new version it seems that I can't use for bytes. I found nothing talking about this in the docs, and here's the piece of code reponsible for it: [cryptography.hazmat.primitives.ciphers.aead](https://github.com/pyca/cryptography/blob/7a2823bdffbaa60262a377ebcd2cd1bc63f4b773/src/cryptography/hazmat/primitives/ciphers/aead.py#L216)

Idk if this is a bug or not but it's definitely bothering me. (I'm using AESGCM by the way!)

Thanks in advance for any help!

**Comment by alex** [comment]
It's been enforced since the 3.3 release (https://github.com/pyca/cryptography/commit/b59d2de9cf0dcf5c36d37007b6e756f18e9b0160). A 4-byte nonce is very dangerous because at that size the liklihood of nonce reuse (which is catastrophc with GCM) is quite significant.

**Comment by ArchGryphon9362** [comment]
Ah ye, well that's a bit disappointing because I'm using a service that I have no control over and has actually mostly been reverse engineered...

**Comment by reaperhulk** [comment]
OpenSSL itself is rejecting nonces under 8 bytes as of 3.0 so even if we wanted to allow this (which we don’t for the reasons Alex has noted) it is impossible under one of our supported configurations. If you have a hard requirement patching this check out yourself is quite simple, but be aware that this will stop working forever when your Linux distribution upgrades to 3.0. And that’s only if you build your own cryptography. cryptography will itself be shipping wheels with 3.0 in the next few releases.

**Comment by ArchGryphon9362** [comment]
Oh! Sadly that is out of my control, but thanks for letting me know, I'll see if there is any way I can use 8 bytes, but thanks for letting me know!

**Comment by ArchGryphon9362** [comment]
Hey, one last question. I saw that changing the size of the nonce byte array changed the output (despite no data changing anywhere else). Does this mean that the nonce byte array must be agreed upon before communication, or is it somehow transported in something like the tag?

**Comment by ArchGryphon9362** [comment]
Like the protocol I'm using includes the nonce during the communication, but only as an integer of the counter, after which you're meant to generate a 4 long byte array so that I essentially get that same number in the 4 byte array in big endian layout.
