### ISSUE TITLE
Version 35.0.0 after version 3.4.8? Or should it read 3.5.0?

### ISSUE THREAD

**Issue by Harm10** [pyca/cryptography#6548]
I am trying to install rpaframework on python 3.8.3 on Windows. Its dependencies state: cryptography<4.0.0,>=3.3.1
But there are no wheels available for 3.8.
And are you sure the latest version is 35.0.0 and not 3.5.0?
BTW version 35.0.0 also does not have a wheel for 3.8

**Comment by tiran** [comment]
https://cryptography.io/en/latest/api-stability/#versioning

https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version

**Comment by Harm10** [comment]
The list on page https://pypi.org/project/cryptography/35.0.0/#files still lists Python versions and 3.8 is not there. So what file should I use? Or should the makers of rpaframework correct their dependencies?

**Comment by Harm10** [comment]
@alex @tiran Isn't this issue closed too soon? I still have a question about the list on pypi.

**Comment by Harm10** [comment]
I am glad to report that using cryptography-3.4.8-cp36-abi3-win32.whl worked on python 3.8.3 with rpaframework 10.9.3 installation.
Before this issue I had never heard of abi3 wheels so I think it is a good follow-up to improve the release documentation.
So apparently pip version 21.2.2 is recent enough............
