### ISSUE TITLE
Missing wheel for Macos 11 (x86_64)

### ISSUE THREAD

**Issue by Leletir** [pyca/cryptography#6549]
Hello,

Thank you for your library !
I'm trying to install cryptography 35.0.0 on Macos 11 (x86_64), but only the wheel fo Macos 10 on x86_64 is available. Furthermore the wheel available for Macos 11 is only for ARM.
Can you please release a wheel for Macos 11 on x86_64 ?

* Python: 3.9.2
*  cryptography: 35.0.0
*  cffi: 1.15.0
*  pip: 20.2.3
*  setuptools: 49.2.1
* How you installed ``cryptography``: pip install cryptography
* Clear steps for reproducing your bug.

```bash
pip install cryptography==0.35.0
```
The build failed because I don't have access to crates.io (RIP rust on corporate network ...)

Have a good day.

**Comment by tiran** [comment]
Please update your pip to a more recent version and try again.

**Comment by Leletir** [comment]
Ok I'm sorry, it works with pip 21.3.1
