### ISSUE TITLE
OpenSSL 3.0.0 support / 3.3.x

### ISSUE THREAD

**Issue by jbleyel** [pyca/cryptography#6556]
Could you please add OpenSSL 3.0.0 support to 3.3.x
like this -> https://github.com/pyca/cryptography/pull/6000
Or is this not possible?

Thanks

**Comment by reaperhulk** [comment]
We do not backport features to older versions, sorry. If you want OpenSSL 3.0 support you'll need to upgrade to 35.0, use a distro that has chosen to do this work (the author of #6000 is an employee of Red Hat), or apply/create patches yourself.
