### ISSUE TITLE
`---BEGIN NEW CERTIFICATE REQUEST---` not recognized properly in rust_x509

### ISSUE THREAD

**Issue by 65a** [pyca/cryptography#6557]
https://github.com/pyca/cryptography/blob/bb05d4b5e69b1ad5fe2c902888e362933b8f0b88/src/rust/src/x509/csr.rs#L295

Running Fedora rawhide, latest version. I assume this is close enough to HEAD. Feel free to close if you have working tests for both cases, or I'm missing something here. Hacking python side to swap 'NEW CERTIFICATE REQUEST' to 'CERTIFICATE REQUEST' does not result in the error being returned, which appears to indicate a correctness problem in this code.

**Comment by reaperhulk** [comment]
It is not close enough to main, no (https://github.com/pyca/cryptography/blob/c7fbef767a94ee1569ae0630006fdb144d6a4e8d/src/rust/src/x509.rs#L674 is how it worked in 35.0). This has been fixed and will be in the next release.

**Comment by 65a** [comment]
Thanks
