### ISSUE TITLE
Missing empty SET OF in CSR with no extensions or attributes

### ISSUE THREAD

**Issue by m-pilia** [pyca/cryptography#6601]
Hi! When using `CertificateSigningRequestBuilder` without adding any extensions or attributes, the resulting CSR seems to not have an empty SET OF (Attributes is not equal to a0:00).

The following is a MWE of the issue:
```python
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import hashes

key = ec.generate_private_key(ec.SECP256R1(), default_backend())

csr = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([
    x509.NameAttribute(NameOID.COUNTRY_NAME, "DE"),
    x509.NameAttribute(NameOID.COMMON_NAME, "foobar"),
])).sign(key, hashes.SHA256())

with open("csr.pem", "wb") as f:
    f.write(csr.public_bytes(serialization.Encoding.PEM))
```

Then if I run `openssl req -in csr.pem -text -noout` I get:
```
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = DE, CN = foobar
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    <omissis>
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        Attributes:
        Requested Extensions:
    Signature Algorithm: ecdsa-with-SHA256
         <omissis>
```

By contrast, if I generate a CSR using OpenSSL from the command line:
```
openssl req -newkey ec:<(openssl genpkey -genparam -algorithm ec -pkeyopt ec_paramgen_curve:P-256) -subj "/C=DE/CN=foobar" -keyout private.key -out csr.pem
```
the resulting CSR shows `a0:00` in the `Attributes` and no `Extensions`, as I would expect:
```
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: C = DE, CN = foobar
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    <omissis>
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        Attributes:
            a0:00
    Signature Algorithm: ecdsa-with-SHA256
         <omissis>
```

### Additional info
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools`` you're using:
```
$ python --version
Python 3.9.7

$ pip list | grep cryptography
cryptography   35.0.0

$ pip list | grep setuptools  
setuptools     57.4.0

$ openssl version  
OpenSSL 1.1.1l  24 Aug 2021
```
* How you installed ``cryptography``:
```
python -m venv .venv
. .venv/bin/activate
pip install cryptography
```

**Comment by reaperhulk** [comment]
Thanks for the report. This behavior has actually been true for many years (I tested back to 2.2 out of curiosity). It would appear something about the way in which we were using the OpenSSL APIs left it out entirely when no extensions/attributes were encoded. However, we no longer use OpenSSL to generate this structure in `main` so in the next release we'll be encoding the empty set as expected.

**Comment by reaperhulk** [comment]
Just to close this out, the actual exact thing occurring here is that we're encoding an empty extensions attribute. This is valid, but also surprising. The behavior changes to empty set in the next release (36.0).

**Comment by m-pilia** [comment]
Great, thanks!
