### ISSUE TITLE
Wheels for CPython versions >3.6

### ISSUE THREAD

**Issue by AntonKueltz** [pyca/cryptography#6618]
Hi all,

I've noticed that the latest release (35.0.0) from SEP2021 still only provides wheels for version 3.6 of CPython [[src](https://pypi.org/project/cryptography/35.0.0/#files)]. Given that python3.6 is EOL in DEC2021 [[src](https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule)] is there a reason that only version 3.6 wheels are supported for the most popular implementation of python (I do see that pypy3.7 is supported)? I understand that newer versions of CPython can build the package from source, but it would be nice to see all currently supported versions of CPython get wheel support as well.

Thanks,
Anton

**Comment by reaperhulk** [comment]
https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version

**Comment by AntonKueltz** [comment]
Thanks, it seems the issues I'm seeing stem from an old pip version then which doesn't understand or respect abi3 wheels.
