### ISSUE TITLE
Extract data from PKCS7

### ISSUE THREAD

**Issue by zspasztori** [pyca/cryptography#6651]
Currently the PKCS7 pem and der loading functions only return the certificate inside the object. 
Are you planning to add support for extracting the data also?

The SignitureBuilder already support inserting data.

**Comment by reaperhulk** [comment]
Is the request here to be able to return attached data that the SignatureBuilder encodes? I don't really want to return that without verification, which is a challenge for the reasons mentioned in https://github.com/pyca/cryptography/issues/5471#issuecomment-981159469
