### ISSUE TITLE
Link against OpenSSL 3

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#6681]
It's probably around time to do this. Sticking in the 37 milestone, although we may choose to bump to 38.

**Comment by alex** [comment]
Note that rust-openssl just reverted their bump to OpenSSL 3 due to performance issues: https://github.com/sfackler/rust-openssl/issues/1576#issuecomment-991821307

**Comment by reaperhulk** [comment]
Alex and I agreed we're going to do this for the 37.0 release. https://github.com/pyca/infra/pull/397 is the related infra PR (which we won't merge until we're close to release)
