### ISSUE TITLE
Building cryptography for an embedded system on Yocto: can I run CFFI at build time?

### ISSUE THREAD

**Issue by AirborneLizard** [pyca/cryptography#6689]
I'm having a bit of a problem building  ``cryptography`` for an embedded system on Yocto. This might be related to #1325. My motivation is to build Paramiko. 

* ``Python``: 2.7
*  ``cryptography``: 36.0.0
*  ``cffi``: 1.15.0
*  ``paramiko``: 2.8.1

Problem description: Yocto insists on cross compiling the whole of GCC as a dependency., even though my pycparser RDEPENDS is only for the C preprocessor. I've verified by trial and error that the C preprocessor is the only dependency that's necessary. 

It seems to me that this is a layered problem involving my bitbake recipes and CFFI as well as cryptography. One solution, as discussed in #1325, would be to use CFFI at build time rather than on the target. 

Is there any way of doing this?

**Comment by alex** [comment]
cffi has two components, one is the part that generates C code for an extension module -- this is only required at build time. the other part is `_cffi_backend` which is required at runtime.

The issue you linked is extremely out of date, and as far as I know cross-compilation should work fine these days.
