### ISSUE TITLE
McAfee detects rust.pyd as a (probably) false positive in version 36.0.0

### ISSUE THREAD

**Issue by studioj** [pyca/cryptography#6697]
McAfee Agent (version 5.7.4.399) reports rust.pyd as a Trojan during installation of version 36.0.0 and it gets removed.

Our IT department will file a false positive investigation with McAfee

![image](https://user-images.githubusercontent.com/22102283/145786636-b3368b10-e511-4bb2-b63b-a6d326cead42.png)

reporting this here so it can serve as a help for people looking for the same problem ... Once its confirmed by McAfee i suggest closing the ticket.

for now a fallback

> pip install cryptography==35.0.0

**Comment by reaperhulk** [comment]
Thanks for letting us know. AV products providing positive value as per usual. 😂

**Comment by studioj** [comment]
more than one positive hit btw
https://www.virustotal.com/gui/file/b8c9e126d5c6e2d1ec03b127992c6370bbb86ccff2ad1e8bd787a34d328d5c0a

**Comment by Tarnum-tst** [comment]
That's the main reason why I always compiling cryptography myself. My builds are not universal, currently I produce two different builds for Python 3.7.9 and Python 3.8.10, here is the one for 3.8.10: https://www.virustotal.com/gui/file/6c862d744aaab2f4531f62161273fa88fd61036361596a309b5eafea261c0ac4
