### ISSUE TITLE
undefined symbol: EC_POINT_get_affine_coordinates_GF2m, version OPENSSL_1_1_0

### ISSUE THREAD

**Issue by jinxudb** [pyca/cryptography#6712]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
Python: 3.7, 
cryptograhy : 36.0.0

* How you installed ``cryptography``
from conda
* Clear steps for reproducing your bug

OS:  Redhat Enterprise 8

In our production,  we use cryptography 36.0.0 with Openssl version 1.1.1L from 24 Aug 2021 without any issue.
In our test envrionment,  same cryptograhy verion 36.0.0, but use Opensll version 3.0.0 from 07 Sep 2021,  we saw this error 

`  File "/app/conda/envs/test/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>`
`      from cryptography.hazmat.backends.openssl.backend import backend`
`  File "/app/conda/envs/test/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 64, in <module>`
`      from cryptography.hazmat.bindings.openssl import binding`
`  File "/app/conda/envs/test/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>`
`      from cryptography.hazmat.bindings._openssl import ffi, lib`
`ImportError: /app/conda/envs/test/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: EC_POINT_get_affine_coordinates_GF2m, version OPENSSL_1_1_0`

Do I have to downgrade the openssl version of 1.1.1?  

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by alex** [comment]
Is there any chance you are compiling and linking against different
versions of OpenSSL?

בתאריך יום ה׳, 16 בדצמ׳ 2021, 9:42, מאת jinxudb ***@***.***>:

**Comment by jinxudb** [comment]
I am not sure,  because we use conda to manage our environments, I can see the openssl v3.0.0 was updated when I exeucte `conda update conda` now,  previously  openssl only updated to v1.1.1L,  
![image](https://user-images.githubusercontent.com/69906980/146553315-3c84ea2f-ff12-411b-b358-e5a2f1c677e5.png)

**Comment by alex** [comment]
Can you provide instructions to reproduce this on a fresh machine?

בתאריך יום ו׳, 17 בדצמ׳ 2021, 8:43, מאת jinxudb ***@***.***>:

**Comment by jinxudb** [comment]
I can paste my docker file here, but I am in an enterprise environment,  I am not allowed to use the image and package in public repo...  

dockerfile: 
> FROM _somerepo_/rhel8/rhel:latest
> SHELL ["/bin/bash", "-c"]
> 
> RUN yum install wget bzip2 git strace lsof libnsl -y
> WORKDIR /app/api/
> COPY .condarc /app/api/
> ENV HOME="/app/api/"
> ENV USERPROFILE="/app/api/"
> RUN wget -q  _could download from conda_/Miniconda3-py37_4.8.2-Linux-x86_64.sh -O /tmp/conda.sh
> 
> RUN chmod +x /tmp/conda.sh         && \
>     /tmp/conda.sh -b -p /app/conda && \
>     rm /tmp/conda.sh
> 
> ENV PATH="/app/conda/bin:${PATH}"
> RUN conda update conda -y
> RUN conda init bash
> RUN conda clean --all -y -q


If I run python in the container and try to import, 

> (base) bash-4.4# python
> Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> \>\>\> from cryptography.hazmat.bindings._openssl import ffi, lib
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: /app/conda/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: EC_POINT_get_affine_coordinates_GF2m, version OPENSSL_1_1_0

**Comment by tiran** [comment]
Could you please provide the output of ``ldd /app/conda/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so``?

**Comment by jinxudb** [comment]
> (base) bash-4.4# ldd /app/conda/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so
        linux-vdso.so.1 (0x00007fff1fb6d000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f651f90c000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f651f426000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f651f206000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f651ee41000)
        libz.so.1 => /app/conda/lib/python3.7/site-packages/cryptography/hazmat/bindings/../../../../../libz.so.1 (0x00007f651fd16000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f651ec3d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f651fba0000)

**Comment by tiran** [comment]
I assume that you are using RHEL 8.5 or 8.4. RHEL's OpenSSL is build with ``no-ec2m`` config flag. The option disables support for binary field elliptic curves. For various reasons only NIST curves are supported on RHEL. Somehow you ended up with a cryptography build with binary field EC. Are the binaries coming from Conda?

```
# rpm -qa openssl-libs
openssl-libs-1.1.1k-4.el8.x86_64
# readelf --dyn-syms /lib64/libcrypto.so.1.1 | grep EC_POINT_get
  3212: 000000000010c630   139 FUNC    GLOBAL DEFAULT   13 EC_POINT_get_Jprojective_@@OPENSSL_1_1_0
  3431: 000000000010ca90     9 FUNC    GLOBAL DEFAULT   13 EC_POINT_get_affine_coord@@OPENSSL_1_1_0
  3637: 000000000010c980   262 FUNC    GLOBAL DEFAULT   13 EC_POINT_get_affine_coord@@OPENSSL_1_1_1
```

**Comment by jinxudb** [comment]
we are using RHEL 8.3

> (base) bash-4.4# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 (Ootpa)
(base) bash-4.4# rpm -qa openssl-libs
openssl-libs-1.1.1g-12.el8_3.x86_64

You can see my docker file,  
The binaries are from "conda update conda -y", which will update conda to the lastest 4.11 version.  
If I force to update conda to 4.10 version in the dockerfile,  I don't have this issue.

**Comment by tiran** [comment]
It looks like the Conda binaries are not compatible with RHEL 8. I suggest that you report the issue to Conda and ask them to address the issue on their side. They need to provide binaries that can handle ``OPENSSL_NO_EC2M`` and other build options correctly.

**Comment by tomato42** [comment]
Red Hat only supports running software built on RHEL:
https://access.redhat.com/articles/rhel8-abi-compatibility

> ## Guidelines for Preserving Binary Compatibility
> 3. An application is only guaranteed to run correctly if it executes in an environment that is as new as the environment it was built in or newer. For example compiling your application on Red Hat Enterprise Linux 8.0 means your application is only guaranteed to run correctly on Red Hat Enterprise Linux 8.0 or later depending on the compatibility level of the components you depend upon.

**Comment by jinxudb** [comment]
but it doesn't explain why it works well in our PROD,   I just checked the settings, see the screenshot below.
![image](https://user-images.githubusercontent.com/69906980/146593231-af6ac5e5-dea7-4776-96d9-f636433bddce.png)

I also managed to update to RHEL 8.5 in our TEST envrionment, still doesn't work,  the difference is openssl version. 
![image](https://user-images.githubusercontent.com/69906980/146593483-ed280e8b-92e3-4f35-8d4d-67b2a8045ace.png)

**Comment by tomato42** [comment]
OpenSSL 3.0.0 does not include OPENSSL_1_1_0 symbols

**Comment by alex** [comment]
If conda is building against one OpenSSL and then linking against a system OpenSSL, that's a conda bug, and I suggest filing it with them.

**Comment by jezdez** [comment]
Some more details about this problem in the conda-forge feedstock for the cryptography package: https://github.com/conda-forge/cryptography-feedstock/pull/80#issuecomment-1001927901

**Comment by reaperhulk** [comment]
`cryptography` does support OpenSSL 3.0.x (and we test it in CI alongside our 1.1.x builds); it, unfortunately, still seems very likely that conda is compiling against headers for one version and linking against a different one.

**Comment by jezdez** [comment]
I don't think cryptography is doing anything wrong here to be clear, just wanted to provide context that "conda - the package manager", where this ticket was opened, isn't at fault here, but the packages used.

To clarify: the default channel for conda as maintained by Anaconda Inc. contains [OpenSSL 1.1.x](https://anaconda.org/main/openssl) and the [default cryptography package is built against that version](https://github.com/AnacondaRecipes/cryptography-feedstock/blob/d93c70285082f72a55aea2c7ea23a18a835846ef/recipe/meta.yaml#L32). But the volunteer-run community project conda-forge (basically a separate channel) has upgraded to [OpenSSL 3.0.x already](https://anaconda.org/conda-forge/openssl) independent to that.

Similar to pip's extra indexes, conda allows installing from multiple "channels" and the OP of this ticket has enabled the "conda-forge" in their environment as seen in the output above, effectively getting OpenSSL 3.0.x as seen in the screenshots above:

> openssl pkgs/main: :openssl-1.1.1d-h76447_4 --> /::openssl-3.0.0-h7f98852_2

I pointed to the discussion in the feedstock of the conda-forge cryptography feedstock to point out that it's a known problem with conda-forge's cryptography package and that it hasn't actually been released with a OpenSSL 3.0.x compatible version yet, either. A work-around is specified there.

**Comment by tiran** [comment]
> But the volunteer-run community project conda-forge (basically a separate channel) has upgraded to [OpenSSL 3.0.x already](https://anaconda.org/conda-forge/openssl) independent to that.

[OT] [I recommend against](https://mail.python.org/archives/list/python-dev@python.org/thread/ATO4DM6QYZGLSGGDZ3TRN5X3QDD5OHOE/) building Python with OpenSSL 3.0 for now. CPython support for OpenSSL 3.0 is still experimental.

**Comment by reaperhulk** [comment]
Ah, thanks for the clarification @jezdez!

**Comment by alex** [comment]
Closing this, as it doesn't appear to be a bug in pyca/cryptography.
