### ISSUE TITLE
Determine how to keep CircleCI base image up-to-date

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#6767]
We now use CircleCI for arm64 linux, but we need a GHA job that files an issue whenever our base image is out of date. If CircleCI has an API for knowing latest then we can use that, otherwise we may just cron on a quarterly basis.

**Comment by alex** [comment]
https://circleci.com/docs/2.0/configuration-reference/#available-machine-images is the list of images, not sure if this is available programmatically anywhere
