### ISSUE TITLE
Fernet does not raise InvalidToken for nearly identical keys

### ISSUE THREAD

**Issue by MaxG87** [pyca/cryptography#6771]
If two keys are almost identical, `cryptography` will happily use the second key to decrypt a ciphertext that was encrypted with the first key.

My versions are as follows:
* cryptography==36.0.1
* python==3.9.7 (by Miniconda)
* pip 21.2.4 (by Miniconda)
* cffi==1.14.5

I am using `cryptography` behind my own abstraction which caused me do write some tests against my abstraction and, subsequently, against `cryptography`. I am using [Hypothesis](hypothesis.readthedocs.io/) to generate test instances which is how I found that edge case.

I reduced the problem to the following minimum working example:
```python
from cryptography.fernet import Fernet, InvalidToken

keys = [
    b"AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAA=",
    b"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQE=",
]

fernets = [Fernet(k) for k in keys]
plaintext = "0005"  # but "" and other strings work as well

while True:
    token = fernets[0].encrypt(plaintext.encode())
    try:
        decrypted = fernets[1].decrypt(token)
        decrypted.decode()
    except InvalidToken:
        pass
```

I would expect that the attempt to decrypt the token always results in `InvalidToken` being raised, making `decrypted.decode()` being unreachable. However, that exception is not raised, causing `decrypted` to be undecodable.

If I change the first letter of the second key from 'A' to 'X', the code behaves as expected - it loops infinitely.

Thank you for the great project! It really helped me.

**Comment by alex** [comment]
This is because fernet keys have two elements: an AES key used for encryption and a signing key used for authentication. In this case your "nearly identical" keys actually do have identical signing keys, which means they compute the same authentication (HMAC).

What are you actually trying to accomplish here? All fernet keys should be randomly generated, or the result of a key-derivation-function, so it should never be the same that this occurs with real keys.

**Comment by MaxG87** [comment]
I have a test to ensure that any attempt to encrypt a message with a different key raises an exception. As I said before, I use [Hypothesis](https://hypothesis.readthedocs.io/en/latest/) to generate test instances, because it allows me to focus on the logic and covers lots of nasty edge cases automatically. Below I append the example from above, rewritten as test.

I cannot just use `Fernet.get_encryption_key()` because that would lead to not reproducible tests. Thus, I had to derive the encryption keys on my own with recipes from Hypothesis.

As said before, I found this while writing tests for my own abstractions. The examples above are by no means meaningful, they are just edge cases found by my test framework. If you think this is nothing that needs fixing, lets close the bug report.

```python
import base64
from typing import Any, Callable

import pytest
from cryptography.fernet import Fernet, InvalidToken
from hypothesis import given, settings
from hypothesis import strategies as st

DRAW_TYPE = Callable[[st.SearchStrategy], Any]


@st.composite
def fernet_key(draw: DRAW_TYPE) -> bytes:
    key: bytes = draw(st.binary(min_size=32, max_size=32))
    return base64.urlsafe_b64encode(key)


@settings(max_examples=100_000)  # Set it really high to trigger bug without restart.
@given(
    keys=st.lists(fernet_key(), min_size=2, max_size=2, unique=True),
    plaintext=st.text(),
)
def test_different_keys_already_raise(keys: list[bytes], plaintext: str):
    fernets = [Fernet(k) for k in keys]
    token = fernets[0].encrypt(plaintext.encode())
    with pytest.raises(InvalidToken):
        fernets[1].decrypt(token)
```

**Comment by MaxG87** [comment]
However, now I would be very glad to know where the signature key starts, so I can generate sufficiently different keys.

**Comment by alex** [comment]
The signature key is the first 16 base64-decoded bytes of the key.

My recommendation to you would be to use a hash function to derive random-looking keys from your inputs deterministically.
