### ISSUE TITLE
DH / DHE primitives code examples in documentation inappropriate

### ISSUE THREAD

**Issue by sausix** [pyca/cryptography#6783]
The documentation handles `peer_public_key` in the DH and DHE examples as ready-to-use `DHPublicKey` objects.
Of course objects have to be serialized to bytes or at least into raw integers for transport between peers.
I'm missing that completely and don't get a solution.

`dh.py` and even the documentation only offer a bunch of **serialization to bytes**, but not any counterpart de-serialization method or example.

If someone really chooses to use DH instead of recommended ECDH, it would be practical to transport a public key as a serialized x509 certificate. That requires a DH exchange session to be built from numbers of a `primitives.asymmetric.rsa.RSAPublicKey` object. Of course this step should not be part of the example.

Thank you

**Comment by reaperhulk** [comment]
You don’t think serializing to DER and then loading via https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_der_public_key is sufficient?

**Comment by sausix** [comment]
In fact I didn't expect the well known functions like `load_der_public_key` also support/return object of type `DHPublicKey`. Thank you.
Should be at least refenced at `public_bytes` functions or at the object definitions itself: `dh.DHPublicKey`.

I still would like to know how to construct a DH session based on a `RSAPublicKey` which could be transmitted with meta data in a x509 certificate.

**Comment by reaperhulk** [comment]
What you're describing is a TLS handshake. There are many resources describing how a TLS handshake works, but at the highest level (of the ephemeral key variant) you use the certificate to authenticate the server is who you think it is, the two sides exchange ephemeral public key data, and the master secret is derived from the result of the DHE/ECDHE operation.

If you're just using this to learn then you can build a toy like this relatively easily, but TLS contains a variety of additional protections that are highly significant to the security of a system like this. You should just use TLS.

**Comment by sausix** [comment]
I'm not describing TLS. I'm still talking about DH.
You know? Two peers agree securely on a common secret key (roughly in my own words).
DH was not designed to pass some key objects within a Python script.

I've mentioned x509 because it's a standardized way to pass a public key with some meta data. And it's serializable.

Why do maintainers always prefer picking the weakest part in issue reports, ignore all other parts like `the documentation is perfect` and blame the author?
It would be great if people could answer like `No it's a bad idea because...` or `An integer would be missing...` or just ask a deeper question instead of assuming reporter is dumb and let's quickly talk about TLS.

Sorry. But I will never create any issues here again if this behaviour is standard.
