### ISSUE TITLE
AWS Lambda: cannot import name 'check_pkcs7_padding' from 'cryptography.hazmat.bindings._rust'

### ISSUE THREAD

**Issue by DLiGoodyear** [pyca/cryptography#6794]
Hi there, 

I would like to report an issue while using "cryptography-36.0.1-pp38-pypy38_pp73-manylinux_2_24_x86_64.whl" on AWS Lambda
https://files.pythonhosted.org/packages/bf/b5/54c756e7be5c004123fbc93c4abaab12ba2288a52ffc5a3489315cdb0275/cryptography-36.0.1-pp38-pypy38_pp73-manylinux_2_24_x86_64.whl
What I did is:
1) Download the wheel
2) Unpack the wheel
3) Zip the folder
4) upload to AWS Lambda layer (Runtime Python 3.8)

Run test:
#1
import cryptography => Runs fine

#2
from cryptography.fernet import Fernet
...
Response
{
  "errorMessage": "Unable to import module 'lambda_function': cannot import name 'check_pkcs7_padding' from 'cryptography.hazmat.bindings._rust' (unknown location)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

Investigation:
1) cryptography.fernet : from cryptography.hazmat.primitives import hashes, padding
2) cryptography.hazmat.primitives.padding: 
from cryptography.hazmat.bindings._rust import (
    check_ansix923_padding,
    check_pkcs7_padding,)
3) cryptography.hazmat.bindings._rust: 
   def check_pkcs7_padding(data: bytes) -> bool: ...
   def check_ansix923_padding(data: bytes) -> bool: ...

Everything seems be alright, however, why Lambda throws "unknown location" error message?

Thanks for your advice, appreciate it!

**Comment by alex** [comment]
You've selected the PyPy wheel, but you're using CPython 3.8 in lambda, you need to download the correct wheel.

**Comment by DLiGoodyear** [comment]
> You've selected the PyPy wheel, but you're using CPython 3.8 in lambda, you need to download the correct wheel.

Hi Alex, 
Appreciate your help. 
Followed your recommendation, I changed the package now using: 
- cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl
Everything worked out properly. 
Again, thanks for your advice!
Best regards,
D
