### ISSUE TITLE
Enumerate test cases for a "Wycheproof for X.509 path buliding"

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#6802]

**Comment by alex** [comment]
Here's my starting list of test cases we'll need to cover, it's definitely incomplete:

- Random self-signed cert is untrusted
- Cert issued from trusted CA is trusted
- Cert issued from untrusted CA is untrusted
- Cert issued from an intermediate of a trusted CA is trusted
- Certs issued from an issuer without basic constraints CA=TRUE are untrusted
- Certs issued deeper than basic constraints pathlen are untrusted (including using the shortest pathlen if there's a conflict between root and intermediate)
- Certs issued before not valid before are untrusted
- Certs issued after not valid after are untrusted
- Certs with keys that do not meet minimum policy requirements (e.g. RSA key size, EC curve) are untrusted
- Certs with signatures that do not meet policy requirements (e.g. MD5) are untrusted
- Certs with an unknown critical extension are untrusted
- Certs with names that do not match the provided are untrusted (TODO: enumerate all these cases)
- Certs with names that do not match name constraints in issuers are untrusted
- Certs without required EKUs, or where EKUs are not present in issuer are untrusted
- Certs without the required KU are untrusted
- Issuers without the required KU are untrusted

**Comment by reaperhulk** [comment]
https://github.com/Netflix/bettertls relevant to NC and path building

**Comment by alex** [comment]
I think the enumeration was completed here so this is no longer actionable.
