### ISSUE TITLE
Improvement: Add support for PKCS12

### ISSUE THREAD

**Issue by harmin-parra** [pyca/cryptography#6806]
Hello

I wonder, could it be possible to add support for PKCS12 ?

With methods like :

```
load
export/save

get_certificate
set_certificate
get_privatekey
set_privatekey
get_ca_certificates
set_ca_certificates
set_aliasname
get_aliasname
```

**Comment by reaperhulk** [comment]
Do you see missing features from the set provided by https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#pkcs12

**Comment by harmin-parra** [comment]
Actually the current API is fine.
It's just that I wasn't aware of the existence of the API described in the link of your comment.
I think the documentation is not very well organized, as I was unable to find that API.

Thanks
