### ISSUE TITLE
Support for RFC 6979 ("Deterministic K") in ec.ECDSA signing?

### ISSUE THREAD

**Issue by rod-chapman** [pyca/cryptography#6810]
Question: does the ec.ECDSA type support the "deterministic K" variant of ECDSA specified in RFC 6979?
If so, how do I enable that in a call to "sign"?

**Comment by alex** [comment]
We do not allow users to control `k` for ECDSA signing. `k` selection is handled by OpenSSL. It does not currently implement RFC 6979 (see https://github.com/openssl/openssl/issues/2078), but it does implement a CSPRNG failure resillient design https://github.com/openssl/openssl/commit/190c615d4398cc6c8b61eb7881d7409314529a75

**Comment by rod-chapman** [comment]
Many thanks for your swift reply.
