### ISSUE TITLE
NameOID missing required field

### ISSUE THREAD

**Issue by s2nder** [pyca/cryptography#6815]
Hello to all
I came across some a problem
I have tried create a request with some subject field and noticed, that I can't use in NameOID field calling 'NAME' with id 2.5.4.41, because it absent in a class NameIOD,  I have found closer field 'GIVEN_NAME' with id 2.5.4.42 but I can't use it. My project requires the field 'NAME'. Can someone help me with them? Can I create a custom field?

**Comment by reaperhulk** [comment]
All the attributes of `NameOID` and other enums like it are just `ObjectIdentifier` instances. Accordingly, you can just create an `ObjectIdentifier` with the value you want (e.g. `myoid = x509.ObjectIdentifier("2.5.4.41")`)

**Comment by s2nder** [comment]
Thank you very much, your answer helped me. But now I have
another question, can you please help me to change SignatureAlgorithmOID
from RSA_WITH_SHA256 to RSASSA_PSS
I have searched it on google but without success.


пн, 24 янв. 2022 г. в 17:43, Paul Kehrer ***@***.***>:

**Comment by reaperhulk** [comment]
We don't support RSA PSS certificates at this time (tracking issue is #2850 but no one has volunteered to do the work so no promises on when it might be added)
