### ISSUE TITLE
Android-Termux  Pip installing error.

### ISSUE THREAD

**Issue by metin02oktay** [pyca/cryptography#6820]
I got these outputs when I input "pip install cryptography"

![resim](https://user-images.githubusercontent.com/23521607/151402449-4ce1084d-3121-4df0-96c6-a42488929911.png)

**Comment by alex** [comment]
Did you read the error message and debug assistance? Are they unclear? Did they not solve the problem?

**Comment by metin02oktay** [comment]
I solved the problem like this: "pip install cryptography==3.1"

**Comment by alex** [comment]
That's solving the problem by getting an out of date cryptography that doesn't work with modern versions of OpenSSL, is missing features, and doesn't receive support or security updates. If that solves it for you than that's fine, but the debug assistance and error message explain how to get current versions of cryptography to work.
