### ISSUE TITLE
Whats with version bump?

### ISSUE THREAD

**Issue by oerp-odoo** [pyca/cryptography#6821]
So I see previous version was `3.4.8`, then next one became `35.0.0` and then `36.0.0`? Was this a typo and you now stuck with weird jump of a version? Or it was somehow intended?

Also its now not clear whether jump `3.4.8` -> `35.0.0` -> `36.0.0` is backwards incompatible or backwards compatible? If I would follow versions prior to `35.0.0`, I would assume `36.0.0` is not major version bump as I would translate it to `3.6.0`?..

**Comment by tiran** [comment]
It's explained in the first point of the changelog entry for 35.0.0 https://cryptography.io/en/latest/changelog/#v35-0-0

**Comment by oerp-odoo** [comment]
Oh OK, thanks.
