### ISSUE TITLE
[FR] build armv7 wheels

### ISSUE THREAD

**Issue by JuniorJPDJ** [pyca/cryptography#6829]
Hi,
ARMv7 is still being used pretty widely, we at Funkwhale and lots of other projects as [synapse](https://github.com/matrix-org/synapse/issues/9403) already had lots of trouble with building newer (rust based) versions of this package on armv7.
It would be very useful and amazing if you guys could build armv7 wheels for your library so lots of projects can move back to using latest version.
I've seen loads of version pinning to rust-less version on several websites when trying to figure out how to build our docker image.

**Comment by alex** [comment]
See https://github.com/pyca/cryptography/issues/6286

**Comment by JuniorJPDJ** [comment]
Sorry and thanks ;)
