### ISSUE TITLE
Cannot install cryptography on AIX: `rust required, but not available`

### ISSUE THREAD

**Issue by aixtools** [pyca/cryptography#6838]
- I just filed an issue with `rust-lang`: https://github.com/rust-lang/rust/issues/93618 -- `unknown OS type: AIX`
- which makes it impossible to get past this hurdle:
```
  adding license file 'LICENSE.PSF'
  running build_ext
  running build_rust

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation/ for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq/
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation/#rust

      Python: 3.9.9
      platform: AIX-1-00C291F54C00-powerpc-64bit
      pip: n/a
      setuptools: 60.7.1
      setuptools_rust: 1.1.2
      =============================DEBUG ASSISTANCE=============================

  error: can't find Rust compiler
```
- My intent is to make a wheel, but it seems this is now an impossibility because `rust-lang` does not know AIX.
- No cryptography, no _ansible-base_, no _ansible_.
- (Unhappy camper)

**Comment by alex** [comment]
You are correct that Rust does not currently support AIX.

I would strongly encourage you to complain to your OS vendor (IBM) and ask them to contribute AIX support to Rust upstream.

**Comment by aixtools** [comment]
haha. as if that will change anything in the next two years.

**Comment by aixtools** [comment]
Something a bit more _helpful_ would be to say what version can be packaged without `rust`. I am going through my notes, but I now have the feeling that this is just another OSS group that believes if you aren't Linux - you aren't.

Funny thing: GNU began because the UNIX world was too narrow minded _then_ (remember: GNU == GNU Not UNIX) It seems the cycle is back to where it started.

**Comment by alex** [comment]
3.4.0 was the first version that included Rust, and 35.0.0 was the first version that required.

We support numerous operating systems -- our CI tests aginst Linux, macOS, and Windows, and we're known to work on numerous BSDs.

**Comment by aixtools** [comment]
Thx. got 3.4.8 to build. For a long while that will be the last version available for AIX.

**Comment by aixtools** [comment]
p.s. I leave it up to you to leave this open, or not - e.g., close "won't fix".

**Comment by alex** [comment]
Okey doke. Good luck. Keep in mind 3.4.8 will not receive any security updates.

I'm closing this since there's no action we can take in the absence of someone contributing AIX support to Rust, at which point we will Just Work (tm).

**Comment by aixtools** [comment]
Open or closed - there is a reference for google to hit. And you are aware of the state of things.

Have a good day!
