### ISSUE TITLE
Can load PKCS12 with ED25519 Keys but cannot Serialize them

### ISSUE THREAD

**Issue by whiteowl3** [pyca/cryptography#6854]
Why does the pkcs12.serialize_key_and_certificates() still sanitize against ed private keys?  cryptography has no problem loading pkcs12 files which contain ed25519 private keys and related certificates.

**Comment by reaperhulk** [comment]
We should probably remove that restriction so that ed25519 and ed448 certs/keys can be serialized.

**Comment by alex** [comment]
A quick review of the OpenSSL source code suggests that this should Just Work (tm).

**Comment by whiteowl3** [comment]
confirmed that simply adding ed25519 private keys to _ALLOWED_PKCS12_TYPES produces pkcs12 files that openssl is capable of parsing to text.
i was going to do a pr but then your test coverage is unclear to me.  for example you don't appear to test for rsa pkcs12, would you want to test ed pkcs12?

**Comment by reaperhulk** [comment]
I'll get a PR up for this next week or if you'd like to contribute one that'd be great as well. Changing the type signature, the isinstance check, and adding test cases would be great.

**Comment by whiteowl3** [comment]
sorry for the trash pull. lost track of my branches for a bit.
