### ISSUE TITLE
Not support Chinese  cryptography algorithm  such as sm2,sm3,sm4 

### ISSUE THREAD

**Issue by hanzhichao** [pyca/cryptography#6857]
I know problem is openssl not support  Chinese  cryptography algorithm  such as sm2,sm3,sm4. and cant recognize the signature algorithm OID.

It's easy to realize the sm2, sm3 ,sm4 algorithm and I have done this.
But I need to write a new crypto project to realize asn1, x509 rsa ecc .

Will cryptography support Chinese  cryptography algorithm  such as sm2,sm3,sm4 in the future?
Or are there ways to solve this?

**Comment by alex** [comment]
We support both SM3 and SM4, as you can see from our docs:

- https://cryptography.io/en/latest/hazmat/primitives/cryptographic-hashes/#cryptography.hazmat.primitives.hashes.SM3
- https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.SM4

We don't have any particular plan for SM2.
