### ISSUE TITLE
3DES in FIPS is disallowed after 2023, already disabled in C9S/RHEL 9 downstream

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#6875]
[NIST SP 800-131A rev 2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf) lists 3DES encryption as disallowed and 3DES decryption as "legacy use"-only. Table 1 on page 7 (PDF page 13) differentiates between two-key and three-key TDEA and and three-key 3DES encryption has a deprecation phase until end of 2023. Table 7 on page 17 (23) lists CMAC with TDEA as disallowed after 2023, too.

C9S and RHEL 9 downstream releases ``openssl-3.0.1-5.el9`` already have 3DES disabled and marked as unapproved in FIPS mode. Cryptography has 3DES listed as always allowed in FIPS mode: https://github.com/pyca/cryptography/blob/cc80cb35d7067fa793eb37c557f312df3173f19d/src/cryptography/hazmat/backends/openssl/backend.py#L150 3DES in the FIPS allow list cause test failures.

Do you want to address the issue in upstream or would you prefer that I take care of the failing tests in C9S, RHEL 9 and Fedora downstream?

* RHBZ https://bugzilla.redhat.com/show_bug.cgi?id=2026445
* downstream patch: https://gitlab.com/redhat/centos-stream/rpms/openssl/-/blob/c9s/0045-FIPS-services-minimize.patch
* https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf

**Comment by alex** [comment]
@reaperhulk says he is in favor of this.
