### ISSUE TITLE
DSA/DSS will be disallowed in FIPS mode

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#6880]
[FIPS PUB 186-5](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf) (Draft) paragraph 4 *The Digital Signature Algorithm (DSA)* lists DSA as no longer approved. The document is still a draft and not yet final. RHEL downstream engineers do not expect any changes to DSA disapproval and blocked DSA in C9S / RHEL 9.

Like #6879 the algorithm is blocked by downstream patch https://gitlab.com/redhat/centos-stream/rpms/openssl/-/blob/c9s/0045-FIPS-services-minimize.patch . The patch causes calls to ``EVP_PKEY_get1_DSA`` to fail with error ``error:030000CD:digital envelope routines::keymgmt export failure``.

**Comment by reaperhulk** [comment]
Do we need to just skip DSA in FIPS tests and quietly wish it never existed?

**Comment by tiran** [comment]
Yes, I wish DSA never existed in the first place. (That's the typical third wish in every fairy tale. Undo all horrible events.)

* DSA key generation, signature generation, and signature verification should raise UnsupportedAlgorithm error
* DSA tests should be skipped

**Comment by reaperhulk** [comment]
Item two is the easy one, so let's do that first. Friendly errors when trying to access disallowed algorithms in FIPS is currently not something `cryptography` even tries to do, and making it work reliably across Red Hat's patches as well as the OpenSSL 3 FIPS provider is likely to be quite a bit of work. 😄

**Comment by alex** [comment]
fixed by #6916
