### ISSUE TITLE
Include openssl binding for creating a certificate from a certificate signing request.

### ISSUE THREAD

**Issue by sanchayanghosh** [pyca/cryptography#6889]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

OpenSSL has a -req switch for issuing a certificate from a certificate signing request. Here, all we provide are the certificate signing request and a CA private key. 

We could provide the same bindings for python cryptography. Current methods are manual and require generating a new certificate using the certificate signing request credentials.

The Requirement Overview:
![Model_requirement_diagram_SysML_1_6_Requirement_Diagram](https://user-images.githubusercontent.com/86283153/155197681-83d652d4-84e0-47ec-bd01-609bda5f1971.SVG)

Here, we will mainly call the OpenSSL native function that creates a certificate from a CSR.

The main function - which will create a Certificate, will be a function addition to CertificateBuilder object, that will access the native OpenSSL - (-req) API function through python.

Class Block Overview:

![SysML_1_6_Block_Definition_Diagram](https://user-images.githubusercontent.com/86283153/155198147-593cffb1-4123-4d48-a2af-a06bc9bbc3c5.SVG)

Rationale behind the approach:

OpenSSL by default can create a certificate by taking in a certificate signing request, and signing it with a CA key. The approach currently used is to create a new self signed certificate from the certificate signing request parameters, which is not an intuitive method for users. 

This approach will provide a 1-1 implementation between OpenSSL and Cryptography.

**Comment by alex** [comment]
It is an intentional design decision that we do not provide a `csr_to_cert(ca, csr) -> cert` function in pyca/cryptography.

This is because which fields may be safely copied from a CSR into a certificate is a policy decision which is different for every CA. For example, in a webpki context it's inappropriate to copy _anything_, as SANs and Subjects need to validated external to their inclusion in a CSR. However, in other contexts a CSR may be a data interchange format between two trusted components of a system wherein more fields may be copied. In almost no circumstances is it correct to trust a basicConstraints extension in a CSR, however!

For these reasons, we do not intend to add such a function to pyca/cryptography, as it would either be wrong in many cases or require a large amount of configuration (which could not be optional, as any default would be wrong in many cases!). Instead our goal is to make the CSR and CertificateBuilder APIs ergonomic enough that users can easily write a small function to copy the appropriate data for their use case from one to the other.

Thanks.

**Comment by sanchayanghosh** [comment]
@alex Thank you for your feedback!

I have a few points to clarify. Can we implement a direct openssl binding into python, taking into account -req switch. 

Since, you have pointed out that there are many fields that may not be appropriate to copy into a certificate in many contexts, shall we directly use OpenSSL API calls to handle the generation of the certificate and provide a binding only for that. We could pass over the certificate signing request data over to OpenSSL and have it return us the Certificate. This way, we do not worry about which fields we would copy. 

This change may just be a way to use OpenSSL through python, but can  provide users with a one-stop API to covert their CSRs. Since, users may also not be very sure of all the fields that they can safely copy. Eg. a user just wants to generate an on-the-fly certificate for TLS. They can just effectively call OpenSSL's conversion function through Python similar to what we do with *.openssl.bindings library in pyca/cryptography.

**Comment by reaperhulk** [comment]
OpenSSL's `-req` flag on the `x509` subcommand unconditionally copies the subject. When combined with `-copy_extensions` you can have it either copy all the extensions (overwriting any existing ones that may be coming from other config), copy only ones not present in the existing config, or not copy at all. This is not a good user experience and ultimately isn't safe to use without extensive X509 experience. Additionally, you can replicate this behavior with two lines of code using CertificateBuilder so I'm opposed to adding anything to simplify what is already extremely simple.

I would be happy to have an example added to the docs that shows how to generate a cert from a CSR in this fashion, with the caveat that we should very prominently document why CSRs should not be considered trusted sources of data in a real system.

**Comment by sanchayanghosh** [comment]
Hi @reaperhulk 

Should I open a seperate documentation PR for the same? I have already seen several StackOverflow questions regarding the same and I would quite prefer a more official source for a guide on how to replicate openssl -req with cryptography

**Comment by reaperhulk** [comment]
I’m fine with opening a PR for doc improvements here. The change needs to show a working example and also contain a warning explaining why this is unsafe to do with untrusted CSRs

**Comment by sanchayanghosh** [comment]
Hi @reaperhulk 

One more doubt. When we use cryptography bindings, how shall we handle the challenge password that CSRs have?

Usually Certificate objects (root certificates) do not contain this field.
