### ISSUE TITLE
Thank You for great documentation 🙏

### ISSUE THREAD

**Issue by Uninen** [pyca/cryptography#6901]
The maintainers of packages like these too seldomly receive thanks for their work. I was able to install and build this package today on a M1 Mac with Python 2.7 (!!) just by reading the clear and up to date instructions in the docs.

(In short: 1) first install openssl and rust, 2) then `env LDFLAGS="-L$(brew --prefix openssl@1.1)/lib" CFLAGS="-I$(brew --prefix openssl@1.1)/include" pip install cryptography`)

Thank You for your work. Feel free to close this issue immediately.

**Comment by alex** [comment]
Thanks for the kind words!
