### ISSUE TITLE
test_openssl_assert_error_on_stack fails with OpenSSL 3.0.1 FIPS

### ISSUE THREAD

**Issue by tiran** [pyca/cryptography#6917]
The test case ``test_openssl_assert_error_on_stack`` fails with ``openssl-3.0.1-5.el9.x86_64`` on C9S on a FIPS enabled system. My guess is FIPS provider changes the error code from invalid block length to generic FIPS ``digital envelope routines::unsupported`` error code:

```
self = <test_openssl.TestOpenSSL object at 0x7f3eb5d8e880>

    def test_openssl_assert_error_on_stack(self):
        b = Binding()
        b.lib.ERR_put_error(
            b.lib.ERR_LIB_EVP,
            b.lib.EVP_F_EVP_ENCRYPTFINAL_EX,
            b.lib.EVP_R_DATA_NOT_MULTIPLE_OF_BLOCK_LENGTH,
            b"",
            -1,
        )
        with pytest.raises(InternalError) as exc_info:
            _openssl_assert(b.lib, False)
    
        error = exc_info.value.err_code[0]
        # BoringSSL has completely different error codes, so we just skip
        # these assertinos.
        if not b.lib.CRYPTOGRAPHY_IS_BORINGSSL:
            # As of 3.0.0 OpenSSL no longer sets func codes (which we now also
            # ignore), so the combined code is a different value.
>           assert error.code in (101183626, 50331786)
E           AssertionError: assert 50856204 in (101183626, 50331786)
E            +  where 50856204 = _OpenSSLErrorWithText(code=50856204, lib=6, reason=524556, reason_text=b'error:0308010C:digital envelope routines::unsupported').code

tests/hazmat/bindings/test_openssl.py:105: AssertionError
```

**Comment by reaperhulk** [comment]
This seems likely to be a change made upstream by RHEL, as we do actually test the 3.0.1 FIPS provider directly (https://github.com/pyca/cryptography/blob/main/.github/workflows/ci.yml#L37). I'm fine with changing this to simply not use error codes from the `lib` object though, as they're not stable and the purpose of the test is to see if we can push an error on stack and then read it off again to get the same values. We don't specifically care what that error is.
