### ISSUE TITLE
Support ExtendedKeyUsage parameters that OpenSSL supports

### ISSUE THREAD

**Issue by sanchayanghosh** [pyca/cryptography#6920]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

Currently, as I checked in cryptography master branch, under ExtendedKeyUsageOID, we do not have support for - 

ipsecIKE               ipsec Internet Key Exchange
 msCodeInd              Microsoft Individual Code Signing (authenticode)
 msCodeCom              Microsoft Commercial Code Signing (authenticode)
 msCTLSign              Microsoft Trust List Signing
 msEFS                  Microsoft Encrypted File System

These are supported in OpenSSL and are used for different network applications. We need to include the usage for this in Python's cryptography extensions.

**Comment by reaperhulk** [comment]
We generally don’t expose constants without a concrete use case. Can you provide examples where you need support for this? These are generally unusual EKUs (especially the MS ones, where certs using these EKUs must chain to roots with specific trust flags).

It’s also entirely possible to generate certificates with arbitrary EKUs right now without us adding these constants. Simply pass an instance of ObjectIdedentifier with the required OID.

**Comment by sanchayanghosh** [comment]
Thanks Paul for the update. I can certainly set custom constants with OIDs to pass for my use case.

Frankly, I do not know the use cases for the Microsoft related OIDs, but IPSec related OIDs are a staple for when we may want to set up IPSec SAs. Without this, we cannot have an IKE.

**Comment by reaperhulk** [comment]
We'd be happy to take a PR adding the IPSec OID if you'd like to contribute it! But you can just instantiate your own OID as a workaround until we release a version with your hypothetical PR 😄

**Comment by sanchayanghosh** [comment]
Before I close this issue, 

Do you feel we should incorporate the other ExtendedKeyUsageOID?

msCodeInd Microsoft Individual Code Signing (authenticode)
msCodeCom Microsoft Commercial Code Signing (authenticode)
msCTLSign Microsoft Trust List Signing

These are used for Code Signing, etc. for windows applications. 

Depending on you suggest, I can close this issue.

**Comment by alex** [comment]
Based on the discussion above I think we can declare this closed. If there's a need for another OID to be added a new issue/PR can be filed.

thanks!
