### ISSUE TITLE
Feature Request: A built-in method that uses the OpenSSL wrapper to generate a PKCS7 certificate from PEM certificates.

### ISSUE THREAD

**Issue by sanchayanghosh** [pyca/cryptography#6932]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

As described above, OpenSSL has an API that generates a PKCS7 certificate from a PEM certificate. These certificates will contain the converted certificate with only the public key.

Use cases for such:

1. Many systems only accept PKCS7 certificate installation in their trust chain. 
2. PKCS7 certificates support also add a Certificate Revocation List. Since, cryptography already supports creating and loading CRLs, we can now take the next step and generate PKCS7 certificates from both.
3. Overall, good to have to expand the capabilities of cryptography.

These certificates will typically use the syntax 

openssl crl2pkcs7 -certfile <pem_path> -crl|-nocrl -out <p7b path>

The output certificate will have the signature - 

-------------BEGIN PKCS7---------------
-------------END PKCS7-----------------

**Comment by reaperhulk** [comment]
If I understand correctly, this is a feature request to allow the serialization of X509 certificates into a PKCS7 structure without a signature. We already support PKCS7 but only as a signed structure (e.g. S/MIME), but the need is for a `p7b` in the Windows/Tomcat sense, correct?

**Comment by sanchayanghosh** [comment]
That is one of the asks.

The other is to also support passing in a CertiicateRevocationList (which we can already generate from within cryptography).

OpenSSL uses this in the context of crl2pkcs7 where we can optionally pass in a revocation list to output a PKCS#7 degenerate "certificates only" structure.

**Comment by reaperhulk** [comment]
I'm not entirely sure I follow the second request, but we'd be happy to look at PRs and discuss!

**Comment by sanchayanghosh** [comment]
Will be sending in the PR by Thursday. I have identified the OpenSSL API function - pem_write_bio_stream under the pem.h library that encodes all the certificate, crl data to pkcs7.

**Comment by jobec** [comment]
I need the same. Right now I'm using this as a hacky workaround.

```python
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.serialization import pkcs7
from cryptography.hazmat.backends.openssl.backend import backend

pkcs7_data = pkcs7.PKCS7SignatureBuilder()
pkcs7_data = pkcs7_data..set_data(b"")
pkcs7_data = pkcs7_data.add_certificate(cert)
with open(file, 'wb') as f:
    f.write(backend.pkcs7_sign(pkcs7_data, serialization.Encoding.PEM, []))
```
