### ISSUE TITLE
Setting ECDSA as signature Algorithm

### ISSUE THREAD

**Issue by oldguardmd** [pyca/cryptography#6944]
Attempting to sign content with ECDSA, I am getting 
- **sign() missing 1 required positional argument: 'algorithm'**

```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import padding
import base64

privateKeyFile = '/someLocation/.ssh/ansible.key'

def sign_streaming(privateKey, content, algorithm=hashes.SHA256()):
    with open(privateKey, 'rb') as privateKey:
        key = serialization.load_pem_private_key(
            privateKey.read(), None, default_backend())
    hasher = hashes.Hash(algorithm, default_backend())
    hasher.update(str.encode(content))
    hashedContent = hasher.finalize()
    return key.sign(
        hashedContent,
        ec.ECDSA(hashes.SHA256)
    )

signature = sign_streaming(privateKeyFile, "GET http://SomeSystemIP/api/class/fvTenant.json?rsp-subtree=children\n")

print(base64.encodebytes(signature).decode())
```
I can get it to sign the content by removing **ec.ECDSA(hashes.SHA256())** and exchanging it with a padding line, but then I am pretty confident that I am not getting ECDSA as my signing algorithm. This changed piece is an example that is functional, but not complete.

```
...
    return key.sign(
        hashedContent,
        padding.PKCS1v15(),
        hashes.SHA256()
```

All I need at this point is to specify the signing algorithm, but I don't see how I do that. 

Running Python 3.9.7 in a CentOS 8 Stream docker container.

Following was installed with pip3
- certifi            2021.10.8
- cffi                1.15.0
- pip                20.2.4
- setuptools    50.3.2

**Comment by alex** [comment]
It looks like you're passing arguments that assume that `key` is an ECDSA private key, but in reality it's an RSA private key. RSA and ECDSA keys' sign methods take different arguments.

**Comment by oldguardmd** [comment]
I see that now. Appreciate the correction.
