### ISSUE TITLE
Difference in AlgorithmID encoding for x509 certificate in different backends

### ISSUE THREAD

**Issue by fjarri** [pyca/cryptography#6949]
Not sure if it would be considered a bug or not.

In my application, I create a certificate in Python (using `cryptography.x509`), pass it to Rust (as DER), where it can be deserialized and serialized again (using [`x509-certificate`](https://crates.io/crates/x509-certificate)), and the resulting DER used on the Python side. The problem is that the resulting DER coming out of Rust is different from the one created by Python (meaning that both the DER bytestrings are different, and the deserialized certificate object is not equal to the original one), even though all the public fields are the same. This results in some inconveniences where I have to manually alter the Python-created certificate (see below on what needs to be altered) to prevent certificate checks from failing.

The reason is that when the certificate is serialized on the Python side, the algorithm ID has no parameters, so the corresponding section of the DER looks like
```
0x30 <length> 0x6 <length> <OID>
```
(where 0x30 is the SEQUENCE tag, and 0x6 is the OID tag). This deserializes fine in Rust, but when I serialize the certificate there, it adds an explicit NULL section:
```
0x30 <length> 0x6 <length> <OID> 0x5 0x0
```

Apparently, it is a [conscious choice](https://github.com/indygreg/PyOxidizer/blob/main/x509-certificate/src/rfc5280.rs#L70) of `x509-certificate` authors: 
```rust
        // parameters is strictly OPTIONAL, which means we can omit it completely.
        // However, it is common to see this field encoded as NULL and some
        // parsers seem to insist the NULL be there or else they refuse to
        // parse the ASN.1. So we ensure this field is always set.
```
I tried creating a self-signed certificate with just `openssl` in console, and it adds the explicit NULL section as well. 

`cryptography`'s Rust backend uses [`asn1`](https://docs.rs/asn1/latest/asn1/) for serialization, and I believe the relevant section is [here](https://github.com/pyca/cryptography/blob/main/src/rust/src/x509/common.rs#L313):
```
#[derive(asn1::Asn1Read, asn1::Asn1Write, PartialEq, Hash, Clone)]
pub(crate) struct AlgorithmIdentifier<'a> {
    pub(crate) oid: asn1::ObjectIdentifier<'a>,
    pub(crate) params: Option<asn1::Tlv<'a>>,
}
```
If `params` was declared as `Explicit`, it would result in the same behavior as `openssl` or `x509-certificate`.

(Although, I must admit, I do have OpenSSL backend selected, so perhaps there's something else at play - hopefully someone who is more knowledgeable about the codebase can point me to the source)

So, I guess, my question is — is that something that you would consider an issue, or do you plan on keeping this behavior? Technically, omitting empty parameters is the correct thing to do according to RFC5820, but it seems that even `openssl` doesn't do it.

**Comment by alex** [comment]
Which `oid` are we talking about here? Various additional specs define whether you're supposed to make `params` be `NULL`, omitted, or have a value, and we try to adhere to those (but perhaps we have a bug!)

**Comment by fjarri** [comment]
In my case, it's 1.2.840.10045.4.3.4 (ecdsa-with-SHA512)
In the pure OpenSSL test I also had 1.2.840.113549.1.1.11 (sha256WithRSAEncryption)

**Comment by alex** [comment]
From the RFC https://datatracker.ietf.org/doc/html/rfc5758#section-3.2:

>   When the ecdsa-with-SHA224, ecdsa-with-SHA256, ecdsa-with-SHA384, or
>   ecdsa-with-SHA512 algorithm identifier appears in the algorithm field
>   as an AlgorithmIdentifier, the encoding MUST omit the parameters
>   field.  That is, the AlgorithmIdentifier SHALL be a SEQUENCE of one
>   component, the OID ecdsa-with-SHA224, ecdsa-with-SHA256, ecdsa-with-
>   SHA384, or ecdsa-with-SHA512.

Based on this I believe our implementation is correct.

**Comment by fjarri** [comment]
Yes, as I said, I am aware that it is the correct behavior according to the standard, but some implementations (inlcuding OpenSSL) do not follow it and claim that some clients require them not to follow it (although I have no information what clients require the explicit null parameters). I'm guessing that your position is that you stick with the standard here.

**Comment by alex** [comment]
Yes -- if there was a compatibility issue where certificates couldn't be verified from a major verifier we'd consider doing the non-standard behavior, however when the issue is simply that we don't match another cert generator, we'll generally prefer to stick to the standard.

**Comment by fjarri** [comment]
Ok, fair enough. I tried to dig around the commit that introduced that comment in `x509-certificate`, but there's no indication on what clients specifically require the NULL field, so I can't really use that as an argument :) Closing.
