### ISSUE TITLE
Parse Error in ASN1.value when signing CertificateSigningRequestBuilder with otherName SAN extension

### ISSUE THREAD

**Issue by phughesion** [pyca/cryptography#6970]
I am using cryptography 37.0.0.dev1 after I initially attempted to fix this issue by following #6926 
pyOpenSSL version 22.0.0

The reproducer in #6926 does not give me any errors.

The proper otherName string (which works using crypto.x509Req()) is "otherName:1.3.6.1.4.1.311.20.2.3;UTF8:Administrator" if that helps at all.

Here is a short reproducer for this issue:

```
from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.serialization import Encoding
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

CN = "Administrator"
otherName = x509.OtherName(x509.ObjectIdentifier("1.3.6.1.4.1.311.20.2.3"), b"Administrator")

csr = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, CN)]))
csr = csr.add_extension(x509.SubjectAlternativeName([otherName]),critical=False)

key = rsa.generate_private_key(public_exponent=65537, key_size=4096)
cert = csr.sign(key, hashes.SHA256())
```
```
Traceback (most recent call last):
  File "/home/paul/Dev/x509.py", line 15, in <module>
    cert = csr.sign(key, hashes.SHA256())
  File "/home/paul/.local/lib/python3.9/site-packages/cryptography/x509/base.py", line 625, in sign
    return rust_x509.create_x509_csr(self, private_key, algorithm)
ValueError: error parsing asn1 value: ParseError { kind: ShortData }
```

**Comment by alex** [comment]
Confirmed the issue, even more minimal reproducer:

```
from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa

csr = (
    x509.CertificateSigningRequestBuilder()
    .subject_name(x509.Name([]))
    .add_extension(
        x509.SubjectAlternativeName(
            [x509.OtherName(x509.ObjectIdentifier("1.3"), b"")]
        ),
        critical=False,
    )
)

key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
csr.sign(key, hashes.SHA256())
```

**Comment by reaperhulk** [comment]
Thanks for the report and the easy reproducer. I can confirm I see the same issue.

**Comment by alex** [comment]
Ok, on closer investigation this is not a bug: OtherName value must be a DER payload. I'll send a PR making this error message clearer.

**Comment by reaperhulk** [comment]
The issue here is that we require OtherName to be valid DER, not an arbitrary byte string. We should improve this error msg on parse, but we could also validate when creating an `OtherName` object.

For your case the actual bytes you likely want to be encoding are b"\x0c\rAdministrator" which is DER for UTF8 string of length 13. You can confirm this by seeing if the DER output of your working example (using the OpenSSL specific string) contains that byte sequence 😄
