### ISSUE TITLE
Possible bug: empty sequence in NameConstraints

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#6982]
Hi,

Now I've been going through various RFCs again and again, and I'm still not quite sure if this is a subtle bug in cryptography, or if this is actually valid x509.  Regarding `permittedSubtrees` and `excludedSubtrees`: Is an empty sequence valid at all (and if yes, what are the semantics?).

cryptography does not treat an empty list any different then any other list, but treats `None` special. That means, you can even create an extension with an empty _list_ of permitted/excluded subtrees, while of course passing None raises an exception:

```python
>>> x509.NameConstraints(permitted_subtrees=[], excluded_subtrees=[])
<NameConstraints(permitted_subtrees=[], excluded_subtrees=[])>
>>> x509.NameConstraints(permitted_subtrees=None, excluded_subtrees=None)
...
    ValueError: At least one of permitted_subtrees and excluded_subtrees must not be None
```

The public bytes generated for an empty list also differ to a `None` value:

```
>>> x509.NameConstraints(permitted_subtrees=[x509.DNSName('example.com')], excluded_subtrees=None).public_bytes()
b'0\x11\xa0\x0f0\r\x82\x0bexample.com'
>>> x509.NameConstraints(permitted_subtrees=[x509.DNSName('example.com')], excluded_subtrees=[]).public_bytes()
b'0\x13\xa0\x0f0\r\x82\x0bexample.com\xa1\x00'
```

So is an empty list something we need to support? Or is it actually a bug?

Slightly related side-note: can we make both values default to `None` in the constructor, that way you can also pass just one of the values when creating the extension. If you agree, I will submit an MR.

**Comment by alex** [comment]
Yes, this is a bug, we should be rejecting non-none values that are less than 0 because:

```
GeneralSubtrees ::= SEQUENCE SIZE (1..MAX) OF GeneralSubtree
```

**Comment by mathiasertl** [comment]
GREAT! (I was hoping for that). I will submit a PR.

**Comment by alex** [comment]
Great, thank you!

**Comment by mathiasertl** [comment]
> Slightly related side-note: can we make both values default to None in the constructor, that way you can also pass just one of the values when creating the extension. If you agree, I will submit an MR.

And what do you think? :-)

**Comment by alex** [comment]
We generally avoid having defaults in APIs -- to ensure that consumers aren't accidentally missing details that are relevant. We know it's a bit more verbose, but we think it's the right trade-off.
