### ISSUE TITLE
Question: OS Random engine, FIPS and OpenSSL < 1.1.1d

### ISSUE THREAD

**Issue by kulikjak** [pyca/cryptography#6992]
Hi, I have a question regarding the OS Random engine, FIPS and OpenSSL 1.0.2*.

In cryptography 2.5 we used up until recently, there was no issue when running with OpenSSL 1.0.2 in the FIPS mode, but recently we moved to 3.1.1 and started getting a warning from the following code snippet:

https://github.com/pyca/cryptography/blob/decec8795ae10ca30e5be0a00fb53db2fe867dfb/src/cryptography/hazmat/backends/openssl/backend.py#L190-L196

In 2.5, there was no check, and `self.activate_osrandom_engine()` was called unconditionally. Now there is this check which I presume is related to [fork reseed fix](https://github.com/pyca/cryptography/pull/5317) of CSPRNG in 1.1.1d, but that was never part of 1.0.2 and thus fork safety was also not an issue, right?

This change got there with https://github.com/pyca/cryptography/commit/4a245a657a071dff959d30eff1d214c7ff88eada but there is no explanation as for why.

Is this an overlooked bug, or do I understand it all wrong?

*) we cannot go further until we have a FIPS certification for OpenSSL 3.0. I do realize that 1.0.2 is no longer supported by cryptography, but I do not expect this to be fixed in main; we will handle it internally.

**Comment by kulikjak** [comment]
I see. And the fact that it was being replaced in cryptography 2.5 was not intended, but a mistake that was mended with https://github.com/pyca/cryptography/commit/4a245a657a071dff959d30eff1d214c7ff88eada. So when using anything older than 1.1.1d with FIPS (including 1.0.2), we don't have FIPS compliant option to use any CSPRNG, right?

**Comment by alex** [comment]
Prior to that commit we were calling `activate_osrandom_engine` unconditionally, but I think it might be a no-op on FIPS openssl. Before that commit we weren't officially supporting FIPS at all, so I really don't know what was happening.

I suggest you reach out to @reaperhulk, he works for your company and can give you better advice.

**Comment by kulikjak** [comment]
Good point, thanks @alex for answers.
