### ISSUE TITLE
error: 101   someone pls help me w this

### ISSUE THREAD

**Issue by LuaR0bloz** [pyca/cryptography#6998]
i have no idea what this error means, someone pls help me
![error](https://user-images.githubusercontent.com/95602665/160030813-5dd2fc89-b161-431f-98c6-6c679f91b557.png)

**Comment by reaperhulk** [comment]
Error 101 means cargo panicked, but this can unfortunately happen for a variety of reasons. You appear to be compiling this on a phone running armv7l, could you provide more details on your environment?

**Comment by alex** [comment]
Closing because no response, will reopen if more details are provided.
