### ISSUE TITLE
Long-standing code for cert signing fails on v36.0.0+

### ISSUE THREAD

**Issue by thinkwelltwd** [pyca/cryptography#7006]
I'm using an in-house CA to sign certs and the same code has been working for years, up to and including 35.0.0. But 36.0.0 and higher raises the following traceback:

```
  File "/usr/local/lib/python3.9/dist-packages/cryptography/x509/base.py", line 881, in sign
    return rust_x509.create_x509_certificate(self, private_key, algorithm)
AttributeError: '_RSAPrivateKey' object has no attribute 'public_bytes'
```

The `sign` method changed from `return backend.create_x509_certificate(self, private_key, algorithm)` to `return rust_x509.create_x509_certificate(self, private_key, algorithm)`

Is this a bug in the new-style rust code?

**Comment by alex** [comment]
Hmm, this may be a bug in the new code, but it's also possible it was a bug in the old code -- allowing a private key somewhere that was supposed to take a public key!

Do you by chance have a minimal reproducer you can share?

If I had to take a guess at what's going on, I'd guess that you're calling `public_key()` on the builder but passing a private key.

**Comment by thinkwelltwd** [comment]
> allowing a private key somewhere that was supposed to take a public key!

Thanks for the fast reply; you're a good guesser. :smile:  I was passing a private key to the Builder's `public_key` arg

```python
    cert = x509.CertificateBuilder(
        public_key=key,
        ...
```

Changing to `pub.public_key()` fixes the problem.

```python
    cert = x509.CertificateBuilder(
        public_key=key.public_key(),
        ...
```

**Comment by alex** [comment]
FWIW part of your problem here is that you're using the `CertificateBuilder` constructor, which is not intended for public use and isn't documented, if you use the builder methods (e.g. https://cryptography.io/en/latest/x509/reference/#cryptography.x509.CertificateBuilder.public_key) it properly raises an exception indicating you need to pass a public key :-)

**Comment by thinkwelltwd** [comment]
> FWIW part of your problem here is that you're using the CertificateBuilder constructor, 

Ah yes :bulb: thanks for pointing that out - updated now. 

Thanks for the `cryptography` library!
