### ISSUE TITLE
[Feature request] support of CMPv2

### ISSUE THREAD

**Issue by grindsa** [pyca/cryptography#7031]
It would be helpful if this lib would provide an interface towards the [openssl-cmp application](https://www.openssl.org/docs/manmaster/man1/openssl-cmp.html)  which has been introduced in openssl 3.0.  Do you have any plans to support this in the near future?

**Comment by reaperhulk** [comment]
There are no plans to support this at this time. If we did implement anything it would probably take the form of CMP data structures, as a full CMP client/server is definitely out of scope for this project.

What's your use case for CMP?

**Comment by grindsa** [comment]
Thank you for your answer. My use-case would be either a python based cmp client for certificate enrolment or a wrapper around the `openssl cmp` command.

**Comment by reaperhulk** [comment]
A CMP implementation is going to remain out of scope for cryptography itself. If someone wants to implement this using cryptography please let us know if our hazmat APIs are insufficient!
