### ISSUE TITLE
Escape sequence bugs in RFC4514 parser (unreleased)

### ISSUE THREAD

**Issue by intgr** [pyca/cryptography#7081]
The parser merged in #7055 seems to have some bugs involving escape sequences. I tested and got these results with git `main` branch:

```python
>>> from cryptography.x509 import Name, NameAttribute, NameOID
>>> Name([NameAttribute(NameOID.COMMON_NAME, "\\123")])
<Name(CN=\\123)>
>>> Name.from_rfc4514_string(_.rfc4514_string())
<Name(CN=3)>
>>> Name([NameAttribute(NameOID.COMMON_NAME, "\\#123")])
<Name(CN=\\#123)>
>>> Name.from_rfc4514_string(_.rfc4514_string())
<Name(CN=\#123)>
```

I opened a new issue just in case to make sure this doesn't slip through the cracks.

**Comment by reaperhulk** [comment]
@intgr Thanks for testing so quickly. Are there more edge cases you suspect exist/have test vectors for? We'll definitely want to fix anything that's wrong before release of course.

**Comment by alex** [comment]
Ok I've submitted a PR to fix this (#7083) -- thanks so much for the early review+testing and if you spot any other bugs please holler!

**Comment by intgr** [comment]
I played around with it a bit more, here's another case. Multi-digit components aren't accepted in dotted OID notation.

```python
>>> Name.from_rfc4514_string(r'2.5.4.1=org')
<Name(2.5.4.1=org)>
>>> Name.from_rfc4514_string(r'2.5.4.10=org')
Traceback (most recent call last):
ValueError
```

**Comment by alex** [comment]
Oh regex.... fix for that pushed to the same PR.
