### ISSUE TITLE
PKCS12 modern defaults

### ISSUE THREAD

**Issue by rbuffat** [pyca/cryptography#7099]
Not sure if this is of relevance. 

While investigating https://github.com/pyca/cryptography/issues/7065 I noticed that creating a PKCS12 truststore using openssl uses different parameters compared to `serialization.BestAvailableEncryption` of cryptography:

OpenSSL 1.1.1n  15 Mar 2022:
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
``` 

cryptography 37.0.0 dev (serialization.BestAvailableEncryption):

```
MAC: sha1, Iteration 1
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 20000
```

keytool java-18-openjdk 18.0.1.u10: 

```
MAC: sha256, Iteration 10000
MAC length: 32, salt length: 20
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 10000, PRF hmacWithSHA256
```

keytool java-8-openjdk 8.332.u04: 

```
MAC: sha1, Iteration 100000
MAC length: 20, salt length: 20
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 50000

```

Relevant code:

https://github.com/pyca/cryptography/blob/d295365e93a5e3142b0cbdcc1b303235e32781cd/src/cryptography/hazmat/backends/openssl/backend.py#L2202-L2212

Commit that changed defaults in OpenSSL 3.0.2:
https://github.com/openssl/openssl/commit/762970bd686c4aa8ea7169e7f76d5a4ce665da93

**Comment by reaperhulk** [comment]
This is covered by #7043, although we appreciate the additional data 😄 Closing in favor of that issue, but we can continue discussion there. In general we're in favor of ratcheting up the encryption quality but we need to do some work to enable it.
