### ISSUE TITLE
Add NameOID for OID not  on cryptography before certificate parsing to get valid OID._name 

### ISSUE THREAD

**Issue by fredcwbr** [pyca/cryptography#7102]
How do I add new NameOID from ObjectIdentifier like  
 OIDMEMBER = x509.ObjectIdentifier("2.5.4.31")
 OIDROLE = x509.ObjectIdentifier("2.5.4.72")
 OIDOWNER = x509.ObjectIdentifier("2.5.4.33")

and others  before x509 load , 

Python 3.9.12
python3-cryptography: 3.4.8-1         500 http://ftp.br.debian.org/debian bookworm/main amd64 Packages

** It's not a bug., 

Looked up the source code to understand how to add new OIDs before loading certificates, and didn't find ., 

Appreciate guidance and help.

Thanks in advance , and congrats to  your work ., really helpfull.,

**Comment by alex** [comment]
You don't need to add ObjectIdentifiers to the `NameOID` structure, you can just pass them to whatever API takes an OID. The `NameOID` structure isn't special, it's just a namespace for a few commonly used OIDs.

**Comment by fredcwbr** [comment]
Didn't understand you reply, and I apologize if it looks like a  dumb question.

In the following snippet 


    Fcert_pem = open(EASYRSAPATH + '/pki/certs_by_serial/039CB3BC609AA93AF7DE579E13308DB8.pem',"rb")
    cert_pem = Fcert_pem.read()
    cert_info = x509.load_pem_x509_certificate(cert_pem)
    # cert_subject = cert_info.subject
    
    for I in cert_info.subject:
        print( 'oid=' , I.oid.dotted_string, ';  Attributo : ', I.oid._name , ' = ',  I.value )

This is the result 


oid= 2.5.4.6 ;  Attributo :  countryName  =  BR
oid= 2.5.4.8 ;  Attributo :  stateOrProvinceName  =  Goias
oid= 2.5.4.7 ;  Attributo :  localityName  =  XXXXXXXXXXXXXXXXX
oid= 2.5.4.10 ;  Attributo :  organizationName  =  XXXXXXXXXXXXXXXXX
oid= 2.5.4.11 ;  Attributo :  organizationalUnitName  =  XXXXXXXXXXXXXXXXX
oid= 2.5.4.3 ;  Attributo :  commonName  =  XXXXXXXXXXXXXXXXX
oid= 1.2.840.113549.1.9.1 ;  Attributo :  XXXXXXXXXXXXXXXXX
oid= 2.5.4.31 ;  Attributo :  Unknown OID  =  OPERADORES
oid= 2.5.4.32 ;  Attributo :  Unknown OID  =  ITTEC-GF
oid= 2.5.4.72 ;  Attributo :  Unknown OID  =  Operador
oid= 2.5.4.33 ;  Attributo :  Unknown OID  =  Servidor


What should be done to get the correct "oid._name" instead of "Unknown OID" ?

**Comment by alex** [comment]
There's no public API giving OIDs names (or for getting names for that matter). You can easily do this yourself with:

```
OID_NAMES = {
    ObjectIdentifier('...'): 'my name',
    # ...
}

oid = ...
name = OID_NAMES.get(oid, oid._name)
```

**Comment by fredcwbr** [comment]
Thank you very much., 
That closes the matter., 


Congrats on your work., 

Best regards
