### ISSUE TITLE
Allow Fernet.decrypt() to accept strings

### ISSUE THREAD

**Issue by rcoup** [pyca/cryptography#7105]
Currently `Fernet.decrypt()` only accepts `bytes`; we could remove some developer friction by also allowing string tokens to be passed:

1. a valid Fernet token as generated by `Fernet.encrypt()` is url-safe base64-encoded
2. so it's definitely not a valid token if `str_token.encode('ascii')` fails
3. when passing a token as part of any JSON payload, stdlib returns strings
4. when passing a token as part of a HTTP header, python web frameworks return string values

Just removes cycles of "TypeError: token must be bytes" error → "add `.encode('ascii')`" → do it again. Not so much in the few places an app is decoding tokens, but I've found it happens repeatedly writing tests and using via REPL.

Even though it's crypto code 🐉 , given the clear base64 encoding of tokens I feel the "be liberal in what you accept" mantra _can_ be robustly applied here to remove friction from the developer experience.

Happy to prepare a patch/tests if you think it's worthwhile addition.

**Comment by reaperhulk** [comment]
I think this is a reasonable argument for allowing str in the fernet and multi fernet APIs, so please do send a PR!
