### ISSUE TITLE
Drop support for OpenSSL 1.1.0

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#7109]
- [x] 37: Initial deprecation warning
- [x] 38: Final release with support (update error messages)
- [x] 39: Drop support

**Comment by reaperhulk** [comment]
Note: we will need to update the FAQ when we fully drop.

**Comment by alex** [comment]
Remaining task here is to either resolve, or update, a few comments findable with: `rg 'CRYPTOGRAPHY_OPENSSL_LESS_THAN_111\b'`
