### ISSUE TITLE
User prompt on calling `load_pem_public_key` with private key

### ISSUE THREAD

**Issue by arunanshub** [pyca/cryptography#7129]
## Issue description

When deserializing a private key using `load_pem_public_key()`, a prompt is displayed:

```none
Enter PEM pass phrase:
```

This happens with `cryptography` version `37.0.0`. Testing with `cryptography` version `36.0.2` shows no such prompt.

## Steps to reproduce bug

```python
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import serialization as ser

priv_key = rsa.generate_private_key(65537, 1024)
priv_key_serialized = priv_key.private_bytes(
    ser.Encoding.PEM,
    ser.PrivateFormat.PKCS8,
    ser.BestAvailableEncryption(b"helloworld"),
)

pub_key = ser.load_pem_public_key(priv_key_serialized)
```

## `cryptography` installation

`cryptography` is installed via `poetry` with version constraint `>=35.0.0`:

```toml
[tool.poetry.dependencies]
python = "^3.8"
cryptography = ">=35.0.0"
```

## Required Version numbers

- `pip` - 21.3.1
- `cffi` - 1.15.0
- `cryptography` - 37.0.0
- `setuptools` - 60.1.0

**Comment by reaperhulk** [comment]
Confirmed, thanks for the easy reproducer. This is due to the switch from OpenSSL 1.1.1 to 3.0.2 in our wheels, where clearly OpenSSL has some extraordinarily undesirable behavior in its APIs.
