### ISSUE TITLE
Removing return type on default_backend makes the function untyped.

### ISSUE THREAD

**Issue by Gaasmann** [pyca/cryptography#7130]
Hello,

It seems that #6750 removed the return type for default_backend making the whole function untyped which makes mypy yell at us in our project for using an untyped function on a typed context. 
You might want something like:
```python
def default_backend() -> Any:
```
to play the role of WhoCares :-)

**Comment by reaperhulk** [comment]
Happy to take a PR to do that if that's helpful!

**Comment by reaperhulk** [comment]
We're planning to do a 37.0.1 today to fix another issue that cropped up with OpenSSL 3.0 so you can have this fix very quickly if you want 😄 (Please send two PRs: one to `main` and the other to `37.0.x`)

**Comment by reaperhulk** [comment]
Both look perfect, thanks for sending the backport PR!

**Comment by Gaasmann** [comment]
Thank you! Closing the issue.
