### ISSUE TITLE
Remove legacy bindings kept for pyOpenSSL < 22.0.0

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#7138]
We re-added bindings in #7136 that we do not want to maintain in perpetuity. This is a tracking issue for removing them in an upcoming milestone.

**Comment by alex** [comment]
Placing in the 38th milestone to discuss, not necessarily a commitment to revert for 38.0

**Comment by alex** [comment]
Agreement that we'll _likely_ want to do this for 38, but we'll make the final decision closer to the release.
