### ISSUE TITLE
Remove deprecated from_encoded_point

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#7179]
It's been deprecated since 2019 and this is a tracking issue for removing it.

**Comment by ronf** [comment]
Can you confirm that this is removing [`ec.EllipticCurvePublicNumbers.from_encoded_point()`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/?highlight=from_encoded_point#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicNumbers.from_encoded_point) and not touching [`ec.EllipticCurvePublicKey.from_encoded_point()`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/?highlight=from_encoded_point#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicKey.from_encoded_point) which replaced it?

You might want to also consider removing [`ec.EllipticCurvePublicNumbers.encode_point()`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/?highlight=encode_point#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicNumbers.encode_point), which was deprecated at the same time.

**Comment by alex** [comment]
Correct on both counts!

**Comment by ronf** [comment]
Thanks!
