### ISSUE TITLE
Expose signature in `SignedCertificateTimestamp` interface

### ISSUE THREAD

**Issue by tetsuo-cpp** [pyca/cryptography#7198]
Hey there. Firstly, thanks so much for building this excellent library. It's been a pleasure to use.

One thing I noticed is that [the SCT interface](https://github.com/pyca/cryptography/blob/main/src/cryptography/x509/certificate_transparency.py#L22) doesn't expose the underlying signature. As part of [sigstore-python](https://github.com/trailofbits/sigstore-python), we'd like to verify the signature (assembling the digitally signed struct and using the signing certificate to check it against the supplied the signature). This would be a lot easier if we could access it via a member called `signature` or similar.

It seems that the signature even gets extracted in the Rust code [here](https://github.com/pyca/cryptography/blob/main/src/rust/src/x509/sct.rs#L143), so it seems like it should be possible to pass it into the SCT type and expose it.

Is there any reason that this might be a bad idea? If you're open to this, I'd be keen to follow up with a PR.

**Comment by reaperhulk** [comment]
Adding a signature getter would definitely be useful. We'll be happy to review a PR. Do you also need signature algorithm?

**Comment by tetsuo-cpp** [comment]
> Adding a signature getter would definitely be useful. We'll be happy to review a PR. Do you also need signature algorithm?

Yeah I think I may as well add a getter for the algorithm while I'm at it.

**Comment by alex** [comment]
done in https://github.com/pyca/cryptography/commit/b9f4ca35b55205b0a24c6b6056eb2877fa4bed4c
