### ISSUE TITLE
Fernet has no attribute encrypt

### ISSUE THREAD

**Issue by Krizsan0596** [pyca/cryptography#7232]
I was trying to encrypt a file with fernet and it was working perfectly until fernet started giving me an error: 
`AttributeError: '_io.TextIOWrapper' object has no attribute 'encrypt'`
Relevant script:
`key = Fernet.generate_key()
f = Fernet(key)
with open(file, "wb") as file_out:
        file_out.write(f.encrypt(data))`
I am using Python 3.8.10, cryptography 36.0.0, cffi 1.15.0, pip 22.0.4, setuptools 45.2.0
I installed cryptography with pip

**Comment by alex** [comment]
Your script doesn't actually reproduce this issue.

However, from the error message it's clear that what's happening is that you have over-ridden the `f` variable, which is supposed to contain the `Fernet` instance, with some other object. Likely a file.

Perhaps you did something like:

```python
f = Fernet(...)
with open(path) as f:
    # ...
```

**Comment by Krizsan0596** [comment]
`from cryptography.fernet import Fernet
import os
files = []

for file in os.listdir():
    if file == os.path.basename(__file__)":
        continue
    if os.path.isfile(file):
        files.append(file)

if os.path.exists("key.key"):
    key = open("key.key", "rb").read()
else:
    key = Fernet.generate_key()
    open("key.key", "wb").write(key)

for file in files:
    f = Fernet(key)
    with open(file, "rb") as file_in:
        data = file_in.read()
    with open(file, "wb") as file_out:
        file_out.write(f.encrypt(data))`
Here is the entire code, giving me the error.

**Comment by alex** [comment]
This code runs fine for me.
