### ISSUE TITLE
Remove verify_interface

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#7278]
Now that `register_interface` is gone we have no use for `verify_interface`, but https://github.com/aws/aws-encryption-sdk-python/issues/464 is a blocker for removing it.

**Comment by alex** [comment]
[Link for metrics](https://pepy.tech/project/aws-encryption-sdk?versions=3.1.1&versions=*).

gap between them is the installs that would be impacted when this happens

**Comment by reaperhulk** [comment]
Digging into this again, it appears they've released versions of v1 and v2 that pinned cryptography versions (concurrent with deprecating them). The vast majority of v3 downloads are on 3.1.1 (the version that removes verify_interface). This is not true of v1 and v2 users, but based on the last 8 months it appears those users simply do not upgrade since very few are on the final v1/v2 releases anyway.

I propose we do this in 40.

**Comment by alex** [comment]
Fine with me, want to submit a PR for it?
