### ISSUE TITLE
Can't import cryptography in Autodesk Maya

### ISSUE THREAD

**Issue by MasterQuazar** [pyca/cryptography#7302]
Hello guys, hope you can help me, I've tried so hard to find the solution but it didn't worked.

I'm currently working on an important scripting project on autodesk maya 2022, and for this one I need to use cryptography, and more than that some of the packages that I've installed (PyGithub) are also using cryptography, so I can't do anything without cryptography.

If i'm trying to import cryptography alone (import cryptography) it works
but if I'm trying to use a script that use the ._rust folder inside cryptography/hazmat/bindings folder (like paddings.py) It doesn't work and because of that for instance I can't use "from cryptography.fernet import Fernet" 'cause this script is also using padding.py

I've got the error "DLL load failed: module could not be found"

This error happen also if I'm trying to use ffi from _openssl, so basically I can't do anything with cryptography in maya.

I know that their environment is a bit different (I don't really get how) but I really need to understand what I'm doing wrong and what I should do to fix the issue.

Thank you in advance for any help.

**Comment by alex** [comment]
We don't know anything about maya autodesk, so you're going to have to give us more context.

For example, how did you install cryptography?

**Comment by MasterQuazar** [comment]
> We don't know anything about maya autodesk, so you're going to have to give us more context.
> 
> For example, how did you install cryptography?

Basically I think Maya has its python environment and instead of python pip, to install package we have to use mayapy -m pip install but I got a dll on all pyd files, _rust, _openssl

**Comment by alex** [comment]
No, the output from the terminal when you are installing.

**Comment by reaperhulk** [comment]
Please provide it using `-v` (e.g. `mayapy -m pip install -v cryptography`).

**Comment by MasterQuazar** [comment]
> Please provide it using `-v` (e.g. `mayapy -m pip install -v cryptography`).

What does it change

**Comment by alex** [comment]
`-v` provides more verbose output to assist in debugging

**Comment by MasterQuazar** [comment]
[cryptography_error.txt](https://github.com/pyca/cryptography/files/8819506/cryptography_error.txt)

I receive this message

**Comment by reaperhulk** [comment]
Okay your installation thinks that `cryptography-37.0.2-cp36-abi3-win_amd64` is a valid wheel for your platform (which it hypothetically is) and it then successfully installs it. Normally this would work fine, but it would appear the mayapy is special.

What happens if you `import cryptography.hazmat.bindings._rust`? Do you get a `ModuleNotFoundError`? What are the file names you see for the _rust and _openssl pyds if you look inside the cryptography/hazmat/bindings folder inside your pip user install?

**Comment by MasterQuazar** [comment]
> Okay your installation thinks that `cryptography-37.0.2-cp36-abi3-win_amd64` is a valid wheel for your platform (which it hypothetically is) and it then successfully installs it. Normally this would work fine, but it would appear the mayapy is special.
> 
> What happens if you `import cryptography.hazmat.bindings._rust`? Do you get a `ModuleNotFoundError`? What are the file names you see for the _rust and _openssl pyds if you look inside the cryptography/hazmat/bindings folder inside your pip user install?

I got "Import Error: DLL load failed, the module could not be found"
![image](https://user-images.githubusercontent.com/102995191/171621203-8e043662-db21-442c-9a05-600e5bb73534.png)
![image](https://user-images.githubusercontent.com/102995191/171621237-a67f6d0d-2d34-4ca7-ab79-5fe37973a2bb.png)

**Comment by MasterQuazar** [comment]
> > Okay your installation thinks that `cryptography-37.0.2-cp36-abi3-win_amd64` is a valid wheel for your platform (which it hypothetically is) and it then successfully installs it. Normally this would work fine, but it would appear the mayapy is special.
> > What happens if you `import cryptography.hazmat.bindings._rust`? Do you get a `ModuleNotFoundError`? What are the file names you see for the _rust and _openssl pyds if you look inside the cryptography/hazmat/bindings folder inside your pip user install?
> 
> I got "Import Error: DLL load failed, the module could not be found" ![image](https://user-images.githubusercontent.com/102995191/171621203-8e043662-db21-442c-9a05-600e5bb73534.png) ![image](https://user-images.githubusercontent.com/102995191/171621237-a67f6d0d-2d34-4ca7-ab79-5fe37973a2bb.png)

the first picture is the content of the _rust folder, and the second one is the content of the bindings folder where there is the _rust folder

**Comment by alex** [comment]
Unfortunately we're at a bit of an impasse here, I don't think any of us know enough about maya to really debug further.

I'd encourage you to reach out to their team to see if they have information on installing extension modules in their environment.
