### ISSUE TITLE
I hope this is the place.....   docker v non-docker installation

### ISSUE THREAD

**Issue by SgtErnestBilko** [pyca/cryptography#7329]
I have seen a few posts on this site but i remain a bit confused.

I have a pi4 running 32bit bullseye.  I have a Django project using channels-redis.

Cryptography is a dependancy of channels and it installs from a wheel without a problem in a python venv.

When I try to install through requirements.txt in a docker Crytography wants to be "made" and I get the 'rust' error.

I am running the same version of bullseye, python and pip in both Docker and venv locations.

I have used the 'apt-get -y install build-essential libssl-dev libffi-dev python3-dev cargo' in Dockerfile 
workaround (thank you [tillsteinbach](https://github.com/tillsteinbach) https://github.com/pyca/cryptography/issues/6347

It's a pain because it takes so long but this can be mitigated by putting the run command early in a Dockerfile.....  I am just curious know why if OS, python and pip are the same in both environments does a 'Docker pip' want to 'make' cryptography and a 'venv pip' download a wheel ?

Thank you

**Comment by reaperhulk** [comment]
We don't provide 32-bit arm wheels, so any wheel obtained would either be from a local cache from previous builds or via alternate python wheel repositories (like `piwheels.org`, which is used by default in raspbian). The docker build environment likely isn't looking at `piwheels.org` (unlike your venv), resulting in it needing to build the package.

**Comment by SgtErnestBilko** [comment]
Thank you very much for you prompt response.  Can I prevail upon your kindness for one more minute ?

Is there a way (that you know of) that I can make the docker build environment look for crytpography in pinwheels.org ?

Thank you

**Comment by reaperhulk** [comment]
Take a look at `--index-url` or `--extra-index-url` in the `pip install` docs.

**Comment by SgtErnestBilko** [comment]
Job done !!!!

in Dockerfile......
RUN pip install --index-url=https://www.piwheels.org/simple --no-cache-dir -r requirements.txt

Thank you very much.   That's saved me hours and I really appreciate your time.
