### ISSUE TITLE
Be able to save objects into files

### ISSUE THREAD

**Issue by harmin-parra** [pyca/cryptography#7330]
Be able to save objects into files in both PEM and DER format when applicable.

Having methods like:

```
cryptography.hazmat.primitives.serialization.pkcs12.save_pkcs12
cryptography.x509.save_pem_x509_certificate
cryptography.x509.save_der_x509_certificate
cryptography.x509.save_pem_x509_crl
cryptography.x509.save_der_x509_crl
etc.
```

**Comment by reaperhulk** [comment]
We have extensive documentation describing how to do this already. Example for certificate: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.public_bytes (and similar for every other x509 object). You can also serialize pkcs12 with https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.pkcs12.serialize_key_and_certificates
