### ISSUE TITLE
Add SSL_CTX_set1_sigalgs_list() binding.

### ISSUE THREAD

**Issue by Jean-Daniel** [pyca/cryptography#7336]
For the same reason as it was added some years ago (https://github.com/pyca/cryptography/issues/4006) `SSL_CTX_set1_sigalgs_list()` is required to control how to connect to a TLS 1.3 server.

And it is required to implements https://github.com/pyca/pyopenssl/issues/848

As TLS 1.3 is becoming common, this is even more important to be able to access this function than before.

Could it be possible to revert https://github.com/pyca/cryptography/pull/6473

**Comment by alex** [comment]
We'd accept a patch reverting that PR.
