### ISSUE TITLE
ECDSA signature verification is not working

### ISSUE THREAD

**Issue by wasifferoze** [pyca/cryptography#7341]
Hi, I was using ECDSA and wanted to verify the signature, however, it was not working. Then I tried to run the example code provided in the documentation which is also not working. Do you know, is there a bug in ECDSA signature verification? I have attached to sample run code in the screenshot.
![ECDSA](https://user-images.githubusercontent.com/25391782/174425804-9ff2dc72-b161-47ba-a8f0-7841ab4e8828.PNG)

**Comment by reaperhulk** [comment]
The verify function raises an exception for invalid signature and otherwise returns nothing. The screenshot doesn’t appear to show a problem, so if you still believe there is an issue please provide a reproducer.

**Comment by alex** [comment]
Your screenshot shows ECDSA signatures working correctly.

**Comment by wasifferoze** [comment]
> The verify function raises an exception for invalid signature and otherwise returns nothing. The screenshot doesn’t appear to show a problem, so if you still believe there is an issue please provide a reproducer.

should not it return True or something? If I want to check it is a valid signature, how can I use it in the conditional statement?

**Comment by alex** [comment]
It raises an exception on an invalid signature.

**Comment by wasifferoze** [comment]
I have public key generated from this code, and want to verify signature how can I do please help

`sender_public_key = sender_public_key.public_bytes(encoding=serialization.Encoding.DER,format=serialization.PublicFormat.SubjectPublicKeyInfo)
sender_public_key.verify(self.signature, sign_result, ec.ECDSA(utils.Prehashed(hashes.SHA256())))`

but it says
 _AttributeError: 'bytes' object has no attribute 'verify'_

**Comment by alex** [comment]
public_bytes returns the DER encoded public key. Why would it have a verify method? You seem to be struggling with basic Python functionality more than cryptography, so I would recommend you spend more time getting familiar with Python.

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#elliptic-curve-signature-algorithms has examples of both signing and verification.

**Comment by wasifferoze** [comment]
I understand we can sign and verify with EC key object, however, I have only this DER encoded public key. The above code was reproducing the key address. My problem is I have a string, signature and The public key of the sender, encoded with DER

**Comment by alex** [comment]
That page also describes how to load keys: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#key-loading -- though it only has PEM examples, there are also equivalent DER functions.

**Comment by wasifferoze** [comment]
Thank you. It works
