### ISSUE TITLE
ImportError: cannot import name 'generate_pkcs12' from 'cryptography.hazmat.primitives.serialization.pkcs12'

### ISSUE THREAD

**Issue by JonhSilver** [pyca/cryptography#7359]
ImportError: cannot import name 'generate_pkcs12' from 'cryptography.hazmat.primitives.serialization.pkcs12'

How do/can I generate a PKCS#12 file using python and the cryptography module having der (binary, need convert to pem) certificate and private key?

**Comment by reaperhulk** [comment]
Where did you get generate_pkcs12? Was that just a guess? As documented, you want to use https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.pkcs12.serialize_key_and_certificates
