### ISSUE TITLE
Question: can we use aes256 by simply using key size of 32 bytes for  Cipher.AES(key) from hazmat primitive ciphers

### ISSUE THREAD

**Issue by evil-user** [pyca/cryptography#7376]
secret_key = // secret
            password = getpass.getpass('Enter Password to protect secret key:')
            password = bytes(password,'utf-8')
            salt = os.urandom(16)
            iv = os.urandom(16)
            key = argon2.low_level.hash_secret_raw(password, salt, 12, 2097152, 4, 32, argon2.low_level.Type.ID, 19)
            cipher = Cipher(algorithms.AES(key), modes.CFB(iv))
            encryptor = cipher.encryptor()
            ciphertext = encryptor.update(secret_key) + encryptor.finalize()

          in above code key variable will have 32 bytes long key will it automatically be using AES256? I planning to use this for 
         developing a quantum resistant  crypto solution where only aes256 is secure.

**Comment by alex** [comment]
Yes, when a 32-byte key is provided then `AES` is AES-256.

**Comment by evil-user** [comment]
thank you.
