### ISSUE TITLE
Question: in class cryptography.hazmat.primitives.ciphers.CipherContext interface can update_into(data, buf)[ used to process large files?

### ISSUE THREAD

**Issue by evil-user** [pyca/cryptography#7377]
in classcryptography.hazmat.primitives.ciphers.CipherContext interface can update_into(data, buf) be used to process large files by splitting a large file into small chunks and allocating a small buffer and encrypting data in small chunks. i dont want to upload entire large file into memory and instead split and encrypt for security reasons.

i am wondering how to implement it using cryptography library ( i dont know if it is possible or not ) , any clues/hints will be greatly appreciated .

i used these docs https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#algorithms for reference.

**Comment by alex** [comment]
Yes, update (and update into) can be called repeatedly to chunk data up.

**Comment by evil-user** [comment]
thank you
