### ISSUE TITLE
Include Rust version in DEBUG ASSISTENCE message?

### ISSUE THREAD

**Issue by hoodmane** [pyca/cryptography#7381]
I'm not sure what the best way to do this is but it seems like it would be helpful to include the output of `rustc -V` in the DEBUG ASSISTENCE.

**Comment by alex** [comment]
I think we'd be happy to accept a patch doing this. I think we want something roughly like https://github.com/pypa/pip/blob/main/src/pip/_internal/network/session.py#L179-L186

**Comment by hoodmane** [comment]
Okay I'll open a PR.
