### ISSUE TITLE
Why do we need private key as signer when using PKCS7SignatureBuilder() ?

### ISSUE THREAD

**Issue by vicentefb** [pyca/cryptography#7405]
https://github.com/pyca/cryptography/blob/7ad17d819affb996c6681c6aac57e43184c54865/src/cryptography/hazmat/primitives/serialization/pkcs7.py#L84

Not an expert in signatures but why do we need to provide the private key in this process and not just the certificate ?

**Comment by alex** [comment]
Because the certificate only contains the public key, and computing a signature requires a private key.

**Comment by vicentefb** [comment]
Ok, thanks for the clarification! On another note, is this FAQ outdated or wrong: https://pyjwt.readthedocs.io/en/stable/faq.html ? 

It's using the cryptography module to extract a private key from a X509 certificate object. Doesn't this defeat the purpose of security in a private key ?

**Comment by alex** [comment]
That FAQ is for pyjwt, not pyca/cryptography. I don't see how that could ever have been accurate though, there's never been a `private_key` method on a certificate, because certificates do not contain a pirvate key.
