### ISSUE TITLE
RFE: remove password length limit on `OpenSSH` encoded private keys

### ISSUE THREAD

**Issue by Ajpantuso** [pyca/cryptography#7436]
### Summary

The current implementation of `SSH` serialization enforces a [maximum password length](https://github.com/pyca/cryptography/blob/main/src/cryptography/hazmat/primitives/serialization/ssh.py#L56) of 72 characters and [references](https://github.com/pyca/cryptography/blob/28934d16fcad8de97284483aeec5d4c2fffab30d/src/cryptography/hazmat/primitives/serialization/ssh.py#L614-L615) the OpenSSH format as a source.

The [OpenSSH format](https://github.com/openssh/openssh-portable/blob/eb679e2959bdb15454eb94751930eb4c9110da94/PROTOCOL.key) however specifies no such restriction since the passphrase is never stored and is supplied directly to the underlying KDF implementation.

`bcrypt 3.1.5`, required by `cryptography`, does not specify any requirements for the password either (besides [non-zero length](https://github.com/pyca/bcrypt/blob/3.1.5/src/_csrc/bcrypt_pbkdf.c)).

Originally reported [here](https://github.com/ansible-collections/community.crypto/issues/492)

**Comment by alex** [comment]
Huh. The original bcrypt algorithmis limited to 72 characters, but this limitation does not apply to bcrypt_pbkdf2 (which is what's used in the OpenSSH format). It looks like this limitation was enforced by accident.

We'd be happy to accept a PR with tests that removed this limitation.

**Comment by 4wk-** [comment]
Hi, I'm the OP of the Ansible's issue. I'm afraid removing this limitation is out of my reach :/
I hope a well-meaning soul will be able a submit a PR someday! 🥇 Regards,
