### ISSUE TITLE
Question: How to derive multiple keys from a shared secret  using hkdf an example would be helpful 

### ISSUE THREAD

**Issue by evil-user** [pyca/cryptography#7438]
is there a simple way to derive multiple keys from a shared secret using hkdf using cryptography pkg. In cryptodome we can easy do it using : -

from Crypto.Protocol.KDF import HKDF
from Crypto.Hash import SHA512
from Crypto.Random import get_random_bytes

salt = get_random_bytes(16)
key1, key2 = HKDF(master_secret, 32, salt, SHA512, 2)

is there a similar simple way. i checked cryptography documentation for examples however it had only examples to derive a single key from shared secret.

**Comment by alex** [comment]
I don't know what pycryptodome is doing behind the scene, but almost certainly its just generarting 64 bytes of output and splitting it into two. That can trivially be done with our API and then slicing the resulting bytes.

**Comment by evil-user** [comment]
Thank you
