### ISSUE TITLE
MultiFernet save in file

### ISSUE THREAD

**Issue by majidpeidaei** [pyca/cryptography#7443]
I need help
for example we invent 3 keys MultiFernet
now we need these existing keys in another python file
now how can we save these keys in a file for later use?

**Comment by alex** [comment]
Fernet keys, as generated by `Fernet.generate_key()` are simply strings, you can save them in whatever serialization format you like.

**Comment by majidpeidaei** [comment]
no problem with one key but there is a problem with MultiFernet, I couldn't do it :-(
Do you have a simple example?

**Comment by alex** [comment]
You're going to have to be more specific, what does "couldn't do it" mean?

A simple Python example:

```
keys = [Fernet.generate_key() for _ in range(3)]
with open("mykeys", "w") as f:
    f.write(json.dumps(keys))

with open("mykeys") as f:
    keys_from_file = json.load(f)

f = MultiFernet([Fernet(k) for k in keys_from_file])
```
