### ISSUE TITLE
in x509 ASN.1 serial_number is an integer, not a 32 bit int

### ISSUE THREAD

**Issue by markgamache** [pyca/cryptography#7456]
The code breaks the serial_number by making it a 32 bit int.  Most things just use hex to avoid the need for a big int. Please do the needful.

**Comment by alex** [comment]
I do not understand what you mean by this. There is no limitation that serial_number be 32-bits anywhere in the code to my knowledge.

**Comment by reaperhulk** [comment]
We even have generation methods that create a 20 octet serial.

**Comment by markgamache** [comment]
I clearly don't understand python number types and this is on me. Everything I've read suggested int in python meant a signed 32 bit int.  After digging more deeply, I see that the size is unlimited in P3.

theCert.serial_number
509556932955659383612042049286273944250011118616
type(theCert.serial_number)
<class 'int'>
    denominator: <attribute 'denominator' of 'int' objects>
    imag: <attribute 'imag' of 'int' objects>
    numerator: <attribute 'numerator' of 'int' objects>
    real: <attribute 'real' of 'int' objects>

as hex  594152B8477E5ABF0C6A4EB41A9DB5E776846C18
159 bit
________________________________
