### ISSUE TITLE
project dependencies in pyproject.toml out of sync with setup.cfg

### ISSUE THREAD

**Issue by tim-mitchell** [pyca/cryptography#7466]
The setup.cfg on master has an install_requires section with a comment saying it should be kept in sync with pyproject.toml

https://github.com/pyca/cryptography/blob/79bd18305955b3ee3c46c77de1fadccb3aacba84/setup.cfg#L47

however there is no corresponding project dependencies listed there.  I would expect to see
```
[project]
dependencies = [
    "cffi >=1.12",
]
``
in pyproject.toml

**Comment by alex** [comment]
That comment refers to keeping it in sync with:

```
[build-system]
requires = [...]
```

**Comment by tim-mitchell** [comment]
[build-system] requires is what you need to build cryptography.  install_requires is what a packages need to be present to run cryptography.  They are not the same thing

If I'm wrong they are still out of sync, because the lists are currently different.

**Comment by alex** [comment]
You asked about the comment, and I'm explaining what it exists to remind us to do.

I'm aware that `build-system` and `install_requires` are not the same. But there's no need to duplicate the `setup.cfg` value into `pyproject.toml`, `setuptools` correctly respects the value in `setup.cfg.`

**Comment by tim-mitchell** [comment]
ok - so your comment confuses me - glad it works for you!
