### ISSUE TITLE
cffi is missing when cryptography is installed using poetry

### ISSUE THREAD

**Issue by dimaqq** [pyca/cryptography#7467]
Possible upstream: https://github.com/python-poetry/poetry/issues/6102

`python -c 'from cryptography.hazmat.primitives.ciphers.aead import AESGCM'`

Fails with:
```py
    from cryptography.hazmat.backends.openssl import aead
  File ...
    from cryptography.hazmat.backends.openssl.backend import backend
  File ...
    from cryptography.hazmat.bindings.openssl import binding
  File ...
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

When `cryptography` is a dep in a poetry project. `cffi` is missing.

If `cryptography` is installed using `pip`, then `cffi` is installed, and the code above works.

**Comment by reaperhulk** [comment]
This issue, if it exists, is unlikely to be a cryptography issue, but rather a poetry one. That said, it also appears from the linked issue that upstream needs details as they are unable to reproduce.
