### ISSUE TITLE
Cannot load x25519 certificate example from RFC 

### ISSUE THREAD

**Issue by vlaci** [pyca/cryptography#7472]
I wanted to load the example X25519 certificate from [RFC 8410]( https://datatracker.ietf.org/doc/html/rfc8410#section-10.2) (which defines X25519) without success:

```python
#!/usr/bin/env python
from cryptography import x509


pem = b"""-----BEGIN CERTIFICATE-----
MIIBLDCB36ADAgECAghWAUdKKo3DMDAFBgMrZXAwGTEXMBUGA1UEAwwOSUVURiBUZX
N0IERlbW8wHhcNMTYwODAxMTIxOTI0WhcNNDAxMjMxMjM1OTU5WjAZMRcwFQYDVQQD
DA5JRVRGIFRlc3QgRGVtbzAqMAUGAytlbgMhAIUg8AmJMKdUdIt93LQ+91oNvzoNJj
ga9OukqY6qm05qo0UwQzAPBgNVHRMBAf8EBTADAQEAMA4GA1UdDwEBAAQEAwIDCDAg
BgNVHQ4BAQAEFgQUmx9e7e0EM4Xk97xiPFl1uQvIuzswBQYDK2VwA0EAryMB/t3J5v
/BzKc9dNZIpDmAgs3babFOTQbs+BolzlDUwsPrdGxO3YNGhW7Ibz3OGhhlxXrCe1Cg
w1AH9efZBw==
-----END CERTIFICATE-----"""

x509.load_pem_x509_certificate(pem)
```

The above code fails with this error:

```
Traceback (most recent call last):
  File "/tmp/tmp.5IH5of1M9C/test_x25519.py", line 18, in <module>
    cryptography.x509.load_pem_x509_certificate(pem)
  File "/tmp/tmp.5IH5of1M9C/.venv/lib/python3.9/site-packages/cryptography/x509/base.py", line 514, in load_pem_x509_certificate
    return rust_x509.load_pem_x509_certificate(data)
ValueError: error parsing asn1 value: ParseError { kind: EncodedDefault, location: ["RawCertificate::tbs_cert", "TbsCertificate::extensions", "1", "Extension::critical"] }
```

This certificate can be loaded by OpenSSL without issue.

---
### Environment:
- Python 3.9.13
- Virtualenv created with `python3 -m venv venv && venv/bin/pip install cryptography==37.0.4`
- Pip freeze output:
```
cffi==1.15.1
cryptography==37.0.4
pycparser==2.21
```

**Comment by alex** [comment]
Well, that's emberassing for the RFC authors. RFC 5280 defines critical as `DEFAULT FALSE`, and the DER specification (ITU something something) clearly says that in DER, default values should _not_ be encoded.

Looking at this cert in [ASN.1 JS](https://lapo.it/asn1js/#MIIBLDCB36ADAgECAghWAUdKKo3DMDAFBgMrZXAwGTEXMBUGA1UEAwwOSUVURiBUZXN0IERlbW8wHhcNMTYwODAxMTIxOTI0WhcNNDAxMjMxMjM1OTU5WjAZMRcwFQYDVQQDDA5JRVRGIFRlc3QgRGVtbzAqMAUGAytlbgMhAIUg8AmJMKdUdIt93LQ-91oNvzoNJjga9OukqY6qm05qo0UwQzAPBgNVHRMBAf8EBTADAQEAMA4GA1UdDwEBAAQEAwIDCDAgBgNVHQ4BAQAEFgQUmx9e7e0EM4Xk97xiPFl1uQvIuzswBQYDK2VwA0EAryMB_t3J5v_BzKc9dNZIpDmAgs3babFOTQbs-BolzlDUwsPrdGxO3YNGhW7Ibz3OGhhlxXrCe1Cgw1AH9efZBw) you can clearly see they did encode the `FALSE` values for critical.

So we are correct to reject this cert and the RFC is wrong to say its a valid cert.

**Comment by alex** [comment]
I'm not familiar with the IETF RFC process, so I've reached out to some friends who are experts to see if this a candidate for an errata.

**Comment by vlaci** [comment]
I guess, the ITU specification you are referencing to is X.690?

> 11.5 Set and sequence components with default value
> The encoding of a set value or sequence value shall not include an encoding for any component value which is equal to its
> default value.

**Comment by alex** [comment]
Yes indeed!

**Comment by alex** [comment]
I have filed an errata on this RFC. It turns out there was an _additional_ errata for a _different_ encoding error. The moral of this story is that even IETF RFC authors use tools which encode invalid certificates!

I'm not sure there's any further action to be taken here.

**Comment by vlaci** [comment]
> I have filed an errata on this RFC. It turns out there was an _additional_ errata for a _different_ encoding error. The moral of this story is that even IETF RFC authors use tools which encode invalid certificates!
> 
> I'm not sure there's any further action to be taken here.

Thank you for all the help :)
