### ISSUE TITLE
Implement TripleSec?

### ISSUE THREAD

**Issue by public** [pyca/cryptography#749]
> TripleSec is a simple to use, open-source triple-paranoid symmetric encryption library 

https://github.com/keybase/triplesec / https://github.com/keybase/python-triplesec / https://keybase.io/triplesec

We need to add

 - [ ] Salsa20
 - [ ] Twofish
 - [ ] SHA-3 / Keccak
 - [ ] Scrypt

to implement this.

**Comment by reaperhulk** [comment]
This is dependent on optional backends becoming a reality so for the moment I'm going to go ahead and close it
