### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by SmartPycg** [pyca/cryptography#7491]
Hi，I failed to build your project due to error: subprocess-exited-with-error

![image](https://user-images.githubusercontent.com/105635378/183792265-a85f42eb-ab8c-491e-8a7c-f757bbfb27e8.png)

I used the following commands in python:3.7 docker：

```
pip install -r dev-requirements.txt
python setup.py install
```

Can you help me？

**Comment by alex** [comment]
What are you trying to do? `pip install cryptography` is generally the correct way to install this package, not git cloning and installing with `setup.py install`.

In any event, please provide _text_ (not a screenshot) of the complete output of running the installation.
