### ISSUE TITLE
Request to remove fernet as it is no longer unmaintained or upgrading fernet's underlying algorithms

### ISSUE THREAD

**Issue by evil-user** [pyca/cryptography#7494]
Fernet specs at https://github.com/fernet/spec/blob/master/Spec.md has been long unmaintained. Moreover there is a lack of active ownership  within project as indicated here https://github.com/fernet/spec/issues/26 and many issues have been long unanswered .

I guess it be better to either replace fernet or upgrade the underlying crypto algorithms like from AES128 to AES256.

**Comment by alex** [comment]
We're not going to remove fernet. It's an entirely stable specification, which has many users.

**Comment by reaperhulk** [comment]
It is true that the Fernet spec is not maintained, but the spec itself is still secure and widely used. The continued and justifiable existence of fernet does not preclude other things being added if appropriate.

**Comment by evil-user** [comment]
sorry @alex @reaperhulk i thought fernet wasn't popular, it was a mistake.
