### ISSUE TITLE
Question: in class classcryptography.hazmat.primitives.hmac.HMAC(key, algorithm) can update() used to repeatedly chunk data

### ISSUE THREAD

**Issue by evil-user** [pyca/cryptography#7497]
in classcryptography.hazmat.primitives.hmac.HMAC(key, algorithm) can update(msg) be used to process large files by splitting a large file into small chunks and allocating a small buffer and HMACing data in small chunks. i dont want to upload entire large file into memory and instead split and process for security reasons.

i used these docs https://cryptography.io/en/latest/hazmat/primitives/mac/hmac/ for reference.

**Comment by alex** [comment]
Yes, `update()` can be called repeatedly with small chunks to avoid holding the entire contents in memory at once.
