### ISSUE TITLE
Suggestion: Promote SSH Keys handling to first class

### ISSUE THREAD

**Issue by lowercase00** [pyca/cryptography#7501]
Currently SSH Key handling methods are mostly considered `hazard materials` in the `hazmat` module.
This leads to a lot of boilerplate code to get a key pair.

It would be great to have SSH Keys as first class citizens, promoted to the Recipes layer, like Fernet is.
The basic parameters I found so far are:
- Public Exponent
- Key Size (this could be restricted to 2048 minimum)
- Encoding
- Format

With sane defaults (public exponent = 65537, key_size = 2048, encoding = "OpenSSH", format = "OpenSSH") it would be possible to make a recipe with the most basic functionality like: `generate_key_pair`, `infer_public_key_from_private_key`, `validate_key` and others.

I would be happy to contribute to this, I have written a couple of recipes for personal use, but would need help to ensure reduced risk of safety issues.

**Comment by reaperhulk** [comment]
Thanks for the proposal, but unfortunately public exponent and key size are only parameters for **some** types of SSH keys. An SSH key can be many different algorithms, including RSA, DSA, ECDSA, and ed25519. The correct choice is dependent upon your interoperability (and potentially compliance) needs. Best practice would be to use ed25519, which has no parameters, but whether or not that can work is environment specific. This make a recipe API difficult if not impossible, so for now we'll be marking this as wontfix.
