### ISSUE TITLE
Feature Request - Add Encryption/Decryption mechanism for ECC

### ISSUE THREAD

**Issue by abhishekbisht1429** [pyca/cryptography#7504]
I want to encrypt a message using elliptic curve cryptography, however, I am unable to find any encrypt and decrypt functions in `ec.py` like in `rsa.py`.

**Comment by reaperhulk** [comment]
ECC does not have direct encrypt/decrypt primitives. Instead you derive a key via ECDH and use that to encrypt under a symmetric key. There are standards for doing this and other libraries have been built on top of this one that implement them. See #4093
