### ISSUE TITLE
Adding GCM-SIV mode for AES

### ISSUE THREAD

**Issue by tasket** [pyca/cryptography#7531]
OpenSSL has recently added a [GCM-SIV mode](https://github.com/openssl/openssl/issues/16721) for AES.  This mode offers nonce-reuse resistance for projects that require safe and repeated use of the same keys (databases, incremental backups, etc.) while maintaining relatively high throughput vs the low throughput of plain SIV mode.

**Comment by reaperhulk** [comment]
We’ll be happy to add this once an openssl release ships with it. Is it planned for 3.1 now? I don’t believe that release has a date yet unfortunately.

**Comment by reaperhulk** [comment]
Looks like this isn't in 3.1.0 so it will (hopefully) be in 3.2.0.

**Comment by reaperhulk** [comment]
We're going to track this in #9795 now that 3.2's release is imminent.
