### ISSUE TITLE
RSA length limitation isn't mentioned in the docs?

### ISSUE THREAD

**Issue by BMaxV** [pyca/cryptography#7566]
Hello everyone,

I'm meddling with forces I don't understand ;) namely, RSA. 

I noticed that RSA doesn't support strings longer than 190 characters? Which is fine, I can split my message up if needed, I was just surprised as that's not menioned in the docs. And the error message just says:

```
.../rsa.py", line 164, in _enc_dec_rsa_pkey_ctx
    raise ValueError("Encryption/decryption failed.")
ValueError: Encryption/decryption failed.
```

Maybe keeping it non-newbie friendly is intentional to stop the said meddling with forces one does not understand, which I can understand.

Below is what I used. I plan to use this as a component object to handle encryption so if it's wrong somehow, don't hold back with critique.

Thank you for your great project! Having this tech available this way is great!

Python 3.8.10 
pip 20.0.2
Cryptography 37.0.4

```
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives import hashes

import cryptography

class CryptoHandler:
    """not complicated, but if there is something wrong, it should
    be easy to switch out and not touch unrelated code."""
    def __init__(self,generate_keys=True):
        if generate_keys:
            self.private_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048)   
            self.public_key=self.private_key.public_key()
            
    def encrypt(self,text):
        my_pad = padding.OAEP(
         mgf=padding.MGF1(algorithm=hashes.SHA256()),
         algorithm=hashes.SHA256(),label=None)
        encrypted=self.public_key.encrypt(text,my_pad)
        return encrypted
    
    def decrypt(self,text):
        if self.private_key!=None:
            my_pad = padding.OAEP(
             mgf=padding.MGF1(algorithm=hashes.SHA256()),
             algorithm=hashes.SHA256(),label=None)
            decrypted=self.private_key.decrypt(text,my_pad)
            return decrypted
        return None

def test():
    print(cryptography.__version__)
    import random
    
    myH=CryptoHandler()
    oldm="hello there"
    m=oldm.encode()
    new_m=myH.encrypt(m)
    real=myH.decrypt(new_m)
    real=real.decode()
    
    print(oldm,real)
    assert oldm==real
    
    strings=["a","b","c"]
    
    c=0
    m=200
    s=""
    while c < m:
        s+=random.choice(strings)
        s2=s.encode()
        try:
            myH.encrypt(s2)
        except ValueError:
            print("failed at",c)
            break
        c+=1
    
if __name__=="__main__":
    test()
```

**Comment by alex** [comment]
RSA encryption is limited to the size of the key (minus a few bytes). So if you have a 2048 bit key you're limited to 256-bytes minus the overhead.

You mention splitting up your message. It sounds like you are describing what is known as "ECB" mode (https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)). This is **not secure**.

The real solution to this is to use a hybrid encryption model: RSA is used to encrypt a new symmetric key, and that symmetric key is used to encrypt arbitrarily long data.

**Comment by BMaxV** [comment]
Cool, I can do that. Thank you for the speedy reply!

Since this was in part about the error message/docs I will not close the issue, but my problem is solved.

**Comment by BMaxV** [comment]
Ok so turns out I can't do that.

As far as I can see, the examples in both

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/x25519/
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dh/

create a shared key that's some byte sequence but that is not compatible with the Fernet from the "safe zone" part of the module.

So I can end up with both parties having a byte sequence that matches and could be used, but I don't know how.

Since this is starting to be properly off topic from the original issue, and since the whole topic is specifically in the "don't touch unless you know what you're doing" section, I don't expect anyone to solve my problem. I just thought I'd let you know that it didn't work and I will have to leave how to do my secure message exchange unsolved for now.

**Comment by reaperhulk** [comment]
You probably want HPKE, which we don’t directly implement at this time. Other libraries exist that use us to implement it though: https://github.com/ctz/hpke-py
