### ISSUE TITLE
copy/deepcopy broken in cryptography 38

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#7587]
Hi,

Since cryptography 38 it is no longer possible to use copy/deepcopy with some (many?) cryptography objects. I assume that this is due to them being ported to Rust (which is not at all mentioned in the changelog, btw :-(). One example I have found is `ObjectIdentifier`, but I assume there may be others:

```python
>>> import copy
>>> from cryptography import x509
>>> copy.copy(x509.NameOID.COMMON_NAME)
...
TypeError: cannot pickle 'builtins.ObjectIdentifier' object
>>> copy.deepcopy(x509.NameOID.COMMON_NAME)
...
TypeError: cannot pickle 'builtins.ObjectIdentifier' object
```

This can easily cause problems in Python code:

```python
>>> class Test:
...     def __init__(self, oid):
...         self.oid = oid
>>> copy.deepcopy(Test(x509.NameOID.COMMON_NAME))
...
TypeError: cannot pickle 'builtins.ObjectIdentifier' object
>>> copy.deepcopy({x509.NameOID.COMMON_NAME: 'CommonName'})
...
TypeError: cannot pickle 'builtins.ObjectIdentifier' object
```

This works in cryptography==37.0.4:

```
>>> copy.deepcopy({x509.NameOID.COMMON_NAME: 'CommonName'})
{<ObjectIdentifier(oid=2.5.4.3, name=commonName)>: 'CommonName'}
```

The [copy](https://docs.python.org/3/library/copy.html) module says that implementing __copy__/__deepcopy__ would fix the issue (so no, no pickle required).

Can we implement this again? I'm not a Rust developer, but I'm willing to try of course.

**Comment by alex** [comment]
Yes, we'd be happy to take a patch reimplementing `__deepcopy__` for `ObjectIdentifier`. Since OIDs are immutable the implementation is pretty simple, you can see the same pattern in `src/rust/src/x509/certificate.rs` at line 119.
