### ISSUE TITLE
add minimum version pin for `pyOpenSSL`

### ISSUE THREAD

**Issue by thesuperzapper** [pyca/cryptography#7603]
We can prevent people from accidentally using a version of `pyOpenSSL` that is too old for their version of `cryptography` by introducing a minimum (but not upper) bound in our `install_requires`.

This will prevent issues like:
- https://github.com/pyca/cryptography/issues/7134
- https://github.com/pyca/cryptography/issues/7126

---

For example, we could add `pyOpenSSL>=22.0.0` to [`install_requires`](https://github.com/pyca/cryptography/blob/d6382bb0ceac8927efbbf2878d72b8554c144ef6/setup.cfg#L47-L48) for the current release, what are your thoughts?

**Comment by lerminou** [comment]
I agree, My fresh server 
(redhat 8.6 / Openssl 1.1.1-k-7)
installs the new cryptography  version 38.0.1 released 5 days ago.
and i have the same error.

**Comment by alex** [comment]
I don't believe this will work: a) It will create a circular dependency, b) cryptography doesn't depend on pyOpenSSL!

Unfortunately what we really did is a new pip feature to be able to declare constraints that aren't actually dependencies.

**Comment by thesuperzapper** [comment]
@alex sorry I got all mixed up, I think I raised this issue on the wrong repo? 

You are saying that we instead should be pinning a MAXIMUM version of `cryptography` within the [`install_requires` of `pyOpenSSL`](https://github.com/pyca/pyopenssl/blob/a145fc3bc6d2e943434beb2f04bbf9b18930296f/setup.py#L99)?
