### ISSUE TITLE
AESSIV Encryption/Decryption fails if empty data is passed

### ISSUE THREAD

**Issue by arunanshub** [pyca/cryptography#7613]
## Issue description

If an empty byte string is passed to `data` parameter of methods `encrypt` and `decrypt` of `AESSIV`, operation fails with `InternalError`.

## Steps to reproduce bug

```python
from cryptography.hazmat.primitives.ciphers import aead

key = bytes(32)
data = b""

cipher = aead.AESSIV(key)
output = cipher.encrypt(data, None)  # raises `InternalError`
```

## cryptography installation

cryptography is installed via poetry with version constraint >=35.0.0:

```toml
[tool.poetry.dependencies]
python = "^3.8"
cryptography = ">=35.0.0"
```

## Required Version numbers

- `pip` - 22.2.2
- `cffi` - 1.15.1
- `cryptography` - 38.0.1
- `setuptools` - 65.3.0

**Comment by reaperhulk** [comment]
Thanks for the report, we should definitely not `InternalError` here. I don't really think an empty encryption under SIV has any meaning so we probably should just disallow zero bytes as a `ValueError`.

**Comment by arunanshub** [comment]
Wouldn't it be valid to just return an empty byte string as output? It is consistent with other modes like AESCCM.

**Comment by reaperhulk** [comment]
OpenSSL itself is erroring when trying to do this with zero bytes, so either we're calling it wrong (possible, but unlikely) or it does not currently support allowing zero byte pt. It wouldn't be an empty output since it should have a 16 byte output that is effectively the MAC (the SIV).

**Comment by arunanshub** [comment]
> Wouldn't it be valid to just return an empty byte string as output? It is consistent with other modes like AESCCM.

You're right, @reaperhulk. The cipher is supposed to return the MAC tag. In fact, `Cryptodome` does that too, instead of erroring out:

```python
from Cryptodome.Cipher import AES

key = bytes(32)
cipher = AES.new(key, AES.MODE_SIV)
output, mac_tag = cipher.encrypt_and_digest(data)

print(output2, mac_tag)
```

I'm not sure about the handling of OpenSSL error. It is preferable to return just the MAC tag, if OpenSSL allows that.

**Comment by reaperhulk** [comment]
OpenSSL does not currently support this at all. This is inconsistent with their other AEADs, so we could try raising an issue with them, but it's not evident that they think there's a useful reason for this to work. Regardless, for now we'll need to make this a ValueError on cryptography even if they do decide to ultimately fix it.
