### ISSUE TITLE
Adobe Acrobat Reader can't open PKCS#12 file with correct password

### ISSUE THREAD

**Issue by PeterTillema** [pyca/cryptography#7614]
Heya! I'm using this library to generate certificates, but I'm having trouble with it, so let me explain the steps I take.

1. Create a private key with a given password
```python
key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
key_bytes = key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.TraditionalOpenSSL,
    encryption_algorithm=serialization.BestAvailableEncryption(
        password.encode('utf-8')
    )
)
# save the private key to a file
```

2. Create a Certificate Signing Request with some properties:
```python
csr = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([
    x509.NameAttribute(NameOID.COUNTRY_NAME, 'NL'),
    x509.NameAttribute(NameOID.STATE_OR_PROVINCE_NAME, 'AAA'),
    x509.NameAttribute(NameOID.ORGANIZATION_NAME, 'BBB'),
    x509.NameAttribute(NameOID.COMMON_NAME, 'CCC'),
    x509.NameAttribute(NameOID.EMAIL_ADDRESS, 'DDD')
])).sign(key, hashes.SHA256())
csr_bytes = csr.public_bytes(serialization.Encoding.PEM)
# save the crt to a file
```

3. Use XCA to create a certificate. I import the request, then select "Digital Signature" as Key Usage, and "Object Signing" under Netscape. Right after that, the csr is signed, and I export the generated certificate to a file.

4. Load the private key from the file with
```python
key = serialization.load_pem_private_key(
    data,  # file data
    password.encode('utf-8')
)
```

5. Load the certificate from the file with
```python
certificate = x509.load_pem_x509_certificate(data)  # certificate data
```

6. Generate the PKCS#12 with
```python
user_certificate_bytes = pkcs12.serialize_key_and_certificates(
    name=None,
    key=key,
    cert=certificate,
    cas=None,
    encryption_algorithm=serialization.BestAvailableEncryption(
        password.encode('utf-8')
    )
)
```
and export it to a file.

7. Open the PKCS#12 file in Adobe Acrobat Reader via Edit > Preferences > Signatures > Identity & trusted certificates. However, when I now want to import my certificate and filling in the correct password, it says it can't import the certificate, even though the password is 100% correct.

To be clear, when I generate the PKCS#12 file with OpenSSL with ` openssl pkcs12 -export -out XXX.pfx -inkey <private key file> -in <certificate file>`, the import goes without any problem.

I'm not sure where my mistake is, hope you can help!

Also, when dumping the contents of this generated certificate file and a correct one I had laying around, it seems cryptography is using `pbeWithSHA1And3-KeyTripleDES-CBC` as the serialization (?) algorithm, while the correct one had `pbeWithSHA1And40BitRC2-CBC`. Could that be a difference?

**Comment by PeterTillema** [comment]
I'm currently using 37.0.2, which seems to be not enough with the new encryption builder. I will update the package and try to use it, will report later what the results are!

**Comment by reaperhulk** [comment]
Yeah it was added in 38. In 36.0.x+ if you're linked against OpenSSL 3 (which all our wheels are) then it defaults to an HMAC of `SHA256`, which causes compatibility issues for many platforms. This drove the creation of the new `encryption_builder` to restore compatibility by allowing users to choose worse, but more compatible options.

**Comment by PeterTillema** [comment]
I fixed it by using

```python
encryption = (
    PrivateFormat.PKCS12.encryption_builder().
    kdf_rounds(50000).
    key_cert_algorithm(pkcs12.PBES.PBESv1SHA1And3KeyTripleDESCBC).
    hmac_hash(hashes.SHA1()).build(b"my password")
)
```
as suggested in the docs as the encryption algorithm when serializing the private key and certificate. I probably should update my PDF to allow better and newer encryption methods :)
