### ISSUE TITLE
cryptography 38.0.0 Not Compatible with redhat8 

### ISSUE THREAD

**Issue by lerminou** [pyca/cryptography#7617]
Receiving the following error when importing cryptography 38.0.0:
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'.

Downgrading to 36.0.2 solved this issue.

redhat8 is fixed to openssl 1.1.1-k, not openssl 3.0.0 planned for redhat9

every python upgrade is broken, for example using Ansible, https://github.com/ansible/awx/issues/12117

**Comment by alex** [comment]
Did you read the change log? It clearly states that 38 is not compatible
with pyopenssl < 22.0

בתאריך יום ה׳, 15 בספט׳ 2022, 10:56, מאת Nicolas DUBUT ‏<
***@***.***>:

**Comment by lerminou** [comment]
Well I missed this line,

I'm not using pip directly but with the associated RPM.

It seems there is no RPM for [python3-cryptograpĥy 38](http://rpmfind.net/linux/rpm2html/search.php?query=python3-cryptography&submit=Search+...&system=&arch=)
