### ISSUE TITLE
Recommendation on how to do public key encryption for large data

### ISSUE THREAD

**Issue by emin63** [pyca/cryptography#7662]
Is there a recommended way of how to do public key encryption for large data?

The reason I ask is because https://github.com/pyca/cryptography/issues/5685 points out that using the existing primitives for a payload larger than the key size fails and the suggestion is to do a hybrid method where we encrypt a private session key for symmetric encryption. 

Is there a working recipe for how to do that? If not, should I implement something along the lines of https://www.pycryptodome.org/src/examples#encrypt-data-with-rsa and submit a PR for the code or the docs?

I apologize if this seems pedantic. Since the docs at https://cryptography.io/en/latest/hazmat/primitives/ say "This is a “Hazardous Materials” module. You should ONLY use it if you’re 100% absolutely sure that you know what you’re doing because this module is full of land mines, dragons, and dinosaurs with laser guns.", I want to make sure to implement the suggestion correctly.

Thanks.

**Comment by reaperhulk** [comment]
https://github.com/ctz/hpke-py is a good option for hybrid public key based encryption. It implements the HPKE RFC and uses this library as its underlying implementation.

**Comment by alex** [comment]
Yes, HPKE is the best choice.

**Comment by reaperhulk** [comment]
HPKE is indeed a "recipe" type thing that is standardized. We may consider including an implementation in the future, but for now since someone else implemented it and that can be used we haven't prioritized doing it ourselves.
