### ISSUE TITLE
`safety` requires `crypography>=39.0.0` which hasn't been released yet

### ISSUE THREAD

**Issue by figchutney** [pyca/cryptography#7670]
Hello 👋 

The security package [`safety`](https://pypi.org/project/safety/) currently requires `cryptography>=39.0.0` for its check to pass (see screenshot), citing the below reason, with ID `51159`:

> Cryptography 39.0.0 drops support for C library "LibreSSL" < 3.4, as these versions are not receiving security support anymore.

However, [it looks like](https://cryptography.io/en/latest/changelog/) version `39.0.0` is under development and hasn't been released yet.

As far as I can see, the only way around this for now is to ask `safety` to ignore its check on `cryptography`.

Thanks 🙏 

<img width="967" alt="image" src="https://user-images.githubusercontent.com/52138939/193592948-c1ed6570-43cb-4b62-aadc-0e87b620dcd7.png">

(I'm seeing this while using Python `3.10.2`. I've not included other package versions, as I felt it didn't really make sense given the problem is specifically _with_ package versions)

**Comment by alex** [comment]
I don't know what safety is, I suppose you should file this bug with them.

**Comment by figchutney** [comment]
Okie dokie. Re-raised at https://github.com/pyupio/safety/issues/413
