### ISSUE TITLE
When will you release 38.0.2 which updates the openssl  to 3.0.6

### ISSUE THREAD

**Issue by wqh17101** [pyca/cryptography#7749]
Hi,i found that 38.0.2 on pypi is yanked.
When will you release a new one with openssl 3.0.6 to fix vulnerablities of openssl 3.0.5

**Comment by alex** [comment]
Well, we're not going to issue a release that upgrades to 3.0.6, because it contains several significant regressions.

The OpenSSL project will be issuing a 3.0.7 next week, and we'll issue a release upgrading to that on the same day it comes out.

**Comment by reaperhulk** [comment]
We won't. OpenSSL withdrew the 3.0.6 entirely. We will release a 38.0.3 when 3.0.7 is released next week.
