### ISSUE TITLE
How to compute CMAC over a specified bit length of input Message

### ISSUE THREAD

**Issue by sreejithrangarajan** [pyca/cryptography#7751]
NIST SP 800-38B  - Section 6.2 (MAC Generation) suggests input message M of bit length Mlen and specifies the below points in computing the last message block

> If the message length is a positive multiple of the block size, then the message is partitioned into complete blocks. The final block is masked with the first subkey; in other words, the final block in the partition is replaced with the exclusive-OR of the final block with the first subkey. The resulting sequence of blocks is the formatted message. The final block is masked with the first subkey; in other words, the final block in the partition is replaced with the exclusive-OR of the final block with the first subkey. 
The resulting sequence of blocks is the formatted message

> If the message length is not a positive multiple of the block size, then the message is partitioned into complete blocks to the greatest extent possible, i.e., into a sequence of complete blocks followed by a final bit string whose length is less than the block size. A padding string is appended to this final bit string, in particular, a single ‘1’ bit followed by the minimum number of ‘0’ bits, possibly none, that are necessary to form a complete block. The complete final block is masked, as described in the previous bullet, with the second subkey. The resulting sequence of blocks is the formatted message.

Is there a way I can specify the length of message (bits) over which the MAC is to be computed?

At present this is how I calculate the CMAC 
```
from cryptography.hazmat.primitives import cmac
from cryptography.hazmat.primitives.ciphers.algorithms import AES

cipher = cmac.CMAC(AES(key))
cipher.update(message)
cmac_tag = cipher.finalize()
```

I'm using the below versions installed via PIP
```
Python 3.9

cryptography==38.0.1
cffi==1.15.1
setuptools==60.2.0
```

**Comment by alex** [comment]
There's no way to specify a length, the length is automatically computed from the length of the message provided.

**Comment by sreejithrangarajan** [comment]
Hi @alex , Thanks. 

Do you think there is any way I can provide the below test vectors taken from ETSI TS 133 401 V17.3.0 [Annex C - C.2.1](https://www.etsi.org/deliver/etsi_ts/133200_133299/133220/17.03.00_60/ts_133220v170300p.pdf) to the CMAC provided by [cryptography](https://github.com/pyca/cryptography) to have the mentioned output?

```
K = (hex) 2bd6459f 82c5b300 952c4910 4881ff48
M = (hex) 38a6f056 c0000000 33323462 63393840
M = (bin) 00111000 10100110 11110000 01010110 11000000 00000000 00000000 00000000 00110011 00110010 00110100 01100010 01100011 00111001 00111000 01
Mlen = 122

MACT = (hex) 118c6eb8
MACT = (bin) 00010001 10001100 01101110 10111000
```

I have tried the below but the computed mac doesn't match the expected one.

```
from cryptography.hazmat.primitives import cmac
from cryptography.hazmat.primitives.ciphers.algorithms import AES
cipher = cmac.CMAC(AES(bytearray.fromhex('2bd6459f 82c5b300 952c4910 4881ff48')))
cipher.update(bytes.fromhex('38a6f056 c0000000 33323462 63393840'))
cmac_tag = cipher.finalize()
cmac_tag[:4].hex()
```
This gives mac beginning with `c28458e9` instead of the expected `118c6eb8`

**Comment by alex** [comment]
I don't see any of the content you described in the doc you linked. Did you possibly link the wrong reference?

In any event, our APIs don't have support for sub-byte length messages. I'm not even sure OpenSSL supports such a thing -- in general very few tools will be, as there's basically no reason to, any reasonable system simply 0-pads things to be full bytes.

**Comment by reaperhulk** [comment]
We don’t support non-byte integral CMAC. Do you have a use case that requires this? I’m not even sure openssl supports this and it doesn’t seem particularly useful unless you have some very specific compatibility requirements.

**Comment by sreejithrangarajan** [comment]
> I don't see any of the content you described in the doc you linked. Did you possibly link the wrong reference?
> 
> In any event, our APIs don't have support for sub-byte length messages. I'm not even sure OpenSSL supports such a thing -- in general very few tools will be, as there's basically no reason to, any reasonable system simply 0-pads things to be full bytes.

@alex, Oh Sorry, I pasted the wrong link. Here it is: https://www.etsi.org/deliver/etsi_ts/133400_133499/133401/17.03.00_60/ts_133401v170300p.pdf

> We don’t support non-byte integral CMAC. Do you have a use case that requires this? I’m not even sure openssl supports this and it doesn’t seem particularly useful unless you have some very specific compatibility requirements.

@reaperhulk, thanks. I was researching how to implement the 5G integrity algorithm as mentioned in the above specification and came across the CMAC provided by cryptography module. However, I saw that some of the test cases mentioned in this specification were not passing with cryptography. Specifically, the Test Set 1, 2, 4 6 and 7 which are for non-byte aligned cases. For 5G use case the message is byte aligned so I guess it should be okay.

The motivation for raising the issue was because of the Clause 5.5 in NIST SP 800-38B

>For a given block cipher and key, the input to the MAC generation function is a bit string called the message, denoted M. The bit length of Mis denoted Mlen. The value of Mlen is not an essential input for the MAC generation algorithm if the implementation has some other means of identifying the last block in the partition of the message, as discussed in Sec. 6.2. Thus, **in such a case, the computation of the MAC may begin “on-line” before the entire message is available**. In principle, there is no restriction on the lengths of messages. **In practice, however, the system in which CMAC is implemented may restrict the length of the input messages to the MAC generation function**

**Comment by alex** [comment]
Notwithstanding how NIST defines, very few implementations will actually handle non-byte-aligned values.

As far as I can tell, OpenSSL (which we use it) doesn't support it.

Given that this isn't actually required for 5G, can we consider this completed?

**Comment by sreejithrangarajan** [comment]
Yes @alex we can.
