### ISSUE TITLE
Failed to build wheel for cryptography (pyproject.toml)

### ISSUE THREAD

**Issue by joshcangit** [pyca/cryptography#7756]
### Error message
```
Fatal error from pip prevented installation. Full pip output in file:
    /data/data/com.termux/files/home/.local/pipx/logs/cmd_2022-12-11_11.19.09_pip_errors.log

pip failed to build package:
    cryptography

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: failed to prepare thin LTO module: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.6' Reader: 'LLVM 15.0.6')
    error: could not compile `cryptography-rust` due to previous error
    error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path src/rust/Cargo.toml --target aarch64-linux-android --release -v --features 'pyo3/extension-module pyo3/abi3-py36' -- --crate-type cdylib` failed with code 101

Error installing magic-wormhole from spec 'https://github.com/ma
gic-wormhole/magic-wormhole/archive/master.tar.gz'.
```
> Used `pip` to install `cryptography`. `cffi` not installed.
### Packages
- **pip**: `22.3`
- **setuptools**: `65.5.0`
- **wheel**: `0.37.1`

### OpenSSL
`openssl/stable,now 1:3.0.5 aarch64`
```
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
```

### Compilers
`clang/stable,now 15.0.3-1 aarch64`
```
clang version 15.0.3
Target: aarch64-unknown-linux-android64
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin
```

`rust/stable,now 1.64.0 aarch64`
```
cargo 1.64.0
rustc 1.64.0
```

### System
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21941
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.accum.se/mirror/termux.dev/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
12
Kernel build information:
Linux localhost 4.14.113-24706840 #1 SMP PREEMPT Thu Jul 21 14:53:58 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-G973F
```

**Comment by joshcangit** [comment]
Installing `magic-wormhole` requires this package.
Even using `pip install` still failed to build this package.

**Comment by alex** [comment]
https://github.com/pyca/cryptography/issues/7636#issuecomment-1282401889 ran into a similar issue and claimed that `export RUSTFLAGS="-C lto=n"` resolved it. I don't think we understand what causes this, but it likely fixes it for you.

**Comment by joshcangit** [comment]
> https://github.com/pyca/cryptography/issues/7636#issuecomment-1282401889 ran into a similar issue and claimed that `export RUSTFLAGS="-C lto=n"` resolved it. I don't think we understand what causes this, but it likely fixes it for you.

Yes, I did read the error.
I think it was something about thinLTO failing.

**Comment by alex** [comment]
Sure, we can tell it's somehow LTO related, but I don't know what specifically provokes that.

It looks like what you'd get if your rust was emitting LLVM bitcode for a different version than the LLVM version involved in the linking. But that's purely conjecture.

**Comment by avenir2027** [comment]
Upgrading libllvm may solve the problem,I also had a problem with cryptograpgy not being installed,after adding temporary environment variables,it was successfully installed,and I saw the same problem in termux's github projecthttps://github.com/termux/termux-packages/issues/12260

**Comment by joshcangit** [comment]
Hope it can also work with thinLTO.

**Comment by badger200** [comment]
> Hope it can also work with thinLTO.

You can fix this bug introduced in clang-15 by adding this to your clang-15 command line:
`-Wl,-mllvm,--opaque-pointers`
This allows clang to tell the ThinLTO module to allow the opaque pointers that it previously was erroring on.
@alex @joshcangit

**Comment by joshcangit** [comment]
> > Hope it can also work with thinLTO.
> 
> You can fix this bug introduced in clang-15 by adding this to your clang-15 command line:
> `-Wl,-mllvm,--opaque-pointers`
> This allows clang to tell the ThinLTO module to allow the opaque pointers that it previously was erroring on. 

How do I use this in the `.cargo/config.toml`?

**Comment by badger200** [comment]
> > > Hope it can also work with thinLTO.
> > 
> > You can fix this bug introduced in clang-15 by adding this to your clang-15 command line:
> > `-Wl,-mllvm,--opaque-pointers`
> > This allows clang to tell the ThinLTO module to allow the opaque pointers that it previously was erroring on. 
> 
> How do I use this in the `.cargo/config.toml`?

Sorry, I'm actually an Apple iOS jailbroken C/C++ developer and when I encountered this ThinLTO opaque pointers error, it took me forever to fix, and I saw so many other pages on google like this one with everyone stumped across a wide variety of platforms, I wanted to share my fix in hopes it would solve it for others. I don't use Rust however, but I believe someone should be able to integrate this command at the point wherever Rust's build process ultimately calls the compiler to link the ThinLTO objects.

**Comment by joshcangit** [comment]
Now I know how to enable _opaque pointers_ but how to make a custom TOML configuration just specifically for this **cryptography** package.

**Comment by joshcangit** [comment]
Does anyone know how to set `--opaque-pointers` under `llvm-args` under Rust build configurations?

If I set this in my `config.toml`, will this adversely affect building other Rust packages?

**Comment by reaperhulk** [comment]
This issue is not unsolved, but it is a complex interaction of issues at the compiler level, so the workarounds (and whether you need them at all) vary by version. We can’t provide support at this level, but the comments in this issue are reasonable pointers to solutions for people with sufficient skills.

It’s unfortunate that this has happened but there’s nothing this project can really do about LTO problems.

**Comment by alex** [comment]
I'll also point out that contrary to your claim that "this issue is so old and still unsolved", numerous people have posted their solutions.

**Comment by hemangjoshi37a** [comment]
I tried multiple ways all that are mentioned in this thread however i solved it eventually. Here is what I did :

1 - cloned `https://github.com/firebase/firebase-admin-python` repo
2 - Edited `requirements.txt` as following
```
astroid == 2.3.3
pylint == 2.3.1
pytest >= 6.2.0
pytest-cov >= 2.4.0
pytest-localserver >= 0.4.1
pytest-asyncio >= 0.16.0
pytest-mock >= 3.6.1

cachecontrol >= 0.12.6
google-api-core[grpc] >= 1.22.1, < 3.0.0dev; platform.python_implementation != 'PyPy'
google-api-python-client >= 1.7.8
google-cloud-firestore >= 2.9.1; platform.python_implementation != 'PyPy'
google-cloud-storage >= 1.37.1
pyjwt >= 2.5.0
```
3 : installed from this edited version using `pip install -r requirements.txt` 
4 : copied the folder `firebase_admin` from this repo's folder to the python packages folder manually

and this is how I solved the issue.
