### ISSUE TITLE
Integration of seed word deterministic private key generation

### ISSUE THREAD

**Issue by hclivess** [pyca/cryptography#7771]
Hello, would it be possible to enable generation of private keys from static data like seed words?

**Comment by alex** [comment]
Which algorithms are you interested in generating keys for?

I think this is likely to be beyond what we can offer, but we'd be interested in understanding the use case more.

**Comment by hclivess** [comment]
In my case I am interested in using it for `Ed25519PrivateKey`, specifically for that function to be able to take input in order to generate a set of keys. In my use case the same (string) input would always generate the same pair of keys.

**Comment by alex** [comment]
The challenges with having an API that natively supports a seed phrase is that the mapping of phrases to keys needs to be stable. This means either we need to ship a wordlist, or need to require users to provide one.

This API is too specific for a general purpose cryptographic library. Therefore we won't add this feature. Users wishing to generate keys from seed phrases can use their preferred algorithm to generates 32-bit random bytes and then load them as a key.

**Comment by hclivess** [comment]
Thank you for answering, can you point me in the direction on how to load 32-bit random bytes as a key?

**Comment by alex** [comment]
https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ed25519/#cryptography.hazmat.primitives.asymmetric.ed25519.Ed25519PrivateKey.from_private_bytes
