### ISSUE TITLE
How could i use this lib to convert pkcs8 key to pkcs1 key?

### ISSUE THREAD

**Issue by w-Bro** [pyca/cryptography#7794]
Sorry for i can't find answer from documention.
I can covert it by this openssl command.
```
openssl rsa -pubin -in public_pkcs8.pem -RSAPublicKey_out -out public_pkcs1.pem
```
Morely, what i want is inputing a pkcs8 key `string` and then outputing a pkcs1 key `string`, not a `.pem` file.

**Comment by alex** [comment]
Key loading and serialization is described in https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/

**Comment by w-Bro** [comment]
> Key loading and serialization is described in https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/

thank you~  it solved.
