### ISSUE TITLE
[regression?] 38.0.3 raises error parsing asn1 value: ParseError { kind: ShortData }

### ISSUE THREAD

**Issue by ploum** [pyca/cryptography#7815]
Hi,

I’m the developer of a Gemini browser which uses python-cryptography to check against x509 certificates.

https://git.sr.ht/~lioploum/offpunk

I received a strange bug report about my browser emitting the error :

error parsing asn1 value: ParseError { kind: ShortData }

when encountering some particular certificates with python-cryptography 38.0.3.
Error seems to happen on the following  line (where previous_cert is a certificate read from a file with file.read() ):  
 
previous_cert = x509.load_der_x509_certificate(previous_cert, _BACKEND)

What is strange is that downgrading to 38.0.1 seems to make the bug disappear.

It should be noted that:
1. As a browser, I have no control over the certificates received. I don’t know how they were generated. I expect python-cryptography to tell me if they are valid or invalid.
2. This code has been working since the very first gemini browser (AV-98) and thus has encountered thousand of certificates in the last 3 years. This bug never surfaced before.

This points toward a regression in python 38.0.3

Complete discussion:
https://todo.sr.ht/~lioploum/offpunk/2

**Comment by reaperhulk** [comment]
Thanks for the report. This is surprising since 38.0.1 and 38.0.3 contain the same version of our rust ASN.1 parser (0.12.2) and no changes to the parsing code in cryptography itself, so on the surface this simply should not happen. Would it be possible to provide a certificate that replicates this so we can investigate a bit more thoroughly?

**Comment by ploum** [comment]
I want to correct my assumption: it might not be working with 38.0.1 (and may have worked only because the certificate being already encountered, it was on another codepath).  

What I’m certain is that it works with version 3.4.8 (in ubuntu) and not in 38.0.3 (ok, that’s a fairly large set I should bissect). Which may point toward something similar to #6386.

**Comment by ploum** [comment]
Thanks, that’s really clear. I now understand what is happening.

It is now my job to get my hand on that particular certificate (I’m working on this right now but has it has been encountered by one of my user, not by myself).

**Comment by alex** [comment]
Do you have a copy of the certificate that's producing this error?

**Comment by alex** [comment]
Any word for the report on a copy of the certificate? Without one it's not possible for us to make any progress here.

**Comment by ploum** [comment]
The person who reported the bug to me was not able to reproduce it. So
you can close this bug for now. If I can reproduce it myself, I will
reopen it.

Thanks for your time!

**Comment by alex** [comment]
Ok. Thank you.
