### ISSUE TITLE
Create SCTs in Python

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#7824]
Hi,

I already filed this in #4820, which was closed as a duplicate of #4531. But this is now also closed, and the issue is not fixed, so I'm finally opening a new issue, hoping to get this implemented:

` cryptography.x509.certificate_transparency.SignedCertificateTimestamp` is an AbstractBaseClass and I found now implementing subclass. This makes it impossible to create `PrecertificateSignedCertificateTimestamps` or `SignedCertificateTimestamps` instances to add to a certificate.  The following attempts all fail:

```
>>> from datetime import datetime
>>> from cryptography import x509
>>> from cryptography.x509 import certificate_transparency as ct
>>> ct.SignedCertificateTimestamp(version=ct.Version.v1, log_id=b'1', timestamp=datetime.utcnow(), entry_type=ct.LogEntryType.PRE_CERTIFICATE)
TypeError: SignedCertificateTimestamp() takes no arguments
>>> ct.SignedCertificateTimestamp(ct.Version.v1, b'1', datetime.utcnow(), ct.LogEntryType.PRE_CERTIFICATE)
TypeError: SignedCertificateTimestamp() takes no arguments
>>> ct.SignedCertificateTimestamp()

TypeError: Can't instantiate abstract class SignedCertificateTimestamp ...
```

If this can't be implemented for some reason, at least the documentation should refer to the fact.

**Comment by alex** [comment]
Are you interested in creating one with all the fields filled in, or signing a new SCT?
