### ISSUE TITLE
Import DLL Error

### ISSUE THREAD

**Issue by HatmanStack** [pyca/cryptography#7836]
Facing this error:
ImportError: DLL load failed while importing _rust: The specified module could not be found.

Python 3.10.7

Name: cryptography
Version: 38.0.3

Name: cffi
Version: 1.15.0

Name: pip
Version: 22.3.1

Name: setuptools
Version: 65.6.1

Installed cryptography as a dependency for snowflake-connector-python.

I had been using cryptography with no issues in version 38.0.2 .  With the update I've been unable to use the library locally.

**Comment by alex** [comment]
The only difference between cryptography 38.0.2 and 38.0.3 is the version
of openssl that is included, so it is very unlikely anything relevant
changed there. It is more likely that something changed in your build
process.

Can you provide us with steps to reproduce this issue?

**Comment by HatmanStack** [comment]
You're definetly right man, Just spun up a VM and all your stuff is working like a charm.  Feel like a dunce for not being able to find the problem on my rig.

**Comment by alex** [comment]
Glad you've been able to get it working.
