### ISSUE TITLE
Drop Python 3.6

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#7843]
It's no longer supported by upstream. We've been warning (though not committing to a deadling) for a while. Usage is currently around 7% or so. Our expectation is that by the time Ubuntu 18.04 goes EOL (April 2023), we should be able to drop it. Expected timeline:

- [x] 39.0 -- deprecated
- [x] 40.0 -- final warning
- [x] 41.0
  - [x] Drop support: Remove from CI, update `python-requires`, remove any branches
  - [x] Remove `python_version >= "3.7"` from CI constraints
  - [x] https://github.com/pyca/cryptography/pull/8116
  - [x] https://github.com/pyca/cryptography/pull/6935
  - [x] pyo3 upgrade follow-ups

**Comment by alex** [comment]
cc: @glyph @mattsb42-aws @bmw @ohemorange @bitprophet @mhils for our various high-profile down-streams

**Comment by glyph** [comment]
Thanks for the heads up. We're all set: https://github.com/twisted/twisted/issues/10303

**Comment by bitprophet** [comment]
I'm only just now dropping <=3.5 on most of my crap, but once the dust settles there (it includes also dropping py2) I'll take a closer look at whether my installbase would get pissy on dropping 3.6 too 🤔

**Comment by reaperhulk** [comment]
3.6 represents a shade under 7% of downloads now, but we've run into quite a few CI issues as a last-mover on dropping 3.6. 40.0.0 will still be the final release that supports 3.6.

**Comment by bitprophet** [comment]
On my end, I just checked, and while Paramiko is ~10-15% 3.6 (in 3rd place after 3.7 and 3.8), fabric and its alias fabric2 are both easily 50-60% 3.6 still. Huh.
