### ISSUE TITLE
Ocsp response from ocsp request (certificate)

### ISSUE THREAD

**Issue by DorianCoding** [pyca/cryptography#7849]
Hello,

i dont catch how we can sign a ocsp response with a certificate if we did not store it first. As it is a not a huge deal for good and revoked cert, how to send a unknown status with a certificate as we dont know that specific certificate?

thanks.

**Comment by alex** [comment]
These are created with https://cryptography.io/en/latest/x509/ocsp/#cryptography.x509.ocsp.OCSPResponseBuilder.build_unsuccessful

**Comment by DorianCoding** [comment]
There is no UNKNOWN status associated here… How can I use the certstatus with a real response? If not possible what should i choose? Unauthorized?

**Comment by alex** [comment]
As documented, unauthorized is what is used when a request for an unknown certificate is made.

**Comment by DorianCoding** [comment]
Okay, it was not very clear to me, even with examples. I will try this. Thanks for your rapid answer.
