### ISSUE TITLE
ValueError: error parsing asn1 value: ParseError { kind: ExtraData }

### ISSUE THREAD

**Issue by Alurith** [pyca/cryptography#7901]
* Versions: `Python 3.10.6`, ``cryptography 38.0.4``, ``cffi 1.15.1``, ``pip 22.2.1``
* How you installed ``cryptography``: via pip as a dependency of  `asyncua`
* Clear steps for reproducing your bug

I tried to connect to a OPC UA server using asynua, I've posted my script and the step on their issue tracker [https://github.com/FreeOpcUa/opcua-asyncio/issues/1148 ](https://github.com/FreeOpcUa/opcua-asyncio/issues/1148) and they point me this way because from the traceback apparently it's the server certificate who trigger an error. 

Here is the traceback
```
(venv) PS D:\workspace\opcua_test> python.exe .\main.py
WARNING:asyncua.uaprotocol:updating client limits to: TransportLimits(max_recv_buffer=65536, max_send_buffer=65536, max_chunk_count=256, max_message_size=16777216)
Traceback (most recent call last):
  File "D:\workspace\opcua_test\main.py", line 33, in <module>
    asyncio.run(main())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\workspace\opcua_test\main.py", line 16, in main
    await client.set_security_string("Basic256Sha256,SignAndEncrypt,cert.pem,key.pem")
  File "D:\workspace\opcua_test\venv\lib\site-packages\asyncua\client\client.py", line 167, in set_security_string
    return await self.set_security(
  File "D:\workspace\opcua_test\venv\lib\site-packages\asyncua\client\client.py", line 197, in set_security
    server_certificate = uacrypto.x509_from_der(endpoint.ServerCertificate)
  File "D:\workspace\opcua_test\venv\lib\site-packages\asyncua\crypto\uacrypto.py", line 37, in x509_from_der
    return x509.load_der_x509_certificate(data, default_backend())
  File "D:\workspace\opcua_test\venv\lib\site-packages\cryptography\x509\base.py", line 528, in load_der_x509_certificate
    return rust_x509.load_der_x509_certificate(data)
ValueError: error parsing asn1 value: ParseError { kind: ExtraData }
```

**Comment by alex** [comment]
Please provide the contents of the certificate that's triggering this error.

**Comment by Alurith** [comment]
Should I paste it here or send you securely somehow?

**Comment by reaperhulk** [comment]
If you consider it sensitive you shouldn’t provide it to us at all. If it contains no sensitive data then please put it here. If you’d prefer emailing it then my address is paul.l.kehrer on gmail.

**Comment by Alurith** [comment]
Here the server certificate.

```ServerCertificate = b"0\x82\x04\x0b0\x82\x02\xf3\xa0\x03\x02\x01\x02\x02\x08V\tX>\xed5-$0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler10001950\x1e\x17\r211025000000Z\x17\r311025000000Z0*1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1\x170\x15\x06\x03U\x04\x03\x0c\x0eVC1OpcUaServer0\x82\x01\"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x8d\\\xf6c\xc4\xcc\x86\x16$\xfc^\xe0\"\x1d\x1e\x85_8\xe8\xe6\xd6\x9cB\xe7\xb5\xcb\xaf\xbbW\x0ff\xde\n\xb2\x8fO\xca\xf3_\xd6\xad\xbbjv\x8bf|\xec\xba\x9e\xc9\xa7)\x15\xc9t\x18]*8\xc4\t\x8f>g\x839\x0f\xea\xb2[7\xf5\xaa\xfc\x166\xeaN\xb0\xab\xd4\xb0p\xdc\xb1P\x9b\xa1+;\x17!\xd8\x9e4d\xcc\xe4\x94\xf6\xc21x\x99\xc8[\xa0dw\x06\x00\x14\xb3Yc\xff@\x83\x1c\xd1E)c:\x8d\xf1\xd0\x91\xb8P\xa3\xaa\x19Vg\xd1\xd9MI\xb32\xbe\x05\xbb\x14Qs\x9c\xc6\xd3\x88\xe0(\x97(\xc0\x19\xfe\x9aJ\xc4\x1c\xb8\xcaxm\xf4`\xf7\xef\x80\x9e\t\x0f\xd5+\x86(\xfb_h*\xe7\x84,+\xbf7H.o%\xe5\xfc\xc9\x91\x18U\x0b\xfc,\xa3'\xe3\xea^\xe6=\x82l\xdc\x07F\xc7\xb4M\xb0\xcbYu\x97Ml\xe7\\\x0b\xb7\xb0\xfc\xa8\x8d\xbe\x07\xeb]RHJ\xe6\xe6\xed\nD\xa5\x86\x12`Q\x1d\xf7\xacT\x92\xfa\xed\x02\x03\x01\x00\x01\xa3\x82\x01#0\x82\x01\x1f0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\n#\x8b\xb5\xa6\xf2\x9d\x0ex\xa7\xae\xff\x92\x96\xfc\x13>\xe1m\xda0\x12\x06\x03U\x1d\x13\x01\x01\xff\x04\x080\x06\x01\x01\xff\x02\x01\x000i\x06\x03U\x1d#\x04b0`\x80\x14\x96\xec\xf4\xe6\x13\xa9$\xca\xb4\xb4\xc6|s\x0f\xdb3<DM/\xa1>\xa4<0:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler1000195\x82\x08Y\x8b\x05J\x8e\xc4\xa3'0\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x02\xf40 \x06\x03U\x1d%\x01\x01\xff\x04\x160\x14\x06\x08+\x06\x01\x05\x05\x07\x03\x01\x06\x08+\x06\x01\x05\x05\x07\x03\x020M\x06\x03U\x1d\x11\x04F0D\x86'urn:bihler1000195:bihler:VC1OpcUaServer\x87\x04\xa9\xfe\xf2A\x87\x04\n\n\n\x02\x82\rBihler10001950\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00Q\x12S\xceV\xaf\xf6#\xa2\xa9\xad\xa9\xbfR\xdcO\xd9.\xa8\xa6j\xf25\xa7n\x13%\xf6WR]:\x82\x04\x16\x10S\n-\xbf\xafA\xab=\xd9\xdc\x0b\xbc\\\xf3E\x90\xd4+\xc4\xc7H\x1a\xa3+w\x8c>=6A(\x9a\x0cM\x19\x0f\xccb\xad\x8e|E\xc0w\xb4\xb5\x17\x06\x1cLk\xe9=\xc1\xb6\xcf\x0fN(\xbf>K\t\xc9\xd8+o'iG\x8eA\xb0s\x10\x1c\x9fK\xb9\xff\x0c\xfc[\xc3\xc4\xc4\x84~\xee\xa5[\xfa\x8d\x96\xc6\xd7\xd1\xeb\xf8&T\x8f\xe3\x17\xcf\x83\\!_\xf1\x81{\xdf\xf5L\xca\xe44\x15-V\xe5\xa2\xabQ\xf6r\xba\xeeT\xbfI\x05\x8cd`\x9f\x85\"P\xf7\xb4\x84%\xf1\x1e\x8c\xdd\xe5G\xa3\x9d\xee3\xfaj\x8b\x06P\xa4\xcbw0yO\xca\xfe\xc4_\xef\x02\xb7g\x8a\xdd\x00s5]H}\x0e\xf3\xd8\x97\xae\x9b\x12\x9c \xca\x04\x00\xfb\xaf~3~C\xda\xba\xf6\xfae\x12'\\w=c\x18\x19\xa8$\xdb :\xc0;\x130\x82\x03\xa70\x82\x02\x8f\xa0\x03\x02\x01\x02\x02\x08Y\x8b\x05J\x8e\xc4\xa3'0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler10001950 \x17\r211025105559Z\x18\x0f22211025105559Z0:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler10001950\x82\x01\"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x82\xf6\xf6!\xb0\xe1dX\xbcQ\xdc7\xd4fMU\x10fi<\x97\x10\xf7\xea\xde5\xdewv\xf4\x98\x95\xcf\xe9\xc4<h\xee\xc9\xa3\xeb\xf2\xe8\r\x1a\xdd\x81\x05w\xed\x92x\xcd\xc2}\xce\xd3\x9a\xf2v2\x95\xf7P\x11\xd3\xf8\x15>\x8fB\xbdR\xf7Q%Sl|\xd1\xbe\xdc\xa5\x0e\xeb(B\xd4\xc4TA\xa6\xcc\xa5Zl\xa3\xeb$9\xc2\n\x8d\x9eP\x96\x87.Tu\xaaR\xe8(\xafl){T\r\xe2\xe8X\xb7|\xf6\xa6\x88J\xe7\x1b\xea,\xcf\x00%\xb0\x02(\xb5\xf2\x05<\xcb\xcf\x02_\xdf\xaa\x12\x0f,r\r\xa8\xbe\xa0bb\x8fJ\xc69=\x11\xa6(\xdcO\xcbl\xe8`,\xee1\x91\xa1\xe7\x97\xf0\x1b\xbe\xc5R\x9a#\xbeI\xc5c\xe5\xc9\x9b\x07\x8f\xbd6\xad\x94h0f+\xd2\xd4A9\xf15\xff\xd7\xaa\xddX\x01\x08\xf7\xa5\x1c$5\x8a.\xcek\xad.\xef\x85qX\x00\xb4\x82\xb7\xff\x93\xa4O\xdd-\x02\x14\xe7\xa4\x9c-\x03\x11\xf9A>\xf4<A\x02\x03\x01\x00\x01\xa3\x81\xae0\x81\xab0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\x96\xec\xf4\xe6\x13\xa9$\xca\xb4\xb4\xc6|s\x0f\xdb3<DM/0\x0f\x06\x03U\x1d\x13\x01\x01\xff\x04\x050\x03\x01\x01\xff0i\x06\x03U\x1d#\x04b0`\x80\x14\x96\xec\xf4\xe6\x13\xa9$\xca\xb4\xb4\xc6|s\x0f\xdb3<DM/\xa1>\xa4<0:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler1000195\x82\x08Y\x8b\x05J\x8e\xc4\xa3'0\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x01\x860\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00y\x03\x17\x00\x89\xdf\x07\xf65>t7\x948{\x7fl\xa7u\xeb\x19\xac#x\x84_,W\xe3\x0f\xc9\xd2YT\xe8\xd3\x0c\xf8\x1a\x13\xf4\xab\x14A\x80\xae\xffl\xd1\xa1?6\x06\xf1\xb8t\xaas\x84\xea(&\x8c\xc8\x9d\xe7\x94\x87$\xd0\xb7[\x11\r\xf8mPc\r\xef\xd0|\xb2\x83\xf0\x8d\x86\xd5\x84\xed\x8a\xca#Q\xa3Xu\x16\x13\xd5\xbc\xe3\x0c`\xec\xfb\xef\x94>t\xb0\x85=V\xb66 \x86.\xd6\xb8\x97\x14\x96\xab\xbf\xcc\x1fj\x82\x037\xc8&\x9d\xad\xf9\x88\x96\x04\xce\xae\x18\xed\x99z\x9f\x8e\x91\xc3Ui[\x14\x94j\xc7\xf3\xf9\xaaR?\xd0\xc5\xea\x81\xeb\x8fiJ)z#\x89B\xe1N#s\xf7\x8d\xcc\x93\x8c\x1c\xf9-\xbeZ\x9c\xdex\n\xcc\xab\xfcbt\xa5\xe7\x95\xf0\x94\xee\x04\xb2\x9b\x15M\x0b_*\x06jN>Yy\\\x8b\xa4\xbc\x00\x15\"\r]\x0e~\x89`\xad\x85\xf8\xa5\x84D\x19G\x8d\xf1J\xde\xfa\x8f\xea\x82\xed\xfc\x92h\x86%\xd6\x18U"`ServerCertificate = b"0\x82\x04\x0b0\x82\x02\xf3\xa0\x03\x02\x01\x02\x02\x08V\tX>\xed5-$0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler10001950\x1e\x17\r211025000000Z\x17\r311025000000Z0*1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1\x170\x15\x06\x03U\x04\x03\x0c\x0eVC1OpcUaServer0\x82\x01\"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x8d\\\xf6c\xc4\xcc\x86\x16$\xfc^\xe0\"\x1d\x1e\x85_8\xe8\xe6\xd6\x9cB\xe7\xb5\xcb\xaf\xbbW\x0ff\xde\n\xb2\x8fO\xca\xf3_\xd6\xad\xbbjv\x8bf|\xec\xba\x9e\xc9\xa7)\x15\xc9t\x18]*8\xc4\t\x8f>g\x839\x0f\xea\xb2[7\xf5\xaa\xfc\x166\xeaN\xb0\xab\xd4\xb0p\xdc\xb1P\x9b\xa1+;\x17!\xd8\x9e4d\xcc\xe4\x94\xf6\xc21x\x99\xc8[\xa0dw\x06\x00\x14\xb3Yc\xff@\x83\x1c\xd1E)c:\x8d\xf1\xd0\x91\xb8P\xa3\xaa\x19Vg\xd1\xd9MI\xb32\xbe\x05\xbb\x14Qs\x9c\xc6\xd3\x88\xe0(\x97(\xc0\x19\xfe\x9aJ\xc4\x1c\xb8\xcaxm\xf4`\xf7\xef\x80\x9e\t\x0f\xd5+\x86(\xfb_h*\xe7\x84,+\xbf7H.o%\xe5\xfc\xc9\x91\x18U\x0b\xfc,\xa3'\xe3\xea^\xe6=\x82l\xdc\x07F\xc7\xb4M\xb0\xcbYu\x97Ml\xe7\\\x0b\xb7\xb0\xfc\xa8\x8d\xbe\x07\xeb]RHJ\xe6\xe6\xed\nD\xa5\x86\x12`Q\x1d\xf7\xacT\x92\xfa\xed\x02\x03\x01\x00\x01\xa3\x82\x01#0\x82\x01\x1f0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\n#\x8b\xb5\xa6\xf2\x9d\x0ex\xa7\xae\xff\x92\x96\xfc\x13>\xe1m\xda0\x12\x06\x03U\x1d\x13\x01\x01\xff\x04\x080\x06\x01\x01\xff\x02\x01\x000i\x06\x03U\x1d#\x04b0`\x80\x14\x96\xec\xf4\xe6\x13\xa9$\xca\xb4\xb4\xc6|s\x0f\xdb3<DM/\xa1>\xa4<0:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler1000195\x82\x08Y\x8b\x05J\x8e\xc4\xa3'0\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x02\xf40 \x06\x03U\x1d%\x01\x01\xff\x04\x160\x14\x06\x08+\x06\x01\x05\x05\x07\x03\x01\x06\x08+\x06\x01\x05\x05\x07\x03\x020M\x06\x03U\x1d\x11\x04F0D\x86'urn:bihler1000195:bihler:VC1OpcUaServer\x87\x04\xa9\xfe\xf2A\x87\x04\n\n\n\x02\x82\rBihler10001950\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00Q\x12S\xceV\xaf\xf6#\xa2\xa9\xad\xa9\xbfR\xdcO\xd9.\xa8\xa6j\xf25\xa7n\x13%\xf6WR]:\x82\x04\x16\x10S\n-\xbf\xafA\xab=\xd9\xdc\x0b\xbc\\\xf3E\x90\xd4+\xc4\xc7H\x1a\xa3+w\x8c>=6A(\x9a\x0cM\x19\x0f\xccb\xad\x8e|E\xc0w\xb4\xb5\x17\x06\x1cLk\xe9=\xc1\xb6\xcf\x0fN(\xbf>K\t\xc9\xd8+o'iG\x8eA\xb0s\x10\x1c\x9fK\xb9\xff\x0c\xfc[\xc3\xc4\xc4\x84~\xee\xa5[\xfa\x8d\x96\xc6\xd7\xd1\xeb\xf8&T\x8f\xe3\x17\xcf\x83\\!_\xf1\x81{\xdf\xf5L\xca\xe44\x15-V\xe5\xa2\xabQ\xf6r\xba\xeeT\xbfI\x05\x8cd`\x9f\x85\"P\xf7\xb4\x84%\xf1\x1e\x8c\xdd\xe5G\xa3\x9d\xee3\xfaj\x8b\x06P\xa4\xcbw0yO\xca\xfe\xc4_\xef\x02\xb7g\x8a\xdd\x00s5]H}\x0e\xf3\xd8\x97\xae\x9b\x12\x9c \xca\x04\x00\xfb\xaf~3~C\xda\xba\xf6\xfae\x12'\\w=c\x18\x19\xa8$\xdb :\xc0;\x130\x82\x03\xa70\x82\x02\x8f\xa0\x03\x02\x01\x02\x02\x08Y\x8b\x05J\x8e\xc4\xa3'0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x000:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler10001950 \x17\r211025105559Z\x18\x0f22211025105559Z0:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler10001950\x82\x01\"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x82\xf6\xf6!\xb0\xe1dX\xbcQ\xdc7\xd4fMU\x10fi<\x97\x10\xf7\xea\xde5\xdewv\xf4\x98\x95\xcf\xe9\xc4<h\xee\xc9\xa3\xeb\xf2\xe8\r\x1a\xdd\x81\x05w\xed\x92x\xcd\xc2}\xce\xd3\x9a\xf2v2\x95\xf7P\x11\xd3\xf8\x15>\x8fB\xbdR\xf7Q%Sl|\xd1\xbe\xdc\xa5\x0e\xeb(B\xd4\xc4TA\xa6\xcc\xa5Zl\xa3\xeb$9\xc2\n\x8d\x9eP\x96\x87.Tu\xaaR\xe8(\xafl){T\r\xe2\xe8X\xb7|\xf6\xa6\x88J\xe7\x1b\xea,\xcf\x00%\xb0\x02(\xb5\xf2\x05<\xcb\xcf\x02_\xdf\xaa\x12\x0f,r\r\xa8\xbe\xa0bb\x8fJ\xc69=\x11\xa6(\xdcO\xcbl\xe8`,\xee1\x91\xa1\xe7\x97\xf0\x1b\xbe\xc5R\x9a#\xbeI\xc5c\xe5\xc9\x9b\x07\x8f\xbd6\xad\x94h0f+\xd2\xd4A9\xf15\xff\xd7\xaa\xddX\x01\x08\xf7\xa5\x1c$5\x8a.\xcek\xad.\xef\x85qX\x00\xb4\x82\xb7\xff\x93\xa4O\xdd-\x02\x14\xe7\xa4\x9c-\x03\x11\xf9A>\xf4<A\x02\x03\x01\x00\x01\xa3\x81\xae0\x81\xab0\x1d\x06\x03U\x1d\x0e\x04\x16\x04\x14\x96\xec\xf4\xe6\x13\xa9$\xca\xb4\xb4\xc6|s\x0f\xdb3<DM/0\x0f\x06\x03U\x1d\x13\x01\x01\xff\x04\x050\x03\x01\x01\xff0i\x06\x03U\x1d#\x04b0`\x80\x14\x96\xec\xf4\xe6\x13\xa9$\xca\xb4\xb4\xc6|s\x0f\xdb3<DM/\xa1>\xa4<0:1\x0f0\r\x06\x03U\x04\n\x0c\x06bihler1'0%\x06\x03U\x04\x03\x0c\x1eVC1OpcUaServerCA_Bihler1000195\x82\x08Y\x8b\x05J\x8e\xc4\xa3'0\x0e\x06\x03U\x1d\x0f\x01\x01\xff\x04\x04\x03\x02\x01\x860\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00y\x03\x17\x00\x89\xdf\x07\xf65>t7\x948{\x7fl\xa7u\xeb\x19\xac#x\x84_,W\xe3\x0f\xc9\xd2YT\xe8\xd3\x0c\xf8\x1a\x13\xf4\xab\x14A\x80\xae\xffl\xd1\xa1?6\x06\xf1\xb8t\xaas\x84\xea(&\x8c\xc8\x9d\xe7\x94\x87$\xd0\xb7[\x11\r\xf8mPc\r\xef\xd0|\xb2\x83\xf0\x8d\x86\xd5\x84\xed\x8a\xca#Q\xa3Xu\x16\x13\xd5\xbc\xe3\x0c`\xec\xfb\xef\x94>t\xb0\x85=V\xb66 \x86.\xd6\xb8\x97\x14\x96\xab\xbf\xcc\x1fj\x82\x037\xc8&\x9d\xad\xf9\x88\x96\x04\xce\xae\x18\xed\x99z\x9f\x8e\x91\xc3Ui[\x14\x94j\xc7\xf3\xf9\xaaR?\xd0\xc5\xea\x81\xeb\x8fiJ)z#\x89B\xe1N#s\xf7\x8d\xcc\x93\x8c\x1c\xf9-\xbeZ\x9c\xdex\n\xcc\xab\xfcbt\xa5\xe7\x95\xf0\x94\xee\x04\xb2\x9b\x15M\x0b_*\x06jN>Yy\\\x8b\xa4\xbc\x00\x15\"\r]\x0e~\x89`\xad\x85\xf8\xa5\x84D\x19G\x8d\xf1J\xde\xfa\x8f\xea\x82\xed\xfc\x92h\x86%\xd6\x18U"```

**Comment by alex** [comment]
I think this is mis-formatted. Pasting this into a python shell gives me a
SyntaxError

**Comment by Alurith** [comment]
I've fixed it, it was copied 2 times.

**Comment by alex** [comment]
This certificate appears to contain a ton of trailing data after the certificate itself: the length headers in the ASN.1 indicate that it is 1035 bytes, but the string itself is is 1978 bytes.

Whatever server is serving this is mis-configured and should stop serving the extra data.

**Comment by Alurith** [comment]
@alex, I can't change anything on the server. Is there a way to ignore the additional data?

**Comment by alex** [comment]
I suppose you could parse the ASN.1 header yourself and only feed the relevant data in to cryptography. we don't provide any functions for doing this though.

To be clear: its correct for cryptograhy to reject this, I don't see any bug on our side here.

**Comment by Alurith** [comment]
Ok, thank you for the support!

**Comment by piotrek204** [comment]
Hi, 
I have the same problem and after investing, it looks like something on the `opcua-asyncio` side. 
Let me describe in detail my case.  
I'm using `C++ SDK Demo Server` in which a certificate was signed by CA root (created new certificate based on CSR) The certificate was signed using `UAGDS security management`.
I have exactly the same observation that @Alurith wrote about.
After analyzing what the server sent, I came to the conclusion that there is a certificate hierarchy (chain) where the first is the server certificate and the second is the CA root cert. 

To verify, enough to write the bytes sent by @Alurith to a file and we see that the certificate is correct  
```
with open("cert.der", 'wb') as f:
    f.write(ServerCertificate)
```

So with that in mind, do you think this issue should be taken care of somehow?

P.S. I can also add that on Wireshark the chain of this certificate also looks like a single certificate and `UAExpert` manages to establish a connection to such a configured server.

**Comment by reaperhulk** [comment]
If the issue is that extra data is being passed after the certificate der and that entire payload is being passed into cryptography it’s not clear to me why it’s not possible for the caller to pass the correct information with no trailing data. Our DER parser accepts DER, not DER plus other arbitrary bytes.

**Comment by piotrek204** [comment]
I would rather say that it is still a chain of certificates rather than a certificate + extra arbitrary data

**Comment by reaperhulk** [comment]
In 39.0.0 we added [load_pem_x509_certificates](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_pem_x509_certificates). I wouldn't be opposed to a `load_der_x509_certificates` in principle, although that's assuming that it's really just concatenated DER with no other delimiter present.

**Comment by reaperhulk** [comment]
A DER structure contains its own length, so when parsing you can know when the previous structure terminates and see if the next byte starts a new DER structure or not. In a TLS connection certs are encoded as elements in a TLS sequence, so it's weird to see them directly concatenated (as they appear to be here). Is this server sending a concatenated blob when it should just be sending the server cert?

**Comment by piotrek204** [comment]
Here is a description of the mechanism that seems to be missing in the client (server too?) implementation [https://reference.opcfoundation.org/Core/Part6/v105/docs/6.2.6](https://reference.opcfoundation.org/Core/Part6/v105/docs/6.2.6)

so if I know that the length of the certificate is written at the beginning of it, we can easily check whether the bytes received from the server are one certificate or many.

```
>>> cert_len_idx = 2
>>> number_of_cert_len_bytes = 2
>>> cert_len = int.from_bytes(endpoint.ServerCertificate[cert_len_idx:cert_len_idx + number_of_cert_len_bytes], byteorder="big", signed=False) + number_of_cert_len_bytes + cert_len_idx
>>> cert_len
1151
```

**Comment by reaperhulk** [comment]
Yeah so this protocol is documented as just having one or more concatenated DER sequences. So you need to parse the first asn1 sequence to get a length and then if the total length of the byte string is longer than that parse again at the next offset.
