### ISSUE TITLE
 EC2 Instance Identity Verification

### ISSUE THREAD

**Issue by KshitizGIT** [pyca/cryptography#7936]
Not sure if this is a correct place to ask.

I need some support using this wonderful `cryptography` module. I need to support AWS EC2 instance verification using this library. However, I am unable to find any documentation/ resources to accomplish this task. I am not a cryptography expert so I would appreciate some help in accomplish this task

Basically, I need help in performing this verifcation process using this library 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-signature.html

I found a wonderful blog post for Javascript using the `crypto` library. Is there any way we can do this using the `cryptography` module?
https://medium.com/@bugzeeeeee/cryptographic-adventures-ec2-instance-identity-verification-in-javascript-b0edfad09de9

**Comment by alex** [comment]
Certificates can be parsed with: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_pem_x509_certificate

You can obtain the public key with: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.public_key

And you can verify signatures with https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPublicKey.verify

**Comment by KshitizGIT** [comment]
Hi @alex ,
Thanks for the reply. I tried with this approach. However, I am getting an `InvalidSignature` exception.
What would be an appropriate value for padding and algorithm for RSA-signed SHA256 digest?
This is my current code.
```python
        public_key_string = """-----BEGIN CERTIFICATE-----
MIIDIjCCAougAwIBAgIJAKnL4UEDMN/FMA0GCSqGSIb3DQEBBQUAMGoxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdTZWF0dGxlMRgw
FgYDVQQKEw9BbWF6b24uY29tIEluYy4xGjAYBgNVBAMTEWVjMi5hbWF6b25hd3Mu
Y29tMB4XDTE0MDYwNTE0MjgwMloXDTI0MDYwNTE0MjgwMlowajELMAkGA1UEBhMC
VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGDAWBgNV
BAoTD0FtYXpvbi5jb20gSW5jLjEaMBgGA1UEAxMRZWMyLmFtYXpvbmF3cy5jb20w
gZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAIe9GN//SRK2knbjySG0ho3yqQM3
e2TDhWO8D2e8+XZqck754gFSo99AbT2RmXClambI7xsYHZFapbELC4H91ycihvrD
jbST1ZjkLQgga0NE1q43eS68ZeTDccScXQSNivSlzJZS8HJZjgqzBlXjZftjtdJL
XeE4hwvo0sD4f3j9AgMBAAGjgc8wgcwwHQYDVR0OBBYEFCXWzAgVyrbwnFncFFIs
77VBdlE4MIGcBgNVHSMEgZQwgZGAFCXWzAgVyrbwnFncFFIs77VBdlE4oW6kbDBq
MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHU2Vh
dHRsZTEYMBYGA1UEChMPQW1hem9uLmNvbSBJbmMuMRowGAYDVQQDExFlYzIuYW1h
em9uYXdzLmNvbYIJAKnL4UEDMN/FMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEF
BQADgYEAFYcz1OgEhQBXIwIdsgCOS8vEtiJYF+j9uO6jz7VOmJqO+pRlAbRlvY8T
C1haGgSI/A1uZUKs/Zfnph0oEI0/hu1IIJ/SKBDtN5lvmZ/IzbOPIJWirlsllQIQ
7zvWbGd9c9+Rm3p04oTvhup99la7kZqevJK0QRdD/6NpCKsqP/0=
-----END CERTIFICATE-----"""
        cert = x509.load_pem_x509_certificate(public_key_string.encode("utf-8"))
        public_key = cert.public_key()
        public_key.verify(
            signature=signature,
            data=request.data.get("document").encode("utf-8"),
            padding=padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH
            ),
            algorithm=hashes.SHA256(),
        )
```

**Comment by alex** [comment]
You need to use the same padding algorithm as was used by AWS. I assume they use PKCS1v15

**Comment by KshitizGIT** [comment]
Thanks @alex for the help.  I was able to solve it using `padding=padding.PKCS1v15()`
