### ISSUE TITLE
Error with compiled 

### ISSUE THREAD

**Issue by Gowixx** [pyca/cryptography#7945]
Hey there! Tryna run something that is compiled on linux with pyinstaller on another linux system.

Versions:
```
pip                    22.0.2
cryptography           3.4.8
cffi                   1.15.1
setuptools             59.6.0
```

*Traceback*
https://cdn.skrrrtt.cool/p/raw/files/2yftsm2koio21kre9

**Comment by alex** [comment]
Its nearly impossible to debug this without any instructions for reproducing or details.

That said, the line of code that the exception is pointed at doesn't actually match what is it in cryptography 3.4.8 (https://github.com/pyca/cryptography/blob/3.4.8/src/cryptography/hazmat/bindings/openssl/binding.py#L167) so I think something must be going wrong in your build process.

I'll note that, in any event, cryptography 3.4.8 is long out of date and is not supported by us.

Finally, the init failed error from OpenSSL traditionally indicates that some shared library it relies on (e.g., zlib) is not available.
