### ISSUE TITLE
Failed to build wheel for cryptography==2.6.1 

### ISSUE THREAD

**Issue by MYSELF365** [pyca/cryptography#7952]
If you're filing a bug (as opposed to a feature request), please try the
following things:

* Check the FAQ to see if your issue is covered there:
  https://cryptography.io/en/latest/faq.html
* Upgrade to the latest version of ``setuptools`` and ``pip``
* Make sure you're on a supported version of OpenSSL
* Try with the latest version of ``cryptography``
* Be sure you have the required compilers (both a C compiler and Rust)
  installed if you aren't using the binary wheels.

If none of that works, please make sure to include the following information in
your bug report:

* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools``
  you're using
* How you installed ``cryptography``
* Clear steps for reproducing your bug

Please do not report security issues on Github! Follow the instructions in our
documentation for reporting security issues:
https://cryptography.io/en/latest/security.html

**Comment by alex** [comment]
a) cryptography 2.6.1 is not at all supported anymore and hasn't been for 3.5 years.
b) Your issue contains absolutely no details.

**Comment by MYSELF365** [comment]
Collecting cryptography==2.6.1
  Using cached cryptography-2.6.1.tar.gz (491 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: six>=1.4.1 in c:\15.0\odoo\odoo-15.0\venv\lib\site-packages (from cryptography==2.6.1) (1.16.0)
Collecting asn1crypto>=0.21.0
  Using cached asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in c:\15.0\odoo\odoo-15.0\venv\lib\site-packages (from cryptography==2.6.1) (1.15.1)
Requirement already satisfied: pycparser in c:\15.0\odoo\odoo-15.0\venv\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.6.1) (2.21)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\15.0\odoo\odoo-15.0\venv\Scripts\python.exe' 'C:\15.0\odoo\odoo-15.0\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\LENOVO\AppData\Local\Temp\tmpzgb1kn6l'
       cwd: C:\Users\LENOVO\AppData\Local\Temp\pip-install-uqrrmqle\cryptography_47a8ac4f69c94cf5af20d8accc16db84
  Complete output (190 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-38
  creating build\lib.win-amd64-cpython-38\cryptography
  copying src\cryptography\exceptions.py -> build\lib.win-amd64-cpython-38\cryptography
  copying src\cryptography\fernet.py -> build\lib.win-amd64-cpython-38\cryptography
  copying src\cryptography\utils.py -> build\lib.win-amd64-cpython-38\cryptography
  copying src\cryptography\__about__.py -> build\lib.win-amd64-cpython-38\cryptography
  copying src\cryptography\__init__.py -> build\lib.win-amd64-cpython-38\cryptography
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat
  copying src\cryptography\hazmat\_oid.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat
  copying src\cryptography\hazmat\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat
  creating build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\base.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\certificate_transparency.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\extensions.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\general_name.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\name.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\ocsp.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\oid.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  copying src\cryptography\x509\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\x509
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\backends
  copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends
  copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\bindings
  copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\bindings
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\mac.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ed25519.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ed448.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\ocsp.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\x448.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\backends\openssl
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\bindings\openssl
  copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\bindings\openssl
  copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\bindings\openssl
  copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\bindings\openssl
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\ed25519.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\ed448.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\x448.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\asymmetric
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\ciphers
  copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\ciphers
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\kdf
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\base.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\pkcs12.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\ssh.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\serialization
  copying src\cryptography\hazmat\primitives\serialization\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\serialization
  creating build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\twofactor
  copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win-amd64-cpython-38\cryptography\hazmat\primitives\twofactor
  running egg_info
  writing src\cryptography.egg-info\PKG-INFO
  writing dependency_links to src\cryptography.egg-info\dependency_links.txt
  writing requirements to src\cryptography.egg-info\requires.txt
  writing top-level names to src\cryptography.egg-info\top_level.txt
  reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs\_build'
  warning: no previously-included files matching '*' found under directory 'vectors'
  adding license file 'LICENSE'
  adding license file 'LICENSE.APACHE'
  adding license file 'LICENSE.BSD'
  adding license file 'AUTHORS.rst'
  writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
  running build_ext
  generating cffi module 'build\\temp.win-amd64-cpython-38\\Release\\_padding.c'
  creating build\temp.win-amd64-cpython-38
  creating build\temp.win-amd64-cpython-38\Release
  generating cffi module 'build\\temp.win-amd64-cpython-38\\Release\\_constant_time.c'
  generating cffi module 'build\\temp.win-amd64-cpython-38\\Release\\_openssl.c'
  building '_openssl' extension
  Traceback (most recent call last):
    File "C:\15.0\odoo\odoo-15.0\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "C:\15.0\odoo\odoo-15.0\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\15.0\odoo\odoo-15.0\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\build_meta.py", line 484, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 247, in <module>
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
      super().run_command(command)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
      super().run_command(command)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
      self.run_command(cmd_name)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\dist.py", line 1208, in run_command
      super().run_command(command)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 144, in run
      base_class.run(self)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 144, in run
      base_class.run(self)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\cffi\setuptools_ext.py", line 144, in run
      base_class.run(self)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
      self.build_extensions()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial        
      self.build_extension(ext)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 549, in build_extension
      objects = self.compiler.compile(
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
      self.initialize()
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\LENOVO\AppData\Local\Temp\pip-build-env-ab2c8z38\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

**Comment by MYSELF365** [comment]
So which version should i use ? cause i'm installing requirements.txt in my odoo15 but it's giving an error  as failed to build wheel for cryptography ,libsass 
so please guide me what should i do?

**Comment by MYSELF365** [comment]
ok thanks i'll use it now
