### ISSUE TITLE
Error with 39.0.0 when using with requests_pkcs12

### ISSUE THREAD

**Issue by CKoes** [pyca/cryptography#7973]
requests_pkcs12 version 1.13 is working with cryptography version 38.0.1 but not with newest version 39.0.0:

![image](https://user-images.githubusercontent.com/19286888/210398615-e7baec52-5bb0-49e1-8edd-8a663d2bc5ee.png)

**Comment by alex** [comment]
This looks like you are using a very old version of pyOpenSSL. Upgrading
pyOpenSSL should resolve this.

**Comment by alex** [comment]
My apologies, I misread this. It's actually a urllib3 bug.

**Comment by reaperhulk** [comment]
Yep, upgrade urllib3 😄
