### ISSUE TITLE
Package size drastically increased from 38.0.4 to 39.0.0

### ISSUE THREAD

**Issue by Scrat94** [pyca/cryptography#7980]
Hello,
I noticed that the size of the package increased from 0.6MB to 13MB between the version 38.0.4 and 39.0.0.
Is this intended or is this caused by an issue? I noticed that, because I am using this library in an AWS Lambda function, and the lambda function can only display code with a size of 6 MB. Due to the new sized 'cryptography' package, this is no longer possible. 

The cryptography lib is getting installed when I am using the [MSAL lib](https://github.com/AzureAD/microsoft-authentication-library-for-python)

Any help to improve the size is appreciated.

![2023-01-04_192215_7zFM](https://user-images.githubusercontent.com/31823370/210623392-43b986ec-692d-4764-91a0-11ed4c6d90fb.png)
![2023-01-04_192223](https://user-images.githubusercontent.com/31823370/210623394-2f93b4e2-e3f7-4532-bc90-da8c33defad9.png)

**Comment by alex** [comment]
Which artifact (wheel) are you installing from?

**Comment by alex** [comment]
I've compared the manylinux_2_17_x86_64 wheels and also the macosx_10_12_universal2 ones, and the files all seem to be approximately the same size, no major deviations.

**Comment by Scrat94** [comment]
@alex not sure if I fully understood your question. I install the 'msal' lib via "pip install msal". And it seems that one of the dependencies is the 'cryptography' lib, which gets automatically installed when I run the command above. 

I observe the same result (size), when running pip install on windows and on the CI Build step of my AWS Pipeline (Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0)

Not sure if my comment answers your question :/

**Comment by alex** [comment]
We offer numerous installable artifacts for cryptography (https://pypi.org/project/cryptography/#files). When you run `pip install msal`, it will say which one its downloading and installing (e.g. `cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl`). I'm asking which that is, so we can compare with that version from 38.0.4.

**Comment by Scrat94** [comment]
I can see the following on windows: `cryptography-39.0.0-cp36-abi3-win_amd64.whl`
In my CI pipeline: `cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB) `

**Comment by alex** [comment]
I have compared `cryptography-38.0.4-cp36-abi3-manylinux_2_28_x86_64.whl` and `cryptography-39.0.0-cp36-abi3-manylinux_2_28_x86_64.whl`.

Both `.whl` files are 4MB. Both `.whl` files are `.zip` archives, and uncompressing them shows 38.0.4 that it contains 12.85 MB in total files and 39.0.0 contains 12.9 MB.

In short, I'm not able to reproduce this.

**Comment by Scrat94** [comment]
Hmm, then its maybe on my side. I will dig deeper into the topic. Thanks a lot for your quick help, answers and troubleshooting!
