### ISSUE TITLE
ImportError and Library Not Loaded appears when using cryptography on macOS 12.6

### ISSUE THREAD

**Issue by MikuAndRabbit** [pyca/cryptography#8012]
The following error occurred when using cryptography today:

```
Traceback (most recent call last):
  File "/Users/usrmac/Downloads/tmp.py", line 10, in <module>
    from cryptography.fernet import Fernet
  File "/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives.hmac import HMAC
  File "/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/primitives/hmac.py", line 12, in <module>
    from cryptography.hazmat.backends.openssl.hmac import _HMACContext
  File "/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: dlopen(/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so, 0x0002): Library not loaded: '@rpath/libssl.1.1.dylib'
  Referenced from: '/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so'
  Reason: tried: '/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/../../../../../libssl.1.1.dylib' (no such file), '/Users/usrmac/opt/miniconda3/lib/python3.9/site-packages/cryptography/hazmat/bindings/../../../../../libssl.1.1.dylib' (no such file), '/Users/usrmac/opt/miniconda3/bin/../lib/libssl.1.1.dylib' (no such file), '/Users/usrmac/opt/miniconda3/bin/../lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
```

The solution I can think of now is to copy `libssl.1.1.dylib` to the folder mentioned in Reason, but I wonder if there is any other way to permanently solve this problem. Because sometimes you need to switch between different conda environments to write and test code.

The following is the relevant environmental information:

```
pip 22.3.1
setuptools 65.5.0
cffi 1.15.1
cryptography 38.0.1
pyopenssl 23.0.0
openssl 3.0.5
```

How to install cryptography: use the conda command `conda install cryptography`

How to install openssl: through the homebrew command `brew install openssl@1.1`

Location of openssl: Run the command `which -a openssl` to get the following results

```
/Users/usrmac/opt/miniconda3/bin/openssl
/usr/bin/openssl
```

Steps for reproducing:
1. install cryptography: `conda install cryptography`
2. import cryptography in a python file: `from cryptography.fernet import Fernet`
3. run the python file: `python -u "/User/usrmac/Downloads/tmp.py"`

If there is any other information I need to provide, please feel free to let me know. Thank you.

**Comment by alex** [comment]
This bug needs to be reported to conda, we are not responsible for how they distribute cryptography, and however they're linking openssl is not something we control -- and is specifically different from how our wheels work.

**Comment by MikuAndRabbit** [comment]
> This bug needs to be reported to conda, we are not responsible for how they distribute cryptography, and however they're linking openssl is not something we control -- and is specifically different from how our wheels work.

Thank you for your help. Just now, I tested the method of conda installation by creating a new environment, and found that the problem did not reoccur. It is finally found that there is a certain delay between the mirror used by conda and the upstream, resulting in the mismatch between the installed cryptography and the openssl version installed by conda.
