### ISSUE TITLE
Dependency checking improvement

### ISSUE THREAD

**Issue by PenelopeFudd** [pyca/cryptography#8031]
Mixing package sources (distribution-packaged vs pip-installed) is not safe, and cryptography is a prime example of this.

What can we do to prevent newbies from doing this, since it generates trivial Git Issues that need to be handled, and gives the false impression that python doesn't handle dependencies well?

It appears that the existing dependency-checking configuration+code isn't catching this.  Is it possible to specify version information in cryptography that says (encodes the fact) that it's incompatible with pyOpenSSL < some version?  

If outdated versions of pip can't handle that kind of reverse-dependency version checking, then cryptography may want to compensate by adding deprecation errors (we're well past warnings now).

As to the wording of the error(s), I've been told that while it's good to tell someone they've made a mistake, it's even better to also tell them what they should do to fix and avoid it in the future.

It'll make things user-friendlier, cut down on Git Issues that can be closed in 5 minutes, and help maintain Python's reputation as an easy language to use.

Thanks

_Originally posted by @PenelopeFudd in https://github.com/pyca/cryptography/issues/8030#issuecomment-1376215997_

**Comment by alex** [comment]
To me this is really a question better directed to the Python packaging
authority. As an individual package we are very limited in our tools to
address this.

**Comment by reaperhulk** [comment]
Closing as this is a systemic issue best addressed with PyPA.
