### ISSUE TITLE
Calling pkcs12.serialize_key_and_certificates() in a type-safe way

### ISSUE THREAD

**Issue by intgr** [pyca/cryptography#8039]
This is more of a best practice question, but I think it should be covered in documentation (I can submit a doc patch later).

When I get a key from `load_pem_private_key()`, it can be lots of types such as RSAPrivateKey or X25519PrivateKey.

But the `pkcs12.serialize_key_and_certificates(key=)` argument uses the internal type alias `_ALLOWED_PKCS12_TYPES` and accepts only RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey, Ed25519PrivateKey, Ed448PrivateKey.

What's the "correct" way to check that the key has the right type? Naively I would write:

```python
private_key = load_pem_private_key(...)
try:
    serialize_key_and_certificates(..., key=private_key, ...)
except TypeError:
    # Report to user
```

However this causes an error with type checkers like mypy:

> error: Argument 2 to "serialize_key_and_certificates" has incompatible type "Union[DHPrivateKey, Ed25519PrivateKey, Ed448PrivateKey, RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey, X25519PrivateKey, X448PrivateKey]"; expected "Union[RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey, Ed25519PrivateKey, Ed448PrivateKey, None]"  [arg-type]

I can add an additional `if` to the code to solve this:

```python
private_key = load_pem_private_key(...)
if not isinstance(
    private_key, (RSAPrivateKey, DSAPrivateKey, EllipticCurvePrivateKey, Ed25519PrivateKey, Ed448PrivateKey)
):
    # Report to user
else:
    serialize_key_and_certificates(..., key=private_key, ...)
```

But this seems cumbersome to hard-code and duplicate the list in every user program. Cryptography does not provide a constant containing accepted PKCS 12 key types, the type alias `_ALLOWED_PKCS12_TYPES` is private.

Maybe a public `tuple` like `ALLOWED_PKCS_KEY_TYPES = (RSAPrivateKey, DSAPrivateKey, ...)` should be added, so users can do `if isinstance(private_key, ALLOWED_PKCS_KEY_TYPES)`

**Comment by reaperhulk** [comment]
This type of situation is present in several places since `load_pem_private_key` and its ilk can load effectively anything, but our certificate signer, PKCS12 serialization, and others take a subset. We could define public tuples of these types (and use them in the `isinstance` checks to try to avoid accidental drift over time), but I'm not sure how we'd document this in a useful fashion.

**Comment by intgr** [comment]
Note that while this works in Python itself, the mypy type checker seems to have a bug when using isinstance() to constrain with Union type aliases:

* https://github.com/python/mypy/issues/14242
