### ISSUE TITLE
NameAttribute.value accepting bytes not documented

### ISSUE THREAD

**Issue by intgr** [pyca/cryptography#8052]
Cryptography type hints suggest that the `NameAttribute.value` attribute is `Union[str, bytes]`, but in documentation it's only documented to be `str`. (The constructor also accepts `Union[str, bytes]`, but the constructor is not documented at all)

https://cryptography.io/en/latest/x509/reference/#cryptography.x509.NameAttribute

Such union types tend to be fragile and messy to work with in code. Ideally the documentation would explain, under what conditions bytes can appear and how to deal with them. For example, can valid certs include binary attribute values that are not valid UTF-8?

**Comment by alex** [comment]
Good catch. The answer is that you can get a `bytes` when the OID is `X500_UNIQUE_IDENTIFIER` and the value in the raw X.509 is encoded as a `BIT STRING`.

**Comment by intgr** [comment]
Thanks 😊
