### ISSUE TITLE
Error when using the wheel with cryptography 38.0.3 and  static openssl 3.0.7

### ISSUE THREAD

**Issue by wqh17101** [pyca/cryptography#8058]
I  build a wheel with static openssl 3.0.7.
When i built openssl,i downloaded the openssl 3.0.7 and then i used this configure.
```
./config no-shared no-ssl2 no-ssl3 -fPIC --prefix=/usr/local/openssl
make && make install
```
Then i built wheel of cryptography by
```
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-binary :all: cryptography
```
It worked.

Howerer, after i installed this wheel. I run `from OpenSSL import SSL,crypto`.
I got
```
| from cryptography.hazmat.bindings.openssl.binding import Binding
| Binding.init_static_locks()
| cls._ensure_ffi_initialized()
| _openssl_assert(
| raise InternalError(
| cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126353445, lib=15, reason=524325, reason_text=b'error:07880025:common libcrypto routines::Reason(524325)')])
```
Python ENV:
pyOpenssl 22.0.0
cryptography 38.0.3 the one i built by myself.

**Comment by reaperhulk** [comment]
Building your own wheel requires significant understanding of C build toolchains. We can’t provide support given the innumerable ways this can go wrong. You should look at how our wheels are built (see wheel-builder.yml and our infra repository) to learn more about how to properly build your own wheel.

**Comment by wqh17101** [comment]
@reaperhulk Right, but i find that you do not use `no-shared ` in build_openssl.sh or wheel-builder.yml .
Howerer your wheel is built with a static openssl.
How to do that?

**Comment by wqh17101** [comment]
I see you use audit-wheel to add lib to wheel, but the cryptography.libs dir is empty in your released wheel. It means that auditwheel does nothing.

**Comment by reaperhulk** [comment]
We build our openssl in our infra images. They are static.

**Comment by wqh17101** [comment]
@reaperhulk OK. I see it. https://github.com/pyca/infra/blob/main/cryptography-linux/openssl-version.sh I will try next week.

**Comment by wqh17101** [comment]
OK. It works! 3.x openssl needs more config flag when building openssl staticly. Maybe you can update the doc to add more info about building cryptography with OpenSSL 3.x @reaperhulk

**Comment by reaperhulk** [comment]
Glad you got it working. We'd be happy to review a PR that provides better instructions for this.
