### ISSUE TITLE
Support for (cross-)signing certificates

### ISSUE THREAD

**Issue by KevinMGranger** [pyca/cryptography#8062]
It would be nice to support cross-signing certificates.

Motivation: I'm writing a tool that will cross-sign CA certs to add a name constraint extension. It's useful for company-internal private CAs that could issue way-too-broad certificates.

Essentially, I want the ability to replicate this workflow:

```console
$ tmpdir="$(mktemp -d)"
$ echo <<END > "$tmpdir/constraint.cfg"
[req]
prompt=no
distinguished_name=dist_name
req_extensions=extensions

[dist_name]
CN=$common_name

[extensions]
basicConstraints=critical,CA:true,pathlen:1
nameConstraints=critical,permitted;DNS:$constraint_domain
END

$ openssl x509 -in broad-ca.pem -CA my-ca.pem -CAkey my-ca.key -set_serial $random_serial -sha256 -extensions extensions -extfile "$tmpdir/constraint.cfg" -out constrained.pem
```

If the bindings necessary for this are similar, the ability to sign CSRs could be part of this work too.

**Comment by alex** [comment]
Creating and signing x.509 certificates are supported, and documented here: https://cryptography.io/en/latest/x509/

**Comment by KevinMGranger** [comment]
I don't see any method to sign the certificate on the Certificate class itself. Am I misunderstanding the workflow?

**Comment by reaperhulk** [comment]
Look at CertificateBuilder.

**Comment by KevinMGranger** [comment]
Ah, I didn't realize that you just copied the information into a new CertificateBuilder-- I thought it was some special workflow.
