### ISSUE TITLE
CertificateRevocationList.is_signature_valid does not allow ed448/ed25519 keys

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#8156]
Hi,

In #6276, CRLs where migrated to Rust. The following lines where added (I'm not sure if there was an equivalent to it before, but I couldn't find it) to `CertificateRevocationList.is_signature_valid()` (or rather, it's OpenSSL Backend implementation in `src/cryptography/hazmat/backends/openssl/backend.py`):

```python
    def _crl_is_signature_valid(
        self, crl: x509.CertificateRevocationList, public_key: PUBLIC_KEY_TYPES
    ) -> bool:
        if not isinstance(
            public_key,
            (
                _DSAPublicKey,
                _RSAPublicKey,
                _EllipticCurvePublicKey,
            ),
        ):
            raise TypeError(
                "Expecting one of DSAPublicKey, RSAPublicKey,"
                " or EllipticCurvePublicKey."
            )
```

Is there any reason for this restriction? I stumbled over this while trying out CRLs signed with Ed448 and Ed25519 keys. As an experiment I removed the lines and the validation did still work fine.

If possible, this should be extended properly to include `_Ed448PublicKey` and `_Ed25519PublicKey`, otherwise it should be documented in the method signature, which so far makes no mention of it.

I'm fine to open an MR either way as well, as long as you tell me what to do :-)

kr, Mat

**Comment by alex** [comment]
It should be fine to extend signature validation to cover those.

**Comment by alex** [comment]
In more detail: It looks like currently this method is implemented with OpenSSL: This means its maybe a case of simply needing to update the `isinstance` check, or maybe it's not supported because OpenSSL doesn't support it.

Regardless, in the medium term, we probably want to move this to our own signature validation code.

**Comment by mathiasertl** [comment]
@alex I can confirm itś working in the current main branch - thanks!
