### ISSUE TITLE
What's our story for Keccak (aka SHA-3)?

### ISSUE THREAD

**Issue by public** [pyca/cryptography#817]
I hear @tiran knows about these things? I think SHA-3 missed the 3.4 merge window for some reason?

OpenSSL seems unlikely to get SHA-3 until there's a TLS cipher suite that needs it. It might be nice to get SHA-3 support before whenever that is, perhaps via a dedicated backend?

**Comment by mgrabovsky** [comment]
Can this be reopened now?

**Comment by reaperhulk** [comment]
Until our C backends (specifically OpenSSL) support sha3 we don't have a good way to ship this. I will go ahead and reopen though because it's a relevant question now that it's finalized.

**Comment by skeuomorf** [comment]
@mgrabovsky Meanwhile, apparently Keccak's official website has a reference C implementation and a Python implementation http://keccak.noekeon.org/files.html

**Comment by alex** [comment]
We'll get this whenever it shows up in OpenSSL (or some other backend we support). Going to close this.

**Comment by mgrabovsky** [comment]
FYI: OpenSSL [added support](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1/NEWS) for SHA-3 in version 1.1.1.

**Comment by reaperhulk** [comment]
Yep, tracking landing support in https://github.com/pyca/cryptography/issues/4197
