### ISSUE TITLE
Memoryview is not allowed in symmetric encryption

### ISSUE THREAD

**Issue by mat-gas** [pyca/cryptography#8175]
Hi,

we'd like to be able to use memoryview in encrypt/decrypt functions for "data" to avoid memory copy of data buffers.

For instance, if we send "nonce + encrypteddata" on the network, we'd like to be able to use a memoryview instead of copying data around

example:

```python
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
import os

key = b'mysupersecretkey'
nonce = os.urandom(12)


data = b'1' * 4 * 1024 * 1024

enc = AESGCM(key)

encrypted = enc.encrypt(nonce, data, b"")

on_the_wire = nonce + encrypted

# send on_the_wire over the network

server_nonce = on_the_wire[:12]
server_encrypted = on_the_wire[12:]

memview = memoryview(on_the_wire)

# it works but we've copied almost all on_the_wire data in server_encrypted (so it consumes RAM)

dec = AESGCM(key)
decrypted_data = dec.decrypt(server_nonce, server_encrypted, b"")

assert(data == decrypted_data)

# memoryview works for nonce

dec = AESGCM(key)
decrypted_data = dec.decrypt(memview[:12], server_encrypted, b"")

assert(data == decrypted_data)

# doesn't work as data and associated data need to be bytes-like, not memoryview
dec = AESGCM(key)
decrypted_data = dec.decrypt(memview[:12], memview[12:], b"")

assert(data == decrypted_data)
```

This old PR (https://github.com/pyca/cryptography/pull/4621) states `key/iv/data` could be a bytelike object but `data` still cannot ("allow bytes-like for key/iv/data")

**Comment by alex** [comment]
I don't recall the reason we chose to exclude data/aad from supporting buffers. I think this would be a straightforward change to make. We'd certainly be happy to take a PR for it.

**Comment by reaperhulk** [comment]
It was likely just an oversight since the original request was about keying material. As Alex said, we'd be happy to review a change here.
