### ISSUE TITLE
regression: cannot subclasss x509.general_name.OtherName

### ISSUE THREAD

**Issue by huwcbjones** [pyca/cryptography#8186]
Prior to #6423, it was possible (unsure if this was intentional or not), to subclass `OtherName` to create custom OID types.

We have a subclass of `OtherName` that makes dealing with UPNs (User Principle Name) that are encoded in client certificates easier to deal with with less boilerplate.
It looks something like this
```py
class UPN(x509.general_name.OtherName):
    """UPN OID for Cryptography"""

    def __init__(self, value: str | bytes):
        if isinstance(value, str):
            value = encoder.encode(value, asn1Spec=char.UTF8String())
        super(UPN, self).__init__(MS_UPN_OID, value)
        if isinstance(value, bytes):
            name = str(decoder.decode(value, asn1Spec=char.UTF8String())[0])
        else:
            name = value
        self.name = name
```

The PR mentioned earlier ported the encoding of general names from Python to Rust.
In doing so, an `isinstance(o, OtherName)` check was effectively turned the encoding check to `type(o) is OtherName`.
This means you can't encode any subclasses of OtherName names anymore!

This feels like a regression to me :/

A workaround to make this work again is below, but this feels subpar.
```
def _make_upn(value: str):
    upn = UPN(value)
    return x509.general_name.OtherName(upn.type_id, upn.value)
```

**Comment by alex** [comment]
Subclassing `OtherName` was never a supported public API, you're intended to instantiate the type.

I'll also note that while the type is implemented in the `general_name` module, its documented location is `cryptography.x509.OtherName`: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.OtherName

**Comment by huwcbjones** [comment]
> Subclassing `OtherName` was never a supported public API, you're intended to instantiate the type.

AFAICT, there's nothing in the docs that touches this topic (hence we _did_ subclass `OtherName`)
If you aren't supposed to subclass, I'd expect some documentation with words to the effect of "don't do this", or something at runtime to prevent it.


I have no idea why we were importing from `general_name` instead of `x509` - we can fix that :)

**Comment by alex** [comment]
We document our supported public API, we cannot practically document the inverse (everything that's not supported), it's infinite!

Nowhere in our public APIs do we _ever_ ask users to subclass anything, there's not a single example of sub-classing in our docs!

**Comment by huwcbjones** [comment]
> We document our supported public API, we cannot practically document the inverse (everything that's not supported), it's infinite!

Completely agree! However Python is an OOP language and public classes are provided, people **will** subclass to add/augment functionaility and it would be naïve to assume otherwise.
Now, if this was in Java, the fix would be easy... smack a `final` in the class definition and be done with it.

From your PoV, what's the resolution to this issue?

**Comment by alex** [comment]
From my perspective this is a wontfix.

**Comment by huwcbjones** [comment]
Ok, if you don't think it's a regression and therefore won't fix it, please can you document it as such?
