### ISSUE TITLE
How to implement "openssl rsa -in ca.key -out key.pem" ?

### ISSUE THREAD

**Issue by L007530** [pyca/cryptography#8189]
Hey, just a question here. I have below code to create a private key, and how do I convert it to key.pem, that same as I execute "openssl rsa -in ca.key -out key.pem"?

```
        key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
        )
        # Write our key to disk for safe keeping
        with open("ca.key", "wb") as f:
            f.write(key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.BestAvailableEncryption(b"passcode123"),
            ))
```

**Comment by alex** [comment]
You can simply convert `key` to some other format with `private_bytes` and write it to a file.

**Comment by L007530** [comment]
Resolved.
Simply replaced
`encryption_algorithm=serialization.BestAvailableEncryption(b"passcode123"),`
with
`encryption_algorithm=serialization.NoEncryption(),`
and changed output file name

**Comment by alex** [comment]
Great
