### ISSUE TITLE
Add schnorr sign/verification to cryptography?

### ISSUE THREAD

**Issue by lambdaq** [pyca/cryptography#8202]
Been playing with nostr project, trying to tweak the protocol a bit, found that `secp256k1` is supported by cryptography project, the missing piece is schnorr algorithm. Any plans to support it?

I found that OpenSSL chose not  https://github.com/openssl/openssl/issues/8440  because 

> All algorithms and protocols should be recognized by a national or international standards body

**Comment by alex** [comment]
we use openssl for our implementation of cryptographic algorithms, so in the absence of that, we don't have a path to implementation.
