### ISSUE TITLE
Clearer error message for unsupported hashes in x509 signing

### ISSUE THREAD

**Issue by matan1008** [pyca/cryptography#8213]
Hey!
I am one of the maintainers of [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) - a pure python package to interact with iDevices.

First of all, I want to thank you for your amazing package.

Second, we recently faced an issue with creating certificates for communication with devices (a generic ValueError arises). After some debugging, we understood that it is related to the drop of SHA1 hash when building a certificate - https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/ca.py#L20

We would really appreciate your help with the following:
- Is there any way to keep using your package with SHA1 hashes?
- Could you please raise a more specific exception than ValueError?
- Do you have any suggestion on the subject?

(Could you please revert the changes? 😅)

Thanks a lot!

**Comment by alex** [comment]
No, we no longer support SHA1 signatures because they cannot be used securely. SHA1 is broken for cryptographic purposes.

Our exception contains a pretty explicit message: `"Hash algorithm sha1 not supported for signatures"`

We will not be reverting the change.

**Comment by matan1008** [comment]
I understand that SHA1 is not secure, but some old devices requires it so I thought it might be a good idea to ask you for suggestions ¯\_(ツ)_/¯
Anyway, catching an error by its message is quite inconvenient - will you accept a PR that raises more specific error?

Thanks for your fast response!

**Comment by alex** [comment]
Do you have an idea of what sort of exception you'd prefer?

If we changed the type signature from `typing.Optional[hashes.HashAlgorithm]` to `typing.Union[SHA256, SHA384, ...]` would that help, do you use mypy?

**Comment by matan1008** [comment]
I would prefer something like the `UnsupportedAlgorithm` or any exception class that subclasses ValueError to something more explicit.

We don't use mypy so changing the typing wouldn't help (and in my humble opinion it goes against the open-closed principle so I don't think its a good idea)

**Comment by alex** [comment]
Well, signing can only be implemented for known types, because it requires mapping to OIDs and parameters, so changing the type doesn't restrict what's possible, it just makes it clearer.

**Comment by reaperhulk** [comment]
Reopening this because I think we haven't made a call on raising a different error here and that doesn't require reporter input.
