### ISSUE TITLE
ANSIX923 unpadding fails on a correct input

### ISSUE THREAD

**Issue by Tijs-B** [pyca/cryptography#8235]
ANSIX923 unpadding fails on an input where the padding bytes (not the last byte) are not `\x00`. According to the [wikipedia page](https://en.wikipedia.org/wiki/Padding_%28cryptography%29#ANSI_X9.23) and [IBM docs](https://www.ibm.com/docs/en/linux-on-systems?topic=processes-ansi-x923-cipher-block-chaining) these bytes can be random, so unpadding data padded with random bytes instead of `\x00` bytes, should work.

Specifically, unpadding `b"111111111122222\x06"` with block size 128 should result in `b"1111111111"`. Right now, the library raises a `ValueError: Invalid padding bytes.` exception. 

# Platform info

- python: 3.10.9
- cryptography: 39.0.1
- cffi: 1.15.1
- pip: 23.0
- setuptools: 65.6.3

I installed `cryptography` by executing `pip3 install cryptography` in a new virtual environment.

# Steps to reproduce

Install `cryptography` 39.0.1 in a new virtual environment. Then in a python shell:

```py
>>> from cryptography.hazmat.primitives import padding
>>> unpadder = padding.ANSIX923(128).unpadder()
>>> padded_data = b"111111111122222\x06"
>>> data = unpadder.update(padded_data) + unpadder.finalize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/var/folders/n7/pc6wh52j4zz80myq2xydblpr0000gn/T/tmp.gxTXlu6q/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/padding.py", line 218, in finalize
    result = _byte_unpadding_check(
  File "/private/var/folders/n7/pc6wh52j4zz80myq2xydblpr0000gn/T/tmp.gxTXlu6q/venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/padding.py", line 101, in _byte_unpadding_check
    raise ValueError("Invalid padding bytes.")
ValueError: Invalid padding bytes.
```

Unpadding `b"111111111122222\x06"` should result in `b"1111111111"`. The last byte is `\x06` which means there are 6 bytes added to the end. Removing those 6 bytes (`22222\x06`) results in `1111111111`.

# Steps to resolve

I'm not familiar with the codebase but I suspect there is an error in the `check_ansix923_padding` rust function in `lib.rs`.

**Comment by reaperhulk** [comment]
According to the [IBM page](https://www.ibm.com/docs/en/linux-on-systems?topic=processes-ansi-x923-cipher-block-chaining) the X9.23 specification has been withdrawn. When we originally landed support for this (https://github.com/pyca/cryptography/pull/2736) we only had wikipedia and [the version](https://en.wikipedia.org/w/index.php?title=Padding_(cryptography)&oldid=702627998) at the time stated null bytes only.

Looking around I see bouncycastle doesn't care, a few random golang impls do, MS's implementation does (as Alex notes above), libtomcrypt had an implementation that didn't care but has entirely removed it, et cetera.

Given that this is a withdrawn standard where we can't get the definitive specification and also it's inconsistently implemented across numerous cryptography providers I'd prefer to deprecate and remove this over guessing about the specification.

**Comment by Tijs-B** [comment]
Alright, @reaperhulk 's explanation sounds reasonable. I will write my own implementation myself for my use case and won't expect a patch in this library. Thank you both for your very quick answers and for the work you put in this project. Should I close this issue?

**Comment by alex** [comment]
Sounds good. Thanks
