### ISSUE TITLE
Missing wheel for pypy38 for cryptography 39.0.1

### ISSUE THREAD

**Issue by krdenison** [pyca/cryptography#8251]
There are pre-built wheels for pypy38 for version 39.0.0 and earlier but the latest release (39.0.1) doesn't have one. Was this an intentional change?
https://pypi.org/simple/cryptography/

Looking for this cryptography-39.0.1-pp38-pypy38_pp73-manylinux_2_28_x86_64.whl

**Comment by reaperhulk** [comment]
Thanks for the report, this is a bug in our wheel builder yaml: https://github.com/pyca/cryptography/blob/d7d698a1565f9ea60aaf22b8a59083384db407c6/.github/workflows/wheel-builder.yml#L87 (that line shouldn't exist)

**Comment by reaperhulk** [comment]
Fixed in #8252 and wheels uploaded, sorry about that!

**Comment by krdenison** [comment]
Thank you for the super fast turn around.
