### ISSUE TITLE
sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [pyca/cryptography#8284]
The sdist package at PyPI is missing the `tox.ini` file.  Please add the file to the sdist to make downstream testing easier.  Thank you.

**Comment by alex** [comment]
We've never (to my memory) included `tox.ini` in our sdists, and if we did, it wouldn't have been tested in that configuration. Can you explain more about your use case?

**Comment by mtelka** [comment]
I'm packaging cryptography for OpenIndiana.  To do so I use the sdist from PyPI.  To make sure the constructed package is correct I need to test it, so it would be great to have the `tox.ini` file handy in the sdist.

**Comment by alex** [comment]
Ok. I've thrown up a PR for this.
