### ISSUE TITLE
Error while following: Using your own OpenSSL on Linux instructions

### ISSUE THREAD

**Issue by Jpgig** [pyca/cryptography#8299]
I am following instructions as noted on the below page for Using your own OpenSSL on Linux instructions
https://cryptography.io/en/latest/installation/#build-on-linux
I followed these steps:
set -e

OPENSSL_VERSION="VERSIONGOESHERE"
CWD=$(pwd)

virtualenv env
. env/bin/activate
pip install -U setuptools
pip install -U wheel pip
curl -O https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
tar xvf openssl-${OPENSSL_VERSION}.tar.gz
cd openssl-${OPENSSL_VERSION}
./config no-shared no-ssl2 no-ssl3 -fPIC --prefix=${CWD}/openssl
make && make install
cd ..
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-binary :all: cryptography

This generates the below 2 files:
![image](https://user-images.githubusercontent.com/115164852/219175101-103f3ac3-dc67-403b-9728-a75a8373c02c.png)
I installed cryptography-39.0.1-cp310-cp310-linux_aarch64.whl file using pip install cryptography-39.0.1-cp310-cp310-linux_aarch64.whl

While importing the cryptography module getting the below error:

![image](https://user-images.githubusercontent.com/115164852/219175502-a98c4250-61e5-4232-a55e-32b5b91f833b.png)

I searched the symbol in _openssl_abi3.so file and got the below message.
![image](https://user-images.githubusercontent.com/115164852/219175316-398510b4-b70b-41a1-9b3d-d979d623972a.png)

Can anyone please help how to resolve this issue?

Thanks,
Jiten

**Comment by reaperhulk** [comment]
`FIPS_mode_set` is only bound if the C preprocessor thinks the OpenSSL version is < 3. This suggests that your actual CFLAGS contain a path to OpenSSL < 3. It's possible `pip` is adding paths you don't want so you may want to try following the way we do it in our wheel builder: https://github.com/pyca/cryptography/blob/main/.github/workflows/wheel-builder.yml#L106-L117

**Comment by Jpgig** [comment]
Thanks a lot for your quick response. I am not entirely familiar with the wheel-builder.yml file.
I made the below changes but still getting the same results.(unable to map the FIPS_mode)
![image](https://user-images.githubusercontent.com/115164852/219389249-484f4973-3e18-4ae1-8726-7e19d6dbaf97.png)

I tried the below FLAGS:
![image](https://user-images.githubusercontent.com/115164852/219388652-b7454850-d7ad-4b15-bd1f-d06bd5ad3877.png)
Is it possible to share the exact steps for "Using your own OpenSSL on Linux"?

**Comment by reaperhulk** [comment]
It's generally infeasible to debug all possible issues with C toolchains, but if you give us a dockerfile to reproduce this I can take a bit of a closer look.

**Comment by Jpgig** [comment]
Thanks for your reply. I don't have a docker file and am also not much familiar with docker. 
Is it possible to share steps with me from where the openssl file is taken by the build system and is there any way I can give the path of my openssl build?

**Comment by reaperhulk** [comment]
To debug this we need a reproducible environment (a linux container). I've shown you examples of exactly how we do it in our CI to successfully build and link a static wheel with a custom OpenSSL, but if you want additional assistance you'll need to go down that path. Building and linking your own version of this is not trivial and does require a significant understanding of toolchains outside of Python, which is why we produce wheels for users who don't possess that expertise.

**Comment by Jpgig** [comment]
Hi Paul, I compiled the openssl version used by cryptography 3.0.8. I looked for the FIPS_mode function but could not find it.
![image](https://user-images.githubusercontent.com/115164852/219490322-d2813cff-41b1-4181-bbc4-64573a0bc57b.png)

In this case, I'm not sure how _openssl.abi.so files get the FIPS_Mode function if it's not part of openssl.

**Comment by alex** [comment]
`FIPS_mode` is not expected to exist in OpenSSL 3.

**Comment by Jpgig** [comment]
Thanks, Alex. As it's not part of openssl 3, how does it get added to _openssl_abi3.so generated by the cryptography build process?

**Comment by alex** [comment]
As @reaperhulk said: cryptography detects the version of OpenSSL it is being compiled against while being built, and then links against OpenSSL when imported.

The symptoms you are seeing indicate that you are compiling against one version of OpenSSL and then linking against a different one.

**Comment by Jpgig** [comment]
Correct I am using a different version of openssl.
I am using the below instruction to link cryptography to that openssl version but somehow it is failing.

virtualenv env
. env/bin/activate
pip install -U setuptools
pip install -U wheel pip
curl -O [https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz](https://www.openssl.org/source/openssl-$%7BOPENSSL_VERSION%7D.tar.gz)
tar xvf openssl-${OPENSSL_VERSION}.tar.gz
cd openssl-${OPENSSL_VERSION}
./config no-shared no-ssl2 no-ssl3 -fPIC --prefix=${CWD}/openssl
make && make install
cd ..
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-binary :all: cryptography

**Comment by alex** [comment]
Your paths are wrong, openssl is in `${CWD}/openssl-${OPENSSL_VERSION}/` but you're putting `${CWD}/openssl/` on the include path. Thus OpenSSL is falling back to your global install.

**Comment by alex** [comment]
I see this is a bug in our docs, I'll submit a PR fixing

**Comment by Jpgig** [comment]
This command is installing openssl to the current working directory/openssl.
 ./config no-shared no-ssl2 no-ssl3 -fPIC --prefix=${CWD}/openssl

and the below command is using openssl from that path.
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-binary :all: cryptography

So I think this is correct.

**Comment by alex** [comment]
Because you did `cd ..` you are no longer in the original `CWD`. You can see OpenSSL is installed at `openssl-3.0.8/openssl/include/`.

**Comment by alex** [comment]
Sorry, that's not quite right, because of the environment variable being assigned above.

**Comment by Jpgig** [comment]
1) CWD=$(pwd) sets variable CWD as the current directory.
e.g I am in the home directory then my CWD = /home
2) this command downloads openssl to /home directory 
curl -O [https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz]
3) This command sets the openssl installation to /home/openssl directory
/config no-shared no-ssl2 no-ssl3 -fPIC **--prefix=${CWD}/openssl**
4) This command takes the openssl from /home/openssl and that's correct.
CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --no-binary :all: cryptography

**Comment by reaperhulk** [comment]
I just ran the exact script in our docs using OpenSSL 3.0.8 in an Ubuntu 22.04 container where I installed just the set of dependencies required to do this and it built a correct wheel that statically linked against the OpenSSL in question.

I then did the same with Ubuntu 20.04 (which does not ship with OpenSSL 3 by default). I installed libssl-dev (which installed the 1.1.1 headers into the include path even though we want to use OpenSSL 3!). After getting past a wheel issue related to C locales I still successfully built a wheel with a statically linked custom OpenSSL.

While doing this I did decide to improve the script very slightly, but it isn't a material change (https://github.com/pyca/cryptography/pull/8392).

So, as best I can tell the instructions remain correct and whatever problem you're having looks to be environment specific. I encourage you to learn how to build containers so you can build this yourself in a more controlled environment, but we can't provide further support here.
