### ISSUE TITLE
BestAvailableEncryption change over time

### ISSUE THREAD

**Issue by NonOriginalNameReally** [pyca/cryptography#8371]
Hi. In the docs covering export of private keys there is a note about the `BestAvailableEncryption` that its encryption algorithm can be changed over time.

There is a question: will it be possible to decrypt and recover old serialized private key if `BestAvailableEncryption` backend will be changed in future (with a latest lib version)?

Does serialized keys store backend schema?

Regards.

**Comment by reaperhulk** [comment]
Serialized keys have OIDs in them describing their encryption and we are capable of decrypting any key OpenSSL supports. At some point in the future legacy encryption may be dropped by us or OpenSSL, but if we choose to do this there will be a long warning period.

**Comment by NonOriginalNameReally** [comment]
@reaperhulk I understand. Thank you for your quick answer.

Side one: is there any way to see what backend is currently `BestAvailableEncryption`?

**Comment by reaperhulk** [comment]
We don't have a way to inquire about this at the moment. We set it to OpenSSL's defaults, which vary by version (and can't be directly interrogated by their own APIs). That said, in OpenSSL 3.0 (which is what our current wheels ship against, and the only time in the last ~5-10 years that OpenSSL has changed their own defaults) this is AES-256-CBC IIRC.

**Comment by NonOriginalNameReally** [comment]
@reaperhulk Thank you.
