### ISSUE TITLE
encode_point was removed but remains in documentation

### ISSUE THREAD

**Issue by encukou** [pyca/cryptography#8374]
The EllipticCurvePublicNumbers.encode_point method was [removed](https://cryptography.io/en/latest/changelog/#v39-0-0) but [is still in the docs](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePublicNumbers.encode_point).

**Comment by reaperhulk** [comment]
Thanks for the report!
