### ISSUE TITLE
Cryptography update broke exchangelib

### ISSUE THREAD

**Issue by ray73864** [pyca/cryptography#8400]
Recently upgraded the cryptography library on my debian 10 webserver which was using exchangelib to connect to an on-premises MSExchange 2019 server in order to download latest attachments, however since the upgrade, that has completely broken.

I posted a bug report to the exchangelib issue tracker, however the developer pointed me here instead.

Original bug report is at https://github.com/ecederstrand/exchangelib/issues/1170

Because my python3 code for exchangelib does a lot of stuff (connecting to the exchange server, downloading attachments, renaming them, uploading them to an SFTP server), I created a test version which had only the basics of connecting to the exchange server, and that too failed.

What's interesting is that I have 2 web servers, my development one and my production one, the development web server runs Debian 11, the production web server runs Debian 10.

The Debian 11 server has python3-cryptography v3.3.2-1
The Debian 10 server has python3-cryptography v2.6.1-3+deb10u3

I am currently running my python script on my development webserver where it works 100% in connecting to our exchange server, it's just the production webserver which isn't working.

**Comment by alex** [comment]
Looking at this code, I'm almost positive that debian incorrectly backported a fix, and that this bug is with debian, not us. Debian does not package our exact code, and in fact applies their own patches. In this case I'm almost positive their patch has a bug.

Can you put a full copy of `/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py` in a gist or somewhere else I can see it?

**Comment by alex** [comment]
Actually, can you just try updating your debian packages (`apt-get update && apt-get upgrade`), it looks to me like they uploaded a fix for this: https://tracker.debian.org/news/1422813/accepted-python-cryptography-261-3deb10u4-source-amd64-all-into-oldstable/

**Comment by ray73864** [comment]
From what I can tell, upgrading to the newer version appears to have fixed the problem.

Thanks for that, I tried everything initially as I couldn't quite work it out, I knew it had to be the upgrade I initially did, just not sure why at the time.

Between yourself and the exchangelib dev, I have disabled my cronjob for exchangelib on my devserver and re-enabled it on the production one.
