### ISSUE TITLE
Secure wipe with memoryview, is it even possible?

### ISSUE THREAD

**Issue by johanrex** [pyca/cryptography#8425]
From the documentation under "Known security limitations" -> "Secure memory wiping":

> Many cryptography APIs which accept bytes also accept types which implement the buffer interface. Thus, users wishing to do so can pass memoryview or another mutable type to cryptography APIs, and overwrite the contents once the data is no longer needed.

My assumptions is that if I want to do secure wipe of memory that stores a secret key, only mutable objects can be involved in creating the secret key. If immutable objects are involved in creating the secret key then I can't securely wipe that memory with python. If these assumptions are correct I have some questions. 

1. I'm struggling to create a memoryview to pass to e.g. Fernet.encrypt that fulfills those assumptions. Is it even possible to create a memoryview that relies only on mutable objects with python? 

2.  If I somehow manage to create a memoryview where all memory involved in creating the secret key can be securely wiped, can I count on the Cryptography library to clear all memory it allocates to store the secret key,

**Comment by alex** [comment]
1. Depends where your data initially resides. For example, if you had contents in a file you could use `file.read_into()` to have it copied directly into a `bytearray`.
2. Most `cryptography` APIs do not allocate any of their own copies of data, and thus do not need to do anything. However, there a few places we allocate copies, and they do not all involve a secure wipe -- for example, in `fernet` keys are base64 encoded and Python does not provide any way to base64 decode into a `bytearray`, thus all keys go via `bytes` which we have no ability to wipe.

In general I consider this secure wiping to be a fairly marginal concern, but hopefully this detail is helpful.

**Comment by johanrex** [comment]
@alex This is absolutely useful details. Very clear. Thank you. 

Indeed, if keys go into a bytes object internally anyway it's of limited use for me to go to great lengths to protect the key in my own code. 

But I'm also curious. I tried to create a random one-time symmetric key without involving any immutable objects but couldn't figure it out. Do you see any way of generating a cryptographically secure key (for Fernet.encrypt) with only mutable objects? All the functionality I looked at used immutable objects.

**Comment by alex** [comment]
Because of the base64 issue I described, there's not a way to use exclusively mutable keys with fernet.

**Comment by johanrex** [comment]
@alex Yes, I realise that. It was more of a general question. Unrelated to the cryptography package. 

But I also realise this is not the place to ask that question. :)
