### ISSUE TITLE
interface for backends that support GCM table acceleration

### ISSUE THREAD

**Issue by dvanduzer** [pyca/cryptography#846]
Some implementations of GCM allow acceleration by computing a table per key. The table state needs to be preserved between operations, but the IV must be reset each time.

This use case might be covered by a new AEADEncryptionContext that includes reset(), update_iv() and update_aad() methods. However EAX and GCM are different enough that a different approach might make more sense.

**Comment by reaperhulk** [comment]
I'm going to close this for now. Implementing generic support for this is quite complex and increasingly unnecessary as hardware supporting CLMUL rapidly becomes more widespread.
