### ISSUE TITLE
Support for py3.9, py3.10, py3.11 ?

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [pyca/cryptography#8462]
Is the current version of cryptography (39.0.2) support py3.9, py3.10, and py3.11?

**Comment by reaperhulk** [comment]
As stated in our documentation, we currently support 3.6+. https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version might also be relevant, depending on what triggered this question.
