### ISSUE TITLE
Enable OIDC publishing

### ISSUE THREAD

**Issue by reaperhulk** [pyca/cryptography#8494]
Copied from #8483 

Plan of action:

- [x] Add support for `workflow_dispatch` and publishing to Test PyPI
- [x] Get ownership of the Test PyPI package
- [x] Merge
- [x] Do a test run publishing to Test PyPI, rinse and repeat until successful
- [x] Re-enable the `workflow_run` path
- [x] Configure on PyPI. (`cryptography` and `cryptography-vectors`)

**Comment by alex** [comment]
And we're good here!
