### ISSUE TITLE
Want to apply more security on top of FPE

### ISSUE THREAD

**Issue by prk2331** [pyca/cryptography#8501]
Hi team, can you please guide me on how I can apply more security on top of FPE? I want deterministic encryption.
I am thinking I need to add more security on top of this. What did you suggest by seeing this code ? Can we apply SHA, aur any other algo on top of it ?
I am Angular developer developer , newbie in python django.

cipher text:
      1df39d71fcb53c67c1ffe88dc862232664c55b4de654729306229ffe2b5b1f10
That much long cipher text im getting

Any guidance

```
import pyffx
import hashlib
import os 
import string

# Define the encryption key and tweak size
KEY_SIZE = 32
TWEAK_SIZE = 8

# Define the number of characters in the token
TOKEN_LENGTH = 128

# Generate a key from a passphrase
def generate_key(passphrase):
    key = hashlib.sha256(passphrase.encode()).digest()
    print(f"Generated key: {key}")
    return key

# Encrypt a plaintext value using FPE
def encrypt(plaintext, key, tweak):
    alphabet = string.ascii_lowercase + string.ascii_lowercase + string.digits
    # Create the FFX object with the desired configuration
    ffx = pyffx.String(key, alphabet=alphabet, length=len(plaintext))
    print(f"FFX object created with key {key} and tweak {tweak}")
    
    # Encrypt the plaintext using FPE
    ciphertext = ffx.encrypt(plaintext)
    print(f"Plaintext encrypted to ciphertext: {ciphertext}")
    # Return the token
    return ciphertext

def decrypt(token, key, tweak):
    return token

    
plain_value = "ramesh"
key = generate_key("mysecretkey")
tweak = os.urandom(TWEAK_SIZE)
encrypted_text = encrypt(plain_value, key, tweak)
print("**********")
print(encrypted_text)
```

**Comment by alex** [comment]
It's not clear what question you're asking, but we are not the authors of `pyffx`, so we cannot provide support in how to use it.

We're also not in a position to provide advice on the design of cryptographic protocols. In general "apply more security on top" doesn't mean anything.

**Comment by prk2331** [comment]
hi @alex  thanks for giving me your time to reply.
My aim is to just make my cipher text more powerful, which is provided by PyFFX (FPE) (just like two layers of encryption), before inserting it into the database.

Can you please help me with how to further encrypt my cipher (I don't want a single-sided hash) so that reverse-engineering is possible and I can get my original message whenever required?
for GDPR compliance Sake i am doing this

Notes:
      Using FPE becuase i want same cipher of same plain text.

**Comment by reaperhulk** [comment]
This project's issue tracker isn't the right place to seek cryptographic design or compliance advice like this, sorry.
