### ISSUE TITLE
Explore splitting off or conditionalizing rust-dependent (X509, etc) components

### ISSUE THREAD

**Issue by ngie-eign** [pyca/cryptography#8513]
Many custom builders of FreeBSD build packages from scratch for distributions and such. Some folks leverage QEMU builders when building the packages, which makes the addition of rust to the build more demanding from a space and compute perspective.
An ask from some folks in the FreeBSD community is to make the Rust dependent (X509, etc) portions of the build conditional to make this possible. An alternative approach might be to split off the rust-dependent artifacts into their own respective project, given that there's an ask here to add more Rust-dependent code to the repo.

**Comment by alex** [comment]
I'm not sure I understand what you're asking for.

Are you asking us for us to package things different, or to make it possible to use pyca/cryptography without Rust?

**Comment by karolyi** [comment]
The reporter means, FreeBSD packages are built on VMs running on QEMU. Apparently (the way I understood it), rust is unable to build with QEMU, thus FreeBSD is unable to provide an up-to-date py-cryptography package.

See this comment for details: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254853#c33

Because of this, the entire ecosystem that uses py-cryptography, will run with a backported, increasingly outdated package. Lots of dependent software will break over time. One example is py-matrix-synapse, which because of a necessary patch, is now hardcoded to use TLS1.2.

See:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266680

Hence this issue report.

**Comment by alex** [comment]
If Rust can't build under qemu, that sounds like a qemu bug (or maybe a rust bug)?

This package depends on Rust for core functionality, and it's becoming more and more central regularly (see #6634). So making it somehow optional isn't an option.

**Comment by ngie-eign** [comment]
> If Rust can't build under qemu, that sounds like a qemu bug (or maybe a rust bug)?

I don't know the full details, but I can inquire with some of the other folks in the project to better understand why rust cannot be built with QEMU on FreeBSD.

For [appliance] consumers of FreeBSD, much like my $work, we compile software packages from scratch because the ABI in our custom FreeBSD variant isn't guaranteed to be compatible with FreeBSD. Compiling Rust from scratch each time is a costly operation in terms of time and CPU, and it greatly increases the scope for upgrading FreeBSD to a version of py-cryptography, py-openssl, etc, that supports OpenSSL 3.

If there's any way where that could be made optional somehow that would save us a considerable amount of resources over the long run.

I understand that this could be solved internal to FreeBSD and $work via various means, but this is a costly set of technical problems that unfortunately cannot be addressed easily right now due to lack of resources (people, compute, $) :(.

> This package depends on Rust for core functionality, and it's becoming more and more central regularly (see #6634). So making it somehow optional isn't an option.

Is there any possible way that this code could be modularized via a conditional argument/manifest? I would be more than happy to supply patches if there's interest in incorporating them into the project, but if not... I suppose FreeBSD will have to maintain a larger port patchset which achieves this.

I understand the ask is potentially large, but it would make maintaining py-cryptography easier for downstream packagers. I was hoping for something similar to how py-cryptodome has a single repo, but from it produces artifacts for py-cryptodome, py-cryptodomex, and py-cryptodome-test-vectors. I empathize with the complexity this introduces in terms of development and support, but having something supported by py-cryptography (even if it's not the default), would allow FreeBSD, et al, to better contribute patches back to the py-cryptography community.

**Comment by alex** [comment]
We do distribute pre-built wheels for many platforms. There's currently not a standard for FreeBSD wheels for Python (nor do we have freebsd in CI), but theoretically we could be publishing pre-built artifacts.

To your point, it's not clear _how_ you want us to modulerize. At this point Rust code is used in x509, but also PKCS7, symmetric padding, linking OpenSSL, and soon X25519. It's not like the boundary would be "oh x509 is a seperate package", it'd be that cryptography was missing tons of core functionality (e.g., symmetric padding is required by fernet).

**Comment by ngie-eign** [comment]
> We do distribute pre-built wheels for many platforms. There's currently not a standard for FreeBSD wheels for Python (nor do we have freebsd in CI), but theoretically we could be publishing pre-built artifacts.
> 
> To your point, it's not clear _how_ you want us to modulerize. At this point Rust code is used in x509, but also PKCS7, symmetric padding, linking OpenSSL, and soon X25519. It's not like the boundary would be "oh x509 is a seperate package", it'd be that cryptography was missing tons of core functionality (e.g., symmetric padding is required by fernet).

Yikes... ok, these are fair points--something I was genuinely concerned about when filing this issue. I'd be happy to help with the CI end of things if the pyca would be interested in it. Cirrus CI has FreeBSD images which can be used for this purpose. I don't think it will necessarily help with all of the architectures/usecases, but it could avoid potential future breakage.

**Comment by reaperhulk** [comment]
We're happy to consider FreeBSD, but we're very performance and maintenance cost sensitive in our CI. Even if we were to add FreeBSD, it wouldn't prevent issues with users who (for whatever reason) need to repeatedly build rustc from source.

Ideally we could add FreeBSD via nested virt, but I believe that's only supported on the macOS builders (which have limited parallelism) or the larger for-pay Linux instances (https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/)

**Comment by karolyi** [comment]
Please keep this issue open until FreeBSD manages to find a solution for the problem (or else I'm gonna need to bump it each time such bots try to close it).

The related FreeBSD bug is https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254853

**Comment by alex** [comment]
We generally only keep open issues when there's some action we can take to resolve it. Since removing our dependency on Rust isn't on the table here, is there some other action for us to consider here?

**Comment by ngie-eign** [comment]
@karolyi : I don't think there's much that can be done, minus forking this project (which I don't want to do and don't have the time for), or heavily hacking the port to produce a rust and non-rust flavor of it.
