### ISSUE TITLE
A few minor flaws in main branch

### ISSUE THREAD

**Issue by Tarnum-tst** [pyca/cryptography#8570]
Hi @alex ,

1. cxx-related crates (cxx, cxxbridge-flags, cxxbridge-macro & cxx-build) should be reverted from 1.0.92 back to 1.0.86 because of MSRV 1.60
2. d74bc0dc3b7e2c576fdf87b6ee40a3db81b2051b should be reverted because of 'warning: unused manifest key: package.rust-version' in MSRV 1.48 (deprecated but still supported currently).
3. Still one warning remains during compilation process of CFFI module:
```
warning: C:\Python37\crypmain\src\rust\target\i686-pc-windows-gnu\release\build\cryptography-rust-77091ad8c3563d12\out\_openssl.c:575: warning: "WIN32_LEAN_AND_MEAN" redefined
warning:   575 | #define WIN32_LEAN_AND_MEAN
warning:       |
warning: <command-line>: note: this is the location of the previous definition
```
The easiest way to get rid off:
```
#ifndef WIN32_LEAN_AND_MEAN
# define WIN32_LEAN_AND_MEAN
#endif
```
Thanks!

**Comment by alex** [comment]
Thanks for the report!

I think for (1) we missed this because teh dep is only used by haiku, which we obviously don't test. We'll still revert it.

2. I don't think we'll revert this, if it's only producing a warning.

3. Yes this seems easy enough.

**Comment by reaperhulk** [comment]
Okay we've done 1 and 3, closing as completed, thanks for the reports 😄
