### ISSUE TITLE
Sort out our optional backend story

### ISSUE THREAD

**Issue by public** [pyca/cryptography#858]
Currently we have 2 backends. CommonCrypto and OpenSSL.

OpenSSL is mandatory. `is_available` always returns True for it. CommonCrypto is mandatory on >= OS X 10.8.

If we want to add certain new features (e.g. #856) it seems likely we'd want to make any new backend requirements optional. e.g. Making people install libsalt so they can run PyOpenSSL would be annoying.

We don't currently have a good way to do feature detection for things like this. Do we search /usr/include? (What about Windows?) Or do we use entrypoints and put new backends in their own packages? Or something else entirely?

**Comment by alex** [comment]
Current thinking is that multiple backends were a mistake. Going to close this.
