### ISSUE TITLE
UMAC support

### ISSUE THREAD

**Issue by public** [pyca/cryptography#861]
OpenSSH 4.7 added support for the [UMAC](http://en.wikipedia.org/wiki/UMAC) algorithm and it is now the preferred MAC algorithm in OpenSSH.

Sadly (in my brief search) I can't find any non-OpenSSH implementations of it that look at all sensible for us to use.

**Comment by reaperhulk** [comment]
I'm going to close this as we haven't had a user request for it in almost 2 years.
