### ISSUE TITLE
Fernet allows to decrypt values using incorrect (different) key

### ISSUE THREAD

**Issue by michalmalus** [pyca/cryptography#8660]
* Versions of Python, ``cryptography``, ``cffi``, ``pip``, and ``setuptools`` you're using

Python 3.10
cryptography 40.0.1
cffi 1.15.1
pip 23.0.1
setuptools 67.6.1

* How you installed ``cryptography``

pip install cryptography

* Clear steps for reproducing your bug

key and incorrect_key differ (1 but last character is different) - I would expect the final assertion to be true (values should not be equal) but it is not - value == decrypted_value

```
from cryptography.fernet import Fernet

key = "0T2I6VHUlGc5z2rLffrhUfwWRIs2ffoIoqb2qyYJkzY="
cipher_suite = Fernet(key)

value = "abc"
encoded_value = cipher_suite.encrypt(bytes(value, "utf-8"))

incorrect_key = "0T2I6VHUlGc5z2rLffrhUfwWRIs2ffoIoqb2qyYJkzZ="
cipher_suite2 = Fernet(incorrect_key)

decrypted_value = cipher_suite2.decrypt(encoded_value).decode("utf-8")

assert value != decrypted_value

```

**Comment by alex** [comment]
These keys base64 decode to the same value, therefore it's expected that they would produce the same result:

```
>>> base64.b64decode("0T2I6VHUlGc5z2rLffrhUfwWRIs2ffoIoqb2qyYJkzY=") == base64.b64decode("0T2I6VHUlGc5z2rLffrhUfwWRIs2ffoIoqb2qyYJkzZ=")
```

**Comment by michalmalus** [comment]
That was quick! Thank you for the explanation :)
