### ISSUE TITLE
[feature request] take back ssl binding "SSL_CTX_set_cert_store"

### ISSUE THREAD

**Issue by SeaHOH** [pyca/cryptography#8675]
I am using `SSL_CTX_set_cert_store` which allow me could maintain only one strore. This is very convenient and functional, but removed from v40. Please, could you take it back to new releases?

**Comment by reaperhulk** [comment]
Do you use this in conjunction with pyopenssl? If so, it would be desirable to add it as a feature there and use the binding from pyopenssl. That way we understand how it’s being used, can test for it, etc.

**Comment by SeaHOH** [comment]
@reaperhulk Yes, I use it with pyOpenSSL. And, you suggestion me make a feature/pull request to pyOpenSSL project (not its dependency). Do I understand correct? If so, could you transport this issue to pyOpenSSL repository? I will change the title then.

**Comment by SeaHOH** [comment]
> This is a multi-step process, so we'll need work on both sides:
> ...

So, we donot need to transport this issue. OK, let's go on.

I think a context configurable cert store will be most useful. There is already `SSL.Context.get_cert_store` here, why not a `SSL.Context.set_cert_store`?

**Comment by mhils** [comment]
FWIW for @mitmproxy we're reusing one SSL.Context for all client connections. `SSL.Connection` nowadays has `use_certificate` and `use_privatekey` methods which make that possible. Not sure if that would be an alternative in your case. :)

**Comment by SeaHOH** [comment]
@mhils Thanks for your suggestion. But I think session reuse will not be work between different servers in your case.

**Comment by reaperhulk** [comment]
Having an SSL.Context.set_cert_store seems reasonable to me. Let's assume that's what we're going to do. Do you have time to implement that on the pyOpenSSL side? As Alex mentioned we need to add the binding here and then add the API in pyOpenSSL. Complicating matters a bit is that we also need to fix a pyOpenSSL test issue, but we can work around that during dev. We'll also have to have an extra branch in `set_cert_store` to handle the versions that don't bind this function until such time as we require >=40.0.3 (or whatever version we release the re-added binding in). This is being done in https://github.com/pyca/pyopenssl/pull/1202 as well.

**Comment by SeaHOH** [comment]
> Do you have time to implement that on the pyOpenSSL side?

Me? I can write the funticon code, but I am not good at English as you see, I cannot use accurate/seemly wording into the code comment. And I am not a programer, write unit tests is hard to me.

**Comment by reaperhulk** [comment]
The binding has been re-added in 40.0.2 and we'll do a pyopenssl release soon to add the new method.

**Comment by SeaHOH** [comment]
New releases of pyOpenSSL did not implemented `SSL.Context.set_cert_store`, so reopen.

**Comment by alex** [comment]
This issue tracks adding the appropriate binding, which is available in cryptography. Any work in pyopenssl needs to be tracked there.
