### ISSUE TITLE
Support deterministic ECDSA sign (RFC6979)

### ISSUE THREAD

**Issue by ivaylo-yordanov** [pyca/cryptography#8709]
Hello,

We are currently evaluating pyca/cryptography for our project, however we require ECDSA (RFC6979) which is not supported at the moment. OpenSSL merged support for generating signatures using deterministic ECDSA a couple of months ago: https://github.com/openssl/openssl/pull/18809. Are you planning to integrate ECDSA sign (RFC6979) in the near future?

**Comment by reaperhulk** [comment]
We're tracking this in #9795 now that OpenSSL 3.2 is almost out.
