### ISSUE TITLE
Expose new EC curve APIs once OpenSSL 1.0.2 is out

### ISSUE THREAD

**Issue by alex** [pyca/cryptography#873]
See #842

**Comment by reaperhulk** [comment]
1.0.2 is now out so these curve APIs should be conditionally exposed (or this issue should be closed if we've decided we don't need them right now).

**Comment by alex** [comment]
It looks like most of these would primarily be used by pyOpenSSL or similar, maybe we should wait until there's a need?

**Comment by reaperhulk** [comment]
:+1:

**Comment by alex** [comment]
If we're actually waiting for pyOpenSSL here, we can close this ticket. We don't have a thing to do.
