### ISSUE TITLE
Python 3.11 + OpenSSL 3.0.8 + Cryptography 39.0 - start of the application fails sometimes - Need Help/Input

### ISSUE THREAD

**Issue by raghupcr** [pyca/cryptography#8761]
_Originally posted by @reaperhulk in https://github.com/pyca/cryptography/issues/7722#issuecomment-1284572949_

Hi Team,

we are facing one issue strangely and initially, everything was working fine. we think it is intermittent. we are observing this whenever we start our application and it is exiting with the following error

cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=50856204, lib=6, reason=524556, reason_text=b'error:0308010C:digital envelope routines::unsupported'), _OpenSSLErrorWithText(code=50331782, lib=6, reason=134, reason_text=b'error:03000086:digital envelope routines::initialization error')])

we tried searching for the solution on Google and got a few things like the need to clear the error stack which we tried in our application ERR_clean_error() but no luck still we are facing this issue. Once we get any OpenSSL error will that be stored in the global cache or something which is referred to in the next execution as well? our understanding it is for each time execution and if there are any errors previously it will bail out.
in our application, we have set the environment variable cryptography_no_legacy_provider flag

we are struggling with how to resolve this error as it is occurring now on almost all platforms 

can someone provide any thoughts or input, please

Config
=====
Python 3.11
OpenSSL 3.0.8 with FIPS enabled ( we are loading only FIPS and base providers and nothing else) 
Cryptography 39.0

Thanks

**Comment by reaperhulk** [comment]
We'd love to help, but we need a mechanism to reproduce this to debug. Could you build a container that demonstrates this issue?

**Comment by raghupcr** [comment]
@reaperhulk  we would love to share the container but acc to our corporate policy we can't share the libs/files which are part of the organization :( .

**Comment by alex** [comment]
If you can provide a from-scratch dockerfile which reproduces this, that would work.

**Comment by raghupcr** [comment]
@alex sure we will check once from our side if we can reproduce with bare openssl and cryptography and with sample code
Thank you
