### ISSUE TITLE
X509_CRL_get_REVOKED bindings should probably be const

### ISSUE THREAD

**Issue by davidben** [pyca/cryptography#8794]
Although they are not const in OpenSSL, mutating it gets you into a bit of a mess. AIUI, cffi doesn't enforce const anyway, but probably making the bindings say const anyway. See https://crbug.com/boringssl/600 for some notes on this.

**Comment by alex** [comment]
Yeah, cffi doesn't enforce `const`. In general we try to mirror what's in the actual header files. So if {Boring,Open,Libre}SSL make it const, we'll follow along, but I don't think it gets us anything for us alone to const it.

**Comment by davidben** [comment]
Sounds good. I'll consider you all not a blocker then. :-)

Reason to potentially do it in the other order (or at least in parallel) is that cffi seems to mean "invoke this (maybe macro) symbol as if it had this prototype", which would suggest you all can be more const than the true symbol, but not less.

But since this is not enforced, this is all moot. :-) I dunno, I could imagine cffi gaining a slower debug mode that checked const to flag bugs.

**Comment by alex** [comment]
I'm going to close this since there doesn't seem to be any action item for us at the moment.
