### ISSUE TITLE
Something changed with newer version. Code no longer works as espected

### ISSUE THREAD

**Issue by robochopbg** [pyca/cryptography#8842]
I have compiled python code and not sure what version this was on.

I have this code that always used to work fine.
Now when i try and import a pfx cert into iis i get incorrect password.

pvtkey = load_pem_private_key(key_data, password=None)
cert = load_pem_x509_certificate(signed_cert)
cert_pass = bytes(cert_pwd,encoding='ascii')
friendly_name = bytes(('*.'+domain),encoding='ascii')
with open(pfx_path, "wb") as f:
      f.write(serialize_key_and_certificates(friendly_name, pvtkey, cert, cas=None,
              encryption_algorithm=serialization.BestAvailableEncryption(cert_pass)))
              
              
With this code it always created a pfx no problem. 

I downgraded to a much older version and this same code above works fine again

**Comment by robochopbg** [comment]
Wow thank you for a really quick response.
 I really appreciate it.

**Comment by reaperhulk** [comment]
I think this is complete, but let us know if that's not the case.
