### ISSUE TITLE
Status and direction of FIPS-140

### ISSUE THREAD

**Issue by Bonn93** [pyca/cryptography#8890]
Hello, 

I'm trying to figure out where the direction and support for FIPS-140-2 is going with this project. It doesn't seem clear from the doco that it's currently well supported

Will FIPS-140 support via OpenSSL3 land in the future? 

I have built NodeJS 18.4 which uses the new `OpenSSL3 FIPS Provider` which seems like a well designed solution, is there any planned support for this in crypto/python?

**Comment by reaperhulk** [comment]
This project supports using the FIPS provider from openssl 3 (as well as RHEL’s FIPS versions). We run tests against them in CI, but don’t guarantee nice error messages if you attempt to do something disallowed.

**Comment by reaperhulk** [comment]
There are two ways you can do this.

1) Use OpenSSL's default configs to automatically load the FIPS provider and enable it.
2) Call `_enable_fips()` on the OpenSSL backend. This still requires the OpenSSL 3 config be properly set up for FIPS, but can manually enable FIPS only behavior. Note that this is not a public API, although we haven't changed it in a while :)
