### ISSUE TITLE
BoringSSL parity: AEADs

### ISSUE THREAD

**Issue by woodruffw** [pyca/cryptography#8903]
This is a breakout for https://github.com/pyca/cryptography/issues/7747, for AEAD functionality specifically.

Relevant parts:

* We should use BoringSSL's own `EVP_AEAD` APIs -- they've indicated no plans to support OpenSSL's `EVP_CIPHER` for anything but AES-GCM, which is supported purely for legacy reasons.
* We've confirmed that BoringSSL's upstream has no interest in primitives or modes of operation that they don't already support, which excludes AES-SIV, AES-OCB3, and AES-CCM.

Subtasks:

- [ ] Support for ChaCha20Poly1305 (exposed as `EVP_aead_chacha20_poly1305` in BoringSSL)

CC @facutuesca

**Comment by facutuesca** [comment]
> CC @facutuesca: if you leave a comment here, @alex or @reaperhulk will be able to assign the issue to you 🙂

Got it, here's my comment 😄
