### ISSUE TITLE
Please make a new release with PyO3 update

### ISSUE THREAD

**Issue by mgorny** [pyca/cryptography#8929]
The latest (40.0.2) release is using PyO3 0.15.2 which doesn't work with PyPy3.10. Please make a new release with the updated PyO3 dependency.

**Comment by alex** [comment]
Python 3.6 compatibility is the issue with backporting the new pyo3 release, MSRV isn't a factor.

https://github.com/pyca/cryptography/commit/7e62312797cc018891fa4ffcfd9485fafacd3dfe is the patch that upgrades us, if you're looking for something to backport.

We don't currently have a plan for when we'll do our next major release, but based on our historic cadence, I'd estimate it at in 4-6 weeks, maybe a bit less if we're super productive.

**Comment by alex** [comment]
For reference, https://github.com/pyca/cryptography/pull/8933 tracks adding PyPy 3.10 to our CI and wheel builder

**Comment by reaperhulk** [comment]
cryptography 41.0.0 is out with the latest pyo3.
