### ISSUE TITLE
Implement XChaCha20-Poly1305 algorithm

### ISSUE THREAD

**Issue by pseusys** [pyca/cryptography#8966]
The only difference of this algorithm is extended (24 byte) nonce, which allows safer nonce randomization with the same key.
The algorithm [is in draft stage for now](https://datatracker.ietf.org/doc/html/draft-arciszewski-xchacha-03), but I believe that shouldn't be an issue since the only difference is one number.
For example, in `pycryptodome` library there [is](https://pycryptodome.readthedocs.io/en/latest/src/cipher/chacha20_poly1305.html) an implementation of XChaCha20-Poly1305.

**Comment by alex** [comment]
Is it available in OpenSSL?

**Comment by pseusys** [comment]
> Is it available in OpenSSL?
As far as I understood, [not yet](https://github.com/openssl/openssl/issues/5523).

**Comment by alex** [comment]
Core cryptographic algorithms for pyca/cryptography are provided by OpenSSL, so there's no action for us to take unless and until it's available there.

**Comment by reaperhulk** [comment]
The draft for this expired and hasn't been updated (since 2018) and the OpenSSL issue is closed as wontfix, so I don't think there's any intent to add this. If OpenSSL does implement this in the future we could add it to our AEAD options, but as is there's nothing we can do.
