### ISSUE TITLE
Diffie-Hellman parameters file

### ISSUE THREAD

**Issue by TheFox** [pyca/cryptography#8988]
How can I load an existing Diffie-Hellman parameters from a PEM file? Documentation only provides examples for `dh.generate_parameters(...)` to generate new parameters. How can I reuse existing parameters?

**Comment by reaperhulk** [comment]
You want https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_pem_parameters

**Comment by TheFox** [comment]
Ok nice. Thank you very much.
