### ISSUE TITLE
Program Crashes when Serializing ed25519 and ed448 Private Keys with DER Encoding, PKCS8 Format, and Password "\x00"

### ISSUE THREAD

**Issue by arunanshub** [pyca/cryptography#9000]
## Issue description

When `ed25519` and `ed448` private keys are serialized using DER encoding, PKCS8 format and **`\x00`** as password, it causes the thread to panic and crashes the program.

## Steps to reproduce bug

```python
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed448, ed25519

ed25519_priv_key = ed25519.Ed25519PrivateKey.generate()
ed25519_priv_key.private_bytes(
    serialization.Encoding.DER,
    serialization.PrivateFormat.PKCS8,
    serialization.BestAvailableEncryption(b"\x00"),
)

ed448_priv_key = ed448.Ed448PrivateKey.generate()
ed448_priv_key.private_bytes(
    serialization.Encoding.DER,
    serialization.PrivateFormat.PKCS8,
    serialization.BestAvailableEncryption(b"\x00"),
)
```

NOTE: using any other password does raise an error.

## cryptography installation
cryptography is installed via poetry with version constraint >=35.0.0:

```toml
[tool.poetry.dependencies]
python = "^3.8"
cryptography = ">=35.0.0"
```

## Required Version numbers

- pip: 23.0.1
- cffi: 1.15.1
- cryptography: 41.0.0
- setuptools: 67.8.0

**Comment by alex** [comment]
Can you please include the full output of the program? Was this something that previously worked?

**Comment by arunanshub** [comment]
Sure, here is the traceback:

```python-traceback
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(0, [0])', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-0.10.53/src/pkey.rs:366:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "[...]/test.py", line 5, in <module>
    ed25519_priv_key.private_bytes(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: NulError(0, [0])
```

> Was this something that previously worked?

Yes, it worked in cryptography v40.0.2.

**Comment by alex** [comment]
Ok, I see the problem. Thanks for the clear report.

**Comment by alex** [comment]
https://github.com/sfackler/rust-openssl/pull/1941 is the first step to fixing.
