### ISSUE TITLE
AttributeError: module \'lib\' has no attribute \'PKCS5_PBKDF2_HMAC\''

### ISSUE THREAD

**Issue by pingshun** [pyca/cryptography#9013]
The 'lib' is from OpenSSL._util.lib, and it points to "cryptography.hazmat.bindings.openssl.binding.Binding().lib".
I got this exception when using "lib.PKCS5_PBKDF2_HMAC(...)", it is easy to reproduce.

Version:
pyOpenSSL                      23.2.0
cryptography                   41.0.0

**Comment by reaperhulk** [comment]
Please provide a stack trace and a method to reproduce this in a fresh virtual environment.

**Comment by pingshun** [comment]
(ENV) core@conf-f698fdf8f-qjwgv:/opt/test$ pip list | grep cryptography
cryptography                   41.0.0
(ENV) core@conf-f698fdf8f-qjwgv:/opt/test$ python
Python 3.7.5 (default, Dec  9 2021, 17:04:37) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.bindings.openssl.binding import Binding
>>> binding = Binding()
>>> lib = binding.lib
>>> if lib.PKCS5_PBKDF2_HMAC('foo', 'bar', '1', '2', '3', '4', '5') != 1:
...   print(1)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'lib' has no attribute 'PKCS5_PBKDF2_HMAC'
>>> 
>>>

**Comment by reaperhulk** [comment]
Our bindings are not public API surface and we change them over time based on our needs. In 41.0.0 we have removed that binding. We have PBKDF2 APIs available, so why are you directly calling this?

**Comment by pingshun** [comment]
Actually, I called this function from pyOpenSSL.
https://github.com/pyca/pyopenssl/blob/main/src/OpenSSL/_util.py#L12
I got the binding and function by:
from OpenSSL._util import lib
lib.PKCS5_PBKDF2_HMAC(...)

**Comment by alex** [comment]
`lib` comes from cryptography, and is indicated by the `_` in `_util`, it's not public.

**Comment by reaperhulk** [comment]
That's just an import from cryptography and, again, is not public API. If you need PBKDF2 you should be using https://cryptography.io/en/latest/hazmat/primitives/key-derivation-functions/#pbkdf2

**Comment by pingshun** [comment]
OK, got it. Thanks.
I think we can close this ticket now.
