### ISSUE TITLE
'error parsing asn1 value: ParseError { kind: ShortData }' when certificate contains a blank line

### ISSUE THREAD

**Issue by matt-mercer** [pyca/cryptography#9033]
Hi .. since upgrading cryptopgraphy from 39.0.2 -> 41.0.1 the certificate below fails to load .. 
appreciate this may be an issue (or not) with the underlying rust / openssl parser .. but raising as it was a little hard to identify the cause  

Versions of:
python=3.10.11
cffi=1.15.1
pip=23.0.1
setuptools=67.8.0
cryptography=41.0.1

How you installed ``cryptography``
poetry add cryptography

steps to reproduce:
`from cryptography import x509

CERT_WITH_BLANK_LINE = """
-----BEGIN CERTIFICATE-----
MIIF7zCCA9egAwIBAgIUTuVnENAO+5syJCWo+ujxisn4LvowDQYJKoZIhvcNAQEL
BQAwgYYxCzAJBgNVBAYTAlhYMRIwEAYDVQQIDAlTdGF0ZU5hbWUxETAPBgNVBAcM
CENpdHlOYW1lMRQwEgYDVQQKDAtDb21wYW55TmFtZTEbMBkGA1UECwwSQ29tcGFu
eVNlY3Rpb25OYW1lMR0wGwYDVQQDDBRDb21tb25OYW1lT3JIb3N0bmFtZTAeFw0y
MzA2MDUxNjQ0MDhaFw0zMzA2MDIxNjQ0MDhaMIGGMQswCQYDVQQGEwJYWDESMBAG
A1UECAwJU3RhdGVOYW1lMREwDwYDVQQHDAhDaXR5TmFtZTEUMBIGA1UECgwLQ29t
cGFueU5hbWUxGzAZBgNVBAsMEkNvbXBhbnlTZWN0aW9uTmFtZTEdMBsGA1UEAwwU
Q29tbW9uTmFtZU9ySG9zdG5hbWUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
AoICAQC0fJEOvLRJRKxrEGph1Pr931PvX4n4/C8i+XlUKyhQlVuxkv9USKxcbRdZ
iRWOtedAD19srznaj5e79jgUVG7ITvDjgYr86EYrMmCs3aSFPjOPK5vTRpEdf/wl
8Bck16DoOiSwcKsVxbscBoNGkD6Pn1/2OpFwzjgeB71xLg7ysb1a+bjlWOA0zenq
cWf9ssPCkboHS/jM2l9iUrRbtDy7GmTvceieKOauBBS197OEELQYpoLd9vsCAAo9
u+0bYTHV6opEK3mVBUXcRoGzClpP0jhyF8R8ZK2VXAAFDD8RsE/i014PmQIIQKUL
G50ja+hD4UO1Z8oG51QOqDqAF8F8CvbKfbG/Ybj0rqAACV6zaBFq3J3Qlz4nEUjF
LvaWG+bWQT160wnh4xyWY9nWdpuVwibb5BE1+xp0VgeenfsBYo0YiqqGMNw0dzti
ZQqyhbpDeLN3UbgOcsyZPgm2y4xFoTX1rG2AGCm2/kxMfqmYneUDZfSSey9N2fyl
K4GUIuHCflt5Z9h9A++Wh04fSRE9Pnm5fIrQiCeFi8Xs0NsMz2ORWs15eM/Fkfwf
mEj7MpuNsj5G8k/wn/z/upz9T46UjNG8dmV9w7HGOjSd17FLFZz/zhBKR4KlXt0T
kHeJjMavedhyaQ0xOAwXFIGHuoQc45104EJ4E0t+c29+ze2pbwIDAQABo1MwUTAd
BgNVHQ4EFgQU4X7ndpRUGgZ5WiPViQQb7fMmk4cwHwYDVR0jBBgwFoAU4X7ndpRU
GgZ5WiPViQQb7fMmk4cwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
AgEAlgIwfcHa+aNoKjrrzezE22I5t48U48w2wrE5lzOpve/ie1WGc+3jRC+jXz5M
8+eeYXGxs397oPCGDhRjqb8gf1l5GNaVfhIVBiEGcfGQXG4Sv9OywxcnxtiHknlj
/Po7Que+rkuj5/uD7IjUOfLeF5ZyMdV6TAm4ptNfPbBxr1ljADojTCgcyI3LFehC
Ly9aFOz9t49pq4yfRQG6sQdIniEwZ+0zmYSYh1Vv+Oea6SKSaWHwMWAvsuwds7Ik
3xMdV89t9szdx4bf6umfmQrZpMuEmLVrzzpRXD+JHQs4CNLQKStVKuIltTApogKu
qX4/5vp8c3eMMVnd9humKHlInYBh7qN8YuWwjFG2ZPit6wh4A9gBbQexvfdUPw6/
iK36F5bK2YREE3E4OQq2h0agFdy7Qv8em9ElejA7l4oAsIGpuAP1QXxFoGTG9LFy
XQCBeGW4FA1YJOzWZEwuH0CTbqX5pKxtGSXQHroUzGfVYE9aiCJMtpFUy0zfHk1v
OFyiR9ITJTHdHz0/pS1/zGkC1g0qqciN4Om6jHIx/IylJjXPZKfYHdjiVR3NB9An
UcWVlAHR4pJszlJoY2a7VRhccFrYqhPpt7B4YC2JIcxPcBiM9D9yVWMMyGCgGhOW
92aldAFf3Szw3VPE6vc6HXm+L8bzXswJQrJkJ6WQOKYQc+o=

-----END CERTIFICATE-----
"""

x509.load_pem_x509_certificate(CERT_WITH_BLANK_LINE.encode("utf-8"))
`

**Comment by reaperhulk** [comment]
This is technically malformed, but from cryptography 35 to 40 this parses successfully. OpenSSL actually never supported this (in 3.4.8 this will fail, which is the last version where we use the pure OpenSSL PEM parser).

We should make this error message a bit more descriptive though (and likely link https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file with a new entry about how blank lines are disallowed).

**Comment by matt-mercer** [comment]
>> This is technically malformed
definitely .. there was a bug in how some test code was assembling the certificate string, but yes a more descriptive error would be really good :)
