### ISSUE TITLE
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by mdevore300** [pyca/cryptography#9060]
I can find the file but it cant.
Conda 4.10.1
Python 3.8.8
Setuptools 52.0.0
cryptography 41.0.0

**Comment by alex** [comment]
Please provide steps to reproduce, you've given us no information.

**Comment by mdevore300** [comment]
Sorry, I am trying to use PDFPlumber in the code. All i did was run import pdfplumber and it gives the error

**Comment by whatcould** [comment]
I'm having this same issue; anytime I try to requires something it fails with `pyo3_runtime.PanicException: Python API call failed`, when running line 16 `from cryptography.hazmat.bindings._rust import _openssl, openssl`.

I upgraded cffi and the issue seemed to resolve. I think for me it had something to do with compilation issues on Apple silicon, because I was getting this [FFI issue](https://foss.heptapod.net/pypy/cffi/-/issues/518).

**Comment by reaperhulk** [comment]
To help you we need a method to reproduce this error in a fresh environment. Do you get this error in a new virtual environment?

**Comment by mdevore300** [comment]
yes. I am in spyder, i highlighted import pdfplumber, hit F9 to run it and the error produces.

**Comment by mdevore300** [comment]
It was pip installed or conda installed.

**Comment by alex** [comment]
Please understand, we cannot attempt to help debug things if you can't even definitely tell us how something was installed. Our package has millions of downloads a day which are successful, so this issue is somehow specific to your environment. We're trying to identify what feature of your environment leads to that, but you're providing us no information to go on. Please see https://cryptography.io/en/latest/faq/#what-issues-can-you-help-with-in-your-issue-tracker

**Comment by reaperhulk** [comment]
Please create a new virtual environment and install your packages into it. It's not possible for us to give additional advice since this appears to be specific to your installation rather than a general issue.

**Comment by QuentinBennett** [comment]
Please don't close, I'm getting the same error. I'll try to reduce to a simple test case.

**Comment by QuentinBennett** [comment]
> Please don't close, I'm getting the same error. I'll try to reduce to a simple test case. . . . PS C:\python> py Python 3.11.3 (tags/v3.11.3:f3909b8, Apr 4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.

Answer was 

pip install cffi --upgrade

**Comment by mdevore300** [comment]
I am working on it. Because of the system it is on, everything needs to get approval from IT, including updating python pkgs.

**Comment by mdevore300** [comment]
So, i've updated all dependencies finally. Still getting the same  error. So all i was trying to do was in spyder, import pdfplumber so i could run a script.  So I highlighted import pdfplumber, then hit F9
The full traceback is as follows:

File "<ipython-input-1-b3d6737fd8e1>", line 1, in <module>
import pdfplumber

File "C:\ProgramData\Anaconda3\lib\site-packages\pdfplumber\__init__.py", line 14, in <module>
for .pdf import PDF

File "C:\ProgramData\Anaconda3\lib\site-packages\pdfplumber\pdf.py, line 8, in <module>
from pdfminer.layour import LAParams

File "C:\ProgramData\Anaconda3\lib\site-packages\pdfminer\layout.py", line 20, in <module>
from .pdfinterp import Color

File "C:\ProgramData\Anaconda3\lib\site-packages\pdfminer\pdfinterp.py", line 12, in <module>
from .pdfdevice import PDFDevice

FIle "C:\ProgramData\Anaconda3\lib\site-packages\pdfminer\pdfdevice.py," line 17, in <module>
from .pdfpage import PDFPage

FIle "C:\ProgramData\Anaconda3\lib\site-packages\pdfminer\pdfpage.py," line 7, in <module>
from .pdfdocument import PDFDocument, PDFTextExtractionNotAllowed, PDFNoPageLabels

FIle "C:\ProgramData\Anaconda3\lib\site-packages\pdfminer\pdfdocument.py", line 23, in <module>
from cryptography.hazmat.preimitives.cipher import Cipher, algorithms, modes

FIle "C:\ProgramData\Anaconda3\lib\site-packages\cryptography\hazmat\primitives\ciphers\__init__.py", line 11, in <module>
from cryptography.hazmat.primitives.ciphers.base import (

FIle "C:\ProgramData\Anaconda3\lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 10, in <module>
from cryptography.exceptions.import (

FIle "C:\ProgramData\Anaconda3\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions

ImportError: cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust (unknown location)

**Comment by rlandge146** [comment]
Has anybody able to resolve the issue..I am getting the following error when installing the same module in amazon glue..

ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._rust'.I tried installing the following packages

cryptography, pyopenssl, setuptools-rust, pdfplumber as indicated in other threads

**Comment by mdevore300** [comment]
I had to go back versions of cryptography and pdfplumber

**Comment by rlandge146** [comment]
@mdevore300 which versions of cryptography and pdfplumber did you go back to to be able to resolve this issue.

**Comment by mdevore300** [comment]
pdfplumber 0.9.0, cryptography 3.4.7

**Comment by rlandge146** [comment]
These versions does not seem to work for me in amazon glue

**Comment by SujayRhombuz** [comment]
"cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)",

have tried the option suggested above nothing works, i am trying to install AWS Lambda.

**Comment by ascopes** [comment]
Any update on this? x86_64 Python3.12, cryptography-41.0.7, cffi-1.16.0 on AWS Lambda is still producing this error, rendering the runtime unusable. Python 3.11 fails due to glibc mismatches even when using the manylinux 2014 distribution, so we are forced to use Python 3.12 for this.

**Comment by AdelinaK** [comment]
I'm using Python 3.11 and Pulumi to deploy Azure Functions. I have the same error: 
Failure Exception: ImportError: cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)

**Comment by spsspro** [comment]
@ascopes @AdelinaK downgrade to `cryptography==3.4.8` will solve the issue.  though i don't know why 🥲

**Comment by ascopes** [comment]
Assuming that defaults to an older manylinux version?

I've had to resort to building and installing all lambda artifacts in a manylinux container to work around issues with 3.11. Haven't tried 3.12 yet.

**Comment by githubakash** [comment]
I am also facing the same issue. I am using python 3.12 with fastapi = 0.99.0.  Earlier I was getting the error as 

> "Unable to import module 'main': cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)"

 . after I downgrade my `cryptography` pkg to `cryptography==3.4.8` , now I am getting the below error,

>   "errorMessage": "Unable to import module 'main': No module named 'cryptography.hazmat.bindings._openssl'",

**Comment by mfouladi** [comment]
Ran into the same issue on my Windows machine while working with fastapi and python-jose to add auth to my app. What ultimately worked for me was running:
`pip install --force-reinstall cryptography`
which pulled the correct versions of cffi for my machine which addressed the issue `ModuleNotFoundError: No module named '_cffi_backend'`

I did also purge my cache prior to this and updated pip:
`pip cache purge`
`pip install --upgrade pip`

still not sure why uninstalling and reinstalling the requirements or specific packages didnt work initially for me so doesn't feel completely resolved but force reinstall did end up working.

**Comment by abhinavbandaru** [comment]
Anyone able to resolve the above issue?

I'm trying to use `cryptography==42.0.5` with `python==3.11.4`, `cffi==1.16.0rc2` and I'm facing this issue
I have also tried downgrading `python==3.10.4` and `cffi==1.15.0` and still facing the same issue

```
File "/dbc/sc-dbc2162/abandaru/abandaru_py311/bora/install/vcsa-installer/vcsaCliInstaller/deps/cryptography/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
File "/dbc/sc-dbc2162/abandaru/abandaru_py311/bora/install/vcsa-installer/vcsaCliInstaller/deps/cryptography/cryptography/exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (/dbc/sc-dbc2162/abandaru/abandaru_py311/testing/vcsa-cli-installer/lin64/lib/library.zip/cryptography/hazmat/bindings/_rust/__init__.pyc)
``` 
I was using `cryptography==38.0.4`, `python==3.10.4` and `cffi==1.15.0` earlier and it was working fine
If anyone has a fix for this, please do let me know

**Comment by tomy128** [comment]
> Anyone able to resolve the above issue?
> 
> I'm trying to use `cryptography==42.0.5` with `python==3.11.4`, `cffi==1.16.0rc2` and I'm facing this issue I have also tried downgrading `python==3.10.4` and `cffi==1.15.0` and still facing the same issue
> 
> ```
> File "/dbc/sc-dbc2162/abandaru/abandaru_py311/bora/install/vcsa-installer/vcsaCliInstaller/deps/cryptography/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
>     from cryptography.exceptions import InternalError
> File "/dbc/sc-dbc2162/abandaru/abandaru_py311/bora/install/vcsa-installer/vcsaCliInstaller/deps/cryptography/cryptography/exceptions.py", line 9, in <module>
>     from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
> ImportError: cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (/dbc/sc-dbc2162/abandaru/abandaru_py311/testing/vcsa-cli-installer/lin64/lib/library.zip/cryptography/hazmat/bindings/_rust/__init__.pyc)
> ```
> 
> I was using `cryptography==38.0.4`, `python==3.10.4` and `cffi==1.15.0` earlier and it was working fine If anyone has a fix for this, please do let me know

Try use `cryptography==41.0.7` and `cffi==1.16.0` with Python 3.11.x (mine is Python 3.11.5)

if python3.8.x try `cryptography==3.4.8` and `cffi==1.14.6`.

hope this help. :-)

also for @techtana0x

**Comment by kenz68** [comment]
@tomy128 downgrade to `cryptography==3.4.8` worked for me. (python 3.9.0 and cffi 1.16.0)

**Comment by abhinavbandaru** [comment]
@tomy128 , thank you for the suggestion! I tried to downgrade to `cryptography==41.0.7` and `cffi==1.16.0` with `python==3.11.4`, I'm still facing the same issue though :/

@kenz68 thank you for the suggestion, but unfortunately I cannot downgrade to `cryptography==3.4.8`

**Comment by abhinavbandaru** [comment]
Can we can re-open this issue? I think a lot of people are still facing this issue with newer versions of cryptography and python?

**Comment by reaperhulk** [comment]
People facing a problem that looks like this should file a new issue with instructions about how to reproduce in a fresh virtual environment. Without that we cannot help, as these issues are almost always an environmental problem specific to the user's machine.

**Comment by ascopes** [comment]
@reaperhulk I think the issue here is that if we knew exactly how to reproduce this, we'd likely already know what the issue is and how to fix it. Without having access to more information from the library when this issue occurs, or a core developer who understands how the underlying Rust bindings work, it makes it very difficult to reproduce.

This issue was closed due to being stale, it never appeared to be actually fixed.

Given there have been 14 responses in the past three months, some with significant detail included already, it feels like it would be a waste to abandon all of this info in the hope someone re-collates it all in a new issue... otherwise this is likely never going to get resolved.

**Comment by reaperhulk** [comment]
People chiming in on this issue may have many different problems. Thus far every time we have looked at one of these issues it has turned out to be an environment problem and not a code issue.

For example, in your case I looked into a similar issue (https://github.com/pyca/cryptography/issues/10440) and we discovered in that case that the reporter had both a newer and older cryptography installed simultaneously, causing their problem. That's a very different environment problem than the people who appear to have some problem with their `cffi` install in this thread.

**Comment by githubakash** [comment]
> I am also facing the same issue while deploying to AWS Lambda. I am using python 3.12 with fastapi = 0.99.0. Earlier I was getting the error as
> 
> > "Unable to import module 'main': cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)"
> 
> . after I downgrade my `cryptography` pkg to `cryptography==3.4.8` , now I am getting the below error,
> 
> > "errorMessage": "Unable to import module 'main': No module named 'cryptography.hazmat.bindings._openssl'",
> 
> I am new to python and seems, it is an rabbit-hole where we need to keep track of these dependencies which is nothing but an nightmare. has anyone got any solution to this? Also, I am not using `cryptography` pkg at all but it is getting installed as an dependencies to other pkg. Is there a way, I can get rid of this pkg all together??

I resolved this issue by using the Linux subsystem on windows machine ( integrated and come out-of-the-box with windows 10) to create the pkg. some how, earlier I was using powershell to create my pkg and it was showing above issues.

**Comment by abhinavbandaru** [comment]
Thank you guys for your inputs. I'll create a new issue for this and link it here once I do it. I'll make sure to provide as many details as I can.

**Comment by abhinavbandaru** [comment]
New issue here: https://github.com/pyca/cryptography/issues/10569

**Comment by abdulwadood10** [comment]
I installed the `paramiko` package with this command 

`pip install --platform manylinux2014_x86_64 --target=./venv/lib/python3.9/site-packages --implementation cp --python-version 3.9 --only-binary=:all: paramiko` 

zipped it with the same root folder with my lambda function. Changed the lambda function runtime to 3.9 and it worked!

**Comment by spchamp** [comment]
For what it's worth I was seeing this error after installing pyca cryptography on a FreeBSD 13 machine. It seems that the rust compiler was in fact not running during the build.

The simplest test case on this system:

```python
 from cryptography.hazmat._oid import ObjectIdentifier
```

After installing via `pip install`, this was producing a similar error .

When checking out the source, creating a virtual env in the source dir, installing the build as editable and installing `-m build` then building from source, e.g `python -m build` in the virtual env under the pyca cryptography source direcory, then build then build runs the rust compiler and produces a usable wheel. 

Could the issue be in setuptools-rust, on some platforms? Just a guess

**Comment by werebear73** [comment]
> Ran into the same issue on my Windows machine while working with fastapi and python-jose to add auth to my app. What ultimately worked for me was running: `pip install --force-reinstall cryptography` which pulled the correct versions of cffi for my machine which addressed the issue `ModuleNotFoundError: No module named '_cffi_backend'`
> 
> I did also purge my cache prior to this and updated pip: `pip cache purge` `pip install --upgrade pip`
> 
> still not sure why uninstalling and reinstalling the requirements or specific packages didnt work initially for me so doesn't feel completely resolved but force reinstall did end up working.

I tried these step and still got the "No module named '_cffi_backend'"
