### ISSUE TITLE
Not able to install latest version of Cryptography

### ISSUE THREAD

**Issue by ganeshhaptik** [pyca/cryptography#9070]
Getting following error:

```ubuntu@haptik-development-devserver-ganesh-vm-int:~/haptik_api$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting pyOpenSSL==23.2.0
  Downloading pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 663 kB/s            
ERROR: Could not find a version that satisfies the requirement cryptography==41.0.1 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.3, 0.4, 0.5, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.9, 0.9.1, 0.9.2, 0.9.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.6, 1.7, 1.7.1, 1.7.2, 1.8, 1.8.1, 1.8.2, 1.9, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2, 2.2.1, 2.2.2, 2.3, 2.3.1, 2.4, 2.4.1, 2.4.2, 2.5, 2.6, 2.6.1, 2.7, 2.8, 2.9, 2.9.1, 2.9.2, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.3.2, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 35.0.0, 36.0.0, 36.0.1, 36.0.2, 37.0.0, 37.0.1, 37.0.2, 37.0.3, 37.0.4, 38.0.0, 38.0.1, 38.0.2, 38.0.3, 38.0.4, 39.0.0, 39.0.1, 39.0.2, 40.0.0, 40.0.1, 40.0.2)
ERROR: No matching distribution found for cryptography==41.0.1
```

Even though `pyOpenSSL` is latest version, could not install `cryptography` package's latest version `41.0.1` on Ubuntu

**Comment by alex** [comment]
What version of python are you using?

**Comment by ganeshhaptik** [comment]
@alex , thanks for quick reply, 
I am using `Python 3.6.8`

**Comment by ganeshhaptik** [comment]
@alex , thanks, but I have seen this that it's not supporting `python 3.6`, but my understanding was then it would support version greater than `3.6` and mine is `3.6.8`, so it should support right? or is it like any python version with prefix `3.6` is not supported here?

**Comment by alex** [comment]
Nothing in the python 3.6 release line is supported. When a Python version is denoted with only one decimal point, that refers to anything in that family. If we intended to only drop support for 3.6.0, we'd have written it as such.

**Comment by ganeshhaptik** [comment]
Thanks @alex for full explanation, was assuming `3.6` and `3.6.0` both same but your explanation has cleared my doubt.
