### ISSUE TITLE
How to "encode" raw data when using UnrecognizedExtension

### ISSUE THREAD

**Issue by sshishov** [pyca/cryptography#9083]
When we are using pre-defined extensions, all of them know how to "encode" them into DER format using `_rust.encode_extension_value(self)`.

Trying to use the same functionality for unrecognized extension produces:
```python
rust_x509.encode_extension_value(x509.UnrecognizedExtension(x509.ObjectIdentifier("1.2.3"), b'SomeValue'))

NotImplementedError: Extension not supported: 1.2.3
```
The real example is needed that this binary value (which we should provide) should be a PrintableString or UTF8String or MBTString. How we can achieve to provide such encoded value without using raw `OpenSSL.crypto` or `pyasn1` or `asn1crypto`?

The intention to not use any dependency library as we are installing and using only `cryptography`. I tried to check the rust bindings but could not find any low-level functionality to fulfill my request.

Could you please help me out. Something like this would be nice to have working:
```python
x509.UnrecognizedExtension(x509.ObjectIdentifier("1.2.3"), encode_somehow('ASN1:PRINTABLESTRING:SomeValue'))
```

Current workaround which we would like to avoid:
```python
x509.UnrecognizedExtension(
    x509.ObjectIdentifier("1.2.3"),
    crypto.X509Extension(b"1.2.3", False, f"ASN1:PRINTABLESTRING:SomeValue".encode()).get_data(),
)
```

**Comment by reaperhulk** [comment]
At this time callers must supply their own ASN.1 encoding for custom extensions with `UnrecognizedExtension`. It would be possible to implement a Python API over the [rust-asn1](https://docs.rs/asn1/latest/asn1/) imperative interfaces, but until someone has the bandwidth and desire to do that work third party DER encoding will be required.
