### ISSUE TITLE
Is Cipher thread-safe: Documenting thread-safety.

### ISSUE THREAD

**Issue by eulersIDcrisis** [pyca/cryptography#9110]
Is the following code thread-safe:
```python
import os
import threading
from concurrent.futures import ThreadPoolExecutor
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

key = b'a' * 32  # 256bit key.
nonce = os.urandom(16)
algorithm = algorithms.ChaCha20(key, nonce)
_CIPHER = Cipher(algorithm, mode=None)

def run_encryption(data):
    encryptor = _CIPHER.encryptor()
    encrypted = encryptor.update(data) + encryptor.finalize()

    decryptor = _CIPHER.decryptor()
    decrypted = decryptor.update(encrypted) + decryptor.finalize()
    return data == decrypted

with ThreadPoolExecutor() as executor:
    for d in range(10):
        executor.submit(run_encryption, 'random data: {}'.format(d).encode('utf-8'))
```
I could not find in the documentation about the thread-safety guarantees or requirements of the library. I sort of assume that `Cipher` used in this way _might_ be thread-safe, while the returned `CipherContext` objects from `encryptor()` and `decryptor()` methods are not, but I do not see this documented. (Maybe I'm looking in the wrong place?)

I believe such documentation is useful, even if the answer is "depends on algorithm".

**Comment by alex** [comment]
Because Cipher objects are stateless, they can be shared/reused without regard to thread safety considerations.

Notwithstanding that, reuse of a Cipher in a context like this is basically never safe, because it means reusing a key, nonce pair, which as per our documentation is catastrophically insecure.

**Comment by eulersIDcrisis** [comment]
This example is a bit contrived, I admit. However, there might be contexts where it might make sense to share a `Cipher` object amongst several threads in the same process (assuming you don't care about the memory hazards and so forth). 

Thank you, this is helpful and I will close the ticket, though it might be useful to document the thread-safety nonetheless (?).

**Comment by alex** [comment]
👍, for the avoidance of doubt: while encryptors/decryptors can also be accessed from multiple threads, actual concurrent modification (i.e., `update` calls) produces inherently indeterminate results.
