### ISSUE TITLE
When  Re-encrypt  give openssl Error

### ISSUE THREAD

**Issue by gxactest** [pyca/cryptography#9120]
[2023-06-23 17:33:40,508] ERROR in app: Exception on /reencrypt [POST]
Traceback (most recent call last):
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/bytestring_splitter/__init__.py", line 90, in produce_value
    message = constructor(bytes_for_this_object, **kwargs)
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/umbral/point.py", line 112, in from_bytes
    backend.openssl_assert(res == 1)
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 241, in openssl_assert
    return binding._openssl_assert(self._lib, ok, errors=errors)
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 80, in _openssl_assert
    raise InternalError(
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=268857446, lib=16, func=103, reason=102, reason_text=b'error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding')])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/data/DKMS-master/restful.py", line 279, in reencrypt
    capsule = Capsule.from_bytes(b_capsule, UmbralParameters(Curve(714)))
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/umbral/pre.py", line 135, in from_bytes
    components = splitter(capsule_bytes)
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/bytestring_splitter/__init__.py", line 196, in __call__
    value = produce_value(message_class, message_name, bytes_for_this_object, kwargs)
  File "/home/gxac/miniconda3/lib/python3.10/site-packages/bytestring_splitter/__init__.py", line 98, in produce_value
    raise BytestringSplittingError(error_message)
bytestring_splitter.BytestringSplittingError: Unable to create a <class 'umbral.point.Point'> from b'123456789abcdefghijklmnopqrstuvwx', got: 
 Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=268857446, lib=16, func=103, reason=102, reason_text=b'error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding')]): ("Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=268857446, lib=16, func=103, reason=102, reason_text=b'error:10067066:elliptic curve routines:ec_GFp_simple_oct2point:invalid encoding')])",)

**Comment by reaperhulk** [comment]
The stack trace shows it attempting to create a PyUmbral Point object from the byte string b'123456789abcdefghijklmnopqrstuvwx‘, which is clearly invalid. If this called our higher level APIs we would capture the error on the stack and raise an exception, but pyUmbral calls our bindings directly so this is an error they need to handle and should be reported there.

**Comment by gxactest** [comment]
Umbral version 0.1.3.a2:
     https://github.com/nucypher/pyUmbral/releases/tag/v0.1.3-alpha.2
i get a case,  Use post:
    Re-encrypt POST /reencrypt { "account":"za", "addresses": [ "QmdVj3LyMPyVHcJ3886HFs594kQsGbBcZG84qneNnhpuR7", "QmW5SLEA7Cj7mhhmgVSjpa5X1LFxjmhR3zMu3oBbpjWak4", "QmZcaBJhNALcxmDPcAozP24vg88iKEHXkBpmBV8tNK3fDd" ], "capsule": "QmYsX5L2xpPSpCm7uLtnmLsW8DonzPUPUq1RJQzeTrv214", "delegating":"038651bf113e8c426867e08623aebd9d6c3e92d59ca7e6e84e04eff213e4e0fdc3", "receiving":"028aaf62c8ae81054ebff5c70150a7a0cc0da43e1cec193f58da0929e62acfd584", "verifying":"03291282cfefb940505aa8edb17046c5accfb9f8ca480fec1467835287ddf3c152", "threshold": 3 }

In the Umbral  \pyUmbral-0.1.3-alpha.2\umbral\pre.py
   
   @classmethod
    def from_bytes(cls, capsule_bytes: bytes, params: UmbralParameters) -> 'Capsule':
        """
        Instantiates a Capsule object from the serialized data.
        """
        curve = params.curve

        bn_size = CurveBN.expected_bytes_length(curve)
        point_size = Point.expected_bytes_length(curve)
        arguments = {'curve': curve}

        if len(capsule_bytes) == cls.expected_bytes_length(curve):
            splitter = BytestringSplitter(
                (Point, point_size, arguments),  # point_e
                (Point, point_size, arguments),  # point_v
                (CurveBN, bn_size, arguments)  # bn_sig
            )
        else:
            raise ValueError("Byte string does not have a valid length for a Capsule")

        components = splitter(capsule_bytes)
        return cls(params, *components)
 
  l get   len of cls.expected_bytes_length(curve):98
so l let capsule_bytes ='123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',  then   len(capsule_bytes) == 98.  in order to  len(capsule_bytes) == cls.expected_bytes_length(curve).
 
May I know how to give the capsule_ Bytes assignment, so that len (capsule_bytes)==cls. expected_ Bytes_ Length (curve):, which means len (capsule_bytes)==cls. expected_ Bytes_ Length (curve)==98, perform the following operation.

The calling code is as follows:

from https://github.com/pallets/flask import Flask, request, Response, jsonify
import [ipfsapi](https://pypi.org/project/ipfsapi)
from [umbral.cfrags](https://pypi.org/project/umbral) import CapsuleFrag
from [umbral.keys](https://pypi.org/project/umbral) import UmbralPrivateKey, UmbralPublicKey
from [umbral.params](https://pypi.org/project/umbral) import UmbralParameters
from [umbral.pre](https://pypi.org/project/umbral) import Capsule
from [umbral.kfrags](https://pypi.org/project/umbral) import KFrag
from [umbral](https://pypi.org/project/umbral) import pre, keys, signing
from [umbral.curve](https://pypi.org/project/umbral) import Curve

import [pymysql](https://pypi.org/project/pymysql)

import os, base64

from https://github.com/pallets/werkzeug import json

app = Flask(__name__)

conn = pymysql.connect(host="localhost", user="XXX", database="XXX", charset="utf8")


@app.route('/hello', methods=['GET'])
def hello_world():
    return "hello world"
# reencrypt
@app.route('/reencrypt', methods=['POST'])
def reencrypt():
    api = ipfsapi.connect('127.0.0.1', 5001)
    addrs = list()
    caddrs = list()
    res = {}
    if request.headers['Content-Type'] == 'application/json':
        account = request.json['account']
        # 所有的传入参数都是hex key
        threshold = request.json['threshold']
        capsulehex = request.json['capsule']
        b_capsule = api.cat(capsulehex)
        capsule = Capsule.from_bytes(b_capsule, UmbralParameters(Curve(714)))
        addrs = request.json['addresses']

        delegatinghex = request.json['delegating']
        b_delegating = bytes.fromhex(delegatinghex)
        delegating = UmbralPublicKey.from_bytes(b_delegating)
        receivinghex = request.json['receiving']
        b_receiving = bytes.fromhex(receivinghex)
        receiving = UmbralPublicKey.from_bytes(b_receiving)
        verifyinghex = request.json['verifying']
        b_verifying = bytes.fromhex(verifyinghex)
        verifying = UmbralPublicKey.from_bytes(b_verifying)
        if threshold > len(addrs):
            return "Not enough addresses."

        capsule.set_correctness_keys(delegating=delegating,
                                     receiving=receiving,
                                     verifying=verifying)

        cfrags = list()  # Receiver's cfrag collection
        # each kfrag is a rk segment
        for addr in addrs:
            rkseg = KFrag.from_bytes(api.cat(addr))
            # cfrag = pre.reencrypt(kfrag=kfrag, capsule=capsule)
            cfrag = pre.reencrypt(kfrag=rkseg, capsule=capsule)
            cfrags.append(cfrag)  # Receiver's collects a cfrag

        for cfrag in cfrags:
            caddrs.append(api.add_bytes(cfrag.to_bytes()))
        savedcap = capsule.to_bytes_all()
        # savedcap包括三块，basic为capsule，correctness为set的key，cfrag是append上去的东西，此时还为空
        print(type(savedcap))
        print(type(savedcap['basic']))

        print(savedcap['correctness'])
        delegating_key = savedcap['correctness']['delegating']
        receiving_key = savedcap['correctness']['receiving']
        verifying_key = savedcap['correctness']['verifying']

        b_delegating_key = delegating_key.to_bytes()
        b_receiving_key = receiving_key.to_bytes()
        b_verifying_key = verifying_key.to_bytes()

        print(b_delegating_key)
        print(b_receiving_key)
        print(b_verifying_key)

        sendbytes = savedcap['basic'] + b'ZAtech' + b_delegating_key + b'ZBtech' + b_receiving_key + b'ZBtech' + b_verifying_key

        print(sendbytes)

        savedcapaddr = api.add_bytes(sendbytes)

        res = {"caddrs": caddrs, "capsule": savedcapaddr}
        return jsonify(res), {'Content-Type': 'application/json'}
    return
# api.add_bytes
if __name__ == "__main__":
    app.run(host='0.0.0.0')

The error prompt during compilation is as follows:
Update your Ubuntu system by running the command sudo apt update && sudo apt upgrade.
Install the dependencies required to build Python 3.10 by running the command sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev wget libbz2-dev.
Download the Python 3.10 source code from the official Python download page by running the command cd /tmp && wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz.
Extract the source code by running the command tar -xf Python-3.10.0.tgz.
Change to the extracted directory by running the command cd Python-3.10.0.
Configure the build by running the command ./configure --enable-optimizations.
Build Python 3.10 by running the command make -j $(nproc).
Install Python 3.10 by running the command sudo make altinstall.
Verify that Python 3.10 is installed by running the command python3.10 --version.

**Comment by reaperhulk** [comment]
We are not the pyUmbral team, you need to report this to them, not us.

**Comment by gxactest** [comment]
OK， thanks
