### ISSUE TITLE
Missing ENV var OPENSSL_DIR="/usr" on OpenBSD

### ISSUE THREAD

**Issue by jpcw** [pyca/cryptography#9144]
Versions of Python, cryptography, cffi, pip, and setuptools
    you're using

-           libressl 3.7
-           Python: 3.10.12
-           platform: OpenBSD-7.3-amd64-64bit-ELF
-           cffi: 1.15.1
-           setuptools: 68.0.0
-           setuptools_rust: 1.6.0
-           rustc: 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball)

 `
mkdir crypto
python3.10 -m venv crypto_env
cd crypto_env/
bin/pip install pip --upgrade
bin/pip install cryptography

        --- stderr
        thread 'main' panicked at 'unable to find openssl include path', cryptography-cffi/build.rs:55:49

`
setting up ENV  OPENSSL_DIR="/usr" like here https://github.com/openbsd/ports/blob/master/security/py-cryptography/Makefile#L38 fix the problem

`
export OPENSSL_DIR="/usr"
bin/pip install cryptography
...
Successfully built cryptography
`

**Comment by alex** [comment]
What is the purpose of this bug report, it seems you have this working correctly. Are you asking for something to be changed?

**Comment by jpcw** [comment]
Hi Alex, sorry for not submitting a patch, but maybe
a piece of code like this one:
`
if os.platform == 'OpenBSD':
    os.environ["OPENSSL_DIR"]="/usr"
`
Not sure where to place it, but i think this two lines or similar could make the job done, in evry circonstances ?

**Comment by alex** [comment]
Ahh, I understand.

The right place to add it would be here: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/find_normal.rs#L95

If you can send a PR, I will merge it there.

**Comment by jpcw** [comment]
Done https://github.com/sfackler/rust-openssl/pull/1983
Thank You

**Comment by alex** [comment]
Fix will be included in our next release
