### ISSUE TITLE
DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by ubalklen** [pyca/cryptography#9146]
Python 3.11.4
pip 23.1.2
Windows 11

When I try to install a private package (`pip install my-package`) that requires `cryptography`, I get this:
```
Collecting cffi>=1.12 (from cryptography->my-package)
  Downloading https://[REDACTED]/pypi/download/cffi/1.15/cffi-1.15.0.tar.gz
     - 484.1 kB 32.0 MB/s 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\username\AppData\Local\Temp\pip-install-u6tcly2x\cffi_fac42eda6a9d4119a8c60127dfca283f\setup.py", line 126, in <module>
          if sys.platform == "win32" and uses_msvc():
                                         ^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-install-u6tcly2x\cffi_fac42eda6a9d4119a8c60127dfca283f\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\miniconda3\envs\cryptography_test_env\Lib\site-packages\setuptools\_distutils\command\config.py", line 223, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\username\AppData\Local\miniconda3\envs\cryptography_test_env\Lib\site-packages\setuptools\_distutils\command\config.py", line 128, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\username\AppData\Local\miniconda3\envs\cryptography_test_env\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\username\AppData\Local\miniconda3\envs\cryptography_test_env\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\miniconda3\envs\cryptography_test_env\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\miniconda3\envs\cryptography_test_env\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
(Note I'm using a private index, but it is configured to get packages from PyPI, so I don't think this is the issue here)

The error message is clear enough ("Microsoft Visual C++ 14.0 or greater is required"). I'm opening this because the installation works in Python 3.10, so I'm not sure how I can be missing something in Python 3.11 that exists in Python 3.10. Installation also works if I upgrade to Python 3.11, uninstall `cryptography` and try to install it again (presumably because `pip` caches the correctly built package).

This seems to be related to what [this guy](https://groups.google.com/g/python-cffi/c/9Fah6Z3SMuc/m/yNhvquAOBAAJ) said in `cffi`'s mailing list:

> For those that have seen these kinds of errors.
> 
> distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.2 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> 
> And you have the latest version of Visual Studio installed....
> 
> I don't know how many people have gotten bitten by MSVC compiler detection problems in SetupTools and Distutils. It has happened to me and it can be extremely frustrating to figure out. Even more so if your OS of choice is something other than Windows. The end game is to provide cross platform support and the lack of a built in packaging framework that is able to set up a proper build environment under Windows is a real sore spot.
> 
> This is where I come to the rescue. I wrote a script that sets up a correct build environment. It actually makes the environment that you see when using Visual Studio but it does it without using the problematic vcvars* batch files (which is what distutils and setup tools uses). Setup tools is not designed to detect Visual Studio installations. It is only made to locate Build Tools installations. There in lies the problem as most CI environments are packaged with Visual Studio and most developers typically would have Visual Studio installed and not Build Tools.

His package can be found at https://pypi.org/project/pyMSVC/

**Comment by reaperhulk** [comment]
This error is coming from `cffi`, not `cryptography`. `cffi` 1.15.0 does not have a Python 3.11 wheel, but `1.15.1` does, which is why you're being forced to compile rather than getting a prebuilt wheel.

**Comment by ubalklen** [comment]
I see, Thanks for the info. I wonder why pip downloaded 1.15.0 instead of 1.15.1.
