### ISSUE TITLE
PyPy 3.10 wheels

### ISSUE THREAD

**Issue by felipou** [pyca/cryptography#9204]
Any chance we could have a patch release (41.0.2) to get pre-built wheels for PyPy 3.10? I've seen that it was already added in the [main branch](https://github.com/pyca/cryptography/commit/ed5ea40ed28e86d924c10ecb49fc647ef0a0dcfd), but there hasn't been any release since.

**Comment by reaperhulk** [comment]
I've generated some 41.0.1 wheels here: https://github.com/pyca/cryptography/actions/runs/5503715197

We may upload these manually, but these are available until we do.

**Comment by alex** [comment]
I've submitted https://github.com/pyca/cryptography/pull/9210 to backport pypy 3.10 wheels to 41.x. This will be in a release this week.

**Comment by reaperhulk** [comment]
Wheels published in 41.0.2
