### ISSUE TITLE
Building static wheels for AWS Lambda (potential documentation issue)

### ISSUE THREAD

**Issue by mikicz** [pyca/cryptography#9222]
Hello!

I am trying to follow the documentation to build `cryptography` for AWS Lambda. I'm not asking for documentation to be updated to have aws lambda instructions, but am struggling to build static wheel using the current documentation, so would like to ask for help. Can you please read the following, and see what I am possibly doing wrong?

I am doing this, because when I run cryptography installed using a wheel, I get the following, the good old:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'XXX': /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)
```

## --no-binary install

At first I tried to follow the instructions in this ticket: https://github.com/pyca/cryptography/issues/6391#issue-1020088939 But using that, I get a different error. (this I am pretty sure also matches the aws lambda dependencies: https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-native-libraries)

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'XXX': libssl.so.3: cannot open shared object file: No such file or directory
```

The ticket shows that the `openssl` so should get included, but using this approach it doesn't.

## Static Wheels

Next I tried to follow Static Wheels part of the installation documentation, here: https://cryptography.io/en/41.0.2/installation/#static-wheels

The wheel does get built, but again the `openssl` so doesn't get included. I have not actually tried to deploy this wheel to lambda, but considering the contents are identical to what gets build when doing the `--no-binary` install, I am pretty sure it won't work. It certainly does look like it doesn't actually statically include openssl. The only `so` file included is the `_rust.abi3.so` file.

## Replication

I've pushed my build code to a repo, here specifically: https://github.com/mikicz/cryptography-wheel-repro

It contains a `Makefile`, which does these two method of install and checks the content of the install. It prints all the `so` files in the installation method. The wheel gets checked with command `list_sos_through_wheel`, the `--no-binary` install gets checked with `list_sos_through_target`.

## Environments

I tried on the following environments:
  - Fedora 38
  - Inside the `python:3.10-slim` docker image

**Comment by reaperhulk** [comment]
Our abi3 wheels built for manylinux2014 (aka manylinux_2_17) should work without issue on lambda. It looks like you installed the manylinux_2_28, which requires glibc 2.28 (evidently newer than the lambda runner's glibc).

As for building your own, it looks like you don't have `OPENSSL_STATIC=1`, which is a requirement for static wheels. We document that in the macOS section, but we'd be happy to take a PR improving the docs to say it more generically.

**Comment by mikicz** [comment]
!! Thank you so much for such a quick reply!

Yes, you're absolutely correct, I have not clocked this at all, but yes, looks like where we're building the deployment package we have a higher version of glibc than lambda, meaning a different version gets installed. Simply adding `--platform manylinux_2_17_x86_64` to the pip install command has fixed this, and now we are able to to use cryptography.

As for `OPENSSL_STATIC=1`, I have tried this (even pushed to my repo), but the openssl `so` does not get included anyway? But I am actually not 100% it should?
