### ISSUE TITLE
ERROR: cannot install cryptography-41.0.2 dependency

### ISSUE THREAD

**Issue by balas77** [pyca/cryptography#9235]
I am using Azure devops pipeline to generate zip file for python based azure function app. I have pipeline bash task to do "func pack --python" and getting the below errors specifically in **azure.identity** module

ERROR: cannot install cryptography-41.0.2 dependency: binary dependencies without wheels are not supported when building locally. Use the "--build remote" option to build dependencies on the Azure Functions build server, or "--build-native-deps" option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish

I have the below dependencies in my requirements.txt file
azure-functions
azure.mgmt.resource
azure.identity
azure.monitor.query
appinsights

![image](https://github.com/pyca/cryptography/assets/64924532/c95b6191-b064-434a-97c7-e88987d3cc05)

Any help to sort this out would be appreciated!

**Comment by alex** [comment]
We are not familiar with func, so we cannot provide support for it.

This module requires binary extension modules for Python, and thus you will need a build toolchain that supports them.
