### ISSUE TITLE
Inquiry regarding serialization

### ISSUE THREAD

**Issue by felartu** [pyca/cryptography#9236]
Hi,

We are planning on building a TLS proxy and we are exploring this cryptography library but we have questions regarding data serialization.

1. Once a TLS connection is established, can we serialize the TLS session in order for another python process to import it and continue the session? This would require exporting the session key material and everything the class instance requires to function properly.
2. Are there hardware dependencies in case we would like to import the TLS session in a different container/VM/server? We have the TCP session mobility figured out but we are now exploring the TLS session.

Regards,

**Comment by alex** [comment]
This library provides cryptographic primitives, we don't have any TLS API. Therefore it's very unclear what you're asking about or how we could reply. You'll need to provide many more details before we could help.

**Comment by felartu** [comment]
Basically, I want to take instances of cryptographic classes and save them to disk via serialization:

example:

```
test_dict = {"Hello": "World!"}
with open("test.pickle", "wb") as outfile:
 	# "wb" argument opens the file in binary mode
	pickle.dump(test_dict, outfile)
```

This code creates a file called test.pickle as a binary blob containing all the object structure, in this case, a python dictionary object, and it can later be picked up by any other python program using deserialization and the exact same object will be present as if it was the original.

Although serialization cannot be done to all types of python objects, thus my question is if the cryptography library would have any potential problem when copying crypto primitives between programs and/or servers.

**Comment by alex** [comment]
None of our types support pickle. Any type that can be serialized has public APIs for doing so, such as `public_bytes()`

**Comment by felartu** [comment]
Understood, can `public_bytes()` be called from all cryptographic types?

**Comment by alex** [comment]
See our documentation for which types have which methods.

**Comment by felartu** [comment]
Thanks, will check it.

One more question, are there system dependencies like file descriptors that will prevent types to be moved to other Python processes or other Python processes running on a different server?

**Comment by alex** [comment]
`public_bytes` and other public APIs for serialization emit bytes, which can be loaded anywhere.

**Comment by felartu** [comment]
Thanks for the information.
