### ISSUE TITLE
CMS support

### ISSUE THREAD

**Issue by groner** [pyca/cryptography#924]
Starting a list of requirements for supporting [CMS](https://tools.ietf.org/html/rfc5652).
- [ ] ASN.1
- [x] Asymmetric Encryption/Decryption (enveloped-data)
- [x] Symmetric Ciphers (enveloped-data)
- [x] Asymmetric Signing/Verification (signed-data)
- [x] Asymmetric key loading

This is far from complete.  I'm avoiding X.509 in my current project, for now, but I guess we'll want that eventually.

**Comment by reaperhulk** [comment]
We're cleaning up our backlog and we're going to prioritize PKCS7 and (eventually) SMIME over the wider CMS profile. Closing this for now.
