### ISSUE TITLE
ChaCha20Poly1305 memory leak

### ISSUE THREAD

**Issue by PaulWhitingS2** [pyca/cryptography#9255]
Cryptography 39.0.0 introduced a memory leak in the ChaCha20Poly1305 class.  It is still present in the most recent release (41.0.2).

1. python -m venv venv
2. source venv/bin/activate
3. pip install cryptography
4. Run the following script.  Monitor memory usage using `top`.

```
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
key = ChaCha20Poly1305.generate_key()
while True:
        chacha = ChaCha20Poly1305(key)
```

Cryptography 38.0.4 - Memory usage remains constant.
Cryptography >= 39.0.0 - Memory usage increases until the process is killed.

**Comment by reaperhulk** [comment]
Thanks for the report. While we chase this down, here is a reduced reproducer:

```python
import gc

from cryptography.hazmat.bindings._rust import FixedPool


class Foo:
    def __init__(self):
        self._pool = FixedPool(self._method)

    def _method(self):
        pass


while True:
    Foo()
    gc.collect()
```

**Comment by reaperhulk** [comment]
It appears we need to implement `__traverse__` and `__clear__` so that the GC can properly collect everything (as there are circular references with the fixed pool). We'll get a fix up soon.
