### ISSUE TITLE
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by Hypurrnating** [pyca/cryptography#9256]
I'm trying to run cryptography on an embeddable package of python 3.11
I've installed cryptography using pip on my main python installation and then went to `C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages` and copied the folders for cryptography, cffi, and pycparser into the `\python-3.11.0-embed-amd64\python311.zip` folder. 
I've used this method for other packages and it has worked without issue. 

Simply doing `import cryptography` works.
However while doing `from cryptography.fernet import Fernet` it gives the error:
```
cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)
```
ive gone to `\python311.zip\cryptography\hazmat\bindings\_rust` and did find a `exceptions.pyi` file located there. Im unsure what the issue is

ty

**Comment by alex** [comment]
zipimport does not support extension modules, cryptography requires an extension module: https://docs.python.org/3/library/zipimport.html

**Comment by alex** [comment]
Great
