### ISSUE TITLE
Intermittent "cryptography.exceptions.UnsupportedAlgorithm" error popping up

### ISSUE THREAD

**Issue by julianogv** [pyca/cryptography#9257]
I'm reaching out for assistance after spending several days unsuccessfully trying to decipher the cause of intermittent errors that occur when I attempt to encrypt data. I'm hoping someone can provide insight into this issue.

I'm currently running a Flask app + uwsgi (2 workers). Occasionally, I encounter the error `cryptography.exceptions.UnsupportedAlgorithm: cipher AES in CBC mode is not supported by this backend (Your version of OpenSSL may be too old. Current version: OpenSSL 3.1.1 30 May 2023.)` 

I've been actively monitoring this for over a day, running with different cryptography and python versions, but have been unable to isolate a pattern or behavior that triggers this exception. Most of the time it works as expected, I'm only having this issue in production, I'm not being able to reproduce it on my local machine or stage environment.

The environment (dependencies installed using pip):
python 3.9 (docker python:3.9-slim)
cryptography==41.0.2
cffi==1.15.1

The code I'm running basically does this:
```python
from cryptography.hazmat.primitives import ciphers
from cryptography.hazmat.primitives.ciphers import modes
from cryptography.hazmat.primitives.ciphers.algorithms import AES
from cryptography.hazmat.backends import default_backend

data_to_encrypt = b"a secret message"
encryptor = ciphers.Cipher(AES(REDACTED), modes.CBC(REDACTED), default_backend()).encryptor()
ct = encryptor.update(data_to_encrypt) + encryptor.finalize()
```

If anyone can help me figure out why this error keeps popping up, that would be awesome!

**Comment by alex** [comment]
For this to occur, you'd basically need `EVP_get_cipherbyname` to fail when called with `aes-{key length}-cbc`:

- https://github.com/pyca/cryptography/blob/main/src/cryptography/hazmat/backends/openssl/ciphers.py#L51-L60
- https://github.com/pyca/cryptography/blob/main/src/cryptography/hazmat/backends/openssl/backend.py#L1560

I don't see how this could happen except a bug in OpenSSL, or perhaps some unrelated memory corruption.

**Comment by reaperhulk** [comment]
This error gets raised here:
https://github.com/pyca/cryptography/blob/524c9eb10c1387eb3c2bf6e7f7b01505516b759f/src/cryptography/hazmat/backends/openssl/ciphers.py#L51-L60
This means it is successfully getting an adapter and invoking it. That looks like
https://github.com/pyca/cryptography/blob/524c9eb10c1387eb3c2bf6e7f7b01505516b759f/src/cryptography/hazmat/backends/openssl/backend.py#L1558-L1576
It's likely you're seeing failures in `EVP_get_cipherbyname`. That calls `OBJ_NAME_get` under the hook which has some locking behaviors so it's possible something weird is happening.

**Comment by julianogv** [comment]
I'm not sure if it might help understanding the root of the problem, but I have recently come across additional sporadic errors associated with SSL 
`botocore.exceptions.SSLError: SSL validation failed for https://sqs.us-east-1.amazonaws.com/ unknown error (_ssl.c:4293)`

**Comment by alex** [comment]
This is very unlikely to be _directly_ related, because this error comes out of the stdlib SSL module, not cryptography.

Nonetheless, to me this is suggestive that the issue may not be a bug so much as some sort of corruption: bad RAM, `libcrypto.so` on disk being corrupted, some other memory corruption in the process messing things up, etc.

**Comment by julianogv** [comment]
After testing some different scenarios, it seems that the error occurs whenever the application workers are restarted, or when a new pod is initiated.

Removing the --max-requests (configuration responsible for restarting workers after an specific request count) from the uwsgi config reduced the frequency of these errors, as the workers are no longer restarting very often.

**Comment by alex** [comment]
The fact that it's restarting related makes me think the cause may be OpenSSL getting re-initialized somehow.

Are you use a deployment model with sub-interpreters or some other mechanism where the workers share a memory space?

**Comment by julianogv** [comment]
> The fact that it's restarting related makes me think the cause may be OpenSSL getting re-initialized somehow.
> 
> Are you use a deployment model with sub-interpreters or some other mechanism where the workers share a memory space?

yes, there is a "process fork" that is made during the initialization, that might be causing the problem.

I'm closing this issue as we "found" the reason.
