### ISSUE TITLE
error: failed to get `openssl-sys` as a dependency of package `cryptography-cffi v0.1.0 (/tmp/pip-req-build-b_h4_ilg/src/rust/cryptography-cffi)`

### ISSUE THREAD

**Issue by KiwiZQY** [pyca/cryptography#9259]
Versions of Python, cryptography, cffi, pip, and setuptools
you're using
Python 3.10
cryptography 40.0.0/40.0.1/41.0.1
pip 23.2
setuptools 68.0.0
setuptools-rust 1.6.0
openssl 3.1.1

How you installed cryptography
Building the Linux package (I am the packager)

I am getting the following error:

![f31cab007be3f253570437b23c9df9c](https://github.com/pyca/cryptography/assets/103408995/e52898dd-c382-4439-9e25-ea3acd042072)

**Comment by alex** [comment]
As the error message clearly indicates, this is a networking issue on your machine: "Could not resolve host: index.crates.io"

**Comment by KiwiZQY** [comment]
> 正如错误消息清楚地表明的那样，这是您计算机上的网络问题：“无法解析主机：index.crates.io”

I'm sorry, my problem wasn't clearly described. In fact, I installed it on an offline linux system server, so there was no way to connect to the Internet.

**Comment by alex** [comment]
You'll need to download all dependencies in advance. We cannot provide support for this process.

**Comment by KiwiZQY** [comment]
> You'll need to download all dependencies in advance. We cannot provide support for this process.
All dependencies have been downloaded. 
Finally, I loaded cryptographic-41.0.2-CP37-abi3-manylinux_2_17_x86_64. manylinux2014_x86_64.whl file to install successfully, But I was surprised, my python version is 3.10, did not expect cp37 files can also be installed successfully.My problem has been solved.
