### ISSUE TITLE
ParseError: ShortData because of missing SET OF attribute

### ISSUE THREAD

**Issue by 0b11stan** [pyca/cryptography#9339]
Hi, not sure if it's a bug or a feature request but here it is.

I need to load CSR generated by embedded devices. Openssl can show me my CSR content with `openssl req -in csr.pem -text` but I get the following error when using cryptography:

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/test/venv/lib/python3.10/site-packages/cryptography/x509/base.py", line 601, in load_pem_x509_csr
    return rust_x509.load_pem_x509_csr(data)
ValueError: error parsing asn1 value: ParseError { kind: ShortData, location: ["Csr::csr_info", "CertificationRequestInfo::attributes"] }
```

After some investigation I found that the only difference with a valid CSR (generated on my computer) and the device's one is a missing "SET OF" attribute on the certificate.

(reference links)
- https://www.openssl.org/docs/man1.0.2/man1/req.html#DIAGNOSTICS
- https://github.com/pyca/cryptography/issues/6601

I understand that this missing attribute makes the certificate an invalid one but it looks like this error is frequent on old implementations and has very little impact. Do you see a solution for me to load the certificate ? In the future maybe a flag can be added for cryptography to ignore this missing attribute ?

For simple reproduction:

```python
from cryptography import x509

x509.load_pem_x509_csr(b"""
-----BEGIN CERTIFICATE REQUEST-----
MIIBWTCBwwIBADAcMQswCQYDVQQGEwJGUjENMAsGA1UEAwwEZGVtbzCBnzANBgkq
hkiG9w0BAQEFAAOBjQAwgYkCgYEAsozXFJgKlaKxgNyNqoEieEedvSceJKhqDnA3
JLdEKbE9decGmyaIzC1TwWL1d888NEtAjiILyJwo8jFlrA+DYfe0sC6pFEfjsMCh
xkMm5dajE1eogmXeQIPmO9gXQdiOibNN5vrFiNMMAA9u4s10F3Mx0eunXZhiN6SM
D9TnkFcCAwEAATANBgkqhkiG9w0BAQsFAAOBgQBBiRTNEraB+Gl+TbIuKCrN9fj2
YM1Chn+twaGTyhyUdAKaKXQWMFzJUmZHzzQ7EtdPDlRgSB/sg+iA8GIBMx24Z6t/
XzkT4WSRQ5bq7TJdeZxrdUSQXQTG5BXSyAjYk0TwEKWh8tHZ7tYoNxmgdp+C+enK
z33OT6dT0wI+S+Qd2g==
-----END CERTIFICATE REQUEST-----
""")
```

For generating a certificate without the "SET OF" attribute:

```bash
# Generate CSR with missing SET OF using an old openssl version wich has the -asn1-kludge arg
podman run --rm -v $PWD:/mnt docker.io/debian:jessie sh -c 'cd /mnt && cat /etc/apt/sources.list | egrep -v "^#|security|update" | sed "s!http://deb!http://archive!" | tee /etc/apt/sources.list && apt-get update && apt-get install -y --force-yes openssl && openssl req -asn1-kludge -nodes -newkey rsa:1024 -subj "/C=FR/CN=demo" -keyout /dev/null -out /mnt/csr.pem' > /dev/null 2>&1 

# Reproducing on the last version
python3.10 -m venv venv && source venv/bin/activate \
  && pip install --upgrade pip && pip install cryptography \
  && python -c 'from cryptography import x509; x509.load_pem_x509_csr(open("csr.pem","rb").read())'
```

Versions

```
Package      Version
------------ -------
cffi         1.15.1
cryptography 41.0.3
pip          23.2.1
pycparser    2.21
setuptools   65.5.0
```

**Comment by reaperhulk** [comment]
In some cases we work with upstreams to fix issues and then we put in (time-limited) workarounds for invalid DER encoding. However, we're unlikely to do this for CSRs for long since they are typically ephemeral (in https://github.com/pyca/cryptography/pull/6600 we put in a workaround for ~6 months for an issue Red Hat fixed).

In your example you're passing `-asn1-kludge` to force it to generate invalid DER -- do you have an example of current software generating invalid CSRs by default that we need to take a look at?

**Comment by 0b11stan** [comment]
Yes I understand, but recent (I can't say for the last one) version of bosh and axis network cameras are generating these type of csr.

**Comment by 0b11stan** [comment]
For reference, a DIRTY workaroud is to add an extension using https://github.com/pyca/pyopenssl then converting to cyptorgraphy object.

```python
from cryptography.hazmat.primitives import serialization
from cryptography import x509
import OpenSSL.crypto as crypto
from OpenSSL.crypto import load_certificate_request, FILETYPE_PEM

req = load_certificate_request(FILETYPE_PEM, open('csr.pem', 'rb').read())
req.add_extensions([crypto.X509Extension(b'subjectAltName', False, b'IP:1.2.3.4')])

csr = req.to_cryptography()
print(csr.public_bytes(encoding=serialization.Encoding.PEM).decode())
```

**Comment by alex** [comment]
The next step here is that someone needs to contact these companies and inform them that their products are generating invalid CSRs. We do not consider adding workarounds unless and until the underlying issue will be resolved.

**Comment by 0b11stan** [comment]
Fair enought, you'r right, I'll contact the manufacturers
