### ISSUE TITLE
O...kay???

### ISSUE THREAD

**Issue by gordonb3** [pyca/cryptography#9382]
If that was supposed to be an answer to a very serious question (#9381) I guess that means I should wish you luck with burying the remainder of your little project. I'm looking forward to someone that isn't such a self-righteous a*hole picking up from where you lost your mind and figured that making your library depend on a development platform that will never support little hardware was a good idea.

I'll still ask you one more time, even though it is obvious that you are not willing (or more like able) to answer intelligibly, what possible pressing reason could you have had to rewrite this code in a language that heavily restricts its usage?

**Comment by gordonb3** [comment]
Just to be clear, I'm already at the point of realizing that you will never consider reverting this fundamental error in judgement. I just like to know what drove you to do it.

**Comment by alex** [comment]
This is not an acceptable issue. If you wish to participate in our issue tracker, you need to conduct yourself with at least a modicum of professionalism. As you've already been warned, you'll be receiving a temporary ban from our issue tracker.

Further, even if you had composed this issue professionally, it (and its predecessor) lacks essential details for us to be able to respond constructively: Notably you do not explain what platforms you're struggling with, the types of issues you're encountering, or provide anything approaching an error message. All of these are typical things _any_ project would expect you to provide to make an issue actionable.

Finally, to your question as to what motivated our adoption of Rust: Security and performance. Code written in memory unsafe languages is inevitably replete with vulnerabilities as a result, and we think there's an urgent need for the industry to migrate away from there. Further, by providing a safe, low-level, language, Rust gives us the opportunity to substantially improve our performance.
