### ISSUE TITLE
Should RSA key generation work in FIPS mode?

### ISSUE THREAD

**Issue by Bonn93** [pyca/cryptography#9389]
Hello, I'm using `cryptography` in a python 3.11.4 container with a FIPS enabled/system wide instance. The FIPS provider is compiled on version 3.0.8, and the core system version is 3.1.1 for OpenSSL.

Python has been installed with `./configure --with-openssl-rpath=auto --enable-optimizations` to use the newer version of OpenSSL on the system. Various tests suggest a lot of things are working as expected ie hashing with Hazmat using `md5_hash = hashes.Hash(hashes.MD5(), backend=default_backend())` appears to work and throws expected failures in FIPS mode. 

I'm trying to test some other areas and looking at RSA, using the example from read the docs, I get the following error if I try to generate a RSA private key: 

`cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([<OpenSSLError(code=50856204, lib=6, reason=524556, reason_text=unsupported)>, <OpenSSLError(code=301990032, lib=36, reason=144, reason_text=unable to fetch drbg)>])`

The example code used: 

```
def rsa_keygen_hazmat():
    # generate a private key
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
    )
```

I'm expecting this to be working and finding very little on the error, only another suggestion about some possible cleanup in earlier versions of openssl 1.1.1~

Any suggestions/ideas? I can generate keys using the `openssl` cli which is also using the FIPS config globally.

**Comment by alex** [comment]
Generating an RSA key should work fine, our unit tests which call this function run under FIPS OpenSSL in CI.

Based on that error ("unable to fetch drbg"), it seems like something may not be properly setup with OpenSSL itself.

**Comment by reaperhulk** [comment]
We test RSA key generation in FIPS in our CI so it definitely works. The error you're getting is coming from internal to OpenSSL (it appears to originate from `rand_lib.c` when it fails on `EVP_RAND_fetch`), which suggests a misconfiguration of some kind in the OpenSSL you're linking unfortunately.

**Comment by Bonn93** [comment]
Wow, fast response! 

Thanks, I will look into this a bit more and update. :+1:

**Comment by Bonn93** [comment]
Hmm, i'm have a few problems here and seem to be struggling with a few different sources and implementation details here. 

I have a multi-stage dockerfile, in various stages I build 3 items: 

- OpenSSL FIPS Provider from 3.0.8 branch
- OpenSSL 3.1.2 latest
- Python 3.11.4 from cpython.git

In the final image, I merge all of my directories to the final image for runtime. 

In this final image, I perform the `fipsinstall` with these params; 

```
RUN openssl fipsinstall -out /usr/local/ssl/fipsmodule.cnf -module /usr/local/lib64/ossl-modules/fips.so
RUN openssl fipsinstall -verify -in /usr/local/ssl/fipsmodule.cnf  -module /usr/local/lib64/ossl-modules/fips.so
RUN openssl fipsinstall -in /usr/local/ssl/fipsmodule.cnf -module /usr/local/lib64/ossl-modules/fips.so
```

I then add the following file to replace the default `openssl.cnf` 

```
config_diagnostics = 1
openssl_conf = openssl_init

.include /usr/local/ssl/fipsmodule.cnf

[openssl_init]
providers = provider_sect
alg_section = algorithm_sect

[provider_sect]
fips = fips_sect
default = default_sect

[default_sect]
activate = 1

[algorithm_sect]
default_properties = fips=yes
```

When I run `openssl version -a` I get  which is what I expect.
```
root@61096fe0c8d3:/app# openssl version -a
OpenSSL 3.1.2 1 Aug 2023 (Library: OpenSSL 3.1.2 1 Aug 2023)
built on: Fri Aug 11 01:27:53 2023 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib64/engines-3"
MODULESDIR: "/usr/local/lib64/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x40000018029c67af
```
If I strace this, I can also see it loading the fips.so

```
openat(AT_FDCWD, "/usr/local/lib64/ossl-modules/fips.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=2588184, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 2394496, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f2df1c00000
mprotect(0x7f2df1c19000, 2195456, PROT_NONE) = 0
mmap(0x7f2df1c19000, 1896448, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7f2df1c19000
mmap(0x7f2df1de8000, 294912, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e8000) = 0x7f2df1de8000
mmap(0x7f2df1e31000, 98304, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x230000) = 0x7f2df1e31000
close(3)                                = 0
mprotect(0x7f2df1e31000, 90112, PROT_READ) = 0
futex(0x7f2df1e4889c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/usr/local/lib64/ossl-modules/fips.so", O_RDONLY) = 3
```

I expect with this config that it's "global" as per: https://www.openssl.org/docs/manmaster/man7/fips_module.html in the section _"Making all applications use the FIPS module by default"_

My understanding is that now if I use python in this environment, it should fips due to the global config nature. I had some tests earlier which I had expected results, but this has flipped them. I have a function im looking at with: 

```
from cryptography.hazmat.backends import default_backend

def is_fips_enabled():
    try:
        backend = default_backend()
        fips_mode = backend._fips_enabled
        return fips_mode
    except AttributeError:
        # If the backend doesn't have _fips_enabled attribute, FIPS is not supported.
        return False
```
Calling this manually, I get something I don't expect. 
```
root@61096fe0c8d3:/app# python3
Python 3.11.4 (tags/v3.11.4:d2340ef257, Aug 11 2023, 02:10:45) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> default_backend()
<OpenSSLBackend(version: OpenSSL 3.1.1 30 May 2023, FIPS: False, Legacy: True)>
>>> 
``` 

But my rsa/keygen is working. Am I missing something? I tried looking through the CI github actions, but im not very familiar with their setup and couldn't distil a similar environment that you test with. 

Full dockerfile for reference: 
```
# This step builds the fips module for later use
FROM ubuntu:22.04 as fips-builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt upgrade -y
RUN apt install build-essential checkinstall zlib1g-dev wget tar git -y
RUN git clone https://github.com/openssl/openssl.git
ARG OPENSSL_FIPS_PROVIDER_VERSION=openssl-3.0.8
RUN cd openssl && git checkout $OPENSSL_FIPS_PROVIDER_VERSION
RUN cd openssl && ./Configure enable-fips
RUN cd openssl && make -j$(nproc)
RUN mkdir -p output
RUN cd openssl && cp providers/fipsmodule.cnf ../output/fipsmodule.cnf
RUN cd openssl && cp providers/fips.so ../output/fips.so

FROM ubuntu:22.04 as openssl-builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt upgrade -y
RUN apt install build-essential checkinstall zlib1g-dev wget tar git -y
ARG OPENSSL_VERSION=openssl-3.1.2
# Clone + build OpenSSL3
RUN git clone https://github.com/openssl/openssl.git
# This builds latest OpenSSL3 - best to determine which stable to use
RUN cd openssl && git checkout $OPENSSL_VERSION
RUN cd openssl && ./Configure enable-fips
RUN cd openssl && make -j$(nproc)
RUN cd openssl && make install
RUN cd openssl && make install_fips
RUN cd openssl && ldconfig /usr/local/lib64/
RUN ldconfig /usr/local/lib64/

RUN apt-get install libssl-dev build-essential git -y
RUN apt-get install curl wget xz-utils tar zlib1g-dev -y
RUN apt-get update -y
RUN apt-get install gdb lcov pkg-config \
libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
lzma lzma-dev tk-dev uuid-dev zlib1g-dev -y

ARG PYTHON_VERSION=v3.11.4
RUN git clone https://github.com/python/cpython.git
RUN cd cpython && git checkout $PYTHON_VERSION
RUN cd cpython && ./configure --with-openssl-rpath=auto --enable-optimizations --prefix=/usr/local
RUN cd cpython && make -j$(nproc) && make install


FROM ubuntu:22.04 as final
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y && apt upgrade -y

COPY --from=fips-builder /output/fipsmodule.cnf /usr/local/ssl/
COPY --from=fips-builder /output/fips.so /usr/local/lib64/ossl-modules/fips.so
COPY --from=openssl-builder /usr/local/lib64/* /usr/local/lib64/
COPY --from=openssl-builder /usr/local/lib64/ossl-modules/* /usr/local/lib64/ossl-modules/
COPY --from=openssl-builder /usr/local/ssl/* /usr/local/ssl/
COPY --from=openssl-builder /usr/local/bin/* /usr/local/bin/
COPY --from=openssl-builder /usr/local /usr/local
COPY --from=openssl-builder /usr/lib/ /usr/lib/
COPY --from=openssl-builder /usr/include/ /usr/include/

RUN ldconfig /usr/local/lib && ldconfig /usr/local/lib64
RUN openssl fipsinstall -out /usr/local/ssl/fipsmodule.cnf -module /usr/local/lib64/ossl-modules/fips.so
RUN openssl fipsinstall -verify -in /usr/local/ssl/fipsmodule.cnf  -module /usr/local/lib64/ossl-modules/fips.so
RUN openssl fipsinstall -in /usr/local/ssl/fipsmodule.cnf -module /usr/local/lib64/ossl-modules/fips.so

ADD custom_openssl.cnf /usr/local/ssl/openssl.cnf
```

**Comment by Bonn93** [comment]
@reaperhulk sorry to ping, not if the label is supposed to be removed from my last reply.

**Comment by reaperhulk** [comment]
Sorry for the slow response here. If you're seeing a different version between the CLI and the version cryptography is reporting then you aren't compiling/linking against what you think you are. Could you expand that dockerfile to show a complete installation? cryptography doesn't care about the OpenSSL used for CPython (they're entirely independent) so a custom CPython isn't needed here to demonstrate your issue.

**Comment by Bonn93** [comment]
Hmm, I'll keep poking around, I know that it doesn't need the latest, but there's some perf issues that were supplied in OpenSSL 3.1.1, but most common install/distros have 3.0.9~

**Comment by Bonn93** [comment]
Okay, I think I found the cause and spotted it due by playing around with some final versions which gave a little hint. 

In the dockerfile, add a `requirements.txt` file and do `pip install -r requirements.txt` this seems to have been bringing in different versions when installing cryptography. 

In Ubuntu 23~ pip gave a warning that I've been kinda ignoring.. 

```
Step 24/32 : RUN pip3 install -r requirements.txt
 ---> Running in 4e3ad8bfd07f
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Removing this pip install and doing exactly as suggested the backend now returns true. 
```
root@d771abc9d19b:/app# python3
Python 3.11.4 (main, Jun  7 2023, 10:13:09) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> default_backend()
<OpenSSLBackend(version: OpenSSL 3.0.10 1 Aug 2023, FIPS: True)>
```

```
root@d771abc9d19b:/app# openssl list -providers
Providers:
  base
    name: OpenSSL Base Provider
    version: 3.0.10
    status: active
  fips
    name: OpenSSL FIPS Provider
    version: 3.0.8
    status: active
```

When I install cryptography via pip3 the `default_backend()` actually returns 3.1.1 which is confusing.

**Comment by reaperhulk** [comment]
Glad you got it figured out!

**Comment by Bonn93** [comment]
Curious how/why `pip install cryptography` installs or gets another version though. The images I built are to be used by lots of micro services, and I expect they'll probably do some `venv` style packaging and probably produce this again. Is there any recommendations to force this system wide or is this really a pip/dep issue? 

Thanks for your help :)

**Comment by Bonn93** [comment]
@reaperhulk sorry, not sure how/if I can re-open this. I'm not sure I understand why I get different outputs when I use pip to install. I am building a base image for lots of services to place their applications in. The global config doesn't seem to be applying. 

1. System installed python works and produces `FIPS: true` 
2. When a consumer of my image declares that they have a need for `cryptography` in their application, they will add this to `requirements.txt` and `pip install -r requirements.txt` 

The 2nd case breaks and gives a different openssl version ( assuming its been statically linked to a openssl build version ) but this is breaking compliance/applications `<OpenSSLBackend(version: OpenSSL 3.1.2 1 Aug 2023, FIPS: False, Legacy: True)>
`

The rest of the container: 
```
root@5835a6b3f80e:/app# openssl list -providers
Providers:
  base
    name: OpenSSL Base Provider
    version: 3.0.10
    status: active
  fips
    name: OpenSSL FIPS Provider
    version: 3.0.8
    status: active
```

I can only get this working with the system/package managers installation via `apt-get instlal python3-cryptography` which is much older than I'd like. How can the latest cryptography version be installed and respect the system-wide/openssl config?

**Comment by reaperhulk** [comment]
You're getting into distribution problems here. `pip install -r requirements.txt` is going to install using whatever python package index is default. If you're distributing a FIPS build to your users it is a requirement for you to either pre-distribute the binary wheel itself and give them mechanisms to install it or else (the normal enterprise answer) run your own internal PyPI that your systems look at first.
