### ISSUE TITLE
Help installing Cryptography on an offline RHEL 8 x86_64 machine!

### ISSUE THREAD

**Issue by bradley-rose** [pyca/cryptography#9390]
Preface: [here's a Reddit thread](https://reddit.com/r/rust/s/I29th9Jn3Q) I created discussing the same issue. 

My environment:

- RHEL 8
- Python: 3.9
- Cryptography version required: 41

I have an offline machine that I'm trying to install the Cryptography package in a Python 3.9 venv. I started by copying both of the pre-compiled manylinux wheels built for Python3.9 over to the machine and attempting to install those, but the Python interpreter told me my machine is not compatible with either of them. The command I executed: `python3 -m pip install <name of cryptography package.whl> --no-index --find-links .`

As a last resort, I tried installing the tarball, but Rust insists on contacting GitHub to update the Cargo repositories and then fails when it is unable to (this is an offline machine). When I include the offline tag in the Cargo config file, Rust starts looking for other packages that I already have installed in my Python virtual environment, so it just feels like another can of worms. 

How can I install, in the simplest way (seriously, I'm not an expert here, spell out each command if possible), the Cryptography package in my environment?

**Comment by reaperhulk** [comment]
If you want to compile cryptography in a fully offline state you'll need to fetch the rust packages (which are not vendored in the sdist) separately. We don't actually have instructions for how to do that in our docs (we should fix that!) and I don't know them offhand (although I'm sure @alex will chime in shortly 😄).

That said, if you're running RHEL8 with Python 3.9 on x86_64 then the [cryptography-41.0.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/21/74/a7ebb5bcf733b1626e4778941e505792d7f655e799ff3bdbd9a176516ee2/cryptography-41.0.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) wheel should work just fine, obviating the need to compile it yourself (if you're comfortable using PyPI binaries).

**Comment by bradley-rose** [comment]
I'll standby for the compilation instructions. I know absolutely nothing about Rust! Im a network administrator trying to install a support application that happens to require Cryptography. I know enough Python to get by, but zero Rust, so this is all new. 

I agree, I expected the wheel to work as well, but my interpreter came back and said it's incompatible! Not sure why that is. I confirmed the machine is indeed x86 with `uname -m`, and it's definitely RHEL 8 confirmed with `cat /etc/os-release`, and `python3 -V" confirms Python 3.9 as well. I'm confused. Again, enough Python to *get by* usually, but the furthest thing from an expert. 

Thanks for the swift reply so far.

**Comment by alex** [comment]
If you run `pip debug --verbose`, what is listed under Compatible tags?

**Comment by reaperhulk** [comment]
To add to Alex's question, is the version of `pip` you have installed less than 19.3? That's the version that added support for understanding what `manylinux2014` meant. 20.3+ extend pip to understand the `manylinux_x_yy` tag format too. So if your pip is older than that you should first install a newer pip wheel, then install the cryptography wheel.

**Comment by bradley-rose** [comment]
> If you want to compile cryptography in a fully offline state you'll need to fetch the rust packages (which are not vendored in the sdist) separately. We don't actually have instructions for how to do that in our docs (we should fix that!) and I don't know them offhand (although I'm sure @alex will chime in shortly 😄).
> 
> That said, if you're running RHEL8 with Python 3.9 on x86_64 then the [cryptography-41.0.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/21/74/a7ebb5bcf733b1626e4778941e505792d7f655e799ff3bdbd9a176516ee2/cryptography-41.0.3-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) wheel should work just fine, obviating the need to compile it yourself (if you're comfortable using PyPI binaries).

I just wanted to note that the `cp37` package did indeed install without the need for compilation! Thank you. I was mistakenly attempting to install [cryptography-41.0.3-pp39-pypy39_pp73-manylinux_2_28_x86_64.whl](https://files.pythonhosted.org/packages/9a/90/4c779507b50c9adf3f11f973f22d80a83097100cf9e1766b21ec4cd0bba2/cryptography-41.0.3-pp39-pypy39_pp73-manylinux_2_28_x86_64.whl) as I assume the "pp39" referred to Python 3.9. 

What does the `cp37` refer to in the filename? I'll need to note this for future installations. This isn't the first time I've run head-first into this issue!

**Comment by alex** [comment]
CPython 3.7 -- because this is an abi3 wheel, 3.7 specifies that it works with any CPython >= 3.7. The `pp39` is PyPy 3.9.

Glad it works now.
