### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [pyca/cryptography#9414]
Is it possible next time on release new version make the github release to have entry on https://github.com/pyca/cryptography/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://pgjones.dev/blog/trusted-plublishing-2023/
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by alex** [comment]
If you're interested in monitoring for new releases, PyPI offers an RSS feed for each package that can be used. Since we do not rely on any of the features of github releases, I think we're unlikely to use it purely for notifications.

**Comment by kloczek** [comment]
First ling https://pgjones.dev/blog/trusted-plublishing-2023/ shows how to add gh release to pypi publishing process.

Issue is that I have already processing email notifications from gh releases using procmail and it works not only for python modules.

**Comment by alex** [comment]
I don't believe that blog post shows creating GH releases. It shows how to use PyPI's trusted publishing process with GHA, which we already do.

**Comment by reaperhulk** [comment]
We don't currently plan to start using GH releases. Perhaps we will change our minds in the future, but for now we consider PyPI's notification systems sufficient.
