### ISSUE TITLE
How to extract a chain ca from a pem certificate which has cert private key and ca chain. 

### ISSUE THREAD

**Issue by sanjaygopinath89** [pyca/cryptography#9437]
I am trying to find out a method to extract ca cert chain(root and the intermediate cert) from a pem certificate 

We have the pem certificate with private key and chain, and i use below method to extract private key. How i can get the chain extracted from same pem cert. ? 

`
private_key = serialization.load_pem_private_key(pem_data, password=password)
pem_private_key = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    ).decode('utf-8')`

**Comment by alex** [comment]
https://cryptography.io/en/latest/x509/reference/#cryptography.x509.load_pem_x509_certificates may be what you're looking for
