### ISSUE TITLE
ImportError: DLL load failed while importing _rust

### ISSUE THREAD

**Issue by SteffenAtWork** [pyca/cryptography#9444]
Hello,

I'm stuck with the error in the title and tried a lot of things to get rid of it. I hope, I'm in the right place because cryptography is "only" used as dependency in another module (requests_ntlm2). When I run the code from powershell (python myscript.py) it runs fine. But when I use the same code to run it as a Windows service (pywin32) I get always the traceback shown later. 

Environment:
- I run the powershell as the same user than is configured for the Windows service (it's an account in ActiveDirectory, no local account)
- Windows Server 2016 (german)
- Python 3.10.11
- All packages are globally installed with pip as administrator

I've uninstalled already cryptography and its dependencies but no change after reinstall (postinstall-script for pywin32 executed several times). I've compared environment-variables in both cases and found only minor differences (see screenshot). I've imported  other modules without any problems (e. g. requests). I've also played around with different PYTHONPATH-variations, but I don't know where the DLL should be (the other modules seem to be found as seen in the Traceback). I also found [Issue 7836](https://github.com/pyca/cryptography/issues/7836) but it contains no hint, where else I could look.

Code which forces the error:
```
from requests_ntlm2 import (
            HttpNtlmAuth,
            HttpNtlmAdapter,
            NtlmCompatibility
        )
```

Traceback:
```
Python could not import the service's module 
Traceback (most recent call last):
  File "C:\OutputFactory\Skripte\OutputFactory.Infinica.Error_Monitoring_Service\pyWinService.py", line 10, in <module>
    import ServiceWorkerImpl
  File "C:\OutputFactory\Skripte\OutputFactory.Infinica.Error_Monitoring_Service\ServiceWorkerImpl.py", line 7, in <module>
    from requests_ntlm2 import (
  File "C:\Program Files\Python310\lib\site-packages\requests_ntlm2\__init__.py", line 1, in <module>
    from .adapters import HttpNtlmAdapter, HttpProxyAdapter
  File "C:\Program Files\Python310\lib\site-packages\requests_ntlm2\adapters.py", line 8, in <module>
    from .connection import DEFAULT_HTTP_VERSION
  File "C:\Program Files\Python310\lib\site-packages\requests_ntlm2\connection.py", line 12, in <module>
    from .core import NtlmCompatibility, get_ntlm_credentials, noop
  File "C:\Program Files\Python310\lib\site-packages\requests_ntlm2\core.py", line 8, in <module>
    from cryptography import x509
  File "C:\Program Files\Python310\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "C:\Program Files\Python310\lib\site-packages\cryptography\x509\certificate_transparency.py", line 11, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: DLL load failed while importing _rust: Das angegebene Modul wurde nicht gefunden.
 
%2: %3
```

Packages
```
PS C:\> python -m pip list -v
Package            Version   Location                                     Installer
------------------ --------- -------------------------------------------- ---------
asttokens          2.2.1     c:\program files\python310\lib\site-packages pip
backcall           0.2.0     c:\program files\python310\lib\site-packages pip
certifi            2023.7.22 c:\program files\python310\lib\site-packages pip
cffi               1.15.1    c:\program files\python310\lib\site-packages pip
charset-normalizer 3.2.0     c:\program files\python310\lib\site-packages pip
colorama           0.4.6     c:\program files\python310\lib\site-packages pip
cryptography       41.0.3    c:\program files\python310\lib\site-packages pip
decorator          5.1.1     c:\program files\python310\lib\site-packages pip
executing          1.2.0     c:\program files\python310\lib\site-packages pip
idna               3.4       c:\program files\python310\lib\site-packages pip
ipython            8.14.0    c:\program files\python310\lib\site-packages pip
jedi               0.19.0    c:\program files\python310\lib\site-packages pip
matplotlib-inline  0.1.6     c:\program files\python310\lib\site-packages pip
ntlm-auth          1.5.0     c:\program files\python310\lib\site-packages pip
parso              0.8.3     c:\program files\python310\lib\site-packages pip
pickleshare        0.7.5     c:\program files\python310\lib\site-packages pip
pip                23.2.1    c:\program files\python310\lib\site-packages pip
prompt-toolkit     3.0.39    c:\program files\python310\lib\site-packages pip
pure-eval          0.2.2     c:\program files\python310\lib\site-packages pip
pycparser          2.21      c:\program files\python310\lib\site-packages pip
Pygments           2.16.1    c:\program files\python310\lib\site-packages pip
PyMuPDF            1.22.5    c:\program files\python310\lib\site-packages pip
pyodbc             4.0.39    c:\program files\python310\lib\site-packages pip
pywin32            306       c:\program files\python310\lib\site-packages pip
requests           2.31.0    c:\program files\python310\lib\site-packages pip
requests-ntlm2     6.5.3     c:\program files\python310\lib\site-packages pip
setuptools         68.1.0    c:\program files\python310\lib\site-packages pip
six                1.16.0    c:\program files\python310\lib\site-packages pip
stack-data         0.6.2     c:\program files\python310\lib\site-packages pip
traitlets          5.9.0     c:\program files\python310\lib\site-packages pip
urllib3            2.0.4     c:\program files\python310\lib\site-packages pip
wcwidth            0.2.6     c:\program files\python310\lib\site-packages pip
```

Environment-variables (left side run as Windows service, right side started directly from Powershell)
![image](https://github.com/pyca/cryptography/assets/142516218/ef0e61d4-889f-418b-9066-5d47ee32391d)

Any tip what I'm doing wrong?

Best regards
Steffen

**Comment by alex** [comment]
Can you please provide instructions for how we can reproduce this from a fresh Windows machine, it's very difficult for us to debug without knowing the exact steps taken to install.

Further, are you able to provide the error messages in english? Not speaking German (at least, not in the last 15 years) means I cannot understand the error message.

**Comment by SteffenAtWork** [comment]
Hello @reaperhulk, hello @alex
thank you for your fast reactions and your work in this project. I'll try to give some more helpful information:
First of all: I don't want you to waste a lot of time, trying to reproduce the behaviour. My hope is, you have an idea, what side-effect could trigger the problem.
I understand, that the problem could be related to pywin32 (or even "in between" in the module requests_ntlm2). I strated with the issue here because it seems, that the code did make a good way into the cryptography module (based on the traceback). It seems to bee related to the x509 module, see last two lines in the traceback (tried to translate to english):
```
from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: DLL load failed while importing _rust: The specified module was not found.
```
What my directories look like
![image](https://github.com/pyca/cryptography/assets/142516218/3a37991f-7e78-4e83-a544-44bcaa84db17)
![image](https://github.com/pyca/cryptography/assets/142516218/fecdd4be-ec11-4019-b006-dee207a5c85b)

What is working in both cases (run a simple script from a non elevated powershell with "python myscript.py" vs. a python service wich consists of several classes/modules installed as (pywin32) service). As mentioned before I run the service and the script with the same User-Account

- import cryptography

What is **only** working when executed directly as script but **not** as service:
- import cryptography.hazmat.bindings._rust (leads to the already known Exception DLL load failed while importing _rust: The specified module was not found.)

Because of this simple test, I don't believe it is an error in the requests_ntlm2 module (from the original traceback in my first post)

Best regards
Steffen

**Comment by reaperhulk** [comment]
`_rust.pyd` is the rust module we use in many parts of our codebase. Your screenshot shows it is present on the FS and you said it works when you use it via our standard supported mechanism, so there is something causing issues when using pywin32. We've never seen this before, so you'll probably need to contact that project.

**Comment by SteffenAtWork** [comment]
In my case I could fix it by reinstalling pywin32 and execute the post_install script which came with pywin32:
python Scripts/pywin32_postinstall.py -install

**Comment by CoderYunTang** [comment]
In pyo3 import "cryptography. Hazmat. Bindings. _rust", there is this error. I don't know how to solve it [issue](https://github.com/PyO3/pyo3/issues/3425)
