### ISSUE TITLE
restore SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER constant?

### ISSUE THREAD

**Issue by julianz-** [pyca/cryptography#9460]
The constant SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER
was removed because it was described as unused in https://github.com/pyca/cryptography/commit/895de04c7318edf0ecb5d55c4758598ff6d79724. However, in https://github.com/cherrypy/cheroot/issues/245 I found that we needed it, in order to make PyOpenSSL work satisfactorily without throwing random WantReadError and WantWriteErrors.  If there's an alternative or better way of handling this issue please advise.

**Comment by reaperhulk** [comment]
fixed in #9461
