### ISSUE TITLE
Ed25519PublicKey.from_public_bytes slow

### ISSUE THREAD

**Issue by nschloe** [pyca/cryptography#9463]
In my application, the creation of a `Ed25519PublicKey` via `from_public_bytes` is _much_ slower than for in other cryptography frameworks, e.g., [PyNaCl](https://github.com/pyca/pynacl/).

MWE:

```python
import time

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from nacl.encoding import HexEncoder
from nacl.signing import VerifyKey
import ed25519 as ed

# create keys, signature with ed25519
priv_key, pub_key = ed.create_keypair()
pub_key_hex = pub_key.to_ascii(encoding="hex").decode()
enc_bytes = b"Lorem ipsum dolor sit amet, consectetur adipisici elit"
sig = priv_key.sign(enc_bytes, encoding="hex")
sig_bytes = bytes.fromhex(sig.decode())
# pub_key.verify(sig, enc_bytes, encoding='hex')

# PyNaCl
t0 = time.time()
verify_key = VerifyKey(pub_key_hex.encode(), encoder=HexEncoder)
t1 = time.time()
verify_key.verify(enc_bytes, sig_bytes)
t2 = time.time()
print("PyNaCl key creation:", t1 - t0)
print("PyNaCl verify:", t2 - t1)
print("PyNaCl total:", t2 - t0)

# cryptography
public_key_bytes = pub_key.to_bytes()
# public_key_bytes = bytes.fromhex(pub_key_hex)
t0 = time.time()
public_key = Ed25519PublicKey.from_public_bytes(public_key_bytes)
t1 = time.time()
public_key.verify(sig_bytes, enc_bytes)
t2 = time.time()
print()
print("cryptography key creation:", t1 - t0)
print("cryptography verify:", t2 - t1)
print("cryptography total:", t2 - t0)
```
```
PyNaCl key creation: 5.4836273193359375e-06
PyNaCl verify: 0.00010919570922851562
PyNaCl total: 0.00011467933654785156

cryptography key creation: 0.05546712875366211
cryptography verify: 0.00035071372985839844
cryptography total: 0.05581784248352051
```

This is with

- Python 3.11.3
- cryptography 41.0.3
- cffi 1.15.1
- pip 23.2.1
- setuptools 68.1.2

**Comment by reaperhulk** [comment]
This is, unfortunately, a property of OpenSSL's current key loading APIs (which became much worse in 3.0.x before slightly improving in 3.1.x while still being substantially worse than 1.1.1). We have some ideas how to improve this, but no timeline as of yet 😞

**Comment by reaperhulk** [comment]
To be clear, we're unlikely to reach PyNaCl's performance here for a variety of reasons, but OpenSSL 1.1.1 is slightly over 2x faster on my laptop vs the current 3.1.2.

**Comment by reaperhulk** [comment]
PyNaCl's `VerifyKey` also doesn't do any initialization of the key. That is done in `verify` (https://github.com/pyca/pynacl/blob/main/src/nacl/signing.py#L137), so for an apples to apples performance comparison you really need to perform a verification in addition to loading the key itself.

**Comment by nschloe** [comment]
> so for an apples to apples performance comparison you really need to perform a verification in addition to loading the key itself.

I have that in my actual code, and PyNaCl is still much faster. Will update the original example accordingly.

**Comment by nschloe** [comment]
Updates the original post. Indeed, PyNaCl's first verification is slower than its key init (as opposed to cryptography), but still about 500 times faster than cryptography.

**Comment by reaperhulk** [comment]
I took a closer look at this and it looks like OpenSSL is doing some sort of lazy initialization of internals because only the first loaded key is slow. Subsequent loads are nearly as fast as PyNaCl:

```
cryptography key load: 0.03046703338623047
cryptography second key load: 7.867813110351562e-06
```

**Comment by nschloe** [comment]
Wait what am I supposed to reply?

**Comment by reaperhulk** [comment]
We use the bot to just make sure we stay on top of items where we can take action, but the messaging is sometimes a bit confusing. 😄

In this case it appears after one key load all subsequent key loads are approximately the same speed as PyNaCl. The same is true of performing a verification. This strongly suggests OpenSSL is doing lazy initialization, which improves import speed at the cost of a slower first operation.

Some benchmarks with a single throwaway key load + verify before performing the benchmark:

```
PyNaCl key creation: 5.245208740234375e-06
PyNaCl verify: 0.00020694732666015625
PyNaCl total: 0.00021219253540039062

cryptography key creation: 9.059906005859375e-06
cryptography verify: 0.0002040863037109375
cryptography total: 0.00021314620971679688
```

I don't think there's any action we can take here that would be helpful, but if you disagree please let us know!

**Comment by nschloe** [comment]
Thanks for the clarification! I agree.
