### ISSUE TITLE
The mode attribute for Cipher() should be Optional ...?

### ISSUE THREAD

**Issue by madscientist** [pyca/cryptography#9464]
I'm getting a type error from mypy when I pass None as the mode to Cipher, but according to the code this is OK...?  I'm using RC4 (yes I know it's not great but the software I'm connecting to needs it), but:

https://github.com/pyca/cryptography/blob/c61ab8735b0405afae059f1378c1ba3acf7ca59e/src/cryptography/hazmat/primitives/ciphers/base.py#L78

shows that the type of `mode` is `Mode`, but the implementation seems to suggest that `None` is OK and indeed if I pass `None` it works.

Shouldn't the type be `Optional[Mode]` here instead?

**Comment by reaperhulk** [comment]
`Mode` is actually a `TypeVar` with the following declaration

https://github.com/pyca/cryptography/blob/c61ab8735b0405afae059f1378c1ba3acf7ca59e/src/cryptography/hazmat/primitives/ciphers/base.py#L73-L75

This makes it Optional (and we test this in CI with `mypy` across our test suite, which has a variety of tests where we pass `None` for mode. For example: https://github.com/pyca/cryptography/blob/c61ab8735b0405afae059f1378c1ba3acf7ca59e/tests/hazmat/primitives/test_chacha20.py#L38-L40

What are you using for your type checking? It's possible that the checker you're using is too old or doesn't support this properly.

**Comment by reaperhulk** [comment]
Ugh, I see you say mypy, sorry. What version are you using?

**Comment by madscientist** [comment]
You're right: I'm using mypy 0.761 and I get a warning but on another system where I have mypy 0.971 I don't.  Sigh.  OK thx.
