### ISSUE TITLE
How to sign a CSR with PSS padding?

### ISSUE THREAD

**Issue by gregbreen** [pyca/cryptography#9467]
I see in the code (https://github.com/pyca/cryptography/pull/8888), and in #5691 and #2850, that PSS padding was added to x509 certificate signing. Is it possible to sign a CSR with PSS padding? Equivalent to this kind of operation:

```
openssl req -new -key key.pem -sha256 -out csr.pem -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1
```

Or does it require an `rsa_padding` parameter to be added to the `sign()` method of `CertificateSigningRequestBuilder`?

**Comment by reaperhulk** [comment]
I'm interested in your use case here -- is there a public CA that requires the use of PSS CSR signature to denote that you want a PSS signed certificate?

**Comment by gregbreen** [comment]
Hi both. Thanks for the comments.

@reaperhulk , AWS IoT Core recently added support for RSA PSS signing algorithms: https://aws.amazon.com/about-aws/whats-new/2023/07/aws-iot-core-new-certificate-signing-key-generation-algorithms/

So users could have a workflow like this:

```
openssl genrsa -out key.pem 2048
openssl req -new -key key.pem -sha256 -out csr.pem -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1
aws iot create-certificate-from-csr --certificate-signing-request=file://csr.pem
```

That wouldn't produce a certificate with RSA PSS signature.

**Comment by gregbreen** [comment]
Thanks @alex !

**Comment by alex** [comment]
@reaperhulk did the work
