### ISSUE TITLE
Cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust'

### ISSUE THREAD

**Issue by SpanditLenkaTR** [pyca/cryptography#9513]
Hi team,

We are getting the error - **"Cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' "** while running AWS lambda service in our repo. We are getting 502 error code with this error message.
FYI - We have already performed all the debug steps as mentioned in FAQ.
We are using the following versions of the libraries-
setuptools - 68.1.0
pip - 23.2.1
cryptography - 41.0.3
cffi - 1.15.1
Python - 3.8

We tried installing cryptography in both ways - 
1. pip install cryptography==41.0.3 (explicitly installed this library)
2. pip install pyjwt[crypto]==2.4.0 (it got installed from backend)

Can you please let us know any pointers on how to resolve this or if we are missing anything else?

**Comment by alex** [comment]
Can you provide steps to reproduce this issue?

**Comment by klubi** [comment]
I have the same issue.

I'm building a custom JWT token authorizer for API Gateway.
requirements.txt:
```txt
pyjwt[crypto]
```
I'm using terraform lambda module to deploy it, and as soon as I include `cryptography` folder in final package then lambda invocations fail with mentioned error.

Code that requires cryptography code:
```python
def get_jwks_url(issuer_url):
    well_known_url = issuer_url + ".well-known/openid-configuration"
    with urllib.request.urlopen(well_known_url) as response:
        well_known = json.load(response)
    if 'jwks_uri' not in well_known:
        raise Exception('jwks_uri not found in OpenID configuration')
    return well_known['jwks_uri']


def decode_and_validate_token(token, authorizations):
    unvalidated = jwt.decode(token, options={"verify_signature": False})

    if unvalidated['iss'] not in authorizations.keys():
        raise Exception(f"{unvalidated['iss']} issuer is not allowed")

    allowed_audiences = authorizations[unvalidated['iss']]
    jwks_url = get_jwks_url(unvalidated['iss'])
    jwks_client = jwt.PyJWKClient(jwks_url)
    header = jwt.get_unverified_header(token)
    key = jwks_client.get_signing_key(header["kid"]).key
    return jwt.decode(token, key=key, algorithms=[header["alg"]], audience=allowed_audiences)
```

**Comment by reaperhulk** [comment]
cryptography contains native code. If you are packaging your local install for lambda then that will never work. See https://cryptography.io/en/latest/faq/#i-m-getting-errors-installing-or-importing-cryptography-on-aws-lambda (and specifically look at "Working with built distributions (wheels)")
