### ISSUE TITLE
Add binding for SSL_CTX_set1_curves_list

### ISSUE THREAD

**Issue by evilaliv3** [pyca/cryptography#9562]
Hello,

This ticket is to re-bump the conversation started in https://github.com/pyca/cryptography/issues/4980.

Since some years have passed i would love to know if there are now some possibility to call these API in python.

This would be the unique way for example to implement server side preferences like described in https://community.letsencrypt.org/t/when-choosing-an-elliptic-curve-look-for-a-safe-curve/161837

Thank you!

**Comment by alex** [comment]
What's the use case here? At this point we basically only add new bindings for which there's a use case we intend to support in either cryptography itself or pyOpenSSL.

pyOpenSSL already has `set_tmp_ecdh`, is this sufficient for what you're seeking to implement?
