### ISSUE TITLE
Call to `utcfromtimestamp` deprecated in Python 3.12

### ISSUE THREAD

**Issue by mathiasertl** [pyca/cryptography#9580]
`src/rust/src/x509/sct.rs` still calls `datetime.utcfromtimestamp()`, which is deprecated in Python 3.12. The Python 3.12. release notes say:

> call [now()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.now) and [fromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.fromtimestamp) with the tz parameter set to [datetime.UTC](https://docs.python.org/3.12/library/datetime.html#datetime.UTC).

Unfortunately my rust-skills are non-existent, so I cannot contribute without a huge effort on what I suspect will be a very trivial change. I hope that's okay.

This is related to #9260.

**Comment by woodruffw** [comment]
I can do this real quick.

**Comment by mathiasertl** [comment]
Thanks @woodruffw !
