### ISSUE TITLE
"Unable to import module 'lambda_function': cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)",

### ISSUE THREAD

**Issue by Nethra4596** [pyca/cryptography#9640]
Hi,

I have installed pysftp and paramiko packages with contains "cryptography" as a dependency package. I am importing this to AWS lambda with runtime python3.9 and tested out. But it throws error as "Unable to import module 'lambda_function': cannot import name 'exceptions' from 'cryptography.hazmat.bindings._rust' (unknown location)",

I have installed al latest versions for pysftp and also paramiko, but still throws error. Please help to resolve the issue

The below screenshot is the paramiko library installed with the dependencies and versions.

![image](https://github.com/pyca/cryptography/assets/124179874/209644aa-004c-496a-a9a4-7dcd7bc555e6)

![image](https://github.com/pyca/cryptography/assets/124179874/fd8e4499-8458-43cc-9653-8816bae18fd8)

**Comment by alex** [comment]
You cannot use a windows package on AWS lambda. Please see https://cryptography.io/en/latest/faq/#i-m-getting-errors-installing-or-importing-cryptography-on-aws-lambda
