### ISSUE TITLE
cryptography.exceptions.InternalError: Unknown OpenSSL error

### ISSUE THREAD

**Issue by cmol** [pyca/cryptography#9657]
Let me start by prefacing that I find it likely that I have a local bug to my system and not cryptography, however I am not sure how to fix this issue.

Background, I am running Ubuntu 23.04 on a machine that has been upgraded through various python versions since 2021 sometime. Last time I know that I had things working was spring of 2022 when I definitely had ansible running.

Versions

 - Python 3.11.4
 - cryptography           38.0.4 (as reported by pip, though it seems pip has changed since I last used it...)
 - pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
 - setuptools             66.1.1
 - cannot find `cffi`

I can reproduce the bug with `python3 -c  "from OpenSSL import crypto"`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 9, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 228, in <module>
    Binding.init_static_locks()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 188, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 176, in _ensure_ffi_initialized
    _openssl_assert(
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 90, in _openssl_assert
    raise InternalError(
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126615813, lib=15, reason=786693, reason_text=b'error:078C0105:common libcrypto routines::init fail')])
```

Not sure how cryptography was installed though I expect as part of an ansible requirement.

This smells to me like OpenSSL 3.x changes, but I must admit that I spend most of my time not in the python world.

I would guess that I need to purge all pip installed packages and get tings installed via pipx or perhaps just via apt, but since pip throws errors about being a managed system, I am not entirely sure how to reach that point.

Thank you in advance.

**Comment by alex** [comment]
In general, without steps to reproduce in a clean virtualenv, it's very difficult for us to provide any advice.

The error message you have here indicates some error with OpenSSL loading shared libraries it relies on. If you have a copy of cryptography installed that links against a copy of OpenSSL that no longer exists on the system, that could certainly cause this.

**Comment by cmol** [comment]
Hi @alex ,

Yeah, I know it's not great and the steps to reproduce seems a bit of a moot point as I think it's an env issue, not a package issue.

How would you go about fixing a broken pip system like this one? Or would you not, and just start anew? I am somewhat surprised my desktop still works if python can't do OpenSSL right now.

**Comment by alex** [comment]
I'd blow it away. If that's impractical for some reason, your best bet is to create an isolated virtualenv (perhaps with a non-system python) and work there.

**Comment by cmol** [comment]
@alex Alright, thank you for the input!
