### ISSUE TITLE
Cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by vkajale9** [pyca/cryptography#9669]
Facing below error while running AWS lambda service in our repo. We are getting 500 "Internal server error" error code with this error message.
cannot import name 'ObjectIdentifier' from 'cryptography.hazmat.bindings._rust' (unknown location).

**Comment by alex** [comment]
Did you follow Amazon's instructions for building your lambda? https://cryptography.io/en/latest/faq/#i-m-getting-errors-installing-or-importing-cryptography-on-aws-lambda
