### ISSUE TITLE
Unable to load private key

### ISSUE THREAD

**Issue by vinayaknagar** [pyca/cryptography#9709]
I am getting this error :  
Unable to load private key : /usr/local/lib/python3.10/dist-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: FIPS_mode

i am using OpenSSL=3.0.2, cryptography=3.3.1,pyOpenSSL=19.1.0

I am using IMX7 which is in yocto environment.

**Comment by alex** [comment]
OpenSSL 3.0 is only supported in cryptography 35+ https://cryptography.io/en/latest/changelog/#v35-0-0

**Comment by syed-ga** [comment]
Hi,

When I try to install cryptography 35+, RUST compiler is must. But I am doing this in docker, how shall I install cryptography?

**Comment by alex** [comment]
Have you followed the instructions in https://cryptography.io/en/latest/installation/?
