### ISSUE TITLE
Bug: CertificateRevocationList.is_signature_valid fails to validate EC signature of CRL created using CertificateRevocationListBuilder

### ISSUE THREAD

**Issue by vkhoroz** [pyca/cryptography#9820]
**Problem:**
Cryptography fails to validate the signature of the CRL which was generated using Cryptography, when using the CertificateRevocationList.is_signature_valid.

**Workaround:**
A workaround is to use the Cryptography key primitives to validate the signature.
But, that is inconvenient, as a different logic needs to be written for each key type.

**Env to Reproduce:**
- Python 3.10.13
- cffi  1.15.1
- cryptography  41.0.3
- pip  22.2.2
- setuptools  68.1.2
- openssl-3.0.10-r0
- Linux Alpine 3.17.5 and Linux Ubuntu 22.04.1, kernel 5.19.0-35-generic
- Cryptography installed from Python Wheel

**Steps to Reproduce:**
1. Generate a self-signed CA with EC keys using OpenSSL.
2. Generate a dummy CRL list using Cryptography's CertificateRevocationListBuilder, and sign it using the above CA.
3. Verify the CRL signature using CertificateRevocationList.is_signature_valid - it fails.

An attached Python script can be used to reproduce the problem: [test_cryptography_crl.txt](https://github.com/pyca/cryptography/files/13242653/test_cryptography_crl.txt).
Note, that both OpenSSL and key primitives tell that the CRL signature is OK.

A sample output of the script run:
```
$ python tests/test_cryptography_crl.txt
read EC key
writing EC key
WRONG: Cryptography CRL signature validation failed, it gives no detail
OK: Cryptography direct signature validation passed
verify OK
Certificate Revocation List (CRL):
        Version 2 (0x1)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = Factory-CA, OU = {{ factory }}
        Last Update: Nov  2 17:31:51 2023 GMT
        Next Update: Nov  2 17:41:51 2023 GMT
Revoked Certificates:
    Serial Number: 7B
        Revocation Date: Nov  2 17:31:51 2023 GMT
        CRL entry extensions:
            X509v3 CRL Reason Code: critical
                Privilege Withdrawn
    Signature Algorithm: ecdsa-with-SHA256
    Signature Value:
        30:44:02:20:41:6f:bb:2c:ef:47:56:16:33:18:45:94:07:41:
        2a:94:cc:d3:fe:6a:a7:db:4c:7f:22:28:7f:db:a9:36:b2:b9:
        02:20:3c:8e:2e:be:ed:7a:de:7c:05:80:db:32:6a:b6:fb:12:
        31:ac:9b:72:b5:8b:45:f8:0d:55:bc:ca:f3:36:e0:f0
-----BEGIN X509 CRL-----
MIHbMIGDAgEBMAoGCCqGSM49BAMCMC0xEzARBgNVBAMMCkZhY3RvcnktQ0ExFjAU
BgNVBAsMDXt7IGZhY3RvcnkgfX0XDTIzMTEwMjE3MzE1MVoXDTIzMTEwMjE3NDE1
MVowJTAjAgF7Fw0yMzExMDIxNzMxNTFaMA8wDQYDVR0VAQH/BAMKAQkwCgYIKoZI
zj0EAwIDRwAwRAIgQW+7LO9HVhYzGEWUB0EqlMzT/mqn20x/Iih/26k2srkCIDyO
Lr7tet58BYDbMmq2+xIxrJtytYtF+A1VvMrzNuDw
-----END X509 CRL-----
```

**Comment by vkhoroz** [comment]
**A note to maintainers:**

It seems that the problem goes from this code line: https://github.com/pyca/cryptography/blob/fcc2bba8a0e694346695fe11ab008e645c547b98/src/rust/src/x509/crl.rs#L392.
But, as `CertificateRevocationList.is_signature_valid` gives no detail about _why signature validation failed_ it is no more than my best guess.

I'd recommend introducing a new method like `CertificateRevocationList.verify_signature` which raises an exception providing some diagnostics about what went wrong. That would help a lot to debug and fix problems like this.

**Comment by alex** [comment]
Your code has:

```
    # Verify that cryptography tells that the CRL signature is invalid
    if crl.is_signature_valid(ca.public_key()):
        print("WRONG: Cryptography CRL signature validation failed, it gives no detail")
    else:
        print("OK: Cryptography CRL signature validation passed")
```

But this condition is backwards. `crl.is_signature_valid()` returns true on a valid signature, but you declare that "WRONG".

**Comment by vkhoroz** [comment]
OMG. Wasting so much effort just to realize that I did a silly mistake.

Thanks @alex and sorry for this invalid bug.
