### ISSUE TITLE
How do I use cryptography on Graviton?

### ISSUE THREAD

**Issue by justgotthis** [pyca/cryptography#9851]
Currently we are running our Python code on x86 and it includes the cryptography package. When we run it on Lambda arm64 Graviton, we get the following error:

"/var/task/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory" 

Is the reason the way it is being built? What do I need to change to make cryptography run on Lambda ARM architecture?

**Comment by alex** [comment]
How are you building your ARM lambda package?

We test and releaes for ARM64, so cryptography is fully supported there.

**Comment by justgotthis** [comment]
Currently we don't have an ARM pipeline so it's being built on x86. Is
there a way to force requirements.txt to download the ARM package for
cryptography? I read somewhere I can but not sure about the details.
Something like:

cryptography 41.0.0 ; platform==aarch64

-Luis.

**Comment by alex** [comment]
You can try `--platform`, but that's your issue right there.

**Comment by justgotthis** [comment]
Thanks. What is the name of the platform for Alpine? I don't know the
platform short names I am capable of putting in requirements.txt to try.

-Luis.

**Comment by alex** [comment]
At this point these questions are not specific to pyca/cryptography, and I recommend you utilize a general purpose Python packaging resource, we're not able to provide support for things beyond pyca/cryptography itself.
