### ISSUE TITLE
Cryptography fails to verify signature on CSR geneated by IIS

### ISSUE THREAD

**Issue by felixfontein** [pyca/cryptography#9879]
This was originally reported as an error in the community.crypto Ansible collection (https://github.com/ansible-collections/community.crypto/issues/672). Reproducer using cryptography:
```py
from cryptography.x509 import load_pem_x509_csr

CSR = b"""
-----BEGIN NEW CERTIFICATE REQUEST-----
MIIEVDCCAzwCAQAwWjELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMRAwDgYD
VQQHDAdIb3VzdG9uMQ0wCwYDVQQKDARhY21lMQswCQYDVQQLDAJJVDENMAsGA1UE
AwwEYWNtZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALiLT1pl5TGf
pl/luNgFPXfBzeDvTlFbxTEiTITK2ws7XE6PLEneUKg41vSUHaJmX9k9lhk8MEde
EBMoIwLxf3pfAQEOryDrcq+Zh6tXRsNAHlJUzX4JREdQttWNbB7Wr53Ln3e5xdni
6Q/i6MVSePoxRmXL8FWACb0gzkeqJEp+DiXG+P47A3EngIGSecITk7ylZj40b3tR
gPLjgyw31xt8Qsa9FQX2Lq7KrU2JPoY4stOZQG8hE8E9OsEB7AsNFcl6jfFQDe1w
NGYOnyRRlBcfVAWBvEFuKMg0gKM7/Szv0+t81BQbq8w6bfmUBVrRAGF1mOnU+BUZ
TfTwtzHnRjcCAwEAAaCCAbMwHAYKKwYBBAGCNw0CAzEOFgwxMC4wLjE0MzkzLjIw
TQYJKwYBBAGCNxUUMUAwPgIBBQwaVEJPLUlUVFMwMC5hbHYuYXV0b2xpdi5pbnQM
EEFQXHotbWFyZWsudGFsYXMMC0luZXRNZ3IuZXhlMHIGCisGAQQBgjcNAgIxZDBi
AgEBHloATQBpAGMAcgBvAHMAbwBmAHQAIABSAFMAQQAgAFMAQwBoAGEAbgBuAGUA
bAAgAEMAcgB5AHAAdABvAGcAcgBhAHAAaABpAGMAIABQAHIAbwB2AGkAZABlAHID
AQAwgc8GCSqGSIb3DQEJDjGBwTCBvjAOBgNVHQ8BAf8EBAMCBPAwEwYDVR0lBAww
CgYIKwYBBQUHAwEweAYJKoZIhvcNAQkPBGswaTAOBggqhkiG9w0DAgICAIAwDgYI
KoZIhvcNAwQCAgCAMAsGCWCGSAFlAwQBKjALBglghkgBZQMEAS0wCwYJYIZIAWUD
BAECMAsGCWCGSAFlAwQBBTAHBgUrDgMCBzAKBggqhkiG9w0DBzAdBgNVHQ4EFgQU
0OjvNAaTsTgXXKjKVY3XWd6hA+8wDQYJKoZIhvcNAQEFBQADggEBAKCl41BSID7O
+jxgy7AtWc7V/9zo+Oag3ag8HuJn1g1HhOILTd4VZhLJqpPZ41TKmix6TdpmNjjC
jNwy2BBt25GIto+vyIQELSiD6eZrFIAhhBibu4VfibCCAq/MIgNE6sbQuEbCAIOp
gvjENjqArlKCQ4JKmlVBBxXSl5dPT6ofdF78hxyGYrLzefgdWpR6XWue0FA7WNl9
mZR56HOb0F8bNtzNoQRacokaI7rYDhrpY0CE2cJ5GA/hhHNca17T23VdXUQl67Vz
EdhDdjvqUh3S+1hA0HyMOUOxcNod9xWUxz75l3aKB7oLDZ3KizX0S3BUM2hz9rrJ
Xja233p3p3I=
-----END NEW CERTIFICATE REQUEST-----
"""

csr = load_pem_x509_csr(CSR)
print(csr.is_signature_valid)
```
This prints `False`. If you store the CSR on disk and run `openssl req -in csr.csr -noout -verify`, OpenSSL claims the CSR is fine (`Certificate request self-signature verify OK`).

**Comment by alex** [comment]
This is because the certificate has an RSA+SHA1 signature. SHA1 is not secure (and hasn't been for several years).

As a result, cryptography doesn't validate x.509 signatures performed with SHA1.

I'm not familiar with IIS, but surely there's a way to configure it to use SHA256.

**Comment by felixfontein** [comment]
I guess it would be better if `is_signature_valid` would not simply allow `True`/`False` but give more information, like in this case "insecure signature scheme, didn't validate" or "unknown signature scheme" (if SHA1+RSA support has been completely removed)). Right now I would interpret `False` as "signature is wrong", which is not the case here.

**Comment by alex** [comment]
I agree that it would have been a better design to be able to include more information, there's quite a few different ways the signature could be invalid.

Unfortunately, we're kind of stuck with this method for now.
