### ISSUE TITLE
Unable to import module 'lambda_function': cannot import name 'x509' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by huu-nguyen** [pyca/cryptography#9881]
Hello guys,

When I downloaded and installed the "azure-identity" library to use on AWS Lambda, it was installed with the "cryptography" package version 41.0.5.
I zipped the library and added it to Layers of AWS Lambda but it got the error as shown in the picture, is there any way to solve this problem?

AWS Lambda Runtime: Python 3.9
AWS Lambda Architecture: x86_64

Thanks

![image](https://github.com/pyca/cryptography/assets/103364943/aff1bb19-71de-482b-bc2b-6fe995783fdc)

**Comment by alex** [comment]
Did you create your lambda zip on a Linux machine compatible with the Lambda environment?

See: https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-native-libraries

**Comment by huu-nguyen** [comment]
> Did you create your lambda zip on a Linux machine compatible with the Lambda environment?
> 
> See: https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-native-libraries

Thanks. It worked.
