### ISSUE TITLE
Improve development documentation for TDD

### ISSUE THREAD

**Issue by adiroiban** [pyca/cryptography#9975]
A few things I noted while trying to development a patch

I will follow up with a PR.

------

Dev dependencies don't talk about rust - https://cryptography.io/en/latest/development/getting-started/#development-dependencies

I know that you find find info about `rust`, but maybe it whould help to have a quick start for Python developers.
For example, for those contributors that will not do dev work on the rust code. 

------

Doing TDD via `nox` is slow

If you work on a single test, coverage and distributed test run will just slow you down.
You can run coverage later, after you are happy with the tests.

Now my example for bindings, might not be the best, as for bindings you will want to recompile

```
$ time nox -e tests  -- tests/hazmat/bindings/test_openssl.py

real    0m21.207s
user    0m37.057s
sys     0m4.543s
```

vs

```
$ time pytest -n auto --dist=worksteal --cov=cryptography --cov=tests --durations=10 tests/hazmat/bindings/test_openssl.py

real    0m6.638s
user    0m27.316s
sys     0m3.032s

```

vs

```
$ time pytest tests/hazmat/bindings/test_openssl.py

real    0m0.587s
user    0m0.522s
sys     0m0.070s
```

**Comment by alex** [comment]
The docs you linked to (https://cryptography.io/en/latest/development/getting-started/#development-dependencies) specifically state that, "Working on cryptography requires the installation of a small number of development dependencies in addition to the dependencies for [Installation](https://cryptography.io/en/latest/installation/)." and the installation page describes the rust requirement. Was there something more you were looking for?

Would a specific mention of Rust help?

In terms of the TDD workflow: yes, it's true that nox can slow down TDD cycles. However, it's too burdensome for us to document testing without nox, as it requires people to have correctly set up their environment.
